/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexUSRs.cpp File Reference
#include `CIndexer.h`
#include `CXCursor.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `clang/Frontend/ASTUnit.h`
#include `clang/Index/USRGeneration.h`
#include `clang/Lex/PreprocessingRecord.h`
#include `llvm/ADT/SmallString.h`
#include `llvm/Support/raw_ostream.h`
Functions
CXString clang_getCursorUSR (CXCursor C)
CXString clang_constructUSR_ObjCIvar (const char *name, CXString classUSR)
CXString clang_constructUSR_ObjCMethod (const char *name, unsigned isInstanceMethod, CXString classUSR)
CXString clang_constructUSR_ObjCClass (const char *name)
CXString clang_constructUSR_ObjCProtocol (const char *name)
CXString clang_constructUSR_ObjCCategory (const char *class_name, const char *category_name)
CXString clang_constructUSR_ObjCProperty (const char *property, CXString classUSR)
Function Documentation
clang_constructUSR_ObjCCategory()
CXString clang_constructUSR_ObjCCategory (const char * class_name, const char * category_name)
Definition at line 124 of file CIndexUSRs.cpp.
                                                                    {
  SmallString<128> Buf(getUSRSpacePrefix());
  llvm::raw_svector_ostream OS(Buf);
  generateUSRForObjCCategory(class_name, category_name, OS);
  return cxstring::createDup(OS.str());
}
References clang::cxstring::createDup().
clang_constructUSR_ObjCClass()
CXString clang_constructUSR_ObjCClass (const char * name)
Definition at line 110 of file CIndexUSRs.cpp.
                                                        {
  SmallString<128> Buf(getUSRSpacePrefix());
  llvm::raw_svector_ostream OS(Buf);
  generateUSRForObjCClass(name, OS);
  return cxstring::createDup(OS.str());
}
References clang::cxstring::createDup().
clang_constructUSR_ObjCIvar()
CXString clang_constructUSR_ObjCIvar (const char * name, CXString classUSR)
Definition at line 92 of file CIndexUSRs.cpp.
                                                                          {
  SmallString<128> Buf(getUSRSpacePrefix());
  llvm::raw_svector_ostream OS(Buf);
  OS << extractUSRSuffix(clang_getCString(classUSR));
  generateUSRForObjCIvar(name, OS);
  return cxstring::createDup(OS.str());
}
clang_constructUSR_ObjCMethod()
CXString clang_constructUSR_ObjCMethod (const char * name, unsigned isInstanceMethod, CXString classUSR)
Definition at line 100 of file CIndexUSRs.cpp.
                                                          {
  SmallString<128> Buf(getUSRSpacePrefix());
  llvm::raw_svector_ostream OS(Buf);
  OS << extractUSRSuffix(clang_getCString(classUSR));
  generateUSRForObjCMethod(name, isInstanceMethod, OS);
  return cxstring::createDup(OS.str());
}
clang_constructUSR_ObjCProperty()
CXString clang_constructUSR_ObjCProperty (const char * property, CXString classUSR)
Definition at line 132 of file CIndexUSRs.cpp.
                                                            {
  SmallString<128> Buf(getUSRSpacePrefix());
  llvm::raw_svector_ostream OS(Buf);
  OS << extractUSRSuffix(clang_getCString(classUSR));
  generateUSRForObjCProperty(property, /*isClassProp=*/false, OS);
  return cxstring::createDup(OS.str());
}
clang_constructUSR_ObjCProtocol()
CXString clang_constructUSR_ObjCProtocol (const char * name)
Definition at line 117 of file CIndexUSRs.cpp.
                                                           {
  SmallString<128> Buf(getUSRSpacePrefix());
  llvm::raw_svector_ostream OS(Buf);
  generateUSRForObjCProtocol(name, OS);
  return cxstring::createDup(OS.str());
}
References clang::cxstring::createDup().
clang_getCursorUSR()
CXString clang_getCursorUSR (CXCursor C)
Definition at line 38 of file CIndexUSRs.cpp.
                                        {
  const CXCursorKind &K = clang_getCursorKind(C);
  if (clang_isDeclaration(K)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (!D)
      return cxstring::createEmpty();
    CXTranslationUnit TU = cxcursor::getCursorTU(C);
    if (!TU)
      return cxstring::createEmpty();
    cxstring::CXStringBuf *buf = cxstring::getCXStringBuf(TU);
    if (!buf)
      return cxstring::createEmpty();
    bool Ignore = cxcursor::getDeclCursorUSR(D, buf->Data);
    if (Ignore) {
      buf->dispose();
      return cxstring::createEmpty();
    }
    // Return the C-string, but don't make a copy since it is already in
    // the string buffer.
    buf->Data.push_back('\0');
    return createCXString(buf);
  }
  if (K == CXCursor_MacroDefinition) {
    CXTranslationUnit TU = cxcursor::getCursorTU(C);
    if (!TU)
      return cxstring::createEmpty();
    cxstring::CXStringBuf *buf = cxstring::getCXStringBuf(TU);
    if (!buf)
      return cxstring::createEmpty();
    bool Ignore = generateUSRForMacro(cxcursor::getCursorMacroDefinition(C),
                                      cxtu::getASTUnit(TU)->getSourceManager(),
                                      buf->Data);
    if (Ignore) {
      buf->dispose();
      return cxstring::createEmpty();
    }
    // Return the C-string, but don't make a copy since it is already in
    // the string buffer.
    buf->Data.push_back('\0');
    return createCXString(buf);
  }
  return cxstring::createEmpty();
}
References clang_getCursorKind(), clang_isDeclaration(), clang::cxstring::createEmpty(), clang::cxstring::CXStringBuf::Data, clang::cxstring::CXStringBuf::dispose(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), clang::cxstring::getCXStringBuf(), and clang::cxcursor::getDeclCursorUSR().