/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.cpp File Reference
#include `CIndexDiagnostic.h`
#include `CIndexer.h`
#include `CXTranslationUnit.h`
#include `CXSourceLocation.h`
#include `CXString.h`
#include `clang/Basic/DiagnosticOptions.h`
#include `clang/Frontend/ASTUnit.h`
#include `clang/Frontend/DiagnosticRenderer.h`
#include `llvm/ADT/SmallString.h`
#include `llvm/Support/raw_ostream.h`
Functions
unsigned clang_getNumDiagnostics (CXTranslationUnit Unit)
CXDiagnostic clang_getDiagnostic (CXTranslationUnit Unit, unsigned Index)
CXDiagnosticSet clang_getDiagnosticSetFromTU (CXTranslationUnit Unit)
void clang_disposeDiagnostic (CXDiagnostic Diagnostic)
CXString clang_formatDiagnostic (CXDiagnostic Diagnostic, unsigned Options)
unsigned clang_defaultDiagnosticDisplayOptions ()
enum CXDiagnosticSeverity clang_getDiagnosticSeverity (CXDiagnostic Diag)
CXSourceLocation clang_getDiagnosticLocation (CXDiagnostic Diag)
CXString clang_getDiagnosticSpelling (CXDiagnostic Diag)
CXString clang_getDiagnosticOption (CXDiagnostic Diag, CXString *Disable)
unsigned clang_getDiagnosticCategory (CXDiagnostic Diag)
CXString clang_getDiagnosticCategoryName (unsigned Category)
CXString clang_getDiagnosticCategoryText (CXDiagnostic Diag)
unsigned clang_getDiagnosticNumRanges (CXDiagnostic Diag)
CXSourceRange clang_getDiagnosticRange (CXDiagnostic Diag, unsigned Range)
unsigned clang_getDiagnosticNumFixIts (CXDiagnostic Diag)
CXString clang_getDiagnosticFixIt (CXDiagnostic Diag, unsigned FixIt, CXSourceRange *ReplacementRange)
void clang_disposeDiagnosticSet (CXDiagnosticSet Diags)
CXDiagnostic clang_getDiagnosticInSet (CXDiagnosticSet Diags, unsigned Index)
CXDiagnosticSet clang_getChildDiagnostics (CXDiagnostic Diag)
unsigned clang_getNumDiagnosticsInSet (CXDiagnosticSet Diags)
Function Documentation
clang_defaultDiagnosticDisplayOptions()
unsigned clang_defaultDiagnosticDisplayOptions ()
Definition at line 361 of file CIndexDiagnostic.cpp.
                                                 {
  return CXDiagnostic_DisplaySourceLocation | CXDiagnostic_DisplayColumn |
         CXDiagnostic_DisplayOption;
}
Referenced by clang::cxindex::printDiagsToStderr().
clang_disposeDiagnostic()
void clang_disposeDiagnostic (CXDiagnostic Diagnostic)
Definition at line 236 of file CIndexDiagnostic.cpp.
                                                      {
  // No-op. Kept as a legacy API. CXDiagnostics are now managed
  // by the enclosing CXDiagnosticSet.
}
clang_disposeDiagnosticSet()
void clang_disposeDiagnosticSet (CXDiagnosticSet Diags)
Definition at line 441 of file CIndexDiagnostic.cpp.
                                                       {
  if (CXDiagnosticSetImpl *D = static_cast<CXDiagnosticSetImpl *>(Diags)) {
    if (D->isExternallyManaged())
      delete D;
  }
}
Referenced by PrintDiagnostics().
clang_formatDiagnostic()
CXString clang_formatDiagnostic (CXDiagnostic Diagnostic, unsigned Options)
Definition at line 241 of file CIndexDiagnostic.cpp.
                                                                           {
  if (!Diagnostic)
    return cxstring::createEmpty();
  CXDiagnosticSeverity Severity = clang_getDiagnosticSeverity(Diagnostic);
  SmallString<256> Str;
  llvm::raw_svector_ostream Out(Str);
  
  if (Options & CXDiagnostic_DisplaySourceLocation) {
    // Print source location (file:line), along with optional column
    // and source ranges.
    CXFile File;
    unsigned Line, Column;
    clang_getSpellingLocation(clang_getDiagnosticLocation(Diagnostic),
                              &File, &Line, &Column, nullptr);
    if (File) {
      CXString FName = clang_getFileName(File);
      Out << clang_getCString(FName) << ":" << Line << ":";
      clang_disposeString(FName);
      if (Options & CXDiagnostic_DisplayColumn)
        Out << Column << ":";
      if (Options & CXDiagnostic_DisplaySourceRanges) {
        unsigned N = clang_getDiagnosticNumRanges(Diagnostic);
        bool PrintedRange = false;
        for (unsigned I = 0; I != N; ++I) {
          CXFile StartFile, EndFile;
          CXSourceRange Range = clang_getDiagnosticRange(Diagnostic, I);
          
          unsigned StartLine, StartColumn, EndLine, EndColumn;
          clang_getSpellingLocation(clang_getRangeStart(Range),
                                    &StartFile, &StartLine, &StartColumn,
                                    nullptr);
          clang_getSpellingLocation(clang_getRangeEnd(Range),
                                    &EndFile, &EndLine, &EndColumn, nullptr);
          if (StartFile != EndFile || StartFile != File)
            continue;
          
          Out << "{" << StartLine << ":" << StartColumn << "-"
              << EndLine << ":" << EndColumn << "}";
          PrintedRange = true;
        }
        if (PrintedRange)
          Out << ":";
      }
      
      Out << " ";
    }
  }
  /* Print warning/error/etc. */
  switch (Severity) {
  case CXDiagnostic_Ignored: llvm_unreachable("impossible");
  case CXDiagnostic_Note: Out << "note: "; break;
  case CXDiagnostic_Warning: Out << "warning: "; break;
  case CXDiagnostic_Error: Out << "error: "; break;
  case CXDiagnostic_Fatal: Out << "fatal error: "; break;
  }
  CXString Text = clang_getDiagnosticSpelling(Diagnostic);
  if (clang_getCString(Text))
    Out << clang_getCString(Text);
  else
    Out << "<no diagnostic text>";
  clang_disposeString(Text);
  
  if (Options & (CXDiagnostic_DisplayOption | CXDiagnostic_DisplayCategoryId |
                 CXDiagnostic_DisplayCategoryName)) {
    bool NeedBracket = true;
    bool NeedComma = false;
    if (Options & CXDiagnostic_DisplayOption) {
      CXString OptionName = clang_getDiagnosticOption(Diagnostic, nullptr);
      if (const char *OptionText = clang_getCString(OptionName)) {
        if (OptionText[0]) {
          Out << " [" << OptionText;
          NeedBracket = false;
          NeedComma = true;
        }
      }
      clang_disposeString(OptionName);
    }
    
    if (Options & (CXDiagnostic_DisplayCategoryId |
                   CXDiagnostic_DisplayCategoryName)) {
      if (unsigned CategoryID = clang_getDiagnosticCategory(Diagnostic)) {
        if (Options & CXDiagnostic_DisplayCategoryId) {
          if (NeedBracket)
            Out << " [";
          if (NeedComma)
            Out << ", ";
          Out << CategoryID;
          NeedBracket = false;
          NeedComma = true;
        }
        
        if (Options & CXDiagnostic_DisplayCategoryName) {
          CXString CategoryName = clang_getDiagnosticCategoryText(Diagnostic);
          if (NeedBracket)
            Out << " [";
          if (NeedComma)
            Out << ", ";
          Out << clang_getCString(CategoryName);
          NeedBracket = false;
          NeedComma = true;
          clang_disposeString(CategoryName);
        }
      }
    }
    (void) NeedComma; // Silence dead store warning.
    if (!NeedBracket)
      Out << "]";
  }
  
  return cxstring::createDup(Out.str());
}
Referenced by PrintDiagnostic(), and clang::cxindex::printDiagsToStderr().
clang_getChildDiagnostics()
CXDiagnosticSet clang_getChildDiagnostics (CXDiagnostic Diag)
Definition at line 456 of file CIndexDiagnostic.cpp.
                                                             {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag)) {
    CXDiagnosticSetImpl &ChildDiags = D->getChildDiagnostics();
    return ChildDiags.empty() ? nullptr : (CXDiagnosticSet) &ChildDiags;
  }
  return nullptr;
}
References clang::CXDiagnosticSetImpl::empty().
Referenced by PrintDiagnosticSet().
clang_getDiagnostic()
CXDiagnostic clang_getDiagnostic (CXTranslationUnit Unit, unsigned Index)
Definition at line 209 of file CIndexDiagnostic.cpp.
                                                                         {
  if (cxtu::isNotUsableTU(Unit)) {
    LOG_BAD_TU(Unit);
    return nullptr;
  }
  CXDiagnosticSet D = clang_getDiagnosticSetFromTU(Unit);
  if (!D)
    return nullptr;
  CXDiagnosticSetImpl *Diags = static_cast<CXDiagnosticSetImpl*>(D);
  if (Index >= Diags->getNumDiagnostics())
    return nullptr;
  return Diags->getDiagnostic(Index);
}
References clang_getDiagnosticSetFromTU(), clang::CXDiagnosticSetImpl::getDiagnostic(), clang::CXDiagnosticSetImpl::getNumDiagnostics(), and LOG_BAD_TU.
clang_getDiagnosticCategory()
unsigned clang_getDiagnosticCategory (CXDiagnostic Diag)
Definition at line 394 of file CIndexDiagnostic.cpp.
                                                        {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag))
    return D->getCategory();
  return 0;
}
clang_getDiagnosticCategoryName()
CXString clang_getDiagnosticCategoryName (unsigned Category)
Definition at line 400 of file CIndexDiagnostic.cpp.
                                                            {
  // Kept for backward compatibility.
  return cxstring::createRef(DiagnosticIDs::getCategoryNameFromID(Category));
}
References clang::cxstring::createRef().
clang_getDiagnosticCategoryText()
CXString clang_getDiagnosticCategoryText (CXDiagnostic Diag)
Definition at line 405 of file CIndexDiagnostic.cpp.
                                                            {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag))
    return D->getCategoryText();
  return cxstring::createEmpty();
}
References clang::cxstring::createEmpty().
clang_getDiagnosticFixIt()
CXString clang_getDiagnosticFixIt (CXDiagnostic Diag, unsigned FixIt, CXSourceRange * ReplacementRange)
Definition at line 430 of file CIndexDiagnostic.cpp.
                                                                   {
  CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag);
  if (!D || FixIt >= D->getNumFixIts()) {
    if (ReplacementRange)
      *ReplacementRange = clang_getNullRange();
    return cxstring::createEmpty();
  }
  return D->getFixIt(FixIt, ReplacementRange);
}
References clang_getNullRange(), clang::cxstring::createEmpty(), clang::CXDiagnosticImpl::getFixIt(), and clang::CXDiagnosticImpl::getNumFixIts().
Referenced by PrintDiagnostic().
clang_getDiagnosticInSet()
CXDiagnostic clang_getDiagnosticInSet (CXDiagnosticSet Diags, unsigned Index)
Definition at line 448 of file CIndexDiagnostic.cpp.
                                                      {
  if (CXDiagnosticSetImpl *D = static_cast<CXDiagnosticSetImpl*>(Diags))
    if (Index < D->getNumDiagnostics())
      return D->getDiagnostic(Index);
  return nullptr;
}
Referenced by PrintDiagnosticSet().
clang_getDiagnosticLocation()
CXSourceLocation clang_getDiagnosticLocation (CXDiagnostic Diag)
Definition at line 372 of file CIndexDiagnostic.cpp.
                                                                {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl*>(Diag))
    return D->getLocation();
  return clang_getNullLocation();
}
References clang_getNullLocation().
Referenced by PrintDiagnostic().
clang_getDiagnosticNumFixIts()
unsigned clang_getDiagnosticNumFixIts (CXDiagnostic Diag)
Definition at line 424 of file CIndexDiagnostic.cpp.
                                                         {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag))
    return D->getNumFixIts();
  return 0;
}
Referenced by PrintDiagnostic().
clang_getDiagnosticNumRanges()
unsigned clang_getDiagnosticNumRanges (CXDiagnostic Diag)
Definition at line 411 of file CIndexDiagnostic.cpp.
                                                         {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag))
    return D->getNumRanges();
  return 0;
}
clang_getDiagnosticOption()
CXString clang_getDiagnosticOption (CXDiagnostic Diag, CXString * Disable)
Definition at line 384 of file CIndexDiagnostic.cpp.
                                                                         {
  if (Disable)
    *Disable = cxstring::createEmpty();
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag))
    return D->getDiagnosticOption(Disable);
  return cxstring::createEmpty();
}
References clang::cxstring::createEmpty().
clang_getDiagnosticRange()
CXSourceRange clang_getDiagnosticRange (CXDiagnostic Diag, unsigned Range)
Definition at line 417 of file CIndexDiagnostic.cpp.
                                                                          {
  CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag);
  if (!D || Range >= D->getNumRanges())
    return clang_getNullRange();
  return D->getRange(Range);
}
References clang_getNullRange(), clang::CXDiagnosticImpl::getNumRanges(), and clang::CXDiagnosticImpl::getRange().
clang_getDiagnosticSetFromTU()
CXDiagnosticSet clang_getDiagnosticSetFromTU (CXTranslationUnit Unit)
Definition at line 226 of file CIndexDiagnostic.cpp.
                                                                     {
  if (cxtu::isNotUsableTU(Unit)) {
    LOG_BAD_TU(Unit);
    return nullptr;
  }
  if (!cxtu::getASTUnit(Unit))
    return nullptr;
  return static_cast<CXDiagnostic>(lazyCreateDiags(Unit));
}
References clang::cxdiag::lazyCreateDiags(), and LOG_BAD_TU.
Referenced by clang_getDiagnostic(), and PrintDiagnostics().
clang_getDiagnosticSeverity()
enum CXDiagnosticSeverity clang_getDiagnosticSeverity (CXDiagnostic Diag)
Definition at line 361 of file CIndexDiagnostic.cpp.
                                                                         {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl*>(Diag))
    return D->getSeverity();
  return CXDiagnostic_Ignored;
}
Referenced by PrintDiagnostic().
clang_getDiagnosticSpelling()
CXString clang_getDiagnosticSpelling (CXDiagnostic Diag)
Definition at line 378 of file CIndexDiagnostic.cpp.
                                                        {
  if (CXDiagnosticImpl *D = static_cast<CXDiagnosticImpl *>(Diag))
    return D->getSpelling();
  return cxstring::createEmpty();
}
References clang::cxstring::createEmpty().
clang_getNumDiagnostics()
unsigned clang_getNumDiagnostics (CXTranslationUnit Unit)
Definition at line 199 of file CIndexDiagnostic.cpp.
                                                         {
  if (cxtu::isNotUsableTU(Unit)) {
    LOG_BAD_TU(Unit);
    return 0;
  }
  if (!cxtu::getASTUnit(Unit))
    return 0;
  return lazyCreateDiags(Unit, /*checkIfChanged=*/true)->getNumDiagnostics();
}
References clang::CXDiagnosticSetImpl::getNumDiagnostics(), clang::cxdiag::lazyCreateDiags(), and LOG_BAD_TU.
clang_getNumDiagnosticsInSet()
unsigned clang_getNumDiagnosticsInSet (CXDiagnosticSet Diags)
Definition at line 464 of file CIndexDiagnostic.cpp.
                                                             {
  if (CXDiagnosticSetImpl *D = static_cast<CXDiagnosticSetImpl*>(Diags))
    return D->getNumDiagnostics();
  return 0;
}
Referenced by PrintDiagnosticSet().