/Users/maximilian/clang-llvm/clang/tools/libclang/CIndex.cpp File Reference
#include `CIndexDiagnostic.h`
#include `CIndexer.h`
#include `CLog.h`
#include `CXCursor.h`
#include `CXSourceLocation.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `CXType.h`
#include `CursorVisitor.h`
#include `clang-c/FatalErrorHandler.h`
#include `clang/AST/Attr.h`
#include `clang/AST/DeclObjCCommon.h`
#include `clang/AST/Mangle.h`
#include `clang/AST/OpenMPClause.h`
#include `clang/AST/StmtVisitor.h`
#include `clang/Basic/Diagnostic.h`
#include `clang/Basic/DiagnosticCategories.h`
#include `clang/Basic/DiagnosticIDs.h`
#include `clang/Basic/Stack.h`
#include `clang/Basic/TargetInfo.h`
#include `clang/Basic/Version.h`
#include `clang/Frontend/ASTUnit.h`
#include `clang/Frontend/CompilerInstance.h`
#include `clang/Index/CommentToXML.h`
#include `clang/Lex/HeaderSearch.h`
#include `clang/Lex/Lexer.h`
#include `clang/Lex/PreprocessingRecord.h`
#include `clang/Lex/Preprocessor.h`
#include `llvm/ADT/Optional.h`
#include `llvm/ADT/STLExtras.h`
#include `llvm/ADT/StringSwitch.h`
#include `llvm/Config/llvm-config.h`
#include `llvm/Support/Compiler.h`
#include `llvm/Support/CrashRecoveryContext.h`
#include `llvm/Support/Format.h`
#include `llvm/Support/ManagedStatic.h`
#include `llvm/Support/MemoryBuffer.h`
#include `llvm/Support/Program.h`
#include `llvm/Support/SaveAndRestore.h`
#include `llvm/Support/Signals.h`
#include `llvm/Support/TargetSelect.h`
#include `llvm/Support/Threading.h`
#include `llvm/Support/Timer.h`
#include `llvm/Support/raw_ostream.h`
#include <mutex>
#include `clang/Basic/OpenCLImageTypes.def`
#include `clang/Basic/OpenCLExtensionTypes.def`
#include `clang/Basic/AArch64SVEACLETypes.def`
#include `clang/Basic/PPCTypes.def`
#include `clang/Basic/RISCVVTypes.def`
#include `clang/AST/BuiltinTypes.def`
#include `llvm/Frontend/OpenMP/OMP.inc`
Classes
struct ExprEvalResult
struct _CXChildVisitResult
struct GetCursorData
Namespaces
 clang
-rename
Macros
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Id:
#define EXT_OPAQUE_TYPE(ExtTYpe, Id, Ext) case BuiltinType::Id:
#define SVE_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define PPC_VECTOR_TYPE(Name, Id, Size) case BuiltinType::Id:
#define RVV_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define BUILTIN_TYPE(Id, SingletonId)
#define SIGNED_TYPE(Id, SingletonId) case BuiltinType::Id:
#define UNSIGNED_TYPE(Id, SingletonId) case BuiltinType::Id:
#define FLOATING_TYPE(Id, SingletonId) case BuiltinType::Id:
#define PLACEHOLDER_TYPE(Id, SingletonId) case BuiltinType::Id:
#define DEFAULT_TYPELOC_IMPL(CLASS, PARENT)
#define DEF_JOB(NAME, DATA, KIND)
#define GEN_CLANG_CLAUSE_CLASS
#define CLAUSE_CLASS(Enum, Str, Class) void Visit##Class(const Class *C);
#define SET_CXOBJCPROP_ATTR(A)
Typedefs
typedef struct _CXChildVisitResult * CXCursorVisitorBlock
typedef std::vector< CXTUResourceUsageEntry > MemUsageEntries
Functions
CXIndex clang_createIndex (int excludeDeclarationsFromPCH, int displayDiagnostics)
void clang_disposeIndex (CXIndex CIdx)
void clang_CXIndex_setGlobalOptions (CXIndex CIdx, unsigned options)
unsigned clang_CXIndex_getGlobalOptions (CXIndex CIdx)
void clang_CXIndex_setInvocationEmissionPathOption (CXIndex CIdx, const char *Path)
void clang_toggleCrashRecovery (unsigned isEnabled)
CXTranslationUnit clang_createTranslationUnit (CXIndex CIdx, const char *ast_filename)
enum CXErrorCode clang_createTranslationUnit2 (CXIndex CIdx, const char *ast_filename, CXTranslationUnit *out_TU)
unsigned clang_defaultEditingTranslationUnitOptions ()
CXTranslationUnit clang_createTranslationUnitFromSourceFile (CXIndex CIdx, const char *source_filename, int num_command_line_args, const char *const *command_line_args, unsigned num_unsaved_files, struct CXUnsavedFile *unsaved_files)
CXTranslationUnit clang_parseTranslationUnit (CXIndex CIdx, const char *source_filename, const char *const *command_line_args, int num_command_line_args, struct CXUnsavedFile *unsaved_files, unsigned num_unsaved_files, unsigned options)
enum CXErrorCode clang_parseTranslationUnit2 (CXIndex CIdx, const char *source_filename, const char *const *command_line_args, int num_command_line_args, struct CXUnsavedFile *unsaved_files, unsigned num_unsaved_files, unsigned options, CXTranslationUnit *out_TU)
enum CXErrorCode clang_parseTranslationUnit2FullArgv (CXIndex CIdx, const char *source_filename, const char *const *command_line_args, int num_command_line_args, struct CXUnsavedFile *unsaved_files, unsigned num_unsaved_files, unsigned options, CXTranslationUnit *out_TU)
CXString clang_Type_getObjCEncoding (CXType CT)
unsigned clang_Cursor_isMacroFunctionLike (CXCursor C)
unsigned clang_Cursor_isMacroBuiltin (CXCursor C)
unsigned clang_Cursor_isFunctionInlined (CXCursor C)
void clang_EvalResult_dispose (CXEvalResult E)
CXEvalResultKind clang_EvalResult_getKind (CXEvalResult E)
int clang_EvalResult_getAsInt (CXEvalResult E)
long long clang_EvalResult_getAsLongLong (CXEvalResult E)
unsigned clang_EvalResult_isUnsignedInt (CXEvalResult E)
unsigned long long clang_EvalResult_getAsUnsigned (CXEvalResult E)
double clang_EvalResult_getAsDouble (CXEvalResult E)
const char * clang_EvalResult_getAsStr (CXEvalResult E)
CXEvalResult clang_Cursor_Evaluate (CXCursor C)
unsigned clang_Cursor_hasAttrs (CXCursor C)
unsigned clang_defaultSaveOptions (CXTranslationUnit TU)
int clang_saveTranslationUnit (CXTranslationUnit TU, const char *FileName, unsigned options)
void clang_disposeTranslationUnit (CXTranslationUnit CTUnit)
unsigned clang_suspendTranslationUnit (CXTranslationUnit CTUnit)
unsigned clang_defaultReparseOptions (CXTranslationUnit TU)
int clang_reparseTranslationUnit (CXTranslationUnit TU, unsigned num_unsaved_files, struct CXUnsavedFile *unsaved_files, unsigned options)
CXString clang_getTranslationUnitSpelling (CXTranslationUnit CTUnit)
CXCursor clang_getTranslationUnitCursor (CXTranslationUnit TU)
CXTargetInfo clang_getTranslationUnitTargetInfo (CXTranslationUnit CTUnit)
CXString clang_TargetInfo_getTriple (CXTargetInfo TargetInfo)
int clang_TargetInfo_getPointerWidth (CXTargetInfo TargetInfo)
void clang_TargetInfo_dispose (CXTargetInfo TargetInfo)
CXString clang_getFileName (CXFile SFile)
time_t clang_getFileTime (CXFile SFile)
CXFile clang_getFile (CXTranslationUnit TU, const char *file_name)
const char * clang_getFileContents (CXTranslationUnit TU, CXFile file, size_t *size)
unsigned clang_isFileMultipleIncludeGuarded (CXTranslationUnit TU, CXFile file)
int clang_getFileUniqueID (CXFile file, CXFileUniqueID *outID)
int clang_File_isEqual (CXFile file1, CXFile file2)
CXString clang_File_tryGetRealPathName (CXFile SFile)
unsigned clang_visitChildren (CXCursor parent, CXCursorVisitor visitor, CXClientData client_data)
unsigned clang_visitChildrenWithBlock (CXCursor parent, CXCursorVisitorBlock block)
CXString clang_getCursorSpelling (CXCursor C)
CXSourceRange clang_Cursor_getSpellingNameRange (CXCursor C, unsigned pieceIndex, unsigned options)
CXString clang_Cursor_getMangling (CXCursor C)
CXStringSet * clang_Cursor_getCXXManglings (CXCursor C)
CXStringSet * clang_Cursor_getObjCManglings (CXCursor C)
CXPrintingPolicy clang_getCursorPrintingPolicy (CXCursor C)
void clang_PrintingPolicy_dispose (CXPrintingPolicy Policy)
unsigned clang_PrintingPolicy_getProperty (CXPrintingPolicy Policy, enum CXPrintingPolicyProperty Property)
void clang_PrintingPolicy_setProperty (CXPrintingPolicy Policy, enum CXPrintingPolicyProperty Property, unsigned Value)
CXString clang_getCursorPrettyPrinted (CXCursor C, CXPrintingPolicy cxPolicy)
CXString clang_getCursorDisplayName (CXCursor C)
CXString clang_getCursorKindSpelling (enum CXCursorKind Kind)
CXCursor clang_getCursor (CXTranslationUnit TU, CXSourceLocation Loc)
CXCursor clang_getNullCursor (void)
unsigned clang_equalCursors (CXCursor X, CXCursor Y)
unsigned clang_hashCursor (CXCursor C)
unsigned clang_isInvalid (enum CXCursorKind K)
unsigned clang_isDeclaration (enum CXCursorKind K)
unsigned clang_isInvalidDeclaration (CXCursor C)
unsigned clang_isReference (enum CXCursorKind K)
unsigned clang_isExpression (enum CXCursorKind K)
unsigned clang_isStatement (enum CXCursorKind K)
unsigned clang_isAttribute (enum CXCursorKind K)
unsigned clang_isTranslationUnit (enum CXCursorKind K)
unsigned clang_isPreprocessing (enum CXCursorKind K)
unsigned clang_isUnexposed (enum CXCursorKind K)
CXCursorKind clang_getCursorKind (CXCursor C)
CXSourceLocation clang_getCursorLocation (CXCursor C)
CXSourceRange clang_getCursorExtent (CXCursor C)
CXCursor clang_getCursorReferenced (CXCursor C)
CXCursor clang_getCursorDefinition (CXCursor C)
unsigned clang_isCursorDefinition (CXCursor C)
CXCursor clang_getCanonicalCursor (CXCursor C)
int clang_Cursor_getObjCSelectorIndex (CXCursor cursor)
unsigned clang_getNumOverloadedDecls (CXCursor C)
CXCursor clang_getOverloadedDecl (CXCursor cursor, unsigned index)
void clang_getDefinitionSpellingAndExtent (CXCursor C, const char **startBuf, const char **endBuf, unsigned *startLine, unsigned *startColumn, unsigned *endLine, unsigned *endColumn)
CXSourceRange clang_getCursorReferenceNameRange (CXCursor C, unsigned NameFlags, unsigned PieceIndex)
void clang_enableStackTraces (void)
void clang_executeOnThread (void(*fn)(void *), void *user_data, unsigned stack_size)
CXTokenKind clang_getTokenKind (CXToken CXTok)
CXString clang_getTokenSpelling (CXTranslationUnit TU, CXToken CXTok)
CXSourceLocation clang_getTokenLocation (CXTranslationUnit TU, CXToken CXTok)
CXSourceRange clang_getTokenExtent (CXTranslationUnit TU, CXToken CXTok)
CXToken * clang_getToken (CXTranslationUnit TU, CXSourceLocation Location)
void clang_tokenize (CXTranslationUnit TU, CXSourceRange Range, CXToken **Tokens, unsigned *NumTokens)
void clang_disposeTokens (CXTranslationUnit TU, CXToken *Tokens, unsigned NumTokens)
const CXXOperatorCallExpr * GetSubscriptOrCallOperator (CXCursor Cursor)
void clang_annotateTokens (CXTranslationUnit TU, CXToken *Tokens, unsigned NumTokens, CXCursor *Cursors)
CXLinkageKind clang_getCursorLinkage (CXCursor cursor)
CXVisibilityKind clang_getCursorVisibility (CXCursor cursor)
enum CXAvailabilityKind clang_getCursorAvailability (CXCursor cursor)
int clang_getCursorPlatformAvailability (CXCursor cursor, int *always_deprecated, CXString *deprecated_message, int *always_unavailable, CXString *unavailable_message, CXPlatformAvailability *availability, int availability_size)
void clang_disposeCXPlatformAvailability (CXPlatformAvailability *availability)
CXLanguageKind clang_getCursorLanguage (CXCursor cursor)
CXTLSKind clang_getCursorTLSKind (CXCursor cursor)
enum CX_StorageClass clang_Cursor_getStorageClass (CXCursor C)
CXCursor clang_getCursorSemanticParent (CXCursor cursor)
CXCursor clang_getCursorLexicalParent (CXCursor cursor)
CXFile clang_getIncludedFile (CXCursor cursor)
unsigned clang_Cursor_getObjCPropertyAttributes (CXCursor C, unsigned reserved)
CXString clang_Cursor_getObjCPropertyGetterName (CXCursor C)
CXString clang_Cursor_getObjCPropertySetterName (CXCursor C)
unsigned clang_Cursor_getObjCDeclQualifiers (CXCursor C)
unsigned clang_Cursor_isObjCOptional (CXCursor C)
unsigned clang_Cursor_isVariadic (CXCursor C)
unsigned clang_Cursor_isExternalSymbol (CXCursor C, CXString *language, CXString *definedIn, unsigned *isGenerated)
CXSourceRange clang_Cursor_getCommentRange (CXCursor C)
CXString clang_Cursor_getRawCommentText (CXCursor C)
CXString clang_Cursor_getBriefCommentText (CXCursor C)
CXModule clang_Cursor_getModule (CXCursor C)
CXModule clang_getModuleForFile (CXTranslationUnit TU, CXFile File)
CXFile clang_Module_getASTFile (CXModule CXMod)
CXModule clang_Module_getParent (CXModule CXMod)
CXString clang_Module_getName (CXModule CXMod)
CXString clang_Module_getFullName (CXModule CXMod)
int clang_Module_isSystem (CXModule CXMod)
unsigned clang_Module_getNumTopLevelHeaders (CXTranslationUnit TU, CXModule CXMod)
CXFile clang_Module_getTopLevelHeader (CXTranslationUnit TU, CXModule CXMod, unsigned Index)
unsigned clang_CXXConstructor_isDefaultConstructor (CXCursor C)
unsigned clang_CXXConstructor_isCopyConstructor (CXCursor C)
unsigned clang_CXXConstructor_isMoveConstructor (CXCursor C)
unsigned clang_CXXConstructor_isConvertingConstructor (CXCursor C)
unsigned clang_CXXField_isMutable (CXCursor C)
unsigned clang_CXXMethod_isPureVirtual (CXCursor C)
unsigned clang_CXXMethod_isConst (CXCursor C)
unsigned clang_CXXMethod_isDefaulted (CXCursor C)
unsigned clang_CXXMethod_isStatic (CXCursor C)
unsigned clang_CXXMethod_isVirtual (CXCursor C)
unsigned clang_CXXRecord_isAbstract (CXCursor C)
unsigned clang_EnumDecl_isScoped (CXCursor C)
CXType clang_getIBOutletCollectionType (CXCursor C)
const char * clang_getTUResourceUsageName (CXTUResourceUsageKind kind)
CXTUResourceUsage clang_getCXTUResourceUsage (CXTranslationUnit TU)
void clang_disposeCXTUResourceUsage (CXTUResourceUsage usage)
CXSourceRangeList * clang_getSkippedRanges (CXTranslationUnit TU, CXFile file)
CXSourceRangeList * clang_getAllSkippedRanges (CXTranslationUnit TU)
void clang_disposeSourceRangeList (CXSourceRangeList *ranges)
CXCursor clang_Cursor_getVarDeclInitializer (CXCursor cursor)
int clang_Cursor_hasVarDeclGlobalStorage (CXCursor cursor)
int clang_Cursor_hasVarDeclExternalStorage (CXCursor cursor)
bool clang::RunSafely (llvm::CrashRecoveryContext &CRC, llvm::function_ref< void()> Fn, unsigned Size)
unsigned clang::GetSafetyThreadStackSize ()
Return the current size to request for `safety`.
void clang::SetSafetyThreadStackSize (unsigned Value)
CXString clang_getClangVersion ()
Macro Definition Documentation
BUILTIN_TYPE
#define BUILTIN_TYPE(Id, SingletonId)
CLAUSE_CLASS
#define CLAUSE_CLASS(Enum, Str, Class) void Visit##Class(const Class *C);
Definition at line 2183 of file CIndex.cpp.
DEF_JOB
#define DEF_JOB(NAME, DATA, KIND)
Value:
  class NAME : public VisitorJob { \
  public: \
    NAME(const DATA *d, CXCursor parent) \
        : VisitorJob(parent, VisitorJob::KIND, d) {} \
    static bool classof(const VisitorJob *VJ) { \
      return VJ->getKind() == KIND; \
    } \
    const DATA *get() const { return static_cast<const DATA *>(data[0]); } \
  };
Definition at line 1851 of file CIndex.cpp.
DEFAULT_TYPELOC_IMPL
#define DEFAULT_TYPELOC_IMPL(CLASS, PARENT)
Value:
  bool CursorVisitor::Visit##CLASS##TypeLoc(CLASS##TypeLoc TL) { \
    return Visit##PARENT##Loc(TL); \
  }
Definition at line 1793 of file CIndex.cpp.
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE(ExtTYpe, Id, Ext) case BuiltinType::Id:
FLOATING_TYPE
#define FLOATING_TYPE(Id, SingletonId) case BuiltinType::Id:
GEN_CLANG_CLAUSE_CLASS
#define GEN_CLANG_CLAUSE_CLASS
Definition at line 2182 of file CIndex.cpp.
IMAGE_TYPE
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Id:
PLACEHOLDER_TYPE
#define PLACEHOLDER_TYPE(Id, SingletonId) case BuiltinType::Id:
PPC_VECTOR_TYPE
#define PPC_VECTOR_TYPE(Name, Id, Size) case BuiltinType::Id:
RVV_TYPE
#define RVV_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
SET_CXOBJCPROP_ATTR
#define SET_CXOBJCPROP_ATTR(A)
Value:
  if (Attr & ObjCPropertyAttribute::kind_##A) \
  Result |= CXObjCPropertyAttr_##A
SIGNED_TYPE
#define SIGNED_TYPE(Id, SingletonId) case BuiltinType::Id:
SVE_TYPE
#define SVE_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
UNSIGNED_TYPE
#define UNSIGNED_TYPE(Id, SingletonId) case BuiltinType::Id:
Typedef Documentation
CXCursorVisitorBlock
typedef struct _CXChildVisitResult * CXCursorVisitorBlock
MemUsageEntries
typedef std::vector<CXTUResourceUsageEntry> MemUsageEntries
Definition at line 8678 of file CIndex.cpp.
Function Documentation
clang_annotateTokens()
void clang_annotateTokens (CXTranslationUnit TU, CXToken * Tokens, unsigned NumTokens, CXCursor * Cursors)
Definition at line 7815 of file CIndex.cpp.
                                                                 {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return;
  }
  if (NumTokens == 0 || !Tokens || !Cursors) {
    LOG_FUNC_SECTION { *Log << "<null input>"; }
    return;
  }
  LOG_FUNC_SECTION {
    *Log << TU << ' ';
    CXSourceLocation bloc = clang_getTokenLocation(TU, Tokens[0]);
    CXSourceLocation eloc = clang_getTokenLocation(TU, Tokens[NumTokens - 1]);
    *Log << clang_getRange(bloc, eloc);
  }
  // Any token we don't specifically annotate will have a NULL cursor.
  CXCursor C = clang_getNullCursor();
  for (unsigned I = 0; I != NumTokens; ++I)
    Cursors[I] = C;
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  if (!CXXUnit)
    return;
  ASTUnit::ConcurrencyCheck Check(*CXXUnit);
  auto AnnotateTokensImpl = [=]() {
    clang_annotateTokensImpl(TU, CXXUnit, Tokens, NumTokens, Cursors);
  };
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, AnnotateTokensImpl, GetSafetyThreadStackSize() * 2)) {
    fprintf(stderr, "libclang: crash detected while annotating tokens\n");
  }
}
clang_createIndex()
CXIndex clang_createIndex (int excludeDeclarationsFromPCH, int displayDiagnostics)
Definition at line 3436 of file CIndex.cpp.
                                                  {
  // We use crash recovery to make some of our APIs more reliable, implicitly
  // enable it.
  if (!getenv("LIBCLANG_DISABLE_CRASH_RECOVERY"))
    llvm::CrashRecoveryContext::Enable();
  // Look through the managed static to trigger construction of the managed
  // static which registers our fatal error handler. This ensures it is only
  // registered once.
  (void)*RegisterFatalErrorHandlerOnce;
  // Initialize targets for clang module support.
  llvm::InitializeAllTargets();
  llvm::InitializeAllTargetMCs();
  llvm::InitializeAllAsmPrinters();
  llvm::InitializeAllAsmParsers();
  CIndexer *CIdxr = new CIndexer();
  if (excludeDeclarationsFromPCH)
    CIdxr->setOnlyLocalDecls();
  if (displayDiagnostics)
    CIdxr->setDisplayDiagnostics();
  if (getenv("LIBCLANG_BGPRIO_INDEX"))
    CIdxr->setCXGlobalOptFlags(CIdxr->getCXGlobalOptFlags() |
                               CXGlobalOpt_ThreadBackgroundPriorityForIndexing);
  if (getenv("LIBCLANG_BGPRIO_EDIT"))
    CIdxr->setCXGlobalOptFlags(CIdxr->getCXGlobalOptFlags() |
                               CXGlobalOpt_ThreadBackgroundPriorityForEditing);
  return CIdxr;
}
Referenced by perform_test_load_source(), perform_test_load_tu(), perform_test_reparse_source(), and write_pch_file().
clang_createTranslationUnit()
CXTranslationUnit clang_createTranslationUnit (CXIndex CIdx, const char * ast_filename)
Definition at line 3500 of file CIndex.cpp.
                                                                        {
  CXTranslationUnit TU;
  enum CXErrorCode Result =
      clang_createTranslationUnit2(CIdx, ast_filename, &TU);
  (void)Result;
  assert((TU && Result == CXError_Success) ||
         (!TU && Result != CXError_Success));
  return TU;
}
References clang_createTranslationUnit2().
Referenced by clang::CIndexer::getClangResourcesPath().
clang_createTranslationUnit2()
enum CXErrorCode clang_createTranslationUnit2 (CXIndex CIdx, const char * ast_filename, CXTranslationUnit * out_TU)
Definition at line 3500 of file CIndex.cpp.
                                                                         {
  if (out_TU)
    *out_TU = nullptr;
  if (!CIdx || !ast_filename || !out_TU)
    return CXError_InvalidArguments;
  LOG_FUNC_SECTION { *Log << ast_filename; }
  CIndexer *CXXIdx = static_cast<CIndexer *>(CIdx);
  FileSystemOptions FileSystemOpts;
  IntrusiveRefCntPtr<DiagnosticsEngine> Diags =
      CompilerInstance::createDiagnostics(new DiagnosticOptions());
  std::unique_ptr<ASTUnit> AU = ASTUnit::LoadFromASTFile(
      ast_filename, CXXIdx->getPCHContainerOperations()->getRawReader(),
      ASTUnit::LoadEverything, Diags, FileSystemOpts, /*UseDebugInfo=*/false,
      CXXIdx->getOnlyLocalDecls(), CaptureDiagsKind::All,
      /*AllowASTWithCompilerErrors=*/true,
      /*UserFilesAreVolatile=*/true);
  *out_TU = MakeCXTranslationUnit(CXXIdx, std::move(AU));
  return *out_TU ? CXError_Success : CXError_Failure;
}
Referenced by clang_createTranslationUnit().
clang_createTranslationUnitFromSourceFile()
CXTranslationUnit clang_createTranslationUnitFromSourceFile (CXIndex CIdx, const char * source_filename, int num_command_line_args, const char *const * command_line_args, unsigned num_unsaved_files, struct CXUnsavedFile * unsaved_files)
Definition at line 3542 of file CIndex.cpp.
                                         {
  unsigned Options = CXTranslationUnit_DetailedPreprocessingRecord;
  return clang_parseTranslationUnit(CIdx, source_filename, command_line_args,
                                    num_command_line_args, unsaved_files,
                                    num_unsaved_files, Options);
}
clang_Cursor_Evaluate()
CXEvalResult clang_Cursor_Evaluate (CXCursor C)
Definition at line 4118 of file CIndex.cpp.
                                               {
  const Expr *E = nullptr;
  if (clang_getCursorKind(C) == CXCursor_CompoundStmt)
    E = evaluateCompoundStmtExpr(cast<CompoundStmt>(getCursorStmt(C)));
  else if (clang_isDeclaration(C.kind))
    E = evaluateDeclExpr(getCursorDecl(C));
  else if (clang_isExpression(C.kind))
    E = getCursorExpr(C);
  if (E)
    return const_cast<CXEvalResult>(
        reinterpret_cast<const void *>(evaluateExpr(const_cast<Expr *>(E), C)));
  return nullptr;
}
References clang_getCursorKind().
clang_Cursor_getBriefCommentText()
CXString clang_Cursor_getBriefCommentText (CXCursor C)
Definition at line 8421 of file CIndex.cpp.
                                                      {
  if (!clang_isDeclaration(C.kind))
    return cxstring::createNull();
  const Decl *D = getCursorDecl(C);
  const ASTContext &Context = getCursorContext(C);
  const RawComment *RC = Context.getRawCommentForAnyRedecl(D);
  if (RC) {
    StringRef BriefText = RC->getBriefText(Context);
    // Don't duplicate the string because RawComment ensures that this memory
    // will not go away.
    return cxstring::createRef(BriefText);
  }
  return cxstring::createNull();
}
References clang_isDeclaration(), clang::cxstring::createNull(), clang::cxstring::createRef(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getCommentRange()
CXSourceRange clang_Cursor_getCommentRange (CXCursor C)
Definition at line 8393 of file CIndex.cpp.
                                                       {
  if (!clang_isDeclaration(C.kind))
    return clang_getNullRange();
  const Decl *D = getCursorDecl(C);
  ASTContext &Context = getCursorContext(C);
  const RawComment *RC = Context.getRawCommentForAnyRedecl(D);
  if (!RC)
    return clang_getNullRange();
  return cxloc::translateSourceRange(Context, RC->getSourceRange());
}
References clang_getNullRange(), clang_isDeclaration(), clang::cxcursor::getCursorContext(), clang::cxcursor::getCursorDecl(), and clang::cxloc::translateSourceRange().
clang_Cursor_getCXXManglings()
CXStringSet* clang_Cursor_getCXXManglings (CXCursor C)
Definition at line 4903 of file CIndex.cpp.
                                                      {
  if (clang_isInvalid(C.kind) || !clang_isDeclaration(C.kind))
    return nullptr;
  const Decl *D = getCursorDecl(C);
  if (!(isa<CXXRecordDecl>(D) || isa<CXXMethodDecl>(D)))
    return nullptr;
  ASTContext &Ctx = D->getASTContext();
  ASTNameGenerator ASTNameGen(Ctx);
  std::vector<std::string> Manglings = ASTNameGen.getAllManglings(D);
  return cxstring::createSet(Manglings);
}
References clang_isDeclaration(), clang_isInvalid(), clang::cxstring::createSet(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getMangling()
CXString clang_Cursor_getMangling (CXCursor C)
Definition at line 4889 of file CIndex.cpp.
                                              {
  if (clang_isInvalid(C.kind) || !clang_isDeclaration(C.kind))
    return cxstring::createEmpty();
  // Mangling only works for functions and variables.
  const Decl *D = getCursorDecl(C);
  if (!D || !(isa<FunctionDecl>(D) || isa<VarDecl>(D)))
    return cxstring::createEmpty();
  ASTContext &Ctx = D->getASTContext();
  ASTNameGenerator ASTNameGen(Ctx);
  return cxstring::createDup(ASTNameGen.getName(D));
}
References clang_isDeclaration(), clang_isInvalid(), clang::cxstring::createDup(), clang::cxstring::createEmpty(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getModule()
CXModule clang_Cursor_getModule (CXCursor C)
Definition at line 8440 of file CIndex.cpp.
                                            {
  if (C.kind == CXCursor_ModuleImportDecl) {
    if (const ImportDecl *ImportD =
            dyn_cast_or_null<ImportDecl>(getCursorDecl(C)))
      return ImportD->getImportedModule();
  }
  return nullptr;
}
References clang::cxcursor::getCursorDecl().
clang_Cursor_getObjCDeclQualifiers()
unsigned clang_Cursor_getObjCDeclQualifiers (CXCursor C)
Definition at line 8317 of file CIndex.cpp.
                                                        {
  if (!clang_isDeclaration(C.kind))
    return CXObjCDeclQualifier_None;
  Decl::ObjCDeclQualifier QT = Decl::OBJC_TQ_None;
  const Decl *D = getCursorDecl(C);
  if (const ObjCMethodDecl *MD = dyn_cast<ObjCMethodDecl>(D))
    QT = MD->getObjCDeclQualifier();
  else if (const ParmVarDecl *PD = dyn_cast<ParmVarDecl>(D))
    QT = PD->getObjCDeclQualifier();
  if (QT == Decl::OBJC_TQ_None)
    return CXObjCDeclQualifier_None;
  unsigned Result = CXObjCDeclQualifier_None;
  if (QT & Decl::OBJC_TQ_In)
    Result |= CXObjCDeclQualifier_In;
  if (QT & Decl::OBJC_TQ_Inout)
    Result |= CXObjCDeclQualifier_Inout;
  if (QT & Decl::OBJC_TQ_Out)
    Result |= CXObjCDeclQualifier_Out;
  if (QT & Decl::OBJC_TQ_Bycopy)
    Result |= CXObjCDeclQualifier_Bycopy;
  if (QT & Decl::OBJC_TQ_Byref)
    Result |= CXObjCDeclQualifier_Byref;
  if (QT & Decl::OBJC_TQ_Oneway)
    Result |= CXObjCDeclQualifier_Oneway;
  return Result;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getObjCManglings()
CXStringSet* clang_Cursor_getObjCManglings (CXCursor C)
Definition at line 4917 of file CIndex.cpp.
                                                       {
  if (clang_isInvalid(C.kind) || !clang_isDeclaration(C.kind))
    return nullptr;
  const Decl *D = getCursorDecl(C);
  if (!(isa<ObjCInterfaceDecl>(D) || isa<ObjCImplementationDecl>(D)))
    return nullptr;
  ASTContext &Ctx = D->getASTContext();
  ASTNameGenerator ASTNameGen(Ctx);
  std::vector<std::string> Manglings = ASTNameGen.getAllManglings(D);
  return cxstring::createSet(Manglings);
}
References clang_isDeclaration(), clang_isInvalid(), clang::cxstring::createSet(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getObjCPropertyAttributes()
unsigned clang_Cursor_getObjCPropertyAttributes (CXCursor C, unsigned reserved)
Definition at line 8264 of file CIndex.cpp.
                                                                               {
  if (C.kind != CXCursor_ObjCPropertyDecl)
    return CXObjCPropertyAttr_noattr;
  unsigned Result = CXObjCPropertyAttr_noattr;
  const ObjCPropertyDecl *PD = dyn_cast<ObjCPropertyDecl>(getCursorDecl(C));
  ObjCPropertyAttribute::Kind Attr = PD->getPropertyAttributesAsWritten();
#define SET_CXOBJCPROP_ATTR(A) \
  if (Attr & ObjCPropertyAttribute::kind_##A) \
  Result |= CXObjCPropertyAttr_##A
  SET_CXOBJCPROP_ATTR(readonly);
  SET_CXOBJCPROP_ATTR(getter);
  SET_CXOBJCPROP_ATTR(assign);
  SET_CXOBJCPROP_ATTR(readwrite);
  SET_CXOBJCPROP_ATTR(retain);
  SET_CXOBJCPROP_ATTR(copy);
  SET_CXOBJCPROP_ATTR(nonatomic);
  SET_CXOBJCPROP_ATTR(setter);
  SET_CXOBJCPROP_ATTR(atomic);
  SET_CXOBJCPROP_ATTR(weak);
  SET_CXOBJCPROP_ATTR(strong);
  SET_CXOBJCPROP_ATTR(unsafe_unretained);
  SET_CXOBJCPROP_ATTR(class);
#undef SET_CXOBJCPROP_ATTR
  return Result;
}
References clang::cxcursor::getCursorDecl(), and SET_CXOBJCPROP_ATTR.
clang_Cursor_getObjCPropertyGetterName()
CXString clang_Cursor_getObjCPropertyGetterName (CXCursor C)
Definition at line 8293 of file CIndex.cpp.
                                                            {
  if (C.kind != CXCursor_ObjCPropertyDecl)
    return cxstring::createNull();
  const ObjCPropertyDecl *PD = dyn_cast<ObjCPropertyDecl>(getCursorDecl(C));
  Selector sel = PD->getGetterName();
  if (sel.isNull())
    return cxstring::createNull();
  return cxstring::createDup(sel.getAsString());
}
References clang::cxstring::createDup(), clang::cxstring::createNull(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getObjCPropertySetterName()
CXString clang_Cursor_getObjCPropertySetterName (CXCursor C)
Definition at line 8305 of file CIndex.cpp.
                                                            {
  if (C.kind != CXCursor_ObjCPropertyDecl)
    return cxstring::createNull();
  const ObjCPropertyDecl *PD = dyn_cast<ObjCPropertyDecl>(getCursorDecl(C));
  Selector sel = PD->getSetterName();
  if (sel.isNull())
    return cxstring::createNull();
  return cxstring::createDup(sel.getAsString());
}
References clang::cxstring::createDup(), clang::cxstring::createNull(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getObjCSelectorIndex()
int clang_Cursor_getObjCSelectorIndex (CXCursor cursor)
Definition at line 6666 of file CIndex.cpp.
                                                       {
  return cxcursor::getSelectorIdentifierIndexAndLoc(cursor).first;
}
References clang::cxcursor::getSelectorIdentifierIndexAndLoc().
clang_Cursor_getRawCommentText()
CXString clang_Cursor_getRawCommentText (CXCursor C)
Definition at line 8406 of file CIndex.cpp.
                                                    {
  if (!clang_isDeclaration(C.kind))
    return cxstring::createNull();
  const Decl *D = getCursorDecl(C);
  ASTContext &Context = getCursorContext(C);
  const RawComment *RC = Context.getRawCommentForAnyRedecl(D);
  StringRef RawText =
      RC ? RC->getRawText(Context.getSourceManager()) : StringRef();
  // Don't duplicate the string because RawText points directly into source
  // code.
  return cxstring::createRef(RawText);
}
References clang_isDeclaration(), clang::cxstring::createNull(), clang::cxstring::createRef(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getSpellingNameRange()
CXSourceRange clang_Cursor_getSpellingNameRange (CXCursor C, unsigned pieceIndex, unsigned options)
Definition at line 4795 of file CIndex.cpp.
                                                                  {
  if (clang_Cursor_isNull(C))
    return clang_getNullRange();
  ASTContext &Ctx = getCursorContext(C);
  if (clang_isStatement(C.kind)) {
    const Stmt *S = getCursorStmt(C);
    if (const LabelStmt *Label = dyn_cast_or_null<LabelStmt>(S)) {
      if (pieceIndex > 0)
        return clang_getNullRange();
      return cxloc::translateSourceRange(Ctx, Label->getIdentLoc());
    }
    return clang_getNullRange();
  }
  if (C.kind == CXCursor_ObjCMessageExpr) {
    if (const ObjCMessageExpr *ME =
            dyn_cast_or_null<ObjCMessageExpr>(getCursorExpr(C))) {
      if (pieceIndex >= ME->getNumSelectorLocs())
        return clang_getNullRange();
      return cxloc::translateSourceRange(Ctx, ME->getSelectorLoc(pieceIndex));
    }
  }
  if (C.kind == CXCursor_ObjCInstanceMethodDecl ||
      C.kind == CXCursor_ObjCClassMethodDecl) {
    if (const ObjCMethodDecl *MD =
            dyn_cast_or_null<ObjCMethodDecl>(getCursorDecl(C))) {
      if (pieceIndex >= MD->getNumSelectorLocs())
        return clang_getNullRange();
      return cxloc::translateSourceRange(Ctx, MD->getSelectorLoc(pieceIndex));
    }
  }
  if (C.kind == CXCursor_ObjCCategoryDecl ||
      C.kind == CXCursor_ObjCCategoryImplDecl) {
    if (pieceIndex > 0)
      return clang_getNullRange();
    if (const ObjCCategoryDecl *CD =
            dyn_cast_or_null<ObjCCategoryDecl>(getCursorDecl(C)))
      return cxloc::translateSourceRange(Ctx, CD->getCategoryNameLoc());
    if (const ObjCCategoryImplDecl *CID =
            dyn_cast_or_null<ObjCCategoryImplDecl>(getCursorDecl(C)))
      return cxloc::translateSourceRange(Ctx, CID->getCategoryNameLoc());
  }
  if (C.kind == CXCursor_ModuleImportDecl) {
    if (pieceIndex > 0)
      return clang_getNullRange();
    if (const ImportDecl *ImportD =
            dyn_cast_or_null<ImportDecl>(getCursorDecl(C))) {
      ArrayRef<SourceLocation> Locs = ImportD->getIdentifierLocs();
      if (!Locs.empty())
        return cxloc::translateSourceRange(
            Ctx, SourceRange(Locs.front(), Locs.back()));
    }
    return clang_getNullRange();
  }
  if (C.kind == CXCursor_CXXMethod || C.kind == CXCursor_Destructor ||
      C.kind == CXCursor_ConversionFunction ||
      C.kind == CXCursor_FunctionDecl) {
    if (pieceIndex > 0)
      return clang_getNullRange();
    if (const FunctionDecl *FD =
            dyn_cast_or_null<FunctionDecl>(getCursorDecl(C))) {
      DeclarationNameInfo FunctionName = FD->getNameInfo();
      return cxloc::translateSourceRange(Ctx, FunctionName.getSourceRange());
    }
    return clang_getNullRange();
  }
  // FIXME: A CXCursor_InclusionDirective should give the location of the
  // filename, but we don't keep track of this.
  // FIXME: A CXCursor_AnnotateAttr should give the location of the annotation
  // but we don't keep track of this.
  // FIXME: A CXCursor_AsmLabelAttr should give the location of the label
  // but we don't keep track of this.
  // Default handling, give the location of the cursor.
  if (pieceIndex > 0)
    return clang_getNullRange();
  CXSourceLocation CXLoc = clang_getCursorLocation(C);
  SourceLocation Loc = cxloc::translateSourceLocation(CXLoc);
  return cxloc::translateSourceRange(Ctx, Loc);
}
References clang_Cursor_isNull(), clang_getCursorLocation(), clang_getNullRange(), clang_isStatement(), clang::cxcursor::getCursorContext(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorExpr(), clang::cxcursor::getCursorStmt(), and clang::cxloc::translateSourceRange().
clang_Cursor_getStorageClass()
enum CX_StorageClass clang_Cursor_getStorageClass (CXCursor C)
Definition at line 8173 of file CIndex.cpp.
                                                              {
  StorageClass sc = SC_None;
  const Decl *D = getCursorDecl(C);
  if (D) {
    if (const FunctionDecl *FD = dyn_cast<FunctionDecl>(D)) {
      sc = FD->getStorageClass();
    } else if (const VarDecl *VD = dyn_cast<VarDecl>(D)) {
      sc = VD->getStorageClass();
    } else {
      return CX_SC_Invalid;
    }
  } else {
    return CX_SC_Invalid;
  }
  switch (sc) {
  case SC_None:
    return CX_SC_None;
  case SC_Extern:
    return CX_SC_Extern;
  case SC_Static:
    return CX_SC_Static;
  case SC_PrivateExtern:
    return CX_SC_PrivateExtern;
  case SC_Auto:
    return CX_SC_Auto;
  case SC_Register:
    return CX_SC_Register;
  }
  llvm_unreachable("Unhandled storage class!");
}
clang_Cursor_getVarDeclInitializer()
CXCursor clang_Cursor_getVarDeclInitializer (CXCursor cursor)
Definition at line 8925 of file CIndex.cpp.
                                                             {
  const Decl *const D = getCursorDecl(cursor);
  if (!D)
    return clang_getNullCursor();
  const auto *const VD = dyn_cast<VarDecl>(D);
  if (!VD)
    return clang_getNullCursor();
  const Expr *const Init = VD->getInit();
  if (!Init)
    return clang_getNullCursor();
  return cxcursor::MakeCXCursor(Init, VD, cxcursor::getCursorTU(cursor));
}
References clang_getNullCursor(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), and clang::cxcursor::MakeCXCursor().
clang_Cursor_hasAttrs()
unsigned clang_Cursor_hasAttrs (CXCursor C)
Definition at line 4132 of file CIndex.cpp.
                                           {
  const Decl *D = getCursorDecl(C);
  if (!D) {
    return 0;
  }
  if (D->hasAttrs()) {
    return 1;
  }
  return 0;
}
References clang::cxcursor::getCursorDecl().
clang_Cursor_hasVarDeclExternalStorage()
int clang_Cursor_hasVarDeclExternalStorage (CXCursor cursor)
Definition at line 8950 of file CIndex.cpp.
                                                            {
  const Decl *const D = getCursorDecl(cursor);
  if (!D)
    return -1;
  const auto *const VD = dyn_cast<VarDecl>(D);
  if (!VD)
    return -1;
  return VD->hasExternalStorage();
}
References clang::cxcursor::getCursorDecl().
clang_Cursor_hasVarDeclGlobalStorage()
int clang_Cursor_hasVarDeclGlobalStorage (CXCursor cursor)
Definition at line 8939 of file CIndex.cpp.
                                                          {
  const Decl *const D = getCursorDecl(cursor);
  if (!D)
    return -1;
  const auto *const VD = dyn_cast<VarDecl>(D);
  if (!VD)
    return -1;
  return VD->hasGlobalStorage();
}
References clang::cxcursor::getCursorDecl().
clang_Cursor_isExternalSymbol()
unsigned clang_Cursor_isExternalSymbol (CXCursor C, CXString * language, CXString * definedIn, unsigned * isGenerated)
Definition at line 8373 of file CIndex.cpp.
                                                              {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = getCursorDecl(C);
  if (auto *attr = D->getExternalSourceSymbolAttr()) {
    if (language)
      *language = cxstring::createDup(attr->getLanguage());
    if (definedIn)
      *definedIn = cxstring::createDup(attr->getDefinedIn());
    if (isGenerated)
      *isGenerated = attr->getGeneratedDeclaration();
    return 1;
  }
  return 0;
}
References clang_isDeclaration(), clang::cxstring::createDup(), and clang::cxcursor::getCursorDecl().
clang_Cursor_isFunctionInlined()
unsigned clang_Cursor_isFunctionInlined (CXCursor C)
Definition at line 3844 of file CIndex.cpp.
                                                    {
  const Decl *D = getCursorDecl(C);
  const FunctionDecl *FD = dyn_cast_or_null<FunctionDecl>(D);
  if (!FD) {
    return false;
  }
  return FD->isInlined();
}
References clang::cxcursor::getCursorDecl().
clang_Cursor_isMacroBuiltin()
unsigned clang_Cursor_isMacroBuiltin (CXCursor C)
Definition at line 3832 of file CIndex.cpp.
                                                 {
  const IdentifierInfo *II = getMacroIdentifier(C);
  if (!II) {
    return false;
  }
  ASTUnit *ASTU = getCursorASTUnit(C);
  Preprocessor &PP = ASTU->getPreprocessor();
  if (const MacroInfo *MI = PP.getMacroInfo(II))
    return MI->isBuiltinMacro();
  return false;
}
clang_Cursor_isMacroFunctionLike()
unsigned clang_Cursor_isMacroFunctionLike (CXCursor C)
Definition at line 3820 of file CIndex.cpp.
                                                      {
  const IdentifierInfo *II = getMacroIdentifier(C);
  if (!II) {
    return false;
  }
  ASTUnit *ASTU = getCursorASTUnit(C);
  Preprocessor &PP = ASTU->getPreprocessor();
  if (const MacroInfo *MI = PP.getMacroInfo(II))
    return MI->isFunctionLike();
  return false;
}
clang_Cursor_isObjCOptional()
unsigned clang_Cursor_isObjCOptional (CXCursor C)
Definition at line 8347 of file CIndex.cpp.
                                                 {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = getCursorDecl(C);
  if (const ObjCPropertyDecl *PD = dyn_cast<ObjCPropertyDecl>(D))
    return PD->getPropertyImplementation() == ObjCPropertyDecl::Optional;
  if (const ObjCMethodDecl *MD = dyn_cast<ObjCMethodDecl>(D))
    return MD->getImplementationControl() == ObjCMethodDecl::Optional;
  return 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_Cursor_isVariadic()
unsigned clang_Cursor_isVariadic (CXCursor C)
Definition at line 8360 of file CIndex.cpp.
                                             {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = getCursorDecl(C);
  if (const FunctionDecl *FD = dyn_cast<FunctionDecl>(D))
    return FD->isVariadic();
  if (const ObjCMethodDecl *MD = dyn_cast<ObjCMethodDecl>(D))
    return MD->isVariadic();
  return 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXIndex_getGlobalOptions()
unsigned clang_CXIndex_getGlobalOptions (CXIndex CIdx)
Definition at line 3481 of file CIndex.cpp.
                                                      {
  if (CIdx)
    return static_cast<CIndexer *>(CIdx)->getCXGlobalOptFlags();
  return 0;
}
clang_CXIndex_setGlobalOptions()
void clang_CXIndex_setGlobalOptions (CXIndex CIdx, unsigned options)
Definition at line 3476 of file CIndex.cpp.
                                                                    {
  if (CIdx)
    static_cast<CIndexer *>(CIdx)->setCXGlobalOptFlags(options);
}
clang_CXIndex_setInvocationEmissionPathOption()
void clang_CXIndex_setInvocationEmissionPathOption (CXIndex CIdx, const char * Path)
Definition at line 3487 of file CIndex.cpp.
                                                                     {
  if (CIdx)
    static_cast<CIndexer *>(CIdx)->setInvocationEmissionPath(Path ? Path : "");
}
Referenced by perform_test_load_source().
clang_CXXConstructor_isConvertingConstructor()
unsigned clang_CXXConstructor_isConvertingConstructor (CXCursor C)
Definition at line 8569 of file CIndex.cpp.
                                                                  {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXConstructorDecl *Constructor =
      D ? dyn_cast_or_null<CXXConstructorDecl>(D->getAsFunction()) : nullptr;
  // Passing 'false' excludes constructors marked 'explicit'.
  return (Constructor && Constructor->isConvertingConstructor(false)) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXConstructor_isCopyConstructor()
unsigned clang_CXXConstructor_isCopyConstructor (CXCursor C)
Definition at line 8549 of file CIndex.cpp.
                                                            {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXConstructorDecl *Constructor =
      D ? dyn_cast_or_null<CXXConstructorDecl>(D->getAsFunction()) : nullptr;
  return (Constructor && Constructor->isCopyConstructor()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXConstructor_isDefaultConstructor()
unsigned clang_CXXConstructor_isDefaultConstructor (CXCursor C)
Definition at line 8539 of file CIndex.cpp.
                                                               {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXConstructorDecl *Constructor =
      D ? dyn_cast_or_null<CXXConstructorDecl>(D->getAsFunction()) : nullptr;
  return (Constructor && Constructor->isDefaultConstructor()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXConstructor_isMoveConstructor()
unsigned clang_CXXConstructor_isMoveConstructor (CXCursor C)
Definition at line 8559 of file CIndex.cpp.
                                                            {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXConstructorDecl *Constructor =
      D ? dyn_cast_or_null<CXXConstructorDecl>(D->getAsFunction()) : nullptr;
  return (Constructor && Constructor->isMoveConstructor()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXField_isMutable()
unsigned clang_CXXField_isMutable (CXCursor C)
Definition at line 8580 of file CIndex.cpp.
                                              {
  if (!clang_isDeclaration(C.kind))
    return 0;
  if (const auto D = cxcursor::getCursorDecl(C))
    if (const auto FD = dyn_cast_or_null<FieldDecl>(D))
      return FD->isMutable() ? 1 : 0;
  return 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXMethod_isConst()
unsigned clang_CXXMethod_isConst (CXCursor C)
Definition at line 8600 of file CIndex.cpp.
                                             {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXMethodDecl *Method =
      D ? dyn_cast_or_null<CXXMethodDecl>(D->getAsFunction()) : nullptr;
  return (Method && Method->getMethodQualifiers().hasConst()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXMethod_isDefaulted()
unsigned clang_CXXMethod_isDefaulted (CXCursor C)
Definition at line 8610 of file CIndex.cpp.
                                                 {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXMethodDecl *Method =
      D ? dyn_cast_or_null<CXXMethodDecl>(D->getAsFunction()) : nullptr;
  return (Method && Method->isDefaulted()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXMethod_isPureVirtual()
unsigned clang_CXXMethod_isPureVirtual (CXCursor C)
Definition at line 8590 of file CIndex.cpp.
                                                   {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXMethodDecl *Method =
      D ? dyn_cast_or_null<CXXMethodDecl>(D->getAsFunction()) : nullptr;
  return (Method && Method->isVirtual() && Method->isPure()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXMethod_isStatic()
unsigned clang_CXXMethod_isStatic (CXCursor C)
Definition at line 8620 of file CIndex.cpp.
                                              {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXMethodDecl *Method =
      D ? dyn_cast_or_null<CXXMethodDecl>(D->getAsFunction()) : nullptr;
  return (Method && Method->isStatic()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXMethod_isVirtual()
unsigned clang_CXXMethod_isVirtual (CXCursor C)
Definition at line 8630 of file CIndex.cpp.
                                               {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const CXXMethodDecl *Method =
      D ? dyn_cast_or_null<CXXMethodDecl>(D->getAsFunction()) : nullptr;
  return (Method && Method->isVirtual()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_CXXRecord_isAbstract()
unsigned clang_CXXRecord_isAbstract (CXCursor C)
Definition at line 8640 of file CIndex.cpp.
                                                {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const auto *D = cxcursor::getCursorDecl(C);
  const auto *RD = dyn_cast_or_null<CXXRecordDecl>(D);
  if (RD)
    RD = RD->getDefinition();
  return (RD && RD->isAbstract()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_defaultEditingTranslationUnitOptions()
unsigned clang_defaultEditingTranslationUnitOptions ()
Definition at line 3537 of file CIndex.cpp.
                                                      {
  return CXTranslationUnit_PrecompiledPreamble |
         CXTranslationUnit_CacheCompletionResults;
}
clang_defaultReparseOptions()
unsigned clang_defaultReparseOptions (CXTranslationUnit TU)
Definition at line 4238 of file CIndex.cpp.
                                                           {
  return CXReparse_None;
}
clang_defaultSaveOptions()
unsigned clang_defaultSaveOptions (CXTranslationUnit TU)
Definition at line 4144 of file CIndex.cpp.
                                                        {
  return CXSaveTranslationUnit_None;
}
clang_disposeCXPlatformAvailability()
void clang_disposeCXPlatformAvailability (CXPlatformAvailability * availability)
Definition at line 8142 of file CIndex.cpp.
                                                                               {
  clang_disposeString(availability->Platform);
  clang_disposeString(availability->Message);
}
References clang_disposeString().
clang_disposeCXTUResourceUsage()
void clang_disposeCXTUResourceUsage (CXTUResourceUsage usage)
Definition at line 8829 of file CIndex.cpp.
                                                             {
  if (usage.data)
    delete (MemUsageEntries *)usage.data;
}
Referenced by clang::PrintLibclangResourceUsage(), and PrintMemoryUsage().
clang_disposeIndex()
void clang_disposeIndex (CXIndex CIdx)
Definition at line 3471 of file CIndex.cpp.
                                      {
  if (CIdx)
    delete static_cast<CIndexer *>(CIdx);
}
clang_disposeSourceRangeList()
void clang_disposeSourceRangeList (CXSourceRangeList * ranges)
Definition at line 8908 of file CIndex.cpp.
                                                             {
  if (ranges) {
    delete[] ranges->ranges;
    delete ranges;
  }
}
clang_disposeTokens()
void clang_disposeTokens (CXTranslationUnit TU, CXToken * Tokens, unsigned NumTokens)
Definition at line 7022 of file CIndex.cpp.
                                             {
  free(Tokens);
}
clang_disposeTranslationUnit()
void clang_disposeTranslationUnit (CXTranslationUnit CTUnit)
Definition at line 4207 of file CIndex.cpp.
                                                            {
  if (CTUnit) {
    // If the translation unit has been marked as unsafe to free, just discard
    // it.
    ASTUnit *Unit = cxtu::getASTUnit(CTUnit);
    if (Unit && Unit->isUnsafeToFree())
      return;
    delete cxtu::getASTUnit(CTUnit);
    delete CTUnit->StringPool;
    delete static_cast<CXDiagnosticSetImpl *>(CTUnit->Diagnostics);
    disposeOverridenCXCursorsPool(CTUnit->OverridenCursorsPool);
    delete CTUnit->CommentToXML;
    delete CTUnit;
  }
}
References clang::cxcursor::disposeOverridenCXCursorsPool().
Referenced by clang::cxtu::CXTUOwner::~CXTUOwner().
clang_enableStackTraces()
void clang_enableStackTraces (void)
Definition at line 6781 of file CIndex.cpp.
                                   {
  // FIXME: Provide an argv0 here so we can find llvm-symbolizer.
  llvm::sys::PrintStackTraceOnErrorSignal(StringRef());
}
Referenced by carcmttest_main(), and cindextest_main().
clang_EnumDecl_isScoped()
unsigned clang_EnumDecl_isScoped (CXCursor C)
Definition at line 8651 of file CIndex.cpp.
                                             {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  auto *Enum = dyn_cast_or_null<EnumDecl>(D);
  return (Enum && Enum->isScoped()) ? 1 : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_equalCursors()
unsigned clang_equalCursors (CXCursor X, CXCursor Y)
Definition at line 5905 of file CIndex.cpp.
                                                    {
  // Clear out the "FirstInDeclGroup" part in a declaration cursor, since we
  // can't set consistently. For example, when visiting a DeclStmt we will set
  // it but we don't set it on the result of clang_getCursorDefinition for
  // a reference of the same declaration.
  // FIXME: Setting "FirstInDeclGroup" in CXCursors is a hack that only works
  // when visiting a DeclStmt currently, the AST should be enhanced to be able
  // to provide that kind of info.
  if (clang_isDeclaration(X.kind))
    X.data[1] = nullptr;
  if (clang_isDeclaration(Y.kind))
    Y.data[1] = nullptr;
  return X == Y;
}
References clang_isDeclaration().
Referenced by clang_Cursor_isNull().
clang_EvalResult_dispose()
void clang_EvalResult_dispose (CXEvalResult E)
Definition at line 3894 of file CIndex.cpp.
                                              {
  delete static_cast<ExprEvalResult *>(E);
}
clang_EvalResult_getAsDouble()
double clang_EvalResult_getAsDouble (CXEvalResult E)
Definition at line 3934 of file CIndex.cpp.
                                                    {
  if (!E) {
    return 0;
  }
  return ((ExprEvalResult *)E)->EvalData.floatVal;
}
clang_EvalResult_getAsInt()
int clang_EvalResult_getAsInt (CXEvalResult E)
Definition at line 3905 of file CIndex.cpp.
                                              {
  return clang_EvalResult_getAsLongLong(E);
}
References clang_EvalResult_getAsLongLong().
clang_EvalResult_getAsLongLong()
long long clang_EvalResult_getAsLongLong (CXEvalResult E)
Definition at line 3909 of file CIndex.cpp.
                                                         {
  if (!E) {
    return 0;
  }
  ExprEvalResult *Result = (ExprEvalResult *)E;
  if (Result->IsUnsignedInt)
    return Result->EvalData.unsignedVal;
  return Result->EvalData.intVal;
}
References ExprEvalResult::EvalData, ExprEvalResult::intVal, ExprEvalResult::IsUnsignedInt, and ExprEvalResult::unsignedVal.
Referenced by clang_EvalResult_getAsInt().
clang_EvalResult_getAsStr()
const char* clang_EvalResult_getAsStr (CXEvalResult E)
Definition at line 3941 of file CIndex.cpp.
                                                      {
  if (!E) {
    return nullptr;
  }
  return ((ExprEvalResult *)E)->EvalData.stringVal;
}
clang_EvalResult_getAsUnsigned()
unsigned long long clang_EvalResult_getAsUnsigned (CXEvalResult E)
Definition at line 3923 of file CIndex.cpp.
                                                                  {
  if (!E) {
    return 0;
  }
  ExprEvalResult *Result = (ExprEvalResult *)E;
  if (Result->IsUnsignedInt)
    return Result->EvalData.unsignedVal;
  return Result->EvalData.intVal;
}
References ExprEvalResult::EvalData, ExprEvalResult::intVal, ExprEvalResult::IsUnsignedInt, and ExprEvalResult::unsignedVal.
clang_EvalResult_getKind()
CXEvalResultKind clang_EvalResult_getKind (CXEvalResult E)
Definition at line 3898 of file CIndex.cpp.
                                                          {
  if (!E) {
    return CXEval_UnExposed;
  }
  return ((ExprEvalResult *)E)->EvalType;
}
clang_EvalResult_isUnsignedInt()
unsigned clang_EvalResult_isUnsignedInt (CXEvalResult E)
Definition at line 3919 of file CIndex.cpp.
                                                        {
  return ((ExprEvalResult *)E)->IsUnsignedInt;
}
clang_executeOnThread()
void clang_executeOnThread (void(*)(void *) fn, void * user_data, unsigned stack_size)
Definition at line 6786 of file CIndex.cpp.
                                                {
  llvm::llvm_execute_on_thread(fn, user_data,
                               stack_size == 0
                                   ? clang::DesiredStackSize
                                   : llvm::Optional<unsigned>(stack_size));
}
clang_File_isEqual()
int clang_File_isEqual (CXFile file1, CXFile file2)
Definition at line 4458 of file CIndex.cpp.
                                                   {
  if (file1 == file2)
    return true;
  if (!file1 || !file2)
    return false;
  FileEntry *FEnt1 = static_cast<FileEntry *>(file1);
  FileEntry *FEnt2 = static_cast<FileEntry *>(file2);
  return FEnt1->getUniqueID() == FEnt2->getUniqueID();
}
clang_File_tryGetRealPathName()
CXString clang_File_tryGetRealPathName (CXFile SFile)
Definition at line 4470 of file CIndex.cpp.
                                                     {
  if (!SFile)
    return cxstring::createNull();
  FileEntry *FEnt = static_cast<FileEntry *>(SFile);
  return cxstring::createRef(FEnt->tryGetRealPathName());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_getAllSkippedRanges()
CXSourceRangeList* clang_getAllSkippedRanges (CXTranslationUnit TU)
Definition at line 8880 of file CIndex.cpp.
                                                                   {
  CXSourceRangeList *skipped = new CXSourceRangeList;
  skipped->count = 0;
  skipped->ranges = nullptr;
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return skipped;
  }
  ASTUnit *astUnit = cxtu::getASTUnit(TU);
  PreprocessingRecord *ppRec =
      astUnit->getPreprocessor().getPreprocessingRecord();
  if (!ppRec)
    return skipped;
  ASTContext &Ctx = astUnit->getASTContext();
  const std::vector<SourceRange> &SkippedRanges = ppRec->getSkippedRanges();
  skipped->count = SkippedRanges.size();
  skipped->ranges = new CXSourceRange[skipped->count];
  for (unsigned i = 0, ei = skipped->count; i != ei; ++i)
    skipped->ranges[i] = cxloc::translateSourceRange(Ctx, SkippedRanges[i]);
  return skipped;
}
clang_getCanonicalCursor()
CXCursor clang_getCanonicalCursor (CXCursor C)
Definition at line 6646 of file CIndex.cpp.
                                              {
  if (!clang_isDeclaration(C.kind))
    return C;
  if (const Decl *D = getCursorDecl(C)) {
    if (const ObjCCategoryImplDecl *CatImplD =
            dyn_cast<ObjCCategoryImplDecl>(D))
      if (ObjCCategoryDecl *CatD = CatImplD->getCategoryDecl())
        return MakeCXCursor(CatD, getCursorTU(C));
    if (const ObjCImplDecl *ImplD = dyn_cast<ObjCImplDecl>(D))
      if (const ObjCInterfaceDecl *IFD = ImplD->getClassInterface())
        return MakeCXCursor(IFD, getCursorTU(C));
    return MakeCXCursor(D->getCanonicalDecl(), getCursorTU(C));
  }
  return C;
}
References clang_isDeclaration(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), and clang::cxcursor::MakeCXCursor().
clang_getClangVersion()
CXString clang_getClangVersion ()
Definition at line 9109 of file CIndex.cpp.
                                 {
  return cxstring::createDup(getClangFullVersion());
}
References clang::cxstring::createDup().
clang_getCursor()
CXCursor clang_getCursor (CXTranslationUnit TU, CXSourceLocation Loc)
Definition at line 5839 of file CIndex.cpp.
                                                                     {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return clang_getNullCursor();
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  ASTUnit::ConcurrencyCheck Check(*CXXUnit);
  SourceLocation SLoc = cxloc::translateSourceLocation(Loc);
  CXCursor Result = cxcursor::getCursor(TU, SLoc);
  LOG_FUNC_SECTION {
    CXFile SearchFile;
    unsigned SearchLine, SearchColumn;
    CXFile ResultFile;
    unsigned ResultLine, ResultColumn;
    CXString SearchFileName, ResultFileName, KindSpelling, USR;
    const char *IsDef = clang_isCursorDefinition(Result) ? " (Definition)" : "";
    CXSourceLocation ResultLoc = clang_getCursorLocation(Result);
    clang_getFileLocation(Loc, &SearchFile, &SearchLine, &SearchColumn,
                          nullptr);
    clang_getFileLocation(ResultLoc, &ResultFile, &ResultLine, &ResultColumn,
                          nullptr);
    SearchFileName = clang_getFileName(SearchFile);
    ResultFileName = clang_getFileName(ResultFile);
    KindSpelling = clang_getCursorKindSpelling(Result.kind);
    USR = clang_getCursorUSR(Result);
    *Log << llvm::format("(%s:%d:%d) = %s", clang_getCString(SearchFileName),
                         SearchLine, SearchColumn,
                         clang_getCString(KindSpelling))
         << llvm::format("(%s:%d:%d):%s%s", clang_getCString(ResultFileName),
                         ResultLine, ResultColumn, clang_getCString(USR),
                         IsDef);
    clang_disposeString(SearchFileName);
    clang_disposeString(ResultFileName);
    clang_disposeString(KindSpelling);
    clang_disposeString(USR);
    CXCursor Definition = clang_getCursorDefinition(Result);
    if (!clang_equalCursors(Definition, clang_getNullCursor())) {
      CXSourceLocation DefinitionLoc = clang_getCursorLocation(Definition);
      CXString DefinitionKindSpelling =
          clang_getCursorKindSpelling(Definition.kind);
      CXFile DefinitionFile;
      unsigned DefinitionLine, DefinitionColumn;
      clang_getFileLocation(DefinitionLoc, &DefinitionFile, &DefinitionLine,
                            &DefinitionColumn, nullptr);
      CXString DefinitionFileName = clang_getFileName(DefinitionFile);
      *Log << llvm::format(" -> %s(%s:%d:%d)",
                           clang_getCString(DefinitionKindSpelling),
                           clang_getCString(DefinitionFileName), DefinitionLine,
                           DefinitionColumn);
      clang_disposeString(DefinitionFileName);
      clang_disposeString(DefinitionKindSpelling);
    }
  }
  return Result;
}
clang_getCursorAvailability()
enum CXAvailabilityKind clang_getCursorAvailability (CXCursor cursor)
Definition at line 7956 of file CIndex.cpp.
                                                                     {
  if (clang_isDeclaration(cursor.kind))
    if (const Decl *D = cxcursor::getCursorDecl(cursor))
      return getCursorAvailabilityForDecl(D);
  return CXAvailability_Available;
}
clang_getCursorDefinition()
CXCursor clang_getCursorDefinition (CXCursor C)
Definition at line 6411 of file CIndex.cpp.
                                               {
  if (clang_isInvalid(C.kind))
    return clang_getNullCursor();
  CXTranslationUnit TU = getCursorTU(C);
  bool WasReference = false;
  if (clang_isReference(C.kind) || clang_isExpression(C.kind)) {
    C = clang_getCursorReferenced(C);
    WasReference = true;
  }
  if (C.kind == CXCursor_MacroExpansion)
    return clang_getCursorReferenced(C);
  if (!clang_isDeclaration(C.kind))
    return clang_getNullCursor();
  const Decl *D = getCursorDecl(C);
  if (!D)
    return clang_getNullCursor();
  switch (D->getKind()) {
  // Declaration kinds that don't really separate the notions of
  // declaration and definition.
  case Decl::Namespace:
  case Decl::Typedef:
  case Decl::TypeAlias:
  case Decl::TypeAliasTemplate:
  case Decl::TemplateTypeParm:
  case Decl::EnumConstant:
  case Decl::Field:
  case Decl::Binding:
  case Decl::MSProperty:
  case Decl::MSGuid:
  case Decl::TemplateParamObject:
  case Decl::IndirectField:
  case Decl::ObjCIvar:
  case Decl::ObjCAtDefsField:
  case Decl::ImplicitParam:
  case Decl::ParmVar:
  case Decl::NonTypeTemplateParm:
  case Decl::TemplateTemplateParm:
  case Decl::ObjCCategoryImpl:
  case Decl::ObjCImplementation:
  case Decl::AccessSpec:
  case Decl::LinkageSpec:
  case Decl::Export:
  case Decl::ObjCPropertyImpl:
  case Decl::FileScopeAsm:
  case Decl::StaticAssert:
  case Decl::Block:
  case Decl::Captured:
  case Decl::OMPCapturedExpr:
  case Decl::Label: // FIXME: Is this right??
  case Decl::ClassScopeFunctionSpecialization:
  case Decl::CXXDeductionGuide:
  case Decl::Import:
  case Decl::OMPThreadPrivate:
  case Decl::OMPAllocate:
  case Decl::OMPDeclareReduction:
  case Decl::OMPDeclareMapper:
  case Decl::OMPRequires:
  case Decl::ObjCTypeParam:
  case Decl::BuiltinTemplate:
  case Decl::PragmaComment:
  case Decl::PragmaDetectMismatch:
  case Decl::UsingPack:
  case Decl::Concept:
  case Decl::LifetimeExtendedTemporary:
  case Decl::RequiresExprBody:
  case Decl::UnresolvedUsingIfExists:
    return C;
  // Declaration kinds that don't make any sense here, but are
  // nonetheless harmless.
  case Decl::Empty:
  case Decl::TranslationUnit:
  case Decl::ExternCContext:
    break;
  // Declaration kinds for which the definition is not resolvable.
  case Decl::UnresolvedUsingTypename:
  case Decl::UnresolvedUsingValue:
    break;
  case Decl::UsingDirective:
    return MakeCXCursor(cast<UsingDirectiveDecl>(D)->getNominatedNamespace(),
                        TU);
  case Decl::NamespaceAlias:
    return MakeCXCursor(cast<NamespaceAliasDecl>(D)->getNamespace(), TU);
  case Decl::Enum:
  case Decl::Record:
  case Decl::CXXRecord:
  case Decl::ClassTemplateSpecialization:
  case Decl::ClassTemplatePartialSpecialization:
    if (TagDecl *Def = cast<TagDecl>(D)->getDefinition())
      return MakeCXCursor(Def, TU);
    return clang_getNullCursor();
  case Decl::Function:
  case Decl::CXXMethod:
  case Decl::CXXConstructor:
  case Decl::CXXDestructor:
  case Decl::CXXConversion: {
    const FunctionDecl *Def = nullptr;
    if (cast<FunctionDecl>(D)->getBody(Def))
      return MakeCXCursor(Def, TU);
    return clang_getNullCursor();
  }
  case Decl::Var:
  case Decl::VarTemplateSpecialization:
  case Decl::VarTemplatePartialSpecialization:
  case Decl::Decomposition: {
    // Ask the variable if it has a definition.
    if (const VarDecl *Def = cast<VarDecl>(D)->getDefinition())
      return MakeCXCursor(Def, TU);
    return clang_getNullCursor();
  }
  case Decl::FunctionTemplate: {
    const FunctionDecl *Def = nullptr;
    if (cast<FunctionTemplateDecl>(D)->getTemplatedDecl()->getBody(Def))
      return MakeCXCursor(Def->getDescribedFunctionTemplate(), TU);
    return clang_getNullCursor();
  }
  case Decl::ClassTemplate: {
    if (RecordDecl *Def =
            cast<ClassTemplateDecl>(D)->getTemplatedDecl()->getDefinition())
      return MakeCXCursor(cast<CXXRecordDecl>(Def)->getDescribedClassTemplate(),
                          TU);
    return clang_getNullCursor();
  }
  case Decl::VarTemplate: {
    if (VarDecl *Def =
            cast<VarTemplateDecl>(D)->getTemplatedDecl()->getDefinition())
      return MakeCXCursor(cast<VarDecl>(Def)->getDescribedVarTemplate(), TU);
    return clang_getNullCursor();
  }
  case Decl::Using:
  case Decl::UsingEnum:
    return MakeCursorOverloadedDeclRef(cast<BaseUsingDecl>(D), D->getLocation(),
                                       TU);
  case Decl::UsingShadow:
  case Decl::ConstructorUsingShadow:
    return clang_getCursorDefinition(
        MakeCXCursor(cast<UsingShadowDecl>(D)->getTargetDecl(), TU));
  case Decl::ObjCMethod: {
    const ObjCMethodDecl *Method = cast<ObjCMethodDecl>(D);
    if (Method->isThisDeclarationADefinition())
      return C;
    // Dig out the method definition in the associated
    // @implementation, if we have it.
    // FIXME: The ASTs should make finding the definition easier.
    if (const ObjCInterfaceDecl *Class =
            dyn_cast<ObjCInterfaceDecl>(Method->getDeclContext()))
      if (ObjCImplementationDecl *ClassImpl = Class->getImplementation())
        if (ObjCMethodDecl *Def = ClassImpl->getMethod(
                Method->getSelector(), Method->isInstanceMethod()))
          if (Def->isThisDeclarationADefinition())
            return MakeCXCursor(Def, TU);
    return clang_getNullCursor();
  }
  case Decl::ObjCCategory:
    if (ObjCCategoryImplDecl *Impl =
            cast<ObjCCategoryDecl>(D)->getImplementation())
      return MakeCXCursor(Impl, TU);
    return clang_getNullCursor();
  case Decl::ObjCProtocol:
    if (const ObjCProtocolDecl *Def =
            cast<ObjCProtocolDecl>(D)->getDefinition())
      return MakeCXCursor(Def, TU);
    return clang_getNullCursor();
  case Decl::ObjCInterface: {
    // There are two notions of a "definition" for an Objective-C
    // class: the interface and its implementation. When we resolved a
    // reference to an Objective-C class, produce the @interface as
    // the definition; when we were provided with the interface,
    // produce the @implementation as the definition.
    const ObjCInterfaceDecl *IFace = cast<ObjCInterfaceDecl>(D);
    if (WasReference) {
      if (const ObjCInterfaceDecl *Def = IFace->getDefinition())
        return MakeCXCursor(Def, TU);
    } else if (ObjCImplementationDecl *Impl = IFace->getImplementation())
      return MakeCXCursor(Impl, TU);
    return clang_getNullCursor();
  }
  case Decl::ObjCProperty:
    // FIXME: We don't really know where to find the
    // ObjCPropertyImplDecls that implement this property.
    return clang_getNullCursor();
  case Decl::ObjCCompatibleAlias:
    if (const ObjCInterfaceDecl *Class =
            cast<ObjCCompatibleAliasDecl>(D)->getClassInterface())
      if (const ObjCInterfaceDecl *Def = Class->getDefinition())
        return MakeCXCursor(Def, TU);
    return clang_getNullCursor();
  case Decl::Friend:
    if (NamedDecl *Friend = cast<FriendDecl>(D)->getFriendDecl())
      return clang_getCursorDefinition(MakeCXCursor(Friend, TU));
    return clang_getNullCursor();
  case Decl::FriendTemplate:
    if (NamedDecl *Friend = cast<FriendTemplateDecl>(D)->getFriendDecl())
      return clang_getCursorDefinition(MakeCXCursor(Friend, TU));
    return clang_getNullCursor();
  }
  return clang_getNullCursor();
}
References clang_getCursorReferenced(), clang_getNullCursor(), clang_isDeclaration(), clang_isExpression(), clang_isInvalid(), clang_isReference(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), clang::cxcursor::MakeCursorOverloadedDeclRef(), and clang::cxcursor::MakeCXCursor().
Referenced by clang_isCursorDefinition().
clang_getCursorDisplayName()
CXString clang_getCursorDisplayName (CXCursor C)
Definition at line 5120 of file CIndex.cpp.
                                                {
  if (!clang_isDeclaration(C.kind))
    return clang_getCursorSpelling(C);
  const Decl *D = getCursorDecl(C);
  if (!D)
    return cxstring::createEmpty();
  PrintingPolicy Policy = getCursorContext(C).getPrintingPolicy();
  if (const FunctionTemplateDecl *FunTmpl = dyn_cast<FunctionTemplateDecl>(D))
    D = FunTmpl->getTemplatedDecl();
  if (const FunctionDecl *Function = dyn_cast<FunctionDecl>(D)) {
    SmallString<64> Str;
    llvm::raw_svector_ostream OS(Str);
    OS << *Function;
    if (Function->getPrimaryTemplate())
      OS << "<>";
    OS << "(";
    for (unsigned I = 0, N = Function->getNumParams(); I != N; ++I) {
      if (I)
        OS << ", ";
      OS << Function->getParamDecl(I)->getType().getAsString(Policy);
    }
    if (Function->isVariadic()) {
      if (Function->getNumParams())
        OS << ", ";
      OS << "...";
    }
    OS << ")";
    return cxstring::createDup(OS.str());
  }
  if (const ClassTemplateDecl *ClassTemplate = dyn_cast<ClassTemplateDecl>(D)) {
    SmallString<64> Str;
    llvm::raw_svector_ostream OS(Str);
    OS << *ClassTemplate;
    OS << "<";
    TemplateParameterList *Params = ClassTemplate->getTemplateParameters();
    for (unsigned I = 0, N = Params->size(); I != N; ++I) {
      if (I)
        OS << ", ";
      NamedDecl *Param = Params->getParam(I);
      if (Param->getIdentifier()) {
        OS << Param->getIdentifier()->getName();
        continue;
      }
      // There is no parameter name, which makes this tricky. Try to come up
      // with something useful that isn't too long.
      if (TemplateTypeParmDecl *TTP = dyn_cast<TemplateTypeParmDecl>(Param))
        if (const auto *TC = TTP->getTypeConstraint()) {
          TC->getConceptNameInfo().printName(OS, Policy);
          if (TC->hasExplicitTemplateArgs())
            OS << "<...>";
        } else
          OS << (TTP->wasDeclaredWithTypename() ? "typename" : "class");
      else if (NonTypeTemplateParmDecl *NTTP =
                   dyn_cast<NonTypeTemplateParmDecl>(Param))
        OS << NTTP->getType().getAsString(Policy);
      else
        OS << "template<...> class";
    }
    OS << ">";
    return cxstring::createDup(OS.str());
  }
  if (const ClassTemplateSpecializationDecl *ClassSpec =
          dyn_cast<ClassTemplateSpecializationDecl>(D)) {
    // If the type was explicitly written, use that.
    if (TypeSourceInfo *TSInfo = ClassSpec->getTypeAsWritten())
      return cxstring::createDup(TSInfo->getType().getAsString(Policy));
    SmallString<128> Str;
    llvm::raw_svector_ostream OS(Str);
    OS << *ClassSpec;
    printTemplateArgumentList(
        OS, ClassSpec->getTemplateArgs().asArray(), Policy,
        ClassSpec->getSpecializedTemplate()->getTemplateParameters());
    return cxstring::createDup(OS.str());
  }
  return clang_getCursorSpelling(C);
}
References clang_getCursorSpelling(), clang_isDeclaration(), clang::cxstring::createDup(), clang::cxstring::createEmpty(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorDecl().
Referenced by clang::cxindex::Logger::operator<<().
clang_getCursorExtent()
CXSourceRange clang_getCursorExtent (CXCursor C)
Definition at line 6293 of file CIndex.cpp.
                                                {
  SourceRange R = getRawCursorExtent(C);
  if (R.isInvalid())
    return clang_getNullRange();
  return cxloc::translateSourceRange(getCursorContext(C), R);
}
Referenced by clang_getCursorReferenceNameRange().
clang_getCursorKind()
CXCursorKind clang_getCursorKind (CXCursor C)
Definition at line 5984 of file CIndex.cpp.
{ return C.kind; }
Referenced by clang_Cursor_Evaluate(), clang_Cursor_getNumTemplateArguments(), clang_getCursorCompletionString(), and clang_getCursorUSR().
clang_getCursorKindSpelling()
CXString clang_getCursorKindSpelling (enum CXCursorKind Kind)
Definition at line 5208 of file CIndex.cpp.
                                                             {
  switch (Kind) {
  case CXCursor_FunctionDecl:
    return cxstring::createRef("FunctionDecl");
  case CXCursor_TypedefDecl:
    return cxstring::createRef("TypedefDecl");
  case CXCursor_EnumDecl:
    return cxstring::createRef("EnumDecl");
  case CXCursor_EnumConstantDecl:
    return cxstring::createRef("EnumConstantDecl");
  case CXCursor_StructDecl:
    return cxstring::createRef("StructDecl");
  case CXCursor_UnionDecl:
    return cxstring::createRef("UnionDecl");
  case CXCursor_ClassDecl:
    return cxstring::createRef("ClassDecl");
  case CXCursor_FieldDecl:
    return cxstring::createRef("FieldDecl");
  case CXCursor_VarDecl:
    return cxstring::createRef("VarDecl");
  case CXCursor_ParmDecl:
    return cxstring::createRef("ParmDecl");
  case CXCursor_ObjCInterfaceDecl:
    return cxstring::createRef("ObjCInterfaceDecl");
  case CXCursor_ObjCCategoryDecl:
    return cxstring::createRef("ObjCCategoryDecl");
  case CXCursor_ObjCProtocolDecl:
    return cxstring::createRef("ObjCProtocolDecl");
  case CXCursor_ObjCPropertyDecl:
    return cxstring::createRef("ObjCPropertyDecl");
  case CXCursor_ObjCIvarDecl:
    return cxstring::createRef("ObjCIvarDecl");
  case CXCursor_ObjCInstanceMethodDecl:
    return cxstring::createRef("ObjCInstanceMethodDecl");
  case CXCursor_ObjCClassMethodDecl:
    return cxstring::createRef("ObjCClassMethodDecl");
  case CXCursor_ObjCImplementationDecl:
    return cxstring::createRef("ObjCImplementationDecl");
  case CXCursor_ObjCCategoryImplDecl:
    return cxstring::createRef("ObjCCategoryImplDecl");
  case CXCursor_CXXMethod:
    return cxstring::createRef("CXXMethod");
  case CXCursor_UnexposedDecl:
    return cxstring::createRef("UnexposedDecl");
  case CXCursor_ObjCSuperClassRef:
    return cxstring::createRef("ObjCSuperClassRef");
  case CXCursor_ObjCProtocolRef:
    return cxstring::createRef("ObjCProtocolRef");
  case CXCursor_ObjCClassRef:
    return cxstring::createRef("ObjCClassRef");
  case CXCursor_TypeRef:
    return cxstring::createRef("TypeRef");
  case CXCursor_TemplateRef:
    return cxstring::createRef("TemplateRef");
  case CXCursor_NamespaceRef:
    return cxstring::createRef("NamespaceRef");
  case CXCursor_MemberRef:
    return cxstring::createRef("MemberRef");
  case CXCursor_LabelRef:
    return cxstring::createRef("LabelRef");
  case CXCursor_OverloadedDeclRef:
    return cxstring::createRef("OverloadedDeclRef");
  case CXCursor_VariableRef:
    return cxstring::createRef("VariableRef");
  case CXCursor_IntegerLiteral:
    return cxstring::createRef("IntegerLiteral");
  case CXCursor_FixedPointLiteral:
    return cxstring::createRef("FixedPointLiteral");
  case CXCursor_FloatingLiteral:
    return cxstring::createRef("FloatingLiteral");
  case CXCursor_ImaginaryLiteral:
    return cxstring::createRef("ImaginaryLiteral");
  case CXCursor_StringLiteral:
    return cxstring::createRef("StringLiteral");
  case CXCursor_CharacterLiteral:
    return cxstring::createRef("CharacterLiteral");
  case CXCursor_ParenExpr:
    return cxstring::createRef("ParenExpr");
  case CXCursor_UnaryOperator:
    return cxstring::createRef("UnaryOperator");
  case CXCursor_ArraySubscriptExpr:
    return cxstring::createRef("ArraySubscriptExpr");
  case CXCursor_OMPArraySectionExpr:
    return cxstring::createRef("OMPArraySectionExpr");
  case CXCursor_OMPArrayShapingExpr:
    return cxstring::createRef("OMPArrayShapingExpr");
  case CXCursor_OMPIteratorExpr:
    return cxstring::createRef("OMPIteratorExpr");
  case CXCursor_BinaryOperator:
    return cxstring::createRef("BinaryOperator");
  case CXCursor_CompoundAssignOperator:
    return cxstring::createRef("CompoundAssignOperator");
  case CXCursor_ConditionalOperator:
    return cxstring::createRef("ConditionalOperator");
  case CXCursor_CStyleCastExpr:
    return cxstring::createRef("CStyleCastExpr");
  case CXCursor_CompoundLiteralExpr:
    return cxstring::createRef("CompoundLiteralExpr");
  case CXCursor_InitListExpr:
    return cxstring::createRef("InitListExpr");
  case CXCursor_AddrLabelExpr:
    return cxstring::createRef("AddrLabelExpr");
  case CXCursor_StmtExpr:
    return cxstring::createRef("StmtExpr");
  case CXCursor_GenericSelectionExpr:
    return cxstring::createRef("GenericSelectionExpr");
  case CXCursor_GNUNullExpr:
    return cxstring::createRef("GNUNullExpr");
  case CXCursor_CXXStaticCastExpr:
    return cxstring::createRef("CXXStaticCastExpr");
  case CXCursor_CXXDynamicCastExpr:
    return cxstring::createRef("CXXDynamicCastExpr");
  case CXCursor_CXXReinterpretCastExpr:
    return cxstring::createRef("CXXReinterpretCastExpr");
  case CXCursor_CXXConstCastExpr:
    return cxstring::createRef("CXXConstCastExpr");
  case CXCursor_CXXFunctionalCastExpr:
    return cxstring::createRef("CXXFunctionalCastExpr");
  case CXCursor_CXXAddrspaceCastExpr:
    return cxstring::createRef("CXXAddrspaceCastExpr");
  case CXCursor_CXXTypeidExpr:
    return cxstring::createRef("CXXTypeidExpr");
  case CXCursor_CXXBoolLiteralExpr:
    return cxstring::createRef("CXXBoolLiteralExpr");
  case CXCursor_CXXNullPtrLiteralExpr:
    return cxstring::createRef("CXXNullPtrLiteralExpr");
  case CXCursor_CXXThisExpr:
    return cxstring::createRef("CXXThisExpr");
  case CXCursor_CXXThrowExpr:
    return cxstring::createRef("CXXThrowExpr");
  case CXCursor_CXXNewExpr:
    return cxstring::createRef("CXXNewExpr");
  case CXCursor_CXXDeleteExpr:
    return cxstring::createRef("CXXDeleteExpr");
  case CXCursor_UnaryExpr:
    return cxstring::createRef("UnaryExpr");
  case CXCursor_ObjCStringLiteral:
    return cxstring::createRef("ObjCStringLiteral");
  case CXCursor_ObjCBoolLiteralExpr:
    return cxstring::createRef("ObjCBoolLiteralExpr");
  case CXCursor_ObjCAvailabilityCheckExpr:
    return cxstring::createRef("ObjCAvailabilityCheckExpr");
  case CXCursor_ObjCSelfExpr:
    return cxstring::createRef("ObjCSelfExpr");
  case CXCursor_ObjCEncodeExpr:
    return cxstring::createRef("ObjCEncodeExpr");
  case CXCursor_ObjCSelectorExpr:
    return cxstring::createRef("ObjCSelectorExpr");
  case CXCursor_ObjCProtocolExpr:
    return cxstring::createRef("ObjCProtocolExpr");
  case CXCursor_ObjCBridgedCastExpr:
    return cxstring::createRef("ObjCBridgedCastExpr");
  case CXCursor_BlockExpr:
    return cxstring::createRef("BlockExpr");
  case CXCursor_PackExpansionExpr:
    return cxstring::createRef("PackExpansionExpr");
  case CXCursor_SizeOfPackExpr:
    return cxstring::createRef("SizeOfPackExpr");
  case CXCursor_LambdaExpr:
    return cxstring::createRef("LambdaExpr");
  case CXCursor_UnexposedExpr:
    return cxstring::createRef("UnexposedExpr");
  case CXCursor_DeclRefExpr:
    return cxstring::createRef("DeclRefExpr");
  case CXCursor_MemberRefExpr:
    return cxstring::createRef("MemberRefExpr");
  case CXCursor_CallExpr:
    return cxstring::createRef("CallExpr");
  case CXCursor_ObjCMessageExpr:
    return cxstring::createRef("ObjCMessageExpr");
  case CXCursor_BuiltinBitCastExpr:
    return cxstring::createRef("BuiltinBitCastExpr");
  case CXCursor_UnexposedStmt:
    return cxstring::createRef("UnexposedStmt");
  case CXCursor_DeclStmt:
    return cxstring::createRef("DeclStmt");
  case CXCursor_LabelStmt:
    return cxstring::createRef("LabelStmt");
  case CXCursor_CompoundStmt:
    return cxstring::createRef("CompoundStmt");
  case CXCursor_CaseStmt:
    return cxstring::createRef("CaseStmt");
  case CXCursor_DefaultStmt:
    return cxstring::createRef("DefaultStmt");
  case CXCursor_IfStmt:
    return cxstring::createRef("IfStmt");
  case CXCursor_SwitchStmt:
    return cxstring::createRef("SwitchStmt");
  case CXCursor_WhileStmt:
    return cxstring::createRef("WhileStmt");
  case CXCursor_DoStmt:
    return cxstring::createRef("DoStmt");
  case CXCursor_ForStmt:
    return cxstring::createRef("ForStmt");
  case CXCursor_GotoStmt:
    return cxstring::createRef("GotoStmt");
  case CXCursor_IndirectGotoStmt:
    return cxstring::createRef("IndirectGotoStmt");
  case CXCursor_ContinueStmt:
    return cxstring::createRef("ContinueStmt");
  case CXCursor_BreakStmt:
    return cxstring::createRef("BreakStmt");
  case CXCursor_ReturnStmt:
    return cxstring::createRef("ReturnStmt");
  case CXCursor_GCCAsmStmt:
    return cxstring::createRef("GCCAsmStmt");
  case CXCursor_MSAsmStmt:
    return cxstring::createRef("MSAsmStmt");
  case CXCursor_ObjCAtTryStmt:
    return cxstring::createRef("ObjCAtTryStmt");
  case CXCursor_ObjCAtCatchStmt:
    return cxstring::createRef("ObjCAtCatchStmt");
  case CXCursor_ObjCAtFinallyStmt:
    return cxstring::createRef("ObjCAtFinallyStmt");
  case CXCursor_ObjCAtThrowStmt:
    return cxstring::createRef("ObjCAtThrowStmt");
  case CXCursor_ObjCAtSynchronizedStmt:
    return cxstring::createRef("ObjCAtSynchronizedStmt");
  case CXCursor_ObjCAutoreleasePoolStmt:
    return cxstring::createRef("ObjCAutoreleasePoolStmt");
  case CXCursor_ObjCForCollectionStmt:
    return cxstring::createRef("ObjCForCollectionStmt");
  case CXCursor_CXXCatchStmt:
    return cxstring::createRef("CXXCatchStmt");
  case CXCursor_CXXTryStmt:
    return cxstring::createRef("CXXTryStmt");
  case CXCursor_CXXForRangeStmt:
    return cxstring::createRef("CXXForRangeStmt");
  case CXCursor_SEHTryStmt:
    return cxstring::createRef("SEHTryStmt");
  case CXCursor_SEHExceptStmt:
    return cxstring::createRef("SEHExceptStmt");
  case CXCursor_SEHFinallyStmt:
    return cxstring::createRef("SEHFinallyStmt");
  case CXCursor_SEHLeaveStmt:
    return cxstring::createRef("SEHLeaveStmt");
  case CXCursor_NullStmt:
    return cxstring::createRef("NullStmt");
  case CXCursor_InvalidFile:
    return cxstring::createRef("InvalidFile");
  case CXCursor_InvalidCode:
    return cxstring::createRef("InvalidCode");
  case CXCursor_NoDeclFound:
    return cxstring::createRef("NoDeclFound");
  case CXCursor_NotImplemented:
    return cxstring::createRef("NotImplemented");
  case CXCursor_TranslationUnit:
    return cxstring::createRef("TranslationUnit");
  case CXCursor_UnexposedAttr:
    return cxstring::createRef("UnexposedAttr");
  case CXCursor_IBActionAttr:
    return cxstring::createRef("attribute(ibaction)");
  case CXCursor_IBOutletAttr:
    return cxstring::createRef("attribute(iboutlet)");
  case CXCursor_IBOutletCollectionAttr:
    return cxstring::createRef("attribute(iboutletcollection)");
  case CXCursor_CXXFinalAttr:
    return cxstring::createRef("attribute(final)");
  case CXCursor_CXXOverrideAttr:
    return cxstring::createRef("attribute(override)");
  case CXCursor_AnnotateAttr:
    return cxstring::createRef("attribute(annotate)");
  case CXCursor_AsmLabelAttr:
    return cxstring::createRef("asm label");
  case CXCursor_PackedAttr:
    return cxstring::createRef("attribute(packed)");
  case CXCursor_PureAttr:
    return cxstring::createRef("attribute(pure)");
  case CXCursor_ConstAttr:
    return cxstring::createRef("attribute(const)");
  case CXCursor_NoDuplicateAttr:
    return cxstring::createRef("attribute(noduplicate)");
  case CXCursor_CUDAConstantAttr:
    return cxstring::createRef("attribute(constant)");
  case CXCursor_CUDADeviceAttr:
    return cxstring::createRef("attribute(device)");
  case CXCursor_CUDAGlobalAttr:
    return cxstring::createRef("attribute(global)");
  case CXCursor_CUDAHostAttr:
    return cxstring::createRef("attribute(host)");
  case CXCursor_CUDASharedAttr:
    return cxstring::createRef("attribute(shared)");
  case CXCursor_VisibilityAttr:
    return cxstring::createRef("attribute(visibility)");
  case CXCursor_DLLExport:
    return cxstring::createRef("attribute(dllexport)");
  case CXCursor_DLLImport:
    return cxstring::createRef("attribute(dllimport)");
  case CXCursor_NSReturnsRetained:
    return cxstring::createRef("attribute(ns_returns_retained)");
  case CXCursor_NSReturnsNotRetained:
    return cxstring::createRef("attribute(ns_returns_not_retained)");
  case CXCursor_NSReturnsAutoreleased:
    return cxstring::createRef("attribute(ns_returns_autoreleased)");
  case CXCursor_NSConsumesSelf:
    return cxstring::createRef("attribute(ns_consumes_self)");
  case CXCursor_NSConsumed:
    return cxstring::createRef("attribute(ns_consumed)");
  case CXCursor_ObjCException:
    return cxstring::createRef("attribute(objc_exception)");
  case CXCursor_ObjCNSObject:
    return cxstring::createRef("attribute(NSObject)");
  case CXCursor_ObjCIndependentClass:
    return cxstring::createRef("attribute(objc_independent_class)");
  case CXCursor_ObjCPreciseLifetime:
    return cxstring::createRef("attribute(objc_precise_lifetime)");
  case CXCursor_ObjCReturnsInnerPointer:
    return cxstring::createRef("attribute(objc_returns_inner_pointer)");
  case CXCursor_ObjCRequiresSuper:
    return cxstring::createRef("attribute(objc_requires_super)");
  case CXCursor_ObjCRootClass:
    return cxstring::createRef("attribute(objc_root_class)");
  case CXCursor_ObjCSubclassingRestricted:
    return cxstring::createRef("attribute(objc_subclassing_restricted)");
  case CXCursor_ObjCExplicitProtocolImpl:
    return cxstring::createRef(
        "attribute(objc_protocol_requires_explicit_implementation)");
  case CXCursor_ObjCDesignatedInitializer:
    return cxstring::createRef("attribute(objc_designated_initializer)");
  case CXCursor_ObjCRuntimeVisible:
    return cxstring::createRef("attribute(objc_runtime_visible)");
  case CXCursor_ObjCBoxable:
    return cxstring::createRef("attribute(objc_boxable)");
  case CXCursor_FlagEnum:
    return cxstring::createRef("attribute(flag_enum)");
  case CXCursor_PreprocessingDirective:
    return cxstring::createRef("preprocessing directive");
  case CXCursor_MacroDefinition:
    return cxstring::createRef("macro definition");
  case CXCursor_MacroExpansion:
    return cxstring::createRef("macro expansion");
  case CXCursor_InclusionDirective:
    return cxstring::createRef("inclusion directive");
  case CXCursor_Namespace:
    return cxstring::createRef("Namespace");
  case CXCursor_LinkageSpec:
    return cxstring::createRef("LinkageSpec");
  case CXCursor_CXXBaseSpecifier:
    return cxstring::createRef("C++ base class specifier");
  case CXCursor_Constructor:
    return cxstring::createRef("CXXConstructor");
  case CXCursor_Destructor:
    return cxstring::createRef("CXXDestructor");
  case CXCursor_ConversionFunction:
    return cxstring::createRef("CXXConversion");
  case CXCursor_TemplateTypeParameter:
    return cxstring::createRef("TemplateTypeParameter");
  case CXCursor_NonTypeTemplateParameter:
    return cxstring::createRef("NonTypeTemplateParameter");
  case CXCursor_TemplateTemplateParameter:
    return cxstring::createRef("TemplateTemplateParameter");
  case CXCursor_FunctionTemplate:
    return cxstring::createRef("FunctionTemplate");
  case CXCursor_ClassTemplate:
    return cxstring::createRef("ClassTemplate");
  case CXCursor_ClassTemplatePartialSpecialization:
    return cxstring::createRef("ClassTemplatePartialSpecialization");
  case CXCursor_NamespaceAlias:
    return cxstring::createRef("NamespaceAlias");
  case CXCursor_UsingDirective:
    return cxstring::createRef("UsingDirective");
  case CXCursor_UsingDeclaration:
    return cxstring::createRef("UsingDeclaration");
  case CXCursor_TypeAliasDecl:
    return cxstring::createRef("TypeAliasDecl");
  case CXCursor_ObjCSynthesizeDecl:
    return cxstring::createRef("ObjCSynthesizeDecl");
  case CXCursor_ObjCDynamicDecl:
    return cxstring::createRef("ObjCDynamicDecl");
  case CXCursor_CXXAccessSpecifier:
    return cxstring::createRef("CXXAccessSpecifier");
  case CXCursor_ModuleImportDecl:
    return cxstring::createRef("ModuleImport");
  case CXCursor_OMPCanonicalLoop:
    return cxstring::createRef("OMPCanonicalLoop");
  case CXCursor_OMPParallelDirective:
    return cxstring::createRef("OMPParallelDirective");
  case CXCursor_OMPSimdDirective:
    return cxstring::createRef("OMPSimdDirective");
  case CXCursor_OMPTileDirective:
    return cxstring::createRef("OMPTileDirective");
  case CXCursor_OMPUnrollDirective:
    return cxstring::createRef("OMPUnrollDirective");
  case CXCursor_OMPForDirective:
    return cxstring::createRef("OMPForDirective");
  case CXCursor_OMPForSimdDirective:
    return cxstring::createRef("OMPForSimdDirective");
  case CXCursor_OMPSectionsDirective:
    return cxstring::createRef("OMPSectionsDirective");
  case CXCursor_OMPSectionDirective:
    return cxstring::createRef("OMPSectionDirective");
  case CXCursor_OMPSingleDirective:
    return cxstring::createRef("OMPSingleDirective");
  case CXCursor_OMPMasterDirective:
    return cxstring::createRef("OMPMasterDirective");
  case CXCursor_OMPCriticalDirective:
    return cxstring::createRef("OMPCriticalDirective");
  case CXCursor_OMPParallelForDirective:
    return cxstring::createRef("OMPParallelForDirective");
  case CXCursor_OMPParallelForSimdDirective:
    return cxstring::createRef("OMPParallelForSimdDirective");
  case CXCursor_OMPParallelMasterDirective:
    return cxstring::createRef("OMPParallelMasterDirective");
  case CXCursor_OMPParallelSectionsDirective:
    return cxstring::createRef("OMPParallelSectionsDirective");
  case CXCursor_OMPTaskDirective:
    return cxstring::createRef("OMPTaskDirective");
  case CXCursor_OMPTaskyieldDirective:
    return cxstring::createRef("OMPTaskyieldDirective");
  case CXCursor_OMPBarrierDirective:
    return cxstring::createRef("OMPBarrierDirective");
  case CXCursor_OMPTaskwaitDirective:
    return cxstring::createRef("OMPTaskwaitDirective");
  case CXCursor_OMPTaskgroupDirective:
    return cxstring::createRef("OMPTaskgroupDirective");
  case CXCursor_OMPFlushDirective:
    return cxstring::createRef("OMPFlushDirective");
  case CXCursor_OMPDepobjDirective:
    return cxstring::createRef("OMPDepobjDirective");
  case CXCursor_OMPScanDirective:
    return cxstring::createRef("OMPScanDirective");
  case CXCursor_OMPOrderedDirective:
    return cxstring::createRef("OMPOrderedDirective");
  case CXCursor_OMPAtomicDirective:
    return cxstring::createRef("OMPAtomicDirective");
  case CXCursor_OMPTargetDirective:
    return cxstring::createRef("OMPTargetDirective");
  case CXCursor_OMPTargetDataDirective:
    return cxstring::createRef("OMPTargetDataDirective");
  case CXCursor_OMPTargetEnterDataDirective:
    return cxstring::createRef("OMPTargetEnterDataDirective");
  case CXCursor_OMPTargetExitDataDirective:
    return cxstring::createRef("OMPTargetExitDataDirective");
  case CXCursor_OMPTargetParallelDirective:
    return cxstring::createRef("OMPTargetParallelDirective");
  case CXCursor_OMPTargetParallelForDirective:
    return cxstring::createRef("OMPTargetParallelForDirective");
  case CXCursor_OMPTargetUpdateDirective:
    return cxstring::createRef("OMPTargetUpdateDirective");
  case CXCursor_OMPTeamsDirective:
    return cxstring::createRef("OMPTeamsDirective");
  case CXCursor_OMPCancellationPointDirective:
    return cxstring::createRef("OMPCancellationPointDirective");
  case CXCursor_OMPCancelDirective:
    return cxstring::createRef("OMPCancelDirective");
  case CXCursor_OMPTaskLoopDirective:
    return cxstring::createRef("OMPTaskLoopDirective");
  case CXCursor_OMPTaskLoopSimdDirective:
    return cxstring::createRef("OMPTaskLoopSimdDirective");
  case CXCursor_OMPMasterTaskLoopDirective:
    return cxstring::createRef("OMPMasterTaskLoopDirective");
  case CXCursor_OMPMasterTaskLoopSimdDirective:
    return cxstring::createRef("OMPMasterTaskLoopSimdDirective");
  case CXCursor_OMPParallelMasterTaskLoopDirective:
    return cxstring::createRef("OMPParallelMasterTaskLoopDirective");
  case CXCursor_OMPParallelMasterTaskLoopSimdDirective:
    return cxstring::createRef("OMPParallelMasterTaskLoopSimdDirective");
  case CXCursor_OMPDistributeDirective:
    return cxstring::createRef("OMPDistributeDirective");
  case CXCursor_OMPDistributeParallelForDirective:
    return cxstring::createRef("OMPDistributeParallelForDirective");
  case CXCursor_OMPDistributeParallelForSimdDirective:
    return cxstring::createRef("OMPDistributeParallelForSimdDirective");
  case CXCursor_OMPDistributeSimdDirective:
    return cxstring::createRef("OMPDistributeSimdDirective");
  case CXCursor_OMPTargetParallelForSimdDirective:
    return cxstring::createRef("OMPTargetParallelForSimdDirective");
  case CXCursor_OMPTargetSimdDirective:
    return cxstring::createRef("OMPTargetSimdDirective");
  case CXCursor_OMPTeamsDistributeDirective:
    return cxstring::createRef("OMPTeamsDistributeDirective");
  case CXCursor_OMPTeamsDistributeSimdDirective:
    return cxstring::createRef("OMPTeamsDistributeSimdDirective");
  case CXCursor_OMPTeamsDistributeParallelForSimdDirective:
    return cxstring::createRef("OMPTeamsDistributeParallelForSimdDirective");
  case CXCursor_OMPTeamsDistributeParallelForDirective:
    return cxstring::createRef("OMPTeamsDistributeParallelForDirective");
  case CXCursor_OMPTargetTeamsDirective:
    return cxstring::createRef("OMPTargetTeamsDirective");
  case CXCursor_OMPTargetTeamsDistributeDirective:
    return cxstring::createRef("OMPTargetTeamsDistributeDirective");
  case CXCursor_OMPTargetTeamsDistributeParallelForDirective:
    return cxstring::createRef("OMPTargetTeamsDistributeParallelForDirective");
  case CXCursor_OMPTargetTeamsDistributeParallelForSimdDirective:
    return cxstring::createRef(
        "OMPTargetTeamsDistributeParallelForSimdDirective");
  case CXCursor_OMPTargetTeamsDistributeSimdDirective:
    return cxstring::createRef("OMPTargetTeamsDistributeSimdDirective");
  case CXCursor_OMPInteropDirective:
    return cxstring::createRef("OMPInteropDirective");
  case CXCursor_OMPDispatchDirective:
    return cxstring::createRef("OMPDispatchDirective");
  case CXCursor_OMPMaskedDirective:
    return cxstring::createRef("OMPMaskedDirective");
  case CXCursor_OverloadCandidate:
    return cxstring::createRef("OverloadCandidate");
  case CXCursor_TypeAliasTemplateDecl:
    return cxstring::createRef("TypeAliasTemplateDecl");
  case CXCursor_StaticAssert:
    return cxstring::createRef("StaticAssert");
  case CXCursor_FriendDecl:
    return cxstring::createRef("FriendDecl");
  case CXCursor_ConvergentAttr:
    return cxstring::createRef("attribute(convergent)");
  case CXCursor_WarnUnusedAttr:
    return cxstring::createRef("attribute(warn_unused)");
  case CXCursor_WarnUnusedResultAttr:
    return cxstring::createRef("attribute(warn_unused_result)");
  case CXCursor_AlignedAttr:
    return cxstring::createRef("attribute(aligned)");
  }
  llvm_unreachable("Unhandled CXCursorKind");
}
References clang::cxstring::createRef().
clang_getCursorLanguage()
CXLanguageKind clang_getCursorLanguage (CXCursor cursor)
Definition at line 8147 of file CIndex.cpp.
                                                        {
  if (clang_isDeclaration(cursor.kind))
    return getDeclLanguage(cxcursor::getCursorDecl(cursor));
  return CXLanguage_Invalid;
}
References clang_isDeclaration().
clang_getCursorLexicalParent()
CXCursor clang_getCursorLexicalParent (CXCursor cursor)
Definition at line 8239 of file CIndex.cpp.
                                                       {
  if (clang_isDeclaration(cursor.kind)) {
    if (const Decl *D = getCursorDecl(cursor)) {
      const DeclContext *DC = D->getLexicalDeclContext();
      if (!DC)
        return clang_getNullCursor();
      return MakeCXCursor(maybeGetTemplateCursor(cast<Decl>(DC)),
                          getCursorTU(cursor));
    }
  }
  // FIXME: Note that we can't easily compute the lexical context of a
  // statement or expression, so we return nothing.
  return clang_getNullCursor();
}
References clang_getNullCursor(), clang_isDeclaration(), clang::cxcursor::getCursorDecl(), and clang::cxcursor::MakeCXCursor().
clang_getCursorLinkage()
CXLinkageKind clang_getCursorLinkage (CXCursor cursor)
Definition at line 7857 of file CIndex.cpp.
                                                      {
  if (!clang_isDeclaration(cursor.kind))
    return CXLinkage_Invalid;
  const Decl *D = cxcursor::getCursorDecl(cursor);
  if (const NamedDecl *ND = dyn_cast_or_null<NamedDecl>(D))
    switch (ND->getLinkageInternal()) {
    case NoLinkage:
    case VisibleNoLinkage:
      return CXLinkage_NoLinkage;
    case ModuleInternalLinkage:
    case InternalLinkage:
      return CXLinkage_Internal;
    case UniqueExternalLinkage:
      return CXLinkage_UniqueExternal;
    case ModuleLinkage:
    case ExternalLinkage:
      return CXLinkage_External;
    };
  return CXLinkage_Invalid;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_getCursorLocation()
CXSourceLocation clang_getCursorLocation (CXCursor C)
Definition at line 5986 of file CIndex.cpp.
                                                     {
  if (clang_isReference(C.kind)) {
    switch (C.kind) {
    case CXCursor_ObjCSuperClassRef: {
      std::pair<const ObjCInterfaceDecl *, SourceLocation> P =
          getCursorObjCSuperClassRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_ObjCProtocolRef: {
      std::pair<const ObjCProtocolDecl *, SourceLocation> P =
          getCursorObjCProtocolRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_ObjCClassRef: {
      std::pair<const ObjCInterfaceDecl *, SourceLocation> P =
          getCursorObjCClassRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_TypeRef: {
      std::pair<const TypeDecl *, SourceLocation> P = getCursorTypeRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_TemplateRef: {
      std::pair<const TemplateDecl *, SourceLocation> P =
          getCursorTemplateRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_NamespaceRef: {
      std::pair<const NamedDecl *, SourceLocation> P = getCursorNamespaceRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_MemberRef: {
      std::pair<const FieldDecl *, SourceLocation> P = getCursorMemberRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_VariableRef: {
      std::pair<const VarDecl *, SourceLocation> P = getCursorVariableRef(C);
      return cxloc::translateSourceLocation(P.first->getASTContext(), P.second);
    }
    case CXCursor_CXXBaseSpecifier: {
      const CXXBaseSpecifier *BaseSpec = getCursorCXXBaseSpecifier(C);
      if (!BaseSpec)
        return clang_getNullLocation();
      if (TypeSourceInfo *TSInfo = BaseSpec->getTypeSourceInfo())
        return cxloc::translateSourceLocation(
            getCursorContext(C), TSInfo->getTypeLoc().getBeginLoc());
      return cxloc::translateSourceLocation(getCursorContext(C),
                                            BaseSpec->getBeginLoc());
    }
    case CXCursor_LabelRef: {
      std::pair<const LabelStmt *, SourceLocation> P = getCursorLabelRef(C);
      return cxloc::translateSourceLocation(getCursorContext(C), P.second);
    }
    case CXCursor_OverloadedDeclRef:
      return cxloc::translateSourceLocation(
          getCursorContext(C), getCursorOverloadedDeclRef(C).second);
    default:
      // FIXME: Need a way to enumerate all non-reference cases.
      llvm_unreachable("Missed a reference kind");
    }
  }
  if (clang_isExpression(C.kind))
    return cxloc::translateSourceLocation(
        getCursorContext(C), getLocationFromExpr(getCursorExpr(C)));
  if (clang_isStatement(C.kind))
    return cxloc::translateSourceLocation(getCursorContext(C),
                                          getCursorStmt(C)->getBeginLoc());
  if (C.kind == CXCursor_PreprocessingDirective) {
    SourceLocation L = cxcursor::getCursorPreprocessingDirective(C).getBegin();
    return cxloc::translateSourceLocation(getCursorContext(C), L);
  }
  if (C.kind == CXCursor_MacroExpansion) {
    SourceLocation L =
        cxcursor::getCursorMacroExpansion(C).getSourceRange().getBegin();
    return cxloc::translateSourceLocation(getCursorContext(C), L);
  }
  if (C.kind == CXCursor_MacroDefinition) {
    SourceLocation L = cxcursor::getCursorMacroDefinition(C)->getLocation();
    return cxloc::translateSourceLocation(getCursorContext(C), L);
  }
  if (C.kind == CXCursor_InclusionDirective) {
    SourceLocation L =
        cxcursor::getCursorInclusionDirective(C)->getSourceRange().getBegin();
    return cxloc::translateSourceLocation(getCursorContext(C), L);
  }
  if (clang_isAttribute(C.kind)) {
    SourceLocation L = cxcursor::getCursorAttr(C)->getLocation();
    return cxloc::translateSourceLocation(getCursorContext(C), L);
  }
  if (!clang_isDeclaration(C.kind))
    return clang_getNullLocation();
  const Decl *D = getCursorDecl(C);
  if (!D)
    return clang_getNullLocation();
  SourceLocation Loc = D->getLocation();
  // FIXME: Multiple variables declared in a single declaration
  // currently lack the information needed to correctly determine their
  // ranges when accounting for the type-specifier. We use context
  // stored in the CXCursor to determine if the VarDecl is in a DeclGroup,
  // and if so, whether it is the first decl.
  if (const VarDecl *VD = dyn_cast<VarDecl>(D)) {
    if (!cxcursor::isFirstInDeclGroup(C))
      Loc = VD->getLocation();
  }
  // For ObjC methods, give the start location of the method name.
  if (const ObjCMethodDecl *MD = dyn_cast<ObjCMethodDecl>(D))
    Loc = MD->getSelectorStartLoc();
  return cxloc::translateSourceLocation(getCursorContext(C), Loc);
}
References clang_getNullLocation(), clang_isExpression(), clang_isReference(), clang::cxcursor::getCursorContext(), clang::cxcursor::getCursorCXXBaseSpecifier(), clang::cxcursor::getCursorLabelRef(), clang::cxcursor::getCursorMemberRef(), clang::cxcursor::getCursorNamespaceRef(), clang::cxcursor::getCursorObjCClassRef(), clang::cxcursor::getCursorObjCProtocolRef(), clang::cxcursor::getCursorObjCSuperClassRef(), clang::cxcursor::getCursorOverloadedDeclRef(), clang::cxcursor::getCursorTemplateRef(), clang::cxcursor::getCursorTypeRef(), and clang::cxcursor::getCursorVariableRef().
Referenced by clang_Cursor_getSpellingNameRange(), and clang::cxindex::Logger::operator<<().
clang_getCursorPlatformAvailability()
int clang_getCursorPlatformAvailability (CXCursor cursor, int * always_deprecated, CXString * deprecated_message, int * always_unavailable, CXString * unavailable_message, CXPlatformAvailability * availability, int availability_size)
Definition at line 8097 of file CIndex.cpp.
                                                               {
  if (always_deprecated)
    *always_deprecated = 0;
  if (deprecated_message)
    *deprecated_message = cxstring::createEmpty();
  if (always_unavailable)
    *always_unavailable = 0;
  if (unavailable_message)
    *unavailable_message = cxstring::createEmpty();
  if (!clang_isDeclaration(cursor.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(cursor);
  if (!D)
    return 0;
  SmallVector<AvailabilityAttr *, 8> AvailabilityAttrs;
  getCursorPlatformAvailabilityForDecl(D, always_deprecated, deprecated_message,
                                       always_unavailable, unavailable_message,
                                       AvailabilityAttrs);
  for (const auto &Avail :
       llvm::enumerate(llvm::makeArrayRef(AvailabilityAttrs)
                           .take_front(availability_size))) {
    availability[Avail.index()].Platform =
        cxstring::createDup(Avail.value()->getPlatform()->getName());
    availability[Avail.index()].Introduced =
        convertVersion(Avail.value()->getIntroduced());
    availability[Avail.index()].Deprecated =
        convertVersion(Avail.value()->getDeprecated());
    availability[Avail.index()].Obsoleted =
        convertVersion(Avail.value()->getObsoleted());
    availability[Avail.index()].Unavailable = Avail.value()->getUnavailable();
    availability[Avail.index()].Message =
        cxstring::createDup(Avail.value()->getMessage());
  }
  return AvailabilityAttrs.size();
}
References clang_isDeclaration(), clang::cxstring::createEmpty(), and clang::cxcursor::getCursorDecl().
clang_getCursorPrettyPrinted()
CXString clang_getCursorPrettyPrinted (CXCursor C, CXPrintingPolicy cxPolicy)
Definition at line 5099 of file CIndex.cpp.
                                                                             {
  if (clang_Cursor_isNull(C))
    return cxstring::createEmpty();
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = getCursorDecl(C);
    if (!D)
      return cxstring::createEmpty();
    SmallString<128> Str;
    llvm::raw_svector_ostream OS(Str);
    PrintingPolicy *UserPolicy = static_cast<PrintingPolicy *>(cxPolicy);
    D->print(OS, UserPolicy ? *UserPolicy
                            : getCursorContext(C).getPrintingPolicy());
    return cxstring::createDup(OS.str());
  }
  return cxstring::createEmpty();
}
References clang_Cursor_isNull(), clang_isDeclaration(), clang::cxstring::createDup(), clang::cxstring::createEmpty(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorDecl().
clang_getCursorPrintingPolicy()
CXPrintingPolicy clang_getCursorPrintingPolicy (CXCursor C)
Definition at line 4931 of file CIndex.cpp.
                                                           {
  if (clang_Cursor_isNull(C))
    return 0;
  return new PrintingPolicy(getCursorContext(C).getPrintingPolicy());
}
References clang_Cursor_isNull(), and clang::cxcursor::getCursorContext().
clang_getCursorReferenced()
CXCursor clang_getCursorReferenced (CXCursor C)
Definition at line 6301 of file CIndex.cpp.
                                               {
  if (clang_isInvalid(C.kind))
    return clang_getNullCursor();
  CXTranslationUnit tu = getCursorTU(C);
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = getCursorDecl(C);
    if (!D)
      return clang_getNullCursor();
    if (const UsingDecl *Using = dyn_cast<UsingDecl>(D))
      return MakeCursorOverloadedDeclRef(Using, D->getLocation(), tu);
    if (const ObjCPropertyImplDecl *PropImpl =
            dyn_cast<ObjCPropertyImplDecl>(D))
      if (ObjCPropertyDecl *Property = PropImpl->getPropertyDecl())
        return MakeCXCursor(Property, tu);
    return C;
  }
  if (clang_isExpression(C.kind)) {
    const Expr *E = getCursorExpr(C);
    const Decl *D = getDeclFromExpr(E);
    if (D) {
      CXCursor declCursor = MakeCXCursor(D, tu);
      declCursor = getSelectorIdentifierCursor(getSelectorIdentifierIndex(C),
                                               declCursor);
      return declCursor;
    }
    if (const OverloadExpr *Ovl = dyn_cast_or_null<OverloadExpr>(E))
      return MakeCursorOverloadedDeclRef(Ovl, tu);
    return clang_getNullCursor();
  }
  if (clang_isStatement(C.kind)) {
    const Stmt *S = getCursorStmt(C);
    if (const GotoStmt *Goto = dyn_cast_or_null<GotoStmt>(S))
      if (LabelDecl *label = Goto->getLabel())
        if (LabelStmt *labelS = label->getStmt())
          return MakeCXCursor(labelS, getCursorDecl(C), tu);
    return clang_getNullCursor();
  }
  if (C.kind == CXCursor_MacroExpansion) {
    if (const MacroDefinitionRecord *Def =
            getCursorMacroExpansion(C).getDefinition())
      return MakeMacroDefinitionCursor(Def, tu);
  }
  if (!clang_isReference(C.kind))
    return clang_getNullCursor();
  switch (C.kind) {
  case CXCursor_ObjCSuperClassRef:
    return MakeCXCursor(getCursorObjCSuperClassRef(C).first, tu);
  case CXCursor_ObjCProtocolRef: {
    const ObjCProtocolDecl *Prot = getCursorObjCProtocolRef(C).first;
    if (const ObjCProtocolDecl *Def = Prot->getDefinition())
      return MakeCXCursor(Def, tu);
    return MakeCXCursor(Prot, tu);
  }
  case CXCursor_ObjCClassRef: {
    const ObjCInterfaceDecl *Class = getCursorObjCClassRef(C).first;
    if (const ObjCInterfaceDecl *Def = Class->getDefinition())
      return MakeCXCursor(Def, tu);
    return MakeCXCursor(Class, tu);
  }
  case CXCursor_TypeRef:
    return MakeCXCursor(getCursorTypeRef(C).first, tu);
  case CXCursor_TemplateRef:
    return MakeCXCursor(getCursorTemplateRef(C).first, tu);
  case CXCursor_NamespaceRef:
    return MakeCXCursor(getCursorNamespaceRef(C).first, tu);
  case CXCursor_MemberRef:
    return MakeCXCursor(getCursorMemberRef(C).first, tu);
  case CXCursor_CXXBaseSpecifier: {
    const CXXBaseSpecifier *B = cxcursor::getCursorCXXBaseSpecifier(C);
    return clang_getTypeDeclaration(cxtype::MakeCXType(B->getType(), tu));
  }
  case CXCursor_LabelRef:
    // FIXME: We end up faking the "parent" declaration here because we
    // don't want to make CXCursor larger.
    return MakeCXCursor(
        getCursorLabelRef(C).first,
        cxtu::getASTUnit(tu)->getASTContext().getTranslationUnitDecl(), tu);
  case CXCursor_OverloadedDeclRef:
    return C;
  case CXCursor_VariableRef:
    return MakeCXCursor(getCursorVariableRef(C).first, tu);
  default:
    // We would prefer to enumerate all non-reference cursor kinds here.
    llvm_unreachable("Unhandled reference cursor kind");
  }
}
References clang_getNullCursor(), clang_isDeclaration(), clang_isExpression(), clang_isInvalid(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorExpr(), clang::cxcursor::getCursorTU(), clang::cxcursor::MakeCursorOverloadedDeclRef(), and clang::cxcursor::MakeCXCursor().
Referenced by clang_getCursorDefinition().
clang_getCursorReferenceNameRange()
CXSourceRange clang_getCursorReferenceNameRange (CXCursor C, unsigned NameFlags, unsigned PieceIndex)
Definition at line 6732 of file CIndex.cpp.
                                                                     {
  RefNamePieces Pieces;
  switch (C.kind) {
  case CXCursor_MemberRefExpr:
    if (const MemberExpr *E = dyn_cast<MemberExpr>(getCursorExpr(C)))
      Pieces = buildPieces(NameFlags, true, E->getMemberNameInfo(),
                           E->getQualifierLoc().getSourceRange());
    break;
  case CXCursor_DeclRefExpr:
    if (const DeclRefExpr *E = dyn_cast<DeclRefExpr>(getCursorExpr(C))) {
      SourceRange TemplateArgLoc(E->getLAngleLoc(), E->getRAngleLoc());
      Pieces =
          buildPieces(NameFlags, false, E->getNameInfo(),
                      E->getQualifierLoc().getSourceRange(), &TemplateArgLoc);
    }
    break;
  case CXCursor_CallExpr:
    if (const CXXOperatorCallExpr *OCE =
            dyn_cast<CXXOperatorCallExpr>(getCursorExpr(C))) {
      const Expr *Callee = OCE->getCallee();
      if (const ImplicitCastExpr *ICE = dyn_cast<ImplicitCastExpr>(Callee))
        Callee = ICE->getSubExpr();
      if (const DeclRefExpr *DRE = dyn_cast<DeclRefExpr>(Callee))
        Pieces = buildPieces(NameFlags, false, DRE->getNameInfo(),
                             DRE->getQualifierLoc().getSourceRange());
    }
    break;
  default:
    break;
  }
  if (Pieces.empty()) {
    if (PieceIndex == 0)
      return clang_getCursorExtent(C);
  } else if (PieceIndex < Pieces.size()) {
    SourceRange R = Pieces[PieceIndex];
    if (R.isValid())
      return cxloc::translateSourceRange(getCursorContext(C), R);
  }
  return clang_getNullRange();
}
References clang_getCursorExtent(), clang_getNullRange(), clang::cxcursor::getCursorContext(), clang::cxcursor::getCursorExpr(), and clang::cxloc::translateSourceRange().
clang_getCursorSemanticParent()
CXCursor clang_getCursorSemanticParent (CXCursor cursor)
Definition at line 8219 of file CIndex.cpp.
                                                        {
  if (clang_isDeclaration(cursor.kind)) {
    if (const Decl *D = getCursorDecl(cursor)) {
      const DeclContext *DC = D->getDeclContext();
      if (!DC)
        return clang_getNullCursor();
      return MakeCXCursor(maybeGetTemplateCursor(cast<Decl>(DC)),
                          getCursorTU(cursor));
    }
  }
  if (clang_isStatement(cursor.kind) || clang_isExpression(cursor.kind)) {
    if (const Decl *D = getCursorDecl(cursor))
      return MakeCXCursor(D, getCursorTU(cursor));
  }
  return clang_getNullCursor();
}
References clang_getNullCursor(), clang_isDeclaration(), clang::cxcursor::getCursorDecl(), and clang::cxcursor::MakeCXCursor().
Referenced by clang_Cursor_getOffsetOfField().
clang_getCursorSpelling()
CXString clang_getCursorSpelling (CXCursor C)
Definition at line 4634 of file CIndex.cpp.
                                             {
  if (clang_isTranslationUnit(C.kind))
    return clang_getTranslationUnitSpelling(getCursorTU(C));
  if (clang_isReference(C.kind)) {
    switch (C.kind) {
    case CXCursor_ObjCSuperClassRef: {
      const ObjCInterfaceDecl *Super = getCursorObjCSuperClassRef(C).first;
      return cxstring::createRef(Super->getIdentifier()->getNameStart());
    }
    case CXCursor_ObjCClassRef: {
      const ObjCInterfaceDecl *Class = getCursorObjCClassRef(C).first;
      return cxstring::createRef(Class->getIdentifier()->getNameStart());
    }
    case CXCursor_ObjCProtocolRef: {
      const ObjCProtocolDecl *OID = getCursorObjCProtocolRef(C).first;
      assert(OID && "getCursorSpelling(): Missing protocol decl");
      return cxstring::createRef(OID->getIdentifier()->getNameStart());
    }
    case CXCursor_CXXBaseSpecifier: {
      const CXXBaseSpecifier *B = getCursorCXXBaseSpecifier(C);
      return cxstring::createDup(B->getType().getAsString());
    }
    case CXCursor_TypeRef: {
      const TypeDecl *Type = getCursorTypeRef(C).first;
      assert(Type && "Missing type decl");
      return cxstring::createDup(
          getCursorContext(C).getTypeDeclType(Type).getAsString());
    }
    case CXCursor_TemplateRef: {
      const TemplateDecl *Template = getCursorTemplateRef(C).first;
      assert(Template && "Missing template decl");
      return cxstring::createDup(Template->getNameAsString());
    }
    case CXCursor_NamespaceRef: {
      const NamedDecl *NS = getCursorNamespaceRef(C).first;
      assert(NS && "Missing namespace decl");
      return cxstring::createDup(NS->getNameAsString());
    }
    case CXCursor_MemberRef: {
      const FieldDecl *Field = getCursorMemberRef(C).first;
      assert(Field && "Missing member decl");
      return cxstring::createDup(Field->getNameAsString());
    }
    case CXCursor_LabelRef: {
      const LabelStmt *Label = getCursorLabelRef(C).first;
      assert(Label && "Missing label");
      return cxstring::createRef(Label->getName());
    }
    case CXCursor_OverloadedDeclRef: {
      OverloadedDeclRefStorage Storage = getCursorOverloadedDeclRef(C).first;
      if (const Decl *D = Storage.dyn_cast<const Decl *>()) {
        if (const NamedDecl *ND = dyn_cast<NamedDecl>(D))
          return cxstring::createDup(ND->getNameAsString());
        return cxstring::createEmpty();
      }
      if (const OverloadExpr *E = Storage.dyn_cast<const OverloadExpr *>())
        return cxstring::createDup(E->getName().getAsString());
      OverloadedTemplateStorage *Ovl =
          Storage.get<OverloadedTemplateStorage *>();
      if (Ovl->size() == 0)
        return cxstring::createEmpty();
      return cxstring::createDup((*Ovl->begin())->getNameAsString());
    }
    case CXCursor_VariableRef: {
      const VarDecl *Var = getCursorVariableRef(C).first;
      assert(Var && "Missing variable decl");
      return cxstring::createDup(Var->getNameAsString());
    }
    default:
      return cxstring::createRef("<not implemented>");
    }
  }
  if (clang_isExpression(C.kind)) {
    const Expr *E = getCursorExpr(C);
    if (C.kind == CXCursor_ObjCStringLiteral ||
        C.kind == CXCursor_StringLiteral) {
      const StringLiteral *SLit;
      if (const ObjCStringLiteral *OSL = dyn_cast<ObjCStringLiteral>(E)) {
        SLit = OSL->getString();
      } else {
        SLit = cast<StringLiteral>(E);
      }
      SmallString<256> Buf;
      llvm::raw_svector_ostream OS(Buf);
      SLit->outputString(OS);
      return cxstring::createDup(OS.str());
    }
    const Decl *D = getDeclFromExpr(getCursorExpr(C));
    if (D)
      return getDeclSpelling(D);
    return cxstring::createEmpty();
  }
  if (clang_isStatement(C.kind)) {
    const Stmt *S = getCursorStmt(C);
    if (const LabelStmt *Label = dyn_cast_or_null<LabelStmt>(S))
      return cxstring::createRef(Label->getName());
    return cxstring::createEmpty();
  }
  if (C.kind == CXCursor_MacroExpansion)
    return cxstring::createRef(
        getCursorMacroExpansion(C).getName()->getNameStart());
  if (C.kind == CXCursor_MacroDefinition)
    return cxstring::createRef(
        getCursorMacroDefinition(C)->getName()->getNameStart());
  if (C.kind == CXCursor_InclusionDirective)
    return cxstring::createDup(getCursorInclusionDirective(C)->getFileName());
  if (clang_isDeclaration(C.kind))
    return getDeclSpelling(getCursorDecl(C));
  if (C.kind == CXCursor_AnnotateAttr) {
    const AnnotateAttr *AA = cast<AnnotateAttr>(cxcursor::getCursorAttr(C));
    return cxstring::createDup(AA->getAnnotation());
  }
  if (C.kind == CXCursor_AsmLabelAttr) {
    const AsmLabelAttr *AA = cast<AsmLabelAttr>(cxcursor::getCursorAttr(C));
    return cxstring::createDup(AA->getLabel());
  }
  if (C.kind == CXCursor_PackedAttr) {
    return cxstring::createRef("packed");
  }
  if (C.kind == CXCursor_VisibilityAttr) {
    const VisibilityAttr *AA = cast<VisibilityAttr>(cxcursor::getCursorAttr(C));
    switch (AA->getVisibility()) {
    case VisibilityAttr::VisibilityType::Default:
      return cxstring::createRef("default");
    case VisibilityAttr::VisibilityType::Hidden:
      return cxstring::createRef("hidden");
    case VisibilityAttr::VisibilityType::Protected:
      return cxstring::createRef("protected");
    }
    llvm_unreachable("unknown visibility type");
  }
  return cxstring::createEmpty();
}
References clang_getTranslationUnitSpelling(), clang_isExpression(), clang_isReference(), clang_isTranslationUnit(), clang::cxstring::createDup(), clang::cxstring::createEmpty(), clang::cxstring::createRef(), clang::cxcursor::getCursorContext(), clang::cxcursor::getCursorCXXBaseSpecifier(), clang::cxcursor::getCursorExpr(), clang::cxcursor::getCursorLabelRef(), clang::cxcursor::getCursorMemberRef(), clang::cxcursor::getCursorNamespaceRef(), clang::cxcursor::getCursorObjCClassRef(), clang::cxcursor::getCursorObjCProtocolRef(), clang::cxcursor::getCursorObjCSuperClassRef(), clang::cxcursor::getCursorOverloadedDeclRef(), clang::cxcursor::getCursorTemplateRef(), clang::cxcursor::getCursorTU(), clang::cxcursor::getCursorTypeRef(), and clang::cxcursor::getCursorVariableRef().
Referenced by clang_getCursorDisplayName().
clang_getCursorTLSKind()
CXTLSKind clang_getCursorTLSKind (CXCursor cursor)
Definition at line 8154 of file CIndex.cpp.
                                                  {
  const Decl *D = cxcursor::getCursorDecl(cursor);
  if (const VarDecl *VD = dyn_cast<VarDecl>(D)) {
    switch (VD->getTLSKind()) {
    case VarDecl::TLS_None:
      return CXTLS_None;
    case VarDecl::TLS_Dynamic:
      return CXTLS_Dynamic;
    case VarDecl::TLS_Static:
      return CXTLS_Static;
    }
  }
  return CXTLS_None;
}
References clang::cxcursor::getCursorDecl().
clang_getCursorVisibility()
CXVisibilityKind clang_getCursorVisibility (CXCursor cursor)
Definition at line 7884 of file CIndex.cpp.
                                                            {
  if (!clang_isDeclaration(cursor.kind))
    return CXVisibility_Invalid;
  const Decl *D = cxcursor::getCursorDecl(cursor);
  if (const NamedDecl *ND = dyn_cast_or_null<NamedDecl>(D))
    switch (ND->getVisibility()) {
    case HiddenVisibility:
      return CXVisibility_Hidden;
    case ProtectedVisibility:
      return CXVisibility_Protected;
    case DefaultVisibility:
      return CXVisibility_Default;
    };
  return CXVisibility_Invalid;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_getCXTUResourceUsage()
CXTUResourceUsage clang_getCXTUResourceUsage (CXTranslationUnit TU)
Definition at line 8736 of file CIndex.cpp.
                                                                   {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    CXTUResourceUsage usage = {(void *)nullptr, 0, nullptr};
    return usage;
  }
  ASTUnit *astUnit = cxtu::getASTUnit(TU);
  std::unique_ptr<MemUsageEntries> entries(new MemUsageEntries());
  ASTContext &astContext = astUnit->getASTContext();
  // How much memory is used by AST nodes and types?
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_AST,
      (unsigned long)astContext.getASTAllocatedMemory());
  // How much memory is used by identifiers?
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_Identifiers,
      (unsigned long)astContext.Idents.getAllocator().getTotalMemory());
  // How much memory is used for selectors?
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_Selectors,
      (unsigned long)astContext.Selectors.getTotalMemory());
  // How much memory is used by ASTContext's side tables?
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_AST_SideTables,
      (unsigned long)astContext.getSideTableAllocatedMemory());
  // How much memory is used for caching global code completion results?
  unsigned long completionBytes = 0;
  if (GlobalCodeCompletionAllocator *completionAllocator =
          astUnit->getCachedCompletionAllocator().get()) {
    completionBytes = completionAllocator->getTotalMemory();
  }
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_GlobalCompletionResults, completionBytes);
  // How much memory is being used by SourceManager's content cache?
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_SourceManagerContentCache,
      (unsigned long)astContext.getSourceManager().getContentCacheSize());
  // How much memory is being used by the MemoryBuffer's in SourceManager?
  const SourceManager::MemoryBufferSizes &srcBufs =
      astUnit->getSourceManager().getMemoryBufferSizes();
  createCXTUResourceUsageEntry(*entries,
                               CXTUResourceUsage_SourceManager_Membuffer_Malloc,
                               (unsigned long)srcBufs.malloc_bytes);
  createCXTUResourceUsageEntry(*entries,
                               CXTUResourceUsage_SourceManager_Membuffer_MMap,
                               (unsigned long)srcBufs.mmap_bytes);
  createCXTUResourceUsageEntry(
      *entries, CXTUResourceUsage_SourceManager_DataStructures,
      (unsigned long)astContext.getSourceManager().getDataStructureSizes());
  // How much memory is being used by the ExternalASTSource?
  if (ExternalASTSource *esrc = astContext.getExternalSource()) {
    const ExternalASTSource::MemoryBufferSizes &sizes =
        esrc->getMemoryBufferSizes();
    createCXTUResourceUsageEntry(
        *entries, CXTUResourceUsage_ExternalASTSource_Membuffer_Malloc,
        (unsigned long)sizes.malloc_bytes);
    createCXTUResourceUsageEntry(
        *entries, CXTUResourceUsage_ExternalASTSource_Membuffer_MMap,
        (unsigned long)sizes.mmap_bytes);
  }
  // How much memory is being used by the Preprocessor?
  Preprocessor &pp = astUnit->getPreprocessor();
  createCXTUResourceUsageEntry(*entries, CXTUResourceUsage_Preprocessor,
                               pp.getTotalMemory());
  if (PreprocessingRecord *pRec = pp.getPreprocessingRecord()) {
    createCXTUResourceUsageEntry(*entries,
                                 CXTUResourceUsage_PreprocessingRecord,
                                 pRec->getTotalMemory());
  }
  createCXTUResourceUsageEntry(*entries,
                               CXTUResourceUsage_Preprocessor_HeaderSearch,
                               pp.getHeaderSearchInfo().getTotalMemory());
  CXTUResourceUsage usage = {(void *)entries.get(), (unsigned)entries->size(),
                             !entries->empty() ? &(*entries)[0] : nullptr};
  (void)entries.release();
  return usage;
}
Referenced by clang::PrintLibclangResourceUsage(), and PrintMemoryUsage().
clang_getDefinitionSpellingAndExtent()
void clang_getDefinitionSpellingAndExtent (CXCursor C, const char ** startBuf, const char ** endBuf, unsigned * startLine, unsigned * startColumn, unsigned * endLine, unsigned * endColumn)
Definition at line 6716 of file CIndex.cpp.
                                                                   {
  assert(getCursorDecl(C) && "CXCursor has null decl");
  const FunctionDecl *FD = dyn_cast<FunctionDecl>(getCursorDecl(C));
  CompoundStmt *Body = dyn_cast<CompoundStmt>(FD->getBody());
  SourceManager &SM = FD->getASTContext().getSourceManager();
  *startBuf = SM.getCharacterData(Body->getLBracLoc());
  *endBuf = SM.getCharacterData(Body->getRBracLoc());
  *startLine = SM.getSpellingLineNumber(Body->getLBracLoc());
  *startColumn = SM.getSpellingColumnNumber(Body->getLBracLoc());
  *endLine = SM.getSpellingLineNumber(Body->getRBracLoc());
  *endColumn = SM.getSpellingColumnNumber(Body->getRBracLoc());
}
References clang::cxcursor::getCursorDecl().
clang_getFile()
CXFile clang_getFile (CXTranslationUnit TU, const char * file_name)
Definition at line 4395 of file CIndex.cpp.
                                                                  {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return nullptr;
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  FileManager &FMgr = CXXUnit->getFileManager();
  auto File = FMgr.getFile(file_name);
  if (!File)
    return nullptr;
  return const_cast<FileEntry *>(*File);
}
clang_getFileContents()
const char* clang_getFileContents (CXTranslationUnit TU, CXFile file, size_t * size)
Definition at line 4410 of file CIndex.cpp.
                                                {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return nullptr;
  }
  const SourceManager &SM = cxtu::getASTUnit(TU)->getSourceManager();
  FileID fid = SM.translateFile(static_cast<FileEntry *>(file));
  llvm::Optional<llvm::MemoryBufferRef> buf = SM.getBufferOrNone(fid);
  if (!buf) {
    if (size)
      *size = 0;
    return nullptr;
  }
  if (size)
    *size = buf->getBufferSize();
  return buf->getBufferStart();
}
clang_getFileName()
CXString clang_getFileName (CXFile SFile)
Definition at line 4379 of file CIndex.cpp.
                                         {
  if (!SFile)
    return cxstring::createNull();
  FileEntry *FEnt = static_cast<FileEntry *>(SFile);
  return cxstring::createRef(FEnt->getName());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
Referenced by InclusionVisitor(), and clang::cxindex::Logger::operator<<().
clang_getFileTime()
time_t clang_getFileTime (CXFile SFile)
Definition at line 4387 of file CIndex.cpp.
                                       {
  if (!SFile)
    return 0;
  FileEntry *FEnt = static_cast<FileEntry *>(SFile);
  return FEnt->getModificationTime();
}
clang_getFileUniqueID()
int clang_getFileUniqueID (CXFile file, CXFileUniqueID * outID)
Definition at line 4446 of file CIndex.cpp.
                                                              {
  if (!file || !outID)
    return 1;
  FileEntry *FEnt = static_cast<FileEntry *>(file);
  const llvm::sys::fs::UniqueID &ID = FEnt->getUniqueID();
  outID->data[0] = ID.getDevice();
  outID->data[1] = ID.getFile();
  outID->data[2] = FEnt->getModificationTime();
  return 0;
}
clang_getIBOutletCollectionType()
CXType clang_getIBOutletCollectionType (CXCursor C)
Definition at line 8664 of file CIndex.cpp.
                                                   {
  if (C.kind != CXCursor_IBOutletCollectionAttr)
    return cxtype::MakeCXType(QualType(), cxcursor::getCursorTU(C));
  const IBOutletCollectionAttr *A =
      cast<IBOutletCollectionAttr>(cxcursor::getCursorAttr(C));
  return cxtype::MakeCXType(A->getInterface(), cxcursor::getCursorTU(C));
}
References clang::cxcursor::getCursorAttr(), clang::cxcursor::getCursorTU(), and clang::cxtype::MakeCXType().
clang_getIncludedFile()
CXFile clang_getIncludedFile (CXCursor cursor)
Definition at line 8256 of file CIndex.cpp.
                                              {
  if (cursor.kind != CXCursor_InclusionDirective)
    return nullptr;
  const InclusionDirective *ID = getCursorInclusionDirective(cursor);
  return const_cast<FileEntry *>(ID->getFile());
}
References clang::cxcursor::getCursorInclusionDirective().
clang_getModuleForFile()
CXModule clang_getModuleForFile (CXTranslationUnit TU, CXFile File)
Definition at line 8450 of file CIndex.cpp.
                                                                   {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return nullptr;
  }
  if (!File)
    return nullptr;
  FileEntry *FE = static_cast<FileEntry *>(File);
  ASTUnit &Unit = *cxtu::getASTUnit(TU);
  HeaderSearch &HS = Unit.getPreprocessor().getHeaderSearchInfo();
  ModuleMap::KnownHeader Header = HS.findModuleForHeader(FE);
  return Header.getModule();
}
clang_getNullCursor()
CXCursor clang_getNullCursor (void)
Definition at line 5901 of file CIndex.cpp.
                                   {
  return MakeCXCursorInvalid(CXCursor_InvalidFile);
}
References clang::cxcursor::MakeCXCursorInvalid().
Referenced by clang::cxindex::AttrListInfo::AttrListInfo(), clang_Cursor_getArgument(), clang_Cursor_getVarDeclInitializer(), clang_Cursor_isNull(), clang_getCursorDefinition(), clang_getCursorLexicalParent(), clang_getCursorReferenced(), clang_getCursorSemanticParent(), clang_getOverloadedDecl(), clang_getSpecializedCursorTemplate(), clang::cxcursor::getCursor(), clang::cxindex::CXIndexDataConsumer::handleObjCCategory(), clang::cxindex::CXIndexDataConsumer::handleObjCCategoryImpl(), and clang::cxindex::CXIndexDataConsumer::handleObjCInterface().
clang_getNumOverloadedDecls()
unsigned clang_getNumOverloadedDecls (CXCursor C)
Definition at line 6670 of file CIndex.cpp.
                                                 {
  if (C.kind != CXCursor_OverloadedDeclRef)
    return 0;
  OverloadedDeclRefStorage Storage = getCursorOverloadedDeclRef(C).first;
  if (const OverloadExpr *E = Storage.dyn_cast<const OverloadExpr *>())
    return E->getNumDecls();
  if (OverloadedTemplateStorage *S =
          Storage.dyn_cast<OverloadedTemplateStorage *>())
    return S->size();
  const Decl *D = Storage.get<const Decl *>();
  if (const UsingDecl *Using = dyn_cast<UsingDecl>(D))
    return Using->shadow_size();
  return 0;
}
References clang::cxcursor::getCursorOverloadedDeclRef().
Referenced by clang_getOverloadedDecl().
clang_getOverloadedDecl()
CXCursor clang_getOverloadedDecl (CXCursor cursor, unsigned index)
Definition at line 6689 of file CIndex.cpp.
                                                                  {
  if (cursor.kind != CXCursor_OverloadedDeclRef)
    return clang_getNullCursor();
  if (index >= clang_getNumOverloadedDecls(cursor))
    return clang_getNullCursor();
  CXTranslationUnit TU = getCursorTU(cursor);
  OverloadedDeclRefStorage Storage = getCursorOverloadedDeclRef(cursor).first;
  if (const OverloadExpr *E = Storage.dyn_cast<const OverloadExpr *>())
    return MakeCXCursor(E->decls_begin()[index], TU);
  if (OverloadedTemplateStorage *S =
          Storage.dyn_cast<OverloadedTemplateStorage *>())
    return MakeCXCursor(S->begin()[index], TU);
  const Decl *D = Storage.get<const Decl *>();
  if (const UsingDecl *Using = dyn_cast<UsingDecl>(D)) {
    // FIXME: This is, unfortunately, linear time.
    UsingDecl::shadow_iterator Pos = Using->shadow_begin();
    std::advance(Pos, index);
    return MakeCXCursor(cast<UsingShadowDecl>(*Pos)->getTargetDecl(), TU);
  }
  return clang_getNullCursor();
}
References clang_getNullCursor(), clang_getNumOverloadedDecls(), clang::cxcursor::getCursorOverloadedDeclRef(), clang::cxcursor::getCursorTU(), and clang::cxcursor::MakeCXCursor().
clang_getSkippedRanges()
CXSourceRangeList* clang_getSkippedRanges (CXTranslationUnit TU, CXFile file)
Definition at line 8834 of file CIndex.cpp.
                                                                             {
  CXSourceRangeList *skipped = new CXSourceRangeList;
  skipped->count = 0;
  skipped->ranges = nullptr;
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return skipped;
  }
  if (!file)
    return skipped;
  ASTUnit *astUnit = cxtu::getASTUnit(TU);
  PreprocessingRecord *ppRec =
      astUnit->getPreprocessor().getPreprocessingRecord();
  if (!ppRec)
    return skipped;
  ASTContext &Ctx = astUnit->getASTContext();
  SourceManager &sm = Ctx.getSourceManager();
  FileEntry *fileEntry = static_cast<FileEntry *>(file);
  FileID wantedFileID = sm.translateFile(fileEntry);
  bool isMainFile = wantedFileID == sm.getMainFileID();
  const std::vector<SourceRange> &SkippedRanges = ppRec->getSkippedRanges();
  std::vector<SourceRange> wantedRanges;
  for (std::vector<SourceRange>::const_iterator i = SkippedRanges.begin(),
                                                ei = SkippedRanges.end();
       i != ei; ++i) {
    if (sm.getFileID(i->getBegin()) == wantedFileID ||
        sm.getFileID(i->getEnd()) == wantedFileID)
      wantedRanges.push_back(*i);
    else if (isMainFile && (astUnit->isInPreambleFileID(i->getBegin()) ||
                            astUnit->isInPreambleFileID(i->getEnd())))
      wantedRanges.push_back(*i);
  }
  skipped->count = wantedRanges.size();
  skipped->ranges = new CXSourceRange[skipped->count];
  for (unsigned i = 0, ei = skipped->count; i != ei; ++i)
    skipped->ranges[i] = cxloc::translateSourceRange(Ctx, wantedRanges[i]);
  return skipped;
}
clang_getToken()
CXToken* clang_getToken (CXTranslationUnit TU, CXSourceLocation Location)
Definition at line 6950 of file CIndex.cpp.
                                                                         {
  LOG_FUNC_SECTION { *Log << TU << ' ' << Location; }
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return NULL;
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  if (!CXXUnit)
    return NULL;
  SourceLocation Begin = cxloc::translateSourceLocation(Location);
  if (Begin.isInvalid())
    return NULL;
  SourceManager &SM = CXXUnit->getSourceManager();
  std::pair<FileID, unsigned> DecomposedEnd = SM.getDecomposedLoc(Begin);
  DecomposedEnd.second +=
      Lexer::MeasureTokenLength(Begin, SM, CXXUnit->getLangOpts());
  SourceLocation End =
      SM.getComposedLoc(DecomposedEnd.first, DecomposedEnd.second);
  SmallVector<CXToken, 32> CXTokens;
  getTokens(CXXUnit, SourceRange(Begin, End), CXTokens);
  if (CXTokens.empty())
    return NULL;
  CXTokens.resize(1);
  CXToken *Token = static_cast<CXToken *>(llvm::safe_malloc(sizeof(CXToken)));
  memmove(Token, CXTokens.data(), sizeof(CXToken));
  return Token;
}
References LOG_FUNC_SECTION.
clang_getTokenExtent()
CXSourceRange clang_getTokenExtent (CXTranslationUnit TU, CXToken CXTok)
Definition at line 6867 of file CIndex.cpp.
                                                                        {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return clang_getNullRange();
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  if (!CXXUnit)
    return clang_getNullRange();
  return cxloc::translateSourceRange(
      CXXUnit->getASTContext(),
      SourceLocation::getFromRawEncoding(CXTok.int_data[1]));
}
clang_getTokenKind()
CXTokenKind clang_getTokenKind (CXToken CXTok)
Definition at line 6806 of file CIndex.cpp.
                                              {
  return static_cast<CXTokenKind>(CXTok.int_data[0]);
}
Referenced by clang_getTokenSpelling().
clang_getTokenLocation()
CXSourceLocation clang_getTokenLocation (CXTranslationUnit TU, CXToken CXTok)
Definition at line 6852 of file CIndex.cpp.
                                                                             {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return clang_getNullLocation();
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  if (!CXXUnit)
    return clang_getNullLocation();
  return cxloc::translateSourceLocation(
      CXXUnit->getASTContext(),
      SourceLocation::getFromRawEncoding(CXTok.int_data[1]));
}
clang_getTokenSpelling()
CXString clang_getTokenSpelling (CXTranslationUnit TU, CXToken CXTok)
Definition at line 6810 of file CIndex.cpp.
                                                                     {
  switch (clang_getTokenKind(CXTok)) {
  case CXToken_Identifier:
  case CXToken_Keyword:
    // We know we have an IdentifierInfo*, so use that.
    return cxstring::createRef(
        static_cast<IdentifierInfo *>(CXTok.ptr_data)->getNameStart());
  case CXToken_Literal: {
    // We have stashed the starting pointer in the ptr_data field. Use it.
    const char *Text = static_cast<const char *>(CXTok.ptr_data);
    return cxstring::createDup(StringRef(Text, CXTok.int_data[2]));
  }
  case CXToken_Punctuation:
  case CXToken_Comment:
    break;
  }
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return cxstring::createEmpty();
  }
  // We have to find the starting buffer pointer the hard way, by
  // deconstructing the source location.
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  if (!CXXUnit)
    return cxstring::createEmpty();
  SourceLocation Loc = SourceLocation::getFromRawEncoding(CXTok.int_data[1]);
  std::pair<FileID, unsigned> LocInfo =
      CXXUnit->getSourceManager().getDecomposedSpellingLoc(Loc);
  bool Invalid = false;
  StringRef Buffer =
      CXXUnit->getSourceManager().getBufferData(LocInfo.first, &Invalid);
  if (Invalid)
    return cxstring::createEmpty();
  return cxstring::createDup(Buffer.substr(LocInfo.second, CXTok.int_data[2]));
}
References clang_getTokenKind(), clang::cxstring::createDup(), and clang::cxstring::createRef().
clang_getTranslationUnitCursor()
CXCursor clang_getTranslationUnitCursor (CXTranslationUnit TU)
Definition at line 4321 of file CIndex.cpp.
                                                              {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return clang_getNullCursor();
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  return MakeCXCursor(CXXUnit->getASTContext().getTranslationUnitDecl(), TU);
}
clang_getTranslationUnitSpelling()
CXString clang_getTranslationUnitSpelling (CXTranslationUnit CTUnit)
Definition at line 4311 of file CIndex.cpp.
                                                                    {
  if (isNotUsableTU(CTUnit)) {
    LOG_BAD_TU(CTUnit);
    return cxstring::createEmpty();
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(CTUnit);
  return cxstring::createDup(CXXUnit->getOriginalSourceFileName());
}
Referenced by clang_getCursorSpelling().
clang_getTranslationUnitTargetInfo()
CXTargetInfo clang_getTranslationUnitTargetInfo (CXTranslationUnit CTUnit)
Definition at line 4331 of file CIndex.cpp.
                                                                          {
  if (isNotUsableTU(CTUnit)) {
    LOG_BAD_TU(CTUnit);
    return nullptr;
  }
  CXTargetInfoImpl *impl = new CXTargetInfoImpl();
  impl->TranslationUnit = CTUnit;
  return impl;
}
clang_getTUResourceUsageName()
const char* clang_getTUResourceUsageName (CXTUResourceUsageKind kind)
Definition at line 8687 of file CIndex.cpp.
                                                                     {
  const char *str = "";
  switch (kind) {
  case CXTUResourceUsage_AST:
    str = "ASTContext: expressions, declarations, and types";
    break;
  case CXTUResourceUsage_Identifiers:
    str = "ASTContext: identifiers";
    break;
  case CXTUResourceUsage_Selectors:
    str = "ASTContext: selectors";
    break;
  case CXTUResourceUsage_GlobalCompletionResults:
    str = "Code completion: cached global results";
    break;
  case CXTUResourceUsage_SourceManagerContentCache:
    str = "SourceManager: content cache allocator";
    break;
  case CXTUResourceUsage_AST_SideTables:
    str = "ASTContext: side tables";
    break;
  case CXTUResourceUsage_SourceManager_Membuffer_Malloc:
    str = "SourceManager: malloc'ed memory buffers";
    break;
  case CXTUResourceUsage_SourceManager_Membuffer_MMap:
    str = "SourceManager: mmap'ed memory buffers";
    break;
  case CXTUResourceUsage_ExternalASTSource_Membuffer_Malloc:
    str = "ExternalASTSource: malloc'ed memory buffers";
    break;
  case CXTUResourceUsage_ExternalASTSource_Membuffer_MMap:
    str = "ExternalASTSource: mmap'ed memory buffers";
    break;
  case CXTUResourceUsage_Preprocessor:
    str = "Preprocessor: malloc'ed memory";
    break;
  case CXTUResourceUsage_PreprocessingRecord:
    str = "Preprocessor: PreprocessingRecord";
    break;
  case CXTUResourceUsage_SourceManager_DataStructures:
    str = "SourceManager: data structures and tables";
    break;
  case CXTUResourceUsage_Preprocessor_HeaderSearch:
    str = "Preprocessor: header search tables";
    break;
  }
  return str;
}
Referenced by clang::PrintLibclangResourceUsage(), and PrintMemoryUsage().
clang_hashCursor()
unsigned clang_hashCursor (CXCursor C)
Definition at line 5921 of file CIndex.cpp.
                                      {
  unsigned Index = 0;
  if (clang_isExpression(C.kind) || clang_isStatement(C.kind))
    Index = 1;
  return llvm::DenseMapInfo<std::pair<unsigned, const void *>>::getHashValue(
      std::make_pair(C.kind, C.data[Index]));
}
References clang_isExpression(), and clang_isStatement().
clang_isAttribute()
unsigned clang_isAttribute (enum CXCursorKind K)
Definition at line 5960 of file CIndex.cpp.
                                                {
  return K >= CXCursor_FirstAttr && K <= CXCursor_LastAttr;
}
clang_isCursorDefinition()
unsigned clang_isCursorDefinition (CXCursor C)
Definition at line 6639 of file CIndex.cpp.
                                              {
  if (!clang_isDeclaration(C.kind))
    return 0;
  return clang_getCursorDefinition(C) == C;
}
References clang_getCursorDefinition(), and clang_isDeclaration().
clang_isDeclaration()
unsigned clang_isDeclaration (enum CXCursorKind K)
Definition at line 5934 of file CIndex.cpp.
                                                  {
  return (K >= CXCursor_FirstDecl && K <= CXCursor_LastDecl) ||
         (K >= CXCursor_FirstExtraDecl && K <= CXCursor_LastExtraDecl);
}
Referenced by clang_Comment_getKind(), clang_Cursor_getArgument(), clang_Cursor_getBriefCommentText(), clang_Cursor_getCommentRange(), clang_Cursor_getCXXManglings(), clang_Cursor_getMangling(), clang_Cursor_getNumArguments(), clang_Cursor_getObjCDeclQualifiers(), clang_Cursor_getObjCManglings(), clang_Cursor_getOffsetOfField(), clang_Cursor_getRawCommentText(), clang_Cursor_isAnonymous(), clang_Cursor_isAnonymousRecordDecl(), clang_Cursor_isBitField(), clang_Cursor_isExternalSymbol(), clang_Cursor_isInlineNamespace(), clang_Cursor_isObjCOptional(), clang_Cursor_isVariadic(), clang_CXXConstructor_isConvertingConstructor(), clang_CXXConstructor_isCopyConstructor(), clang_CXXConstructor_isDefaultConstructor(), clang_CXXConstructor_isMoveConstructor(), clang_CXXField_isMutable(), clang_CXXMethod_isConst(), clang_CXXMethod_isDefaulted(), clang_CXXMethod_isPureVirtual(), clang_CXXMethod_isStatic(), clang_CXXMethod_isVirtual(), clang_CXXRecord_isAbstract(), clang_EnumDecl_isScoped(), clang_equalCursors(), clang_getCanonicalCursor(), clang_getCursorCompletionString(), clang_getCursorDefinition(), clang_getCursorDisplayName(), clang_getCursorExceptionSpecificationType(), clang_getCursorLanguage(), clang_getCursorLexicalParent(), clang_getCursorLinkage(), clang_getCursorPlatformAvailability(), clang_getCursorPrettyPrinted(), clang_getCursorReferenced(), clang_getCursorResultType(), clang_getCursorSemanticParent(), clang_getCursorType(), clang_getCursorUSR(), clang_getCursorVisibility(), clang_getDeclObjCTypeEncoding(), clang_getEnumConstantDeclUnsignedValue(), clang_getEnumConstantDeclValue(), clang_getEnumDeclIntegerType(), clang_getFieldDeclBitWidth(), clang_getOverriddenCursors(), clang_getSpecializedCursorTemplate(), clang_getTypedefDeclUnderlyingType(), clang_isCursorDefinition(), clang_isInvalidDeclaration(), clang::cxcursor::getOverriddenCursors(), and clang::cxcursor::isFirstInDeclGroup().
clang_isExpression()
unsigned clang_isExpression (enum CXCursorKind K)
Definition at line 5952 of file CIndex.cpp.
                                                 {
  return K >= CXCursor_FirstExpr && K <= CXCursor_LastExpr;
}
Referenced by clang_Cursor_getArgument(), clang_Cursor_getNumArguments(), clang_Cursor_getReceiverType(), clang_Cursor_isDynamicCall(), clang_getCursorDefinition(), clang_getCursorLocation(), clang_getCursorReferenced(), clang_getCursorSpelling(), clang_getCursorType(), and clang_hashCursor().
clang_isFileMultipleIncludeGuarded()
unsigned clang_isFileMultipleIncludeGuarded (CXTranslationUnit TU, CXFile file)
Definition at line 4430 of file CIndex.cpp.
                                                                               {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return 0;
  }
  if (!file)
    return 0;
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  FileEntry *FEnt = static_cast<FileEntry *>(file);
  return CXXUnit->getPreprocessor()
      .getHeaderSearchInfo()
      .isFileMultipleIncludeGuarded(FEnt);
}
clang_isInvalid()
unsigned clang_isInvalid (enum CXCursorKind K)
Definition at line 5930 of file CIndex.cpp.
                                              {
  return K >= CXCursor_FirstInvalid && K <= CXCursor_LastInvalid;
}
Referenced by clang_Cursor_getCXXManglings(), clang_Cursor_getMangling(), clang_Cursor_getObjCManglings(), clang_getCursorDefinition(), clang_getCursorReferenced(), and clang_Type_visitFields().
clang_isInvalidDeclaration()
unsigned clang_isInvalidDeclaration (CXCursor C)
Definition at line 5939 of file CIndex.cpp.
                                                {
  if (clang_isDeclaration(C.kind)) {
    if (const Decl *D = getCursorDecl(C))
      return D->isInvalidDecl();
  }
  return 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_isPreprocessing()
unsigned clang_isPreprocessing (enum CXCursorKind K)
Definition at line 5968 of file CIndex.cpp.
                                                    {
  return K >= CXCursor_FirstPreprocessing && K <= CXCursor_LastPreprocessing;
}
clang_isReference()
unsigned clang_isReference (enum CXCursorKind K)
Definition at line 5948 of file CIndex.cpp.
                                                {
  return K >= CXCursor_FirstRef && K <= CXCursor_LastRef;
}
Referenced by clang_getCursorDefinition(), clang_getCursorLocation(), clang_getCursorSpelling(), and clang_getCursorType().
clang_isStatement()
unsigned clang_isStatement (enum CXCursorKind K)
Definition at line 5956 of file CIndex.cpp.
                                                {
  return K >= CXCursor_FirstStmt && K <= CXCursor_LastStmt;
}
Referenced by clang_Cursor_getSpellingNameRange(), and clang_hashCursor().
clang_isTranslationUnit()
unsigned clang_isTranslationUnit (enum CXCursorKind K)
Definition at line 5964 of file CIndex.cpp.
                                                      {
  return K == CXCursor_TranslationUnit;
}
Referenced by clang_getCursorSpelling().
clang_isUnexposed()
unsigned clang_isUnexposed (enum CXCursorKind K)
Definition at line 5972 of file CIndex.cpp.
                                                {
  switch (K) {
  case CXCursor_UnexposedDecl:
  case CXCursor_UnexposedExpr:
  case CXCursor_UnexposedStmt:
  case CXCursor_UnexposedAttr:
    return true;
  default:
    return false;
  }
}
clang_Module_getASTFile()
CXFile clang_Module_getASTFile (CXModule CXMod)
Definition at line 8466 of file CIndex.cpp.
                                               {
  if (!CXMod)
    return nullptr;
  Module *Mod = static_cast<Module *>(CXMod);
  if (auto File = Mod->getASTFile())
    return const_cast<FileEntry *>(&File->getFileEntry());
  return nullptr;
}
clang_Module_getFullName()
CXString clang_Module_getFullName (CXModule CXMod)
Definition at line 8489 of file CIndex.cpp.
                                                  {
  if (!CXMod)
    return cxstring::createEmpty();
  Module *Mod = static_cast<Module *>(CXMod);
  return cxstring::createDup(Mod->getFullModuleName());
}
References clang::cxstring::createDup(), and clang::cxstring::createEmpty().
clang_Module_getName()
CXString clang_Module_getName (CXModule CXMod)
Definition at line 8482 of file CIndex.cpp.
                                              {
  if (!CXMod)
    return cxstring::createEmpty();
  Module *Mod = static_cast<Module *>(CXMod);
  return cxstring::createDup(Mod->Name);
}
References clang::cxstring::createDup(), and clang::cxstring::createEmpty().
clang_Module_getNumTopLevelHeaders()
unsigned clang_Module_getNumTopLevelHeaders (CXTranslationUnit TU, CXModule CXMod)
Definition at line 8503 of file CIndex.cpp.
                                                            {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return 0;
  }
  if (!CXMod)
    return 0;
  Module *Mod = static_cast<Module *>(CXMod);
  FileManager &FileMgr = cxtu::getASTUnit(TU)->getFileManager();
  ArrayRef<const FileEntry *> TopHeaders = Mod->getTopHeaders(FileMgr);
  return TopHeaders.size();
}
clang_Module_getParent()
CXModule clang_Module_getParent (CXModule CXMod)
Definition at line 8475 of file CIndex.cpp.
                                                {
  if (!CXMod)
    return nullptr;
  Module *Mod = static_cast<Module *>(CXMod);
  return Mod->Parent;
}
clang_Module_getTopLevelHeader()
CXFile clang_Module_getTopLevelHeader (CXTranslationUnit TU, CXModule CXMod, unsigned Index)
Definition at line 8517 of file CIndex.cpp.
                                                      {
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return nullptr;
  }
  if (!CXMod)
    return nullptr;
  Module *Mod = static_cast<Module *>(CXMod);
  FileManager &FileMgr = cxtu::getASTUnit(TU)->getFileManager();
  ArrayRef<const FileEntry *> TopHeaders = Mod->getTopHeaders(FileMgr);
  if (Index < TopHeaders.size())
    return const_cast<FileEntry *>(TopHeaders[Index]);
  return nullptr;
}
clang_Module_isSystem()
int clang_Module_isSystem (CXModule CXMod)
Definition at line 8496 of file CIndex.cpp.
                                          {
  if (!CXMod)
    return 0;
  Module *Mod = static_cast<Module *>(CXMod);
  return Mod->IsSystem;
}
clang_parseTranslationUnit()
CXTranslationUnit clang_parseTranslationUnit (CXIndex CIdx, const char * source_filename, const char *const * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned num_unsaved_files, unsigned options)
Definition at line 3717 of file CIndex.cpp.
                                                                         {
  CXTranslationUnit TU;
  enum CXErrorCode Result = clang_parseTranslationUnit2(
      CIdx, source_filename, command_line_args, num_command_line_args,
      unsaved_files, num_unsaved_files, options, &TU);
  (void)Result;
  assert((TU && Result == CXError_Success) ||
         (!TU && Result != CXError_Success));
  return TU;
}
References clang_parseTranslationUnit2().
clang_parseTranslationUnit2()
enum CXErrorCode clang_parseTranslationUnit2 (CXIndex CIdx, const char * source_filename, const char *const * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned num_unsaved_files, unsigned options, CXTranslationUnit * out_TU)
Definition at line 3717 of file CIndex.cpp.
                                                 {
  noteBottomOfStack();
  SmallVector<const char *, 4> Args;
  Args.push_back("clang");
  Args.append(command_line_args, command_line_args + num_command_line_args);
  return clang_parseTranslationUnit2FullArgv(
      CIdx, source_filename, Args.data(), Args.size(), unsaved_files,
      num_unsaved_files, options, out_TU);
}
Referenced by clang_parseTranslationUnit().
clang_parseTranslationUnit2FullArgv()
enum CXErrorCode clang_parseTranslationUnit2FullArgv (CXIndex CIdx, const char * source_filename, const char *const * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned num_unsaved_files, unsigned options, CXTranslationUnit * out_TU)
Definition at line 3717 of file CIndex.cpp.
                                                 {
  LOG_FUNC_SECTION {
    *Log << source_filename << ": ";
    for (int i = 0; i != num_command_line_args; ++i)
      *Log << command_line_args[i] << " ";
  }
  if (num_unsaved_files && !unsaved_files)
    return CXError_InvalidArguments;
  CXErrorCode result = CXError_Failure;
  auto ParseTranslationUnitImpl = [=, &result] {
    noteBottomOfStack();
    result = clang_parseTranslationUnit_Impl(
        CIdx, source_filename, command_line_args, num_command_line_args,
        llvm::makeArrayRef(unsaved_files, num_unsaved_files), options, out_TU);
  };
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, ParseTranslationUnitImpl)) {
    fprintf(stderr, "libclang: crash detected during parsing: {\n");
    fprintf(stderr, " 'source_filename' : '%s'\n", source_filename);
    fprintf(stderr, " 'command_line_args' : [");
    for (int i = 0; i != num_command_line_args; ++i) {
      if (i)
        fprintf(stderr, ", ");
      fprintf(stderr, "'%s'", command_line_args[i]);
    }
    fprintf(stderr, "],\n");
    fprintf(stderr, " 'unsaved_files' : [");
    for (unsigned i = 0; i != num_unsaved_files; ++i) {
      if (i)
        fprintf(stderr, ", ");
      fprintf(stderr, "('%s', '...', %ld)", unsaved_files[i].Filename,
              unsaved_files[i].Length);
    }
    fprintf(stderr, "],\n");
    fprintf(stderr, " 'options' : %d,\n", options);
    fprintf(stderr, "}\n");
    return CXError_Crashed;
  } else if (getenv("LIBCLANG_RESOURCE_USAGE")) {
    if (CXTranslationUnit *TU = out_TU)
      PrintLibclangResourceUsage(*TU);
  }
  return result;
}
clang_PrintingPolicy_dispose()
void clang_PrintingPolicy_dispose (CXPrintingPolicy Policy)
Definition at line 4937 of file CIndex.cpp.
                                                           {
  if (Policy)
    delete static_cast<PrintingPolicy *>(Policy);
}
clang_PrintingPolicy_getProperty()
unsigned clang_PrintingPolicy_getProperty (CXPrintingPolicy Policy, enum CXPrintingPolicyProperty Property)
Definition at line 4943 of file CIndex.cpp.
                                                                         {
  if (!Policy)
    return 0;
  PrintingPolicy *P = static_cast<PrintingPolicy *>(Policy);
  switch (Property) {
  case CXPrintingPolicy_Indentation:
    return P->Indentation;
  case CXPrintingPolicy_SuppressSpecifiers:
    return P->SuppressSpecifiers;
  case CXPrintingPolicy_SuppressTagKeyword:
    return P->SuppressTagKeyword;
  case CXPrintingPolicy_IncludeTagDefinition:
    return P->IncludeTagDefinition;
  case CXPrintingPolicy_SuppressScope:
    return P->SuppressScope;
  case CXPrintingPolicy_SuppressUnwrittenScope:
    return P->SuppressUnwrittenScope;
  case CXPrintingPolicy_SuppressInitializers:
    return P->SuppressInitializers;
  case CXPrintingPolicy_ConstantArraySizeAsWritten:
    return P->ConstantArraySizeAsWritten;
  case CXPrintingPolicy_AnonymousTagLocations:
    return P->AnonymousTagLocations;
  case CXPrintingPolicy_SuppressStrongLifetime:
    return P->SuppressStrongLifetime;
  case CXPrintingPolicy_SuppressLifetimeQualifiers:
    return P->SuppressLifetimeQualifiers;
  case CXPrintingPolicy_SuppressTemplateArgsInCXXConstructors:
    return P->SuppressTemplateArgsInCXXConstructors;
  case CXPrintingPolicy_Bool:
    return P->Bool;
  case CXPrintingPolicy_Restrict:
    return P->Restrict;
  case CXPrintingPolicy_Alignof:
    return P->Alignof;
  case CXPrintingPolicy_UnderscoreAlignof:
    return P->UnderscoreAlignof;
  case CXPrintingPolicy_UseVoidForZeroParams:
    return P->UseVoidForZeroParams;
  case CXPrintingPolicy_TerseOutput:
    return P->TerseOutput;
  case CXPrintingPolicy_PolishForDeclaration:
    return P->PolishForDeclaration;
  case CXPrintingPolicy_Half:
    return P->Half;
  case CXPrintingPolicy_MSWChar:
    return P->MSWChar;
  case CXPrintingPolicy_IncludeNewlines:
    return P->IncludeNewlines;
  case CXPrintingPolicy_MSVCFormatting:
    return P->MSVCFormatting;
  case CXPrintingPolicy_ConstantsAsWritten:
    return P->ConstantsAsWritten;
  case CXPrintingPolicy_SuppressImplicitBase:
    return P->SuppressImplicitBase;
  case CXPrintingPolicy_FullyQualifiedName:
    return P->FullyQualifiedName;
  }
  assert(false && "Invalid CXPrintingPolicyProperty");
  return 0;
}
clang_PrintingPolicy_setProperty()
void clang_PrintingPolicy_setProperty (CXPrintingPolicy Policy, enum CXPrintingPolicyProperty Property, unsigned Value)
Definition at line 5008 of file CIndex.cpp.
                                                      {
  if (!Policy)
    return;
  PrintingPolicy *P = static_cast<PrintingPolicy *>(Policy);
  switch (Property) {
  case CXPrintingPolicy_Indentation:
    P->Indentation = Value;
    return;
  case CXPrintingPolicy_SuppressSpecifiers:
    P->SuppressSpecifiers = Value;
    return;
  case CXPrintingPolicy_SuppressTagKeyword:
    P->SuppressTagKeyword = Value;
    return;
  case CXPrintingPolicy_IncludeTagDefinition:
    P->IncludeTagDefinition = Value;
    return;
  case CXPrintingPolicy_SuppressScope:
    P->SuppressScope = Value;
    return;
  case CXPrintingPolicy_SuppressUnwrittenScope:
    P->SuppressUnwrittenScope = Value;
    return;
  case CXPrintingPolicy_SuppressInitializers:
    P->SuppressInitializers = Value;
    return;
  case CXPrintingPolicy_ConstantArraySizeAsWritten:
    P->ConstantArraySizeAsWritten = Value;
    return;
  case CXPrintingPolicy_AnonymousTagLocations:
    P->AnonymousTagLocations = Value;
    return;
  case CXPrintingPolicy_SuppressStrongLifetime:
    P->SuppressStrongLifetime = Value;
    return;
  case CXPrintingPolicy_SuppressLifetimeQualifiers:
    P->SuppressLifetimeQualifiers = Value;
    return;
  case CXPrintingPolicy_SuppressTemplateArgsInCXXConstructors:
    P->SuppressTemplateArgsInCXXConstructors = Value;
    return;
  case CXPrintingPolicy_Bool:
    P->Bool = Value;
    return;
  case CXPrintingPolicy_Restrict:
    P->Restrict = Value;
    return;
  case CXPrintingPolicy_Alignof:
    P->Alignof = Value;
    return;
  case CXPrintingPolicy_UnderscoreAlignof:
    P->UnderscoreAlignof = Value;
    return;
  case CXPrintingPolicy_UseVoidForZeroParams:
    P->UseVoidForZeroParams = Value;
    return;
  case CXPrintingPolicy_TerseOutput:
    P->TerseOutput = Value;
    return;
  case CXPrintingPolicy_PolishForDeclaration:
    P->PolishForDeclaration = Value;
    return;
  case CXPrintingPolicy_Half:
    P->Half = Value;
    return;
  case CXPrintingPolicy_MSWChar:
    P->MSWChar = Value;
    return;
  case CXPrintingPolicy_IncludeNewlines:
    P->IncludeNewlines = Value;
    return;
  case CXPrintingPolicy_MSVCFormatting:
    P->MSVCFormatting = Value;
    return;
  case CXPrintingPolicy_ConstantsAsWritten:
    P->ConstantsAsWritten = Value;
    return;
  case CXPrintingPolicy_SuppressImplicitBase:
    P->SuppressImplicitBase = Value;
    return;
  case CXPrintingPolicy_FullyQualifiedName:
    P->FullyQualifiedName = Value;
    return;
  }
  assert(false && "Invalid CXPrintingPolicyProperty");
}
clang_reparseTranslationUnit()
int clang_reparseTranslationUnit (CXTranslationUnit TU, unsigned num_unsaved_files, struct CXUnsavedFile * unsaved_files, unsigned options)
Definition at line 4284 of file CIndex.cpp.
                                                   {
  LOG_FUNC_SECTION { *Log << TU; }
  if (num_unsaved_files && !unsaved_files)
    return CXError_InvalidArguments;
  CXErrorCode result;
  auto ReparseTranslationUnitImpl = [=, &result]() {
    result = clang_reparseTranslationUnit_Impl(
        TU, llvm::makeArrayRef(unsaved_files, num_unsaved_files), options);
  };
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, ReparseTranslationUnitImpl)) {
    fprintf(stderr, "libclang: crash detected during reparsing\n");
    cxtu::getASTUnit(TU)->setUnsafeToFree(true);
    return CXError_Crashed;
  } else if (getenv("LIBCLANG_RESOURCE_USAGE"))
    PrintLibclangResourceUsage(TU);
  return result;
}
References LOG_FUNC_SECTION.
clang_saveTranslationUnit()
int clang_saveTranslationUnit (CXTranslationUnit TU, const char * FileName, unsigned options)
Definition at line 4159 of file CIndex.cpp.
                                                {
  LOG_FUNC_SECTION { *Log << TU << ' ' << FileName; }
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return CXSaveError_InvalidTU;
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  ASTUnit::ConcurrencyCheck Check(*CXXUnit);
  if (!CXXUnit->hasSema())
    return CXSaveError_InvalidTU;
  CXSaveError result;
  auto SaveTranslationUnitImpl = [=, &result]() {
    result = clang_saveTranslationUnit_Impl(TU, FileName, options);
  };
  if (!CXXUnit->getDiagnostics().hasUnrecoverableErrorOccurred()) {
    SaveTranslationUnitImpl();
    if (getenv("LIBCLANG_RESOURCE_USAGE"))
      PrintLibclangResourceUsage(TU);
    return result;
  }
  // We have an AST that has invalid nodes due to compiler errors.
  // Use a crash recovery thread for protection.
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, SaveTranslationUnitImpl)) {
    fprintf(stderr, "libclang: crash detected during AST saving: {\n");
    fprintf(stderr, " 'filename' : '%s'\n", FileName);
    fprintf(stderr, " 'options' : %d,\n", options);
    fprintf(stderr, "}\n");
    return CXSaveError_Unknown;
  } else if (getenv("LIBCLANG_RESOURCE_USAGE")) {
    PrintLibclangResourceUsage(TU);
  }
  return result;
}
References LOG_FUNC_SECTION.
clang_suspendTranslationUnit()
unsigned clang_suspendTranslationUnit (CXTranslationUnit CTUnit)
Definition at line 4224 of file CIndex.cpp.
                                                                {
  if (CTUnit) {
    ASTUnit *Unit = cxtu::getASTUnit(CTUnit);
    if (Unit && Unit->isUnsafeToFree())
      return false;
    Unit->ResetForParse();
    return true;
  }
  return false;
}
clang_TargetInfo_dispose()
void clang_TargetInfo_dispose (CXTargetInfo TargetInfo)
Definition at line 4368 of file CIndex.cpp.
                                                       {
  if (!TargetInfo)
    return;
  delete TargetInfo;
}
clang_TargetInfo_getPointerWidth()
int clang_TargetInfo_getPointerWidth (CXTargetInfo TargetInfo)
Definition at line 4356 of file CIndex.cpp.
                                                              {
  if (!TargetInfo)
    return -1;
  CXTranslationUnit CTUnit = TargetInfo->TranslationUnit;
  assert(!isNotUsableTU(CTUnit) &&
         "Unexpected unusable translation unit in TargetInfo");
  ASTUnit *CXXUnit = cxtu::getASTUnit(CTUnit);
  return CXXUnit->getASTContext().getTargetInfo().getMaxPointerWidth();
}
clang_TargetInfo_getTriple()
CXString clang_TargetInfo_getTriple (CXTargetInfo TargetInfo)
Definition at line 4342 of file CIndex.cpp.
                                                             {
  if (!TargetInfo)
    return cxstring::createEmpty();
  CXTranslationUnit CTUnit = TargetInfo->TranslationUnit;
  assert(!isNotUsableTU(CTUnit) &&
         "Unexpected unusable translation unit in TargetInfo");
  ASTUnit *CXXUnit = cxtu::getASTUnit(CTUnit);
  std::string Triple =
      CXXUnit->getASTContext().getTargetInfo().getTriple().normalize();
  return cxstring::createDup(Triple);
}
References clang::cxstring::createEmpty().
clang_toggleCrashRecovery()
void clang_toggleCrashRecovery (unsigned isEnabled)
Definition at line 3493 of file CIndex.cpp.
                                                   {
  if (isEnabled)
    llvm::CrashRecoveryContext::Enable();
  else
    llvm::CrashRecoveryContext::Disable();
}
clang_tokenize()
void clang_tokenize (CXTranslationUnit TU, CXSourceRange Range, CXToken ** Tokens, unsigned * NumTokens)
Definition at line 6986 of file CIndex.cpp.
                                         {
  LOG_FUNC_SECTION { *Log << TU << ' ' << Range; }
  if (Tokens)
    *Tokens = nullptr;
  if (NumTokens)
    *NumTokens = 0;
  if (isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return;
  }
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  if (!CXXUnit || !Tokens || !NumTokens)
    return;
  ASTUnit::ConcurrencyCheck Check(*CXXUnit);
  SourceRange R = cxloc::translateCXSourceRange(Range);
  if (R.isInvalid())
    return;
  SmallVector<CXToken, 32> CXTokens;
  getTokens(CXXUnit, R, CXTokens);
  if (CXTokens.empty())
    return;
  *Tokens = static_cast<CXToken *>(
      llvm::safe_malloc(sizeof(CXToken) * CXTokens.size()));
  memmove(*Tokens, CXTokens.data(), sizeof(CXToken) * CXTokens.size());
  *NumTokens = CXTokens.size();
}
References LOG_FUNC_SECTION.
clang_Type_getObjCEncoding()
CXString clang_Type_getObjCEncoding (CXType CT)
Definition at line 3800 of file CIndex.cpp.
                                               {
  CXTranslationUnit tu = static_cast<CXTranslationUnit>(CT.data[1]);
  ASTContext &Ctx = getASTUnit(tu)->getASTContext();
  std::string encoding;
  Ctx.getObjCEncodingForType(QualType::getFromOpaquePtr(CT.data[0]), encoding);
  return cxstring::createDup(encoding);
}
clang_visitChildren()
unsigned clang_visitChildren (CXCursor parent, CXCursorVisitor visitor, CXClientData client_data)
Definition at line 4555 of file CIndex.cpp.
                                                       {
  CursorVisitor CursorVis(getCursorTU(parent), visitor, client_data,
                          /*VisitPreprocessorLast=*/false);
  return CursorVis.VisitChildren(parent);
}
References clang::cxcursor::getCursorTU(), and clang::cxcursor::CursorVisitor::VisitChildren().
Referenced by clang_visitChildrenWithBlock().
clang_visitChildrenWithBlock()
unsigned clang_visitChildrenWithBlock (CXCursor parent, CXCursorVisitorBlock block)
Definition at line 4592 of file CIndex.cpp.
                                                                  {
  return clang_visitChildren(parent, visitWithBlock, block);
}
References clang_visitChildren().
GetSubscriptOrCallOperator()
const CXXOperatorCallExpr* GetSubscriptOrCallOperator (CXCursor Cursor)
Definition at line 7142 of file CIndex.cpp.
                                                                       {
  if (!clang_isExpression(Cursor.kind))
    return nullptr;
  const Expr *E = getCursorExpr(Cursor);
  if (const auto *OCE = dyn_cast<CXXOperatorCallExpr>(E)) {
    const OverloadedOperatorKind Kind = OCE->getOperator();
    if (Kind == OO_Call || Kind == OO_Subscript)
      return OCE;
  }
  return nullptr;
}