/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexCodeCompletion.cpp File Reference
#include `CIndexer.h`
#include `CIndexDiagnostic.h`
#include `CLog.h`
#include `CXCursor.h`
#include `CXSourceLocation.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `clang/AST/Decl.h`
#include `clang/AST/DeclObjC.h`
#include `clang/AST/Type.h`
#include `clang/Basic/FileManager.h`
#include `clang/Basic/SourceManager.h`
#include `clang/Frontend/ASTUnit.h`
#include `clang/Frontend/CompilerInstance.h`
#include `clang/Sema/CodeCompleteConsumer.h`
#include `clang/Sema/Sema.h`
#include `llvm/ADT/SmallString.h`
#include `llvm/ADT/StringExtras.h`
#include `llvm/Support/CrashRecoveryContext.h`
#include `llvm/Support/FileSystem.h`
#include `llvm/Support/FormatVariadic.h`
#include `llvm/Support/MemoryBuffer.h`
#include `llvm/Support/Program.h`
#include `llvm/Support/Timer.h`
#include `llvm/Support/raw_ostream.h`
#include <atomic>
#include <cstdio>
#include <cstdlib>
#include <string>
Functions
enum CXCompletionChunkKind clang_getCompletionChunkKind (CXCompletionString completion_string, unsigned chunk_number)
CXString clang_getCompletionChunkText (CXCompletionString completion_string, unsigned chunk_number)
CXCompletionString clang_getCompletionChunkCompletionString (CXCompletionString completion_string, unsigned chunk_number)
unsigned clang_getNumCompletionChunks (CXCompletionString completion_string)
unsigned clang_getCompletionPriority (CXCompletionString completion_string)
enum CXAvailabilityKind clang_getCompletionAvailability (CXCompletionString completion_string)
unsigned clang_getCompletionNumAnnotations (CXCompletionString completion_string)
CXString clang_getCompletionAnnotation (CXCompletionString completion_string, unsigned annotation_number)
CXString clang_getCompletionParent (CXCompletionString completion_string, CXCursorKind *kind)
CXString clang_getCompletionBriefComment (CXCompletionString completion_string)
unsigned clang_getCompletionNumFixIts (CXCodeCompleteResults *results, unsigned completion_index)
CXString clang_getCompletionFixIt (CXCodeCompleteResults *results, unsigned completion_index, unsigned fixit_index, CXSourceRange *replacement_range)
CXCodeCompleteResults * clang_codeCompleteAt (CXTranslationUnit TU, const char *complete_filename, unsigned complete_line, unsigned complete_column, struct CXUnsavedFile *unsaved_files, unsigned num_unsaved_files, unsigned options)
unsigned clang_defaultCodeCompleteOptions (void)
void clang_disposeCodeCompleteResults (CXCodeCompleteResults *ResultsIn)
unsigned clang_codeCompleteGetNumDiagnostics (CXCodeCompleteResults *ResultsIn)
CXDiagnostic clang_codeCompleteGetDiagnostic (CXCodeCompleteResults *ResultsIn, unsigned Index)
unsigned long long clang_codeCompleteGetContexts (CXCodeCompleteResults *ResultsIn)
enum CXCursorKind clang_codeCompleteGetContainerKind (CXCodeCompleteResults *ResultsIn, unsigned *IsIncomplete)
CXString clang_codeCompleteGetContainerUSR (CXCodeCompleteResults *ResultsIn)
CXString clang_codeCompleteGetObjCSelector (CXCodeCompleteResults *ResultsIn)
void clang_sortCodeCompletionResults (CXCompletionResult *Results, unsigned NumResults)
Function Documentation
clang_codeCompleteAt()
CXCodeCompleteResults* clang_codeCompleteAt (CXTranslationUnit TU, const char * complete_filename, unsigned complete_line, unsigned complete_column, struct CXUnsavedFile * unsaved_files, unsigned num_unsaved_files, unsigned options)
Definition at line 851 of file CIndexCodeCompletion.cpp.
                                                              {
  LOG_FUNC_SECTION {
    *Log << TU << ' '
         << complete_filename << ':' << complete_line << ':' << complete_column;
  }
  if (num_unsaved_files && !unsaved_files)
    return nullptr;
  CXCodeCompleteResults *result;
  auto CodeCompleteAtImpl = [=, &result]() {
    result = clang_codeCompleteAt_Impl(
        TU, complete_filename, complete_line, complete_column,
        llvm::makeArrayRef(unsaved_files, num_unsaved_files), options);
  };
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, CodeCompleteAtImpl)) {
    fprintf(stderr, "libclang: crash detected in code completion\n");
    cxtu::getASTUnit(TU)->setUnsafeToFree(true);
    return nullptr;
  } else if (getenv("LIBCLANG_RESOURCE_USAGE"))
    PrintLibclangResourceUsage(TU);
  return result;
}
References LOG_FUNC_SECTION.
clang_codeCompleteGetContainerKind()
enum CXCursorKind clang_codeCompleteGetContainerKind (CXCodeCompleteResults * ResultsIn, unsigned * IsIncomplete)
Definition at line 926 of file CIndexCodeCompletion.cpp.
                                                                             {
  AllocatedCXCodeCompleteResults *Results =
    static_cast<AllocatedCXCodeCompleteResults *>(ResultsIn);
  if (!Results)
    return CXCursor_InvalidCode;
  if (IsIncomplete != nullptr) {
    *IsIncomplete = Results->ContainerIsIncomplete;
  }
  
  return Results->ContainerKind;
}
clang_codeCompleteGetContainerUSR()
CXString clang_codeCompleteGetContainerUSR (CXCodeCompleteResults * ResultsIn)
Definition at line 950 of file CIndexCodeCompletion.cpp.
                                                                             {
  AllocatedCXCodeCompleteResults *Results =
    static_cast<AllocatedCXCodeCompleteResults *>(ResultsIn);
  if (!Results)
    return cxstring::createEmpty();
  return cxstring::createRef(Results->ContainerUSR.c_str());
}
clang_codeCompleteGetContexts()
unsigned long long clang_codeCompleteGetContexts (CXCodeCompleteResults * ResultsIn)
Definition at line 926 of file CIndexCodeCompletion.cpp.
                                                                {
  AllocatedCXCodeCompleteResults *Results
    = static_cast<AllocatedCXCodeCompleteResults*>(ResultsIn);
  if (!Results)
    return 0;
  
  return Results->Contexts;
}
clang_codeCompleteGetDiagnostic()
CXDiagnostic clang_codeCompleteGetDiagnostic (CXCodeCompleteResults * ResultsIn, unsigned Index)
Definition at line 909 of file CIndexCodeCompletion.cpp.
                                                {
  AllocatedCXCodeCompleteResults *Results
    = static_cast<AllocatedCXCodeCompleteResults*>(ResultsIn);
  if (!Results || Index >= Results->Diagnostics.size())
    return nullptr;
  CXStoredDiagnostic *Diag = Results->DiagnosticsWrappers[Index].get();
  if (!Diag)
    Diag = (Results->DiagnosticsWrappers[Index] =
                std::make_unique<CXStoredDiagnostic>(
                    Results->Diagnostics[Index], Results->LangOpts))
               .get();
  return Diag;
}
clang_codeCompleteGetNumDiagnostics()
unsigned clang_codeCompleteGetNumDiagnostics (CXCodeCompleteResults * ResultsIn)
Definition at line 899 of file CIndexCodeCompletion.cpp.
                                                                      {
  AllocatedCXCodeCompleteResults *Results
    = static_cast<AllocatedCXCodeCompleteResults*>(ResultsIn);
  if (!Results)
    return 0;
  return Results->Diagnostics.size();
}
clang_codeCompleteGetObjCSelector()
CXString clang_codeCompleteGetObjCSelector (CXCodeCompleteResults * ResultsIn)
Definition at line 960 of file CIndexCodeCompletion.cpp.
                                                                             {
  AllocatedCXCodeCompleteResults *Results =
    static_cast<AllocatedCXCodeCompleteResults *>(ResultsIn);
  if (!Results)
    return cxstring::createEmpty();
  
  return cxstring::createDup(Results->Selector);
}
clang_defaultCodeCompleteOptions()
unsigned clang_defaultCodeCompleteOptions (void)
Definition at line 885 of file CIndexCodeCompletion.cpp.
                                                {
  return CXCodeComplete_IncludeMacros;
}
Referenced by perform_code_completion().
clang_disposeCodeCompleteResults()
void clang_disposeCodeCompleteResults (CXCodeCompleteResults * ResultsIn)
Definition at line 889 of file CIndexCodeCompletion.cpp.
                                                                        {
  if (!ResultsIn)
    return;
  AllocatedCXCodeCompleteResults *Results
    = static_cast<AllocatedCXCodeCompleteResults*>(ResultsIn);
  delete Results;
}
clang_getCompletionAnnotation()
CXString clang_getCompletionAnnotation (CXCompletionString completion_string, unsigned annotation_number)
Definition at line 210 of file CIndexCodeCompletion.cpp.
                                                                   {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  return CCStr ? cxstring::createRef(CCStr->getAnnotation(annotation_number))
               : cxstring::createNull();
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_getCompletionAvailability()
enum CXAvailabilityKind clang_getCompletionAvailability (CXCompletionString completion_string)
Definition at line 192 of file CIndexCodeCompletion.cpp.
                                                                      {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  return CCStr? static_cast<CXAvailabilityKind>(CCStr->getAvailability())
              : CXAvailability_Available;
}
clang_getCompletionBriefComment()
CXString clang_getCompletionBriefComment (CXCompletionString completion_string)
Definition at line 231 of file CIndexCodeCompletion.cpp.
                                                                      {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  if (!CCStr)
    return cxstring::createNull();
  return cxstring::createRef(CCStr->getBriefComment());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_getCompletionChunkCompletionString()
CXCompletionString clang_getCompletionChunkCompletionString (CXCompletionString completion_string, unsigned chunk_number)
Definition at line 150 of file CIndexCodeCompletion.cpp.
                                                                {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  if (!CCStr || chunk_number >= CCStr->size())
    return nullptr;
  switch ((*CCStr)[chunk_number].Kind) {
  case CodeCompletionString::CK_TypedText:
  case CodeCompletionString::CK_Text:
  case CodeCompletionString::CK_Placeholder:
  case CodeCompletionString::CK_CurrentParameter:
  case CodeCompletionString::CK_Informative:
  case CodeCompletionString::CK_LeftParen:
  case CodeCompletionString::CK_RightParen:
  case CodeCompletionString::CK_LeftBracket:
  case CodeCompletionString::CK_RightBracket:
  case CodeCompletionString::CK_LeftBrace:
  case CodeCompletionString::CK_RightBrace:
  case CodeCompletionString::CK_LeftAngle:
  case CodeCompletionString::CK_RightAngle:
  case CodeCompletionString::CK_Comma:
  case CodeCompletionString::CK_ResultType:
  case CodeCompletionString::CK_Colon:
  case CodeCompletionString::CK_SemiColon:
  case CodeCompletionString::CK_Equal:
  case CodeCompletionString::CK_HorizontalSpace:
  case CodeCompletionString::CK_VerticalSpace:
    return nullptr;
  case CodeCompletionString::CK_Optional:
    // Note: treated as an empty text block.
    return (*CCStr)[chunk_number].Optional;
  }
  llvm_unreachable("Invalid CompletionKind!");
}
clang_getCompletionChunkKind()
enum CXCompletionChunkKind clang_getCompletionChunkKind (CXCompletionString completion_string, unsigned chunk_number)
Definition at line 1 of file CIndexCodeCompletion.cpp.
                                                    {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  if (!CCStr || chunk_number >= CCStr->size())
    return CXCompletionChunk_Text;
  switch ((*CCStr)[chunk_number].Kind) {
  case CodeCompletionString::CK_TypedText:
    return CXCompletionChunk_TypedText;
  case CodeCompletionString::CK_Text:
    return CXCompletionChunk_Text;
  case CodeCompletionString::CK_Optional:
    return CXCompletionChunk_Optional;
  case CodeCompletionString::CK_Placeholder:
    return CXCompletionChunk_Placeholder;
  case CodeCompletionString::CK_Informative:
    return CXCompletionChunk_Informative;
  case CodeCompletionString::CK_ResultType:
    return CXCompletionChunk_ResultType;
  case CodeCompletionString::CK_CurrentParameter:
    return CXCompletionChunk_CurrentParameter;
  case CodeCompletionString::CK_LeftParen:
    return CXCompletionChunk_LeftParen;
  case CodeCompletionString::CK_RightParen:
    return CXCompletionChunk_RightParen;
  case CodeCompletionString::CK_LeftBracket:
    return CXCompletionChunk_LeftBracket;
  case CodeCompletionString::CK_RightBracket:
    return CXCompletionChunk_RightBracket;
  case CodeCompletionString::CK_LeftBrace:
    return CXCompletionChunk_LeftBrace;
  case CodeCompletionString::CK_RightBrace:
    return CXCompletionChunk_RightBrace;
  case CodeCompletionString::CK_LeftAngle:
    return CXCompletionChunk_LeftAngle;
  case CodeCompletionString::CK_RightAngle:
    return CXCompletionChunk_RightAngle;
  case CodeCompletionString::CK_Comma:
    return CXCompletionChunk_Comma;
  case CodeCompletionString::CK_Colon:
    return CXCompletionChunk_Colon;
  case CodeCompletionString::CK_SemiColon:
    return CXCompletionChunk_SemiColon;
  case CodeCompletionString::CK_Equal:
    return CXCompletionChunk_Equal;
  case CodeCompletionString::CK_HorizontalSpace:
    return CXCompletionChunk_HorizontalSpace;
  case CodeCompletionString::CK_VerticalSpace:
    return CXCompletionChunk_VerticalSpace;
  }
  llvm_unreachable("Invalid CompletionKind!");
}
clang_getCompletionChunkText()
CXString clang_getCompletionChunkText (CXCompletionString completion_string, unsigned chunk_number)
Definition at line 111 of file CIndexCodeCompletion.cpp.
                                                             {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  if (!CCStr || chunk_number >= CCStr->size())
    return cxstring::createNull();
  switch ((*CCStr)[chunk_number].Kind) {
  case CodeCompletionString::CK_TypedText:
  case CodeCompletionString::CK_Text:
  case CodeCompletionString::CK_Placeholder:
  case CodeCompletionString::CK_CurrentParameter:
  case CodeCompletionString::CK_Informative:
  case CodeCompletionString::CK_LeftParen:
  case CodeCompletionString::CK_RightParen:
  case CodeCompletionString::CK_LeftBracket:
  case CodeCompletionString::CK_RightBracket:
  case CodeCompletionString::CK_LeftBrace:
  case CodeCompletionString::CK_RightBrace:
  case CodeCompletionString::CK_LeftAngle:
  case CodeCompletionString::CK_RightAngle:
  case CodeCompletionString::CK_Comma:
  case CodeCompletionString::CK_ResultType:
  case CodeCompletionString::CK_Colon:
  case CodeCompletionString::CK_SemiColon:
  case CodeCompletionString::CK_Equal:
  case CodeCompletionString::CK_HorizontalSpace:
  case CodeCompletionString::CK_VerticalSpace:
    return cxstring::createRef((*CCStr)[chunk_number].Text);
      
  case CodeCompletionString::CK_Optional:
    // Note: treated as an empty text block.
    return cxstring::createEmpty();
  }
  llvm_unreachable("Invalid CodeCompletionString Kind!");
}
References clang::cxstring::createEmpty(), clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_getCompletionFixIt()
CXString clang_getCompletionFixIt (CXCodeCompleteResults * results, unsigned completion_index, unsigned fixit_index, CXSourceRange * replacement_range)
Definition at line 322 of file CIndexCodeCompletion.cpp.
                                                                    {
  AllocatedCXCodeCompleteResults *allocated_results = (AllocatedCXCodeCompleteResults *)results;
  if (!allocated_results || allocated_results->FixItsVector.size() <= completion_index) {
    if (replacement_range)
      *replacement_range = clang_getNullRange();
    return cxstring::createNull();
  }
  ArrayRef<FixItHint> FixIts = allocated_results->FixItsVector[completion_index];
  if (FixIts.size() <= fixit_index) {
    if (replacement_range)
      *replacement_range = clang_getNullRange();
    return cxstring::createNull();
  }
  const FixItHint &FixIt = FixIts[fixit_index];
  if (replacement_range) {
    *replacement_range = cxloc::translateSourceRange(
        *allocated_results->SourceMgr, allocated_results->LangOpts,
        FixIt.RemoveRange);
  }
  return cxstring::createRef(FixIt.CodeToInsert.c_str());
}
References clang_getNullRange(), clang::cxstring::createNull(), clang::cxstring::createRef(), and clang::cxloc::translateSourceRange().
clang_getCompletionNumAnnotations()
unsigned clang_getCompletionNumAnnotations (CXCompletionString completion_string)
Definition at line 204 of file CIndexCodeCompletion.cpp.
{
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  return CCStr ? CCStr->getAnnotationCount() : 0;
}
clang_getCompletionNumFixIts()
unsigned clang_getCompletionNumFixIts (CXCodeCompleteResults * results, unsigned completion_index)
Definition at line 312 of file CIndexCodeCompletion.cpp.
                                                                 {
  AllocatedCXCodeCompleteResults *allocated_results = (AllocatedCXCodeCompleteResults *)results;
  if (!allocated_results || allocated_results->FixItsVector.size() <= completion_index)
    return 0;
  return static_cast<unsigned>(allocated_results->FixItsVector[completion_index].size());
}
clang_getCompletionParent()
CXString clang_getCompletionParent (CXCompletionString completion_string, CXCursorKind * kind)
Definition at line 218 of file CIndexCodeCompletion.cpp.
                                              {
  if (kind)
    *kind = CXCursor_NotImplemented;
  
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  if (!CCStr)
    return cxstring::createNull();
  
  return cxstring::createRef(CCStr->getParentContextName());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_getCompletionPriority()
unsigned clang_getCompletionPriority (CXCompletionString completion_string)
Definition at line 192 of file CIndexCodeCompletion.cpp.
                                                                           {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  return CCStr? CCStr->getPriority() : unsigned(CCP_Unlikely);
}
clang_getNumCompletionChunks()
unsigned clang_getNumCompletionChunks (CXCompletionString completion_string)
Definition at line 187 of file CIndexCodeCompletion.cpp.
                                                                            {
  CodeCompletionString *CCStr = (CodeCompletionString *)completion_string;
  return CCStr? CCStr->size() : 0;
}
clang_sortCodeCompletionResults()
void clang_sortCodeCompletionResults (CXCompletionResult * Results, unsigned NumResults)
Definition at line 1041 of file CIndexCodeCompletion.cpp.
                                                          {
  std::stable_sort(Results, Results + NumResults, OrderCompletionResults());
}