/Users/maximilian/clang-llvm/clang/tools/libclang/CXCursor.cpp File Reference
#include `CXCursor.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `CXType.h`
#include `clang-c/Index.h`
#include `clang/AST/Attr.h`
#include `clang/AST/Decl.h`
#include `clang/AST/DeclCXX.h`
#include `clang/AST/DeclObjC.h`
#include `clang/AST/DeclTemplate.h`
#include `clang/AST/Expr.h`
#include `clang/AST/ExprCXX.h`
#include `clang/AST/ExprObjC.h`
#include `clang/Frontend/ASTUnit.h`
#include `llvm/Support/ErrorHandling.h`
Classes
struct llvm::DenseMapInfo< CXCursor >
Namespaces
 llvm
Typedefs
typedef llvm::DenseMap< CXCursor, unsigned > CXCursorSet_Impl
Enumerations
enum CXGetTemplateArgumentStatus {
CXGetTemplateArgumentStatus_Success = 0
, CXGetTemplateArgumentStatus_CursorNotFunctionDecl = -1
, CXGetTemplateArgumentStatus_BadFunctionDeclCast = -2
, CXGetTemplateArgumentStatus_NullTemplSpecInfo = -3
,
CXGetTemplateArgumentStatus_InvalidIndex = -4
 }
Functions
int clang_Cursor_isNull (CXCursor cursor)
CXTranslationUnit clang_Cursor_getTranslationUnit (CXCursor cursor)
int clang_Cursor_getNumArguments (CXCursor C)
CXCursor clang_Cursor_getArgument (CXCursor C, unsigned i)
int clang_Cursor_getNumTemplateArguments (CXCursor C)
enum CXTemplateArgumentKind clang_Cursor_getTemplateArgumentKind (CXCursor C, unsigned I)
CXType clang_Cursor_getTemplateArgumentType (CXCursor C, unsigned I)
long long clang_Cursor_getTemplateArgumentValue (CXCursor C, unsigned I)
unsigned long long clang_Cursor_getTemplateArgumentUnsignedValue (CXCursor C, unsigned I)
CXCursorSet clang_createCXCursorSet ()
void clang_disposeCXCursorSet (CXCursorSet set)
unsigned clang_CXCursorSet_contains (CXCursorSet set, CXCursor cursor)
unsigned clang_CXCursorSet_insert (CXCursorSet set, CXCursor cursor)
CXCompletionString clang_getCursorCompletionString (CXCursor cursor)
void clang_getOverriddenCursors (CXCursor cursor, CXCursor **overridden, unsigned *num_overridden)
void clang_disposeOverriddenCursors (CXCursor *overridden)
int clang_Cursor_isDynamicCall (CXCursor C)
CXType clang_Cursor_getReceiverType (CXCursor C)
Typedef Documentation
CXCursorSet_Impl
typedef llvm::DenseMap<CXCursor, unsigned> CXCursorSet_Impl
Definition at line 1461 of file CXCursor.cpp.
Enumeration Type Documentation
CXGetTemplateArgumentStatus
enum CXGetTemplateArgumentStatus
Enumerator
CXGetTemplateArgumentStatus_Success The operation completed successfully
CXGetTemplateArgumentStatus_CursorNotFunctionDecl The specified cursor did not represent a FunctionDecl.
CXGetTemplateArgumentStatus_BadFunctionDeclCast The specified cursor was not castable to a FunctionDecl.
CXGetTemplateArgumentStatus_NullTemplSpecInfo A NULL FunctionTemplateSpecializationInfo was retrieved.
CXGetTemplateArgumentStatus_InvalidIndex An invalid (OOB) argument index was specified
Definition at line 1336 of file CXCursor.cpp.
                                 {
  CXGetTemplateArgumentStatus_Success = 0,
  CXGetTemplateArgumentStatus_CursorNotFunctionDecl = -1,
  CXGetTemplateArgumentStatus_BadFunctionDeclCast = -2,
  CXGetTemplateArgumentStatus_NullTemplSpecInfo = -3,
  CXGetTemplateArgumentStatus_InvalidIndex = -4
};
Function Documentation
clang_createCXCursorSet()
CXCursorSet clang_createCXCursorSet ()
Definition at line 1488 of file CXCursor.cpp.
                                      {
  return packCXCursorSet(new CXCursorSet_Impl());
}
clang_Cursor_getArgument()
CXCursor clang_Cursor_getArgument (CXCursor C, unsigned i)
Definition at line 1283 of file CXCursor.cpp.
                                                          {
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const ObjCMethodDecl *MD = dyn_cast_or_null<ObjCMethodDecl>(D)) {
      if (i < MD->param_size())
        return cxcursor::MakeCXCursor(MD->parameters()[i],
                                      cxcursor::getCursorTU(C));
    } else if (const FunctionDecl *FD = dyn_cast_or_null<FunctionDecl>(D)) {
      if (i < FD->param_size())
        return cxcursor::MakeCXCursor(FD->parameters()[i],
                                      cxcursor::getCursorTU(C));
    }
  }
  if (clang_isExpression(C.kind)) {
    const Expr *E = cxcursor::getCursorExpr(C);
    if (const CallExpr *CE = dyn_cast<CallExpr>(E)) {
      if (i < CE->getNumArgs()) {
        return cxcursor::MakeCXCursor(CE->getArg(i), getCursorDecl(C),
                                      cxcursor::getCursorTU(C));
      }
    }
    if (const CXXConstructExpr *CE = dyn_cast<CXXConstructExpr>(E)) {
      if (i < CE->getNumArgs()) {
        return cxcursor::MakeCXCursor(CE->getArg(i), getCursorDecl(C),
                                      cxcursor::getCursorTU(C));
      }
    }
  }
  return clang_getNullCursor();
}
References clang_getNullCursor(), clang_isDeclaration(), clang_isExpression(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorExpr(), clang::cxcursor::getCursorTU(), and clang::cxcursor::MakeCXCursor().
clang_Cursor_getNumArguments()
int clang_Cursor_getNumArguments (CXCursor C)
Definition at line 1261 of file CXCursor.cpp.
                                             {
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const ObjCMethodDecl *MD = dyn_cast_or_null<ObjCMethodDecl>(D))
      return MD->param_size();
    if (const FunctionDecl *FD = dyn_cast_or_null<FunctionDecl>(D))
      return FD->param_size();
  }
  if (clang_isExpression(C.kind)) {
    const Expr *E = cxcursor::getCursorExpr(C);
    if (const CallExpr *CE = dyn_cast<CallExpr>(E)) {
      return CE->getNumArgs();
    }
    if (const CXXConstructExpr *CE = dyn_cast<CXXConstructExpr>(E)) {
      return CE->getNumArgs();
    }
  }
  return -1;
}
References clang_isDeclaration(), clang_isExpression(), clang::cxcursor::getCursorDecl(), and clang::cxcursor::getCursorExpr().
clang_Cursor_getNumTemplateArguments()
int clang_Cursor_getNumTemplateArguments (CXCursor C)
Definition at line 1316 of file CXCursor.cpp.
                                                     {
  if (clang_getCursorKind(C) != CXCursor_FunctionDecl) {
    return -1;
  }
  const FunctionDecl *FD =
      llvm::dyn_cast_or_null<clang::FunctionDecl>(getCursorDecl(C));
  if (!FD) {
    return -1;
  }
  const FunctionTemplateSpecializationInfo *SpecInfo =
      FD->getTemplateSpecializationInfo();
  if (!SpecInfo) {
    return -1;
  }
  return SpecInfo->TemplateArguments->size();
}
References clang_getCursorKind(), and clang::cxcursor::getCursorDecl().
clang_Cursor_getReceiverType()
CXType clang_Cursor_getReceiverType (CXCursor C)
Definition at line 1687 of file CXCursor.cpp.
                                                {
  CXTranslationUnit TU = cxcursor::getCursorTU(C);
  const Expr *E = nullptr;
  if (clang_isExpression(C.kind))
    E = getCursorExpr(C);
  if (const ObjCMessageExpr *MsgE = dyn_cast_or_null<ObjCMessageExpr>(E))
    return cxtype::MakeCXType(MsgE->getReceiverType(), TU);
  if (auto *PropRefE = dyn_cast<ObjCPropertyRefExpr>(E)) {
    return cxtype::MakeCXType(
        PropRefE->getReceiverType(cxcursor::getCursorContext(C)), TU);
  }
  const MemberExpr *ME = nullptr;
  if (isa<MemberExpr>(E))
    ME = cast<MemberExpr>(E);
  else if (const CallExpr *CE = dyn_cast<CallExpr>(E))
    ME = dyn_cast_or_null<MemberExpr>(CE->getCallee());
  if (ME) {
    if (dyn_cast_or_null<CXXMethodDecl>(ME->getMemberDecl())) {
      auto receiverTy = ME->getBase()->IgnoreImpCasts()->getType();
      return cxtype::MakeCXType(receiverTy, TU);
    }
  }
  return cxtype::MakeCXType(QualType(), TU);
}
References clang_isExpression(), clang::cxcursor::getCursorContext(), clang::cxcursor::getCursorExpr(), clang::cxcursor::getCursorTU(), and clang::cxtype::MakeCXType().
clang_Cursor_getTemplateArgumentKind()
enum CXTemplateArgumentKind clang_Cursor_getTemplateArgumentKind (CXCursor C, unsigned I)
Definition at line 1353 of file CXCursor.cpp.
                                                                             {
  TemplateArgument TA;
  if (clang_Cursor_getTemplateArgument(C, I, &TA)) {
    return CXTemplateArgumentKind_Invalid;
  }
  switch (TA.getKind()) {
  case TemplateArgument::Null:
    return CXTemplateArgumentKind_Null;
  case TemplateArgument::Type:
    return CXTemplateArgumentKind_Type;
  case TemplateArgument::Declaration:
    return CXTemplateArgumentKind_Declaration;
  case TemplateArgument::NullPtr:
    return CXTemplateArgumentKind_NullPtr;
  case TemplateArgument::Integral:
    return CXTemplateArgumentKind_Integral;
  case TemplateArgument::Template:
    return CXTemplateArgumentKind_Template;
  case TemplateArgument::TemplateExpansion:
    return CXTemplateArgumentKind_TemplateExpansion;
  case TemplateArgument::Expression:
    return CXTemplateArgumentKind_Expression;
  case TemplateArgument::Pack:
    return CXTemplateArgumentKind_Pack;
  }
  return CXTemplateArgumentKind_Invalid;
}
clang_Cursor_getTemplateArgumentType()
CXType clang_Cursor_getTemplateArgumentType (CXCursor C, unsigned I)
Definition at line 1410 of file CXCursor.cpp.
                                                                    {
  TemplateArgument TA;
  if (clang_Cursor_getTemplateArgument(C, I, &TA) !=
      CXGetTemplateArgumentStatus_Success) {
    return cxtype::MakeCXType(QualType(), getCursorTU(C));
  }
  if (TA.getKind() != TemplateArgument::Type) {
    return cxtype::MakeCXType(QualType(), getCursorTU(C));
  }
  return cxtype::MakeCXType(TA.getAsType(), getCursorTU(C));
}
clang_Cursor_getTemplateArgumentUnsignedValue()
unsigned long long clang_Cursor_getTemplateArgumentUnsignedValue (CXCursor C, unsigned I)
Definition at line 1440 of file CXCursor.cpp.
                                                                             {
  TemplateArgument TA;
  if (clang_Cursor_getTemplateArgument(C, I, &TA) !=
      CXGetTemplateArgumentStatus_Success) {
    assert(0 && "Unable to retrieve TemplateArgument");
    return 0;
  }
  if (TA.getKind() != TemplateArgument::Integral) {
    assert(0 && "Passed template argument is not Integral");
    return 0;
  }
  return TA.getAsIntegral().getZExtValue();
}
clang_Cursor_getTemplateArgumentValue()
long long clang_Cursor_getTemplateArgumentValue (CXCursor C, unsigned I)
Definition at line 1424 of file CXCursor.cpp.
                                                                        {
  TemplateArgument TA;
  if (clang_Cursor_getTemplateArgument(C, I, &TA) !=
      CXGetTemplateArgumentStatus_Success) {
    assert(0 && "Unable to retrieve TemplateArgument");
    return 0;
  }
  if (TA.getKind() != TemplateArgument::Integral) {
    assert(0 && "Passed template argument is not Integral");
    return 0;
  }
  return TA.getAsIntegral().getSExtValue();
}
clang_Cursor_getTranslationUnit()
CXTranslationUnit clang_Cursor_getTranslationUnit (CXCursor cursor)
Definition at line 1257 of file CXCursor.cpp.
                                                                   {
  return getCursorTU(cursor);
}
References clang::cxcursor::getCursorTU().
clang_Cursor_isDynamicCall()
int clang_Cursor_isDynamicCall (CXCursor C)
Definition at line 1648 of file CXCursor.cpp.
                                           {
  const Expr *E = nullptr;
  if (clang_isExpression(C.kind))
    E = getCursorExpr(C);
  if (!E)
    return 0;
  if (const ObjCMessageExpr *MsgE = dyn_cast<ObjCMessageExpr>(E)) {
    if (MsgE->getReceiverKind() != ObjCMessageExpr::Instance)
      return false;
    if (auto *RecE = dyn_cast<ObjCMessageExpr>(
            MsgE->getInstanceReceiver()->IgnoreParenCasts())) {
      if (RecE->getMethodFamily() == OMF_alloc)
        return false;
    }
    return true;
  }
  if (auto *PropRefE = dyn_cast<ObjCPropertyRefExpr>(E)) {
    return !PropRefE->isSuperReceiver();
  }
  const MemberExpr *ME = nullptr;
  if (isa<MemberExpr>(E))
    ME = cast<MemberExpr>(E);
  else if (const CallExpr *CE = dyn_cast<CallExpr>(E))
    ME = dyn_cast_or_null<MemberExpr>(CE->getCallee());
  if (ME) {
    if (const CXXMethodDecl *MD =
            dyn_cast_or_null<CXXMethodDecl>(ME->getMemberDecl()))
      return MD->isVirtual() &&
             ME->performsVirtualDispatch(
                 cxcursor::getCursorContext(C).getLangOpts());
  }
  return 0;
}
References clang_isExpression(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorExpr().
clang_Cursor_isNull()
int clang_Cursor_isNull (CXCursor cursor)
Definition at line 1253 of file CXCursor.cpp.
                                         {
  return clang_equalCursors(cursor, clang_getNullCursor());
}
References clang_equalCursors(), and clang_getNullCursor().
Referenced by clang_Cursor_getSpellingNameRange(), clang_findReferencesInFile(), clang_getCursorPrettyPrinted(), and clang_getCursorPrintingPolicy().
clang_CXCursorSet_contains()
unsigned clang_CXCursorSet_contains (CXCursorSet set, CXCursor cursor)
Definition at line 1496 of file CXCursor.cpp.
                                                                      {
  CXCursorSet_Impl *setImpl = unpackCXCursorSet(set);
  if (!setImpl)
    return 0;
  return setImpl->find(cursor) != setImpl->end();
}
clang_CXCursorSet_insert()
unsigned clang_CXCursorSet_insert (CXCursorSet set, CXCursor cursor)
Definition at line 1503 of file CXCursor.cpp.
                                                                    {
  // Do not insert invalid cursors into the set.
  if (cursor.kind >= CXCursor_FirstInvalid &&
      cursor.kind <= CXCursor_LastInvalid)
    return 1;
  CXCursorSet_Impl *setImpl = unpackCXCursorSet(set);
  if (!setImpl)
    return 1;
  unsigned &entry = (*setImpl)[cursor];
  unsigned flag = entry == 0 ? 1 : 0;
  entry = 1;
  return flag;
}
clang_disposeCXCursorSet()
void clang_disposeCXCursorSet (CXCursorSet set)
Definition at line 1492 of file CXCursor.cpp.
                                               {
  delete unpackCXCursorSet(set);
}
clang_disposeOverriddenCursors()
void clang_disposeOverriddenCursors (CXCursor * overridden)
Definition at line 1628 of file CXCursor.cpp.
                                                          {
  if (!overridden)
    return;
  // Use pointer arithmetic to get back the first faux entry
  // which has a back-reference to the TU and the vector.
  --overridden;
  OverridenCursorsPool::CursorVec *Vec =
      static_cast<OverridenCursorsPool::CursorVec *>(
          const_cast<void *>(overridden->data[0]));
  CXTranslationUnit TU = getCursorTU(*overridden);
  assert(Vec && TU);
  OverridenCursorsPool &pool =
      *static_cast<OverridenCursorsPool *>(TU->OverridenCursorsPool);
  pool.AvailableCursors.push_back(Vec);
}
References clang::cxcursor::getCursorTU().
clang_getCursorCompletionString()
CXCompletionString clang_getCursorCompletionString (CXCursor cursor)
Definition at line 1518 of file CXCursor.cpp.
                                                                    {
  enum CXCursorKind kind = clang_getCursorKind(cursor);
  if (clang_isDeclaration(kind)) {
    const Decl *decl = getCursorDecl(cursor);
    if (const NamedDecl *namedDecl = dyn_cast_or_null<NamedDecl>(decl)) {
      ASTUnit *unit = getCursorASTUnit(cursor);
      CodeCompletionResult Result(namedDecl, CCP_Declaration);
      CodeCompletionString *String = Result.CreateCodeCompletionString(
          unit->getASTContext(), unit->getPreprocessor(),
          CodeCompletionContext::CCC_Other,
          unit->getCodeCompletionTUInfo().getAllocator(),
          unit->getCodeCompletionTUInfo(), true);
      return String;
    }
  } else if (kind == CXCursor_MacroDefinition) {
    const MacroDefinitionRecord *definition = getCursorMacroDefinition(cursor);
    const IdentifierInfo *Macro = definition->getName();
    ASTUnit *unit = getCursorASTUnit(cursor);
    CodeCompletionResult Result(
        Macro,
        unit->getPreprocessor().getMacroDefinition(Macro).getMacroInfo());
    CodeCompletionString *String = Result.CreateCodeCompletionString(
        unit->getASTContext(), unit->getPreprocessor(),
        CodeCompletionContext::CCC_Other,
        unit->getCodeCompletionTUInfo().getAllocator(),
        unit->getCodeCompletionTUInfo(), false);
    return String;
  }
  return nullptr;
}
References clang_getCursorKind(), clang_isDeclaration(), clang::cxcursor::getCursorASTUnit(), clang::cxcursor::getCursorDecl(), and clang::cxcursor::getCursorMacroDefinition().
clang_getOverriddenCursors()
void clang_getOverriddenCursors (CXCursor cursor, CXCursor ** overridden, unsigned * num_overridden)
Definition at line 1573 of file CXCursor.cpp.
                                                          {
  if (overridden)
    *overridden = nullptr;
  if (num_overridden)
    *num_overridden = 0;
  CXTranslationUnit TU = cxcursor::getCursorTU(cursor);
  if (!overridden || !num_overridden || !TU)
    return;
  if (!clang_isDeclaration(cursor.kind))
    return;
  OverridenCursorsPool &pool =
      *static_cast<OverridenCursorsPool *>(TU->OverridenCursorsPool);
  OverridenCursorsPool::CursorVec *Vec = nullptr;
  if (!pool.AvailableCursors.empty()) {
    Vec = pool.AvailableCursors.back();
    pool.AvailableCursors.pop_back();
  } else {
    Vec = new OverridenCursorsPool::CursorVec();
    pool.AllCursors.push_back(Vec);
  }
  // Clear out the vector, but don't free the memory contents. This
  // reduces malloc() traffic.
  Vec->clear();
  // Use the first entry to contain a back reference to the vector.
  // This is a complete hack.
  CXCursor backRefCursor = MakeCXCursorInvalid(CXCursor_InvalidFile, TU);
  backRefCursor.data[0] = Vec;
  assert(cxcursor::getCursorTU(backRefCursor) == TU);
  Vec->push_back(backRefCursor);
  // Get the overridden cursors.
  cxcursor::getOverriddenCursors(cursor, *Vec);
  // Did we get any overridden cursors? If not, return Vec to the pool
  // of available cursor vectors.
  if (Vec->size() == 1) {
    pool.AvailableCursors.push_back(Vec);
    return;
  }
  // Now tell the caller about the overridden cursors.
  assert(Vec->size() > 1);
  *overridden = &((*Vec)[1]);
  *num_overridden = Vec->size() - 1;
}
References clang_isDeclaration(), clang::cxcursor::getCursorTU(), clang::cxcursor::getOverriddenCursors(), and clang::cxcursor::MakeCXCursorInvalid().