/Users/maximilian/clang-llvm/clang/tools/libclang/CXComment.cpp File Reference
#include `CXComment.h`
#include `CXCursor.h`
#include `CXString.h`
#include `clang-c/Documentation.h`
#include `clang-c/Index.h`
#include `clang/AST/Decl.h`
#include `clang/Index/CommentToXML.h`
#include `llvm/ADT/StringExtras.h`
#include `llvm/Support/ErrorHandling.h`
#include <climits>
Functions
CXComment clang_Cursor_getParsedComment (CXCursor C)
enum CXCommentKind clang_Comment_getKind (CXComment CXC)
unsigned clang_Comment_getNumChildren (CXComment CXC)
CXComment clang_Comment_getChild (CXComment CXC, unsigned ChildIdx)
unsigned clang_Comment_isWhitespace (CXComment CXC)
unsigned clang_InlineContentComment_hasTrailingNewline (CXComment CXC)
CXString clang_TextComment_getText (CXComment CXC)
CXString clang_InlineCommandComment_getCommandName (CXComment CXC)
enum CXCommentInlineCommandRenderKind clang_InlineCommandComment_getRenderKind (CXComment CXC)
unsigned clang_InlineCommandComment_getNumArgs (CXComment CXC)
CXString clang_InlineCommandComment_getArgText (CXComment CXC, unsigned ArgIdx)
CXString clang_HTMLTagComment_getTagName (CXComment CXC)
unsigned clang_HTMLStartTagComment_isSelfClosing (CXComment CXC)
unsigned clang_HTMLStartTag_getNumAttrs (CXComment CXC)
CXString clang_HTMLStartTag_getAttrName (CXComment CXC, unsigned AttrIdx)
CXString clang_HTMLStartTag_getAttrValue (CXComment CXC, unsigned AttrIdx)
CXString clang_BlockCommandComment_getCommandName (CXComment CXC)
unsigned clang_BlockCommandComment_getNumArgs (CXComment CXC)
CXString clang_BlockCommandComment_getArgText (CXComment CXC, unsigned ArgIdx)
CXComment clang_BlockCommandComment_getParagraph (CXComment CXC)
CXString clang_ParamCommandComment_getParamName (CXComment CXC)
unsigned clang_ParamCommandComment_isParamIndexValid (CXComment CXC)
unsigned clang_ParamCommandComment_getParamIndex (CXComment CXC)
unsigned clang_ParamCommandComment_isDirectionExplicit (CXComment CXC)
enum CXCommentParamPassDirection clang_ParamCommandComment_getDirection (CXComment CXC)
CXString clang_TParamCommandComment_getParamName (CXComment CXC)
unsigned clang_TParamCommandComment_isParamPositionValid (CXComment CXC)
unsigned clang_TParamCommandComment_getDepth (CXComment CXC)
unsigned clang_TParamCommandComment_getIndex (CXComment CXC, unsigned Depth)
CXString clang_VerbatimBlockLineComment_getText (CXComment CXC)
CXString clang_VerbatimLineComment_getText (CXComment CXC)
CXString clang_HTMLTagComment_getAsString (CXComment CXC)
CXString clang_FullComment_getAsHTML (CXComment CXC)
CXString clang_FullComment_getAsXML (CXComment CXC)
Function Documentation
clang_BlockCommandComment_getArgText()
CXString clang_BlockCommandComment_getArgText (CXComment CXC, unsigned ArgIdx)
Definition at line 243 of file CXComment.cpp.
                                                               {
  const BlockCommandComment *BCC = getASTNodeAs<BlockCommandComment>(CXC);
  if (!BCC || ArgIdx >= BCC->getNumArgs())
    return cxstring::createNull();
  return cxstring::createRef(BCC->getArgText(ArgIdx));
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_BlockCommandComment_getCommandName()
CXString clang_BlockCommandComment_getCommandName (CXComment CXC)
Definition at line 226 of file CXComment.cpp.
                                                                 {
  const BlockCommandComment *BCC = getASTNodeAs<BlockCommandComment>(CXC);
  if (!BCC)
    return cxstring::createNull();
  const CommandTraits &Traits = getCommandTraits(CXC);
  return cxstring::createRef(BCC->getCommandName(Traits));
}
References clang::cxstring::createNull().
clang_BlockCommandComment_getNumArgs()
unsigned clang_BlockCommandComment_getNumArgs (CXComment CXC)
Definition at line 235 of file CXComment.cpp.
                                                             {
  const BlockCommandComment *BCC = getASTNodeAs<BlockCommandComment>(CXC);
  if (!BCC)
    return 0;
  return BCC->getNumArgs();
}
clang_BlockCommandComment_getParagraph()
CXComment clang_BlockCommandComment_getParagraph (CXComment CXC)
Definition at line 252 of file CXComment.cpp.
                                                                {
  const BlockCommandComment *BCC = getASTNodeAs<BlockCommandComment>(CXC);
  if (!BCC)
    return createCXComment(nullptr, nullptr);
  return createCXComment(BCC->getParagraph(), CXC.TranslationUnit);
}
clang_Comment_getChild()
CXComment clang_Comment_getChild (CXComment CXC, unsigned ChildIdx)
Definition at line 97 of file CXComment.cpp.
                                                                   {
  const Comment *C = getASTNode(CXC);
  if (!C || ChildIdx >= C->child_count())
    return createCXComment(nullptr, nullptr);
  return createCXComment(*(C->child_begin() + ChildIdx), CXC.TranslationUnit);
}
clang_Comment_getKind()
enum CXCommentKind clang_Comment_getKind (CXComment CXC)
Definition at line 28 of file CXComment.cpp.
                                                        {
  const Comment *C = getASTNode(CXC);
  if (!C)
    return CXComment_Null;
  switch (C->getCommentKind()) {
  case Comment::NoCommentKind:
    return CXComment_Null;
  case Comment::TextCommentKind:
    return CXComment_Text;
  case Comment::InlineCommandCommentKind:
    return CXComment_InlineCommand;
  case Comment::HTMLStartTagCommentKind:
    return CXComment_HTMLStartTag;
  case Comment::HTMLEndTagCommentKind:
    return CXComment_HTMLEndTag;
  case Comment::ParagraphCommentKind:
    return CXComment_Paragraph;
  case Comment::BlockCommandCommentKind:
    return CXComment_BlockCommand;
  case Comment::ParamCommandCommentKind:
    return CXComment_ParamCommand;
  case Comment::TParamCommandCommentKind:
    return CXComment_TParamCommand;
  case Comment::VerbatimBlockCommentKind:
    return CXComment_VerbatimBlockCommand;
  case Comment::VerbatimBlockLineCommentKind:
    return CXComment_VerbatimBlockLine;
  case Comment::VerbatimLineCommentKind:
    return CXComment_VerbatimLine;
  case Comment::FullCommentKind:
    return CXComment_FullComment;
  }
  llvm_unreachable("unknown CommentKind");
}
References clang_isDeclaration().
clang_Comment_getNumChildren()
unsigned clang_Comment_getNumChildren (CXComment CXC)
Definition at line 89 of file CXComment.cpp.
                                                     {
  const Comment *C = getASTNode(CXC);
  if (!C)
    return 0;
  return C->child_count();
}
clang_Comment_isWhitespace()
unsigned clang_Comment_isWhitespace (CXComment CXC)
Definition at line 105 of file CXComment.cpp.
                                                   {
  const Comment *C = getASTNode(CXC);
  if (!C)
    return false;
  if (const TextComment *TC = dyn_cast<TextComment>(C))
    return TC->isWhitespace();
  if (const ParagraphComment *PC = dyn_cast<ParagraphComment>(C))
    return PC->isWhitespace();
  return false;
}
clang_Cursor_getParsedComment()
CXComment clang_Cursor_getParsedComment (CXCursor C)
Definition at line 28 of file CXComment.cpp.
                                                    {
  using namespace clang::cxcursor;
  if (!clang_isDeclaration(C.kind))
    return createCXComment(nullptr, nullptr);
  const Decl *D = getCursorDecl(C);
  const ASTContext &Context = getCursorContext(C);
  const FullComment *FC = Context.getCommentForDecl(D, /*PP=*/nullptr);
  return createCXComment(FC, getCursorTU(C));
}
clang_FullComment_getAsHTML()
CXString clang_FullComment_getAsHTML (CXComment CXC)
Definition at line 379 of file CXComment.cpp.
                                                    {
  const FullComment *FC = getASTNodeAs<FullComment>(CXC);
  if (!FC)
    return cxstring::createNull();
  CXTranslationUnit TU = CXC.TranslationUnit;
  if (!TU->CommentToXML)
    TU->CommentToXML = new clang::index::CommentToXMLConverter();
  SmallString<1024> HTML;
  TU->CommentToXML
      ->convertCommentToHTML(FC, HTML, cxtu::getASTUnit(TU)->getASTContext());
  return cxstring::createDup(HTML.str());
}
References clang::cxstring::createNull().
clang_FullComment_getAsXML()
CXString clang_FullComment_getAsXML (CXComment CXC)
Definition at line 394 of file CXComment.cpp.
                                                   {
  const FullComment *FC = getASTNodeAs<FullComment>(CXC);
  if (!FC)
    return cxstring::createNull();
  CXTranslationUnit TU = CXC.TranslationUnit;
  if (!TU->CommentToXML)
    TU->CommentToXML = new clang::index::CommentToXMLConverter();
  SmallString<1024> XML;
  TU->CommentToXML
      ->convertCommentToXML(FC, XML, cxtu::getASTUnit(TU)->getASTContext());
  return cxstring::createDup(XML.str());
}
References clang::cxstring::createNull().
clang_HTMLStartTag_getAttrName()
CXString clang_HTMLStartTag_getAttrName (CXComment CXC, unsigned AttrIdx)
Definition at line 210 of file CXComment.cpp.
                                                                         {
  const HTMLStartTagComment *HST = getASTNodeAs<HTMLStartTagComment>(CXC);
  if (!HST || AttrIdx >= HST->getNumAttrs())
    return cxstring::createNull();
  return cxstring::createRef(HST->getAttr(AttrIdx).Name);
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_HTMLStartTag_getAttrValue()
CXString clang_HTMLStartTag_getAttrValue (CXComment CXC, unsigned AttrIdx)
Definition at line 218 of file CXComment.cpp.
                                                                          {
  const HTMLStartTagComment *HST = getASTNodeAs<HTMLStartTagComment>(CXC);
  if (!HST || AttrIdx >= HST->getNumAttrs())
    return cxstring::createNull();
  return cxstring::createRef(HST->getAttr(AttrIdx).Value);
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_HTMLStartTag_getNumAttrs()
unsigned clang_HTMLStartTag_getNumAttrs (CXComment CXC)
Definition at line 202 of file CXComment.cpp.
                                                       {
  const HTMLStartTagComment *HST = getASTNodeAs<HTMLStartTagComment>(CXC);
  if (!HST)
    return 0;
  return HST->getNumAttrs();
}
clang_HTMLStartTagComment_isSelfClosing()
unsigned clang_HTMLStartTagComment_isSelfClosing (CXComment CXC)
Definition at line 194 of file CXComment.cpp.
                                                                {
  const HTMLStartTagComment *HST = getASTNodeAs<HTMLStartTagComment>(CXC);
  if (!HST)
    return false;
  return HST->isSelfClosing();
}
clang_HTMLTagComment_getAsString()
CXString clang_HTMLTagComment_getAsString (CXComment CXC)
Definition at line 364 of file CXComment.cpp.
                                                         {
  const HTMLTagComment *HTC = getASTNodeAs<HTMLTagComment>(CXC);
  if (!HTC)
    return cxstring::createNull();
  CXTranslationUnit TU = CXC.TranslationUnit;
  if (!TU->CommentToXML)
    TU->CommentToXML = new clang::index::CommentToXMLConverter();
  SmallString<128> Text;
  TU->CommentToXML->convertHTMLTagNodeToText(
      HTC, Text, cxtu::getASTUnit(TU)->getASTContext());
  return cxstring::createDup(Text.str());
}
References clang::cxstring::createNull().
clang_HTMLTagComment_getTagName()
CXString clang_HTMLTagComment_getTagName (CXComment CXC)
Definition at line 186 of file CXComment.cpp.
                                                        {
  const HTMLTagComment *HTC = getASTNodeAs<HTMLTagComment>(CXC);
  if (!HTC)
    return cxstring::createNull();
  return cxstring::createRef(HTC->getTagName());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_InlineCommandComment_getArgText()
CXString clang_InlineCommandComment_getArgText (CXComment CXC, unsigned ArgIdx)
Definition at line 177 of file CXComment.cpp.
                                                                {
  const InlineCommandComment *ICC = getASTNodeAs<InlineCommandComment>(CXC);
  if (!ICC || ArgIdx >= ICC->getNumArgs())
    return cxstring::createNull();
  return cxstring::createRef(ICC->getArgText(ArgIdx));
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_InlineCommandComment_getCommandName()
CXString clang_InlineCommandComment_getCommandName (CXComment CXC)
Definition at line 135 of file CXComment.cpp.
                                                                  {
  const InlineCommandComment *ICC = getASTNodeAs<InlineCommandComment>(CXC);
  if (!ICC)
    return cxstring::createNull();
  const CommandTraits &Traits = getCommandTraits(CXC);
  return cxstring::createRef(ICC->getCommandName(Traits));
}
References clang::cxstring::createNull().
clang_InlineCommandComment_getNumArgs()
unsigned clang_InlineCommandComment_getNumArgs (CXComment CXC)
Definition at line 169 of file CXComment.cpp.
                                                              {
  const InlineCommandComment *ICC = getASTNodeAs<InlineCommandComment>(CXC);
  if (!ICC)
    return 0;
  return ICC->getNumArgs();
}
clang_InlineCommandComment_getRenderKind()
enum CXCommentInlineCommandRenderKind clang_InlineCommandComment_getRenderKind (CXComment CXC)
Definition at line 135 of file CXComment.cpp.
                                                        {
  const InlineCommandComment *ICC = getASTNodeAs<InlineCommandComment>(CXC);
  if (!ICC)
    return CXCommentInlineCommandRenderKind_Normal;
  switch (ICC->getRenderKind()) {
  case InlineCommandComment::RenderNormal:
    return CXCommentInlineCommandRenderKind_Normal;
  case InlineCommandComment::RenderBold:
    return CXCommentInlineCommandRenderKind_Bold;
  case InlineCommandComment::RenderMonospaced:
    return CXCommentInlineCommandRenderKind_Monospaced;
  case InlineCommandComment::RenderEmphasized:
    return CXCommentInlineCommandRenderKind_Emphasized;
  case InlineCommandComment::RenderAnchor:
    return CXCommentInlineCommandRenderKind_Anchor;
  }
  llvm_unreachable("unknown InlineCommandComment::RenderKind");
}
clang_InlineContentComment_hasTrailingNewline()
unsigned clang_InlineContentComment_hasTrailingNewline (CXComment CXC)
Definition at line 119 of file CXComment.cpp.
                                                                      {
  const InlineContentComment *ICC = getASTNodeAs<InlineContentComment>(CXC);
  if (!ICC)
    return false;
  return ICC->hasTrailingNewline();
}
clang_ParamCommandComment_getDirection()
enum CXCommentParamPassDirection clang_ParamCommandComment_getDirection (CXComment CXC)
Definition at line 284 of file CXComment.cpp.
                                                                           {
  const ParamCommandComment *PCC = getASTNodeAs<ParamCommandComment>(CXC);
  if (!PCC)
    return CXCommentParamPassDirection_In;
  switch (PCC->getDirection()) {
  case ParamCommandComment::In:
    return CXCommentParamPassDirection_In;
  case ParamCommandComment::Out:
    return CXCommentParamPassDirection_Out;
  case ParamCommandComment::InOut:
    return CXCommentParamPassDirection_InOut;
  }
  llvm_unreachable("unknown ParamCommandComment::PassDirection");
}
clang_ParamCommandComment_getParamIndex()
unsigned clang_ParamCommandComment_getParamIndex (CXComment CXC)
Definition at line 276 of file CXComment.cpp.
                                                                {
  const ParamCommandComment *PCC = getASTNodeAs<ParamCommandComment>(CXC);
  if (!PCC || !PCC->isParamIndexValid() || PCC->isVarArgParam())
    return ParamCommandComment::InvalidParamIndex;
  return PCC->getParamIndex();
}
clang_ParamCommandComment_getParamName()
CXString clang_ParamCommandComment_getParamName (CXComment CXC)
Definition at line 260 of file CXComment.cpp.
                                                               {
  const ParamCommandComment *PCC = getASTNodeAs<ParamCommandComment>(CXC);
  if (!PCC || !PCC->hasParamName())
    return cxstring::createNull();
  return cxstring::createRef(PCC->getParamNameAsWritten());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_ParamCommandComment_isDirectionExplicit()
unsigned clang_ParamCommandComment_isDirectionExplicit (CXComment CXC)
Definition at line 284 of file CXComment.cpp.
                                                                      {
  const ParamCommandComment *PCC = getASTNodeAs<ParamCommandComment>(CXC);
  if (!PCC)
    return false;
  return PCC->isDirectionExplicit();
}
clang_ParamCommandComment_isParamIndexValid()
unsigned clang_ParamCommandComment_isParamIndexValid (CXComment CXC)
Definition at line 268 of file CXComment.cpp.
                                                                    {
  const ParamCommandComment *PCC = getASTNodeAs<ParamCommandComment>(CXC);
  if (!PCC)
    return false;
  return PCC->isParamIndexValid();
}
clang_TextComment_getText()
CXString clang_TextComment_getText (CXComment CXC)
Definition at line 127 of file CXComment.cpp.
                                                  {
  const TextComment *TC = getASTNodeAs<TextComment>(CXC);
  if (!TC)
    return cxstring::createNull();
  return cxstring::createRef(TC->getText());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_TParamCommandComment_getDepth()
unsigned clang_TParamCommandComment_getDepth (CXComment CXC)
Definition at line 327 of file CXComment.cpp.
                                                            {
  const TParamCommandComment *TPCC = getASTNodeAs<TParamCommandComment>(CXC);
  if (!TPCC || !TPCC->isPositionValid())
    return 0;
  return TPCC->getDepth();
}
clang_TParamCommandComment_getIndex()
unsigned clang_TParamCommandComment_getIndex (CXComment CXC, unsigned Depth)
Definition at line 335 of file CXComment.cpp.
                                                                            {
  const TParamCommandComment *TPCC = getASTNodeAs<TParamCommandComment>(CXC);
  if (!TPCC || !TPCC->isPositionValid() || Depth >= TPCC->getDepth())
    return 0;
  return TPCC->getIndex(Depth);
}
clang_TParamCommandComment_getParamName()
CXString clang_TParamCommandComment_getParamName (CXComment CXC)
Definition at line 311 of file CXComment.cpp.
                                                                {
  const TParamCommandComment *TPCC = getASTNodeAs<TParamCommandComment>(CXC);
  if (!TPCC || !TPCC->hasParamName())
    return cxstring::createNull();
  return cxstring::createRef(TPCC->getParamNameAsWritten());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_TParamCommandComment_isParamPositionValid()
unsigned clang_TParamCommandComment_isParamPositionValid (CXComment CXC)
Definition at line 319 of file CXComment.cpp.
                                                                        {
  const TParamCommandComment *TPCC = getASTNodeAs<TParamCommandComment>(CXC);
  if (!TPCC)
    return false;
  return TPCC->isPositionValid();
}
clang_VerbatimBlockLineComment_getText()
CXString clang_VerbatimBlockLineComment_getText (CXComment CXC)
Definition at line 343 of file CXComment.cpp.
                                                               {
  const VerbatimBlockLineComment *VBL =
      getASTNodeAs<VerbatimBlockLineComment>(CXC);
  if (!VBL)
    return cxstring::createNull();
  return cxstring::createRef(VBL->getText());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_VerbatimLineComment_getText()
CXString clang_VerbatimLineComment_getText (CXComment CXC)
Definition at line 352 of file CXComment.cpp.
                                                          {
  const VerbatimLineComment *VLC = getASTNodeAs<VerbatimLineComment>(CXC);
  if (!VLC)
    return cxstring::createNull();
  return cxstring::createRef(VLC->getText());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().