/Users/maximilian/clang-llvm/clang/tools/libclang/CXType.cpp File Reference
#include `CIndexer.h`
#include `CXCursor.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `CXType.h`
#include `clang/AST/Decl.h`
#include `clang/AST/DeclObjC.h`
#include `clang/AST/DeclTemplate.h`
#include `clang/AST/Expr.h`
#include `clang/AST/Type.h`
#include `clang/Basic/AddressSpaces.h`
#include `clang/Frontend/ASTUnit.h`
#include `clang/Basic/OpenCLImageTypes.def`
#include `clang/Basic/OpenCLExtensionTypes.def`
Macros
#define BTCASE(K) case BuiltinType::K: return CXType_##K
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) BTCASE(Id);
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext) BTCASE(Id);
#define TKCASE(K) case Type::K: return CXType_##K
#define TKIND(X) case CXType_##X: s = `` #X ``; break
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) TKIND(Id);
#define EXT_OPAQUE_TYPE(ExtTYpe, Id, Ext) TKIND(Id);
#define TCALLINGCONV(X) case CC_##X: return CXCallingConv_##X
Functions
CXType clang_getCursorType (CXCursor C)
CXString clang_getTypeSpelling (CXType CT)
CXType clang_getTypedefDeclUnderlyingType (CXCursor C)
CXType clang_getEnumDeclIntegerType (CXCursor C)
long long clang_getEnumConstantDeclValue (CXCursor C)
unsigned long long clang_getEnumConstantDeclUnsignedValue (CXCursor C)
int clang_getFieldDeclBitWidth (CXCursor C)
CXType clang_getCanonicalType (CXType CT)
unsigned clang_isConstQualifiedType (CXType CT)
unsigned clang_isVolatileQualifiedType (CXType CT)
unsigned clang_isRestrictQualifiedType (CXType CT)
unsigned clang_getAddressSpace (CXType CT)
CXString clang_getTypedefName (CXType CT)
CXType clang_getPointeeType (CXType CT)
CXCursor clang_getTypeDeclaration (CXType CT)
CXString clang_getTypeKindSpelling (enum CXTypeKind K)
unsigned clang_equalTypes (CXType A, CXType B)
unsigned clang_isFunctionTypeVariadic (CXType X)
CXCallingConv clang_getFunctionTypeCallingConv (CXType X)
int clang_getNumArgTypes (CXType X)
CXType clang_getArgType (CXType X, unsigned i)
CXType clang_getResultType (CXType X)
CXType clang_getCursorResultType (CXCursor C)
int clang_getExceptionSpecificationType (CXType X)
int clang_getCursorExceptionSpecificationType (CXCursor C)
unsigned clang_isPODType (CXType X)
CXType clang_getElementType (CXType CT)
long long clang_getNumElements (CXType CT)
CXType clang_getArrayElementType (CXType CT)
long long clang_getArraySize (CXType CT)
long long clang_Type_getAlignOf (CXType T)
CXType clang_Type_getClassType (CXType CT)
long long clang_Type_getSizeOf (CXType T)
long long clang_Type_getOffsetOf (CXType PT, const char *S)
CXType clang_Type_getModifiedType (CXType CT)
long long clang_Cursor_getOffsetOfField (CXCursor C)
enum CXRefQualifierKind clang_Type_getCXXRefQualifier (CXType T)
unsigned clang_Cursor_isBitField (CXCursor C)
CXString clang_getDeclObjCTypeEncoding (CXCursor C)
int clang_Type_getNumTemplateArguments (CXType CT)
CXType clang_Type_getTemplateArgumentAsType (CXType CT, unsigned index)
CXType clang_Type_getObjCObjectBaseType (CXType CT)
unsigned clang_Type_getNumObjCProtocolRefs (CXType CT)
CXCursor clang_Type_getObjCProtocolDecl (CXType CT, unsigned i)
unsigned clang_Type_getNumObjCTypeArgs (CXType CT)
CXType clang_Type_getObjCTypeArg (CXType CT, unsigned i)
unsigned clang_Type_visitFields (CXType PT, CXFieldVisitor visitor, CXClientData client_data)
unsigned clang_Cursor_isAnonymous (CXCursor C)
unsigned clang_Cursor_isAnonymousRecordDecl (CXCursor C)
unsigned clang_Cursor_isInlineNamespace (CXCursor C)
CXType clang_Type_getNamedType (CXType CT)
unsigned clang_Type_isTransparentTagTypedef (CXType TT)
enum CXTypeNullabilityKind clang_Type_getNullability (CXType CT)
CXType clang_Type_getValueType (CXType CT)
Macro Definition Documentation
BTCASE
#define BTCASE(K) case BuiltinType::K: return CXType_##K
EXT_OPAQUE_TYPE [1/2]
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext) BTCASE(Id);
EXT_OPAQUE_TYPE [2/2]
#define EXT_OPAQUE_TYPE(ExtTYpe, Id, Ext) TKIND(Id);
IMAGE_TYPE [1/2]
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) BTCASE(Id);
IMAGE_TYPE [2/2]
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) TKIND(Id);
TCALLINGCONV
#define TCALLINGCONV(X) case CC_##X: return CXCallingConv_##X
TKCASE
#define TKCASE(K) case Type::K: return CXType_##K
TKIND
#define TKIND(X) case CXType_##X: s = `` #X ``; break
Function Documentation
clang_Cursor_getOffsetOfField()
long long clang_Cursor_getOffsetOfField (CXCursor C)
Definition at line 1054 of file CXType.cpp.
                                                    {
  if (clang_isDeclaration(C.kind)) {
    // we need to validate the parent type
    CXCursor PC = clang_getCursorSemanticParent(C);
    CXType PT = clang_getCursorType(PC);
    long long Error = validateFieldParentType(PC,PT);
    if (Error < 0)
      return Error;
    // proceed with the offset calculation
    const Decl *D = cxcursor::getCursorDecl(C);
    ASTContext &Ctx = cxcursor::getCursorContext(C);
    if (const FieldDecl *FD = dyn_cast_or_null<FieldDecl>(D))
      return Ctx.getFieldOffset(FD);
    if (const IndirectFieldDecl *IFD = dyn_cast_or_null<IndirectFieldDecl>(D))
      return Ctx.getFieldOffset(IFD);
  }
  return -1;
}
References clang_getCursorSemanticParent(), clang_getCursorType(), and clang_isDeclaration().
clang_Cursor_isAnonymous()
unsigned clang_Cursor_isAnonymous (CXCursor C)
Definition at line 1256 of file CXType.cpp.
                                             {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  if (const NamespaceDecl *ND = dyn_cast_or_null<NamespaceDecl>(D)) {
    return ND->isAnonymousNamespace();
  } else if (const TagDecl *TD = dyn_cast_or_null<TagDecl>(D)) {
    return TD->getTypedefNameForAnonDecl() == nullptr &&
           TD->getIdentifier() == nullptr;
  }
  return 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_Cursor_isAnonymousRecordDecl()
unsigned clang_Cursor_isAnonymousRecordDecl (CXCursor C)
Definition at line 1270 of file CXType.cpp.
                                                       {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  if (const RecordDecl *FD = dyn_cast_or_null<RecordDecl>(D))
    return FD->isAnonymousStructOrUnion();
  return 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_Cursor_isBitField()
unsigned clang_Cursor_isBitField (CXCursor C)
Definition at line 1091 of file CXType.cpp.
                                             {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const FieldDecl *FD = dyn_cast_or_null<FieldDecl>(cxcursor::getCursorDecl(C));
  if (!FD)
    return 0;
  return FD->isBitField();
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_Cursor_isInlineNamespace()
unsigned clang_Cursor_isInlineNamespace (CXCursor C)
Definition at line 1279 of file CXType.cpp.
                                                    {
  if (!clang_isDeclaration(C.kind))
    return 0;
  const Decl *D = cxcursor::getCursorDecl(C);
  const NamespaceDecl *ND = dyn_cast_or_null<NamespaceDecl>(D);
  return ND ? ND->isInline() : 0;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_equalTypes()
unsigned clang_equalTypes (CXType A, CXType B)
Definition at line 627 of file CXType.cpp.
                                              {
  return A.data[0] == B.data[0] && A.data[1] == B.data[1];
}
clang_getAddressSpace()
unsigned clang_getAddressSpace (CXType CT)
Definition at line 419 of file CXType.cpp.
                                          {
  QualType T = GetQualType(CT);
  // For non language-specific address space, use separate helper function.
  if (T.getAddressSpace() >= LangAS::FirstTargetAddressSpace) {
    return T.getQualifiers().getAddressSpaceAttributePrintValue();
  }
  // FIXME: this function returns either a LangAS or a target AS
  // Those values can overlap which makes this function rather unpredictable
  // for any caller
  return (unsigned)T.getAddressSpace();
}
clang_getArgType()
CXType clang_getArgType (CXType X, unsigned i)
Definition at line 695 of file CXType.cpp.
                                              {
  QualType T = GetQualType(X);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(X));
  if (const FunctionProtoType *FD = T->getAs<FunctionProtoType>()) {
    unsigned numParams = FD->getNumParams();
    if (i >= numParams)
      return MakeCXType(QualType(), GetTU(X));
    return MakeCXType(FD->getParamType(i), GetTU(X));
  }
  
  return MakeCXType(QualType(), GetTU(X));
}
clang_getArrayElementType()
CXType clang_getArrayElementType (CXType CT)
Definition at line 850 of file CXType.cpp.
                                            {
  QualType ET = QualType();
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (TP) {
    switch (TP->getTypeClass()) {
    case Type::ConstantArray:
      ET = cast<ConstantArrayType> (TP)->getElementType();
      break;
    case Type::IncompleteArray:
      ET = cast<IncompleteArrayType> (TP)->getElementType();
      break;
    case Type::VariableArray:
      ET = cast<VariableArrayType> (TP)->getElementType();
      break;
    case Type::DependentSizedArray:
      ET = cast<DependentSizedArrayType> (TP)->getElementType();
      break;
    default:
      break;
    }
  }
  return MakeCXType(ET, GetTU(CT));
}
clang_getArraySize()
long long clang_getArraySize (CXType CT)
Definition at line 876 of file CXType.cpp.
                                        {
  long long result = -1;
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (TP) {
    switch (TP->getTypeClass()) {
    case Type::ConstantArray:
      result = cast<ConstantArrayType> (TP)->getSize().getSExtValue();
      break;
    default:
      break;
    }
  }
  return result;
}
clang_getCanonicalType()
CXType clang_getCanonicalType (CXType CT)
Definition at line 389 of file CXType.cpp.
                                         {
  if (CT.kind == CXType_Invalid)
    return CT;
  QualType T = GetQualType(CT);
  CXTranslationUnit TU = GetTU(CT);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(CT));
  return MakeCXType(cxtu::getASTUnit(TU)->getASTContext()
                        .getCanonicalType(T),
                    TU);
}
clang_getCursorExceptionSpecificationType()
int clang_getCursorExceptionSpecificationType (CXCursor C)
Definition at line 775 of file CXType.cpp.
                                                          {
  if (clang_isDeclaration(C.kind))
    return clang_getExceptionSpecificationType(clang_getCursorType(C));
  return -1;
}
References clang_getCursorType(), clang_getExceptionSpecificationType(), and clang_isDeclaration().
clang_getCursorResultType()
CXType clang_getCursorResultType (CXCursor C)
Definition at line 722 of file CXType.cpp.
                                             {
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const ObjCMethodDecl *MD = dyn_cast_or_null<ObjCMethodDecl>(D))
      return MakeCXType(MD->getReturnType(), cxcursor::getCursorTU(C));
    return clang_getResultType(clang_getCursorType(C));
  }
  return MakeCXType(QualType(), cxcursor::getCursorTU(C));
}
References clang_getCursorType(), clang_getResultType(), clang_isDeclaration(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), and clang::cxtype::MakeCXType().
clang_getCursorType()
CXType clang_getCursorType (CXCursor C)
Definition at line 216 of file CXType.cpp.
                                       {
  using namespace cxcursor;
  CXTranslationUnit TU = cxcursor::getCursorTU(C);
  if (!TU)
    return MakeCXType(QualType(), TU);
  ASTContext &Context = cxtu::getASTUnit(TU)->getASTContext();
  if (clang_isExpression(C.kind)) {
    QualType T = cxcursor::getCursorExpr(C)->getType();
    return MakeCXType(T, TU);
  }
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (!D)
      return MakeCXType(QualType(), TU);
    if (const TypeDecl *TD = dyn_cast<TypeDecl>(D))
      return MakeCXType(Context.getTypeDeclType(TD), TU);
    if (const ObjCInterfaceDecl *ID = dyn_cast<ObjCInterfaceDecl>(D))
      return MakeCXType(Context.getObjCInterfaceType(ID), TU);
    if (const DeclaratorDecl *DD = dyn_cast<DeclaratorDecl>(D))
      return MakeCXType(DD->getType(), TU);
    if (const ValueDecl *VD = dyn_cast<ValueDecl>(D))
      return MakeCXType(VD->getType(), TU);
    if (const ObjCPropertyDecl *PD = dyn_cast<ObjCPropertyDecl>(D))
      return MakeCXType(PD->getType(), TU);
    if (const FunctionTemplateDecl *FTD = dyn_cast<FunctionTemplateDecl>(D))
      return MakeCXType(FTD->getTemplatedDecl()->getType(), TU);
    return MakeCXType(QualType(), TU);
  }
  if (clang_isReference(C.kind)) {
    switch (C.kind) {
    case CXCursor_ObjCSuperClassRef: {
      QualType T
        = Context.getObjCInterfaceType(getCursorObjCSuperClassRef(C).first);
      return MakeCXType(T, TU);
    }
    case CXCursor_ObjCClassRef: {
      QualType T = Context.getObjCInterfaceType(getCursorObjCClassRef(C).first);
      return MakeCXType(T, TU);
    }
    case CXCursor_TypeRef: {
      QualType T = Context.getTypeDeclType(getCursorTypeRef(C).first);
      return MakeCXType(T, TU);
    }
    case CXCursor_CXXBaseSpecifier:
      return cxtype::MakeCXType(getCursorCXXBaseSpecifier(C)->getType(), TU);
    case CXCursor_MemberRef:
      return cxtype::MakeCXType(getCursorMemberRef(C).first->getType(), TU);
    case CXCursor_VariableRef:
      return cxtype::MakeCXType(getCursorVariableRef(C).first->getType(), TU);
    case CXCursor_ObjCProtocolRef:
    case CXCursor_TemplateRef:
    case CXCursor_NamespaceRef:
    case CXCursor_OverloadedDeclRef:
    default:
      break;
    }
    return MakeCXType(QualType(), TU);
  }
  return MakeCXType(QualType(), TU);
}
References clang_isDeclaration(), clang_isExpression(), clang_isReference(), clang::cxcursor::getCursorCXXBaseSpecifier(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorExpr(), clang::cxcursor::getCursorMemberRef(), clang::cxcursor::getCursorObjCClassRef(), clang::cxcursor::getCursorObjCSuperClassRef(), clang::cxcursor::getCursorTU(), clang::cxcursor::getCursorTypeRef(), clang::cxcursor::getCursorVariableRef(), and clang::cxtype::MakeCXType().
Referenced by clang_Cursor_getOffsetOfField(), clang_getCursorExceptionSpecificationType(), and clang_getCursorResultType().
clang_getDeclObjCTypeEncoding()
CXString clang_getDeclObjCTypeEncoding (CXCursor C)
Definition at line 1100 of file CXType.cpp.
                                                   {
  if (!clang_isDeclaration(C.kind))
    return cxstring::createEmpty();
  const Decl *D = cxcursor::getCursorDecl(C);
  ASTContext &Ctx = cxcursor::getCursorContext(C);
  std::string encoding;
  if (const ObjCMethodDecl *OMD = dyn_cast<ObjCMethodDecl>(D)) {
    encoding = Ctx.getObjCEncodingForMethodDecl(OMD);
  } else if (const ObjCPropertyDecl *OPD = dyn_cast<ObjCPropertyDecl>(D))
    encoding = Ctx.getObjCEncodingForPropertyDecl(OPD, nullptr);
  else if (const FunctionDecl *FD = dyn_cast<FunctionDecl>(D))
    encoding = Ctx.getObjCEncodingForFunctionDecl(FD);
  else {
    QualType Ty;
    if (const TypeDecl *TD = dyn_cast<TypeDecl>(D))
      Ty = Ctx.getTypeDeclType(TD);
    if (const ValueDecl *VD = dyn_cast<ValueDecl>(D))
      Ty = VD->getType();
    else return cxstring::createRef("?");
    Ctx.getObjCEncodingForType(Ty, encoding);
  }
  return cxstring::createDup(encoding);
}
References clang_isDeclaration(), clang::cxstring::createDup(), clang::cxstring::createEmpty(), clang::cxstring::createRef(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorDecl().
clang_getElementType()
CXType clang_getElementType (CXType CT)
Definition at line 792 of file CXType.cpp.
                                       {
  QualType ET = QualType();
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (TP) {
    switch (TP->getTypeClass()) {
    case Type::ConstantArray:
      ET = cast<ConstantArrayType> (TP)->getElementType();
      break;
    case Type::IncompleteArray:
      ET = cast<IncompleteArrayType> (TP)->getElementType();
      break;
    case Type::VariableArray:
      ET = cast<VariableArrayType> (TP)->getElementType();
      break;
    case Type::DependentSizedArray:
      ET = cast<DependentSizedArrayType> (TP)->getElementType();
      break;
    case Type::Vector:
      ET = cast<VectorType> (TP)->getElementType();
      break;
    case Type::ExtVector:
      ET = cast<ExtVectorType>(TP)->getElementType();
      break;
    case Type::Complex:
      ET = cast<ComplexType> (TP)->getElementType();
      break;
    default:
      break;
    }
  }
  return MakeCXType(ET, GetTU(CT));
}
clang_getEnumConstantDeclUnsignedValue()
unsigned long long clang_getEnumConstantDeclUnsignedValue (CXCursor C)
Definition at line 358 of file CXType.cpp.
                                                                      {
  using namespace cxcursor;
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const EnumConstantDecl *TD = dyn_cast_or_null<EnumConstantDecl>(D)) {
      return TD->getInitVal().getZExtValue();
    }
    return ULLONG_MAX;
  }
  return ULLONG_MAX;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_getEnumConstantDeclValue()
long long clang_getEnumConstantDeclValue (CXCursor C)
Definition at line 342 of file CXType.cpp.
                                                     {
  using namespace cxcursor;
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const EnumConstantDecl *TD = dyn_cast_or_null<EnumConstantDecl>(D)) {
      return TD->getInitVal().getSExtValue();
    }
    return LLONG_MIN;
  }
  return LLONG_MIN;
}
References clang_isDeclaration(), and clang::cxcursor::getCursorDecl().
clang_getEnumDeclIntegerType()
CXType clang_getEnumDeclIntegerType (CXCursor C)
Definition at line 324 of file CXType.cpp.
                                                {
  using namespace cxcursor;
  CXTranslationUnit TU = cxcursor::getCursorTU(C);
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const EnumDecl *TD = dyn_cast_or_null<EnumDecl>(D)) {
      QualType T = TD->getIntegerType();
      return MakeCXType(T, TU);
    }
    return MakeCXType(QualType(), TU);
  }
  return MakeCXType(QualType(), TU);
}
References clang_isDeclaration(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), and clang::cxtype::MakeCXType().
clang_getExceptionSpecificationType()
int clang_getExceptionSpecificationType (CXType X)
Definition at line 764 of file CXType.cpp.
                                                  {
  QualType T = GetQualType(X);
  if (T.isNull())
    return -1;
  if (const auto *FD = T->getAs<FunctionProtoType>())
    return getExternalExceptionSpecificationKind(FD->getExceptionSpecType());
  return -1;
}
Referenced by clang_getCursorExceptionSpecificationType().
clang_getFieldDeclBitWidth()
int clang_getFieldDeclBitWidth (CXCursor C)
Definition at line 374 of file CXType.cpp.
                                           {
  using namespace cxcursor;
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = getCursorDecl(C);
    if (const FieldDecl *FD = dyn_cast_or_null<FieldDecl>(D)) {
      if (FD->isBitField())
        return FD->getBitWidthValue(getCursorContext(C));
    }
  }
  return -1;
}
References clang_isDeclaration(), clang::cxcursor::getCursorContext(), and clang::cxcursor::getCursorDecl().
clang_getFunctionTypeCallingConv()
CXCallingConv clang_getFunctionTypeCallingConv (CXType X)
Definition at line 645 of file CXType.cpp.
                                                         {
  QualType T = GetQualType(X);
  if (T.isNull())
    return CXCallingConv_Invalid;
  
  if (const FunctionType *FD = T->getAs<FunctionType>()) {
#define TCALLINGCONV(X) case CC_##X: return CXCallingConv_##X
    switch (FD->getCallConv()) {
      TCALLINGCONV(C);
      TCALLINGCONV(X86StdCall);
      TCALLINGCONV(X86FastCall);
      TCALLINGCONV(X86ThisCall);
      TCALLINGCONV(X86Pascal);
      TCALLINGCONV(X86RegCall);
      TCALLINGCONV(X86VectorCall);
      TCALLINGCONV(AArch64VectorCall);
      TCALLINGCONV(Win64);
      TCALLINGCONV(X86_64SysV);
      TCALLINGCONV(AAPCS);
      TCALLINGCONV(AAPCS_VFP);
      TCALLINGCONV(IntelOclBicc);
      TCALLINGCONV(Swift);
      TCALLINGCONV(PreserveMost);
      TCALLINGCONV(PreserveAll);
    case CC_SpirFunction: return CXCallingConv_Unexposed;
    case CC_OpenCLKernel: return CXCallingConv_Unexposed;
      break;
    }
#undef TCALLINGCONV
  }
  
  return CXCallingConv_Invalid;
}
clang_getNumArgTypes()
int clang_getNumArgTypes (CXType X)
Definition at line 679 of file CXType.cpp.
                                   {
  QualType T = GetQualType(X);
  if (T.isNull())
    return -1;
  
  if (const FunctionProtoType *FD = T->getAs<FunctionProtoType>()) {
    return FD->getNumParams();
  }
  
  if (T->getAs<FunctionNoProtoType>()) {
    return 0;
  }
  
  return -1;
}
clang_getNumElements()
long long clang_getNumElements (CXType CT)
Definition at line 827 of file CXType.cpp.
                                          {
  long long result = -1;
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (TP) {
    switch (TP->getTypeClass()) {
    case Type::ConstantArray:
      result = cast<ConstantArrayType> (TP)->getSize().getSExtValue();
      break;
    case Type::Vector:
      result = cast<VectorType> (TP)->getNumElements();
      break;
    case Type::ExtVector:
      result = cast<ExtVectorType>(TP)->getNumElements();
      break;
    default:
      break;
    }
  }
  return result;
}
clang_getPointeeType()
CXType clang_getPointeeType (CXType CT)
Definition at line 443 of file CXType.cpp.
                                       {
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (!TP)
    return MakeCXType(QualType(), GetTU(CT));
try_again:
  switch (TP->getTypeClass()) {
    case Type::Pointer:
      T = cast<PointerType>(TP)->getPointeeType();
      break;
    case Type::BlockPointer:
      T = cast<BlockPointerType>(TP)->getPointeeType();
      break;
    case Type::LValueReference:
    case Type::RValueReference:
      T = cast<ReferenceType>(TP)->getPointeeType();
      break;
    case Type::ObjCObjectPointer:
      T = cast<ObjCObjectPointerType>(TP)->getPointeeType();
      break;
    case Type::MemberPointer:
      T = cast<MemberPointerType>(TP)->getPointeeType();
      break;
    case Type::Auto:
    case Type::DeducedTemplateSpecialization:
      TP = cast<DeducedType>(TP)->getDeducedType().getTypePtrOrNull();
      if (TP)
        goto try_again;
      break;
    default:
      T = QualType();
      break;
  }
  return MakeCXType(T, GetTU(CT));
}
clang_getResultType()
CXType clang_getResultType (CXType X)
Definition at line 711 of file CXType.cpp.
                                     {
  QualType T = GetQualType(X);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(X));
  
  if (const FunctionType *FD = T->getAs<FunctionType>())
    return MakeCXType(FD->getReturnType(), GetTU(X));
  return MakeCXType(QualType(), GetTU(X));
}
Referenced by clang_getCursorResultType().
clang_getTypeDeclaration()
CXCursor clang_getTypeDeclaration (CXType CT)
Definition at line 481 of file CXType.cpp.
                                             {
  if (CT.kind == CXType_Invalid)
    return cxcursor::MakeCXCursorInvalid(CXCursor_NoDeclFound);
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (!TP)
    return cxcursor::MakeCXCursorInvalid(CXCursor_NoDeclFound);
  Decl *D = nullptr;
try_again:
  switch (TP->getTypeClass()) {
  case Type::Typedef:
    D = cast<TypedefType>(TP)->getDecl();
    break;
  case Type::ObjCObject:
    D = cast<ObjCObjectType>(TP)->getInterface();
    break;
  case Type::ObjCInterface:
    D = cast<ObjCInterfaceType>(TP)->getDecl();
    break;
  case Type::Record:
  case Type::Enum:
    D = cast<TagType>(TP)->getDecl();
    break;
  case Type::TemplateSpecialization:
    if (const RecordType *Record = TP->getAs<RecordType>())
      D = Record->getDecl();
    else
      D = cast<TemplateSpecializationType>(TP)->getTemplateName()
                                                         .getAsTemplateDecl();
    break;
  case Type::Auto:
  case Type::DeducedTemplateSpecialization:
    TP = cast<DeducedType>(TP)->getDeducedType().getTypePtrOrNull();
    if (TP)
      goto try_again;
    break;
  case Type::InjectedClassName:
    D = cast<InjectedClassNameType>(TP)->getDecl();
    break;
  // FIXME: Template type parameters!
  case Type::Elaborated:
    TP = cast<ElaboratedType>(TP)->getNamedType().getTypePtrOrNull();
    goto try_again;
  default:
    break;
  }
  if (!D)
    return cxcursor::MakeCXCursorInvalid(CXCursor_NoDeclFound);
  return cxcursor::MakeCXCursor(D, GetTU(CT));
}
References clang::cxcursor::MakeCXCursorInvalid().
Referenced by clang_Type_getOffsetOf(), and clang_Type_visitFields().
clang_getTypedefDeclUnderlyingType()
CXType clang_getTypedefDeclUnderlyingType (CXCursor C)
Definition at line 306 of file CXType.cpp.
                                                      {
  using namespace cxcursor;
  CXTranslationUnit TU = cxcursor::getCursorTU(C);
  if (clang_isDeclaration(C.kind)) {
    const Decl *D = cxcursor::getCursorDecl(C);
    if (const TypedefNameDecl *TD = dyn_cast_or_null<TypedefNameDecl>(D)) {
      QualType T = TD->getUnderlyingType();
      return MakeCXType(T, TU);
    }
    return MakeCXType(QualType(), TU);
  }
  return MakeCXType(QualType(), TU);
}
References clang_isDeclaration(), clang::cxcursor::getCursorDecl(), clang::cxcursor::getCursorTU(), and clang::cxtype::MakeCXType().
clang_getTypedefName()
CXString clang_getTypedefName (CXType CT)
Definition at line 432 of file CXType.cpp.
                                         {
  QualType T = GetQualType(CT);
  const TypedefType *TT = T->getAs<TypedefType>();
  if (TT) {
    TypedefNameDecl *TD = TT->getDecl();
    if (TD)
      return cxstring::createDup(TD->getNameAsString().c_str());
  }
  return cxstring::createEmpty();
}
clang_getTypeKindSpelling()
CXString clang_getTypeKindSpelling (enum CXTypeKind K)
Definition at line 543 of file CXType.cpp.
                                                      {
  const char *s = nullptr;
#define TKIND(X) case CXType_##X: s = "" #X ""; break
  switch (K) {
    TKIND(Invalid);
    TKIND(Unexposed);
    TKIND(Void);
    TKIND(Bool);
    TKIND(Char_U);
    TKIND(UChar);
    TKIND(Char16);
    TKIND(Char32);
    TKIND(UShort);
    TKIND(UInt);
    TKIND(ULong);
    TKIND(ULongLong);
    TKIND(UInt128);
    TKIND(Char_S);
    TKIND(SChar);
    case CXType_WChar: s = "WChar"; break;
    TKIND(Short);
    TKIND(Int);
    TKIND(Long);
    TKIND(LongLong);
    TKIND(Int128);
    TKIND(Half);
    TKIND(Float);
    TKIND(Double);
    TKIND(LongDouble);
    TKIND(ShortAccum);
    TKIND(Accum);
    TKIND(LongAccum);
    TKIND(UShortAccum);
    TKIND(UAccum);
    TKIND(ULongAccum);
    TKIND(Float16);
    TKIND(Float128);
    TKIND(NullPtr);
    TKIND(Overload);
    TKIND(Dependent);
    TKIND(ObjCId);
    TKIND(ObjCClass);
    TKIND(ObjCSel);
    TKIND(Complex);
    TKIND(Pointer);
    TKIND(BlockPointer);
    TKIND(LValueReference);
    TKIND(RValueReference);
    TKIND(Record);
    TKIND(Enum);
    TKIND(Typedef);
    TKIND(ObjCInterface);
    TKIND(ObjCObject);
    TKIND(ObjCObjectPointer);
    TKIND(ObjCTypeParam);
    TKIND(FunctionNoProto);
    TKIND(FunctionProto);
    TKIND(ConstantArray);
    TKIND(IncompleteArray);
    TKIND(VariableArray);
    TKIND(DependentSizedArray);
    TKIND(Vector);
    TKIND(ExtVector);
    TKIND(MemberPointer);
    TKIND(Auto);
    TKIND(Elaborated);
    TKIND(Pipe);
    TKIND(Attributed);
    TKIND(BFloat16);
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) TKIND(Id);
#include "clang/Basic/OpenCLImageTypes.def"
#undef IMAGE_TYPE
#define EXT_OPAQUE_TYPE(ExtTYpe, Id, Ext) TKIND(Id);
#include "clang/Basic/OpenCLExtensionTypes.def"
    TKIND(OCLSampler);
    TKIND(OCLEvent);
    TKIND(OCLQueue);
    TKIND(OCLReserveID);
    TKIND(Atomic);
  }
#undef TKIND
  return cxstring::createRef(s);
}
References clang::cxstring::createRef(), and TKIND.
clang_getTypeSpelling()
CXString clang_getTypeSpelling (CXType CT)
Definition at line 291 of file CXType.cpp.
                                          {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return cxstring::createEmpty();
  CXTranslationUnit TU = GetTU(CT);
  SmallString<64> Str;
  llvm::raw_svector_ostream OS(Str);
  PrintingPolicy PP(cxtu::getASTUnit(TU)->getASTContext().getLangOpts());
  T.print(OS, PP);
  return cxstring::createDup(OS.str());
}
clang_isConstQualifiedType()
unsigned clang_isConstQualifiedType (CXType CT)
Definition at line 404 of file CXType.cpp.
                                               {
  QualType T = GetQualType(CT);
  return T.isLocalConstQualified();
}
clang_isFunctionTypeVariadic()
unsigned clang_isFunctionTypeVariadic (CXType X)
Definition at line 631 of file CXType.cpp.
                                                {
  QualType T = GetQualType(X);
  if (T.isNull())
    return 0;
  if (const FunctionProtoType *FD = T->getAs<FunctionProtoType>())
    return (unsigned)FD->isVariadic();
  if (T->getAs<FunctionNoProtoType>())
    return 1;
  
  return 0;
}
clang_isPODType()
unsigned clang_isPODType (CXType X)
Definition at line 782 of file CXType.cpp.
                                   {
  QualType T = GetQualType(X);
  if (T.isNull())
    return 0;
  
  CXTranslationUnit TU = GetTU(X);
  return T.isPODType(cxtu::getASTUnit(TU)->getASTContext()) ? 1 : 0;
}
clang_isRestrictQualifiedType()
unsigned clang_isRestrictQualifiedType (CXType CT)
Definition at line 414 of file CXType.cpp.
                                                  {
  QualType T = GetQualType(CT);
  return T.isLocalRestrictQualified();
}
clang_isVolatileQualifiedType()
unsigned clang_isVolatileQualifiedType (CXType CT)
Definition at line 409 of file CXType.cpp.
                                                  {
  QualType T = GetQualType(CT);
  return T.isLocalVolatileQualified();
}
clang_Type_getAlignOf()
long long clang_Type_getAlignOf (CXType T)
Definition at line 897 of file CXType.cpp.
                                          {
  if (T.kind == CXType_Invalid)
    return CXTypeLayoutError_Invalid;
  ASTContext &Ctx = cxtu::getASTUnit(GetTU(T))->getASTContext();
  QualType QT = GetQualType(T);
  // [expr.alignof] p1: return size_t value for complete object type, reference
  // or array.
  // [expr.alignof] p3: if reference type, return size of referenced type
  if (QT->isReferenceType())
    QT = QT.getNonReferenceType();
  if (!isIncompleteTypeWithAlignment(QT))
    return CXTypeLayoutError_Incomplete;
  if (QT->isDependentType())
    return CXTypeLayoutError_Dependent;
  if (const auto *Deduced = dyn_cast<DeducedType>(QT))
    if (Deduced->getDeducedType().isNull())
      return CXTypeLayoutError_Undeduced;
  // Exceptions by GCC extension - see ASTContext.cpp:1313 getTypeInfoImpl
  // if (QT->isFunctionType()) return 4; // Bug #15511 - should be 1
  // if (QT->isVoidType()) return 1;
  return Ctx.getTypeAlignInChars(QT).getQuantity();
}
clang_Type_getClassType()
CXType clang_Type_getClassType (CXType CT)
Definition at line 920 of file CXType.cpp.
                                          {
  QualType ET = QualType();
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (TP && TP->getTypeClass() == Type::MemberPointer) {
    ET = QualType(cast<MemberPointerType> (TP)->getClass(), 0);
  }
  return MakeCXType(ET, GetTU(CT));
}
clang_Type_getCXXRefQualifier()
enum CXRefQualifierKind clang_Type_getCXXRefQualifier (CXType T)
Definition at line 1054 of file CXType.cpp.
                                                                {
  QualType QT = GetQualType(T);
  if (QT.isNull())
    return CXRefQualifier_None;
  const FunctionProtoType *FD = QT->getAs<FunctionProtoType>();
  if (!FD)
    return CXRefQualifier_None;
  switch (FD->getRefQualifier()) {
    case RQ_None:
      return CXRefQualifier_None;
    case RQ_LValue:
      return CXRefQualifier_LValue;
    case RQ_RValue:
      return CXRefQualifier_RValue;
  }
  return CXRefQualifier_None;
}
clang_Type_getModifiedType()
CXType clang_Type_getModifiedType (CXType CT)
Definition at line 1043 of file CXType.cpp.
                                             {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(CT));
  if (auto *ATT = T->getAs<AttributedType>())
    return MakeCXType(ATT->getModifiedType(), GetTU(CT));
  return MakeCXType(QualType(), GetTU(CT));
}
clang_Type_getNamedType()
CXType clang_Type_getNamedType (CXType CT)
Definition at line 1287 of file CXType.cpp.
                                         {
  QualType T = GetQualType(CT);
  const Type *TP = T.getTypePtrOrNull();
  if (TP && TP->getTypeClass() == Type::Elaborated)
    return MakeCXType(cast<ElaboratedType>(TP)->getNamedType(), GetTU(CT));
  return MakeCXType(QualType(), GetTU(CT));
}
clang_Type_getNullability()
enum CXTypeNullabilityKind clang_Type_getNullability (CXType CT)
Definition at line 1297 of file CXType.cpp.
                                                                {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return CXTypeNullability_Invalid;
  ASTContext &Ctx = cxtu::getASTUnit(GetTU(CT))->getASTContext();
  if (auto nullability = T->getNullability(Ctx)) {
    switch (*nullability) {
      case NullabilityKind::NonNull:
        return CXTypeNullability_NonNull;
      case NullabilityKind::Nullable:
        return CXTypeNullability_Nullable;
      case NullabilityKind::NullableResult:
        return CXTypeNullability_NullableResult;
      case NullabilityKind::Unspecified:
        return CXTypeNullability_Unspecified;
    }
  }
  return CXTypeNullability_Invalid;
}
clang_Type_getNumObjCProtocolRefs()
unsigned clang_Type_getNumObjCProtocolRefs (CXType CT)
Definition at line 1172 of file CXType.cpp.
                                                      {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return 0;
  const ObjCObjectType *OT = dyn_cast<ObjCObjectType>(T);
  if (!OT)
    return 0;
  return OT->getNumProtocols();
}
clang_Type_getNumObjCTypeArgs()
unsigned clang_Type_getNumObjCTypeArgs (CXType CT)
Definition at line 1200 of file CXType.cpp.
                                                  {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return 0;
  const ObjCObjectType *OT = dyn_cast<ObjCObjectType>(T);
  if (!OT)
    return 0;
  return OT->getTypeArgs().size();
}
clang_Type_getNumTemplateArguments()
int clang_Type_getNumTemplateArguments (CXType CT)
Definition at line 1135 of file CXType.cpp.
                                                  {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return -1;
  auto TA = GetTemplateArguments(T);
  if (!TA)
    return -1;
  return GetTemplateArgumentArraySize(TA.getValue());
}
clang_Type_getObjCObjectBaseType()
CXType clang_Type_getObjCObjectBaseType (CXType CT)
Definition at line 1160 of file CXType.cpp.
                                                   {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(CT));
  const ObjCObjectType *OT = dyn_cast<ObjCObjectType>(T);
  if (!OT)
    return MakeCXType(QualType(), GetTU(CT));
  return MakeCXType(OT->getBaseType(), GetTU(CT));
}
clang_Type_getObjCProtocolDecl()
CXCursor clang_Type_getObjCProtocolDecl (CXType CT, unsigned i)
Definition at line 1184 of file CXType.cpp.
                                                               {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return cxcursor::MakeCXCursorInvalid(CXCursor_NoDeclFound);
  const ObjCObjectType *OT = dyn_cast<ObjCObjectType>(T);
  if (!OT)
    return cxcursor::MakeCXCursorInvalid(CXCursor_NoDeclFound);
  const ObjCProtocolDecl *PD = OT->getProtocol(i);
  if (!PD)
    return cxcursor::MakeCXCursorInvalid(CXCursor_NoDeclFound);
  return cxcursor::MakeCXCursor(PD, GetTU(CT));
}
clang_Type_getObjCTypeArg()
CXType clang_Type_getObjCTypeArg (CXType CT, unsigned i)
Definition at line 1212 of file CXType.cpp.
                                                        {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(CT));
  const ObjCObjectType *OT = dyn_cast<ObjCObjectType>(T);
  if (!OT)
    return MakeCXType(QualType(), GetTU(CT));
  const ArrayRef<QualType> TA = OT->getTypeArgs();
  if ((size_t)i >= TA.size())
    return MakeCXType(QualType(), GetTU(CT));
  return MakeCXType(TA[i], GetTU(CT));
}
clang_Type_getOffsetOf()
long long clang_Type_getOffsetOf (CXType PT, const char * S)
Definition at line 1012 of file CXType.cpp.
                                                           {
  // check that PT is not incomplete/dependent
  CXCursor PC = clang_getTypeDeclaration(PT);
  long long Error = validateFieldParentType(PC,PT);
  if (Error < 0)
    return Error;
  if (!S)
    return CXTypeLayoutError_InvalidFieldName;
  // lookup field
  ASTContext &Ctx = cxtu::getASTUnit(GetTU(PT))->getASTContext();
  IdentifierInfo *II = &Ctx.Idents.get(S);
  DeclarationName FieldName(II);
  const RecordDecl *RD =
        dyn_cast_or_null<RecordDecl>(cxcursor::getCursorDecl(PC));
  // verified in validateFieldParentType
  RD = RD->getDefinition();
  RecordDecl::lookup_result Res = RD->lookup(FieldName);
  // If a field of the parent record is incomplete, lookup will fail.
  // and we would return InvalidFieldName instead of Incomplete.
  // But this erroneous results does protects again a hidden assertion failure
  // in the RecordLayoutBuilder
  if (!Res.isSingleResult())
    return CXTypeLayoutError_InvalidFieldName;
  if (const FieldDecl *FD = dyn_cast<FieldDecl>(Res.front()))
    return Ctx.getFieldOffset(FD);
  if (const IndirectFieldDecl *IFD = dyn_cast<IndirectFieldDecl>(Res.front()))
    return Ctx.getFieldOffset(IFD);
  // we don't want any other Decl Type.
  return CXTypeLayoutError_InvalidFieldName;
}
References clang_getTypeDeclaration().
clang_Type_getSizeOf()
long long clang_Type_getSizeOf (CXType T)
Definition at line 931 of file CXType.cpp.
                                         {
  if (T.kind == CXType_Invalid)
    return CXTypeLayoutError_Invalid;
  ASTContext &Ctx = cxtu::getASTUnit(GetTU(T))->getASTContext();
  QualType QT = GetQualType(T);
  // [expr.sizeof] p2: if reference type, return size of referenced type
  if (QT->isReferenceType())
    QT = QT.getNonReferenceType();
  // [expr.sizeof] p1: return -1 on: func, incomplete, bitfield, incomplete
  // enumeration
  // Note: We get the cxtype, not the cxcursor, so we can't call
  // FieldDecl->isBitField()
  // [expr.sizeof] p3: pointer ok, function not ok.
  // [gcc extension] lib/AST/ExprConstant.cpp:1372 HandleSizeof : vla == error
  if (QT->isIncompleteType())
    return CXTypeLayoutError_Incomplete;
  if (QT->isDependentType())
    return CXTypeLayoutError_Dependent;
  if (!QT->isConstantSizeType())
    return CXTypeLayoutError_NotConstantSize;
  if (const auto *Deduced = dyn_cast<DeducedType>(QT))
    if (Deduced->getDeducedType().isNull())
      return CXTypeLayoutError_Undeduced;
  // [gcc extension] lib/AST/ExprConstant.cpp:1372
  // HandleSizeof : {voidtype,functype} == 1
  // not handled by ASTContext.cpp:1313 getTypeInfoImpl
  if (QT->isVoidType() || QT->isFunctionType())
    return 1;
  return Ctx.getTypeSizeInChars(QT).getQuantity();
}
clang_Type_getTemplateArgumentAsType()
CXType clang_Type_getTemplateArgumentAsType (CXType CT, unsigned index)
Definition at line 1147 of file CXType.cpp.
                                                                       {
  QualType T = GetQualType(CT);
  if (T.isNull())
    return MakeCXType(QualType(), GetTU(CT));
  auto TA = GetTemplateArguments(T);
  if (!TA)
    return MakeCXType(QualType(), GetTU(CT));
  Optional<QualType> QT = FindTemplateArgumentTypeAt(TA.getValue(), index);
  return MakeCXType(QT.getValueOr(QualType()), GetTU(CT));
}
clang_Type_getValueType()
CXType clang_Type_getValueType (CXType CT)
Definition at line 1327 of file CXType.cpp.
                                          {
  QualType T = GetQualType(CT);
  if (T.isNull() || !T->isAtomicType())
      return MakeCXType(QualType(), GetTU(CT));
  const auto *AT = T->castAs<AtomicType>();
  return MakeCXType(AT->getValueType(), GetTU(CT));
}
clang_Type_isTransparentTagTypedef()
unsigned clang_Type_isTransparentTagTypedef (CXType TT)
Definition at line 1297 of file CXType.cpp.
                                                      {
  QualType T = GetQualType(TT);
  if (auto *TT = dyn_cast_or_null<TypedefType>(T.getTypePtrOrNull())) {
    if (auto *D = TT->getDecl())
      return D->isTransparentTag();
  }
  return false;
}
clang_Type_visitFields()
unsigned clang_Type_visitFields (CXType PT, CXFieldVisitor visitor, CXClientData client_data)
Definition at line 1228 of file CXType.cpp.
                                                         {
  CXCursor PC = clang_getTypeDeclaration(PT);
  if (clang_isInvalid(PC.kind))
    return false;
  const RecordDecl *RD =
        dyn_cast_or_null<RecordDecl>(cxcursor::getCursorDecl(PC));
  if (!RD || RD->isInvalidDecl())
    return false;
  RD = RD->getDefinition();
  if (!RD || RD->isInvalidDecl())
    return false;
  for (RecordDecl::field_iterator I = RD->field_begin(), E = RD->field_end();
       I != E; ++I){
    const FieldDecl *FD = dyn_cast_or_null<FieldDecl>((*I));
    // Callback to the client.
    switch (visitor(cxcursor::MakeCXCursor(FD, GetTU(PT)), client_data)){
    case CXVisit_Break:
      return true;
    case CXVisit_Continue:
      break;
    }
  }
  return true;
}
References clang_getTypeDeclaration(), clang_isInvalid(), clang::cxcursor::getCursorDecl(), and clang::cxcursor::MakeCXCursor().