/Users/maximilian/clang-llvm/clang/tools/libclang/CXCompilationDatabase.cpp File Reference
#include `clang-c/CXCompilationDatabase.h`
#include `CXString.h`
#include `clang/Tooling/CompilationDatabase.h`
#include <cstdio>
Classes
struct AllocatedCXCompileCommands
Functions
CXCompilationDatabase clang_CompilationDatabase_fromDirectory (const char *BuildDir, CXCompilationDatabase_Error *ErrorCode)
void clang_CompilationDatabase_dispose (CXCompilationDatabase CDb)
CXCompileCommands clang_CompilationDatabase_getCompileCommands (CXCompilationDatabase CDb, const char *CompleteFileName)
CXCompileCommands clang_CompilationDatabase_getAllCompileCommands (CXCompilationDatabase CDb)
void clang_CompileCommands_dispose (CXCompileCommands Cmds)
unsigned clang_CompileCommands_getSize (CXCompileCommands Cmds)
CXCompileCommand clang_CompileCommands_getCommand (CXCompileCommands Cmds, unsigned I)
CXString clang_CompileCommand_getDirectory (CXCompileCommand CCmd)
CXString clang_CompileCommand_getFilename (CXCompileCommand CCmd)
unsigned clang_CompileCommand_getNumArgs (CXCompileCommand CCmd)
CXString clang_CompileCommand_getArg (CXCompileCommand CCmd, unsigned Arg)
unsigned clang_CompileCommand_getNumMappedSources (CXCompileCommand CCmd)
CXString clang_CompileCommand_getMappedSourcePath (CXCompileCommand CCmd, unsigned I)
CXString clang_CompileCommand_getMappedSourceContent (CXCompileCommand CCmd, unsigned I)
Function Documentation
clang_CompilationDatabase_dispose()
void clang_CompilationDatabase_dispose (CXCompilationDatabase CDb)
Definition at line 32 of file CXCompilationDatabase.cpp.
{
  delete static_cast<CompilationDatabase *>(CDb);
}
clang_CompilationDatabase_fromDirectory()
CXCompilationDatabase clang_CompilationDatabase_fromDirectory (const char * BuildDir, CXCompilationDatabase_Error * ErrorCode)
Definition at line 11 of file CXCompilationDatabase.cpp.
{
  std::string ErrorMsg;
  CXCompilationDatabase_Error Err = CXCompilationDatabase_NoError;
  std::unique_ptr<CompilationDatabase> db =
      CompilationDatabase::loadFromDirectory(BuildDir, ErrorMsg);
  if (!db) {
    fprintf(stderr, "LIBCLANG TOOLING ERROR: %s\n", ErrorMsg.c_str());
    Err = CXCompilationDatabase_CanNotLoadDatabase;
  }
  if (ErrorCode)
    *ErrorCode = Err;
  return db.release();
}
clang_CompilationDatabase_getAllCompileCommands()
CXCompileCommands clang_CompilationDatabase_getAllCompileCommands (CXCompilationDatabase CDb)
Definition at line 59 of file CXCompilationDatabase.cpp.
                                                                           {
  if (CompilationDatabase *db = static_cast<CompilationDatabase *>(CDb)) {
    std::vector<CompileCommand> CCmd(db->getAllCompileCommands());
    if (!CCmd.empty())
      return new AllocatedCXCompileCommands(std::move(CCmd));
  }
  return nullptr;
}
clang_CompilationDatabase_getCompileCommands()
CXCompileCommands clang_CompilationDatabase_getCompileCommands (CXCompilationDatabase CDb, const char * CompleteFileName)
Definition at line 46 of file CXCompilationDatabase.cpp.
{
  if (CompilationDatabase *db = static_cast<CompilationDatabase *>(CDb)) {
    std::vector<CompileCommand> CCmd(db->getCompileCommands(CompleteFileName));
    if (!CCmd.empty())
      return new AllocatedCXCompileCommands(std::move(CCmd));
  }
  return nullptr;
}
clang_CompileCommand_getArg()
CXString clang_CompileCommand_getArg (CXCompileCommand CCmd, unsigned Arg)
Definition at line 132 of file CXCompilationDatabase.cpp.
{
  if (!CCmd)
    return cxstring::createNull();
  CompileCommand *Cmd = static_cast<CompileCommand *>(CCmd);
  if (Arg >= Cmd->CommandLine.size())
    return cxstring::createNull();
  return cxstring::createRef(Cmd->CommandLine[Arg].c_str());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_CompileCommand_getDirectory()
CXString clang_CompileCommand_getDirectory (CXCompileCommand CCmd)
Definition at line 103 of file CXCompilationDatabase.cpp.
{
  if (!CCmd)
    return cxstring::createNull();
  CompileCommand *cmd = static_cast<CompileCommand *>(CCmd);
  return cxstring::createRef(cmd->Directory.c_str());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_CompileCommand_getFilename()
CXString clang_CompileCommand_getFilename (CXCompileCommand CCmd)
Definition at line 113 of file CXCompilationDatabase.cpp.
{
  if (!CCmd)
    return cxstring::createNull();
  CompileCommand *cmd = static_cast<CompileCommand *>(CCmd);
  return cxstring::createRef(cmd->Filename.c_str());
}
References clang::cxstring::createNull(), and clang::cxstring::createRef().
clang_CompileCommand_getMappedSourceContent()
CXString clang_CompileCommand_getMappedSourceContent (CXCompileCommand CCmd, unsigned I)
Definition at line 162 of file CXCompilationDatabase.cpp.
{
  // Left here for backward compatibility. No mapped sources exists in the C++
  // backend anymore.
  return cxstring::createNull();
}
References clang::cxstring::createNull().
clang_CompileCommand_getMappedSourcePath()
CXString clang_CompileCommand_getMappedSourcePath (CXCompileCommand CCmd, unsigned I)
Definition at line 154 of file CXCompilationDatabase.cpp.
{
  // Left here for backward compatibility. No mapped sources exists in the C++
  // backend anymore.
  return cxstring::createNull();
}
References clang::cxstring::createNull().
clang_CompileCommand_getNumArgs()
unsigned clang_CompileCommand_getNumArgs (CXCompileCommand CCmd)
Definition at line 123 of file CXCompilationDatabase.cpp.
{
  if (!CCmd)
    return 0;
  return static_cast<CompileCommand *>(CCmd)->CommandLine.size();
}
clang_CompileCommand_getNumMappedSources()
unsigned clang_CompileCommand_getNumMappedSources (CXCompileCommand CCmd)
Definition at line 146 of file CXCompilationDatabase.cpp.
{
  // Left here for backward compatibility. No mapped sources exists in the C++
  // backend anymore.
  return 0;
}
clang_CompileCommands_dispose()
void clang_CompileCommands_dispose (CXCompileCommands Cmds)
Definition at line 70 of file CXCompilationDatabase.cpp.
{
  delete static_cast<AllocatedCXCompileCommands *>(Cmds);
}
clang_CompileCommands_getCommand()
CXCompileCommand clang_CompileCommands_getCommand (CXCompileCommands Cmds, unsigned I)
Definition at line 88 of file CXCompilationDatabase.cpp.
{
  if (!Cmds)
    return nullptr;
  AllocatedCXCompileCommands *ACC =
    static_cast<AllocatedCXCompileCommands *>(Cmds);
  if (I >= ACC->CCmd.size())
    return nullptr;
  return &ACC->CCmd[I];
}
References AllocatedCXCompileCommands::CCmd.
clang_CompileCommands_getSize()
unsigned clang_CompileCommands_getSize (CXCompileCommands Cmds)
Definition at line 76 of file CXCompilationDatabase.cpp.
{
  if (!Cmds)
    return 0;
  AllocatedCXCompileCommands *ACC =
    static_cast<AllocatedCXCompileCommands *>(Cmds);
  return ACC->CCmd.size();
}
References AllocatedCXCompileCommands::CCmd.