/Users/maximilian/clang-llvm/clang/tools/libclang/CXString.cpp File Reference
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `clang-c/Index.h`
#include `clang/Frontend/ASTUnit.h`
#include `llvm/Support/ErrorHandling.h`
Namespaces
 clang
-rename
 clang::cxstring
Enumerations
enum CXStringFlag { CXS_Unmanaged
, CXS_Malloc
, CXS_StringBuf
 }
Describes the kind of underlying data in CXString.
Functions
CXString clang::cxstring::createEmpty ()
Create a CXString object for an empty `` string.
CXString clang::cxstring::createNull ()
CXString clang::cxstring::createRef (const char *String)
CXString clang::cxstring::createDup (const char *String)
CXString clang::cxstring::createRef (StringRef String)
CXString clang::cxstring::createDup (StringRef String)
CXString clang::cxstring::createCXString (CXStringBuf *buf)
Create a CXString object that is backed by a string buffer.
CXStringSet * clang::cxstring::createSet (const std::vector< std::string > &Strings)
CXStringBuf * clang::cxstring::getCXStringBuf (CXTranslationUnit TU)
bool clang::cxstring::isManagedByPool (CXString str)
Returns true if the CXString data is managed by a pool.
const char * clang_getCString (CXString string)
void clang_disposeString (CXString string)
void clang_disposeStringSet (CXStringSet *set)
Enumeration Type Documentation
CXStringFlag
enum CXStringFlag
Describes the kind of underlying data in CXString.
Enumerator
CXS_Unmanaged CXString contains a 'const char *' that it doesn't own.
CXS_Malloc CXString contains a 'const char *' that it allocated with malloc().
CXS_StringBuf CXString contains a CXStringBuf that needs to be returned to the CXStringPool.
Definition at line 24 of file CXString.cpp.
                  {
  CXS_Unmanaged,
  CXS_Malloc,
  CXS_StringBuf
};
Function Documentation
clang_disposeString()
void clang_disposeString (CXString string)
Definition at line 170 of file CXString.cpp.
                                          {
  switch ((CXStringFlag) string.private_flags) {
    case CXS_Unmanaged:
      break;
    case CXS_Malloc:
      if (string.data)
        free(const_cast<void *>(string.data));
      break;
    case CXS_StringBuf:
      static_cast<cxstring::CXStringBuf *>(
          const_cast<void *>(string.data))->dispose();
      break;
  }
}
References CXS_Malloc, CXS_StringBuf, CXS_Unmanaged, and clang::cxstring::CXStringBuf::dispose().
Referenced by clang_disposeCXPlatformAvailability(), clang_disposeStringSet(), InclusionVisitor(), clang::cxindex::Logger::operator<<(), PrintDiagnostic(), and clang::cxindex::printDiagsToStderr().
clang_disposeStringSet()
void clang_disposeStringSet (CXStringSet * set)
Definition at line 185 of file CXString.cpp.
                                              {
  for (unsigned SI = 0, SE = set->Count; SI < SE; ++SI)
    clang_disposeString(set->Strings[SI]);
  delete[] set->Strings;
  delete set;
}
References clang_disposeString().
clang_getCString()
const char* clang_getCString (CXString string)
Definition at line 163 of file CXString.cpp.
                                              {
  if (string.private_flags == (unsigned) CXS_StringBuf) {
    return static_cast<const cxstring::CXStringBuf *>(string.data)->Data.data();
  }
  return static_cast<const char *>(string.data);
}
References CXS_StringBuf.
Referenced by InclusionVisitor(), clang::cxindex::Logger::operator<<(), PrintDiagnostic(), and clang::cxindex::printDiagsToStderr().