/Users/maximilian/clang-llvm/clang/tools/libclang/CXSourceLocation.cpp File Reference
#include `CXSourceLocation.h`
#include `CIndexer.h`
#include `CLog.h`
#include `CXLoadedDiagnostic.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `clang/Basic/FileManager.h`
#include `clang/Frontend/ASTUnit.h`
#include `llvm/Support/Compiler.h`
#include `llvm/Support/Format.h`
Functions
CXSourceLocation clang_getNullLocation ()
unsigned clang_equalLocations (CXSourceLocation loc1, CXSourceLocation loc2)
CXSourceRange clang_getNullRange ()
CXSourceRange clang_getRange (CXSourceLocation begin, CXSourceLocation end)
unsigned clang_equalRanges (CXSourceRange range1, CXSourceRange range2)
int clang_Range_isNull (CXSourceRange range)
CXSourceLocation clang_getRangeStart (CXSourceRange range)
CXSourceLocation clang_getRangeEnd (CXSourceRange range)
CXSourceLocation clang_getLocation (CXTranslationUnit TU, CXFile file, unsigned line, unsigned column)
CXSourceLocation clang_getLocationForOffset (CXTranslationUnit TU, CXFile file, unsigned offset)
int clang_Location_isInSystemHeader (CXSourceLocation location)
int clang_Location_isFromMainFile (CXSourceLocation location)
void clang_getExpansionLocation (CXSourceLocation location, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
void clang_getPresumedLocation (CXSourceLocation location, CXString *filename, unsigned *line, unsigned *column)
void clang_getInstantiationLocation (CXSourceLocation location, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
void clang_getSpellingLocation (CXSourceLocation location, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
void clang_getFileLocation (CXSourceLocation location, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
Function Documentation
clang_equalLocations()
unsigned clang_equalLocations (CXSourceLocation loc1, CXSourceLocation loc2)
Definition at line 46 of file CXSourceLocation.cpp.
                                                                            {
  return (loc1.ptr_data[0] == loc2.ptr_data[0] &&
          loc1.ptr_data[1] == loc2.ptr_data[1] &&
          loc1.int_data == loc2.int_data);
}
Referenced by PrintDiagnostic().
clang_equalRanges()
unsigned clang_equalRanges (CXSourceRange range1, CXSourceRange range2)
Definition at line 75 of file CXSourceLocation.cpp.
                                                                       {
  return range1.ptr_data[0] == range2.ptr_data[0]
    && range1.ptr_data[1] == range2.ptr_data[1]
    && range1.begin_int_data == range2.begin_int_data
    && range1.end_int_data == range2.end_int_data;
}
Referenced by clang_Range_isNull().
clang_getExpansionLocation()
void clang_getExpansionLocation (CXSourceLocation location, CXFile * file, unsigned * line, unsigned * column, unsigned * offset)
Definition at line 222 of file CXSourceLocation.cpp.
                                                  {
  if (!isASTUnitSourceLocation(location)) {
    CXLoadedDiagnostic::decodeLocation(location, file, line, column, offset);
    return;
  }
  SourceLocation Loc = SourceLocation::getFromRawEncoding(location.int_data);
  if (!location.ptr_data[0] || Loc.isInvalid()) {
    createNullLocation(file, line, column, offset);
    return;
  }
  const SourceManager &SM =
  *static_cast<const SourceManager*>(location.ptr_data[0]);
  SourceLocation ExpansionLoc = SM.getExpansionLoc(Loc);
  
  // Check that the FileID is invalid on the expansion location.
  // This can manifest in invalid code.
  FileID fileID = SM.getFileID(ExpansionLoc);
  bool Invalid = false;
  const SrcMgr::SLocEntry &sloc = SM.getSLocEntry(fileID, &Invalid);
  if (Invalid || !sloc.isFile()) {
    createNullLocation(file, line, column, offset);
    return;
  }
  
  if (file)
    *file = const_cast<FileEntry *>(SM.getFileEntryForSLocEntry(sloc));
  if (line)
    *line = SM.getExpansionLineNumber(ExpansionLoc);
  if (column)
    *column = SM.getExpansionColumnNumber(ExpansionLoc);
  if (offset)
    *offset = SM.getDecomposedLoc(ExpansionLoc).second;
}
Referenced by clang_getInstantiationLocation().
clang_getFileLocation()
void clang_getFileLocation (CXSourceLocation location, CXFile * file, unsigned * line, unsigned * column, unsigned * offset)
Definition at line 340 of file CXSourceLocation.cpp.
                                             {
  if (!isASTUnitSourceLocation(location)) {
    CXLoadedDiagnostic::decodeLocation(location, file, line,
                                           column, offset);
    return;
  }
  SourceLocation Loc = SourceLocation::getFromRawEncoding(location.int_data);
  if (!location.ptr_data[0] || Loc.isInvalid())
    return createNullLocation(file, line, column, offset);
  const SourceManager &SM =
  *static_cast<const SourceManager*>(location.ptr_data[0]);
  SourceLocation FileLoc = SM.getFileLoc(Loc);
  std::pair<FileID, unsigned> LocInfo = SM.getDecomposedLoc(FileLoc);
  FileID FID = LocInfo.first;
  unsigned FileOffset = LocInfo.second;
  if (FID.isInvalid())
    return createNullLocation(file, line, column, offset);
  if (file)
    *file = const_cast<FileEntry *>(SM.getFileEntryForID(FID));
  if (line)
    *line = SM.getLineNumber(FID, FileOffset);
  if (column)
    *column = SM.getColumnNumber(FID, FileOffset);
  if (offset)
    *offset = FileOffset;
}
Referenced by clang::cxindex::Logger::operator<<().
clang_getInstantiationLocation()
void clang_getInstantiationLocation (CXSourceLocation location, CXFile * file, unsigned * line, unsigned * column, unsigned * offset)
Definition at line 294 of file CXSourceLocation.cpp.
                                                      {
  // Redirect to new API.
  clang_getExpansionLocation(location, file, line, column, offset);
}
References clang_getExpansionLocation().
clang_getLocation()
CXSourceLocation clang_getLocation (CXTranslationUnit TU, CXFile file, unsigned line, unsigned column)
Definition at line 115 of file CXSourceLocation.cpp.
                                                    {
  if (cxtu::isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return clang_getNullLocation();
  }
  if (!file)
    return clang_getNullLocation();
  if (line == 0 || column == 0)
    return clang_getNullLocation();
  
  LogRef Log = Logger::make(__func__);
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  ASTUnit::ConcurrencyCheck Check(*CXXUnit);
  const FileEntry *File = static_cast<const FileEntry *>(file);
  SourceLocation SLoc = CXXUnit->getLocation(File, line, column);
  if (SLoc.isInvalid()) {
    if (Log)
      *Log << llvm::format("(\"%s\", %d, %d) = invalid",
                           File->getName().str().c_str(), line, column);
    return clang_getNullLocation();
  }
  
  CXSourceLocation CXLoc =
      cxloc::translateSourceLocation(CXXUnit->getASTContext(), SLoc);
  if (Log)
    *Log << llvm::format("(\"%s\", %d, %d) = ", File->getName().str().c_str(),
                         line, column)
         << CXLoc;
  return CXLoc;
}
References clang_getNullLocation(), LOG_BAD_TU, and clang::cxindex::Logger::make().
clang_getLocationForOffset()
CXSourceLocation clang_getLocationForOffset (CXTranslationUnit TU, CXFile file, unsigned offset)
Definition at line 150 of file CXSourceLocation.cpp.
                                                             {
  if (cxtu::isNotUsableTU(TU)) {
    LOG_BAD_TU(TU);
    return clang_getNullLocation();
  }
  if (!file)
    return clang_getNullLocation();
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  SourceLocation SLoc
    = CXXUnit->getLocation(static_cast<const FileEntry *>(file), offset);
  if (SLoc.isInvalid())
    return clang_getNullLocation();
  
  return cxloc::translateSourceLocation(CXXUnit->getASTContext(), SLoc);
}
References clang_getNullLocation(), and LOG_BAD_TU.
clang_getNullLocation()
CXSourceLocation clang_getNullLocation ()
Definition at line 41 of file CXSourceLocation.cpp.
                                         {
  CXSourceLocation Result = { { nullptr, nullptr }, 0 };
  return Result;
}
Referenced by clang_getCursorLocation(), clang_getDiagnosticLocation(), clang_getLocation(), clang_getLocationForOffset(), clang_indexLoc_getCXSourceLocation(), and clang::CXStoredDiagnostic::getLocation().
clang_getNullRange()
CXSourceRange clang_getNullRange ()
Definition at line 52 of file CXSourceLocation.cpp.
                                   {
  CXSourceRange Result = { { nullptr, nullptr }, 0, 0 };
  return Result;
}
Referenced by clang_Cursor_getCommentRange(), clang_Cursor_getSpellingNameRange(), clang_getCompletionFixIt(), clang_getCursorReferenceNameRange(), clang_getDiagnosticFixIt(), clang_getDiagnosticRange(), and clang_Range_isNull().
clang_getPresumedLocation()
void clang_getPresumedLocation (CXSourceLocation location, CXString * filename, unsigned * line, unsigned * column)
Definition at line 263 of file CXSourceLocation.cpp.
                                                 {
  if (!isASTUnitSourceLocation(location)) {
    // Other SourceLocation implementations do not support presumed locations
    // at this time.
    createNullLocation(filename, line, column);
    return;
  }
  SourceLocation Loc = SourceLocation::getFromRawEncoding(location.int_data);
  if (!location.ptr_data[0] || Loc.isInvalid()) {
    createNullLocation(filename, line, column);
    return;
  }
  const SourceManager &SM =
      *static_cast<const SourceManager *>(location.ptr_data[0]);
  PresumedLoc PreLoc = SM.getPresumedLoc(Loc);
  if (PreLoc.isInvalid()) {
    createNullLocation(filename, line, column);
    return;
  }
  if (filename) *filename = cxstring::createRef(PreLoc.getFilename());
  if (line) *line = PreLoc.getLine();
  if (column) *column = PreLoc.getColumn();
}
clang_getRange()
CXSourceRange clang_getRange (CXSourceLocation begin, CXSourceLocation end)
Definition at line 57 of file CXSourceLocation.cpp.
                                                                           {
  if (!isASTUnitSourceLocation(begin)) {
    if (isASTUnitSourceLocation(end))
      return clang_getNullRange();
    CXSourceRange Result = { { begin.ptr_data[0], end.ptr_data[0] }, 0, 0 };
    return Result;
  }
  
  if (begin.ptr_data[0] != end.ptr_data[0] ||
      begin.ptr_data[1] != end.ptr_data[1])
    return clang_getNullRange();
  
  CXSourceRange Result = { { begin.ptr_data[0], begin.ptr_data[1] },
                           begin.int_data, end.int_data };
  return Result;
}
clang_getRangeEnd()
CXSourceLocation clang_getRangeEnd (CXSourceRange range)
Definition at line 99 of file CXSourceLocation.cpp.
                                                        {
  // Special decoding for CXSourceLocations for CXLoadedDiagnostics.
  if ((uintptr_t)range.ptr_data[0] & 0x1) {
    CXSourceLocation Result = { { range.ptr_data[1], nullptr }, 0 };
    return Result;
  }
  CXSourceLocation Result = { { range.ptr_data[0], range.ptr_data[1] },
    range.end_int_data };
  return Result;
}
Referenced by clang::cxindex::Logger::operator<<(), and PrintDiagnostic().
clang_getRangeStart()
CXSourceLocation clang_getRangeStart (CXSourceRange range)
Definition at line 87 of file CXSourceLocation.cpp.
                                                          {
  // Special decoding for CXSourceLocations for CXLoadedDiagnostics.
  if ((uintptr_t)range.ptr_data[0] & 0x1) {
    CXSourceLocation Result = { { range.ptr_data[0], nullptr }, 0 };
    return Result;
  }
  
  CXSourceLocation Result = { { range.ptr_data[0], range.ptr_data[1] },
    range.begin_int_data };
  return Result;
}
Referenced by clang::cxindex::Logger::operator<<(), and PrintDiagnostic().
clang_getSpellingLocation()
void clang_getSpellingLocation (CXSourceLocation location, CXFile * file, unsigned * line, unsigned * column, unsigned * offset)
Definition at line 303 of file CXSourceLocation.cpp.
                                                 {
  if (!isASTUnitSourceLocation(location)) {
    CXLoadedDiagnostic::decodeLocation(location, file, line,
                                           column, offset);
    return;
  }
  
  SourceLocation Loc = SourceLocation::getFromRawEncoding(location.int_data);
  
  if (!location.ptr_data[0] || Loc.isInvalid())
    return createNullLocation(file, line, column, offset);
  
  const SourceManager &SM =
  *static_cast<const SourceManager*>(location.ptr_data[0]);
  // FIXME: This should call SourceManager::getSpellingLoc().
  SourceLocation SpellLoc = SM.getFileLoc(Loc);
  std::pair<FileID, unsigned> LocInfo = SM.getDecomposedLoc(SpellLoc);
  FileID FID = LocInfo.first;
  unsigned FileOffset = LocInfo.second;
  
  if (FID.isInvalid())
    return createNullLocation(file, line, column, offset);
  
  if (file)
    *file = const_cast<FileEntry *>(SM.getFileEntryForID(FID));
  if (line)
    *line = SM.getLineNumber(FID, FileOffset);
  if (column)
    *column = SM.getColumnNumber(FID, FileOffset);
  if (offset)
    *offset = FileOffset;
}
Referenced by InclusionVisitor(), and PrintDiagnostic().
clang_Location_isFromMainFile()
int clang_Location_isFromMainFile (CXSourceLocation location)
Definition at line 211 of file CXSourceLocation.cpp.
                                                             {
  const SourceLocation Loc =
    SourceLocation::getFromRawEncoding(location.int_data);
  if (Loc.isInvalid())
    return 0;
  const SourceManager &SM =
    *static_cast<const SourceManager*>(location.ptr_data[0]);
  return SM.isWrittenInMainFile(Loc);
}
clang_Location_isInSystemHeader()
int clang_Location_isInSystemHeader (CXSourceLocation location)
Definition at line 200 of file CXSourceLocation.cpp.
                                                               {
  const SourceLocation Loc =
    SourceLocation::getFromRawEncoding(location.int_data);
  if (Loc.isInvalid())
    return 0;
  const SourceManager &SM =
    *static_cast<const SourceManager*>(location.ptr_data[0]);
  return SM.isInSystemHeader(Loc);
}
clang_Range_isNull()
int clang_Range_isNull (CXSourceRange range)
Definition at line 82 of file CXSourceLocation.cpp.
                                            {
  return clang_equalRanges(range, clang_getNullRange());
}
References clang_equalRanges(), and clang_getNullRange().