Tests/CleanTime Test Cases/Performance_Fibonacci_Without_Counter.cpp File Reference
#include <iostream>
#include <fstream>
#include `../lib/DataStorage.cpp`
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 5 of file Performance_Fibonacci_Without_Counter.cpp.
               {
    DataStorage dataStorage("Runtime,Scope");
    dataStorage.startEvent(0);
    double n, t1 = 0, t2 = 1, nextTerm = 0;
    n = 1000;
    std::cout << "Fibonacci Series: ";
    for (int i = 1; i <= n; ++i) {
        if(i == 1) {
            std::cout << t1;
            std::cout << ", ";
        }
        else if(i == 2) {
            std::cout << t2;
            std::cout << ", ";
        }
        nextTerm = t1 + t2;
        t1 = t2;
        t2 = nextTerm;
        std::cout << nextTerm << ", ";
    }
    dataStorage.endEvent(0);
    dataStorage.print();
    return 0;
}
References dataStorage(), DataStorage::endEvent(), DataStorage::print(), and DataStorage::startEvent().