/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/DummyClangFuzzer.cpp File Reference
#include `llvm/FuzzMutate/FuzzerCLI.h`
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
int LLVMFuzzerInitialize (int *argc, char ***argv)
int main (int argc, char *argv[])
Function Documentation
LLVMFuzzerInitialize()
int LLVMFuzzerInitialize (int * argc, char *** argv)
Definition at line 19 of file ClangFuzzer.cpp.
{ return 0; }
Referenced by main().
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 17 of file DummyClangFuzzer.cpp.
                                 {
  return llvm::runFuzzerOnInputs(argc, argv, LLVMFuzzerTestOneInput,
                                 LLVMFuzzerInitialize);
}
References LLVMFuzzerInitialize(), and LLVMFuzzerTestOneInput().