/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangLoopProtoFuzzer.cpp File Reference
#include `cxx_loop_proto.pb.h`
#include `fuzzer-initialize/fuzzer_initialize.h`
#include `handle-cxx/handle_cxx.h`
#include `proto-to-cxx/proto_to_cxx.h`
#include `src/libfuzzer/libfuzzer_macro.h`
Functions
DEFINE_BINARY_PROTO_FUZZER (const LoopFunction &input)
Detailed Description
This file implements a function that runs Clang on a single input and uses libprotobuf-mutator to find new inputs. This function is then linked into the Fuzzer library. This file differs from ExampleClangProtoFuzzer in that it uses a different protobuf that includes C++ code with a single for loop.
Function Documentation
DEFINE_BINARY_PROTO_FUZZER()
DEFINE_BINARY_PROTO_FUZZER (const LoopFunction & input)
Definition at line 26 of file ExampleClangLoopProtoFuzzer.cpp.
                                                      {
  auto S = LoopFunctionToString(input);
  HandleCXX(S, GetCLArgs());
}
References clang_fuzzer::GetCLArgs(), clang_fuzzer::HandleCXX(), and clang_fuzzer::LoopFunctionToString().