/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangProtoFuzzer.cpp File Reference
#include `cxx_proto.pb.h`
#include `handle-cxx/handle_cxx.h`
#include `proto-to-cxx/proto_to_cxx.h`
#include `fuzzer-initialize/fuzzer_initialize.h`
#include `src/libfuzzer/libfuzzer_macro.h`
Functions
DEFINE_BINARY_PROTO_FUZZER (const Function &input)
Detailed Description
This file implements a function that runs Clang on a single input and uses libprotobuf-mutator to find new inputs. This function is then linked into the Fuzzer library.
Function Documentation
DEFINE_BINARY_PROTO_FUZZER()
DEFINE_BINARY_PROTO_FUZZER (const Function & input)
Definition at line 24 of file ExampleClangProtoFuzzer.cpp.
                                                  {
  auto S = FunctionToString(input);
  HandleCXX(S, "./test.cc", GetCLArgs());
}
References clang_fuzzer::FunctionToString(), clang_fuzzer::GetCLArgs(), and clang_fuzzer::HandleCXX().