/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangLLVMProtoFuzzer.cpp File Reference
#include `cxx_loop_proto.pb.h`
#include `fuzzer-initialize/fuzzer_initialize.h`
#include `handle-llvm/handle_llvm.h`
#include `proto-to-llvm/loop_proto_to_llvm.h`
#include `src/libfuzzer/libfuzzer_macro.h`
Functions
DEFINE_BINARY_PROTO_FUZZER (const LoopFunction &input)
Detailed Description
This file implements a function that compiles a single LLVM IR string as input and uses libprotobuf-mutator to find new inputs. This function is then linked into the Fuzzer library.
Function Documentation
DEFINE_BINARY_PROTO_FUZZER()
DEFINE_BINARY_PROTO_FUZZER (const LoopFunction & input)
Definition at line 24 of file ExampleClangLLVMProtoFuzzer.cpp.
                                                      {
  auto S = LoopFunctionToLLVMString(input);
  HandleLLVM(S, GetCLArgs());
}
References clang_fuzzer::GetCLArgs(), clang_fuzzer::HandleLLVM(), and clang_fuzzer::LoopFunctionToLLVMString().