Tests/Examples/FunctionCallDecls.cpp File Reference
#include <iostream>
Functions
void test ()
int main (void)
Function Documentation
main()
int main (void)
Definition at line 9 of file FunctionCallDecls.cpp.
               {
    test();
    return 0;
}
References test().
test()
void test ()
Definition at line 3 of file FunctionCallDecls.cpp.
            {
    int i = 0;
    i = i + 2;
    std::cout << i;
}
Referenced by main(), tests.unit.test_analyze.FilteringFlagsTest::test_arch(), tests.unit.test_shell.ShellTest::test_decode_encode_are_same(), tests.unit.test_compilation.SplitTest::test_detect_cxx_from_compiler_name(), tests.unit.test_shell.ShellTest::test_encode_decode_are_same(), tests.unit.test_compilation.SplitTest::test_filter_flags(), tests.unit.test_intercept.InterceptUtilTest::test_format_entry_filters_action(), tests.unit.test_intercept.InterceptUtilTest::test_format_entry_normalize_filename(), tests.unit.test_clang.ClangGetCheckersTest::test_is_active(), tests.unit.test_analyze.FilteringFlagsTest::test_language_captured(), tests.unit.test_analyze.AnalyzerTest::test_nodebug_macros_appended(), and tests.unit.test_compilation.SplitTest::test_source_file().