Tests/Examples/FunctionCallDecl.cpp File Reference
#include <iostream>
Functions
void print ()
int main (void)
Function Documentation
main()
int main (void)
Definition at line 7 of file FunctionCallDecl.cpp.
               {
    print();
    return 0;
}
References print().
print()
void print ()
Definition at line 3 of file FunctionCallDecl.cpp.
             {
    std::cout << "Hello World";
}
Referenced by ScanView.ScanViewServer::halt(), ScanView.ScanViewServer::handle_error(), ScanView.ScanViewRequestHandler::handle_exception(), clang-format-diff::main(), clang-format::main(), clang-rename::main(), main(), libscanbuild.arguments::print_active_checkers(), libscanbuild.arguments::print_checkers(), ScanView.ReporterThread::run(), clang-format-sublime.ClangFormatCommand::run(), ScanView.ScanViewRequestHandler::send_open_report(), and ScanView.ScanViewServer::serve_forever().