/Users/maximilian/clang-llvm/clang/tools/libclang/Indexing.cpp File Reference
#include `CIndexDiagnostic.h`
#include `CIndexer.h`
#include `CLog.h`
#include `CXCursor.h`
#include `CXIndexDataConsumer.h`
#include `CXSourceLocation.h`
#include `CXString.h`
#include `CXTranslationUnit.h`
#include `clang/AST/ASTConsumer.h`
#include `clang/Frontend/ASTUnit.h`
#include `clang/Frontend/CompilerInstance.h`
#include `clang/Frontend/CompilerInvocation.h`
#include `clang/Frontend/FrontendAction.h`
#include `clang/Frontend/MultiplexConsumer.h`
#include `clang/Frontend/Utils.h`
#include `clang/Index/IndexingAction.h`
#include `clang/Lex/HeaderSearch.h`
#include `clang/Lex/PPCallbacks.h`
#include `clang/Lex/PPConditionalDirectiveRecord.h`
#include `clang/Lex/Preprocessor.h`
#include `clang/Lex/PreprocessorOptions.h`
#include `llvm/Support/CrashRecoveryContext.h`
#include `llvm/Support/MemoryBuffer.h`
#include <cstdio>
#include <mutex>
#include <utility>
Classes
struct llvm::DenseMapInfo< PPRegion >
Namespaces
 llvm
Functions
int clang_index_isEntityObjCContainerKind (CXIdxEntityKind K)
const CXIdxObjCContainerDeclInfo * clang_index_getObjCContainerDeclInfo (const CXIdxDeclInfo *DInfo)
const CXIdxObjCInterfaceDeclInfo * clang_index_getObjCInterfaceDeclInfo (const CXIdxDeclInfo *DInfo)
const CXIdxObjCCategoryDeclInfo * clang_index_getObjCCategoryDeclInfo (const CXIdxDeclInfo *DInfo)
const CXIdxObjCProtocolRefListInfo * clang_index_getObjCProtocolRefListInfo (const CXIdxDeclInfo *DInfo)
const CXIdxObjCPropertyDeclInfo * clang_index_getObjCPropertyDeclInfo (const CXIdxDeclInfo *DInfo)
const CXIdxIBOutletCollectionAttrInfo * clang_index_getIBOutletCollectionAttrInfo (const CXIdxAttrInfo *AInfo)
const CXIdxCXXClassDeclInfo * clang_index_getCXXClassDeclInfo (const CXIdxDeclInfo *DInfo)
CXIdxClientContainer clang_index_getClientContainer (const CXIdxContainerInfo *info)
void clang_index_setClientContainer (const CXIdxContainerInfo *info, CXIdxClientContainer client)
CXIdxClientEntity clang_index_getClientEntity (const CXIdxEntityInfo *info)
void clang_index_setClientEntity (const CXIdxEntityInfo *info, CXIdxClientEntity client)
CXIndexAction clang_IndexAction_create (CXIndex CIdx)
void clang_IndexAction_dispose (CXIndexAction idxAction)
int clang_indexSourceFile (CXIndexAction idxAction, CXClientData client_data, IndexerCallbacks *index_callbacks, unsigned index_callbacks_size, unsigned index_options, const char *source_filename, const char *const *command_line_args, int num_command_line_args, struct CXUnsavedFile *unsaved_files, unsigned num_unsaved_files, CXTranslationUnit *out_TU, unsigned TU_options)
int clang_indexSourceFileFullArgv (CXIndexAction idxAction, CXClientData client_data, IndexerCallbacks *index_callbacks, unsigned index_callbacks_size, unsigned index_options, const char *source_filename, const char *const *command_line_args, int num_command_line_args, struct CXUnsavedFile *unsaved_files, unsigned num_unsaved_files, CXTranslationUnit *out_TU, unsigned TU_options)
int clang_indexTranslationUnit (CXIndexAction idxAction, CXClientData client_data, IndexerCallbacks *index_callbacks, unsigned index_callbacks_size, unsigned index_options, CXTranslationUnit TU)
void clang_indexLoc_getFileLocation (CXIdxLoc location, CXIdxClientFile *indexFile, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
CXSourceLocation clang_indexLoc_getCXSourceLocation (CXIdxLoc location)
Function Documentation
clang_index_getClientContainer()
CXIdxClientContainer clang_index_getClientContainer (const CXIdxContainerInfo * info)
Definition at line 822 of file Indexing.cpp.
                                                               {
  if (!info)
    return nullptr;
  const ContainerInfo *Container = static_cast<const ContainerInfo *>(info);
  return Container->IndexCtx->getClientContainerForDC(Container->DC);
}
References clang::cxindex::ContainerInfo::DC, clang::cxindex::CXIndexDataConsumer::getClientContainerForDC(), and clang::cxindex::ContainerInfo::IndexCtx.
clang_index_getClientEntity()
CXIdxClientEntity clang_index_getClientEntity (const CXIdxEntityInfo * info)
Definition at line 837 of file Indexing.cpp.
                                                                           {
  if (!info)
    return nullptr;
  const EntityInfo *Entity = static_cast<const EntityInfo *>(info);
  return Entity->IndexCtx->getClientEntity(Entity->Dcl);
}
References clang::cxindex::EntityInfo::Dcl, clang::cxindex::CXIndexDataConsumer::getClientEntity(), and clang::cxindex::EntityInfo::IndexCtx.
clang_index_getCXXClassDeclInfo()
const CXIdxCXXClassDeclInfo* clang_index_getCXXClassDeclInfo (const CXIdxDeclInfo * DInfo)
Definition at line 810 of file Indexing.cpp.
                                                            {
  if (!DInfo)
    return nullptr;
  const DeclInfo *DI = static_cast<const DeclInfo *>(DInfo);
  if (const CXXClassDeclInfo *ClassInfo = dyn_cast<CXXClassDeclInfo>(DI))
    return &ClassInfo->CXXClassInfo;
  return nullptr;
}
clang_index_getIBOutletCollectionAttrInfo()
const CXIdxIBOutletCollectionAttrInfo* clang_index_getIBOutletCollectionAttrInfo (const CXIdxAttrInfo * AInfo)
Definition at line 797 of file Indexing.cpp.
                                                                      {
  if (!AInfo)
    return nullptr;
  const AttrInfo *DI = static_cast<const AttrInfo *>(AInfo);
  if (const IBOutletCollectionInfo *
        IBInfo = dyn_cast<IBOutletCollectionInfo>(DI))
    return &IBInfo->IBCollInfo;
  return nullptr;
}
clang_index_getObjCCategoryDeclInfo()
const CXIdxObjCCategoryDeclInfo* clang_index_getObjCCategoryDeclInfo (const CXIdxDeclInfo * DInfo)
Definition at line 751 of file Indexing.cpp.
                                                               {
  if (!DInfo)
    return nullptr;
  const DeclInfo *DI = static_cast<const DeclInfo *>(DInfo);
  if (const ObjCCategoryDeclInfo *
        CatInfo = dyn_cast<ObjCCategoryDeclInfo>(DI))
    return &CatInfo->ObjCCatDeclInfo;
  return nullptr;
}
clang_index_getObjCContainerDeclInfo()
const CXIdxObjCContainerDeclInfo* clang_index_getObjCContainerDeclInfo (const CXIdxDeclInfo * DInfo)
Definition at line 725 of file Indexing.cpp.
                                                                 {
  if (!DInfo)
    return nullptr;
  const DeclInfo *DI = static_cast<const DeclInfo *>(DInfo);
  if (const ObjCContainerDeclInfo *
        ContInfo = dyn_cast<ObjCContainerDeclInfo>(DI))
    return &ContInfo->ObjCContDeclInfo;
  return nullptr;
}
clang_index_getObjCInterfaceDeclInfo()
const CXIdxObjCInterfaceDeclInfo* clang_index_getObjCInterfaceDeclInfo (const CXIdxDeclInfo * DInfo)
Definition at line 738 of file Indexing.cpp.
                                                                 {
  if (!DInfo)
    return nullptr;
  const DeclInfo *DI = static_cast<const DeclInfo *>(DInfo);
  if (const ObjCInterfaceDeclInfo *
        InterInfo = dyn_cast<ObjCInterfaceDeclInfo>(DI))
    return &InterInfo->ObjCInterDeclInfo;
  return nullptr;
}
clang_index_getObjCPropertyDeclInfo()
const CXIdxObjCPropertyDeclInfo* clang_index_getObjCPropertyDeclInfo (const CXIdxDeclInfo * DInfo)
Definition at line 785 of file Indexing.cpp.
                                                                {
  if (!DInfo)
    return nullptr;
  const DeclInfo *DI = static_cast<const DeclInfo *>(DInfo);
  if (const ObjCPropertyDeclInfo *PropInfo = dyn_cast<ObjCPropertyDeclInfo>(DI))
    return &PropInfo->ObjCPropDeclInfo;
  return nullptr;
}
clang_index_getObjCProtocolRefListInfo()
const CXIdxObjCProtocolRefListInfo* clang_index_getObjCProtocolRefListInfo (const CXIdxDeclInfo * DInfo)
Definition at line 764 of file Indexing.cpp.
                                                                   {
  if (!DInfo)
    return nullptr;
  const DeclInfo *DI = static_cast<const DeclInfo *>(DInfo);
  
  if (const ObjCInterfaceDeclInfo *
        InterInfo = dyn_cast<ObjCInterfaceDeclInfo>(DI))
    return InterInfo->ObjCInterDeclInfo.protocols;
  
  if (const ObjCProtocolDeclInfo *
        ProtInfo = dyn_cast<ObjCProtocolDeclInfo>(DI))
    return &ProtInfo->ObjCProtoRefListInfo;
  if (const ObjCCategoryDeclInfo *CatInfo = dyn_cast<ObjCCategoryDeclInfo>(DI))
    return CatInfo->ObjCCatDeclInfo.protocols;
  return nullptr;
}
clang_index_isEntityObjCContainerKind()
int clang_index_isEntityObjCContainerKind (CXIdxEntityKind K)
Definition at line 720 of file Indexing.cpp.
                                                             {
  return CXIdxEntity_ObjCClass <= K && K <= CXIdxEntity_ObjCCategory;
}
clang_index_setClientContainer()
void clang_index_setClientContainer (const CXIdxContainerInfo * info, CXIdxClientContainer client)
Definition at line 829 of file Indexing.cpp.
                                                                 {
  if (!info)
    return;
  const ContainerInfo *Container = static_cast<const ContainerInfo *>(info);
  Container->IndexCtx->addContainerInMap(Container->DC, client);
}
References clang::cxindex::CXIndexDataConsumer::addContainerInMap(), clang::cxindex::ContainerInfo::DC, and clang::cxindex::ContainerInfo::IndexCtx.
clang_index_setClientEntity()
void clang_index_setClientEntity (const CXIdxEntityInfo * info, CXIdxClientEntity client)
Definition at line 844 of file Indexing.cpp.
                                                           {
  if (!info)
    return;
  const EntityInfo *Entity = static_cast<const EntityInfo *>(info);
  Entity->IndexCtx->setClientEntity(Entity->Dcl, client);
}
References clang::cxindex::EntityInfo::Dcl, clang::cxindex::EntityInfo::IndexCtx, and clang::cxindex::CXIndexDataConsumer::setClientEntity().
clang_IndexAction_create()
CXIndexAction clang_IndexAction_create (CXIndex CIdx)
Definition at line 852 of file Indexing.cpp.
                                                     {
  return new IndexSessionData(CIdx);
}
clang_IndexAction_dispose()
void clang_IndexAction_dispose (CXIndexAction idxAction)
Definition at line 856 of file Indexing.cpp.
                                                        {
  if (idxAction)
    delete static_cast<IndexSessionData *>(idxAction);
}
clang_indexLoc_getCXSourceLocation()
CXSourceLocation clang_indexLoc_getCXSourceLocation (CXIdxLoc location)
Definition at line 989 of file Indexing.cpp.
                                                                       {
  SourceLocation Loc = SourceLocation::getFromRawEncoding(location.int_data);
  if (!location.ptr_data[0] || Loc.isInvalid())
    return clang_getNullLocation();
  CXIndexDataConsumer &DataConsumer =
      *static_cast<CXIndexDataConsumer*>(location.ptr_data[0]);
  return cxloc::translateSourceLocation(DataConsumer.getASTContext(), Loc);
}
References clang_getNullLocation(), and clang::cxindex::CXIndexDataConsumer::getASTContext().
clang_indexLoc_getFileLocation()
void clang_indexLoc_getFileLocation (CXIdxLoc location, CXIdxClientFile * indexFile, CXFile * file, unsigned * line, unsigned * column, unsigned * offset)
Definition at line 968 of file Indexing.cpp.
                                                      {
  if (indexFile) *indexFile = nullptr;
  if (file) *file = nullptr;
  if (line) *line = 0;
  if (column) *column = 0;
  if (offset) *offset = 0;
  SourceLocation Loc = SourceLocation::getFromRawEncoding(location.int_data);
  if (!location.ptr_data[0] || Loc.isInvalid())
    return;
  CXIndexDataConsumer &DataConsumer =
      *static_cast<CXIndexDataConsumer*>(location.ptr_data[0]);
  DataConsumer.translateLoc(Loc, indexFile, file, line, column, offset);
}
References clang::cxindex::CXIndexDataConsumer::translateLoc().
clang_indexSourceFile()
int clang_indexSourceFile (CXIndexAction idxAction, CXClientData client_data, IndexerCallbacks * index_callbacks, unsigned index_callbacks_size, unsigned index_options, const char * source_filename, const char *const * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned num_unsaved_files, CXTranslationUnit * out_TU, unsigned TU_options)
Definition at line 861 of file Indexing.cpp.
                                               {
  SmallVector<const char *, 4> Args;
  Args.push_back("clang");
  Args.append(command_line_args, command_line_args + num_command_line_args);
  return clang_indexSourceFileFullArgv(
      idxAction, client_data, index_callbacks, index_callbacks_size,
      index_options, source_filename, Args.data(), Args.size(), unsaved_files,
      num_unsaved_files, out_TU, TU_options);
}
References clang_indexSourceFileFullArgv().
clang_indexSourceFileFullArgv()
int clang_indexSourceFileFullArgv (CXIndexAction idxAction, CXClientData client_data, IndexerCallbacks * index_callbacks, unsigned index_callbacks_size, unsigned index_options, const char * source_filename, const char *const * command_line_args, int num_command_line_args, struct CXUnsavedFile * unsaved_files, unsigned num_unsaved_files, CXTranslationUnit * out_TU, unsigned TU_options)
Definition at line 882 of file Indexing.cpp.
                                                    {
  LOG_FUNC_SECTION {
    *Log << source_filename << ": ";
    for (int i = 0; i != num_command_line_args; ++i)
      *Log << command_line_args[i] << " ";
  }
  if (num_unsaved_files && !unsaved_files)
    return CXError_InvalidArguments;
  CXErrorCode result = CXError_Failure;
  auto IndexSourceFileImpl = [=, &result]() {
    result = clang_indexSourceFile_Impl(
        idxAction, client_data, index_callbacks, index_callbacks_size,
        index_options, source_filename, command_line_args,
        num_command_line_args,
        llvm::makeArrayRef(unsaved_files, num_unsaved_files), out_TU,
        TU_options);
  };
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, IndexSourceFileImpl)) {
    fprintf(stderr, "libclang: crash detected during indexing source file: {\n");
    fprintf(stderr, " 'source_filename' : '%s'\n", source_filename);
    fprintf(stderr, " 'command_line_args' : [");
    for (int i = 0; i != num_command_line_args; ++i) {
      if (i)
        fprintf(stderr, ", ");
      fprintf(stderr, "'%s'", command_line_args[i]);
    }
    fprintf(stderr, "],\n");
    fprintf(stderr, " 'unsaved_files' : [");
    for (unsigned i = 0; i != num_unsaved_files; ++i) {
      if (i)
        fprintf(stderr, ", ");
      fprintf(stderr, "('%s', '...', %ld)", unsaved_files[i].Filename,
              unsaved_files[i].Length);
    }
    fprintf(stderr, "],\n");
    fprintf(stderr, " 'options' : %d,\n", TU_options);
    fprintf(stderr, "}\n");
    
    return 1;
  } else if (getenv("LIBCLANG_RESOURCE_USAGE")) {
    if (out_TU)
      PrintLibclangResourceUsage(*out_TU);
  }
  return result;
}
References LOG_FUNC_SECTION.
Referenced by clang_indexSourceFile().
clang_indexTranslationUnit()
int clang_indexTranslationUnit (CXIndexAction idxAction, CXClientData client_data, IndexerCallbacks * index_callbacks, unsigned index_callbacks_size, unsigned index_options, CXTranslationUnit TU)
Definition at line 940 of file Indexing.cpp.
                                                     {
  LOG_FUNC_SECTION {
    *Log << TU;
  }
  CXErrorCode result;
  auto IndexTranslationUnitImpl = [=, &result]() {
    result = clang_indexTranslationUnit_Impl(
        idxAction, client_data, index_callbacks, index_callbacks_size,
        index_options, TU);
  };
  llvm::CrashRecoveryContext CRC;
  if (!RunSafely(CRC, IndexTranslationUnitImpl)) {
    fprintf(stderr, "libclang: crash detected during indexing TU\n");
    
    return 1;
  }
  return result;
}
References LOG_FUNC_SECTION.