Tests/Prime Tests Cases/Performance_Prime_With_Counter_3.cpp File Reference
#include <chrono>
#include <ctime>
#include <iostream>
#include <bitset>
#include <map>
#include <cstring>
#include <cmath>
#include <fstream>
#include `../lib/DataStorage.cpp`
Classes
class BitArray
class prime_sieve
Functions
DataStorage dataStorage (`Runtime,Scope,CustomCompoundStmt i000002,WhileStmt 2844763`)
int main ()
Function Documentation
dataStorage()
DataStorage dataStorage (` Runtime, Scope , CustomCompoundStmt i000002, WhileStmt 2844763`)
Referenced by main(), and prime_sieve::runSieve().
main()
int main (void)
Definition at line 178 of file Performance_Prime_With_Counter_3.cpp.
{
dataStorage.startEvent(0);
    auto passes = 0;
    auto tStart = steady_clock::now();
    while (true)
    {
        prime_sieve sieve(1000000L);
        dataStorage.startEvent(1);
sieve.runSieve();
dataStorage.endEvent(1);
        passes++;
        if (duration_cast<seconds>(steady_clock::now() - tStart).count() >= 5)
        {
            sieve.printResults(false, duration_cast<microseconds>(steady_clock::now() - tStart).count() / 1000000.0, passes);
            break;
        }
    }
    dataStorage.endEvent(0);
dataStorage.print();return 0;
}
References dataStorage(), DataStorage::endEvent(), DataStorage::print(), prime_sieve::printResults(), prime_sieve::runSieve(), and DataStorage::startEvent().