Tests/Prime Tests Cases/Performance_Prime_With_Counter_2.cpp File Reference
#include <chrono>
#include <ctime>
#include <iostream>
#include <bitset>
#include <map>
#include <cstring>
#include <cmath>
#include <fstream>
#include `../lib/DataStorage.cpp`
Classes
class BitArray
class prime_sieve
Functions
DataStorage dataStorage (`Runtime,Scope,CustomCompoundStmt i000002,CXXMemberCallExpr 2873611,CustomCompoundStmt i000004,IfStmt 2876146`)
int main ()
Function Documentation
dataStorage()
DataStorage dataStorage (` Runtime, Scope , CustomCompoundStmt i000002, CXXMemberCallExpr 2873611, CustomCompoundStmt i000004, IfStmt 2876146`)
Referenced by main().
main()
int main (void)
Definition at line 174 of file Performance_Prime_With_Counter_2.cpp.
{
dataStorage.startEvent(0);
    auto passes = 0;
    auto tStart = steady_clock::now();
    dataStorage.startEvent(1);
while (true)
    {
        dataStorage.startEvent(2);
prime_sieve sieve(1000000L);
        dataStorage.endEvent(2);
dataStorage.startEvent(3);
sieve.runSieve();
dataStorage.endEvent(3);
        dataStorage.startEvent(4);
passes++;
        dataStorage.endEvent(4);
dataStorage.startEvent(5);
if (duration_cast<seconds>(steady_clock::now() - tStart).count() >= 5)
        {
            sieve.printResults(false, duration_cast<microseconds>(steady_clock::now() - tStart).count() / 1000000.0, passes);
            break;
        }dataStorage.endEvent(5);
    }
dataStorage.endEvent(1);
    dataStorage.endEvent(0);
dataStorage.print();return 0;
}
References dataStorage(), DataStorage::endEvent(), DataStorage::print(), prime_sieve::printResults(), prime_sieve::runSieve(), and DataStorage::startEvent().