RegionProfile.cpp File Reference
#include `RegionProfile.h`
#include <iomanip>
Classes
class MyVisitor
class Consumer
Customizes a Instance of ASTConsumer. The Consumer is used by the Frontend Action to traverse the AST Tree.
class ClangFrontendAction
Creates ASTConsumer and returns ASTContext. A new ClangFrontendAction is created in the main, where the CompilerInstance and the SourceFiles are used to generate a new AST Tree Consumer.
Functions
SourceLocation getLocationAfterToken (SourceLocation sourceLocation, ASTContext *localContext)
Returns Location after Token. The end location of a function oder stmt returns the location before a brace or a semicolon. The events have to be called after the end token. This location is returned by this function.
void traverseChildren (Stmt *funcBody, ASTContext *localContext)
Traverses recursively through the body of the specified function body. Function Body is a set of statements.
int main (int argc, const char **argv)
The entry point of the tool. The main functions deals with the input files and options. Furthermore the ClangFrontendAction will be created and is used to transform the code. After transformation the rewritten code will be printed to the specified output file.
Function Documentation
getLocationAfterToken()
SourceLocation getLocationAfterToken (SourceLocation sourceLocation, ASTContext * localContext)
Returns Location after Token. The end location of a function oder stmt returns the location before a brace or a semicolon. The events have to be called after the end token. This location is returned by this function.
!
Definition at line 10 of file RegionProfile.cpp.
                                                                                                {
    // get the current token at the specified location
    Optional <Token> currentToken(clang::Lexer::findNextToken(
            sourceLocation, localContext->getSourceManager(),
            localContext->getLangOpts()));
    // if token is raw identifier return last token
    if (currentToken->getKind() == clang::tok::raw_identifier) {
        sourceLocation = sourceLocation.getLocWithOffset(-1);
    }
        // if token is semi return this token
    else if (currentToken->getKind() == clang::tok::semi) {
        sourceLocation = sourceLocation.getLocWithOffset(0);
    }
        // if token is brace return next token
    else if (currentToken->getKind() == clang::tok::r_brace) {
        sourceLocation = sourceLocation.getLocWithOffset(1);
    }
    // find location after semicolon
    SourceLocation locAfterSemi(clang::Lexer::findLocationAfterToken(
            sourceLocation, clang::tok::semi,
            localContext->getSourceManager(),
            localContext->getLangOpts(), true));
    // find location after brace
    SourceLocation locAfterBrace(clang::Lexer::findLocationAfterToken(
            sourceLocation, clang::tok::r_brace,
            localContext->getSourceManager(),
            localContext->getLangOpts(), true));
    // if loc after semi is valid return locAfterSemi
    if (currentToken->getKind() != clang::tok::r_brace && locAfterSemi.isValid()) {
        sourceLocation = locAfterSemi;
    }
        // if loc after brace is valid return locAfterBrace
    else if (currentToken->getKind() != clang::tok::r_brace && locAfterBrace.isValid()) {
        sourceLocation = locAfterBrace;
    }
    // if token is brace return current location
    return sourceLocation;
}
Referenced by traverseChildren(), and MyVisitor::VisitStmt().
main()
int main (int argc, const char ** argv)
The entry point of the tool. The main functions deals with the input files and options. Furthermore the ClangFrontendAction will be created and is used to transform the code. After transformation the rewritten code will be printed to the specified output file.
!
Definition at line 400 of file RegionProfile.cpp.
                                        {
    // runtime start
    std::chrono::system_clock::time_point startTime = std::chrono::system_clock::now();
    // create Common Option Parser
    auto ExpectedParser = CommonOptionsParser::create(argc, argv, MyToolCategory, llvm::cl::Required);
    // terminate if specified options are not expected
    if (!ExpectedParser) {
        llvm::errs() << ExpectedParser.takeError();
        return 1;
    }
    // create local parameter variables
    std::string outputFilename = "output.cpp";
    std::string stmtId = "start";
    // create the stream for output file
    std::error_code err_code;
    // parse arguments
    for (int i = 0; i < argc; ++i) {
        // if output file is specified
        if (std::string(argv[ i ]) == "-o") {
            outputFilename = std::string(argv[ i + 1 ]);
        }
        // if statement id is specified
        if (std::string(argv[ i ]) == "--stmt") {
            stmtId = std::string(argv[ i + 1 ]);
        }
    }
    // Print Hagn Tool Information
    cout << setw(82) << setfill('=') << "\n";
    cout << setw(45) << setfill(' ') << "Hagn Tool" << setw(25) << "\n";
    cout << setw(83) << setfill('=') << "\n\n";
    cout << "Input File: " << argv[ 1 ] << "\n";
    cout << "Output File: " << outputFilename << "\n";
    // print no statement id notification
    if (stmtId == "start") {
        cout << "Mode: Annotating Main Function\n";
    } else {
        cout << "Mode: Annotate specified Statement\n";
        cout << "Statement ID: " << stmtId << "\n";
    }
    // add statement id to global scope
    statementOption = stmtId;
    // set destination of output file to the specified file
    llvm::raw_fd_ostream dest(outputFilename, err_code);
    // Parse the options and create new ClangTool
    CommonOptionsParser &OptionsParser = ExpectedParser.get();
    ClangTool Tool(OptionsParser.getCompilations(),
                    OptionsParser.getSourcePathList());
    // run the Clang Tool, creating a new FrontendAction
    int result = Tool.run(newFrontendActionFactory<ClangFrontendAction>().get());
    // add initialization and summary if transformation was successful
    if (transformationSuccess) {
        // if initialization Location is valid insert includes and create DataStorage Object
        identifierString.pop_back();
        if (initializationLocation.isValid()) {
            rewriter.InsertText(initializationLocation,
                                 "#include \"../lib/DataStorage.cpp\"\n""DataStorage dataStorage(\"" +
                                 identifierString + "\");");
        } else {
            cerr << "Invalid initializationLocation, Line 356";
            exit(EXIT_FAILURE);
        }
        // start an event at the beginning of the main function
        if (runtimeStartLocation.isValid()) {
            rewriter.InsertText(runtimeStartLocation, "dataStorage.startEvent(0);\n");
        } else {
            cerr << "Invalid runtimeStartLocation, Line 364";
            exit(EXIT_FAILURE);
        }
        // start event and insert time summery as last step in the main function
        if (summaryLocation.isValid()) {
            rewriter.InsertText(summaryLocation, "dataStorage.endEvent(0);\ndataStorage.print();");
        } else {
            cerr << "Invalid summaryLocation, Line 372";
            exit(EXIT_FAILURE);
        }
        // runtime end
        std::chrono::system_clock::time_point endTime = std::chrono::system_clock::now();
        std::chrono::duration<double, std::milli> ms_double = endTime - startTime;
        // print hagn tool runtime
        cout << "Runtime: " << ms_double.count() << "ms\n";
        // print program finished notification
        cout << "Success: Yes\n\n";
        // add transformed code to output file
        rewriter.getEditBuffer(rewriter.getSourceMgr().getMainFileID()).write(dest);
    } else {
        cout << "Success: No\n\n";
        exit(EXIT_FAILURE);
    }
    return result;
}
traverseChildren()
void traverseChildren (Stmt * funcBody, ASTContext * localContext)
Traverses recursively through the body of the specified function body. Function Body is a set of statements.
!
Definition at line 60 of file RegionProfile.cpp.
                                                                  {
    // count statements in body and search for parent statements
    int childrenSize = 0;
    Stmt *parentStmt = NULL;
    for (Stmt::child_iterator i = funcBody->child_begin(), e = funcBody->child_end(); i != e; ++i) {
        Stmt *currStmt = *i;
        if (currStmt->getStmtClass() != Stmt::ReturnStmtClass) {
            childrenSize++;
            if (currStmt->getStmtClass() == Stmt::CallExprClass
                 || currStmt->getStmtClass() == Stmt::ForStmtClass
                 || currStmt->getStmtClass() == Stmt::WhileStmtClass
                 || currStmt->getStmtClass() == Stmt::IfStmtClass
                 || currStmt->getStmtClass() == Stmt::CXXMemberCallExprClass
                    ) {
                parentStmt = currStmt;
            }
        }
    }
    // if body has multiple children, annotate all statements with performance counter
    if (childrenSize > 1) {
        bool isCompoundedStatement = false;
        SourceLocation lastEventEndLocation;
        for (Stmt::child_iterator i = funcBody->child_begin(), e = funcBody->child_end();
              i != e; ++i) {
            Stmt *currStmt = *i;
            currStmt->getStmtClassName();
            if (currStmt->getStmtClass() != Stmt::ReturnStmtClass) {
                SourceLocation beginLoc = currStmt->getBeginLoc();
                SourceLocation endLoc = getLocationAfterToken(currStmt->getEndLoc(), localContext);
                // if statement runtime is not merged
                if (!isCompoundedStatement) {
                    // set start time always
                    rewriter.InsertText(beginLoc,
                                         "dataStorage.startEvent(" + std::to_string(internalIdentifier) + ");\n");
                    // if statement is not parent, wait for next statement
                    if (currStmt->getStmtClass() != Stmt::CallExprClass &&
                         currStmt->getStmtClass() != Stmt::ForStmtClass &&
                         currStmt->getStmtClass() != Stmt::WhileStmtClass &&
                         currStmt->getStmtClass() != Stmt::IfStmtClass &&
                         currStmt->getStmtClass() != Stmt::CXXMemberCallExprClass
                            ) {
                        lastEventEndLocation = endLoc;
                        isCompoundedStatement = true;
                        // statement is parent, do not merge runtime
                    } else {
                        rewriter.InsertText(endLoc,
                                             "dataStorage.endEvent(" + std::to_string(internalIdentifier) + ");\n");
                        // concat stmtclass and stmtid and add to identifierString
                        int64_t id = currStmt->getID(*localContext);
                        std::string idString =
                                currStmt->getStmtClassName() + std::string(" ") + std::to_string(id);
                        identifierString += idString + ",";
                        isCompoundedStatement = false;
                        internalIdentifier++;
                    }
                    // if waiting for next statement
                } else {
                    // if statement is parent, stop last merge and annotate this statement
                    if (currStmt->getStmtClass() == Stmt::CallExprClass ||
                         currStmt->getStmtClass() == Stmt::ForStmtClass ||
                         currStmt->getStmtClass() == Stmt::WhileStmtClass ||
                         currStmt->getStmtClass() == Stmt::IfStmtClass ||
                         currStmt->getStmtClass() == Stmt::CXXMemberCallExprClass
                            ) {
                        // end old event
                        rewriter.InsertText(beginLoc,
                                             "dataStorage.endEvent(" + std::to_string(internalIdentifier) +
                                             ");\n");
                        // add compound description to identifier string
                        identifierString += "CustomCompoundStmt i00000" + to_string(internalIdentifier++) + ",";
                        // start and end new event around parent function
                        rewriter.InsertText(beginLoc,
                                             "dataStorage.startEvent(" + std::to_string(internalIdentifier) +
                                             ");\n");
                        rewriter.InsertText(endLoc,
                                             "dataStorage.endEvent(" + std::to_string(internalIdentifier++) +
                                             ");\n");
                        // concat stmtclass and stmtid and add to identifierString
                        int64_t id = currStmt->getID(*localContext);
                        std::string idString =
                                currStmt->getStmtClassName() + std::string(" ") + std::to_string(id);
                        identifierString += idString + ",";
                        isCompoundedStatement = false;
                        // wait for next statement again
                    } else {
                        lastEventEndLocation = endLoc;
                        isCompoundedStatement = true;
                    }
                }
            }
        }
        // end last event
        if (isCompoundedStatement && lastEventEndLocation.isValid()) {
            rewriter.InsertText(lastEventEndLocation,
                                 "dataStorage.endEvent(" + std::to_string(internalIdentifier++) + ");\n");
            identifierString += "CustomCompoundStmt i00000" + to_string(internalIdentifier) + ",";
        }
        // set transformation successful
        transformationSuccess = true;
    }
        // if body has zero or one statements
    else {
        // if one child is parent of another set of statements
        // call traverseChildren recursively
        if (parentStmt != NULL) {
            if (parentStmt->getStmtClass() == Stmt::CallExprClass) {
                CallExpr *expr = cast<CallExpr>(parentStmt);
                Stmt *nextBody = expr->getDirectCallee()->getBody();
                traverseChildren(nextBody, localContext);
            }
            if (parentStmt->getStmtClass() == Stmt::ForStmtClass) {
                ForStmt *forStmt = cast<ForStmt>(parentStmt);
                Stmt *nextBody = forStmt->getBody();
                traverseChildren(nextBody, localContext);
            }
            if (parentStmt->getStmtClass() == Stmt::WhileStmtClass) {
                WhileStmt *whileStmt = cast<WhileStmt>(parentStmt);
                Stmt *nextBody = whileStmt->getBody();
                traverseChildren(nextBody, localContext);
            }
            if (parentStmt->getStmtClass() == Stmt::IfStmtClass) {
                IfStmt *ifStmt = cast<IfStmt>(parentStmt);
                Stmt *nextBody = ifStmt->getThen();
                traverseChildren(nextBody, localContext);
            }
            if (parentStmt->getStmtClass() == Stmt::CXXMemberCallExprClass) {
                CXXMemberCallExpr *cxxMemberCallExpr = cast<CXXMemberCallExpr>(parentStmt);
                Stmt *nextBody = cxxMemberCallExpr->getDirectCallee()->getBody();
                traverseChildren(nextBody, localContext);
            }
            // if return is the only statement annotate nothing
        } else {
            // cout << "hagn-tool hasn't found any statements!\n";
        }
    }
}
References getLocationAfterToken(), identifierString, internalIdentifier, rewriter, and transformationSuccess.
Referenced by MyVisitor::VisitFunctionDecl(), and MyVisitor::VisitStmt().