/Users/maximilian/clang-llvm/clang/tools/c-arcmt-test/c-arcmt-test.c File Reference
#include `clang-c/Index.h`
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Classes
struct thread_info
Typedefs
typedef struct thread_info thread_info
Functions
int carcmttest_main (int argc, const char **argv)
void thread_runner (void *client_data_v)
int main (int argc, const char **argv)
Typedef Documentation
thread_info
typedef struct thread_info thread_info
Function Documentation
carcmttest_main()
int carcmttest_main (int argc, const char ** argv)
Definition at line 74 of file c-arcmt-test.c.
                                                 {
  clang_enableStackTraces();
  if (argc == 3 && strncmp(argv[1], "-mt-migrate-directory", 21) == 0)
    return print_remappings(argv[2]);
  if (argc > 1)
    return print_remappings_filelist(argv+1, argc-1);
  
  print_usage();
  return 1;
}
References clang_enableStackTraces().
Referenced by thread_runner().
main()
int main (int argc, const char ** argv)
Definition at line 109 of file c-arcmt-test.c.
                                      {
  thread_info client_data;
  atexit(flush_atexit);
#if defined(_WIN32)
  if (getenv("LIBCLANG_LOGGING") == NULL)
    putenv("LIBCLANG_LOGGING=1");
  _setmode(_fileno(stdout), _O_BINARY);
#else
  setenv("LIBCLANG_LOGGING", "1", /*overwrite=*/0);
#endif
  if (getenv("CINDEXTEST_NOTHREADS"))
    return carcmttest_main(argc, argv);
  client_data.argc = argc;
  client_data.argv = argv;
  clang_executeOnThread(thread_runner, &client_data, 0);
  return client_data.result;
}
thread_runner()
void thread_runner (void * client_data_v)
Definition at line 97 of file c-arcmt-test.c.
                                        {
  thread_info *client_data = client_data_v;
  client_data->result = carcmttest_main(client_data->argc, client_data->argv);
}
References thread_info::argc, thread_info::argv, carcmttest_main(), and thread_info::result.