TreePrinter Class Reference
Public Member Functions
TreePrinter (llvm::raw_ostream &out)
void printGroup (const GroupRecord &Group, unsigned Indent=0)
int showGroup (StringRef RootGroup)
int showAll ()
void showKey ()
Static Public Member Functions
static bool isIgnored (unsigned DiagID)
static bool unimplemented (const GroupRecord &Group)
static bool enabledByDefault (const GroupRecord &Group)
Public Attributes
llvm::raw_ostream & out
bool Internal
Detailed Description
Definition at line 23 of file TreeView.cpp.
Constructor & Destructor Documentation
TreePrinter()
TreePrinter::TreePrinter (llvm::raw_ostream & out) [inline]
Definition at line 30 of file TreeView.cpp.
: out(out), Internal(false) {}
Member Function Documentation
enabledByDefault()
static bool TreePrinter::enabledByDefault (const GroupRecord & Group) [inline], [static]
Definition at line 50 of file TreeView.cpp.
                                                         {
    for (const DiagnosticRecord &DR : Group.diagnostics()) {
      if (isIgnored(DR.DiagID))
        return false;
    }
    for (const GroupRecord &GR : Group.subgroups()) {
      if (!enabledByDefault(GR))
        return false;
    }
    return true;
  }
References diagtool::GroupRecord::diagnostics(), and diagtool::GroupRecord::subgroups().
isIgnored()
static bool TreePrinter::isIgnored (unsigned DiagID) [inline], [static]
Definition at line 32 of file TreeView.cpp.
                                         {
    // FIXME: This feels like a hack.
    static clang::DiagnosticsEngine Diags(new DiagnosticIDs,
                                          new DiagnosticOptions);
    return Diags.isIgnored(DiagID, SourceLocation());
  }
printGroup()
void TreePrinter::printGroup (const GroupRecord & Group, unsigned Indent = 0) [inline]
Definition at line 64 of file TreeView.cpp.
                                                                 {
    out.indent(Indent * 2);
    if (unimplemented(Group))
      out << Colors::RED;
    else if (enabledByDefault(Group))
      out << Colors::GREEN;
    else
      out << Colors::YELLOW;
    out << "-W" << Group.getName() << "\n" << Colors::RESET;
    ++Indent;
    for (const GroupRecord &GR : Group.subgroups()) {
      printGroup(GR, Indent);
    }
    if (Internal) {
      for (const DiagnosticRecord &DR : Group.diagnostics()) {
        if (!isIgnored(DR.DiagID))
          out << Colors::GREEN;
        out.indent(Indent * 2);
        out << DR.getName() << Colors::RESET << "\n";
      }
    }
  }
References diagtool::GroupRecord::diagnostics(), diagtool::GroupRecord::getName(), and diagtool::GroupRecord::subgroups().
showAll()
int TreePrinter::showAll () [inline]
Definition at line 110 of file TreeView.cpp.
                {
    ArrayRef<GroupRecord> AllGroups = getDiagnosticGroups();
    llvm::DenseSet<unsigned> NonRootGroupIDs;
    for (const GroupRecord &GR : AllGroups) {
      for (auto SI = GR.subgroup_begin(), SE = GR.subgroup_end(); SI != SE;
           ++SI) {
        NonRootGroupIDs.insert((unsigned)SI.getID());
      }
    }
    assert(NonRootGroupIDs.size() < AllGroups.size());
    for (unsigned i = 0, e = AllGroups.size(); i != e; ++i) {
      if (!NonRootGroupIDs.count(i))
        printGroup(AllGroups[i]);
    }
    return 0;
  }
References diagtool::getDiagnosticGroups().
showGroup()
int TreePrinter::showGroup (StringRef RootGroup) [inline]
Definition at line 91 of file TreeView.cpp.
                                     {
    ArrayRef<GroupRecord> AllGroups = getDiagnosticGroups();
    if (RootGroup.size() > UINT16_MAX) {
      llvm::errs() << "No such diagnostic group exists\n";
      return 1;
    }
    const GroupRecord *Found = llvm::lower_bound(AllGroups, RootGroup);
    if (Found == AllGroups.end() || Found->getName() != RootGroup) {
      llvm::errs() << "No such diagnostic group exists\n";
      return 1;
    }
    printGroup(*Found);
    return 0;
  }
References diagtool::getDiagnosticGroups(), and diagtool::GroupRecord::getName().
showKey()
void TreePrinter::showKey () [inline]
Definition at line 131 of file TreeView.cpp.
                 {
    out << '\n' << Colors::GREEN << "GREEN" << Colors::RESET
        << " = enabled by default";
    out << '\n' << Colors::RED << "RED" << Colors::RESET
        << " = unimplemented (accepted for GCC compatibility)\n\n";
  }
unimplemented()
static bool TreePrinter::unimplemented (const GroupRecord & Group) [inline], [static]
Definition at line 39 of file TreeView.cpp.
                                                      {
    if (!Group.diagnostics().empty())
      return false;
    for (const GroupRecord &GR : Group.subgroups())
      if (!unimplemented(GR))
        return false;
    return true;
  }
References diagtool::GroupRecord::diagnostics(), and diagtool::GroupRecord::subgroups().
Member Data Documentation
Internal
bool TreePrinter::Internal
Definition at line 28 of file TreeView.cpp.
out
llvm::raw_ostream& TreePrinter::out
Definition at line 27 of file TreeView.cpp.
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/diagtool/TreeView.cpp