BitArray Class Reference
Public Member Functions
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
BitArray (size_t size)
~BitArray ()
bool get (size_t n) const
void setFlagsFalse (size_t n, size_t skip)
Static Public Member Functions
static constexpr uint32_t rol (uint32_t x, uint32_t n)
static constexpr uint32_t rol (uint32_t x, uint32_t n)
static constexpr uint32_t rol (uint32_t x, uint32_t n)
static constexpr uint32_t rol (uint32_t x, uint32_t n)
static constexpr uint32_t rol (uint32_t x, uint32_t n)
static constexpr uint32_t rol (uint32_t x, uint32_t n)
static constexpr uint32_t rol (uint32_t x, uint32_t n)
Detailed Description
Definition at line 20 of file Performance_Prime_With_Counter_1.cpp.
Constructor & Destructor Documentation
BitArray() [1/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 40 of file Performance_Prime_With_Counter_1.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [1/7]
BitArray::~BitArray () [inline]
Definition at line 45 of file Performance_Prime_With_Counter_1.cpp.
{delete [] array;}
BitArray() [2/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 40 of file Performance_Prime_With_Counter_2.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [2/7]
BitArray::~BitArray () [inline]
Definition at line 45 of file Performance_Prime_With_Counter_2.cpp.
{delete [] array;}
BitArray() [3/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 40 of file Performance_Prime_With_Counter_3.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [3/7]
BitArray::~BitArray () [inline]
Definition at line 45 of file Performance_Prime_With_Counter_3.cpp.
{delete [] array;}
BitArray() [4/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 40 of file Performance_Prime_With_Counter_4.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [4/7]
BitArray::~BitArray () [inline]
Definition at line 45 of file Performance_Prime_With_Counter_4.cpp.
{delete [] array;}
BitArray() [5/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 40 of file Performance_Prime_With_Counter_5.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [5/7]
BitArray::~BitArray () [inline]
Definition at line 45 of file Performance_Prime_With_Counter_5.cpp.
{delete [] array;}
BitArray() [6/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 40 of file Performance_Prime_With_Counter_6.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [6/7]
BitArray::~BitArray () [inline]
Definition at line 45 of file Performance_Prime_With_Counter_6.cpp.
{delete [] array;}
BitArray() [7/7]
BitArray::BitArray (size_t size) [inline], [explicit]
Definition at line 39 of file Performance_Prime_Without_Counter.cpp.
                                   : arrSize(size) {
        array = new uint32_t[arraySize(size)];
        std::memset(array, 0xFF, (size >> 3) + ((size & 7) > 0));
    }
 BitArray() [7/7]
BitArray::~BitArray () [inline]
Definition at line 44 of file Performance_Prime_Without_Counter.cpp.
{delete [] array;}
Member Function Documentation
get() [1/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 47 of file Performance_Prime_With_Counter_1.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
Referenced by prime_sieve::countPrimes(), prime_sieve::printResults(), and prime_sieve::runSieve().
get() [2/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 47 of file Performance_Prime_With_Counter_2.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
get() [3/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 47 of file Performance_Prime_With_Counter_3.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
get() [4/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 47 of file Performance_Prime_With_Counter_4.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
get() [5/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 47 of file Performance_Prime_With_Counter_5.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
get() [6/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 47 of file Performance_Prime_With_Counter_6.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
get() [7/7]
bool BitArray::get (size_t n) const [inline]
Definition at line 46 of file Performance_Prime_Without_Counter.cpp.
                             {
        return getSubindex(n, array[index(n)]);
    }
rol() [1/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 51 of file Performance_Prime_With_Counter_1.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
rol() [2/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 51 of file Performance_Prime_With_Counter_2.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
rol() [3/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 51 of file Performance_Prime_With_Counter_3.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
rol() [4/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 51 of file Performance_Prime_With_Counter_4.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
rol() [5/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 51 of file Performance_Prime_With_Counter_5.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
rol() [6/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 51 of file Performance_Prime_With_Counter_6.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
rol() [7/7]
static constexpr uint32_t BitArray::rol (uint32_t x, uint32_t n) [inline], [static], [constexpr]
Definition at line 50 of file Performance_Prime_Without_Counter.cpp.
                                                          {
        return (x<<n) | (x>>(32-n));
    }
setFlagsFalse() [1/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 55 of file Performance_Prime_With_Counter_1.cpp.
                                              {
        auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        while (n < arrSize) {
            array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
        }
    }
Referenced by prime_sieve::runSieve().
setFlagsFalse() [2/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 55 of file Performance_Prime_With_Counter_2.cpp.
                                              {
        auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        while (n < arrSize) {
            array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
        }
    }
setFlagsFalse() [3/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 55 of file Performance_Prime_With_Counter_3.cpp.
                                              {
        auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        while (n < arrSize) {
            array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
        }
    }
setFlagsFalse() [4/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 55 of file Performance_Prime_With_Counter_4.cpp.
                                              {
        auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        while (n < arrSize) {
            array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
        }
    }
setFlagsFalse() [5/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 55 of file Performance_Prime_With_Counter_5.cpp.
                                              {
        dataStorage.startEvent(2);
auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        dataStorage.endEvent(2);
dataStorage.startEvent(3);
while (n < arrSize) {
            array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
        }dataStorage.endEvent(3);
    }
References dataStorage(), DataStorage::endEvent(), and DataStorage::startEvent().
setFlagsFalse() [6/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 55 of file Performance_Prime_With_Counter_6.cpp.
                                              {
        auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        dataStorage.startEvent(1);
while (n < arrSize) {
            dataStorage.startEvent(2);
array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
dataStorage.endEvent(2);
        }dataStorage.endEvent(1);
    }
References dataStorage(), DataStorage::endEvent(), and DataStorage::startEvent().
setFlagsFalse() [7/7]
void BitArray::setFlagsFalse (size_t n, size_t skip) [inline]
Definition at line 54 of file Performance_Prime_Without_Counter.cpp.
                                              {
        auto rolling_mask = ~uint32_t(1 << n % 32);
        auto roll_bits = skip % 32;
        while (n < arrSize) {
            array[index(n)] &= rolling_mask;
            n += skip;
            rolling_mask = rol(rolling_mask, roll_bits);
        }
    }
The documentation for this class was generated from the following files:
Tests/Prime Tests Cases/Performance_Prime_With_Counter_1.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_2.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_3.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_4.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_5.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_6.cpp
Tests/Prime Tests Cases/Performance_Prime_Without_Counter.cpp