clang::cxcursor::CursorVisitor Class Reference
#include <CursorVisitor.h>
Public Types
typedef bool(* PostChildrenVisitorTy) (CXCursor cursor, CXClientData client_data)
Public Member Functions
CursorVisitor (CXTranslationUnit TU, CXCursorVisitor Visitor, CXClientData ClientData, bool VisitPreprocessorLast, bool VisitIncludedPreprocessingEntries=false, SourceRange RegionOfInterest=SourceRange(), bool VisitDeclsOnly=false, PostChildrenVisitorTy PostChildrenVisitor=nullptr)
~CursorVisitor ()
ASTUnit * getASTUnit () const
CXTranslationUnit getTU () const
bool Visit (CXCursor Cursor, bool CheckedRegionOfInterest=false)
bool visitFileRegion ()
bool visitPreprocessedEntitiesInRegion ()
bool shouldVisitIncludedEntities () const
template<typename InputIterator >
bool visitPreprocessedEntities (InputIterator First, InputIterator Last, PreprocessingRecord &PPRec, FileID FID=FileID())
bool VisitChildren (CXCursor Parent)
bool VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl *D)
bool VisitTypeAliasDecl (TypeAliasDecl *D)
bool VisitAttributes (Decl *D)
bool VisitBlockDecl (BlockDecl *B)
bool VisitCXXRecordDecl (CXXRecordDecl *D)
Optional< bool > shouldVisitCursor (CXCursor C)
bool VisitDeclContext (DeclContext *DC)
bool VisitTranslationUnitDecl (TranslationUnitDecl *D)
bool VisitTypedefDecl (TypedefDecl *D)
bool VisitTagDecl (TagDecl *D)
bool VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl *D)
bool VisitClassTemplatePartialSpecializationDecl (ClassTemplatePartialSpecializationDecl *D)
bool VisitTemplateTypeParmDecl (TemplateTypeParmDecl *D)
bool VisitEnumConstantDecl (EnumConstantDecl *D)
bool VisitDeclaratorDecl (DeclaratorDecl *DD)
bool VisitFunctionDecl (FunctionDecl *ND)
bool VisitFieldDecl (FieldDecl *D)
bool VisitVarDecl (VarDecl *)
bool VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl *D)
bool VisitFunctionTemplateDecl (FunctionTemplateDecl *D)
bool VisitClassTemplateDecl (ClassTemplateDecl *D)
bool VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl *D)
bool VisitObjCTypeParamDecl (ObjCTypeParamDecl *D)
bool VisitObjCMethodDecl (ObjCMethodDecl *ND)
bool VisitObjCContainerDecl (ObjCContainerDecl *D)
bool VisitObjCCategoryDecl (ObjCCategoryDecl *ND)
bool VisitObjCProtocolDecl (ObjCProtocolDecl *PID)
bool VisitObjCPropertyDecl (ObjCPropertyDecl *PD)
bool VisitObjCTypeParamList (ObjCTypeParamList *typeParamList)
bool VisitObjCInterfaceDecl (ObjCInterfaceDecl *D)
bool VisitObjCImplDecl (ObjCImplDecl *D)
bool VisitObjCCategoryImplDecl (ObjCCategoryImplDecl *D)
bool VisitObjCImplementationDecl (ObjCImplementationDecl *D)
bool VisitObjCPropertyImplDecl (ObjCPropertyImplDecl *PD)
bool VisitLinkageSpecDecl (LinkageSpecDecl *D)
bool VisitNamespaceDecl (NamespaceDecl *D)
bool VisitNamespaceAliasDecl (NamespaceAliasDecl *D)
bool VisitUsingDirectiveDecl (UsingDirectiveDecl *D)
bool VisitUsingDecl (UsingDecl *D)
bool VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl *D)
bool VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl *D)
bool VisitStaticAssertDecl (StaticAssertDecl *D)
bool VisitFriendDecl (FriendDecl *D)
bool VisitDecompositionDecl (DecompositionDecl *D)
bool VisitDeclarationNameInfo (DeclarationNameInfo Name)
bool VisitNestedNameSpecifier (NestedNameSpecifier *NNS, SourceRange Range)
bool VisitNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
bool VisitTemplateParameters (const TemplateParameterList *Params)
bool VisitTemplateName (TemplateName Name, SourceLocation Loc)
bool VisitTemplateArgumentLoc (const TemplateArgumentLoc &TAL)
bool VisitTagTypeLoc (TagTypeLoc TL)
bool VisitArrayTypeLoc (ArrayTypeLoc TL)
bool VisitFunctionTypeLoc (FunctionTypeLoc TL, bool SkipResultType=false)
bool IsInRegionOfInterest (CXCursor C)
bool RunVisitorWorkList (VisitorWorkList &WL)
void EnqueueWorkList (VisitorWorkList &WL, const Stmt *S)
LLVM_ATTRIBUTE_NOINLINE bool Visit (const Stmt *S)
Detailed Description
Definition at line 63 of file CursorVisitor.h.
Member Typedef Documentation
PostChildrenVisitorTy
typedef bool(* clang::cxcursor::CursorVisitor::PostChildrenVisitorTy) (CXCursor cursor, CXClientData client_data)
Callback called after child nodes of a cursor have been visited. Return true to break visitation or false to continue.
Definition at line 68 of file CursorVisitor.h.
Constructor & Destructor Documentation
CursorVisitor()
clang::cxcursor::CursorVisitor::CursorVisitor (CXTranslationUnit TU, CXCursorVisitor Visitor, CXClientData ClientData, bool VisitPreprocessorLast, bool VisitIncludedPreprocessingEntries = false, SourceRange RegionOfInterest = SourceRange(), bool VisitDeclsOnly = false, PostChildrenVisitorTy PostChildrenVisitor = nullptr) [inline]
Definition at line 150 of file CursorVisitor.h.
      : TU(TU), AU(cxtu::getASTUnit(TU)), Visitor(Visitor),
        PostChildrenVisitor(PostChildrenVisitor), ClientData(ClientData),
        VisitPreprocessorLast(VisitPreprocessorLast),
        VisitIncludedEntities(VisitIncludedPreprocessingEntries),
        RegionOfInterest(RegionOfInterest), VisitDeclsOnly(VisitDeclsOnly),
        DI_current(nullptr), FileDI_current(nullptr) {
    Parent.kind = CXCursor_NoDeclFound;
    Parent.data[0] = nullptr;
    Parent.data[1] = nullptr;
    Parent.data[2] = nullptr;
    StmtParent = nullptr;
  }
 CursorVisitor()
clang::cxcursor::CursorVisitor::~CursorVisitor () [inline]
Definition at line 169 of file CursorVisitor.h.
                   {
    // Free the pre-allocated worklists for data-recursion.
    for (SmallVectorImpl<VisitorWorkList *>::iterator I = WorkListCache.begin(),
                                                      E = WorkListCache.end();
         I != E; ++I) {
      delete *I;
    }
  }
Member Function Documentation
EnqueueWorkList()
void CursorVisitor::EnqueueWorkList (VisitorWorkList & WL, const Stmt * S)
Definition at line 3149 of file CIndex.cpp.
                                                                      {
  EnqueueVisitor(WL, MakeCXCursor(S, StmtParent, TU, RegionOfInterest))
      .Visit(S);
}
References clang::cxcursor::MakeCXCursor().
getASTUnit()
ASTUnit* clang::cxcursor::CursorVisitor::getASTUnit () const [inline]
Definition at line 178 of file CursorVisitor.h.
{ return AU; }
getTU()
CXTranslationUnit clang::cxcursor::CursorVisitor::getTU () const [inline]
Definition at line 179 of file CursorVisitor.h.
{ return TU; }
IsInRegionOfInterest()
bool CursorVisitor::IsInRegionOfInterest (CXCursor C)
Definition at line 3154 of file CIndex.cpp.
                                                   {
  if (RegionOfInterest.isValid()) {
    SourceRange Range = getRawCursorExtent(C);
    if (Range.isInvalid() || CompareRegionOfInterest(Range))
      return false;
  }
  return true;
}
RunVisitorWorkList()
bool CursorVisitor::RunVisitorWorkList (VisitorWorkList & WL)
Definition at line 3163 of file CIndex.cpp.
                                                          {
  while (!WL.empty()) {
    // Dequeue the worklist item.
    VisitorJob LI = WL.pop_back_val();
    // Set the Parent field, then back to its old value once we're done.
    SetParentRAII SetParent(Parent, StmtParent, LI.getParent());
    switch (LI.getKind()) {
    case VisitorJob::DeclVisitKind: {
      const Decl *D = cast<DeclVisit>(&LI)->get();
      if (!D)
        continue;
      // For now, perform default visitation for Decls.
      if (Visit(MakeCXCursor(D, TU, RegionOfInterest,
                             cast<DeclVisit>(&LI)->isFirst())))
        return true;
      continue;
    }
    case VisitorJob::ExplicitTemplateArgsVisitKind: {
      for (const TemplateArgumentLoc &Arg :
           *cast<ExplicitTemplateArgsVisit>(&LI)) {
        if (VisitTemplateArgumentLoc(Arg))
          return true;
      }
      continue;
    }
    case VisitorJob::TypeLocVisitKind: {
      // Perform default visitation for TypeLocs.
      if (Visit(cast<TypeLocVisit>(&LI)->get()))
        return true;
      continue;
    }
    case VisitorJob::LabelRefVisitKind: {
      const LabelDecl *LS = cast<LabelRefVisit>(&LI)->get();
      if (LabelStmt *stmt = LS->getStmt()) {
        if (Visit(MakeCursorLabelRef(stmt, cast<LabelRefVisit>(&LI)->getLoc(),
                                     TU))) {
          return true;
        }
      }
      continue;
    }
    case VisitorJob::NestedNameSpecifierLocVisitKind: {
      NestedNameSpecifierLocVisit *V = cast<NestedNameSpecifierLocVisit>(&LI);
      if (VisitNestedNameSpecifierLoc(V->get()))
        return true;
      continue;
    }
    case VisitorJob::DeclarationNameInfoVisitKind: {
      if (VisitDeclarationNameInfo(cast<DeclarationNameInfoVisit>(&LI)->get()))
        return true;
      continue;
    }
    case VisitorJob::MemberRefVisitKind: {
      MemberRefVisit *V = cast<MemberRefVisit>(&LI);
      if (Visit(MakeCursorMemberRef(V->get(), V->getLoc(), TU)))
        return true;
      continue;
    }
    case VisitorJob::StmtVisitKind: {
      const Stmt *S = cast<StmtVisit>(&LI)->get();
      if (!S)
        continue;
      // Update the current cursor.
      CXCursor Cursor = MakeCXCursor(S, StmtParent, TU, RegionOfInterest);
      if (!IsInRegionOfInterest(Cursor))
        continue;
      switch (Visitor(Cursor, Parent, ClientData)) {
      case CXChildVisit_Break:
        return true;
      case CXChildVisit_Continue:
        break;
      case CXChildVisit_Recurse:
        if (PostChildrenVisitor)
          WL.push_back(PostChildrenVisit(nullptr, Cursor));
        EnqueueWorkList(WL, S);
        break;
      }
      continue;
    }
    case VisitorJob::MemberExprPartsKind: {
      // Handle the other pieces in the MemberExpr besides the base.
      const MemberExpr *M = cast<MemberExprParts>(&LI)->get();
      // Visit the nested-name-specifier
      if (NestedNameSpecifierLoc QualifierLoc = M->getQualifierLoc())
        if (VisitNestedNameSpecifierLoc(QualifierLoc))
          return true;
      // Visit the declaration name.
      if (VisitDeclarationNameInfo(M->getMemberNameInfo()))
        return true;
      // Visit the explicitly-specified template arguments, if any.
      if (M->hasExplicitTemplateArgs()) {
        for (const TemplateArgumentLoc *Arg = M->getTemplateArgs(),
                                       *ArgEnd = Arg + M->getNumTemplateArgs();
             Arg != ArgEnd; ++Arg) {
          if (VisitTemplateArgumentLoc(*Arg))
            return true;
        }
      }
      continue;
    }
    case VisitorJob::DeclRefExprPartsKind: {
      const DeclRefExpr *DR = cast<DeclRefExprParts>(&LI)->get();
      // Visit nested-name-specifier, if present.
      if (NestedNameSpecifierLoc QualifierLoc = DR->getQualifierLoc())
        if (VisitNestedNameSpecifierLoc(QualifierLoc))
          return true;
      // Visit declaration name.
      if (VisitDeclarationNameInfo(DR->getNameInfo()))
        return true;
      continue;
    }
    case VisitorJob::OverloadExprPartsKind: {
      const OverloadExpr *O = cast<OverloadExprParts>(&LI)->get();
      // Visit the nested-name-specifier.
      if (NestedNameSpecifierLoc QualifierLoc = O->getQualifierLoc())
        if (VisitNestedNameSpecifierLoc(QualifierLoc))
          return true;
      // Visit the declaration name.
      if (VisitDeclarationNameInfo(O->getNameInfo()))
        return true;
      // Visit the overloaded declaration reference.
      if (Visit(MakeCursorOverloadedDeclRef(O, TU)))
        return true;
      continue;
    }
    case VisitorJob::SizeOfPackExprPartsKind: {
      const SizeOfPackExpr *E = cast<SizeOfPackExprParts>(&LI)->get();
      NamedDecl *Pack = E->getPack();
      if (isa<TemplateTypeParmDecl>(Pack)) {
        if (Visit(MakeCursorTypeRef(cast<TemplateTypeParmDecl>(Pack),
                                    E->getPackLoc(), TU)))
          return true;
        continue;
      }
      if (isa<TemplateTemplateParmDecl>(Pack)) {
        if (Visit(MakeCursorTemplateRef(cast<TemplateTemplateParmDecl>(Pack),
                                        E->getPackLoc(), TU)))
          return true;
        continue;
      }
      // Non-type template parameter packs and function parameter packs are
      // treated like DeclRefExpr cursors.
      continue;
    }
    case VisitorJob::LambdaExprPartsKind: {
      // Visit non-init captures.
      const LambdaExpr *E = cast<LambdaExprParts>(&LI)->get();
      for (LambdaExpr::capture_iterator C = E->explicit_capture_begin(),
                                        CEnd = E->explicit_capture_end();
           C != CEnd; ++C) {
        if (!C->capturesVariable())
          continue;
        if (Visit(MakeCursorVariableRef(C->getCapturedVar(), C->getLocation(),
                                        TU)))
          return true;
      }
      // Visit init captures
      for (auto InitExpr : E->capture_inits()) {
        if (InitExpr && Visit(InitExpr))
          return true;
      }
      TypeLoc TL = E->getCallOperator()->getTypeSourceInfo()->getTypeLoc();
      // Visit parameters and return type, if present.
      if (FunctionTypeLoc Proto = TL.getAs<FunctionProtoTypeLoc>()) {
        if (E->hasExplicitParameters()) {
          // Visit parameters.
          for (unsigned I = 0, N = Proto.getNumParams(); I != N; ++I)
            if (Visit(MakeCXCursor(Proto.getParam(I), TU)))
              return true;
        }
        if (E->hasExplicitResultType()) {
          // Visit result type.
          if (Visit(Proto.getReturnLoc()))
            return true;
        }
      }
      break;
    }
    case VisitorJob::PostChildrenVisitKind:
      if (PostChildrenVisitor(Parent, ClientData))
        return true;
      break;
    }
  }
  return false;
}
References clang::cxcursor::VisitorJob::DeclarationNameInfoVisitKind, clang::cxcursor::VisitorJob::DeclVisitKind, clang::cxcursor::VisitorJob::ExplicitTemplateArgsVisitKind, startfile::get(), clang::cxcursor::VisitorJob::getKind(), clang::cxcursor::VisitorJob::getParent(), clang::cxcursor::VisitorJob::LabelRefVisitKind, clang::cxcursor::MakeCursorLabelRef(), clang::cxcursor::MakeCursorMemberRef(), clang::cxcursor::MakeCXCursor(), clang::cxcursor::VisitorJob::MemberRefVisitKind, clang::cxcursor::VisitorJob::NestedNameSpecifierLocVisitKind, clang::cxcursor::VisitorJob::StmtVisitKind, and clang::cxcursor::VisitorJob::TypeLocVisitKind.
shouldVisitCursor()
Optional< bool > CursorVisitor::shouldVisitCursor (CXCursor C)
Definition at line 602 of file CIndex.cpp.
                                                               {
  if (RegionOfInterest.isValid()) {
    SourceRange Range = getFullCursorExtent(Cursor, AU->getSourceManager());
    if (Range.isInvalid())
      return None;
    switch (CompareRegionOfInterest(Range)) {
    case RangeBefore:
      // This declaration comes before the region of interest; skip it.
      return None;
    case RangeAfter:
      // This declaration comes after the region of interest; we're done.
      return false;
    case RangeOverlap:
      // This declaration overlaps the region of interest; visit it.
      break;
    }
  }
  return true;
}
shouldVisitIncludedEntities()
bool clang::cxcursor::CursorVisitor::shouldVisitIncludedEntities () const [inline]
Definition at line 189 of file CursorVisitor.h.
{ return VisitIncludedEntities; }
Visit() [1/2]
bool CursorVisitor::Visit (const Stmt * S)
Definition at line 3368 of file CIndex.cpp.
                                       {
  VisitorWorkList *WL = nullptr;
  if (!WorkListFreeList.empty()) {
    WL = WorkListFreeList.back();
    WL->clear();
    WorkListFreeList.pop_back();
  } else {
    WL = new VisitorWorkList();
    WorkListCache.push_back(WL);
  }
  EnqueueWorkList(*WL, S);
  bool result = RunVisitorWorkList(*WL);
  WorkListFreeList.push_back(WL);
  return result;
}
Visit() [2/2]
bool CursorVisitor::Visit (CXCursor Cursor, bool CheckedRegionOfInterest = false)
Visit the given cursor and, if requested by the visitor, its children.
Parameters
Cursor the cursor to visit.
CheckedRegionOfInterest if true, then the caller already checked that this cursor is within the region of interest.
Returns
true if the visitation should be aborted, false if it should continue.
Definition at line 194 of file CIndex.cpp.
                                                                       {
  if (clang_isInvalid(Cursor.kind))
    return false;
  if (clang_isDeclaration(Cursor.kind)) {
    const Decl *D = getCursorDecl(Cursor);
    if (!D) {
      assert(0 && "Invalid declaration cursor");
      return true; // abort.
    }
    // Ignore implicit declarations, unless it's an objc method because
    // currently we should report implicit methods for properties when indexing.
    if (D->isImplicit() && !isa<ObjCMethodDecl>(D))
      return false;
  }
  // If we have a range of interest, and this cursor doesn't intersect with it,
  // we're done.
  if (RegionOfInterest.isValid() && !CheckedRegionOfInterest) {
    SourceRange Range = getRawCursorExtent(Cursor);
    if (Range.isInvalid() || CompareRegionOfInterest(Range))
      return false;
  }
  switch (Visitor(Cursor, Parent, ClientData)) {
  case CXChildVisit_Break:
    return true;
  case CXChildVisit_Continue:
    return false;
  case CXChildVisit_Recurse: {
    bool ret = VisitChildren(Cursor);
    if (PostChildrenVisitor)
      if (PostChildrenVisitor(Cursor, ClientData))
        return true;
    return ret;
  }
  }
  llvm_unreachable("Invalid CXChildVisitResult!");
}
VisitArrayTypeLoc()
bool CursorVisitor::VisitArrayTypeLoc (ArrayTypeLoc TL)
Definition at line 1685 of file CIndex.cpp.
                                                     {
  if (Visit(TL.getElementLoc()))
    return true;
  if (Expr *Size = TL.getSizeExpr())
    return Visit(MakeCXCursor(Size, StmtParent, TU, RegionOfInterest));
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitAttributes()
bool CursorVisitor::VisitAttributes (Decl * D)
Definition at line 1836 of file CIndex.cpp.
                                           {
  for (const auto *I : D->attrs())
    if ((TU->ParsingOptions & CXTranslationUnit_VisitImplicitAttributes ||
         !I->isImplicit()) &&
        Visit(MakeCXCursor(I, D, TU)))
      return true;
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitBlockDecl()
bool CursorVisitor::VisitBlockDecl (BlockDecl * B)
Definition at line 591 of file CIndex.cpp.
                                               {
  if (TypeSourceInfo *TSInfo = B->getSignatureAsWritten())
    if (Visit(TSInfo->getTypeLoc()))
      return true;
  if (Stmt *Body = B->getBody())
    return Visit(MakeCXCursor(Body, StmtParent, TU, RegionOfInterest));
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitChildren()
bool CursorVisitor::VisitChildren (CXCursor Cursor)
Visit the children of the given cursor.
Returns
true if the visitation should be aborted, false if it should continue.
Definition at line 492 of file CIndex.cpp.
                                                 {
  if (clang_isReference(Cursor.kind) &&
      Cursor.kind != CXCursor_CXXBaseSpecifier) {
    // By definition, references have no children.
    return false;
  }
  // Set the Parent field to Cursor, then back to its old value once we're
  // done.
  SetParentRAII SetParent(Parent, StmtParent, Cursor);
  if (clang_isDeclaration(Cursor.kind)) {
    Decl *D = const_cast<Decl *>(getCursorDecl(Cursor));
    if (!D)
      return false;
    return VisitAttributes(D) || Visit(D);
  }
  if (clang_isStatement(Cursor.kind)) {
    if (const Stmt *S = getCursorStmt(Cursor))
      return Visit(S);
    return false;
  }
  if (clang_isExpression(Cursor.kind)) {
    if (const Expr *E = getCursorExpr(Cursor))
      return Visit(E);
    return false;
  }
  if (clang_isTranslationUnit(Cursor.kind)) {
    CXTranslationUnit TU = getCursorTU(Cursor);
    ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
    int VisitOrder[2] = {VisitPreprocessorLast, !VisitPreprocessorLast};
    for (unsigned I = 0; I != 2; ++I) {
      if (VisitOrder[I]) {
        if (!CXXUnit->isMainFileAST() && CXXUnit->getOnlyLocalDecls() &&
            RegionOfInterest.isInvalid()) {
          for (ASTUnit::top_level_iterator TL = CXXUnit->top_level_begin(),
                                           TLEnd = CXXUnit->top_level_end();
               TL != TLEnd; ++TL) {
            const Optional<bool> V = handleDeclForVisitation(*TL);
            if (!V.hasValue())
              continue;
            return V.getValue();
          }
        } else if (VisitDeclContext(
                       CXXUnit->getASTContext().getTranslationUnitDecl()))
          return true;
        continue;
      }
      // Walk the preprocessing record.
      if (CXXUnit->getPreprocessor().getPreprocessingRecord())
        visitPreprocessedEntitiesInRegion();
    }
    return false;
  }
  if (Cursor.kind == CXCursor_CXXBaseSpecifier) {
    if (const CXXBaseSpecifier *Base = getCursorCXXBaseSpecifier(Cursor)) {
      if (TypeSourceInfo *BaseTSInfo = Base->getTypeSourceInfo()) {
        return Visit(BaseTSInfo->getTypeLoc());
      }
    }
  }
  if (Cursor.kind == CXCursor_IBOutletCollectionAttr) {
    const IBOutletCollectionAttr *A =
        cast<IBOutletCollectionAttr>(cxcursor::getCursorAttr(Cursor));
    if (const ObjCObjectType *ObjT = A->getInterface()->getAs<ObjCObjectType>())
      return Visit(cxcursor::MakeCursorObjCClassRef(
          ObjT->getInterface(),
          A->getInterfaceLoc()->getTypeLoc().getBeginLoc(), TU));
  }
  // If pointing inside a macro definition, check if the token is an identifier
  // that was ever defined as a macro. In such a case, create a "pseudo" macro
  // expansion cursor for that token.
  SourceLocation BeginLoc = RegionOfInterest.getBegin();
  if (Cursor.kind == CXCursor_MacroDefinition &&
      BeginLoc == RegionOfInterest.getEnd()) {
    SourceLocation Loc = AU->mapLocationToPreamble(BeginLoc);
    const MacroInfo *MI =
        getMacroInfo(cxcursor::getCursorMacroDefinition(Cursor), TU);
    if (MacroDefinitionRecord *MacroDef =
            checkForMacroInMacroDefinition(MI, Loc, TU))
      return Visit(cxcursor::MakeMacroExpansionCursor(MacroDef, BeginLoc, TU));
  }
  // Nothing to visit at the moment.
  return false;
}
Referenced by clang_visitChildren().
VisitClassTemplateDecl()
bool CursorVisitor::VisitClassTemplateDecl (ClassTemplateDecl * D)
Definition at line 950 of file CIndex.cpp.
                                                               {
  // FIXME: Visit the "outer" template parameter lists on the TagDecl
  // before visiting these template parameters.
  if (VisitTemplateParameters(D->getTemplateParameters()))
    return true;
  auto *CD = D->getTemplatedDecl();
  return VisitAttributes(CD) || VisitCXXRecordDecl(CD);
}
VisitClassTemplatePartialSpecializationDecl()
bool CursorVisitor::VisitClassTemplatePartialSpecializationDecl (ClassTemplatePartialSpecializationDecl * D)
Definition at line 745 of file CIndex.cpp.
                                               {
  // FIXME: Visit the "outer" template parameter lists on the TagDecl
  // before visiting these template parameters.
  if (VisitTemplateParameters(D->getTemplateParameters()))
    return true;
  // Visit the partial specialization arguments.
  const ASTTemplateArgumentListInfo *Info = D->getTemplateArgsAsWritten();
  const TemplateArgumentLoc *TemplateArgs = Info->getTemplateArgs();
  for (unsigned I = 0, N = Info->NumTemplateArgs; I != N; ++I)
    if (VisitTemplateArgumentLoc(TemplateArgs[I]))
      return true;
  return VisitCXXRecordDecl(D);
}
VisitClassTemplateSpecializationDecl()
bool CursorVisitor::VisitClassTemplateSpecializationDecl (ClassTemplateSpecializationDecl * D)
Definition at line 713 of file CIndex.cpp.
                                        {
  bool ShouldVisitBody = false;
  switch (D->getSpecializationKind()) {
  case TSK_Undeclared:
  case TSK_ImplicitInstantiation:
    // Nothing to visit
    return false;
  case TSK_ExplicitInstantiationDeclaration:
  case TSK_ExplicitInstantiationDefinition:
    break;
  case TSK_ExplicitSpecialization:
    ShouldVisitBody = true;
    break;
  }
  // Visit the template arguments used in the specialization.
  if (TypeSourceInfo *SpecType = D->getTypeAsWritten()) {
    TypeLoc TL = SpecType->getTypeLoc();
    if (TemplateSpecializationTypeLoc TSTLoc =
            TL.getAs<TemplateSpecializationTypeLoc>()) {
      for (unsigned I = 0, N = TSTLoc.getNumArgs(); I != N; ++I)
        if (VisitTemplateArgumentLoc(TSTLoc.getArgLoc(I)))
          return true;
    }
  }
  return ShouldVisitBody && VisitCXXRecordDecl(D);
}
VisitCXXRecordDecl()
bool CursorVisitor::VisitCXXRecordDecl (CXXRecordDecl * D)
Definition at line 1820 of file CIndex.cpp.
                                                       {
  // Visit the nested-name-specifier, if present.
  if (NestedNameSpecifierLoc QualifierLoc = D->getQualifierLoc())
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  if (D->isCompleteDefinition()) {
    for (const auto &I : D->bases()) {
      if (Visit(cxcursor::MakeCursorCXXBaseSpecifier(&I, TU)))
        return true;
    }
  }
  return VisitTagDecl(D);
}
References clang::cxcursor::MakeCursorCXXBaseSpecifier().
VisitDeclarationNameInfo()
bool CursorVisitor::VisitDeclarationNameInfo (DeclarationNameInfo Name)
Definition at line 1312 of file CIndex.cpp.
                                                                     {
  switch (Name.getName().getNameKind()) {
  case clang::DeclarationName::Identifier:
  case clang::DeclarationName::CXXLiteralOperatorName:
  case clang::DeclarationName::CXXDeductionGuideName:
  case clang::DeclarationName::CXXOperatorName:
  case clang::DeclarationName::CXXUsingDirective:
    return false;
  case clang::DeclarationName::CXXConstructorName:
  case clang::DeclarationName::CXXDestructorName:
  case clang::DeclarationName::CXXConversionFunctionName:
    if (TypeSourceInfo *TSInfo = Name.getNamedTypeInfo())
      return Visit(TSInfo->getTypeLoc());
    return false;
  case clang::DeclarationName::ObjCZeroArgSelector:
  case clang::DeclarationName::ObjCOneArgSelector:
  case clang::DeclarationName::ObjCMultiArgSelector:
    // FIXME: Per-identifier location info?
    return false;
  }
  llvm_unreachable("Invalid DeclarationName::Kind!");
}
VisitDeclaratorDecl()
bool CursorVisitor::VisitDeclaratorDecl (DeclaratorDecl * DD)
Definition at line 783 of file CIndex.cpp.
                                                          {
  unsigned NumParamList = DD->getNumTemplateParameterLists();
  for (unsigned i = 0; i < NumParamList; i++) {
    TemplateParameterList *Params = DD->getTemplateParameterList(i);
    if (VisitTemplateParameters(Params))
      return true;
  }
  if (TypeSourceInfo *TSInfo = DD->getTypeSourceInfo())
    if (Visit(TSInfo->getTypeLoc()))
      return true;
  // Visit the nested-name-specifier, if present.
  if (NestedNameSpecifierLoc QualifierLoc = DD->getQualifierLoc())
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  return false;
}
VisitDeclContext()
bool CursorVisitor::VisitDeclContext (DeclContext * DC)
Definition at line 625 of file CIndex.cpp.
                                                    {
  DeclContext::decl_iterator I = DC->decls_begin(), E = DC->decls_end();
  // FIXME: Eventually remove. This part of a hack to support proper
  // iteration over all Decls contained lexically within an ObjC container.
  SaveAndRestore<DeclContext::decl_iterator *> DI_saved(DI_current, &I);
  SaveAndRestore<DeclContext::decl_iterator> DE_saved(DE_current, E);
  for (; I != E; ++I) {
    Decl *D = *I;
    if (D->getLexicalDeclContext() != DC)
      continue;
    // Filter out synthesized property accessor redeclarations.
    if (isa<ObjCImplDecl>(DC))
      if (auto *OMD = dyn_cast<ObjCMethodDecl>(D))
        if (OMD->isSynthesizedAccessorStub())
          continue;
    const Optional<bool> V = handleDeclForVisitation(D);
    if (!V.hasValue())
      continue;
    return V.getValue();
  }
  return false;
}
VisitDecompositionDecl()
bool CursorVisitor::VisitDecompositionDecl (DecompositionDecl * D)
Definition at line 1304 of file CIndex.cpp.
                                                               {
  for (auto *B : D->bindings()) {
    if (Visit(MakeCXCursor(B, TU, RegionOfInterest)))
      return true;
  }
  return VisitVarDecl(D);
}
References clang::cxcursor::MakeCXCursor().
VisitEnumConstantDecl()
bool CursorVisitor::VisitEnumConstantDecl (EnumConstantDecl * D)
Definition at line 777 of file CIndex.cpp.
                                                             {
  if (Expr *Init = D->getInitExpr())
    return Visit(MakeCXCursor(Init, StmtParent, TU, RegionOfInterest));
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitFieldDecl()
bool CursorVisitor::VisitFieldDecl (FieldDecl * D)
Definition at line 906 of file CIndex.cpp.
                                               {
  if (VisitDeclaratorDecl(D))
    return true;
  if (Expr *BitWidth = D->getBitWidth())
    return Visit(MakeCXCursor(BitWidth, StmtParent, TU, RegionOfInterest));
  if (Expr *Init = D->getInClassInitializer())
    return Visit(MakeCXCursor(Init, StmtParent, TU, RegionOfInterest));
  return false;
}
References clang::cxcursor::MakeCXCursor().
visitFileRegion()
bool CursorVisitor::visitFileRegion ()
Visit declarations and preprocessed entities for the file region designated by
See also
RegionOfInterest.
Definition at line 258 of file CIndex.cpp.
                                    {
  if (RegionOfInterest.isInvalid())
    return false;
  ASTUnit *Unit = cxtu::getASTUnit(TU);
  SourceManager &SM = Unit->getSourceManager();
  std::pair<FileID, unsigned> Begin = SM.getDecomposedLoc(
                                  SM.getFileLoc(RegionOfInterest.getBegin())),
                              End = SM.getDecomposedLoc(
                                  SM.getFileLoc(RegionOfInterest.getEnd()));
  if (End.first != Begin.first) {
    // If the end does not reside in the same file, try to recover by
    // picking the end of the file of begin location.
    End.first = Begin.first;
    End.second = SM.getFileIDSize(Begin.first);
  }
  assert(Begin.first == End.first);
  if (Begin.second > End.second)
    return false;
  FileID File = Begin.first;
  unsigned Offset = Begin.second;
  unsigned Length = End.second - Begin.second;
  if (!VisitDeclsOnly && !VisitPreprocessorLast)
    if (visitPreprocessedEntitiesInRegion())
      return true; // visitation break.
  if (visitDeclsFromFileRegion(File, Offset, Length))
    return true; // visitation break.
  if (!VisitDeclsOnly && VisitPreprocessorLast)
    return visitPreprocessedEntitiesInRegion();
  return false;
}
VisitFriendDecl()
bool CursorVisitor::VisitFriendDecl (FriendDecl * D)
Definition at line 1293 of file CIndex.cpp.
                                                 {
  if (NamedDecl *FriendD = D->getFriendDecl()) {
    if (Visit(MakeCXCursor(FriendD, TU, RegionOfInterest)))
      return true;
  } else if (TypeSourceInfo *TI = D->getFriendType()) {
    if (Visit(TI->getTypeLoc()))
      return true;
  }
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitFunctionDecl()
bool CursorVisitor::VisitFunctionDecl (FunctionDecl * ND)
Definition at line 819 of file CIndex.cpp.
                                                      {
  unsigned NumParamList = ND->getNumTemplateParameterLists();
  for (unsigned i = 0; i < NumParamList; i++) {
    TemplateParameterList *Params = ND->getTemplateParameterList(i);
    if (VisitTemplateParameters(Params))
      return true;
  }
  if (TypeSourceInfo *TSInfo = ND->getTypeSourceInfo()) {
    // Visit the function declaration's syntactic components in the order
    // written. This requires a bit of work.
    TypeLoc TL = TSInfo->getTypeLoc().IgnoreParens();
    FunctionTypeLoc FTL = TL.getAs<FunctionTypeLoc>();
    const bool HasTrailingRT = HasTrailingReturnType(ND);
    // If we have a function declared directly (without the use of a typedef),
    // visit just the return type. Otherwise, just visit the function's type
    // now.
    if ((FTL && !isa<CXXConversionDecl>(ND) && !HasTrailingRT &&
         Visit(FTL.getReturnLoc())) ||
        (!FTL && Visit(TL)))
      return true;
    // Visit the nested-name-specifier, if present.
    if (NestedNameSpecifierLoc QualifierLoc = ND->getQualifierLoc())
      if (VisitNestedNameSpecifierLoc(QualifierLoc))
        return true;
    // Visit the declaration name.
    if (!isa<CXXDestructorDecl>(ND))
      if (VisitDeclarationNameInfo(ND->getNameInfo()))
        return true;
    // FIXME: Visit explicitly-specified template arguments!
    // Visit the function parameters, if we have a function type.
    if (FTL && VisitFunctionTypeLoc(FTL, true))
      return true;
    // Visit the function's trailing return type.
    if (FTL && HasTrailingRT && Visit(FTL.getReturnLoc()))
      return true;
    // FIXME: Attributes?
  }
  if (ND->doesThisDeclarationHaveABody() && !ND->isLateTemplateParsed()) {
    if (CXXConstructorDecl *Constructor = dyn_cast<CXXConstructorDecl>(ND)) {
      // Find the initializers that were written in the source.
      SmallVector<CXXCtorInitializer *, 4> WrittenInits;
      for (auto *I : Constructor->inits()) {
        if (!I->isWritten())
          continue;
        WrittenInits.push_back(I);
      }
      // Sort the initializers in source order
      llvm::array_pod_sort(WrittenInits.begin(), WrittenInits.end(),
                           &CompareCXXCtorInitializers);
      // Visit the initializers in source order
      for (unsigned I = 0, N = WrittenInits.size(); I != N; ++I) {
        CXXCtorInitializer *Init = WrittenInits[I];
        if (Init->isAnyMemberInitializer()) {
          if (Visit(MakeCursorMemberRef(Init->getAnyMember(),
                                        Init->getMemberLocation(), TU)))
            return true;
        } else if (TypeSourceInfo *TInfo = Init->getTypeSourceInfo()) {
          if (Visit(TInfo->getTypeLoc()))
            return true;
        }
        // Visit the initializer value.
        if (Expr *Initializer = Init->getInit())
          if (Visit(MakeCXCursor(Initializer, ND, TU, RegionOfInterest)))
            return true;
      }
    }
    if (Visit(MakeCXCursor(ND->getBody(), StmtParent, TU, RegionOfInterest)))
      return true;
  }
  return false;
}
VisitFunctionTemplateDecl()
bool CursorVisitor::VisitFunctionTemplateDecl (FunctionTemplateDecl * D)
Definition at line 940 of file CIndex.cpp.
                                                                     {
  // FIXME: Visit the "outer" template parameter lists on the FunctionDecl
  // before visiting these template parameters.
  if (VisitTemplateParameters(D->getTemplateParameters()))
    return true;
  auto *FD = D->getTemplatedDecl();
  return VisitAttributes(FD) || VisitFunctionDecl(FD);
}
VisitFunctionTypeLoc()
bool CursorVisitor::VisitFunctionTypeLoc (FunctionTypeLoc TL, bool SkipResultType = false)
Definition at line 1672 of file CIndex.cpp.
                                                              {
  if (!SkipResultType && Visit(TL.getReturnLoc()))
    return true;
  for (unsigned I = 0, N = TL.getNumParams(); I != N; ++I)
    if (Decl *D = TL.getParam(I))
      if (Visit(MakeCXCursor(D, TU, RegionOfInterest)))
        return true;
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitLinkageSpecDecl()
bool CursorVisitor::VisitLinkageSpecDecl (LinkageSpecDecl * D)
Definition at line 1518 of file CIndex.cpp.
                                                           {
  return VisitDeclContext(D);
}
VisitNamespaceAliasDecl()
bool CursorVisitor::VisitNamespaceAliasDecl (NamespaceAliasDecl * D)
Definition at line 1231 of file CIndex.cpp.
                                                                 {
  // Visit nested-name-specifier.
  if (NestedNameSpecifierLoc QualifierLoc = D->getQualifierLoc())
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  return Visit(MakeCursorNamespaceRef(D->getAliasedNamespace(),
                                      D->getTargetNameLoc(), TU));
}
References clang::cxcursor::MakeCursorNamespaceRef().
VisitNamespaceDecl()
bool CursorVisitor::VisitNamespaceDecl (NamespaceDecl * D)
Definition at line 1227 of file CIndex.cpp.
                                                       {
  return VisitDeclContext(D);
}
VisitNestedNameSpecifier()
bool CursorVisitor::VisitNestedNameSpecifier (NestedNameSpecifier * NNS, SourceRange Range)
Definition at line 1338 of file CIndex.cpp.
                                                                {
  // FIXME: This whole routine is a hack to work around the lack of proper
  // source information in nested-name-specifiers (PR5791). Since we do have
  // a beginning source location, we can visit the first component of the
  // nested-name-specifier, if it's a single-token component.
  if (!NNS)
    return false;
  // Get the first component in the nested-name-specifier.
  while (NestedNameSpecifier *Prefix = NNS->getPrefix())
    NNS = Prefix;
  switch (NNS->getKind()) {
  case NestedNameSpecifier::Namespace:
    return Visit(
        MakeCursorNamespaceRef(NNS->getAsNamespace(), Range.getBegin(), TU));
  case NestedNameSpecifier::NamespaceAlias:
    return Visit(MakeCursorNamespaceRef(NNS->getAsNamespaceAlias(),
                                        Range.getBegin(), TU));
  case NestedNameSpecifier::TypeSpec: {
    // If the type has a form where we know that the beginning of the source
    // range matches up with a reference cursor. Visit the appropriate reference
    // cursor.
    const Type *T = NNS->getAsType();
    if (const TypedefType *Typedef = dyn_cast<TypedefType>(T))
      return Visit(MakeCursorTypeRef(Typedef->getDecl(), Range.getBegin(), TU));
    if (const TagType *Tag = dyn_cast<TagType>(T))
      return Visit(MakeCursorTypeRef(Tag->getDecl(), Range.getBegin(), TU));
    if (const TemplateSpecializationType *TST =
            dyn_cast<TemplateSpecializationType>(T))
      return VisitTemplateName(TST->getTemplateName(), Range.getBegin());
    break;
  }
  case NestedNameSpecifier::TypeSpecWithTemplate:
  case NestedNameSpecifier::Global:
  case NestedNameSpecifier::Identifier:
  case NestedNameSpecifier::Super:
    break;
  }
  return false;
}
References clang::cxcursor::MakeCursorNamespaceRef(), and clang::cxcursor::MakeCursorTypeRef().
VisitNestedNameSpecifierLoc()
bool CursorVisitor::VisitNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Definition at line 1385 of file CIndex.cpp.
                                      {
  SmallVector<NestedNameSpecifierLoc, 4> Qualifiers;
  for (; Qualifier; Qualifier = Qualifier.getPrefix())
    Qualifiers.push_back(Qualifier);
  while (!Qualifiers.empty()) {
    NestedNameSpecifierLoc Q = Qualifiers.pop_back_val();
    NestedNameSpecifier *NNS = Q.getNestedNameSpecifier();
    switch (NNS->getKind()) {
    case NestedNameSpecifier::Namespace:
      if (Visit(MakeCursorNamespaceRef(NNS->getAsNamespace(),
                                       Q.getLocalBeginLoc(), TU)))
        return true;
      break;
    case NestedNameSpecifier::NamespaceAlias:
      if (Visit(MakeCursorNamespaceRef(NNS->getAsNamespaceAlias(),
                                       Q.getLocalBeginLoc(), TU)))
        return true;
      break;
    case NestedNameSpecifier::TypeSpec:
    case NestedNameSpecifier::TypeSpecWithTemplate:
      if (Visit(Q.getTypeLoc()))
        return true;
      break;
    case NestedNameSpecifier::Global:
    case NestedNameSpecifier::Identifier:
    case NestedNameSpecifier::Super:
      break;
    }
  }
  return false;
}
References clang::cxcursor::MakeCursorNamespaceRef().
VisitNonTypeTemplateParmDecl()
bool CursorVisitor::VisitNonTypeTemplateParmDecl (NonTypeTemplateParmDecl * D)
Definition at line 929 of file CIndex.cpp.
                                                                           {
  if (VisitDeclaratorDecl(D))
    return true;
  if (D->hasDefaultArgument() && !D->defaultArgumentWasInherited())
    if (Expr *DefArg = D->getDefaultArgument())
      return Visit(MakeCXCursor(DefArg, StmtParent, TU, RegionOfInterest));
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitObjCCategoryDecl()
bool CursorVisitor::VisitObjCCategoryDecl (ObjCCategoryDecl * ND)
Definition at line 1081 of file CIndex.cpp.
                                                              {
  if (Visit(MakeCursorObjCClassRef(ND->getClassInterface(), ND->getLocation(),
                                   TU)))
    return true;
  if (VisitObjCTypeParamList(ND->getTypeParamList()))
    return true;
  ObjCCategoryDecl::protocol_loc_iterator PL = ND->protocol_loc_begin();
  for (ObjCCategoryDecl::protocol_iterator I = ND->protocol_begin(),
                                           E = ND->protocol_end();
       I != E; ++I, ++PL)
    if (Visit(MakeCursorObjCProtocolRef(*I, *PL, TU)))
      return true;
  return VisitObjCContainerDecl(ND);
}
References clang::cxcursor::MakeCursorObjCClassRef(), and clang::cxcursor::MakeCursorObjCProtocolRef().
VisitObjCCategoryImplDecl()
bool CursorVisitor::VisitObjCCategoryImplDecl (ObjCCategoryImplDecl * D)
Definition at line 1196 of file CIndex.cpp.
                                                                     {
  // 'ID' could be null when dealing with invalid code.
  if (ObjCInterfaceDecl *ID = D->getClassInterface())
    if (Visit(MakeCursorObjCClassRef(ID, D->getLocation(), TU)))
      return true;
  return VisitObjCImplDecl(D);
}
References clang::cxcursor::MakeCursorObjCClassRef().
VisitObjCContainerDecl()
bool CursorVisitor::VisitObjCContainerDecl (ObjCContainerDecl * D)
Definition at line 1018 of file CIndex.cpp.
                                                               {
  // FIXME: Eventually convert back to just 'VisitDeclContext()'. Essentially
  // an @implementation can lexically contain Decls that are not properly
  // nested in the AST. When we identify such cases, we need to retrofit
  // this nesting here.
  if (!DI_current && !FileDI_current)
    return VisitDeclContext(D);
  // Scan the Decls that immediately come after the container
  // in the current DeclContext. If any fall within the
  // container's lexical region, stash them into a vector
  // for later processing.
  SmallVector<Decl *, 24> DeclsInContainer;
  SourceLocation EndLoc = D->getSourceRange().getEnd();
  SourceManager &SM = AU->getSourceManager();
  if (EndLoc.isValid()) {
    if (DI_current) {
      addRangedDeclsInContainer(DI_current, DE_current, SM, EndLoc,
                                DeclsInContainer);
    } else {
      addRangedDeclsInContainer(FileDI_current, FileDE_current, SM, EndLoc,
                                DeclsInContainer);
    }
  }
  // The common case.
  if (DeclsInContainer.empty())
    return VisitDeclContext(D);
  // Get all the Decls in the DeclContext, and sort them with the
  // additional ones we've collected. Then visit them.
  for (auto *SubDecl : D->decls()) {
    if (!SubDecl || SubDecl->getLexicalDeclContext() != D ||
        SubDecl->getBeginLoc().isInvalid())
      continue;
    DeclsInContainer.push_back(SubDecl);
  }
  // Now sort the Decls so that they appear in lexical order.
  llvm::sort(DeclsInContainer, [&SM](Decl *A, Decl *B) {
    SourceLocation L_A = A->getBeginLoc();
    SourceLocation L_B = B->getBeginLoc();
    return L_A != L_B
               ? SM.isBeforeInTranslationUnit(L_A, L_B)
               : SM.isBeforeInTranslationUnit(A->getEndLoc(), B->getEndLoc());
  });
  // Now visit the decls.
  for (SmallVectorImpl<Decl *>::iterator I = DeclsInContainer.begin(),
                                         E = DeclsInContainer.end();
       I != E; ++I) {
    CXCursor Cursor = MakeCXCursor(*I, TU, RegionOfInterest);
    const Optional<bool> &V = shouldVisitCursor(Cursor);
    if (!V.hasValue())
      continue;
    if (!V.getValue())
      return false;
    if (Visit(Cursor, true))
      return true;
  }
  return false;
}
VisitObjCImplDecl()
bool CursorVisitor::VisitObjCImplDecl (ObjCImplDecl * D)
Definition at line 1192 of file CIndex.cpp.
                                                     {
  return VisitObjCContainerDecl(D);
}
VisitObjCImplementationDecl()
bool CursorVisitor::VisitObjCImplementationDecl (ObjCImplementationDecl * D)
Definition at line 1205 of file CIndex.cpp.
                                                                         {
#if 0
  // Issue callbacks for super class.
  // FIXME: No source location information!
  if (D->getSuperClass() &&
      Visit(MakeCursorObjCSuperClassRef(D->getSuperClass(),
                                        D->getSuperClassLoc(),
                                        TU)))
    return true;
#endif
  return VisitObjCImplDecl(D);
}
References clang::cxcursor::MakeCursorObjCSuperClassRef().
VisitObjCInterfaceDecl()
bool CursorVisitor::VisitObjCInterfaceDecl (ObjCInterfaceDecl * D)
Definition at line 1163 of file CIndex.cpp.
                                                               {
  if (!D->isThisDeclarationADefinition()) {
    // Forward declaration is treated like a reference.
    return Visit(MakeCursorObjCClassRef(D, D->getLocation(), TU));
  }
  // Objective-C type parameters.
  if (VisitObjCTypeParamList(D->getTypeParamListAsWritten()))
    return true;
  // Issue callbacks for super class.
  if (D->getSuperClass() && Visit(MakeCursorObjCSuperClassRef(
                                D->getSuperClass(), D->getSuperClassLoc(), TU)))
    return true;
  if (TypeSourceInfo *SuperClassTInfo = D->getSuperClassTInfo())
    if (Visit(SuperClassTInfo->getTypeLoc()))
      return true;
  ObjCInterfaceDecl::protocol_loc_iterator PL = D->protocol_loc_begin();
  for (ObjCInterfaceDecl::protocol_iterator I = D->protocol_begin(),
                                            E = D->protocol_end();
       I != E; ++I, ++PL)
    if (Visit(MakeCursorObjCProtocolRef(*I, *PL, TU)))
      return true;
  return VisitObjCContainerDecl(D);
}
References clang::cxcursor::MakeCursorObjCClassRef(), clang::cxcursor::MakeCursorObjCProtocolRef(), and clang::cxcursor::MakeCursorObjCSuperClassRef().
VisitObjCMethodDecl()
bool CursorVisitor::VisitObjCMethodDecl (ObjCMethodDecl * ND)
Definition at line 983 of file CIndex.cpp.
                                                          {
  if (TypeSourceInfo *TSInfo = ND->getReturnTypeSourceInfo())
    if (Visit(TSInfo->getTypeLoc()))
      return true;
  for (const auto *P : ND->parameters()) {
    if (Visit(MakeCXCursor(P, TU, RegionOfInterest)))
      return true;
  }
  return ND->isThisDeclarationADefinition() &&
         Visit(MakeCXCursor(ND->getBody(), StmtParent, TU, RegionOfInterest));
}
References clang::cxcursor::MakeCXCursor().
VisitObjCPropertyDecl()
bool CursorVisitor::VisitObjCPropertyDecl (ObjCPropertyDecl * PD)
Definition at line 1113 of file CIndex.cpp.
                                                              {
  if (PD->getTypeSourceInfo() && Visit(PD->getTypeSourceInfo()->getTypeLoc()))
    return true;
  // FIXME: This implements a workaround with @property declarations also being
  // installed in the DeclContext for the @interface. Eventually this code
  // should be removed.
  ObjCCategoryDecl *CDecl = dyn_cast<ObjCCategoryDecl>(PD->getDeclContext());
  if (!CDecl || !CDecl->IsClassExtension())
    return false;
  ObjCInterfaceDecl *ID = CDecl->getClassInterface();
  if (!ID)
    return false;
  IdentifierInfo *PropertyId = PD->getIdentifier();
  ObjCPropertyDecl *prevDecl = ObjCPropertyDecl::findPropertyDecl(
      cast<DeclContext>(ID), PropertyId, PD->getQueryKind());
  if (!prevDecl)
    return false;
  // Visit synthesized methods since they will be skipped when visiting
  // the @interface.
  if (ObjCMethodDecl *MD = prevDecl->getGetterMethodDecl())
    if (MD->isPropertyAccessor() && MD->getLexicalDeclContext() == CDecl)
      if (Visit(MakeCXCursor(MD, TU, RegionOfInterest)))
        return true;
  if (ObjCMethodDecl *MD = prevDecl->getSetterMethodDecl())
    if (MD->isPropertyAccessor() && MD->getLexicalDeclContext() == CDecl)
      if (Visit(MakeCXCursor(MD, TU, RegionOfInterest)))
        return true;
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitObjCPropertyImplDecl()
bool CursorVisitor::VisitObjCPropertyImplDecl (ObjCPropertyImplDecl * PD)
Definition at line 1219 of file CIndex.cpp.
                                                                      {
  if (ObjCIvarDecl *Ivar = PD->getPropertyIvarDecl())
    if (PD->isIvarNameSpecified())
      return Visit(MakeCursorMemberRef(Ivar, PD->getPropertyIvarDeclLoc(), TU));
  return false;
}
References clang::cxcursor::MakeCursorMemberRef().
VisitObjCProtocolDecl()
bool CursorVisitor::VisitObjCProtocolDecl (ObjCProtocolDecl * PID)
Definition at line 1099 of file CIndex.cpp.
                                                               {
  if (!PID->isThisDeclarationADefinition())
    return Visit(MakeCursorObjCProtocolRef(PID, PID->getLocation(), TU));
  ObjCProtocolDecl::protocol_loc_iterator PL = PID->protocol_loc_begin();
  for (ObjCProtocolDecl::protocol_iterator I = PID->protocol_begin(),
                                           E = PID->protocol_end();
       I != E; ++I, ++PL)
    if (Visit(MakeCursorObjCProtocolRef(*I, *PL, TU)))
      return true;
  return VisitObjCContainerDecl(PID);
}
References clang::cxcursor::MakeCursorObjCProtocolRef().
VisitObjCTypeParamDecl()
bool CursorVisitor::VisitObjCTypeParamDecl (ObjCTypeParamDecl * D)
Definition at line 971 of file CIndex.cpp.
                                                               {
  // Visit the bound, if it's explicit.
  if (D->hasExplicitBound()) {
    if (auto TInfo = D->getTypeSourceInfo()) {
      if (Visit(TInfo->getTypeLoc()))
        return true;
    }
  }
  return false;
}
VisitObjCTypeParamList()
bool CursorVisitor::VisitObjCTypeParamList (ObjCTypeParamList * typeParamList)
Definition at line 1150 of file CIndex.cpp.
                                                                           {
  if (!typeParamList)
    return false;
  for (auto *typeParam : *typeParamList) {
    // Visit the type parameter.
    if (Visit(MakeCXCursor(typeParam, TU, RegionOfInterest)))
      return true;
  }
  return false;
}
References clang::cxcursor::MakeCXCursor().
visitPreprocessedEntities()
template<typename InputIterator >
bool CursorVisitor::visitPreprocessedEntities (InputIterator First, InputIterator Last, PreprocessingRecord & PPRec, FileID FID = FileID())
Definition at line 451 of file CIndex.cpp.
                                                          {
  for (; First != Last; ++First) {
    if (!FID.isInvalid() && !PPRec.isEntityInFileID(First, FID))
      continue;
    PreprocessedEntity *PPE = *First;
    if (!PPE)
      continue;
    if (MacroExpansion *ME = dyn_cast<MacroExpansion>(PPE)) {
      if (Visit(MakeMacroExpansionCursor(ME, TU)))
        return true;
      continue;
    }
    if (MacroDefinitionRecord *MD = dyn_cast<MacroDefinitionRecord>(PPE)) {
      if (Visit(MakeMacroDefinitionCursor(MD, TU)))
        return true;
      continue;
    }
    if (InclusionDirective *ID = dyn_cast<InclusionDirective>(PPE)) {
      if (Visit(MakeInclusionDirectiveCursor(ID, TU)))
        return true;
      continue;
    }
  }
  return false;
}
References clang::cxcursor::MakeInclusionDirectiveCursor(), clang::cxcursor::MakeMacroDefinitionCursor(), and clang::cxcursor::MakeMacroExpansionCursor().
visitPreprocessedEntitiesInRegion()
bool CursorVisitor::visitPreprocessedEntitiesInRegion ()
Definition at line 407 of file CIndex.cpp.
                                                      {
  if (!AU->getPreprocessor().getPreprocessingRecord())
    return false;
  PreprocessingRecord &PPRec = *AU->getPreprocessor().getPreprocessingRecord();
  SourceManager &SM = AU->getSourceManager();
  if (RegionOfInterest.isValid()) {
    SourceRange MappedRange = AU->mapRangeToPreamble(RegionOfInterest);
    SourceLocation B = MappedRange.getBegin();
    SourceLocation E = MappedRange.getEnd();
    if (AU->isInPreambleFileID(B)) {
      if (SM.isLoadedSourceLocation(E))
        return visitPreprocessedEntitiesInRange(SourceRange(B, E), PPRec,
                                                *this);
      // Beginning of range lies in the preamble but it also extends beyond
      // it into the main file. Split the range into 2 parts, one covering
      // the preamble and another covering the main file. This allows subsequent
      // calls to visitPreprocessedEntitiesInRange to accept a source range that
      // lies in the same FileID, allowing it to skip preprocessed entities that
      // do not come from the same FileID.
      bool breaked = visitPreprocessedEntitiesInRange(
          SourceRange(B, AU->getEndOfPreambleFileID()), PPRec, *this);
      if (breaked)
        return true;
      return visitPreprocessedEntitiesInRange(
          SourceRange(AU->getStartOfMainFileID(), E), PPRec, *this);
    }
    return visitPreprocessedEntitiesInRange(SourceRange(B, E), PPRec, *this);
  }
  bool OnlyLocalDecls = !AU->isMainFileAST() && AU->getOnlyLocalDecls();
  if (OnlyLocalDecls)
    return visitPreprocessedEntities(PPRec.local_begin(), PPRec.local_end(),
                                     PPRec);
  return visitPreprocessedEntities(PPRec.begin(), PPRec.end(), PPRec);
}
VisitStaticAssertDecl()
bool CursorVisitor::VisitStaticAssertDecl (StaticAssertDecl * D)
Definition at line 1284 of file CIndex.cpp.
                                                             {
  if (Visit(MakeCXCursor(D->getAssertExpr(), StmtParent, TU, RegionOfInterest)))
    return true;
  if (StringLiteral *Message = D->getMessage())
    if (Visit(MakeCXCursor(Message, StmtParent, TU, RegionOfInterest)))
      return true;
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitTagDecl()
bool CursorVisitor::VisitTagDecl (TagDecl * D)
Definition at line 711 of file CIndex.cpp.
{ return VisitDeclContext(D); }
VisitTagTypeLoc()
bool CursorVisitor::VisitTagTypeLoc (TagTypeLoc TL)
Definition at line 1591 of file CIndex.cpp.
                                                 {
  if (TL.isDefinition())
    return Visit(MakeCXCursor(TL.getDecl(), TU, RegionOfInterest));
  return Visit(MakeCursorTypeRef(TL.getDecl(), TL.getNameLoc(), TU));
}
References clang::cxcursor::MakeCursorTypeRef(), and clang::cxcursor::MakeCXCursor().
VisitTemplateArgumentLoc()
bool CursorVisitor::VisitTemplateArgumentLoc (const TemplateArgumentLoc & TAL)
Definition at line 1479 of file CIndex.cpp.
                                                                           {
  switch (TAL.getArgument().getKind()) {
  case TemplateArgument::Null:
  case TemplateArgument::Integral:
  case TemplateArgument::Pack:
    return false;
  case TemplateArgument::Type:
    if (TypeSourceInfo *TSInfo = TAL.getTypeSourceInfo())
      return Visit(TSInfo->getTypeLoc());
    return false;
  case TemplateArgument::Declaration:
    if (Expr *E = TAL.getSourceDeclExpression())
      return Visit(MakeCXCursor(E, StmtParent, TU, RegionOfInterest));
    return false;
  case TemplateArgument::NullPtr:
    if (Expr *E = TAL.getSourceNullPtrExpression())
      return Visit(MakeCXCursor(E, StmtParent, TU, RegionOfInterest));
    return false;
  case TemplateArgument::Expression:
    if (Expr *E = TAL.getSourceExpression())
      return Visit(MakeCXCursor(E, StmtParent, TU, RegionOfInterest));
    return false;
  case TemplateArgument::Template:
  case TemplateArgument::TemplateExpansion:
    if (VisitNestedNameSpecifierLoc(TAL.getTemplateQualifierLoc()))
      return true;
    return VisitTemplateName(TAL.getArgument().getAsTemplateOrTemplatePattern(),
                             TAL.getTemplateNameLoc());
  }
  llvm_unreachable("Invalid TemplateArgument::Kind!");
}
References clang::cxcursor::MakeCXCursor().
VisitTemplateName()
bool CursorVisitor::VisitTemplateName (TemplateName Name, SourceLocation Loc)
Definition at line 1441 of file CIndex.cpp.
                                                                           {
  switch (Name.getKind()) {
  case TemplateName::Template:
    return Visit(MakeCursorTemplateRef(Name.getAsTemplateDecl(), Loc, TU));
  case TemplateName::OverloadedTemplate:
    // Visit the overloaded template set.
    if (Visit(MakeCursorOverloadedDeclRef(Name, Loc, TU)))
      return true;
    return false;
  case TemplateName::AssumedTemplate:
    // FIXME: Visit DeclarationName?
    return false;
  case TemplateName::DependentTemplate:
    // FIXME: Visit nested-name-specifier.
    return false;
  case TemplateName::QualifiedTemplate:
    // FIXME: Visit nested-name-specifier.
    return Visit(MakeCursorTemplateRef(
        Name.getAsQualifiedTemplateName()->getDecl(), Loc, TU));
  case TemplateName::SubstTemplateTemplateParm:
    return Visit(MakeCursorTemplateRef(
        Name.getAsSubstTemplateTemplateParm()->getParameter(), Loc, TU));
  case TemplateName::SubstTemplateTemplateParmPack:
    return Visit(MakeCursorTemplateRef(
        Name.getAsSubstTemplateTemplateParmPack()->getParameterPack(), Loc,
        TU));
  }
  llvm_unreachable("Invalid TemplateName::Kind!");
}
References clang::cxcursor::MakeCursorOverloadedDeclRef(), and clang::cxcursor::MakeCursorTemplateRef().
VisitTemplateParameters()
bool CursorVisitor::VisitTemplateParameters (const TemplateParameterList * Params)
Definition at line 1426 of file CIndex.cpp.
                                         {
  if (!Params)
    return false;
  for (TemplateParameterList::const_iterator P = Params->begin(),
                                             PEnd = Params->end();
       P != PEnd; ++P) {
    if (Visit(MakeCXCursor(*P, TU, RegionOfInterest)))
      return true;
  }
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitTemplateTemplateParmDecl()
bool CursorVisitor::VisitTemplateTemplateParmDecl (TemplateTemplateParmDecl * D)
Definition at line 960 of file CIndex.cpp.
                                                                             {
  if (VisitTemplateParameters(D->getTemplateParameters()))
    return true;
  if (D->hasDefaultArgument() && !D->defaultArgumentWasInherited() &&
      VisitTemplateArgumentLoc(D->getDefaultArgument()))
    return true;
  return false;
}
VisitTemplateTypeParmDecl()
bool CursorVisitor::VisitTemplateTypeParmDecl (TemplateTypeParmDecl * D)
Definition at line 762 of file CIndex.cpp.
                                                                     {
  if (const auto *TC = D->getTypeConstraint())
    if (Visit(MakeCXCursor(TC->getImmediatelyDeclaredConstraint(), StmtParent,
                           TU, RegionOfInterest)))
      return true;
  // Visit the default argument.
  if (D->hasDefaultArgument() && !D->defaultArgumentWasInherited())
    if (TypeSourceInfo *DefArg = D->getDefaultArgumentInfo())
      if (Visit(DefArg->getTypeLoc()))
        return true;
  return false;
}
References clang::cxcursor::MakeCXCursor().
VisitTranslationUnitDecl()
bool CursorVisitor::VisitTranslationUnitDecl (TranslationUnitDecl * D)
Definition at line 686 of file CIndex.cpp.
                                                                   {
  llvm_unreachable("Translation units are visited directly by Visit()");
}
VisitTypeAliasDecl()
bool CursorVisitor::VisitTypeAliasDecl (TypeAliasDecl * D)
Definition at line 697 of file CIndex.cpp.
                                                       {
  if (TypeSourceInfo *TSInfo = D->getTypeSourceInfo())
    return Visit(TSInfo->getTypeLoc());
  return false;
}
VisitTypeAliasTemplateDecl()
bool CursorVisitor::VisitTypeAliasTemplateDecl (TypeAliasTemplateDecl * D)
Definition at line 690 of file CIndex.cpp.
                                                                       {
  if (VisitTemplateParameters(D->getTemplateParameters()))
    return true;
  return Visit(MakeCXCursor(D->getTemplatedDecl(), TU, RegionOfInterest));
}
References clang::cxcursor::MakeCXCursor().
VisitTypedefDecl()
bool CursorVisitor::VisitTypedefDecl (TypedefDecl * D)
Definition at line 704 of file CIndex.cpp.
                                                   {
  if (TypeSourceInfo *TSInfo = D->getTypeSourceInfo())
    return Visit(TSInfo->getTypeLoc());
  return false;
}
VisitUnresolvedUsingTypenameDecl()
bool CursorVisitor::VisitUnresolvedUsingTypenameDecl (UnresolvedUsingTypenameDecl * D)
Definition at line 1274 of file CIndex.cpp.
                                    {
  // Visit nested-name-specifier.
  if (NestedNameSpecifierLoc QualifierLoc = D->getQualifierLoc())
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  return false;
}
VisitUnresolvedUsingValueDecl()
bool CursorVisitor::VisitUnresolvedUsingValueDecl (UnresolvedUsingValueDecl * D)
Definition at line 1264 of file CIndex.cpp.
                                                                             {
  // Visit nested-name-specifier.
  if (NestedNameSpecifierLoc QualifierLoc = D->getQualifierLoc()) {
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  }
  return VisitDeclarationNameInfo(D->getNameInfo());
}
VisitUsingDecl()
bool CursorVisitor::VisitUsingDecl (UsingDecl * D)
Definition at line 1241 of file CIndex.cpp.
                                               {
  // Visit nested-name-specifier.
  if (NestedNameSpecifierLoc QualifierLoc = D->getQualifierLoc()) {
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  }
  if (Visit(MakeCursorOverloadedDeclRef(D, D->getLocation(), TU)))
    return true;
  return VisitDeclarationNameInfo(D->getNameInfo());
}
References clang::cxcursor::MakeCursorOverloadedDeclRef().
VisitUsingDirectiveDecl()
bool CursorVisitor::VisitUsingDirectiveDecl (UsingDirectiveDecl * D)
Definition at line 1254 of file CIndex.cpp.
                                                                 {
  // Visit nested-name-specifier.
  if (NestedNameSpecifierLoc QualifierLoc = D->getQualifierLoc())
    if (VisitNestedNameSpecifierLoc(QualifierLoc))
      return true;
  return Visit(MakeCursorNamespaceRef(D->getNominatedNamespaceAsWritten(),
                                      D->getIdentLocation(), TU));
}
References clang::cxcursor::MakeCursorNamespaceRef().
VisitVarDecl()
bool CursorVisitor::VisitVarDecl (VarDecl * D)
Definition at line 919 of file CIndex.cpp.
                                           {
  if (VisitDeclaratorDecl(D))
    return true;
  if (Expr *Init = D->getInit())
    return Visit(MakeCXCursor(Init, StmtParent, TU, RegionOfInterest));
  return false;
}
References clang::cxcursor::MakeCXCursor().
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CursorVisitor.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndex.cpp