Reporter.EmailReporter Class Reference
Public Member Functions
def getName (self)
def getParameters (self)
def attachFile (self, outer, path)
def fileReport (self, report, parameters)
Detailed Description
Definition at line 78 of file Reporter.py.
Member Function Documentation
attachFile()
def Reporter.EmailReporter.attachFile (self, outer, path)
Definition at line 86 of file Reporter.py.
    def attachFile(self, outer, path):
        # Guess the content type based on the file's extension. Encoding
        # will be ignored, although we should check for simple things like
        # gzip'd or compressed files.
        ctype, encoding = mimetypes.guess_type(path)
        if ctype is None or encoding is not None:
            # No guess could be made, or the file is encoded (compressed), so
            # use a generic bag-of-bits type.
            ctype = 'application/octet-stream'
        maintype, subtype = ctype.split('/', 1)
        if maintype == 'text':
            fp = open(path)
            # Note: we should handle calculating the charset
            msg = MIMEText(fp.read(), _subtype=subtype)
            fp.close()
        else:
            fp = open(path, 'rb')
            msg = MIMEBase(maintype, subtype)
            msg.set_payload(fp.read())
            fp.close()
            # Encode the payload using Base64
            encoders.encode_base64(msg)
        # Set the filename parameter
        msg.add_header('Content-Disposition', 'attachment', filename=os.path.basename(path))
        outer.attach(msg)
References startfile.open().
Referenced by Reporter.EmailReporter.fileReport().
fileReport()
def Reporter.EmailReporter.fileReport (self, report, parameters)
Definition at line 112 of file Reporter.py.
    def fileReport(self, report, parameters):
        mainMsg = """\
BUG REPORT
---
Title: %s
Description: %s
"""%(report.title, report.description)
        if not parameters.get('To'):
            raise ReportFailure('No "To" address specified.')
        if not parameters.get('From'):
            raise ReportFailure('No "From" address specified.')
        msg = MIMEMultipart()
        msg['Subject'] = 'BUG REPORT: %s'%(report.title)
        # FIXME: Get config parameters
        msg['To'] = parameters.get('To')
        msg['From'] = parameters.get('From')
        msg.preamble = mainMsg
        msg.attach(MIMEText(mainMsg, _subtype='text/plain'))
        for file in report.files:
            self.attachFile(msg, file)
        try:
            s = smtplib.SMTP(host=parameters.get('SMTP Server'),
                             port=parameters.get('SMTP Port'))
            s.sendmail(msg['From'], msg['To'], msg.as_string())
            s.close()
        except:
            raise ReportFailure('Unable to send message via SMTP.')
        return "Message sent!"
References Reporter.EmailReporter.attachFile().
getName()
def Reporter.EmailReporter.getName (self)
Definition at line 79 of file Reporter.py.
    def getName(self):
        return 'Email'
Referenced by Reporter.TextParameter.getHTML(), Reporter.SelectionParameter.getHTML(), and Reporter.ReporterParameter.getValue().
getParameters()
def Reporter.EmailReporter.getParameters (self)
Definition at line 82 of file Reporter.py.
    def getParameters(self):
        return [TextParameter(x) for x in ['To', 'From', 'SMTP Server', 'SMTP Port']]
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-view/share/Reporter.py