ScanView.ScanViewServer Class Reference
Public Member Functions
def __init__ (self, address, handler, root, reporters, options)
def load_config (self)
def save_config (self)
def halt (self)
def serve_forever (self)
def finish_request (self, request, client_address)
def handle_error (self, request, client_address)
Public Attributes
root
reporters
options
halted
config
RequestHandlerClass
Detailed Description
Definition at line 132 of file ScanView.py.
Constructor & Destructor Documentation
__init__()
def ScanView.ScanViewServer.__init__ (self, address, handler, root, reporters, options)
Definition at line 133 of file ScanView.py.
    def __init__(self, address, handler, root, reporters, options):
        HTTPServer.__init__(self, address, handler)
        self.root = root
        self.reporters = reporters
        self.options = options
        self.halted = False
        self.config = None
        self.load_config()
Member Function Documentation
finish_request()
def ScanView.ScanViewServer.finish_request (self, request, client_address)
Definition at line 186 of file ScanView.py.
    def finish_request(self, request, client_address):
        if self.options.autoReload:
            import ScanView
            self.RequestHandlerClass = reload(ScanView).ScanViewRequestHandler
        HTTPServer.finish_request(self, request, client_address)
References ScanView.ScanViewServer.options.
halt()
def ScanView.ScanViewServer.halt (self)
Definition at line 172 of file ScanView.py.
    def halt(self):
        self.halted = True
        if self.options.debug:
            print("%s: SERVER: halting." % (sys.argv[0],), file=sys.stderr)
References ScanView.ScanViewServer.halted, ScanView.ScanViewServer.options, and print().
handle_error()
def ScanView.ScanViewServer.handle_error (self, request, client_address)
Definition at line 192 of file ScanView.py.
    def handle_error(self, request, client_address):
        # Ignore socket errors
        info = sys.exc_info()
        if info and isinstance(info[1], socket.error):
            if self.options.debug > 1:
                print("%s: SERVER: ignored socket error." % (sys.argv[0],), file=sys.stderr)
            return
        HTTPServer.handle_error(self, request, client_address)
# Borrowed from Quixote, with simplifications.
References ScanView.ScanViewServer.options, and print().
load_config()
def ScanView.ScanViewServer.load_config (self)
Definition at line 142 of file ScanView.py.
    def load_config(self):
        self.config = configparser.RawConfigParser()
        # Add defaults
        self.config.add_section('ScanView')
        for r in self.reporters:
            self.config.add_section(r.getName())
            for p in r.getParameters():
              if p.saveConfigValue():
                self.config.set(r.getName(), p.getName(), '')
        # Ignore parse errors
        try:
            self.config.read([kConfigPath])
        except:
            pass
        # Save on exit
        import atexit
        atexit.register(lambda: self.save_config())
        
References ScanView.ScanViewServer.config, ScanView.ScanViewServer.reporters, and ScanView.ScanViewServer.save_config().
save_config()
def ScanView.ScanViewServer.save_config (self)
Definition at line 163 of file ScanView.py.
    def save_config(self):
        # Ignore errors (only called on exit).
        try:
            f = open(kConfigPath,'w')
            self.config.write(f)
            f.close()
        except:
            pass
        
References ScanView.ScanViewServer.config, and startfile.open().
Referenced by ScanView.ScanViewServer.load_config().
serve_forever()
def ScanView.ScanViewServer.serve_forever (self)
Definition at line 177 of file ScanView.py.
    def serve_forever(self):
        while not self.halted:
            if self.options.debug > 1:
                print("%s: SERVER: waiting..." % (sys.argv[0],), file=sys.stderr)
            try:
                self.handle_request()
            except OSError as e:
                print('OSError',e.errno)
References ScanView.ScanViewServer.halted, ScanView.ScanViewServer.options, and print().
Member Data Documentation
config
ScanView.ScanViewServer.config
Definition at line 139 of file ScanView.py.
Referenced by ScanView.ScanViewServer.load_config(), and ScanView.ScanViewServer.save_config().
halted
ScanView.ScanViewServer.halted
Definition at line 138 of file ScanView.py.
Referenced by ScanView.ScanViewServer.halt(), and ScanView.ScanViewServer.serve_forever().
options
ScanView.ScanViewServer.options
Definition at line 137 of file ScanView.py.
Referenced by ScanView.ScanViewServer.finish_request(), ScanView.ScanViewServer.halt(), ScanView.ScanViewServer.handle_error(), and ScanView.ScanViewServer.serve_forever().
reporters
ScanView.ScanViewServer.reporters
Definition at line 136 of file ScanView.py.
Referenced by ScanView.ScanViewServer.load_config().
RequestHandlerClass
ScanView.ScanViewServer.RequestHandlerClass
Definition at line 189 of file ScanView.py.
root
ScanView.ScanViewServer.root
Definition at line 135 of file ScanView.py.
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-view/share/ScanView.py