Reporter.BugzillaReporter Class Reference
Public Member Functions
def getName (self)
def getParameters (self)
def fileReport (self, report, parameters)
Detailed Description
Definition at line 146 of file Reporter.py.
Member Function Documentation
fileReport()
def Reporter.BugzillaReporter.fileReport (self, report, parameters)
Definition at line 153 of file Reporter.py.
    def fileReport(self, report, parameters):
        raise NotImplementedError
 
getName()
def Reporter.BugzillaReporter.getName (self)
Definition at line 147 of file Reporter.py.
    def getName(self):
        return 'Bugzilla'
    
Referenced by Reporter.TextParameter.getHTML(), Reporter.SelectionParameter.getHTML(), and Reporter.ReporterParameter.getValue().
getParameters()
def Reporter.BugzillaReporter.getParameters (self)
Definition at line 150 of file Reporter.py.
    def getParameters(self):
        return [TextParameter(x) for x in ['URL','Product']]
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-view/share/Reporter.py