diagtool::DiagTool Class Reference
#include <DiagTool.h>
Public Member Functions
DiagTool (llvm::StringRef toolCmd, llvm::StringRef toolDesc)
virtual ~DiagTool ()
llvm::StringRef getName () const
llvm::StringRef getDescription () const
virtual int run (unsigned argc, char *argv[], llvm::raw_ostream &out)=0
Detailed Description
Definition at line 24 of file DiagTool.h.
Constructor & Destructor Documentation
DiagTool()
DiagTool::DiagTool (llvm::StringRef toolCmd, llvm::StringRef toolDesc)
Definition at line 19 of file DiagTool.cpp.
    : cmd(std::string(toolCmd)), description(std::string(toolDesc)) {}
 DiagTool()
DiagTool::~DiagTool () [virtual]
Definition at line 22 of file DiagTool.cpp.
{}
Member Function Documentation
getDescription()
llvm::StringRef diagtool::DiagTool::getDescription () const [inline]
Definition at line 32 of file DiagTool.h.
{ return description; }
getName()
llvm::StringRef diagtool::DiagTool::getName () const [inline]
Definition at line 31 of file DiagTool.h.
{ return cmd; }
Referenced by Reporter.TextParameter::getHTML(), Reporter.SelectionParameter::getHTML(), and Reporter.ReporterParameter::getValue().
run()
virtual int diagtool::DiagTool::run (unsigned argc, char * argv[], llvm::raw_ostream & out) [pure virtual]
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagTool.h
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagTool.cpp