clang::CXDiagnosticSetImpl Class Reference
#include <CIndexDiagnostic.h>
Public Member Functions
CXDiagnosticSetImpl (bool isManaged=false)
virtual ~CXDiagnosticSetImpl ()
size_t getNumDiagnostics () const
CXDiagnosticImpl * getDiagnostic (unsigned i) const
void appendDiagnostic (std::unique_ptr< CXDiagnosticImpl > D)
bool empty () const
bool isExternallyManaged () const
Detailed Description
Definition at line 27 of file CIndexDiagnostic.h.
Constructor & Destructor Documentation
CXDiagnosticSetImpl()
clang::CXDiagnosticSetImpl::CXDiagnosticSetImpl (bool isManaged = false) [inline]
Definition at line 31 of file CIndexDiagnostic.h.
    : IsExternallyManaged(isManaged) {}
 CXDiagnosticSetImpl()
CXDiagnosticSetImpl::~CXDiagnosticSetImpl () [virtual]
Definition at line 30 of file CIndexDiagnostic.cpp.
{}
Member Function Documentation
appendDiagnostic()
void CXDiagnosticSetImpl::appendDiagnostic (std::unique_ptr< CXDiagnosticImpl > D)
Definition at line 33 of file CIndexDiagnostic.cpp.
                                                                       {
  Diagnostics.push_back(std::move(D));
}
Referenced by clang::CXDiagnosticImpl::append().
empty()
bool clang::CXDiagnosticSetImpl::empty () const [inline]
Definition at line 47 of file CIndexDiagnostic.h.
                     {
    return Diagnostics.empty();
  }
Referenced by clang_getChildDiagnostics().
getDiagnostic()
CXDiagnosticImpl* clang::CXDiagnosticSetImpl::getDiagnostic (unsigned i) const [inline]
Definition at line 40 of file CIndexDiagnostic.h.
                                                    {
    assert(i < getNumDiagnostics());
    return Diagnostics[i].get();
  }
References getNumDiagnostics().
Referenced by clang_getDiagnostic().
getNumDiagnostics()
size_t clang::CXDiagnosticSetImpl::getNumDiagnostics () const [inline]
Definition at line 36 of file CIndexDiagnostic.h.
                                   {
    return Diagnostics.size();
  }
Referenced by clang_getDiagnostic(), clang_getNumDiagnostics(), getDiagnostic(), and clang::cxdiag::lazyCreateDiags().
isExternallyManaged()
bool clang::CXDiagnosticSetImpl::isExternallyManaged () const [inline]
Definition at line 51 of file CIndexDiagnostic.h.
{ return IsExternallyManaged; }
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.cpp