clang::LibclangInvocationReporter Class Reference
#include <CIndexer.h>
Public Types
enum class OperationKind { ParseOperation
, CompletionOperation
 }
Public Member Functions
LibclangInvocationReporter (CIndexer &Idx, OperationKind Op, unsigned ParseOptions, llvm::ArrayRef< const char * > Args, llvm::ArrayRef< std::string > InvocationArgs, llvm::ArrayRef< CXUnsavedFile > UnsavedFiles)
~LibclangInvocationReporter ()
Detailed Description
Logs information about a particular libclang operation like parsing to a new file in the invocation emission path.
Definition at line 89 of file CIndexer.h.
Member Enumeration Documentation
OperationKind
enum clang::LibclangInvocationReporter::OperationKind [strong]
Enumerator
ParseOperation
CompletionOperation
Definition at line 91 of file CIndexer.h.
{ ParseOperation, CompletionOperation };
Constructor & Destructor Documentation
LibclangInvocationReporter()
LibclangInvocationReporter::LibclangInvocationReporter (CIndexer & Idx, OperationKind Op, unsigned ParseOptions, llvm::ArrayRef< const char * > Args, llvm::ArrayRef< std::string > InvocationArgs, llvm::ArrayRef< CXUnsavedFile > UnsavedFiles)
Definition at line 152 of file CIndexer.cpp.
                                              {
  StringRef Path = Idx.getInvocationEmissionPath();
  if (Path.empty())
    return;
  // Create a temporary file for the invocation log.
  SmallString<256> TempPath;
  TempPath = Path;
  llvm::sys::path::append(TempPath, "libclang-%%%%%%%%%%%%");
  int FD;
  if (llvm::sys::fs::createUniqueFile(TempPath, FD, TempPath,
                                      llvm::sys::fs::OF_Text))
    return;
  File = std::string(TempPath.begin(), TempPath.end());
  llvm::raw_fd_ostream OS(FD, /*ShouldClose=*/true);
  // Write out the information about the invocation to it.
  auto WriteStringKey = [&OS](StringRef Key, StringRef Value) {
    OS << R"(")" << Key << R"(":")";
    OS << llvm::yaml::escape(Value) << '"';
  };
  OS << '{';
  WriteStringKey("toolchain", Idx.getClangToolchainPath());
  OS << ',';
  WriteStringKey("libclang.operation",
                 Op == OperationKind::ParseOperation ? "parse" : "complete");
  OS << ',';
  OS << R"("libclang.opts":)" << ParseOptions;
  OS << ',';
  OS << R"("args":[)";
  for (const auto &I : llvm::enumerate(Args)) {
    if (I.index())
      OS << ',';
    OS << '"' << llvm::yaml::escape(I.value()) << '"';
  }
  if (!InvocationArgs.empty()) {
    OS << R"(],"invocation-args":[)";
    for (const auto &I : llvm::enumerate(InvocationArgs)) {
      if (I.index())
        OS << ',';
      OS << '"' << llvm::yaml::escape(I.value()) << '"';
    }
  }
  if (!UnsavedFiles.empty()) {
    OS << R"(],"unsaved_file_hashes":[)";
    for (const auto &UF : llvm::enumerate(UnsavedFiles)) {
      if (UF.index())
        OS << ',';
      OS << '{';
      WriteStringKey("name", UF.value().Filename);
      OS << ',';
      llvm::MD5 Hash;
      Hash.update(getContents(UF.value()));
      llvm::MD5::MD5Result Result;
      Hash.final(Result);
      SmallString<32> Digest = Result.digest();
      WriteStringKey("md5", Digest);
      OS << '}';
    }
  }
  OS << "]}";
}
References libscanbuild.report::escape(), clang::CIndexer::getClangToolchainPath(), clang::CIndexer::getInvocationEmissionPath(), and ParseOperation.
 LibclangInvocationReporter()
LibclangInvocationReporter::~LibclangInvocationReporter ()
Definition at line 219 of file CIndexer.cpp.
                                                        {
  if (!File.empty())
    llvm::sys::fs::remove(File);
}
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexer.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexer.cpp