diagtool::GroupRecord::group_iterator< RecordType > Class Template Reference
#include <DiagnosticNames.h>
Public Types
typedef RecordType value_type
typedef const value_type & reference
typedef const value_type * pointer
typedef std::forward_iterator_tag iterator_category
typedef std::ptrdiff_t difference_type
Public Member Functions
reference operator* () const
pointer operator-> () const
short getID () const
group_iterator & operator++ ()
bool operator== (const group_iterator &Other) const
bool operator!= (const group_iterator &Other) const
Friends
struct GroupRecord
Detailed Description
template<typename RecordType>
class diagtool::GroupRecord::group_iterator< RecordType >
Definition at line 47 of file DiagnosticNames.h.
Member Typedef Documentation
difference_type
template<typename RecordType >
typedef std::ptrdiff_t diagtool::GroupRecord::group_iterator< RecordType >::difference_type
Definition at line 61 of file DiagnosticNames.h.
iterator_category
template<typename RecordType >
typedef std::forward_iterator_tag diagtool::GroupRecord::group_iterator< RecordType >::iterator_category
Definition at line 60 of file DiagnosticNames.h.
pointer
template<typename RecordType >
typedef const value_type* diagtool::GroupRecord::group_iterator< RecordType >::pointer
Definition at line 59 of file DiagnosticNames.h.
reference
template<typename RecordType >
typedef const value_type& diagtool::GroupRecord::group_iterator< RecordType >::reference
Definition at line 58 of file DiagnosticNames.h.
value_type
template<typename RecordType >
typedef RecordType diagtool::GroupRecord::group_iterator< RecordType >::value_type
Definition at line 57 of file DiagnosticNames.h.
Member Function Documentation
getID()
template<typename RecordType >
short diagtool::GroupRecord::group_iterator< RecordType >::getID () const [inline]
Definition at line 68 of file DiagnosticNames.h.
                                 {
        return *CurrentID;
      }
operator!=()
template<typename RecordType >
bool diagtool::GroupRecord::group_iterator< RecordType >::operator!= (const group_iterator< RecordType > & Other) const [inline]
Definition at line 83 of file DiagnosticNames.h.
                                                         {
        return CurrentID != Other.CurrentID;
      }
operator*()
template<typename RecordType >
GroupRecord::diagnostics_iterator::reference diagtool::GroupRecord::diagnostics_iterator::operator* () const [inline]
Definition at line 108 of file DiagnosticNames.h.
                                                {
    return getDiagnosticGroups()[*CurrentID];
  }
References diagtool::getDiagnosticGroups().
Referenced by diagtool::GroupRecord::group_iterator< RecordType >::operator->().
operator++()
template<typename RecordType >
group_iterator& diagtool::GroupRecord::group_iterator< RecordType >::operator++ () [inline]
Definition at line 72 of file DiagnosticNames.h.
                                   {
        ++CurrentID;
        if (*CurrentID == -1)
          CurrentID = nullptr;
        return *this;
      }
operator->()
template<typename RecordType >
pointer diagtool::GroupRecord::group_iterator< RecordType >::operator-> () const [inline]
Definition at line 64 of file DiagnosticNames.h.
                                        {
        return &operator*();
      }
References diagtool::GroupRecord::group_iterator< RecordType >::operator*().
operator==()
template<typename RecordType >
bool diagtool::GroupRecord::group_iterator< RecordType >::operator== (const group_iterator< RecordType > & Other) const [inline]
Definition at line 79 of file DiagnosticNames.h.
                                                         {
        return CurrentID == Other.CurrentID;
      }
Friends And Related Function Documentation
GroupRecord
template<typename RecordType >
friend struct GroupRecord [friend]
Definition at line 50 of file DiagnosticNames.h.
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.h