DataStorage Class Reference
Public Member Functions
DataStorage (string identifierString)
void startEvent (int identifier)
void endEvent (int identifier)
void print ()
Public Attributes
StatementRuntime * statementRuntimeArray
int statementRuntimeArraySize
Detailed Description
Definition at line 3 of file DataStorage.cpp.
Constructor & Destructor Documentation
DataStorage()
DataStorage::DataStorage (string identifierString) [inline]
Definition at line 13 of file DataStorage.cpp.
                                           {
        // count entries in identifierStrings
        statementRuntimeArraySize = std::count(identifierString.begin(), identifierString.end(), ',') + 1;
        statementRuntimeArray = new StatementRuntime[statementRuntimeArraySize];
        statementRuntimeArraySize = 0;
        // split identifier string to array
        std::stringstream identifierStream(identifierString);
        string segment;
        while (std::getline(identifierStream, segment, ',')) {
            statementRuntimeArray[ statementRuntimeArraySize++ ].identifier = segment;
        }
    }
References StatementRuntime::identifier, identifierString, statementRuntimeArray, and statementRuntimeArraySize.
Member Function Documentation
endEvent()
void DataStorage::endEvent (int identifier) [inline]
Definition at line 46 of file DataStorage.cpp.
                                    {
        statementRuntimeArray[ identifier ].endTime = high_resolution_clock::now();
        //cout << "\ntime:" << high_resolution_clock::now().time_since_epoch().count();
    }
References StatementRuntime::endTime, and statementRuntimeArray.
Referenced by main(), prime_sieve::runSieve(), and BitArray::setFlagsFalse().
print()
void DataStorage::print () [inline]
Definition at line 52 of file DataStorage.cpp.
                  {
        // calculate total runtime
        MeasurementEvaluation total;
        total.identifier = "Runtime";
        total.duration = statementRuntimeArray[ 0 ].endTime - statementRuntimeArray[ 0 ].startTime;
        //ofstream outfile;
        //outfile.open("Time_Without_Print.txt", ios_base::app);
        //outfile << hlibhelp::convertToSpecifiedUnit(total.duration, "s") << "\n";
        // calculate scope runtime
        MeasurementEvaluation scope;
        scope.identifier = "Scope";
        scope.duration = statementRuntimeArray[ 1 ].endTime - statementRuntimeArray[ 1 ].startTime;
        // sum of runtime of all annotated statements
        std::chrono::duration<double, std::nano> statementRuntimeSum;
        // get unit for runtime if scope measured
        string unit = hlibhelp::getUnit(total.duration);
        // normally scope is measured
        bool scopeIsMeasured = true;
        cout << scope.duration.count();
        // if scope is not measured, calculate time between first and last counter
        if (scope.duration.count() == 0) {
            scope.duration = statementRuntimeArray[ statementRuntimeArraySize - 1 ].endTime -
                             statementRuntimeArray[ 2 ].startTime;
            // get unit for runtime
            unit = hlibhelp::getUnit(scope.duration);
            scopeIsMeasured = false;
        }
        // print the statistic banner
        hlibhelp::printStatisticBanner();
        // print table header
        hlibhelp::printTableSeparator(115, "—", "top", "\n");
        hlibhelp::printTableRow("ID", "ClassType", 0, "", "Scope", "Total", "Calls");
        hlibhelp::printTableSeparator(115, "—", "middle", "\n");
        double sumCalls = 0;
        // iterate through all measured statements
        for (int i = 2; i < statementRuntimeArraySize; i++) {
            // calculate duration
            MeasurementEvaluation currentEvaluation;
            currentEvaluation.duration = statementRuntimeArray[ i ].endTime - statementRuntimeArray[ i ].startTime;
            currentEvaluation.totalUsage = currentEvaluation.duration / total.duration * 100;
            currentEvaluation.scopeUsage = currentEvaluation.duration / scope.duration * 100;
            sumCalls += statementRuntimeArray[ i ].called;
            std::ostringstream calledToString;
            calledToString << std::fixed << setprecision(0) << statementRuntimeArray[ i ].called;
            currentEvaluation.called = calledToString.str();
            statementRuntimeSum += currentEvaluation.duration;
            // split identifier in id and class type
            string *segments = hlibhelp::getSegmentsOfString(statementRuntimeArray[ i ].identifier);
            // current evaluation to string
            double durationBeautified = hlibhelp::convertToSpecifiedUnit(currentEvaluation.duration, unit);
            string scopeUsageBeautified = hlibhelp::getUsageAsString(currentEvaluation.scopeUsage);
            string totalUsageBeautified = hlibhelp::getUsageAsString(currentEvaluation.totalUsage);
            // print current evaluation the row table
            hlibhelp::printTableRow(segments[ 1 ], segments[ 0 ], durationBeautified, unit,
                                     scopeUsageBeautified, totalUsageBeautified, currentEvaluation.called);
        }
        // evaluate hagn tool runtime
        MeasurementEvaluation hagnTool;
        hagnTool.identifier = "Perf Counter";
        hagnTool.duration = scope.duration - statementRuntimeSum;
        hagnTool.totalUsage = hagnTool.duration / total.duration * 100;
        hagnTool.scopeUsage = hagnTool.duration / scope.duration * 100;
        std::ostringstream calledToString;
        sumCalls = sumCalls*2;
        calledToString << std::fixed << setprecision(0) << sumCalls;
        hagnTool.called = calledToString.str();
        ofstream callsFile;
        callsFile.open("Calls.txt", ios_base::app);
        callsFile << calledToString.str() << "\n";
        // hagn tool evaluation to string
        double hagnToolDurationBeautified = hlibhelp::convertToSpecifiedUnit(hagnTool.duration, unit);
        string totalUsageBeautified = hlibhelp::getUsageAsString(hagnTool.totalUsage);
        string scopeUsageBeautified = hlibhelp::getUsageAsString(hagnTool.scopeUsage);
        // print hagnTool row table
        hlibhelp::printTableRow(hagnTool.identifier, "", hagnToolDurationBeautified, unit, scopeUsageBeautified,
                                 totalUsageBeautified, hagnTool.called);
        // check if scope measurement should be printed
        if (scopeIsMeasured) {
            hlibhelp::printTableSeparator(115, "—", "middle", "\n");
            double scopeDurationBeautified = hlibhelp::convertToSpecifiedUnit(scope.duration, unit);
            hlibhelp::printTableRow(scope.identifier, "", scopeDurationBeautified, unit, "", "", "");
        } else {
            hlibhelp::printTableSeparator(115, "—", "middle", "\n");
        }
        // total duration to string
        double totalDurationBeautified = hlibhelp::convertToSpecifiedUnit(total.duration, unit);
        // print runtime row table
        hlibhelp::printTableRow(total.identifier, "", totalDurationBeautified, unit, "", "", "");
        hlibhelp::printTableSeparator(115, "—", "bottom", "\n");
        cout << "\n\n";
    }
References StatementRuntime::called, MeasurementEvaluation::called, hlibhelp::convertToSpecifiedUnit(), MeasurementEvaluation::duration, StatementRuntime::endTime, hlibhelp::getSegmentsOfString(), hlibhelp::getUnit(), hlibhelp::getUsageAsString(), MeasurementEvaluation::identifier, hlibhelp::printStatisticBanner(), hlibhelp::printTableRow(), hlibhelp::printTableSeparator(), MeasurementEvaluation::scopeUsage, StatementRuntime::startTime, statementRuntimeArray, statementRuntimeArraySize, and MeasurementEvaluation::totalUsage.
Referenced by main().
startEvent()
void DataStorage::startEvent (int identifier) [inline]
Definition at line 28 of file DataStorage.cpp.
                                      {
        statementRuntimeArray[ identifier ].called++;
        // if identifier is already measured, sum runtimes
        if (statementRuntimeArray[ identifier ].startTime != invalidTime &&
             statementRuntimeArray[ identifier ].endTime != invalidTime) {
            statementRuntimeArray[ identifier ].startTime = high_resolution_clock::now() -
                                                            (statementRuntimeArray[ identifier ].endTime -
                                                              statementRuntimeArray[ identifier ].startTime);
        }
            // else add timestamp as start time
        else {
            statementRuntimeArray[ identifier ].startTime = high_resolution_clock::now();
        }
        //cout << "\ntime:" << high_resolution_clock::now().time_since_epoch().count();
    }
References StatementRuntime::called, StatementRuntime::endTime, invalidTime, StatementRuntime::startTime, and statementRuntimeArray.
Referenced by main(), prime_sieve::runSieve(), and BitArray::setFlagsFalse().
Member Data Documentation
statementRuntimeArray
StatementRuntime* DataStorage::statementRuntimeArray
Definition at line 7 of file DataStorage.cpp.
Referenced by DataStorage(), endEvent(), print(), and startEvent().
statementRuntimeArraySize
int DataStorage::statementRuntimeArraySize
Definition at line 10 of file DataStorage.cpp.
Referenced by DataStorage(), and print().
The documentation for this class was generated from the following file:
lib/DataStorage.cpp