libear.Configure Class Reference
Public Member Functions
def __init__ (self, toolset)
def check_function_exists (self, function, name)
def check_symbol_exists (self, symbol, include, name)
def write_by_template (self, template, output)
Public Attributes
ctx
results
Detailed Description
Definition at line 162 of file __init__.py.
Constructor & Destructor Documentation
__init__()
def libear.Configure.__init__ (self, toolset)
Definition at line 163 of file __init__.py.
    def __init__(self, toolset):
        self.ctx = toolset
        self.results = {'APPLE': sys.platform == 'darwin'}
Member Function Documentation
check_function_exists()
def libear.Configure.check_function_exists (self, function, name)
Definition at line 180 of file __init__.py.
    def check_function_exists(self, function, name):
        template = "int FUNCTION(); int main() { return FUNCTION(); }"
        source = template.replace("FUNCTION", function)
        logging.debug('Checking function %s', function)
        found = self._try_to_compile_and_link(source)
        logging.debug('Checking function %s -- %s', function,
                      'found' if found else 'not found')
        self.results.update({name: found})
References libear.Configure._try_to_compile_and_link(), and libear.Configure.results.
check_symbol_exists()
def libear.Configure.check_symbol_exists (self, symbol, include, name)
Definition at line 190 of file __init__.py.
    def check_symbol_exists(self, symbol, include, name):
        template = """#include <INCLUDE>
                      int main() { return ((int*)(&SYMBOL))[0]; }"""
        source = template.replace('INCLUDE', include).replace("SYMBOL", symbol)
        logging.debug('Checking symbol %s', symbol)
        found = self._try_to_compile_and_link(source)
        logging.debug('Checking symbol %s -- %s', symbol,
                      'found' if found else 'not found')
        self.results.update({name: found})
References libear.Configure._try_to_compile_and_link(), and libear.Configure.results.
write_by_template()
def libear.Configure.write_by_template (self, template, output)
Definition at line 201 of file __init__.py.
    def write_by_template(self, template, output):
        def transform(line, definitions):
            pattern = re.compile(r'^#cmakedefine\s+(\S+)')
            m = pattern.match(line)
            if m:
                key = m.group(1)
                if key not in definitions or not definitions[key]:
                    return '/* #undef {0} */{1}'.format(key, os.linesep)
                else:
                    return '#define {0}{1}'.format(key, os.linesep)
            return line
        with open(template, 'r') as src_handle:
            logging.debug('Writing config to %s', output)
            with open(output, 'w') as dst_handle:
                for line in src_handle:
                    dst_handle.write(transform(line, self.results))
References startfile.open(), and libear.Configure.results.
Member Data Documentation
ctx
libear.Configure.ctx
Definition at line 164 of file __init__.py.
Referenced by libear.SharedLibrary.build_release().
results
libear.Configure.results
Definition at line 165 of file __init__.py.
Referenced by libear.Configure.check_function_exists(), libear.Configure.check_symbol_exists(), and libear.Configure.write_by_template().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libear/__init__.py