tests.unit.test_analyze.FilteringFlagsTest Class Reference
Public Member Functions
def test_language_captured (self)
def test_arch (self)
def assertFlagsChanged (self, expected, flags)
def assertFlagsUnchanged (self, flags)
def assertFlagsFiltered (self, flags)
def test_optimalizations_pass (self)
def test_include_pass (self)
def test_define_pass (self)
def test_output_filtered (self)
def test_some_warning_filtered (self)
def test_compile_only_flags_pass (self)
def test_compile_and_link_flags_pass (self)
def test_some_flags_filtered (self)
Detailed Description
Definition at line 28 of file test_analyze.py.
Member Function Documentation
assertFlagsChanged()
def tests.unit.test_analyze.FilteringFlagsTest.assertFlagsChanged (self, expected, flags)
Definition at line 51 of file test_analyze.py.
    def assertFlagsChanged(self, expected, flags):
        cmd = ['clang', '-c', 'source.c'] + flags
        opts = sut.classify_parameters(cmd)
        self.assertEqual(expected, opts['flags'])
Referenced by tests.unit.test_analyze.FilteringFlagsTest.assertFlagsFiltered(), and tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
assertFlagsFiltered()
def tests.unit.test_analyze.FilteringFlagsTest.assertFlagsFiltered (self, flags)
Definition at line 59 of file test_analyze.py.
    def assertFlagsFiltered(self, flags):
        self.assertFlagsChanged([], flags)
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsChanged().
Referenced by tests.unit.test_analyze.FilteringFlagsTest.test_output_filtered(), tests.unit.test_analyze.FilteringFlagsTest.test_some_flags_filtered(), and tests.unit.test_analyze.FilteringFlagsTest.test_some_warning_filtered().
assertFlagsUnchanged()
def tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged (self, flags)
Definition at line 56 of file test_analyze.py.
    def assertFlagsUnchanged(self, flags):
        self.assertFlagsChanged(flags, flags)
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsChanged().
Referenced by tests.unit.test_analyze.FilteringFlagsTest.test_compile_and_link_flags_pass(), tests.unit.test_analyze.FilteringFlagsTest.test_compile_only_flags_pass(), tests.unit.test_analyze.FilteringFlagsTest.test_define_pass(), tests.unit.test_analyze.FilteringFlagsTest.test_include_pass(), tests.unit.test_analyze.FilteringFlagsTest.test_optimalizations_pass(), and tests.unit.test_analyze.FilteringFlagsTest.test_some_warning_filtered().
test_arch()
def tests.unit.test_analyze.FilteringFlagsTest.test_arch (self)
Definition at line 40 of file test_analyze.py.
    def test_arch(self):
        def test(flags):
            cmd = ['clang', '-c', 'source.c'] + flags
            opts = sut.classify_parameters(cmd)
            return opts['arch_list']
        self.assertEqual([], test([]))
        self.assertEqual(['mips'], test(['-arch', 'mips']))
        self.assertEqual(['mips', 'i386'],
                         test(['-arch', 'mips', '-arch', 'i386']))
References test().
test_compile_and_link_flags_pass()
def tests.unit.test_analyze.FilteringFlagsTest.test_compile_and_link_flags_pass (self)
Definition at line 103 of file test_analyze.py.
    def test_compile_and_link_flags_pass(self):
        self.assertFlagsUnchanged(['-fsinged-char'])
        self.assertFlagsUnchanged(['-fPIC'])
        self.assertFlagsUnchanged(['-stdlib=libc++'])
        self.assertFlagsUnchanged(['--sysroot', '/'])
        self.assertFlagsUnchanged(['-isysroot', '/'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
test_compile_only_flags_pass()
def tests.unit.test_analyze.FilteringFlagsTest.test_compile_only_flags_pass (self)
Definition at line 95 of file test_analyze.py.
    def test_compile_only_flags_pass(self):
        self.assertFlagsUnchanged(['-std=C99'])
        self.assertFlagsUnchanged(['-nostdinc'])
        self.assertFlagsUnchanged(['-isystem', '/image/debian'])
        self.assertFlagsUnchanged(['-iprefix', '/usr/local'])
        self.assertFlagsUnchanged(['-iquote=me'])
        self.assertFlagsUnchanged(['-iquote', 'me'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
test_define_pass()
def tests.unit.test_analyze.FilteringFlagsTest.test_define_pass (self)
Definition at line 80 of file test_analyze.py.
    def test_define_pass(self):
        self.assertFlagsUnchanged(['-DNDEBUG'])
        self.assertFlagsUnchanged(['-UNDEBUG'])
        self.assertFlagsUnchanged(['-Dvar1=val1', '-Dvar2=val2'])
        self.assertFlagsUnchanged(['-Dvar="val ues"'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
test_include_pass()
def tests.unit.test_analyze.FilteringFlagsTest.test_include_pass (self)
Definition at line 69 of file test_analyze.py.
    def test_include_pass(self):
        self.assertFlagsUnchanged([])
        self.assertFlagsUnchanged(['-include', '/usr/local/include'])
        self.assertFlagsUnchanged(['-I.'])
        self.assertFlagsUnchanged(['-I', '.'])
        self.assertFlagsUnchanged(['-I/usr/local/include'])
        self.assertFlagsUnchanged(['-I', '/usr/local/include'])
        self.assertFlagsUnchanged(['-I/opt', '-I', '/opt/otp/include'])
        self.assertFlagsUnchanged(['-isystem', '/path'])
        self.assertFlagsUnchanged(['-isystem=/path'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
test_language_captured()
def tests.unit.test_analyze.FilteringFlagsTest.test_language_captured (self)
Definition at line 30 of file test_analyze.py.
    def test_language_captured(self):
        def test(flags):
            cmd = ['clang', '-c', 'source.c'] + flags
            opts = sut.classify_parameters(cmd)
            return opts['language']
        self.assertEqual(None, test([]))
        self.assertEqual('c', test(['-x', 'c']))
        self.assertEqual('cpp', test(['-x', 'cpp']))
References test().
test_optimalizations_pass()
def tests.unit.test_analyze.FilteringFlagsTest.test_optimalizations_pass (self)
Definition at line 62 of file test_analyze.py.
    def test_optimalizations_pass(self):
        self.assertFlagsUnchanged(['-O'])
        self.assertFlagsUnchanged(['-O1'])
        self.assertFlagsUnchanged(['-Os'])
        self.assertFlagsUnchanged(['-O2'])
        self.assertFlagsUnchanged(['-O3'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
test_output_filtered()
def tests.unit.test_analyze.FilteringFlagsTest.test_output_filtered (self)
Definition at line 86 of file test_analyze.py.
    def test_output_filtered(self):
        self.assertFlagsFiltered(['-o', 'source.o'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsFiltered().
test_some_flags_filtered()
def tests.unit.test_analyze.FilteringFlagsTest.test_some_flags_filtered (self)
Definition at line 110 of file test_analyze.py.
    def test_some_flags_filtered(self):
        self.assertFlagsFiltered(['-g'])
        self.assertFlagsFiltered(['-fsyntax-only'])
        self.assertFlagsFiltered(['-save-temps'])
        self.assertFlagsFiltered(['-init', 'my_init'])
        self.assertFlagsFiltered(['-sectorder', 'a', 'b', 'c'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsFiltered().
test_some_warning_filtered()
def tests.unit.test_analyze.FilteringFlagsTest.test_some_warning_filtered (self)
Definition at line 89 of file test_analyze.py.
    def test_some_warning_filtered(self):
        self.assertFlagsFiltered(['-Wall'])
        self.assertFlagsFiltered(['-Wnoexcept'])
        self.assertFlagsFiltered(['-Wreorder', '-Wunused', '-Wundef'])
        self.assertFlagsUnchanged(['-Wno-reorder', '-Wno-unused'])
References tests.unit.test_analyze.FilteringFlagsTest.assertFlagsFiltered(), and tests.unit.test_analyze.FilteringFlagsTest.assertFlagsUnchanged().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/unit/test_analyze.py