prime_sieve Class Reference
Public Member Functions
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
prime_sieve (long n)
~prime_sieve ()
void runSieve ()
void printResults (bool showResults, double duration, int passes)
int countPrimes ()
Detailed Description
Definition at line 66 of file Performance_Prime_With_Counter_1.cpp.
Constructor & Destructor Documentation
prime_sieve() [1/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 84 of file Performance_Prime_With_Counter_1.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [1/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 89 of file Performance_Prime_With_Counter_1.cpp.
      {
      }
prime_sieve() [2/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 84 of file Performance_Prime_With_Counter_2.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [2/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 89 of file Performance_Prime_With_Counter_2.cpp.
      {
      }
prime_sieve() [3/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 84 of file Performance_Prime_With_Counter_3.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [3/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 89 of file Performance_Prime_With_Counter_3.cpp.
      {
      }
prime_sieve() [4/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 84 of file Performance_Prime_With_Counter_4.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [4/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 89 of file Performance_Prime_With_Counter_4.cpp.
      {
      }
prime_sieve() [5/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 88 of file Performance_Prime_With_Counter_5.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [5/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 93 of file Performance_Prime_With_Counter_5.cpp.
      {
      }
prime_sieve() [6/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 88 of file Performance_Prime_With_Counter_6.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [6/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 93 of file Performance_Prime_With_Counter_6.cpp.
      {
      }
prime_sieve() [7/7]
prime_sieve::prime_sieve (long n) [inline]
Definition at line 83 of file Performance_Prime_Without_Counter.cpp.
        : Bits(n), sieveSize(n)
      {
      }
 prime_sieve() [7/7]
prime_sieve::~prime_sieve () [inline]
Definition at line 88 of file Performance_Prime_Without_Counter.cpp.
      {
      }
Member Function Documentation
countPrimes() [1/7]
int prime_sieve::countPrimes () [inline]
Definition at line 150 of file Performance_Prime_With_Counter_1.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
countPrimes() [2/7]
int prime_sieve::countPrimes () [inline]
Definition at line 150 of file Performance_Prime_With_Counter_2.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
countPrimes() [3/7]
int prime_sieve::countPrimes () [inline]
Definition at line 154 of file Performance_Prime_With_Counter_3.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
countPrimes() [4/7]
int prime_sieve::countPrimes () [inline]
Definition at line 158 of file Performance_Prime_With_Counter_4.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
countPrimes() [5/7]
int prime_sieve::countPrimes () [inline]
Definition at line 156 of file Performance_Prime_With_Counter_5.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
countPrimes() [6/7]
int prime_sieve::countPrimes () [inline]
Definition at line 154 of file Performance_Prime_With_Counter_6.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
countPrimes() [7/7]
int prime_sieve::countPrimes () [inline]
Definition at line 149 of file Performance_Prime_Without_Counter.cpp.
      {
          int count = (sieveSize >= 2);;
          for (int i = 3; i < sieveSize; i+=2)
              if (Bits.get(i))
                  count++;
          return count;
      }
References BitArray::get().
printResults() [1/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 114 of file Performance_Prime_With_Counter_1.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
Referenced by main().
printResults() [2/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 114 of file Performance_Prime_With_Counter_2.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
printResults() [3/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 118 of file Performance_Prime_With_Counter_3.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
printResults() [4/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 122 of file Performance_Prime_With_Counter_4.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
printResults() [5/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 120 of file Performance_Prime_With_Counter_5.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
printResults() [6/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 118 of file Performance_Prime_With_Counter_6.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
printResults() [7/7]
void prime_sieve::printResults (bool showResults, double duration, int passes) [inline]
Definition at line 113 of file Performance_Prime_Without_Counter.cpp.
      {
          if (showResults)
              printf("2, ");
          int count = (sieveSize >= 2); // Starting count (2 is prime)
          for (int num = 3; num <= sieveSize; num+=2)
          {
              if (Bits.get(num))
              {
                  if (showResults)
                      printf("%d, ", num);
                  count++;
              }
          }
          if (showResults)
              printf("\n");
          ofstream outfile;
          outfile.open("Time_Performance_Prime.txt", ios_base::app);
          outfile << passes << "\n";
          /*printf("Passes: %d, Time: %lf, Avg: %lf, Limit: %ld, Count1: %d, Count2: %d, Valid: %d\n",
                 passes,
                 duration,
                 duration / passes,
                 sieveSize,
                 count,
                 countPrimes(),
                 validateResults());
          // Following 2 lines added by rbergen to conform to drag race output format
          printf("\n");
          printf("davepl_pol;%d;%f;1;algorithm=base,faithful=yes,bits=1\n", passes, duration);*/
      }
References BitArray::get().
runSieve() [1/7]
void prime_sieve::runSieve () [inline]
Definition at line 93 of file Performance_Prime_With_Counter_1.cpp.
      {
          int factor = 3;
          int q = (int) sqrt(sieveSize);
          while (factor <= q)
          {
              for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
              Bits.setFlagsFalse(factor * factor, factor + factor);
              factor += 2;
          }
      }
References BitArray::get(), and BitArray::setFlagsFalse().
Referenced by main().
runSieve() [2/7]
void prime_sieve::runSieve () [inline]
Definition at line 93 of file Performance_Prime_With_Counter_2.cpp.
      {
          int factor = 3;
          int q = (int) sqrt(sieveSize);
          while (factor <= q)
          {
              for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
              Bits.setFlagsFalse(factor * factor, factor + factor);
              factor += 2;
          }
      }
References BitArray::get(), and BitArray::setFlagsFalse().
runSieve() [3/7]
void prime_sieve::runSieve () [inline]
Definition at line 93 of file Performance_Prime_With_Counter_3.cpp.
      {
          dataStorage.startEvent(2);
int factor = 3;
          int q = (int) sqrt(sieveSize);
          dataStorage.endEvent(2);
dataStorage.startEvent(3);
while (factor <= q)
          {
              for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
              Bits.setFlagsFalse(factor * factor, factor + factor);
              factor += 2;
          }dataStorage.endEvent(3);
      }
References dataStorage(), DataStorage::endEvent(), BitArray::get(), BitArray::setFlagsFalse(), and DataStorage::startEvent().
runSieve() [4/7]
void prime_sieve::runSieve () [inline]
Definition at line 93 of file Performance_Prime_With_Counter_4.cpp.
      {
          int factor = 3;
          int q = (int) sqrt(sieveSize);
          dataStorage.startEvent(1);
while (factor <= q)
          {
              dataStorage.startEvent(2);
for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
dataStorage.endEvent(2);
              dataStorage.startEvent(3);
Bits.setFlagsFalse(factor * factor, factor + factor);
dataStorage.endEvent(3);
              dataStorage.startEvent(4);
factor += 2;
dataStorage.endEvent(4);
          }dataStorage.endEvent(1);
      }
References dataStorage(), DataStorage::endEvent(), BitArray::get(), BitArray::setFlagsFalse(), and DataStorage::startEvent().
runSieve() [5/7]
void prime_sieve::runSieve () [inline]
Definition at line 97 of file Performance_Prime_With_Counter_5.cpp.
      {
          int factor = 3;
          int q = (int) sqrt(sieveSize);
          while (factor <= q)
          {
              for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
              dataStorage.startEvent(1);
Bits.setFlagsFalse(factor * factor, factor + factor);
dataStorage.endEvent(1);
              factor += 2;
          }
      }
References dataStorage(), DataStorage::endEvent(), BitArray::get(), BitArray::setFlagsFalse(), and DataStorage::startEvent().
runSieve() [6/7]
void prime_sieve::runSieve () [inline]
Definition at line 97 of file Performance_Prime_With_Counter_6.cpp.
      {
          int factor = 3;
          int q = (int) sqrt(sieveSize);
          while (factor <= q)
          {
              for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
              Bits.setFlagsFalse(factor * factor, factor + factor);
              factor += 2;
          }
      }
References BitArray::get(), and BitArray::setFlagsFalse().
runSieve() [7/7]
void prime_sieve::runSieve () [inline]
Definition at line 92 of file Performance_Prime_Without_Counter.cpp.
      {
          int factor = 3;
          int q = (int) sqrt(sieveSize);
          while (factor <= q)
          {
              for (int num = factor; num < sieveSize; num += 2)
              {
                  if (Bits.get(num))
                  {
                      factor = num;
                      break;
                  }
              }
              Bits.setFlagsFalse(factor * factor, factor + factor);
              factor += 2;
          }
      }
References BitArray::get(), and BitArray::setFlagsFalse().
The documentation for this class was generated from the following files:
Tests/Prime Tests Cases/Performance_Prime_With_Counter_1.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_2.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_3.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_4.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_5.cpp
Tests/Prime Tests Cases/Performance_Prime_With_Counter_6.cpp
Tests/Prime Tests Cases/Performance_Prime_Without_Counter.cpp