tests.functional.cases.test_from_cdb.OutputDirectoryTest Class Reference
Public Member Functions
def test_regular_keeps_report_dir (self)
def test_clear_deletes_report_dir (self)
def test_clear_keeps_report_dir_when_asked (self)
Detailed Description
Definition at line 36 of file test_from_cdb.py.
Member Function Documentation
test_clear_deletes_report_dir()
def tests.functional.cases.test_from_cdb.OutputDirectoryTest.test_clear_deletes_report_dir (self)
Definition at line 43 of file test_from_cdb.py.
    def test_clear_deletes_report_dir(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('clean', tmpdir)
            exit_code, reportdir = run_analyzer(tmpdir, cdb, [])
            self.assertFalse(os.path.isdir(reportdir))
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_clear_keeps_report_dir_when_asked()
def tests.functional.cases.test_from_cdb.OutputDirectoryTest.test_clear_keeps_report_dir_when_asked (self)
Definition at line 49 of file test_from_cdb.py.
    def test_clear_keeps_report_dir_when_asked(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('clean', tmpdir)
            exit_code, reportdir = run_analyzer(tmpdir, cdb, ['--keep-empty'])
            self.assertTrue(os.path.isdir(reportdir))
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_regular_keeps_report_dir()
def tests.functional.cases.test_from_cdb.OutputDirectoryTest.test_regular_keeps_report_dir (self)
Definition at line 37 of file test_from_cdb.py.
    def test_regular_keeps_report_dir(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('regular', tmpdir)
            exit_code, reportdir = run_analyzer(tmpdir, cdb, [])
            self.assertTrue(os.path.isdir(reportdir))
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/cases/test_from_cdb.py