clang::cxindex::AttrListInfo Class Reference
#include <CXIndexDataConsumer.h>
Public Member Functions
AttrListInfo (const Decl *D, CXIndexDataConsumer &IdxCtx)
const CXIdxAttrInfo *const * getAttrs () const
unsigned getNumAttrs () const
void Retain ()
void Release ()
Static Public Member Functions
static IntrusiveRefCntPtr< AttrListInfo > create (const Decl *D, CXIndexDataConsumer &IdxCtx)
Detailed Description
Definition at line 239 of file CXIndexDataConsumer.h.
Constructor & Destructor Documentation
AttrListInfo()
AttrListInfo::AttrListInfo (const Decl * D, CXIndexDataConsumer & IdxCtx)
Definition at line 279 of file CXIndexDataConsumer.cpp.
  : SA(IdxCtx), ref_cnt(0) {
  if (!D->hasAttrs())
    return;
  for (const auto *A : D->attrs()) {
    CXCursor C = MakeCXCursor(A, D, IdxCtx.CXTU);
    CXIdxLoc Loc = IdxCtx.getIndexLoc(A->getLocation());
    switch (C.kind) {
    default:
      Attrs.push_back(AttrInfo(CXIdxAttr_Unexposed, C, Loc, A));
      break;
    case CXCursor_IBActionAttr:
      Attrs.push_back(AttrInfo(CXIdxAttr_IBAction, C, Loc, A));
      break;
    case CXCursor_IBOutletAttr:
      Attrs.push_back(AttrInfo(CXIdxAttr_IBOutlet, C, Loc, A));
      break;
    case CXCursor_IBOutletCollectionAttr:
      IBCollAttrs.push_back(IBOutletCollectionInfo(C, Loc, A));
      break;
    }
  }
  for (unsigned i = 0, e = IBCollAttrs.size(); i != e; ++i) {
    IBOutletCollectionInfo &IBInfo = IBCollAttrs[i];
    CXAttrs.push_back(&IBInfo);
    const IBOutletCollectionAttr *
      IBAttr = cast<IBOutletCollectionAttr>(IBInfo.A);
    SourceLocation InterfaceLocStart =
        IBAttr->getInterfaceLoc()->getTypeLoc().getBeginLoc();
    IBInfo.IBCollInfo.attrInfo = &IBInfo;
    IBInfo.IBCollInfo.classLoc = IdxCtx.getIndexLoc(InterfaceLocStart);
    IBInfo.IBCollInfo.objcClass = nullptr;
    IBInfo.IBCollInfo.classCursor = clang_getNullCursor();
    QualType Ty = IBAttr->getInterface();
    if (const ObjCObjectType *ObjectTy = Ty->getAs<ObjCObjectType>()) {
      if (const ObjCInterfaceDecl *InterD = ObjectTy->getInterface()) {
        IdxCtx.getEntityInfo(InterD, IBInfo.ClassInfo, SA);
        IBInfo.IBCollInfo.objcClass = &IBInfo.ClassInfo;
        IBInfo.IBCollInfo.classCursor =
            MakeCursorObjCClassRef(InterD, InterfaceLocStart, IdxCtx.CXTU);
      }
    }
  }
  for (unsigned i = 0, e = Attrs.size(); i != e; ++i)
    CXAttrs.push_back(&Attrs[i]);
}
References clang::cxindex::AttrInfo::A, clang_getNullCursor(), clang::cxindex::IBOutletCollectionInfo::ClassInfo, clang::cxindex::IBOutletCollectionInfo::IBCollInfo, clang::cxcursor::MakeCursorObjCClassRef(), and clang::cxcursor::MakeCXCursor().
Member Function Documentation
create()
IntrusiveRefCntPtr< AttrListInfo > AttrListInfo::create (const Decl * D, CXIndexDataConsumer & IdxCtx) [static]
Definition at line 332 of file CXIndexDataConsumer.cpp.
                                                               {
  ScratchAlloc SA(IdxCtx);
  AttrListInfo *attrs = SA.allocate<AttrListInfo>();
  return new (attrs) AttrListInfo(D, IdxCtx);
}
References clang::cxindex::ScratchAlloc::allocate().
getAttrs()
const CXIdxAttrInfo* const* clang::cxindex::AttrListInfo::getAttrs () const [inline]
Definition at line 255 of file CXIndexDataConsumer.h.
                                               {
    if (CXAttrs.empty())
      return nullptr;
    return CXAttrs.data();
  }
getNumAttrs()
unsigned clang::cxindex::AttrListInfo::getNumAttrs () const [inline]
Definition at line 260 of file CXIndexDataConsumer.h.
{ return (unsigned)CXAttrs.size(); }
Release()
void clang::cxindex::AttrListInfo::Release () [inline]
Definition at line 266 of file CXIndexDataConsumer.h.
                 {
    assert (ref_cnt > 0 && "Reference count is already zero.");
    if (--ref_cnt == 0) {
      // Memory is allocated from a BumpPtrAllocator, no need to delete it.
      this->~AttrListInfo();
    }
  }
Retain()
void clang::cxindex::AttrListInfo::Retain () [inline]
Retain/Release only useful when we allocate a AttrListInfo from the BumpPtrAllocator, and not from the stack; so that we keep a pointer
Definition at line 265 of file CXIndexDataConsumer.h.
{ ++ref_cnt; }
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.cpp