tests.functional.cases.test_exec_anatomy.ExecAnatomyTest Class Reference
Public Member Functions
def assertEqualJson (self, expected, result)
def test_all_exec_calls (self)
Detailed Description
Definition at line 31 of file test_exec_anatomy.py.
Member Function Documentation
assertEqualJson()
def tests.functional.cases.test_exec_anatomy.ExecAnatomyTest.assertEqualJson (self, expected, result)
Definition at line 32 of file test_exec_anatomy.py.
    def assertEqualJson(self, expected, result):
        def read_json(filename):
            with open(filename) as handler:
                return json.load(handler)
        lhs = read_json(expected)
        rhs = read_json(result)
        for item in lhs:
            self.assertTrue(rhs.count(item))
        for item in rhs:
            self.assertTrue(lhs.count(item))
References startfile.open().
Referenced by tests.functional.cases.test_exec_anatomy.ExecAnatomyTest.test_all_exec_calls().
test_all_exec_calls()
def tests.functional.cases.test_exec_anatomy.ExecAnatomyTest.test_all_exec_calls (self)
Definition at line 44 of file test_exec_anatomy.py.
    def test_all_exec_calls(self):
        this_dir, _ = os.path.split(__file__)
        source_dir = os.path.abspath(os.path.join(this_dir, '..', 'exec'))
        with libear.TemporaryDirectory() as tmp_dir:
            expected, result = run(source_dir, tmp_dir)
            self.assertEqualJson(expected, result)
References tests.functional.cases.test_exec_anatomy.ExecAnatomyTest.assertEqualJson(), tests.functional.cases.test_exec_anatomy.run(), and libear.TemporaryDirectory().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/cases/test_exec_anatomy.py