clang::CIndexer Class Reference
#include <CIndexer.h>
Public Member Functions
CIndexer (std::shared_ptr< PCHContainerOperations > PCHContainerOps=std::make_shared< PCHContainerOperations >())
bool getOnlyLocalDecls () const
void setOnlyLocalDecls (bool Local=true)
bool getDisplayDiagnostics () const
void setDisplayDiagnostics (bool Display=true)
std::shared_ptr< PCHContainerOperations > getPCHContainerOperations () const
unsigned getCXGlobalOptFlags () const
void setCXGlobalOptFlags (unsigned options)
bool isOptEnabled (CXGlobalOptFlags opt) const
const std::string & getClangResourcesPath ()
Get the path of the clang resource files.
StringRef getClangToolchainPath ()
void setInvocationEmissionPath (StringRef Str)
StringRef getInvocationEmissionPath () const
Detailed Description
Definition at line 34 of file CIndexer.h.
Constructor & Destructor Documentation
CIndexer()
clang::CIndexer::CIndexer (std::shared_ptr< PCHContainerOperations > PCHContainerOps = std::make_shared<PCHContainerOperations>()) [inline]
Definition at line 47 of file CIndexer.h.
      : OnlyLocalDecls(false), DisplayDiagnostics(false),
        Options(CXGlobalOpt_None), PCHContainerOps(std::move(PCHContainerOps)) {
  }
Member Function Documentation
getClangResourcesPath()
const std::string & CIndexer::getClangResourcesPath ()
Get the path of the clang resource files.
Definition at line 99 of file CIndexer.cpp.
                                                 {
  // Did we already compute the path?
  if (!ResourcesPath.empty())
    return ResourcesPath;
  SmallString<128> LibClangPath;
  // Find the location where this library lives (libclang.dylib).
#ifdef _WIN32
  MEMORY_BASIC_INFORMATION mbi;
  char path[MAX_PATH];
  VirtualQuery((void *)(uintptr_t)clang_createTranslationUnit, &mbi,
               sizeof(mbi));
  GetModuleFileNameA((HINSTANCE)mbi.AllocationBase, path, MAX_PATH);
#ifdef __CYGWIN__
  char w32path[MAX_PATH];
  strcpy(w32path, path);
#if CYGWIN_VERSION_API_MAJOR > 0 || CYGWIN_VERSION_API_MINOR >= 181
  cygwin_conv_path(CCP_WIN_A_TO_POSIX, w32path, path, MAX_PATH);
#else
  cygwin_conv_to_full_posix_path(w32path, path);
#endif
#endif
  LibClangPath += path;
#elif defined(_AIX)
  getClangResourcesPathImplAIX(LibClangPath);
#else
  // This silly cast below avoids a C++ warning.
  Dl_info info;
  if (dladdr((void *)(uintptr_t)clang_createTranslationUnit, &info) == 0)
    llvm_unreachable("Call to dladdr() failed");
  // We now have the CIndex directory, locate clang relative to it.
  LibClangPath += info.dli_fname;
#endif
  // Cache our result.
  ResourcesPath = driver::Driver::GetResourcesPath(LibClangPath);
  return ResourcesPath;
}
References clang_createTranslationUnit().
Referenced by getClangToolchainPath().
getClangToolchainPath()
StringRef CIndexer::getClangToolchainPath ()
Definition at line 142 of file CIndexer.cpp.
                                          {
  if (!ToolchainPath.empty())
    return ToolchainPath;
  StringRef ResourcePath = getClangResourcesPath();
  ToolchainPath =
      std::string(llvm::sys::path::parent_path(llvm::sys::path::parent_path(
          llvm::sys::path::parent_path(ResourcePath))));
  return ToolchainPath;
}
References getClangResourcesPath().
Referenced by clang::LibclangInvocationReporter::LibclangInvocationReporter().
getCXGlobalOptFlags()
unsigned clang::CIndexer::getCXGlobalOptFlags () const [inline]
Definition at line 68 of file CIndexer.h.
{ return Options; }
getDisplayDiagnostics()
bool clang::CIndexer::getDisplayDiagnostics () const [inline]
Definition at line 59 of file CIndexer.h.
{ return DisplayDiagnostics; }
getInvocationEmissionPath()
StringRef clang::CIndexer::getInvocationEmissionPath () const [inline]
Definition at line 84 of file CIndexer.h.
{ return InvocationEmissionPath; }
Referenced by clang::LibclangInvocationReporter::LibclangInvocationReporter().
getOnlyLocalDecls()
bool clang::CIndexer::getOnlyLocalDecls () const [inline]
Whether we only want to see `local` declarations (that did not come from a previous precompiled header). If false, we want to see all declarations.
Definition at line 56 of file CIndexer.h.
{ return OnlyLocalDecls; }
getPCHContainerOperations()
std::shared_ptr<PCHContainerOperations> clang::CIndexer::getPCHContainerOperations () const [inline]
Definition at line 64 of file CIndexer.h.
                                                                          {
    return PCHContainerOps;
  }
isOptEnabled()
bool clang::CIndexer::isOptEnabled (CXGlobalOptFlags opt) const [inline]
Definition at line 71 of file CIndexer.h.
                                                {
    return Options & opt;
  }
setCXGlobalOptFlags()
void clang::CIndexer::setCXGlobalOptFlags (unsigned options) [inline]
Definition at line 69 of file CIndexer.h.
{ Options = options; }
setDisplayDiagnostics()
void clang::CIndexer::setDisplayDiagnostics (bool Display = true) [inline]
Definition at line 60 of file CIndexer.h.
                                                  {
    DisplayDiagnostics = Display;
  }
setInvocationEmissionPath()
void clang::CIndexer::setInvocationEmissionPath (StringRef Str) [inline]
Definition at line 80 of file CIndexer.h.
                                                {
    InvocationEmissionPath = std::string(Str);
  }
setOnlyLocalDecls()
void clang::CIndexer::setOnlyLocalDecls (bool Local = true) [inline]
Definition at line 57 of file CIndexer.h.
{ OnlyLocalDecls = Local; }
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexer.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexer.cpp