clang::cxcursor::MacroExpansionCursor Class Reference
#include <CXCursor.h>
Public Member Functions
MacroExpansionCursor (CXCursor C)
const IdentifierInfo * getName () const
const MacroDefinitionRecord * getDefinition () const
SourceRange getSourceRange () const
Detailed Description
Wraps a macro expansion cursor and provides a common interface for a normal macro expansion cursor or a `pseudo` one.
`Pseudo` macro expansion cursors (essentially a macro definition along with a source location) are created in special cases, for example they can be created for identifiers inside macro definitions, if these identifiers are macro names.
Definition at line 166 of file CXCursor.h.
Constructor & Destructor Documentation
MacroExpansionCursor()
clang::cxcursor::MacroExpansionCursor::MacroExpansionCursor (CXCursor C) [inline]
Definition at line 184 of file CXCursor.h.
                                   : C(C) {
    assert(C.kind == CXCursor_MacroExpansion);
  }
Member Function Documentation
getDefinition()
const MacroDefinitionRecord * cxcursor::MacroExpansionCursor::getDefinition () const
Definition at line 1023 of file CXCursor.cpp.
                                                  {
  if (isPseudo())
    return getAsMacroDefinition();
  return getAsMacroExpansion()->getDefinition();
}
getName()
const IdentifierInfo * cxcursor::MacroExpansionCursor::getName () const
Definition at line 1017 of file CXCursor.cpp.
                                                                  {
  if (isPseudo())
    return getAsMacroDefinition()->getName();
  return getAsMacroExpansion()->getName();
}
Referenced by Reporter.TextParameter::getHTML(), Reporter.SelectionParameter::getHTML(), and Reporter.ReporterParameter::getValue().
getSourceRange()
SourceRange cxcursor::MacroExpansionCursor::getSourceRange () const
Definition at line 1028 of file CXCursor.cpp.
                                                               {
  if (isPseudo())
    return getPseudoLoc();
  return getAsMacroExpansion()->getSourceRange();
}
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CXCursor.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CXCursor.cpp