clang::cxindex::Logger Class Reference
#include <CLog.h>
Public Member Functions
Logger (llvm::StringRef name, bool trace)
~Logger ()
Logger & operator<< (CXTranslationUnit)
Logger & operator<< (const FileEntry *FE)
Logger & operator<< (CXCursor cursor)
Logger & operator<< (CXSourceLocation)
Logger & operator<< (CXSourceRange)
Logger & operator<< (CXString)
Logger & operator<< (llvm::StringRef Str)
Logger & operator<< (const char *Str)
Logger & operator<< (unsigned long N)
Logger & operator<< (long N)
Logger & operator<< (unsigned int N)
Logger & operator<< (int N)
Logger & operator<< (char C)
Logger & operator<< (unsigned char C)
Logger & operator<< (signed char C)
Logger & operator<< (const llvm::format_object_base &Fmt)
Static Public Member Functions
static const char * getEnvVar ()
static bool isLoggingEnabled ()
static bool isStackTracingEnabled ()
static LogRef make (llvm::StringRef name, bool trace=isStackTracingEnabled())
Detailed Description
Collects logging output and writes it to stderr when it's destructed. Common use case:
if (LogRef Log = Logger::make(__func__)) {
  *Log << "stuff";
}
Definition at line 40 of file CLog.h.
Constructor & Destructor Documentation
Logger()
clang::cxindex::Logger::Logger (llvm::StringRef name, bool trace) [inline], [explicit]
Definition at line 63 of file CLog.h.
      : Name(std::string(name)), Trace(trace), LogOS(Msg) {}
Referenced by make().
 Logger()
cxindex::Logger::~Logger ()
Definition at line 9189 of file CIndex.cpp.
                       {
  std::lock_guard<std::mutex> L(*LoggingMutex);
  static llvm::TimeRecord sBeginTR = llvm::TimeRecord::getCurrentTime();
  raw_ostream &OS = llvm::errs();
  OS << "[libclang:" << Name << ':';
#ifdef USE_DARWIN_THREADS
  // TODO: Portability.
  mach_port_t tid = pthread_mach_thread_np(pthread_self());
  OS << tid << ':';
#endif
  llvm::TimeRecord TR = llvm::TimeRecord::getCurrentTime();
  OS << llvm::format("%7.4f] ", TR.getWallTime() - sBeginTR.getWallTime());
  OS << Msg << '\n';
  if (Trace) {
    llvm::sys::PrintStackTrace(OS);
    OS << "--------------------------------------------------\n";
  }
}
Member Function Documentation
getEnvVar()
static const char* clang::cxindex::Logger::getEnvVar () [inline], [static]
Definition at line 46 of file CLog.h.
                                 {
    static const char *sCachedVar = ::getenv("LIBCLANG_LOGGING");
    return sCachedVar;
  }
Referenced by isLoggingEnabled(), and isStackTracingEnabled().
isLoggingEnabled()
static bool clang::cxindex::Logger::isLoggingEnabled () [inline], [static]
Definition at line 50 of file CLog.h.
{ return getEnvVar() != nullptr; }
References getEnvVar().
Referenced by make().
isStackTracingEnabled()
static bool clang::cxindex::Logger::isStackTracingEnabled () [inline], [static]
Definition at line 51 of file CLog.h.
                                      {
    if (const char *EnvOpt = Logger::getEnvVar())
      return llvm::StringRef(EnvOpt) == "2";
    return false;
  }
References getEnvVar().
make()
static LogRef clang::cxindex::Logger::make (llvm::StringRef name, bool trace = isStackTracingEnabled()) [inline], [static]
Definition at line 56 of file CLog.h.
                                                           {
    if (isLoggingEnabled())
      return new Logger(name, trace);
    return nullptr;
  }
References isLoggingEnabled(), and Logger().
Referenced by clang_getLocation().
operator<<() [1/16]
Logger& clang::cxindex::Logger::operator<< (char C) [inline]
Definition at line 83 of file CLog.h.
{ LogOS << C; return *this; }
operator<<() [2/16]
Logger& clang::cxindex::Logger::operator<< (const char * Str) [inline]
Definition at line 74 of file CLog.h.
                                      {
    if (Str)
      LogOS << Str;
    return *this;
  }
operator<<() [3/16]
Logger & cxindex::Logger::operator<< (const FileEntry * FE)
Definition at line 9127 of file CIndex.cpp.
                                                     {
  *this << FE->getName();
  return *this;
}
operator<<() [4/16]
Logger & cxindex::Logger::operator<< (const llvm::format_object_base & Fmt)
Definition at line 9182 of file CIndex.cpp.
                                                                   {
  LogOS << Fmt;
  return *this;
}
operator<<() [5/16]
Logger & cxindex::Logger::operator<< (CXCursor cursor)
Definition at line 9132 of file CIndex.cpp.
                                                 {
  CXString cursorName = clang_getCursorDisplayName(cursor);
  *this << cursorName << "@" << clang_getCursorLocation(cursor);
  clang_disposeString(cursorName);
  return *this;
}
References clang_disposeString(), clang_getCursorDisplayName(), and clang_getCursorLocation().
operator<<() [6/16]
Logger & cxindex::Logger::operator<< (CXSourceLocation Loc)
Definition at line 9139 of file CIndex.cpp.
                                                      {
  CXFile File;
  unsigned Line, Column;
  clang_getFileLocation(Loc, &File, &Line, &Column, nullptr);
  CXString FileName = clang_getFileName(File);
  *this << llvm::format("(%s:%d:%d)", clang_getCString(FileName), Line, Column);
  clang_disposeString(FileName);
  return *this;
}
References clang_getFileLocation(), and clang_getFileName().
operator<<() [7/16]
Logger & cxindex::Logger::operator<< (CXSourceRange range)
Definition at line 9149 of file CIndex.cpp.
                                                     {
  CXSourceLocation BLoc = clang_getRangeStart(range);
  CXSourceLocation ELoc = clang_getRangeEnd(range);
  CXFile BFile;
  unsigned BLine, BColumn;
  clang_getFileLocation(BLoc, &BFile, &BLine, &BColumn, nullptr);
  CXFile EFile;
  unsigned ELine, EColumn;
  clang_getFileLocation(ELoc, &EFile, &ELine, &EColumn, nullptr);
  CXString BFileName = clang_getFileName(BFile);
  if (BFile == EFile) {
    *this << llvm::format("[%s %d:%d-%d:%d]", clang_getCString(BFileName),
                          BLine, BColumn, ELine, EColumn);
  } else {
    CXString EFileName = clang_getFileName(EFile);
    *this << llvm::format("[%s:%d:%d - ", clang_getCString(BFileName), BLine,
                          BColumn)
          << llvm::format("%s:%d:%d]", clang_getCString(EFileName), ELine,
                          EColumn);
    clang_disposeString(EFileName);
  }
  clang_disposeString(BFileName);
  return *this;
}
References clang_getFileLocation(), clang_getFileName(), clang_getRangeEnd(), and clang_getRangeStart().
operator<<() [8/16]
Logger & cxindex::Logger::operator<< (CXString Str)
Definition at line 9177 of file CIndex.cpp.
                                              {
  *this << clang_getCString(Str);
  return *this;
}
References clang_getCString().
operator<<() [9/16]
Logger & cxindex::Logger::operator<< (CXTranslationUnit TU)
Definition at line 9113 of file CIndex.cpp.
                                                      {
  if (TU) {
    if (ASTUnit *Unit = cxtu::getASTUnit(TU)) {
      LogOS << '<' << Unit->getMainFileName() << '>';
      if (Unit->isMainFileAST())
        LogOS << " (" << Unit->getASTFileName() << ')';
      return *this;
    }
  } else {
    LogOS << "<NULL TU>";
  }
  return *this;
}
operator<<() [10/16]
Logger& clang::cxindex::Logger::operator<< (int N) [inline]
Definition at line 82 of file CLog.h.
{ LogOS << N; return *this; }
operator<<() [11/16]
Logger& clang::cxindex::Logger::operator<< (llvm::StringRef Str) [inline]
Definition at line 73 of file CLog.h.
{ LogOS << Str; return *this; }
operator<<() [12/16]
Logger& clang::cxindex::Logger::operator<< (long N) [inline]
Definition at line 80 of file CLog.h.
{ LogOS << N ; return *this; }
operator<<() [13/16]
Logger& clang::cxindex::Logger::operator<< (signed char C) [inline]
Definition at line 85 of file CLog.h.
{ LogOS << C; return *this; }
operator<<() [14/16]
Logger& clang::cxindex::Logger::operator<< (unsigned char C) [inline]
Definition at line 84 of file CLog.h.
{ LogOS << C; return *this; }
operator<<() [15/16]
Logger& clang::cxindex::Logger::operator<< (unsigned int N) [inline]
Definition at line 81 of file CLog.h.
{ LogOS << N; return *this; }
operator<<() [16/16]
Logger& clang::cxindex::Logger::operator<< (unsigned long N) [inline]
Definition at line 79 of file CLog.h.
{ LogOS << N; return *this; }
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CLog.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndex.cpp