tests.unit.test_analyze.ReportFailureTest Class Reference
Public Member Functions
def assertUnderFailures (self, path)
def test_report_failure_create_files (self)
Detailed Description
Definition at line 185 of file test_analyze.py.
Member Function Documentation
assertUnderFailures()
def tests.unit.test_analyze.ReportFailureTest.assertUnderFailures (self, path)
Definition at line 187 of file test_analyze.py.
    def assertUnderFailures(self, path):
        self.assertEqual('failures', os.path.basename(os.path.dirname(path)))
Referenced by tests.unit.test_analyze.ReportFailureTest.test_report_failure_create_files().
test_report_failure_create_files()
def tests.unit.test_analyze.ReportFailureTest.test_report_failure_create_files (self)
Definition at line 190 of file test_analyze.py.
    def test_report_failure_create_files(self):
        with libear.TemporaryDirectory() as tmpdir:
            # create input file
            filename = os.path.join(tmpdir, 'test.c')
            with open(filename, 'w') as handle:
                handle.write('int main() { return 0')
            uname_msg = ' '.join(os.uname()) + os.linesep
            error_msg = 'this is my error output'
            # execute test
            opts = {
                'clang': 'clang',
                'directory': os.getcwd(),
                'flags': [],
                'file': filename,
                'output_dir': tmpdir,
                'language': 'c',
                'error_type': 'other_error',
                'error_output': error_msg,
                'exit_code': 13
            }
            sut.report_failure(opts)
            # verify the result
            result = dict()
            pp_file = None
            for root, _, files in os.walk(tmpdir):
                keys = [os.path.join(root, name) for name in files]
                for key in keys:
                    with open(key, 'r') as handle:
                        result[key] = handle.readlines()
                    if re.match(r'^(.*/)+clang(.*)\.i$', key):
                        pp_file = key
            # prepocessor file generated
            self.assertUnderFailures(pp_file)
            # info file generated and content dumped
            info_file = pp_file + '.info.txt'
            self.assertTrue(info_file in result)
            self.assertEqual('Other Error\n', result[info_file][1])
            self.assertEqual(uname_msg, result[info_file][3])
            # error file generated and content dumped
            error_file = pp_file + '.stderr.txt'
            self.assertTrue(error_file in result)
            self.assertEqual([error_msg], result[error_file])
References tests.unit.test_analyze.ReportFailureTest.assertUnderFailures(), startfile.open(), and libear.TemporaryDirectory().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/unit/test_analyze.py