tests.functional.cases.test_from_cdb.ExitCodeTest Class Reference
Public Member Functions
def test_regular_does_not_set_exit_code (self)
def test_clear_does_not_set_exit_code (self)
def test_regular_sets_exit_code_if_asked (self)
def test_clear_does_not_set_exit_code_if_asked (self)
def test_regular_sets_exit_code_if_asked_from_plist (self)
def test_clear_does_not_set_exit_code_if_asked_from_plist (self)
Detailed Description
Definition at line 56 of file test_from_cdb.py.
Member Function Documentation
test_clear_does_not_set_exit_code()
def tests.functional.cases.test_from_cdb.ExitCodeTest.test_clear_does_not_set_exit_code (self)
Definition at line 63 of file test_from_cdb.py.
    def test_clear_does_not_set_exit_code(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('clean', tmpdir)
            exit_code, __ = run_analyzer(tmpdir, cdb, [])
            self.assertFalse(exit_code)
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_clear_does_not_set_exit_code_if_asked()
def tests.functional.cases.test_from_cdb.ExitCodeTest.test_clear_does_not_set_exit_code_if_asked (self)
Definition at line 75 of file test_from_cdb.py.
    def test_clear_does_not_set_exit_code_if_asked(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('clean', tmpdir)
            exit_code, __ = run_analyzer(tmpdir, cdb, ['--status-bugs'])
            self.assertFalse(exit_code)
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_clear_does_not_set_exit_code_if_asked_from_plist()
def tests.functional.cases.test_from_cdb.ExitCodeTest.test_clear_does_not_set_exit_code_if_asked_from_plist (self)
Definition at line 88 of file test_from_cdb.py.
    def test_clear_does_not_set_exit_code_if_asked_from_plist(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('clean', tmpdir)
            exit_code, __ = run_analyzer(
                tmpdir, cdb, ['--status-bugs', '--plist'])
            self.assertFalse(exit_code)
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_regular_does_not_set_exit_code()
def tests.functional.cases.test_from_cdb.ExitCodeTest.test_regular_does_not_set_exit_code (self)
Definition at line 57 of file test_from_cdb.py.
    def test_regular_does_not_set_exit_code(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('regular', tmpdir)
            exit_code, __ = run_analyzer(tmpdir, cdb, [])
            self.assertFalse(exit_code)
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_regular_sets_exit_code_if_asked()
def tests.functional.cases.test_from_cdb.ExitCodeTest.test_regular_sets_exit_code_if_asked (self)
Definition at line 69 of file test_from_cdb.py.
    def test_regular_sets_exit_code_if_asked(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('regular', tmpdir)
            exit_code, __ = run_analyzer(tmpdir, cdb, ['--status-bugs'])
            self.assertTrue(exit_code)
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_regular_sets_exit_code_if_asked_from_plist()
def tests.functional.cases.test_from_cdb.ExitCodeTest.test_regular_sets_exit_code_if_asked_from_plist (self)
Definition at line 81 of file test_from_cdb.py.
    def test_regular_sets_exit_code_if_asked_from_plist(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('regular', tmpdir)
            exit_code, __ = run_analyzer(
                tmpdir, cdb, ['--status-bugs', '--plist'])
            self.assertTrue(exit_code)
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/cases/test_from_cdb.py