tests.functional.cases.test_from_cdb.TitleTest Class Reference
Public Member Functions
def assertTitleEqual (self, directory, expected)
def test_default_title_in_report (self)
def test_given_title_in_report (self)
Detailed Description
Definition at line 181 of file test_from_cdb.py.
Member Function Documentation
assertTitleEqual()
def tests.functional.cases.test_from_cdb.TitleTest.assertTitleEqual (self, directory, expected)
Definition at line 182 of file test_from_cdb.py.
    def assertTitleEqual(self, directory, expected):
        import re
        patterns = [
            re.compile(r'<title>(?P<page>.*)</title>'),
            re.compile(r'<h1>(?P<head>.*)</h1>')
        ]
        result = dict()
        index = os.path.join(directory, 'index.html')
        with open(index, 'r') as handler:
            for line in handler.readlines():
                for regex in patterns:
                    match = regex.match(line.strip())
                    if match:
                        result.update(match.groupdict())
                        break
        self.assertEqual(result['page'], result['head'])
        self.assertEqual(result['page'], expected)
References startfile.open().
Referenced by tests.functional.cases.test_from_cdb.TitleTest.test_default_title_in_report(), and tests.functional.cases.test_from_cdb.TitleTest.test_given_title_in_report().
test_default_title_in_report()
def tests.functional.cases.test_from_cdb.TitleTest.test_default_title_in_report (self)
Definition at line 201 of file test_from_cdb.py.
    def test_default_title_in_report(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('broken', tmpdir)
            exit_code, reportdir = run_analyzer(tmpdir, cdb, [])
            self.assertTitleEqual(reportdir, 'src - analyzer results')
References tests.functional.cases.test_from_cdb.TitleTest.assertTitleEqual(), tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_given_title_in_report()
def tests.functional.cases.test_from_cdb.TitleTest.test_given_title_in_report (self)
Definition at line 207 of file test_from_cdb.py.
    def test_given_title_in_report(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('broken', tmpdir)
            exit_code, reportdir = run_analyzer(
                tmpdir, cdb, ['--html-title', 'this is the title'])
            self.assertTitleEqual(reportdir, 'this is the title')
References tests.functional.cases.test_from_cdb.TitleTest.assertTitleEqual(), tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/cases/test_from_cdb.py