tests.unit.test_analyze.RunAnalyzerTest Class Reference
Public Member Functions
def test_run_analyzer (self)
def test_run_analyzer_crash (self)
def test_run_analyzer_crash_and_forwarded (self)
def test_run_analyzer_with_sarif (self)
Static Public Member Functions
def run_analyzer (content, failures_report, output_format='plist')
Detailed Description
Definition at line 128 of file test_analyze.py.
Member Function Documentation
run_analyzer()
def tests.unit.test_analyze.RunAnalyzerTest.run_analyzer (content, failures_report, output_format = 'plist') [static]
Definition at line 131 of file test_analyze.py.
    def run_analyzer(content, failures_report, output_format='plist'):
        with libear.TemporaryDirectory() as tmpdir:
            filename = os.path.join(tmpdir, 'test.cpp')
            with open(filename, 'w') as handle:
                handle.write(content)
            opts = {
                'clang': 'clang',
                'directory': os.getcwd(),
                'flags': [],
                'direct_args': [],
                'file': filename,
                'output_dir': tmpdir,
                'output_format': output_format,
                'output_failures': failures_report
            }
            spy = Spy()
            result = sut.run_analyzer(opts, spy.call)
            output_files = []
            for entry in os.listdir(tmpdir):
                output_files.append(entry)
            return (result, spy.arg, output_files)
References startfile.open(), and libear.TemporaryDirectory().
Referenced by tests.functional.cases.test_from_cmd.OutputDirectoryTest.test_clear_deletes_report_dir(), tests.functional.cases.test_from_cmd.OutputDirectoryTest.test_clear_keeps_report_dir_when_asked(), and tests.functional.cases.test_from_cmd.OutputDirectoryTest.test_regular_keeps_report_dir().
test_run_analyzer()
def tests.unit.test_analyze.RunAnalyzerTest.test_run_analyzer (self)
Definition at line 154 of file test_analyze.py.
    def test_run_analyzer(self):
        content = "int div(int n, int d) { return n / d; }"
        (result, fwds, _) = RunAnalyzerTest.run_analyzer(content, False)
        self.assertEqual(None, fwds)
        self.assertEqual(0, result['exit_code'])
test_run_analyzer_crash()
def tests.unit.test_analyze.RunAnalyzerTest.test_run_analyzer_crash (self)
Definition at line 160 of file test_analyze.py.
    def test_run_analyzer_crash(self):
        content = "int div(int n, int d) { return n / d }"
        (result, fwds, _) = RunAnalyzerTest.run_analyzer(content, False)
        self.assertEqual(None, fwds)
        self.assertEqual(1, result['exit_code'])
test_run_analyzer_crash_and_forwarded()
def tests.unit.test_analyze.RunAnalyzerTest.test_run_analyzer_crash_and_forwarded (self)
Definition at line 166 of file test_analyze.py.
    def test_run_analyzer_crash_and_forwarded(self):
        content = "int div(int n, int d) { return n / d }"
        (_, fwds, _) = RunAnalyzerTest.run_analyzer(content, True)
        self.assertEqual(1, fwds['exit_code'])
        self.assertTrue(len(fwds['error_output']) > 0)
test_run_analyzer_with_sarif()
def tests.unit.test_analyze.RunAnalyzerTest.test_run_analyzer_with_sarif (self)
Definition at line 172 of file test_analyze.py.
    def test_run_analyzer_with_sarif(self):
        content = "int div(int n, int d) { return n / d; }"
        (result, fwds, output_files) = RunAnalyzerTest.run_analyzer(content, False, output_format='sarif')
        self.assertEqual(None, fwds)
        self.assertEqual(0, result['exit_code'])
        pattern = re.compile(r'^result-.+\.sarif$')
        for f in output_files:
            if re.match(pattern, f):
                return
        self.fail('no result sarif files found in output')
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/unit/test_analyze.py