clang::cxindex::ScratchAlloc Class Reference
#include <CXIndexDataConsumer.h>
Public Member Functions
ScratchAlloc (CXIndexDataConsumer &indexCtx)
ScratchAlloc (const ScratchAlloc &SA)
~ScratchAlloc ()
const char * toCStr (StringRef Str)
const char * copyCStr (StringRef Str)
template<typename T >
T * allocate ()
Detailed Description
Definition at line 32 of file CXIndexDataConsumer.h.
Constructor & Destructor Documentation
ScratchAlloc() [1/2]
clang::cxindex::ScratchAlloc::ScratchAlloc (CXIndexDataConsumer & indexCtx) [inline], [explicit]
Definition at line 481 of file CXIndexDataConsumer.h.
                                                             : IdxCtx(idxCtx) {
  ++IdxCtx.StrAdapterCount;
}
ScratchAlloc() [2/2]
clang::cxindex::ScratchAlloc::ScratchAlloc (const ScratchAlloc & SA) [inline]
Definition at line 484 of file CXIndexDataConsumer.h.
                                                        : IdxCtx(SA.IdxCtx) {
  ++IdxCtx.StrAdapterCount;
}
 ScratchAlloc()
clang::cxindex::ScratchAlloc::~ScratchAlloc () [inline]
Definition at line 488 of file CXIndexDataConsumer.h.
                                   {
  --IdxCtx.StrAdapterCount;
  if (IdxCtx.StrAdapterCount == 0)
    IdxCtx.StrScratch.Reset();
}
Member Function Documentation
allocate()
template<typename T >
T * clang::cxindex::ScratchAlloc::allocate [inline]
Definition at line 495 of file CXIndexDataConsumer.h.
                                 {
  return IdxCtx.StrScratch.Allocate<T>();
}
Referenced by clang::cxindex::AttrListInfo::create().
copyCStr()
const char * ScratchAlloc::copyCStr (StringRef Str)
Definition at line 404 of file CXIndexDataConsumer.cpp.
                                                {
  char *buf = IdxCtx.StrScratch.Allocate<char>(Str.size() + 1);
  std::uninitialized_copy(Str.begin(), Str.end(), buf);
  buf[Str.size()] = '\0';
  return buf;
}
Referenced by toCStr().
toCStr()
const char * ScratchAlloc::toCStr (StringRef Str)
Definition at line 396 of file CXIndexDataConsumer.cpp.
                                              {
  if (Str.empty())
    return "";
  if (Str.data()[Str.size()] == '\0')
    return Str.data();
  return copyCStr(Str);
}
References copyCStr().
Referenced by clang::cxindex::CXIndexDataConsumer::ppIncludedFile().
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.cpp