clang::CXDiagnosticImpl Class Reference
#include <CIndexDiagnostic.h>
Public Types
enum Kind { StoredDiagnosticKind
, LoadedDiagnosticKind
, CustomNoteDiagnosticKind
 }
Public Member Functions
virtual ~CXDiagnosticImpl ()
virtual CXDiagnosticSeverity getSeverity () const =0
Return the severity of the diagnostic.
virtual CXSourceLocation getLocation () const =0
Return the location of the diagnostic.
virtual CXString getSpelling () const =0
Return the spelling of the diagnostic.
virtual CXString getDiagnosticOption (CXString *Disable) const =0
Return the text for the diagnostic option.
virtual unsigned getCategory () const =0
Return the category of the diagnostic.
virtual CXString getCategoryText () const =0
Return the category string of the diagnostic.
virtual unsigned getNumRanges () const =0
Return the number of source ranges for the diagnostic.
virtual CXSourceRange getRange (unsigned Range) const =0
Return the source ranges for the diagnostic.
virtual unsigned getNumFixIts () const =0
Return the number of FixIts.
virtual CXString getFixIt (unsigned FixIt, CXSourceRange *ReplacementRange) const =0
Return the FixIt information (source range and inserted text).
Kind getKind () const
CXDiagnosticSetImpl & getChildDiagnostics ()
Protected Member Functions
CXDiagnosticImpl (Kind k)
void append (std::unique_ptr< CXDiagnosticImpl > D)
Protected Attributes
CXDiagnosticSetImpl ChildDiags
Detailed Description
Definition at line 54 of file CIndexDiagnostic.h.
Member Enumeration Documentation
Kind
enum clang::CXDiagnosticImpl::Kind
Enumerator
StoredDiagnosticKind
LoadedDiagnosticKind
CustomNoteDiagnosticKind
Definition at line 56 of file CIndexDiagnostic.h.
            { StoredDiagnosticKind, LoadedDiagnosticKind,
              CustomNoteDiagnosticKind };
Constructor & Destructor Documentation
 CXDiagnosticImpl()
CXDiagnosticImpl::~CXDiagnosticImpl () [virtual]
Definition at line 37 of file CIndexDiagnostic.cpp.
{}
CXDiagnosticImpl()
clang::CXDiagnosticImpl::CXDiagnosticImpl (Kind k) [inline], [protected]
Definition at line 99 of file CIndexDiagnostic.h.
: K(k) {}
Member Function Documentation
append()
void clang::CXDiagnosticImpl::append (std::unique_ptr< CXDiagnosticImpl > D) [inline], [protected]
Definition at line 102 of file CIndexDiagnostic.h.
                                                 {
    ChildDiags.appendDiagnostic(std::move(D));
  }
References clang::CXDiagnosticSetImpl::appendDiagnostic(), and ChildDiags.
getCategory()
virtual unsigned clang::CXDiagnosticImpl::getCategory () const [pure virtual]
Return the category of the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
getCategoryText()
virtual CXString clang::CXDiagnosticImpl::getCategoryText () const [pure virtual]
Return the category string of the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
getChildDiagnostics()
CXDiagnosticSetImpl& clang::CXDiagnosticImpl::getChildDiagnostics () [inline]
Definition at line 94 of file CIndexDiagnostic.h.
                                             {
    return ChildDiags;
  }
References ChildDiags.
getDiagnosticOption()
virtual CXString clang::CXDiagnosticImpl::getDiagnosticOption (CXString * Disable) const [pure virtual]
Return the text for the diagnostic option.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
getFixIt()
virtual CXString clang::CXDiagnosticImpl::getFixIt (unsigned FixIt, CXSourceRange * ReplacementRange) const [pure virtual]
Return the FixIt information (source range and inserted text).
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
Referenced by clang_getDiagnosticFixIt().
getKind()
Kind clang::CXDiagnosticImpl::getKind () const [inline]
Definition at line 92 of file CIndexDiagnostic.h.
{ return K; }
Referenced by clang::CXStoredDiagnostic::classof(), and clang::CXLoadedDiagnostic::classof().
getLocation()
virtual CXSourceLocation clang::CXDiagnosticImpl::getLocation () const [pure virtual]
Return the location of the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
getNumFixIts()
virtual unsigned clang::CXDiagnosticImpl::getNumFixIts () const [pure virtual]
Return the number of FixIts.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
Referenced by clang_getDiagnosticFixIt().
getNumRanges()
virtual unsigned clang::CXDiagnosticImpl::getNumRanges () const [pure virtual]
Return the number of source ranges for the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
Referenced by clang_getDiagnosticRange().
getRange()
virtual CXSourceRange clang::CXDiagnosticImpl::getRange (unsigned Range) const [pure virtual]
Return the source ranges for the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
Referenced by clang_getDiagnosticRange().
getSeverity()
virtual CXDiagnosticSeverity clang::CXDiagnosticImpl::getSeverity () const [pure virtual]
Return the severity of the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
getSpelling()
virtual CXString clang::CXDiagnosticImpl::getSpelling () const [pure virtual]
Return the spelling of the diagnostic.
Implemented in clang::CXLoadedDiagnostic, and clang::CXStoredDiagnostic.
Member Data Documentation
ChildDiags
CXDiagnosticSetImpl clang::CXDiagnosticImpl::ChildDiags [protected]
Definition at line 100 of file CIndexDiagnostic.h.
Referenced by append(), and getChildDiagnostics().
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.cpp