clang::CXLoadedDiagnostic Class Reference
#include <CXLoadedDiagnostic.h>
Classes
struct Location
Public Types
enum Kind { StoredDiagnosticKind
, LoadedDiagnosticKind
, CustomNoteDiagnosticKind
 }
Public Member Functions
CXLoadedDiagnostic ()
~CXLoadedDiagnostic () override
CXDiagnosticSeverity getSeverity () const override
Return the severity of the diagnostic.
CXSourceLocation getLocation () const override
Return the location of the diagnostic.
CXString getSpelling () const override
Return the spelling of the diagnostic.
CXString getDiagnosticOption (CXString *Disable) const override
Return the text for the diagnostic option.
unsigned getCategory () const override
Return the category of the diagnostic.
CXString getCategoryText () const override
Return the category string of the diagnostic.
unsigned getNumRanges () const override
Return the number of source ranges for the diagnostic.
CXSourceRange getRange (unsigned Range) const override
Return the source ranges for the diagnostic.
unsigned getNumFixIts () const override
Return the number of FixIts.
CXString getFixIt (unsigned FixIt, CXSourceRange *ReplacementRange) const override
Return the FixIt information (source range and inserted text).
Kind getKind () const
CXDiagnosticSetImpl & getChildDiagnostics ()
Static Public Member Functions
static bool classof (const CXDiagnosticImpl *D)
static void decodeLocation (CXSourceLocation location, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
Decode the CXSourceLocation into file, line, column, and offset.
Public Attributes
Location DiagLoc
std::vector< CXSourceRange > Ranges
std::vector< std::pair< CXSourceRange, const char * > > FixIts
const char * Spelling
llvm::StringRef DiagOption
llvm::StringRef CategoryText
unsigned severity
unsigned category
Protected Member Functions
void append (std::unique_ptr< CXDiagnosticImpl > D)
Protected Attributes
CXDiagnosticSetImpl ChildDiags
Detailed Description
Definition at line 23 of file CXLoadedDiagnostic.h.
Member Enumeration Documentation
Kind
enum clang::CXDiagnosticImpl::Kind [inherited]
Enumerator
StoredDiagnosticKind
LoadedDiagnosticKind
CustomNoteDiagnosticKind
Definition at line 56 of file CIndexDiagnostic.h.
            { StoredDiagnosticKind, LoadedDiagnosticKind,
              CustomNoteDiagnosticKind };
Constructor & Destructor Documentation
CXLoadedDiagnostic()
clang::CXLoadedDiagnostic::CXLoadedDiagnostic () [inline]
Definition at line 25 of file CXLoadedDiagnostic.h.
                       : CXDiagnosticImpl(LoadedDiagnosticKind),
    severity(0), category(0) {}
 CXLoadedDiagnostic()
CXLoadedDiagnostic::~CXLoadedDiagnostic () [override]
Definition at line 63 of file CXLoadedDiagnostic.cpp.
{}
Member Function Documentation
append()
void clang::CXDiagnosticImpl::append (std::unique_ptr< CXDiagnosticImpl > D) [inline], [protected], [inherited]
Definition at line 102 of file CIndexDiagnostic.h.
                                                 {
    ChildDiags.appendDiagnostic(std::move(D));
  }
References clang::CXDiagnosticSetImpl::appendDiagnostic(), and clang::CXDiagnosticImpl::ChildDiags.
classof()
static bool clang::CXLoadedDiagnostic::classof (const CXDiagnosticImpl * D) [inline], [static]
Definition at line 61 of file CXLoadedDiagnostic.h.
                                                 {
    return D->getKind() == LoadedDiagnosticKind;
  }
References clang::CXDiagnosticImpl::getKind(), and clang::CXDiagnosticImpl::LoadedDiagnosticKind.
decodeLocation()
void CXLoadedDiagnostic::decodeLocation (CXSourceLocation location, CXFile * file, unsigned * line, unsigned * column, unsigned * offset) [static]
Decode the CXSourceLocation into file, line, column, and offset.
Definition at line 148 of file CXLoadedDiagnostic.cpp.
                                                              {
  
  
  // CXSourceLocation consists of the following fields:
  //
  // void *ptr_data[2];
  // unsigned int_data;
  //
  // The lowest bit of ptr_data[0] is always set to 1 to indicate this
  // is a persistent diagnostic.
  //
  // For now, do the unoptimized approach and store the data in a side
  // data structure. We can optimize this case later.
  
  uintptr_t V = (uintptr_t) location.ptr_data[0];
  assert((V & 0x1) == 1);
  V &= ~(uintptr_t)1;
  
  const Location &Loc = *((Location*)V);
  
  if (file)
    *file = Loc.file;
  if (line)
    *line = Loc.line;
  if (column)
    *column = Loc.column;
  if (offset)
    *offset = Loc.offset;
}
References clang::CXLoadedDiagnostic::Location::column, clang::CXLoadedDiagnostic::Location::file, clang::CXLoadedDiagnostic::Location::line, and clang::CXLoadedDiagnostic::Location::offset.
getCategory()
unsigned CXLoadedDiagnostic::getCategory () const [override], [virtual]
Return the category of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 119 of file CXLoadedDiagnostic.cpp.
                                               {
  return category;
}
References category.
getCategoryText()
CXString CXLoadedDiagnostic::getCategoryText () const [override], [virtual]
Return the category string of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 123 of file CXLoadedDiagnostic.cpp.
                                                   {
  return cxstring::createDup(CategoryText);
}
References CategoryText, and clang::cxstring::createDup().
getChildDiagnostics()
CXDiagnosticSetImpl& clang::CXDiagnosticImpl::getChildDiagnostics () [inline], [inherited]
Definition at line 94 of file CIndexDiagnostic.h.
                                             {
    return ChildDiags;
  }
References clang::CXDiagnosticImpl::ChildDiags.
getDiagnosticOption()
CXString CXLoadedDiagnostic::getDiagnosticOption (CXString * Disable) const [override], [virtual]
Return the text for the diagnostic option.
Implements clang::CXDiagnosticImpl.
Definition at line 109 of file CXLoadedDiagnostic.cpp.
                                                                        {
  if (DiagOption.empty())
    return cxstring::createEmpty();
  // FIXME: possibly refactor with logic in CXStoredDiagnostic.
  if (Disable)
    *Disable = cxstring::createDup((Twine("-Wno-") + DiagOption).str());
  return cxstring::createDup((Twine("-W") + DiagOption).str());
}
References clang::cxstring::createDup(), clang::cxstring::createEmpty(), and DiagOption.
getFixIt()
CXString CXLoadedDiagnostic::getFixIt (unsigned FixIt, CXSourceRange * ReplacementRange) const [override], [virtual]
Return the FixIt information (source range and inserted text).
Implements clang::CXDiagnosticImpl.
Definition at line 140 of file CXLoadedDiagnostic.cpp.
                                                                             {
  assert(FixIt < FixIts.size());
  if (ReplacementRange)
    *ReplacementRange = FixIts[FixIt].first;
  return cxstring::createRef(FixIts[FixIt].second);
}
References clang::cxstring::createRef(), and FixIts.
getKind()
Kind clang::CXDiagnosticImpl::getKind () const [inline], [inherited]
Definition at line 92 of file CIndexDiagnostic.h.
{ return K; }
Referenced by clang::CXStoredDiagnostic::classof(), and classof().
getLocation()
CXSourceLocation CXLoadedDiagnostic::getLocation () const [override], [virtual]
Return the location of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 99 of file CXLoadedDiagnostic.cpp.
                                                       {
  // The lowest bit of ptr_data[0] is always set to 1 to indicate this
  // is a persistent diagnostic.
  return makeLocation(&DiagLoc);
}
getNumFixIts()
unsigned CXLoadedDiagnostic::getNumFixIts () const [override], [virtual]
Return the number of FixIts.
Implements clang::CXDiagnosticImpl.
Definition at line 136 of file CXLoadedDiagnostic.cpp.
                                                {
  return FixIts.size();
}
References FixIts.
getNumRanges()
unsigned CXLoadedDiagnostic::getNumRanges () const [override], [virtual]
Return the number of source ranges for the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 127 of file CXLoadedDiagnostic.cpp.
                                                {
  return Ranges.size();
}
References Ranges.
getRange()
CXSourceRange CXLoadedDiagnostic::getRange (unsigned Range) const [override], [virtual]
Return the source ranges for the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 131 of file CXLoadedDiagnostic.cpp.
                                                               {
  assert(Range < Ranges.size());
  return Ranges[Range];
}
References Ranges.
getSeverity()
CXDiagnosticSeverity CXLoadedDiagnostic::getSeverity () const [override], [virtual]
Return the severity of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 69 of file CXLoadedDiagnostic.cpp.
                                                           {
  // FIXME: Fail more softly if the diagnostic level is unknown?
  auto severityAsLevel = static_cast<serialized_diags::Level>(severity);
  assert(severity == static_cast<unsigned>(severityAsLevel) &&
         "unknown serialized diagnostic level");
  switch (severityAsLevel) {
#define CASE(X) case serialized_diags::X: return CXDiagnostic_##X;
  CASE(Ignored)
  CASE(Note)
  CASE(Warning)
  CASE(Error)
  CASE(Fatal)
#undef CASE
  // The 'Remark' level isn't represented in the stable API.
  case serialized_diags::Remark: return CXDiagnostic_Warning;
  }
  
  llvm_unreachable("Invalid diagnostic level");
}
References CASE, and severity.
getSpelling()
CXString CXLoadedDiagnostic::getSpelling () const [override], [virtual]
Return the spelling of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 105 of file CXLoadedDiagnostic.cpp.
                                               {
  return cxstring::createRef(Spelling);
}
References clang::cxstring::createRef(), and Spelling.
Member Data Documentation
category
unsigned clang::CXLoadedDiagnostic::category
Definition at line 89 of file CXLoadedDiagnostic.h.
Referenced by getCategory().
CategoryText
llvm::StringRef clang::CXLoadedDiagnostic::CategoryText
Definition at line 87 of file CXLoadedDiagnostic.h.
Referenced by getCategoryText().
ChildDiags
CXDiagnosticSetImpl clang::CXDiagnosticImpl::ChildDiags [protected], [inherited]
Definition at line 100 of file CIndexDiagnostic.h.
Referenced by clang::CXDiagnosticImpl::append(), and clang::CXDiagnosticImpl::getChildDiagnostics().
DiagLoc
Location clang::CXLoadedDiagnostic::DiagLoc
Definition at line 81 of file CXLoadedDiagnostic.h.
DiagOption
llvm::StringRef clang::CXLoadedDiagnostic::DiagOption
Definition at line 86 of file CXLoadedDiagnostic.h.
Referenced by getDiagnosticOption().
FixIts
std::vector<std::pair<CXSourceRange, const char *> > clang::CXLoadedDiagnostic::FixIts
Definition at line 84 of file CXLoadedDiagnostic.h.
Referenced by getFixIt(), and getNumFixIts().
Ranges
std::vector<CXSourceRange> clang::CXLoadedDiagnostic::Ranges
Definition at line 83 of file CXLoadedDiagnostic.h.
Referenced by getNumRanges(), and getRange().
severity
unsigned clang::CXLoadedDiagnostic::severity
Definition at line 88 of file CXLoadedDiagnostic.h.
Referenced by getSeverity().
Spelling
const char* clang::CXLoadedDiagnostic::Spelling
Definition at line 85 of file CXLoadedDiagnostic.h.
Referenced by getSpelling().
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CXLoadedDiagnostic.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CXLoadedDiagnostic.cpp