MyVisitor Class Reference
Public Member Functions
MyVisitor (ASTContext *Context)
virtual bool VisitStmt (Stmt *stmt)
Visit every statement linked to input file. If a stmt option is specified the tools searches for the first occurrence of an statement with the specified id. The statement is then casted to the matching statement class and body of the statement will be extracted and annotated.
virtual bool VisitFunctionDecl (FunctionDecl *func)
Visit every function linked to input file. The functions are traversed to find locations for initialization, runtime performance counter and for printing the summary. If stmt option is not specified, the main method will be traversed.
virtual ~MyVisitor ()
Detailed Description
Definition at line 220 of file RegionProfile.cpp.
Constructor & Destructor Documentation
MyVisitor()
MyVisitor::MyVisitor (ASTContext * Context) [inline], [explicit]
Definition at line 225 of file RegionProfile.cpp.
            : astContext(Context) // initialize private members
    {
        rewriter.setSourceMgr(astContext->getSourceManager(),
                               astContext->getLangOpts());
    }
References rewriter.
 MyVisitor()
virtual MyVisitor::~MyVisitor () [inline], [virtual]
Definition at line 357 of file RegionProfile.cpp.
{ }
Member Function Documentation
VisitFunctionDecl()
virtual bool MyVisitor::VisitFunctionDecl (FunctionDecl * func) [inline], [virtual]
Visit every function linked to input file. The functions are traversed to find locations for initialization, runtime performance counter and for printing the summary. If stmt option is not specified, the main method will be traversed.
!
Definition at line 295 of file RegionProfile.cpp.
                                                         {
        // find initialization location for includes and initialization of hagn lib
        if (initializationLocation.isInvalid() &&
             astContext->getSourceManager().isInMainFile(func->getLocation())) {
            SourceLocation lastLocation;
            for (auto it = astContext->getSourceManager().fileinfo_begin();
                  it != astContext->getSourceManager().fileinfo_end(); it++) {
                SourceLocation currentLocation = astContext->getSourceManager().getIncludeLoc(
                        astContext->getSourceManager().translateFile(it->first));
                if (currentLocation.isValid() && astContext->getSourceManager().isInFileID(currentLocation, astContext->getSourceManager().getMainFileID())) {
                    if (astContext->getSourceManager().getSpellingLineNumber(lastLocation) <= astContext->getSourceManager().getSpellingLineNumber(currentLocation)) {
                        lastLocation = currentLocation;
                    }
                }
            }
            initializationLocation = astContext->getSourceManager().translateFileLineCol(
                    astContext->getSourceManager().getFileEntryForID(astContext->getSourceManager().getMainFileID()),
                    astContext->getSourceManager().getSpellingLineNumber(lastLocation)+1, 1);
        }
        // find first location in main class for runtime measurement
        if (runtimeStartLocation.isInvalid() &&
             astContext->getSourceManager().isInMainFile(func->getLocation())) {
            if (func->isMain()) {
                SourceLocation locAfterBrace(clang::Lexer::findLocationAfterToken(
                        func->getBody()->getBeginLoc().getLocWithOffset(-1), clang::tok::l_brace,
                        astContext->getSourceManager(),
                        astContext->getLangOpts(), true));
                runtimeStartLocation = locAfterBrace;
            }
        }
        // find summary location in main class for ending runtime event and print event
        if (summaryLocation.isInvalid() &&
             astContext->getSourceManager().isInMainFile(func->getLocation())) {
            if (func->isMain()) {
                for (Stmt::child_iterator i = func->getBody()->child_begin(), e = func->getBody()->child_end();
                      i != e; ++i) {
                    Stmt *currStmt = *i;
                    if (currStmt->getStmtClass() == Stmt::ReturnStmtClass) {
                        summaryLocation = currStmt->getBeginLoc();
                    }
                }
            }
        }
        // annotate only main function if statement option is start
        if (astContext->getSourceManager().isInMainFile(func->getLocation())) {
            if (statementOption == "start") {
                if (func->isMain()) {
                    traverseChildren(func->getBody(), astContext);
                }
            }
        }
        return 1;
    }
References initializationLocation, runtimeStartLocation, statementOption, summaryLocation, and traverseChildren().
VisitStmt()
virtual bool MyVisitor::VisitStmt (Stmt * stmt) [inline], [virtual]
Visit every statement linked to input file. If a stmt option is specified the tools searches for the first occurrence of an statement with the specified id. The statement is then casted to the matching statement class and body of the statement will be extracted and annotated.
!
Definition at line 240 of file RegionProfile.cpp.
                                         {
        // only statements in main file
        if (astContext->getSourceManager().isInMainFile(stmt->getBeginLoc())) {
            // when stmt identifier is specified
            if (statementOption != "start") {
                // get statement identifier and cast to string
                int64_t currentId = stmt->getID(*astContext);
                std::string currentIdString = std::to_string(currentId);
                // find statement with matching id
                if (currentIdString == statementOption) {
                    rewriter.InsertText(stmt->getBeginLoc(), "dataStorage.startEvent(1);\n");
                    rewriter.InsertText(getLocationAfterToken(stmt->getEndLoc(), astContext),
                                         "dataStorage.endEvent(1);\n");
                    if (stmt->getStmtClass() == Stmt::CallExprClass) {
                        CallExpr *expr = cast<CallExpr>(stmt);
                        Stmt *nextBody = expr->getDirectCallee()->getBody();
                        traverseChildren(nextBody, astContext);
                    }
                    if (stmt->getStmtClass() == Stmt::ForStmtClass) {
                        ForStmt *forStmt = cast<ForStmt>(stmt);
                        Stmt *nextBody = forStmt->getBody();
                        traverseChildren(nextBody, astContext);
                    }
                    if (stmt->getStmtClass() == Stmt::WhileStmtClass) {
                        WhileStmt *whileStmt = cast<WhileStmt>(stmt);
                        Stmt *nextBody = whileStmt->getBody();
                        traverseChildren(nextBody, astContext);
                    }
                    if (stmt->getStmtClass() == Stmt::IfStmtClass) {
                        IfStmt *ifStmt = cast<IfStmt>(stmt);
                        Stmt *nextBody = ifStmt->getThen();
                        traverseChildren(nextBody, astContext);
                    }
                    if (stmt->getStmtClass() == Stmt::CXXMemberCallExprClass) {
                        CXXMemberCallExpr *cxxMemberCallExpr = cast<CXXMemberCallExpr>(stmt);
                        Stmt *nextBody = cxxMemberCallExpr->getDirectCallee()->getBody();
                        traverseChildren(nextBody, astContext);
                    }
                }
            }
        }
        return 1;
    }
References getLocationAfterToken(), rewriter, statementOption, and traverseChildren().
The documentation for this class was generated from the following file:
RegionProfile.cpp