tests.functional.cases.test_from_cdb.FailureReportTest Class Reference
Public Member Functions
def test_broken_creates_failure_reports (self)
def test_broken_does_not_creates_failure_reports (self)
Detailed Description
Definition at line 164 of file test_from_cdb.py.
Member Function Documentation
test_broken_creates_failure_reports()
def tests.functional.cases.test_from_cdb.FailureReportTest.test_broken_creates_failure_reports (self)
Definition at line 165 of file test_from_cdb.py.
    def test_broken_creates_failure_reports(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('broken', tmpdir)
            exit_code, reportdir = run_analyzer(tmpdir, cdb, [])
            self.assertTrue(
                os.path.isdir(os.path.join(reportdir, 'failures')))
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
test_broken_does_not_creates_failure_reports()
def tests.functional.cases.test_from_cdb.FailureReportTest.test_broken_does_not_creates_failure_reports (self)
Definition at line 172 of file test_from_cdb.py.
    def test_broken_does_not_creates_failure_reports(self):
        with libear.TemporaryDirectory() as tmpdir:
            cdb = prepare_cdb('broken', tmpdir)
            exit_code, reportdir = run_analyzer(
                tmpdir, cdb, ['--no-failure-reports'])
            self.assertFalse(
                os.path.isdir(os.path.join(reportdir, 'failures')))
References tests.functional.cases.test_from_cdb.prepare_cdb(), tests.functional.cases.test_from_cdb.run_analyzer(), and libear.TemporaryDirectory().
The documentation for this class was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/cases/test_from_cdb.py