clang::cxindex::CXIndexDataConsumer Class Reference
#include <CXIndexDataConsumer.h>
Public Member Functions
CXIndexDataConsumer (CXClientData clientData, IndexerCallbacks &indexCallbacks, unsigned indexOptions, CXTranslationUnit cxTU)
ASTContext & getASTContext () const
CXTranslationUnit getCXTU () const
void setASTContext (ASTContext &ctx)
void setPreprocessor (std::shared_ptr< Preprocessor > PP) override
bool shouldSuppressRefs () const
bool shouldIndexFunctionLocalSymbols () const
bool shouldIndexImplicitTemplateInsts () const
bool shouldAbort ()
bool hasDiagnosticCallback () const
void enteredMainFile (const FileEntry *File)
void ppIncludedFile (SourceLocation hashLoc, StringRef filename, const FileEntry *File, bool isImport, bool isAngled, bool isModuleImport)
void importedModule (const ImportDecl *ImportD)
void importedPCH (const FileEntry *File)
void startedTranslationUnit ()
void indexDiagnostics ()
void handleDiagnosticSet (CXDiagnosticSet CXDiagSet)
bool handleFunction (const FunctionDecl *FD)
bool handleVar (const VarDecl *D)
bool handleField (const FieldDecl *D)
bool handleEnumerator (const EnumConstantDecl *D)
bool handleTagDecl (const TagDecl *D)
bool handleTypedefName (const TypedefNameDecl *D)
bool handleObjCInterface (const ObjCInterfaceDecl *D)
bool handleObjCImplementation (const ObjCImplementationDecl *D)
bool handleObjCProtocol (const ObjCProtocolDecl *D)
bool handleObjCCategory (const ObjCCategoryDecl *D)
bool handleObjCCategoryImpl (const ObjCCategoryImplDecl *D)
bool handleObjCMethod (const ObjCMethodDecl *D, SourceLocation Loc)
bool handleSynthesizedObjCProperty (const ObjCPropertyImplDecl *D)
bool handleSynthesizedObjCMethod (const ObjCMethodDecl *D, SourceLocation Loc, const DeclContext *LexicalDC)
bool handleObjCProperty (const ObjCPropertyDecl *D)
bool handleNamespace (const NamespaceDecl *D)
bool handleClassTemplate (const ClassTemplateDecl *D)
bool handleFunctionTemplate (const FunctionTemplateDecl *D)
bool handleTypeAliasTemplate (const TypeAliasTemplateDecl *D)
bool handleReference (const NamedDecl *D, SourceLocation Loc, CXCursor Cursor, const NamedDecl *Parent, const DeclContext *DC, const Expr *E=nullptr, CXIdxEntityRefKind Kind=CXIdxEntityRef_Direct, CXSymbolRole Role=CXSymbolRole_None)
bool isNotFromSourceFile (SourceLocation Loc) const
void translateLoc (SourceLocation Loc, CXIdxClientFile *indexFile, CXFile *file, unsigned *line, unsigned *column, unsigned *offset)
CXIdxClientContainer getClientContainerForDC (const DeclContext *DC) const
void addContainerInMap (const DeclContext *DC, CXIdxClientContainer container)
CXIdxClientEntity getClientEntity (const Decl *D) const
void setClientEntity (const Decl *D, CXIdxClientEntity client)
Static Public Member Functions
static bool isFunctionLocalDecl (const Decl *D)
static bool isTemplateImplicitInstantiation (const Decl *D)
Friends
class ScratchAlloc
class AttrListInfo
Detailed Description
Definition at line 275 of file CXIndexDataConsumer.h.
Constructor & Destructor Documentation
CXIndexDataConsumer()
clang::cxindex::CXIndexDataConsumer::CXIndexDataConsumer (CXClientData clientData, IndexerCallbacks & indexCallbacks, unsigned indexOptions, CXTranslationUnit cxTU) [inline]
Definition at line 334 of file CXIndexDataConsumer.h.
    : Ctx(nullptr), ClientData(clientData), CB(indexCallbacks),
      IndexOptions(indexOptions), CXTU(cxTU),
      StrScratch(), StrAdapterCount(0) { }
Member Function Documentation
addContainerInMap()
void CXIndexDataConsumer::addContainerInMap (const DeclContext * DC, CXIdxClientContainer container)
Definition at line 941 of file CXIndexDataConsumer.cpp.
                                                                        {
  if (!DC)
    return;
  ContainerMapTy::iterator I = ContainerMap.find(DC);
  if (I == ContainerMap.end()) {
    if (container)
      ContainerMap[DC] = container;
    return;
  }
  // Allow changing the container of a previously seen DeclContext so we
  // can handle invalid user code, like a function re-definition.
  if (container)
    I->second = container;
  else
    ContainerMap.erase(I);
}
Referenced by clang_index_setClientContainer(), and startedTranslationUnit().
enteredMainFile()
void CXIndexDataConsumer::enteredMainFile (const FileEntry * File)
Definition at line 450 of file CXIndexDataConsumer.cpp.
                                                               {
  if (File && CB.enteredMainFile) {
    CXIdxClientFile idxFile =
      CB.enteredMainFile(ClientData,
                         static_cast<CXFile>(const_cast<FileEntry *>(File)),
                         nullptr);
    FileMap[File] = idxFile;
  }
}
getASTContext()
ASTContext& clang::cxindex::CXIndexDataConsumer::getASTContext () const [inline]
Definition at line 340 of file CXIndexDataConsumer.h.
{ return *Ctx; }
Referenced by clang_indexLoc_getCXSourceLocation().
getClientContainerForDC()
CXIdxClientContainer CXIndexDataConsumer::getClientContainerForDC (const DeclContext * DC) const
Definition at line 1069 of file CXIndexDataConsumer.cpp.
                                                                        {
  if (!DC)
    return nullptr;
  ContainerMapTy::const_iterator I = ContainerMap.find(DC);
  if (I == ContainerMap.end())
    return nullptr;
  return I->second;
}
Referenced by clang_index_getClientContainer().
getClientEntity()
CXIdxClientEntity CXIndexDataConsumer::getClientEntity (const Decl * D) const
Definition at line 960 of file CXIndexDataConsumer.cpp.
                                                                          {
  if (!D)
    return nullptr;
  EntityMapTy::const_iterator I = EntityMap.find(D);
  if (I == EntityMap.end())
    return nullptr;
  return I->second;
}
Referenced by clang_index_getClientEntity().
getCXTU()
CXTranslationUnit clang::cxindex::CXIndexDataConsumer::getCXTU () const [inline]
Definition at line 341 of file CXIndexDataConsumer.h.
{ return CXTU; }
Referenced by indexDiagnostics().
handleClassTemplate()
bool CXIndexDataConsumer::handleClassTemplate (const ClassTemplateDecl * D)
Definition at line 867 of file CXIndexDataConsumer.cpp.
                                                                        {
  return handleCXXRecordDecl(D->getTemplatedDecl(), D);
}
handleDiagnosticSet()
void CXIndexDataConsumer::handleDiagnosticSet (CXDiagnosticSet CXDiagSet)
Definition at line 534 of file CXIndexDataConsumer.cpp.
                                                                    {
  if (!CB.diagnostic)
    return;
  CB.diagnostic(ClientData, CXDiagSet, nullptr);
}
Referenced by indexDiagnostics().
handleEnumerator()
bool CXIndexDataConsumer::handleEnumerator (const EnumConstantDecl * D)
Definition at line 635 of file CXIndexDataConsumer.cpp.
                                                                    {
  DeclInfo DInfo(/*isRedeclaration=*/false, /*isDefinition=*/true,
                 /*isContainer=*/false);
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleField()
bool CXIndexDataConsumer::handleField (const FieldDecl * D)
Definition at line 629 of file CXIndexDataConsumer.cpp.
                                                        {
  DeclInfo DInfo(/*isRedeclaration=*/false, /*isDefinition=*/true,
                 /*isContainer=*/false);
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleFunction()
bool CXIndexDataConsumer::handleFunction (const FunctionDecl * FD)
Definition at line 607 of file CXIndexDataConsumer.cpp.
                                                              {
  bool isDef = D->isThisDeclarationADefinition();
  bool isContainer = isDef;
  bool isSkipped = false;
  if (D->hasSkippedBody()) {
    isSkipped = true;
    isDef = true;
    isContainer = false;
  }
  DeclInfo DInfo(!D->isFirstDecl(), isDef, isContainer);
  if (isSkipped)
    DInfo.flags |= CXIdxDeclFlag_Skipped;
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleFunctionTemplate()
bool CXIndexDataConsumer::handleFunctionTemplate (const FunctionTemplateDecl * D)
Definition at line 871 of file CXIndexDataConsumer.cpp.
                                                                              {
  DeclInfo DInfo(/*isRedeclaration=*/!D->isCanonicalDecl(),
                 /*isDefinition=*/D->isThisDeclarationADefinition(),
                 /*isContainer=*/D->isThisDeclarationADefinition());
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleNamespace()
bool CXIndexDataConsumer::handleNamespace (const NamespaceDecl * D)
Definition at line 860 of file CXIndexDataConsumer.cpp.
                                                                {
  DeclInfo DInfo(/*isRedeclaration=*/!D->isOriginalNamespace(),
                 /*isDefinition=*/true,
                 /*isContainer=*/true);
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleObjCCategory()
bool CXIndexDataConsumer::handleObjCCategory (const ObjCCategoryDecl * D)
Definition at line 741 of file CXIndexDataConsumer.cpp.
                                                                      {
  ScratchAlloc SA(*this);
  ObjCCategoryDeclInfo CatDInfo(/*isImplementation=*/false);
  EntityInfo ClassEntity;
  const ObjCInterfaceDecl *IFaceD = D->getClassInterface();
  SourceLocation ClassLoc = D->getLocation();
  SourceLocation CategoryLoc = D->IsClassExtension() ? ClassLoc
                                                     : D->getCategoryNameLoc();
  getEntityInfo(IFaceD, ClassEntity, SA);
  if (shouldSuppressRefs())
    markEntityOccurrenceInFile(IFaceD, ClassLoc);
  ObjCProtocolListInfo ProtInfo(D->getReferencedProtocols(), *this, SA);
  
  CatDInfo.ObjCCatDeclInfo.containerInfo = &CatDInfo.ObjCContDeclInfo;
  if (IFaceD) {
    CatDInfo.ObjCCatDeclInfo.objcClass = &ClassEntity;
    CatDInfo.ObjCCatDeclInfo.classCursor =
        MakeCursorObjCClassRef(IFaceD, ClassLoc, CXTU);
  } else {
    CatDInfo.ObjCCatDeclInfo.objcClass = nullptr;
    CatDInfo.ObjCCatDeclInfo.classCursor = clang_getNullCursor();
  }
  CatDInfo.ObjCCatDeclInfo.classLoc = getIndexLoc(ClassLoc);
  CatDInfo.ObjCProtoListInfo = ProtInfo.getListInfo();
  CatDInfo.ObjCCatDeclInfo.protocols = &CatDInfo.ObjCProtoListInfo;
  return handleObjCContainer(D, CategoryLoc, getCursor(D), CatDInfo);
}
References clang_getNullCursor(), clang::cxcursor::MakeCursorObjCClassRef(), clang::cxindex::ObjCCategoryDeclInfo::ObjCCatDeclInfo, clang::cxindex::ObjCContainerDeclInfo::ObjCContDeclInfo, clang::cxindex::ObjCCategoryDeclInfo::ObjCProtoListInfo, and shouldSuppressRefs().
handleObjCCategoryImpl()
bool CXIndexDataConsumer::handleObjCCategoryImpl (const ObjCCategoryImplDecl * D)
Definition at line 773 of file CXIndexDataConsumer.cpp.
                                                                              {
  ScratchAlloc SA(*this);
  const ObjCCategoryDecl *CatD = D->getCategoryDecl();
  ObjCCategoryDeclInfo CatDInfo(/*isImplementation=*/true);
  EntityInfo ClassEntity;
  const ObjCInterfaceDecl *IFaceD = CatD->getClassInterface();
  SourceLocation ClassLoc = D->getLocation();
  SourceLocation CategoryLoc = D->getCategoryNameLoc();
  getEntityInfo(IFaceD, ClassEntity, SA);
  if (shouldSuppressRefs())
    markEntityOccurrenceInFile(IFaceD, ClassLoc);
  CatDInfo.ObjCCatDeclInfo.containerInfo = &CatDInfo.ObjCContDeclInfo;
  if (IFaceD) {
    CatDInfo.ObjCCatDeclInfo.objcClass = &ClassEntity;
    CatDInfo.ObjCCatDeclInfo.classCursor =
        MakeCursorObjCClassRef(IFaceD, ClassLoc, CXTU);
  } else {
    CatDInfo.ObjCCatDeclInfo.objcClass = nullptr;
    CatDInfo.ObjCCatDeclInfo.classCursor = clang_getNullCursor();
  }
  CatDInfo.ObjCCatDeclInfo.classLoc = getIndexLoc(ClassLoc);
  CatDInfo.ObjCCatDeclInfo.protocols = nullptr;
  return handleObjCContainer(D, CategoryLoc, getCursor(D), CatDInfo);
}
References clang_getNullCursor(), clang::cxcursor::MakeCursorObjCClassRef(), clang::cxindex::ObjCCategoryDeclInfo::ObjCCatDeclInfo, clang::cxindex::ObjCContainerDeclInfo::ObjCContDeclInfo, and shouldSuppressRefs().
handleObjCImplementation()
bool CXIndexDataConsumer::handleObjCImplementation (const ObjCImplementationDecl * D)
Definition at line 704 of file CXIndexDataConsumer.cpp.
                                                                               {
  ObjCContainerDeclInfo ContDInfo(/*isForwardRef=*/false,
                      /*isRedeclaration=*/true,
                      /*isImplementation=*/true);
  return handleObjCContainer(D, D->getLocation(), getCursor(D), ContDInfo);
}
handleObjCInterface()
bool CXIndexDataConsumer::handleObjCInterface (const ObjCInterfaceDecl * D)
Definition at line 656 of file CXIndexDataConsumer.cpp.
                                                                        {
  // For @class forward declarations, suppress them the same way as references.
  if (!D->isThisDeclarationADefinition()) {
    if (shouldSuppressRefs() && markEntityOccurrenceInFile(D, D->getLocation()))
      return false; // already occurred.
    // FIXME: This seems like the wrong definition for redeclaration.
    bool isRedeclaration = D->hasDefinition() || D->getPreviousDecl();
    ObjCContainerDeclInfo ContDInfo(/*isForwardRef=*/true, isRedeclaration,
                                    /*isImplementation=*/false);
    return handleObjCContainer(D, D->getLocation(),
                               MakeCursorObjCClassRef(D, D->getLocation(),
                                                      CXTU),
                               ContDInfo);
  }
  ScratchAlloc SA(*this);
  CXIdxBaseClassInfo BaseClass;
  EntityInfo BaseEntity;
  BaseClass.cursor = clang_getNullCursor();
  if (ObjCInterfaceDecl *SuperD = D->getSuperClass()) {
    getEntityInfo(SuperD, BaseEntity, SA);
    SourceLocation SuperLoc = D->getSuperClassLoc();
    BaseClass.base = &BaseEntity;
    BaseClass.cursor = MakeCursorObjCSuperClassRef(SuperD, SuperLoc, CXTU);
    BaseClass.loc = getIndexLoc(SuperLoc);
    if (shouldSuppressRefs())
      markEntityOccurrenceInFile(SuperD, SuperLoc);
  }
  
  ObjCProtocolList EmptyProtoList;
  ObjCProtocolListInfo ProtInfo(D->isThisDeclarationADefinition()
                                  ? D->getReferencedProtocols()
                                  : EmptyProtoList,
                                *this, SA);
  
  ObjCInterfaceDeclInfo InterInfo(D);
  InterInfo.ObjCProtoListInfo = ProtInfo.getListInfo();
  InterInfo.ObjCInterDeclInfo.containerInfo = &InterInfo.ObjCContDeclInfo;
  InterInfo.ObjCInterDeclInfo.superInfo = D->getSuperClass() ? &BaseClass
                                                             : nullptr;
  InterInfo.ObjCInterDeclInfo.protocols = &InterInfo.ObjCProtoListInfo;
  return handleObjCContainer(D, D->getLocation(), getCursor(D), InterInfo);
}
References clang_getNullCursor(), clang::cxcursor::MakeCursorObjCClassRef(), clang::cxcursor::MakeCursorObjCSuperClassRef(), clang::cxindex::ObjCContainerDeclInfo::ObjCContDeclInfo, clang::cxindex::ObjCInterfaceDeclInfo::ObjCInterDeclInfo, clang::cxindex::ObjCInterfaceDeclInfo::ObjCProtoListInfo, and shouldSuppressRefs().
handleObjCMethod()
bool CXIndexDataConsumer::handleObjCMethod (const ObjCMethodDecl * D, SourceLocation Loc)
Definition at line 802 of file CXIndexDataConsumer.cpp.
                                                               {
  bool isDef = D->isThisDeclarationADefinition();
  bool isContainer = isDef;
  bool isSkipped = false;
  if (D->hasSkippedBody()) {
    isSkipped = true;
    isDef = true;
    isContainer = false;
  }
  DeclInfo DInfo(!D->isCanonicalDecl(), isDef, isContainer);
  if (isSkipped)
    DInfo.flags |= CXIdxDeclFlag_Skipped;
  return handleDecl(D, Loc, getCursor(D), DInfo);
}
handleObjCProperty()
bool CXIndexDataConsumer::handleObjCProperty (const ObjCPropertyDecl * D)
Definition at line 835 of file CXIndexDataConsumer.cpp.
                                                                      {
  ScratchAlloc SA(*this);
  ObjCPropertyDeclInfo DInfo;
  EntityInfo GetterEntity;
  EntityInfo SetterEntity;
  DInfo.ObjCPropDeclInfo.declInfo = &DInfo;
  if (ObjCMethodDecl *Getter = D->getGetterMethodDecl()) {
    getEntityInfo(Getter, GetterEntity, SA);
    DInfo.ObjCPropDeclInfo.getter = &GetterEntity;
  } else {
    DInfo.ObjCPropDeclInfo.getter = nullptr;
  }
  if (ObjCMethodDecl *Setter = D->getSetterMethodDecl()) {
    getEntityInfo(Setter, SetterEntity, SA);
    DInfo.ObjCPropDeclInfo.setter = &SetterEntity;
  } else {
    DInfo.ObjCPropDeclInfo.setter = nullptr;
  }
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
References clang::cxindex::ObjCPropertyDeclInfo::ObjCPropDeclInfo.
handleObjCProtocol()
bool CXIndexDataConsumer::handleObjCProtocol (const ObjCProtocolDecl * D)
Definition at line 712 of file CXIndexDataConsumer.cpp.
                                                                      {
  if (!D->isThisDeclarationADefinition()) {
    if (shouldSuppressRefs() && markEntityOccurrenceInFile(D, D->getLocation()))
      return false; // already occurred.
    
    // FIXME: This seems like the wrong definition for redeclaration.
    bool isRedeclaration = D->hasDefinition() || D->getPreviousDecl();
    ObjCContainerDeclInfo ContDInfo(/*isForwardRef=*/true,
                                    isRedeclaration,
                                    /*isImplementation=*/false);
    return handleObjCContainer(D, D->getLocation(),
                               MakeCursorObjCProtocolRef(D, D->getLocation(),
                                                         CXTU),
                               ContDInfo);
  }
  
  ScratchAlloc SA(*this);
  ObjCProtocolList EmptyProtoList;
  ObjCProtocolListInfo ProtListInfo(D->isThisDeclarationADefinition()
                                      ? D->getReferencedProtocols()
                                      : EmptyProtoList,
                                    *this, SA);
  
  ObjCProtocolDeclInfo ProtInfo(D);
  ProtInfo.ObjCProtoRefListInfo = ProtListInfo.getListInfo();
  return handleObjCContainer(D, D->getLocation(), getCursor(D), ProtInfo);
}
References clang::cxcursor::MakeCursorObjCProtocolRef(), clang::cxindex::ObjCProtocolDeclInfo::ObjCProtoRefListInfo, and shouldSuppressRefs().
handleReference()
bool CXIndexDataConsumer::handleReference (const NamedDecl * D, SourceLocation Loc, CXCursor Cursor, const NamedDecl * Parent, const DeclContext * DC, const Expr * E = nullptr, CXIdxEntityRefKind Kind = CXIdxEntityRef_Direct, CXSymbolRole Role = CXSymbolRole_None)
Definition at line 884 of file CXIndexDataConsumer.cpp.
                                                         {
  if (!CB.indexEntityReference)
    return false;
  if (!D || !DC)
    return false;
  if (Loc.isInvalid())
    return false;
  if (!shouldIndexFunctionLocalSymbols() && isFunctionLocalDecl(D))
    return false;
  if (isNotFromSourceFile(D->getLocation()))
    return false;
  if (D->isImplicit() && shouldIgnoreIfImplicit(D))
    return false;
  if (shouldSuppressRefs()) {
    if (markEntityOccurrenceInFile(D, Loc))
      return false; // already occurred.
  }
  ScratchAlloc SA(*this);
  EntityInfo RefEntity, ParentEntity;
  getEntityInfo(D, RefEntity, SA);
  if (!RefEntity.USR)
    return false;
  getEntityInfo(Parent, ParentEntity, SA);
  ContainerInfo Container;
  getContainerInfo(DC, Container);
  CXIdxEntityRefInfo Info = { Kind,
                              Cursor,
                              getIndexLoc(Loc),
                              &RefEntity,
                              Parent ? &ParentEntity : nullptr,
                              &Container,
                              Role };
  CB.indexEntityReference(ClientData, &Info);
  return true;
}
Referenced by handleSynthesizedObjCProperty().
handleSynthesizedObjCMethod()
bool CXIndexDataConsumer::handleSynthesizedObjCMethod (const ObjCMethodDecl * D, SourceLocation Loc, const DeclContext * LexicalDC)
Definition at line 827 of file CXIndexDataConsumer.cpp.
                                                                               {
  DeclInfo DInfo(/*isRedeclaration=*/true, /*isDefinition=*/true,
                 /*isContainer=*/false);
  return handleDecl(D, Loc, getCursor(D), DInfo, LexicalDC, D->getDeclContext());
}
handleSynthesizedObjCProperty()
bool CXIndexDataConsumer::handleSynthesizedObjCProperty (const ObjCPropertyImplDecl * D)
Definition at line 819 of file CXIndexDataConsumer.cpp.
                                                                               {
  ObjCPropertyDecl *PD = D->getPropertyDecl();
  auto *DC = D->getDeclContext();
  return handleReference(PD, D->getLocation(), getCursor(D),
                         dyn_cast<NamedDecl>(DC), DC);
}
References handleReference().
handleTagDecl()
bool CXIndexDataConsumer::handleTagDecl (const TagDecl * D)
Definition at line 641 of file CXIndexDataConsumer.cpp.
                                                        {
  if (const CXXRecordDecl *CXXRD = dyn_cast<CXXRecordDecl>(D))
    return handleCXXRecordDecl(CXXRD, D);
  DeclInfo DInfo(!D->isFirstDecl(), D->isThisDeclarationADefinition(),
                 D->isThisDeclarationADefinition());
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleTypeAliasTemplate()
bool CXIndexDataConsumer::handleTypeAliasTemplate (const TypeAliasTemplateDecl * D)
Definition at line 878 of file CXIndexDataConsumer.cpp.
                                                                                {
  DeclInfo DInfo(/*isRedeclaration=*/!D->isCanonicalDecl(),
                 /*isDefinition=*/true, /*isContainer=*/false);
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleTypedefName()
bool CXIndexDataConsumer::handleTypedefName (const TypedefNameDecl * D)
Definition at line 650 of file CXIndexDataConsumer.cpp.
                                                                    {
  DeclInfo DInfo(!D->isFirstDecl(), /*isDefinition=*/true,
                 /*isContainer=*/false);
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
handleVar()
bool CXIndexDataConsumer::handleVar (const VarDecl * D)
Definition at line 623 of file CXIndexDataConsumer.cpp.
                                                    {
  DeclInfo DInfo(!D->isFirstDecl(), D->isThisDeclarationADefinition(),
                 /*isContainer=*/false);
  return handleDecl(D, D->getLocation(), getCursor(D), DInfo);
}
hasDiagnosticCallback()
bool clang::cxindex::CXIndexDataConsumer::hasDiagnosticCallback () const [inline]
Definition at line 362 of file CXIndexDataConsumer.h.
{ return CB.diagnostic; }
Referenced by indexDiagnostics().
importedModule()
void CXIndexDataConsumer::importedModule (const ImportDecl * ImportD)
Definition at line 478 of file CXIndexDataConsumer.cpp.
                                                                  {
  if (!CB.importedASTFile)
    return;
  Module *Mod = ImportD->getImportedModule();
  if (!Mod)
    return;
  // If the imported module is part of the top-level module that we're
  // indexing, it doesn't correspond to an imported AST file.
  // FIXME: This assumes that AST files and top-level modules directly
  // correspond, which is unlikely to remain true forever.
  if (Module *SrcMod = ImportD->getImportedOwningModule())
    if (SrcMod->getTopLevelModule() == Mod->getTopLevelModule())
      return;
  FileEntry *FE = nullptr;
  if (auto File = Mod->getASTFile())
    FE = const_cast<FileEntry *>(&File->getFileEntry());
  CXIdxImportedASTFileInfo Info = {static_cast<CXFile>(FE), Mod,
                                   getIndexLoc(ImportD->getLocation()),
                                   ImportD->isImplicit()};
  CXIdxClientASTFile astFile = CB.importedASTFile(ClientData, &Info);
  (void)astFile;
}
importedPCH()
void CXIndexDataConsumer::importedPCH (const FileEntry * File)
Definition at line 504 of file CXIndexDataConsumer.cpp.
                                                           {
  if (!CB.importedASTFile)
    return;
  CXIdxImportedASTFileInfo Info = {
                                    static_cast<CXFile>(
                                      const_cast<FileEntry *>(File)),
                                    /*module=*/nullptr,
                                    getIndexLoc(SourceLocation()),
                                    /*isImplicit=*/false
                                  };
  CXIdxClientASTFile astFile = CB.importedASTFile(ClientData, &Info);
  (void)astFile;
}
indexDiagnostics()
void CXIndexDataConsumer::indexDiagnostics ()
Definition at line 526 of file CXIndexDataConsumer.cpp.
                                           {
  if (!hasDiagnosticCallback())
    return;
  CXDiagnosticSetImpl *DiagSet = cxdiag::lazyCreateDiags(getCXTU());
  handleDiagnosticSet(DiagSet);
}
References getCXTU(), handleDiagnosticSet(), hasDiagnosticCallback(), and clang::cxdiag::lazyCreateDiags().
isFunctionLocalDecl()
bool CXIndexDataConsumer::isFunctionLocalDecl (const Decl * D) [static]
Definition at line 420 of file CXIndexDataConsumer.cpp.
                                                           {
  assert(D);
  if (!D->getParentFunctionOrMethod())
    return false;
  if (const NamedDecl *ND = dyn_cast<NamedDecl>(D)) {
    switch (ND->getFormalLinkage()) {
    case NoLinkage:
    case InternalLinkage:
      return true;
    case VisibleNoLinkage:
    case ModuleInternalLinkage:
    case UniqueExternalLinkage:
      llvm_unreachable("Not a sema linkage");
    case ModuleLinkage:
    case ExternalLinkage:
      return false;
    }
  }
  return true;
}
isNotFromSourceFile()
bool CXIndexDataConsumer::isNotFromSourceFile (SourceLocation Loc) const
Definition at line 932 of file CXIndexDataConsumer.cpp.
                                                                      {
  if (Loc.isInvalid())
    return true;
  SourceManager &SM = Ctx->getSourceManager();
  SourceLocation FileLoc = SM.getFileLoc(Loc);
  FileID FID = SM.getFileID(FileLoc);
  return SM.getFileEntryForID(FID) == nullptr;
}
isTemplateImplicitInstantiation()
bool CXIndexDataConsumer::isTemplateImplicitInstantiation (const Decl * D) [static]
Definition at line 1229 of file CXIndexDataConsumer.cpp.
                                                                       {
  if (const ClassTemplateSpecializationDecl *
        SD = dyn_cast<ClassTemplateSpecializationDecl>(D)) {
    return SD->getSpecializationKind() == TSK_ImplicitInstantiation;
  }
  if (const FunctionDecl *FD = dyn_cast<FunctionDecl>(D)) {
    return FD->getTemplateSpecializationKind() == TSK_ImplicitInstantiation;
  }
  return false;
}
ppIncludedFile()
void CXIndexDataConsumer::ppIncludedFile (SourceLocation hashLoc, StringRef filename, const FileEntry * File, bool isImport, bool isAngled, bool isModuleImport)
Definition at line 460 of file CXIndexDataConsumer.cpp.
                                                          {
  if (!CB.ppIncludedFile)
    return;
  ScratchAlloc SA(*this);
  CXIdxIncludedFileInfo Info = { getIndexLoc(hashLoc),
                                 SA.toCStr(filename),
                                 static_cast<CXFile>(
                                   const_cast<FileEntry *>(File)),
                                 isImport, isAngled, isModuleImport };
  CXIdxClientFile idxFile = CB.ppIncludedFile(ClientData, &Info);
  FileMap[File] = idxFile;
}
References clang::cxindex::ScratchAlloc::toCStr().
setASTContext()
void CXIndexDataConsumer::setASTContext (ASTContext & ctx)
Definition at line 411 of file CXIndexDataConsumer.cpp.
                                                       {
  Ctx = &ctx;
  cxtu::getASTUnit(CXTU)->setASTContext(&ctx);
}
setClientEntity()
void CXIndexDataConsumer::setClientEntity (const Decl * D, CXIdxClientEntity client)
Definition at line 969 of file CXIndexDataConsumer.cpp.
                                                                                 {
  if (!D)
    return;
  EntityMap[D] = client;
}
Referenced by clang_index_setClientEntity().
setPreprocessor()
void CXIndexDataConsumer::setPreprocessor (std::shared_ptr< Preprocessor > PP) [override]
Definition at line 416 of file CXIndexDataConsumer.cpp.
                                                                        {
  cxtu::getASTUnit(CXTU)->setPreprocessor(std::move(PP));
}
shouldAbort()
bool CXIndexDataConsumer::shouldAbort ()
Definition at line 444 of file CXIndexDataConsumer.cpp.
                                      {
  if (!CB.abortQuery)
    return false;
  return CB.abortQuery(ClientData, nullptr);
}
shouldIndexFunctionLocalSymbols()
bool clang::cxindex::CXIndexDataConsumer::shouldIndexFunctionLocalSymbols () const [inline]
Definition at line 350 of file CXIndexDataConsumer.h.
                                               {
    return IndexOptions & CXIndexOpt_IndexFunctionLocalSymbols;
  }
shouldIndexImplicitTemplateInsts()
bool clang::cxindex::CXIndexDataConsumer::shouldIndexImplicitTemplateInsts () const [inline]
Definition at line 354 of file CXIndexDataConsumer.h.
                                                {
    return IndexOptions & CXIndexOpt_IndexImplicitTemplateInstantiations;
  }
shouldSuppressRefs()
bool clang::cxindex::CXIndexDataConsumer::shouldSuppressRefs () const [inline]
Definition at line 346 of file CXIndexDataConsumer.h.
                                  {
    return IndexOptions & CXIndexOpt_SuppressRedundantRefs;
  }
Referenced by handleObjCCategory(), handleObjCCategoryImpl(), handleObjCInterface(), and handleObjCProtocol().
startedTranslationUnit()
void CXIndexDataConsumer::startedTranslationUnit ()
Definition at line 519 of file CXIndexDataConsumer.cpp.
                                                 {
  CXIdxClientContainer idxCont = nullptr;
  if (CB.startedTranslationUnit)
    idxCont = CB.startedTranslationUnit(ClientData, nullptr);
  addContainerInMap(Ctx->getTranslationUnitDecl(), idxCont);
}
References addContainerInMap().
translateLoc()
void CXIndexDataConsumer::translateLoc (SourceLocation Loc, CXIdxClientFile * indexFile, CXFile * file, unsigned * line, unsigned * column, unsigned * offset)
Definition at line 1101 of file CXIndexDataConsumer.cpp.
                                                     {
  if (Loc.isInvalid())
    return;
  SourceManager &SM = Ctx->getSourceManager();
  Loc = SM.getFileLoc(Loc);
  std::pair<FileID, unsigned> LocInfo = SM.getDecomposedLoc(Loc);
  FileID FID = LocInfo.first;
  unsigned FileOffset = LocInfo.second;
  if (FID.isInvalid())
    return;
  
  const FileEntry *FE = SM.getFileEntryForID(FID);
  if (indexFile)
    *indexFile = getIndexFile(FE);
  if (file)
    *file = const_cast<FileEntry *>(FE);
  if (line)
    *line = SM.getLineNumber(FID, FileOffset);
  if (column)
    *column = SM.getColumnNumber(FID, FileOffset);
  if (offset)
    *offset = FileOffset;
}
Referenced by clang_indexLoc_getFileLocation().
Friends And Related Function Documentation
AttrListInfo
friend class AttrListInfo [friend]
Definition at line 331 of file CXIndexDataConsumer.h.
ScratchAlloc
friend class ScratchAlloc [friend]
Definition at line 296 of file CXIndexDataConsumer.h.
The documentation for this class was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.cpp