/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/exec/main.c File Reference
#include `config.h`
#include <sys/wait.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <paths.h>
Macros
#define FORK(FUNC)
Typedefs
typedef void(* exec_fun) ()
Functions
char ** get_environ ()
void expected_out_open (const char *expected)
void expected_out_close ()
void expected_out (const char *file)
void create_source (char *file)
void wait_for (pid_t child)
int main (int argc, char *const argv[])
Variables
char ** environ
Macro Definition Documentation
FORK
#define FORK(FUNC)
Value:
    { \
        pid_t child = fork(); \
        if (-1 == child) { \
            perror("fork"); \
            exit(EXIT_FAILURE); \
        } else if (0 == child) { \
            FUNC fprintf(stderr, "children process failed to exec\n"); \
            exit(EXIT_FAILURE); \
        } else { \
            wait_for(child); \
        } \
    }
Definition at line 97 of file main.c.
Typedef Documentation
exec_fun
typedef void(* exec_fun) ()
Definition at line 83 of file main.c.
Function Documentation
create_source()
void create_source (char * file)
Definition at line 73 of file main.c.
                               {
    FILE *fd = fopen(file, "w");
    if (!fd) {
        perror("fopen");
        exit(EXIT_FAILURE);
    }
    fprintf(fd, "typedef int score;\n");
    fclose(fd);
}
expected_out()
void expected_out (const char * file)
Definition at line 60 of file main.c.
                                    {
    if (need_comma)
        fprintf(fd, ",\n");
    else
        need_comma = 1;
    fprintf(fd, "{\n");
    fprintf(fd, " \"directory\": \"%s\",\n", cwd);
    fprintf(fd, " \"command\": \"cc -c %s\",\n", file);
    fprintf(fd, " \"file\": \"%s/%s\"\n", cwd, file);
    fprintf(fd, "}\n");
}
expected_out_close()
void expected_out_close ()
Definition at line 51 of file main.c.
                          {
    fprintf(fd, "]\n");
    fclose(fd);
    fd = NULL;
    free((void *)cwd);
    cwd = NULL;
}
Referenced by main().
expected_out_open()
void expected_out_open (const char * expected)
Definition at line 40 of file main.c.
                                             {
    cwd = getcwd(NULL, 0);
    fd = fopen(expected, "w");
    if (!fd) {
        perror("fopen");
        exit(EXIT_FAILURE);
    }
    fprintf(fd, "[\n");
    need_comma = 0;
}
Referenced by main().
get_environ()
char** get_environ ()
Definition at line 26 of file main.c.
                     {
#ifdef HAVE_NSGETENVIRON
    return *_NSGetEnviron();
#else
    return environ;
#endif
}
References environ.
main()
int main (int argc, char *const argv[])
Definition at line 266 of file main.c.
                                       {
    if (argc != 2)
        exit(EXIT_FAILURE);
    expected_out_open(argv[1]);
#ifdef HAVE_EXECV
    call_execv();
#endif
#ifdef HAVE_EXECVE
    call_execve();
#endif
#ifdef HAVE_EXECVP
    call_execvp();
#endif
#ifdef HAVE_EXECVP2
    call_execvP();
#endif
#ifdef HAVE_EXECVPE
    call_execvpe();
#endif
#ifdef HAVE_EXECT
    call_exect();
#endif
#ifdef HAVE_EXECL
    call_execl();
#endif
#ifdef HAVE_EXECLP
    call_execlp();
#endif
#ifdef HAVE_EXECLE
    call_execle();
#endif
#ifdef HAVE_POSIX_SPAWN
    call_posix_spawn();
#endif
#ifdef HAVE_POSIX_SPAWNP
    call_posix_spawnp();
#endif
    expected_out_close();
    return 0;
}
References expected_out_close(), and expected_out_open().
wait_for()
void wait_for (pid_t child)
Definition at line 85 of file main.c.
                           {
    int status;
    if (-1 == waitpid(child, &status, 0)) {
        perror("wait");
        exit(EXIT_FAILURE);
    }
    if (WIFEXITED(status) ? WEXITSTATUS(status) : EXIT_FAILURE) {
        fprintf(stderr, "children process has non zero exit code\n");
        exit(EXIT_FAILURE);
    }
}
Variable Documentation
environ
char** environ [extern]
Referenced by get_environ().