clang Namespace Reference
-rename
Namespaces
 comments
 cxcomment
 cxcursor
 cxdiag
 cxindex
 cxloc
 cxstring
 cxtu
 cxtype
 format
 index
 refactor
Classes
class CXDiagnosticSetImpl
class CXDiagnosticImpl
struct CXStoredDiagnostic
The storage behind a CXDiagnostic.
class CIndexer
class LibclangInvocationReporter
class CXLoadedDiagnostic
Functions
bool RunSafely (llvm::CrashRecoveryContext &CRC, llvm::function_ref< void()> Fn, unsigned Size)
unsigned GetSafetyThreadStackSize ()
Return the current size to request for `safety`.
void SetSafetyThreadStackSize (unsigned Value)
void setThreadBackgroundPriority ()
void PrintLibclangResourceUsage (CXTranslationUnit TU)
Print libclang's resource usage to standard error.
Detailed Description
-rename
Minimal clang-rename integration with Vim.

Before installing make sure one of the following is satisfied:

* clang-rename is in your PATH
* `g:clang_rename_path` in ~/.vimrc points to valid clang-rename executable
* `binary` in clang-rename.py points to valid to clang-rename executable

To install, simply put this into your ~/.vimrc for python2 support

    noremap <leader>cr :pyf <path-to>/clang-rename.py<cr>

For python3 use the following command (note the change from :pyf to :py3f)

    noremap <leader>cr :py3f <path-to>/clang-rename.py<cr>

IMPORTANT NOTE: Before running the tool, make sure you saved the file.

All you have to do now is to place a cursor on a variable/function/class which
you would like to rename and press '<leader>cr'. You will be prompted for a new
name if the cursor points to a valid symbol.
Function Documentation
GetSafetyThreadStackSize()
unsigned clang::GetSafetyThreadStackSize ()
Return the current size to request for `safety`.
Definition at line 8979 of file CIndex.cpp.
{ return SafetyStackThreadSize; }
Referenced by RunSafely().
PrintLibclangResourceUsage()
void clang::PrintLibclangResourceUsage (CXTranslationUnit TU)
Print libclang's resource usage to standard error.
Definition at line 8915 of file CIndex.cpp.
                                                           {
  CXTUResourceUsage Usage = clang_getCXTUResourceUsage(TU);
  for (unsigned I = 0; I != Usage.numEntries; ++I)
    fprintf(stderr, " %s: %lu\n",
            clang_getTUResourceUsageName(Usage.entries[I].kind),
            Usage.entries[I].amount);
  clang_disposeCXTUResourceUsage(Usage);
}
References clang_disposeCXTUResourceUsage(), clang_getCXTUResourceUsage(), and clang_getTUResourceUsageName().
RunSafely()
bool clang::RunSafely (llvm::CrashRecoveryContext & CRC, llvm::function_ref< void()> Fn, unsigned Size = 0)
Execution the given code `safely`, using crash recovery or safety threads when possible.
Returns
False if a crash was detected.
Definition at line 8970 of file CIndex.cpp.
                              {
  if (!Size)
    Size = GetSafetyThreadStackSize();
  if (Size && !getenv("LIBCLANG_NOTHREADS"))
    return CRC.RunSafelyOnThread(Fn, Size);
  return CRC.RunSafely(Fn);
}
References GetSafetyThreadStackSize().
SetSafetyThreadStackSize()
void clang::SetSafetyThreadStackSize (unsigned Value)
Set the current size to request for `safety` (or 0, if safety threads should not be used).
Definition at line 8981 of file CIndex.cpp.
{ SafetyStackThreadSize = Value; }
setThreadBackgroundPriority()
void clang::setThreadBackgroundPriority ()
Set the thread priority to background. FIXME: Move to llvm/Support.
Definition at line 8985 of file CIndex.cpp.
                                        {
  if (getenv("LIBCLANG_BGPRIO_DISABLE"))
    return;
#if LLVM_ENABLE_THREADS
  llvm::set_thread_priority(llvm::ThreadPriority::Background);
#endif
}