libscanbuild.compilation Namespace Reference
Functions
def split_command (command)
def classify_source (filename, c_compiler=True)
def compiler_language (command)
Variables
dictionary IGNORED_FLAGS
COMPILER_PATTERNS
Function Documentation
classify_source()
def libscanbuild.compilation.classify_source (filename, c_compiler = True)
 Return the language from file name extension. 
Definition at line 103 of file compilation.py.
def classify_source(filename, c_compiler=True):
    """ Return the language from file name extension. """
    mapping = {
        '.c': 'c' if c_compiler else 'c++',
        '.i': 'c-cpp-output' if c_compiler else 'c++-cpp-output',
        '.ii': 'c++-cpp-output',
        '.m': 'objective-c',
        '.mi': 'objective-c-cpp-output',
        '.mm': 'objective-c++',
        '.mii': 'objective-c++-cpp-output',
        '.C': 'c++',
        '.cc': 'c++',
        '.CC': 'c++',
        '.cp': 'c++',
        '.cpp': 'c++',
        '.cxx': 'c++',
        '.c++': 'c++',
        '.C++': 'c++',
        '.txx': 'c++'
    }
    __, extension = os.path.splitext(os.path.basename(filename))
    return mapping.get(extension)
Referenced by libscanbuild.analyze.classify_parameters(), libscanbuild.analyze.language_check(), and libscanbuild.compilation.split_command().
compiler_language()
def libscanbuild.compilation.compiler_language (command)
 A predicate to decide the command is a compiler call or not.

Returns 'c' or 'c++' when it match. None otherwise. 
Definition at line 129 of file compilation.py.
def compiler_language(command):
    """ A predicate to decide the command is a compiler call or not.
    Returns 'c' or 'c++' when it match. None otherwise. """
    cplusplus = re.compile(r'^(.+)(\+\+)(-.+|)$')
    if command:
        executable = os.path.basename(command[0])
        if any(pattern.match(executable) for pattern in COMPILER_PATTERNS):
            return 'c++' if cplusplus.match(executable) else 'c'
    return None
Referenced by libscanbuild.analyze.classify_parameters(), and libscanbuild.compilation.split_command().
split_command()
def libscanbuild.compilation.split_command (command)
 Returns a value when the command is a compilation, None otherwise.

The value on success is a named tuple with the following attributes:

    files:    list of source files
    flags:    list of compile options
    compiler: string value of 'c' or 'c++' 
Definition at line 59 of file compilation.py.
def split_command(command):
    """ Returns a value when the command is a compilation, None otherwise.
    The value on success is a named tuple with the following attributes:
        files: list of source files
        flags: list of compile options
        compiler: string value of 'c' or 'c++' """
    # the result of this method
    result = collections.namedtuple('Compilation',
                                    ['compiler', 'flags', 'files'])
    result.compiler = compiler_language(command)
    result.flags = []
    result.files = []
    # quit right now, if the program was not a C/C++ compiler
    if not result.compiler:
        return None
    # iterate on the compile options
    args = iter(command[1:])
    for arg in args:
        # quit when compilation pass is not involved
        if arg in {'-E', '-S', '-cc1', '-M', '-MM', '-###'}:
            return None
        # ignore some flags
        elif arg in IGNORED_FLAGS:
            count = IGNORED_FLAGS[arg]
            for _ in range(count):
                next(args)
        elif re.match(r'^-(l|L|Wl,).+', arg):
            pass
        # some parameters could look like filename, take as compile option
        elif arg in {'-D', '-I'}:
            result.flags.extend([arg, next(args)])
        # parameter which looks source file is taken...
        elif re.match(r'^[^-].+', arg) and classify_source(arg):
            result.files.append(arg)
        # and consider everything else as compile option.
        else:
            result.flags.append(arg)
    # do extra check on number of source files
    return result if result.files else None
References libscanbuild.compilation.classify_source(), and libscanbuild.compilation.compiler_language().
Referenced by libscanbuild.analyze.analyze_compiler_wrapper_impl(), and libscanbuild.intercept.format_entry().
Variable Documentation
COMPILER_PATTERNS
libscanbuild.compilation.COMPILER_PATTERNS
Initial value:
= frozenset([
    re.compile(r'^(intercept-|analyze-|)c(c|\+\+)$'),
    re.compile(r'^([^-]*-)*[mg](cc|\+\+)(-\d+(\.\d+){0,2})?$'),
    re.compile(r'^([^-]*-)*clang(\+\+)?(-\d+(\.\d+){0,2})?$'),
    re.compile(r'^llvm-g(cc|\+\+)$'),
])
Definition at line 51 of file compilation.py.
IGNORED_FLAGS
dictionary libscanbuild.compilation.IGNORED_FLAGS
Initial value:
= {
    # compiling only flag, ignored because the creator of compilation
    # database will explicitly set it.
    '-c': 0,
    # preprocessor macros, ignored because would cause duplicate entries in
    # the output (the only difference would be these flags). this is actual
    # finding from users, who suffered longer execution time caused by the
    # duplicates.
    '-MD': 0,
    '-MMD': 0,
    '-MG': 0,
    '-MP': 0,
    '-MF': 1,
    '-MT': 1,
    '-MQ': 1,
    # linker options, ignored because for compilation database will contain
    # compilation commands only. so, the compiler would ignore these flags
    # anyway. the benefit to get rid of them is to make the output more
    # readable.
    '-static': 0,
    '-shared': 0,
    '-s': 0,
    '-rdynamic': 0,
    '-l': 1,
    '-L': 1,
    '-u': 1,
    '-z': 1,
    '-T': 1,
    '-Xlinker': 1
}
Definition at line 19 of file compilation.py.