clang::cxcursor Namespace Reference
Classes
class VisitorJob
class CursorVisitor
class MacroExpansionCursor
Typedefs
typedef SmallVector< VisitorJob, 10 > VisitorWorkList
typedef llvm::PointerUnion< const OverloadExpr *, const Decl *, OverloadedTemplateStorage * > OverloadedDeclRefStorage
Internal storage for an overloaded declaration reference cursor;.
Functions
CXCursor getCursor (CXTranslationUnit, SourceLocation)
CXCursor MakeCXCursor (const clang::Attr *A, const clang::Decl *Parent, CXTranslationUnit TU)
CXCursor MakeCXCursor (const clang::Decl *D, CXTranslationUnit TU, SourceRange RegionOfInterest=SourceRange(), bool FirstInDeclGroup=true)
CXCursor MakeCXCursor (const clang::Stmt *S, const clang::Decl *Parent, CXTranslationUnit TU, SourceRange RegionOfInterest=SourceRange())
CXCursor MakeCXCursorInvalid (CXCursorKind K, CXTranslationUnit TU=nullptr)
CXCursor MakeCursorObjCSuperClassRef (ObjCInterfaceDecl *Super, SourceLocation Loc, CXTranslationUnit TU)
Create an Objective-C superclass reference at the given location.
std::pair< const ObjCInterfaceDecl *, SourceLocation > getCursorObjCSuperClassRef (CXCursor C)
CXCursor MakeCursorObjCProtocolRef (const ObjCProtocolDecl *Proto, SourceLocation Loc, CXTranslationUnit TU)
Create an Objective-C protocol reference at the given location.
std::pair< const ObjCProtocolDecl *, SourceLocation > getCursorObjCProtocolRef (CXCursor C)
CXCursor MakeCursorObjCClassRef (const ObjCInterfaceDecl *Class, SourceLocation Loc, CXTranslationUnit TU)
Create an Objective-C class reference at the given location.
std::pair< const ObjCInterfaceDecl *, SourceLocation > getCursorObjCClassRef (CXCursor C)
CXCursor MakeCursorTypeRef (const TypeDecl *Type, SourceLocation Loc, CXTranslationUnit TU)
Create a type reference at the given location.
std::pair< const TypeDecl *, SourceLocation > getCursorTypeRef (CXCursor C)
CXCursor MakeCursorTemplateRef (const TemplateDecl *Template, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a template at the given location.
std::pair< const TemplateDecl *, SourceLocation > getCursorTemplateRef (CXCursor C)
CXCursor MakeCursorNamespaceRef (const NamedDecl *NS, SourceLocation Loc, CXTranslationUnit TU)
std::pair< const NamedDecl *, SourceLocation > getCursorNamespaceRef (CXCursor C)
CXCursor MakeCursorVariableRef (const VarDecl *Var, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a variable at the given location.
std::pair< const VarDecl *, SourceLocation > getCursorVariableRef (CXCursor C)
CXCursor MakeCursorMemberRef (const FieldDecl *Field, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a field at the given location.
std::pair< const FieldDecl *, SourceLocation > getCursorMemberRef (CXCursor C)
CXCursor MakeCursorCXXBaseSpecifier (const CXXBaseSpecifier *B, CXTranslationUnit TU)
Create a CXX base specifier cursor.
const CXXBaseSpecifier * getCursorCXXBaseSpecifier (CXCursor C)
Unpack a CXXBaseSpecifier cursor into a CXXBaseSpecifier.
CXCursor MakePreprocessingDirectiveCursor (SourceRange Range, CXTranslationUnit TU)
Create a preprocessing directive cursor.
SourceRange getCursorPreprocessingDirective (CXCursor C)
Unpack a given preprocessing directive to retrieve its source range.
CXCursor MakeMacroDefinitionCursor (const MacroDefinitionRecord *, CXTranslationUnit TU)
Create a macro definition cursor.
const MacroDefinitionRecord * getCursorMacroDefinition (CXCursor C)
CXCursor MakeMacroExpansionCursor (MacroExpansion *, CXTranslationUnit TU)
Create a macro expansion cursor.
CXCursor MakeMacroExpansionCursor (MacroDefinitionRecord *, SourceLocation Loc, CXTranslationUnit TU)
CXCursor MakeInclusionDirectiveCursor (InclusionDirective *, CXTranslationUnit TU)
Create an inclusion directive cursor.
const InclusionDirective * getCursorInclusionDirective (CXCursor C)
CXCursor MakeCursorLabelRef (LabelStmt *Label, SourceLocation Loc, CXTranslationUnit TU)
Create a label reference at the given location.
std::pair< const LabelStmt *, SourceLocation > getCursorLabelRef (CXCursor C)
CXCursor MakeCursorOverloadedDeclRef (const OverloadExpr *E, CXTranslationUnit TU)
Create a overloaded declaration reference cursor for an expression.
CXCursor MakeCursorOverloadedDeclRef (const Decl *D, SourceLocation Location, CXTranslationUnit TU)
Create a overloaded declaration reference cursor for a declaration.
CXCursor MakeCursorOverloadedDeclRef (TemplateName Template, SourceLocation Location, CXTranslationUnit TU)
Create a overloaded declaration reference cursor for a template name.
std::pair< OverloadedDeclRefStorage, SourceLocation > getCursorOverloadedDeclRef (CXCursor C)
const Decl * getCursorDecl (CXCursor Cursor)
const Expr * getCursorExpr (CXCursor Cursor)
const Stmt * getCursorStmt (CXCursor Cursor)
const Attr * getCursorAttr (CXCursor Cursor)
ASTContext & getCursorContext (CXCursor Cursor)
ASTUnit * getCursorASTUnit (CXCursor Cursor)
CXTranslationUnit getCursorTU (CXCursor Cursor)
void getOverriddenCursors (CXCursor cursor, SmallVectorImpl< CXCursor > &overridden)
void * createOverridenCXCursorsPool ()
void disposeOverridenCXCursorsPool (void *pool)
Dispose of the overridden CXCursors pool.
std::pair< int, SourceLocation > getSelectorIdentifierIndexAndLoc (CXCursor)
CXCursor getSelectorIdentifierCursor (int SelIdx, CXCursor cursor)
CXCursor getTypeRefCursor (CXCursor cursor)
bool getDeclCursorUSR (const Decl *D, SmallVectorImpl< char > &Buf)
bool operator== (CXCursor X, CXCursor Y)
bool operator!= (CXCursor X, CXCursor Y)
bool isFirstInDeclGroup (CXCursor C)
Typedef Documentation
OverloadedDeclRefStorage
typedef llvm::PointerUnion<const OverloadExpr *, const Decl *, OverloadedTemplateStorage *> clang::cxcursor::OverloadedDeclRefStorage
Internal storage for an overloaded declaration reference cursor;.
Definition at line 230 of file CXCursor.h.
VisitorWorkList
typedef SmallVector<VisitorJob, 10> clang::cxcursor::VisitorWorkList
Definition at line 60 of file CursorVisitor.h.
Function Documentation
createOverridenCXCursorsPool()
void * clang::cxcursor::createOverridenCXCursorsPool ()
Create an opaque pool used for fast generation of overridden CXCursor arrays.
Definition at line 1565 of file CXCursor.cpp.
                                             {
  return new OverridenCursorsPool();
}
Referenced by clang::cxtu::MakeCXTranslationUnit().
disposeOverridenCXCursorsPool()
void clang::cxcursor::disposeOverridenCXCursorsPool (void * pool)
Dispose of the overridden CXCursors pool.
Definition at line 1569 of file CXCursor.cpp.
                                                       {
  delete static_cast<OverridenCursorsPool *>(pool);
}
Referenced by clang_disposeTranslationUnit().
getCursor()
CXCursor clang::cxcursor::getCursor (CXTranslationUnit TU, SourceLocation SLoc)
Definition at line 6123 of file CIndex.cpp.
                                                                      {
  assert(TU);
  // Guard against an invalid SourceLocation, or we may assert in one
  // of the following calls.
  if (SLoc.isInvalid())
    return clang_getNullCursor();
  ASTUnit *CXXUnit = cxtu::getASTUnit(TU);
  // Translate the given source location to make it point at the beginning of
  // the token under the cursor.
  SLoc = Lexer::GetBeginningOfToken(SLoc, CXXUnit->getSourceManager(),
                                    CXXUnit->getASTContext().getLangOpts());
  CXCursor Result = MakeCXCursorInvalid(CXCursor_NoDeclFound);
  if (SLoc.isValid()) {
    GetCursorData ResultData(CXXUnit->getSourceManager(), SLoc, Result);
    CursorVisitor CursorVis(TU, GetCursorVisitor, &ResultData,
                            /*VisitPreprocessorLast=*/true,
                            /*VisitIncludedEntities=*/false,
                            SourceLocation(SLoc));
    CursorVis.visitFileRegion();
  }
  return Result;
}
References clang_getNullCursor(), and MakeCXCursorInvalid().
getCursorASTUnit()
ASTUnit * clang::cxcursor::getCursorASTUnit (CXCursor Cursor)
Definition at line 1126 of file CXCursor.cpp.
                                                   {
  CXTranslationUnit TU = getCursorTU(Cursor);
  if (!TU)
    return nullptr;
  return cxtu::getASTUnit(TU);
}
Referenced by clang_findReferencesInFile(), clang_getCursorCompletionString(), and getCursorPreprocessingDirective().
getCursorAttr()
const Attr * clang::cxcursor::getCursorAttr (CXCursor Cursor)
Definition at line 1118 of file CXCursor.cpp.
                                                   {
  return static_cast<const Attr *>(Cursor.data[1]);
}
Referenced by clang_getIBOutletCollectionType().
getCursorContext()
ASTContext & clang::cxcursor::getCursorContext (CXCursor Cursor)
Definition at line 1122 of file CXCursor.cpp.
                                                      {
  return getCursorASTUnit(Cursor)->getASTContext();
}
Referenced by clang_Cursor_getBriefCommentText(), clang_Cursor_getCommentRange(), clang_Cursor_getRawCommentText(), clang_Cursor_getReceiverType(), clang_Cursor_getSpellingNameRange(), clang_Cursor_isDynamicCall(), clang_getCursorDisplayName(), clang_getCursorLocation(), clang_getCursorPrettyPrinted(), clang_getCursorPrintingPolicy(), clang_getCursorReferenceNameRange(), clang_getCursorSpelling(), clang_getDeclObjCTypeEncoding(), and clang_getFieldDeclBitWidth().
getCursorCXXBaseSpecifier()
const CXXBaseSpecifier * clang::cxcursor::getCursorCXXBaseSpecifier (CXCursor C)
Unpack a CXXBaseSpecifier cursor into a CXXBaseSpecifier.
Definition at line 970 of file CXCursor.cpp.
                                                                      {
  assert(C.kind == CXCursor_CXXBaseSpecifier);
  return static_cast<const CXXBaseSpecifier *>(C.data[0]);
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), clang_getCursorType(), and clang_getCXXAccessSpecifier().
getCursorDecl()
const Decl * clang::cxcursor::getCursorDecl (CXCursor Cursor)
Definition at line 1101 of file CXCursor.cpp.
                                                   {
  return static_cast<const Decl *>(Cursor.data[0]);
}
Referenced by clang_Cursor_getArgument(), clang_Cursor_getBriefCommentText(), clang_Cursor_getCommentRange(), clang_Cursor_getCXXManglings(), clang_Cursor_getMangling(), clang_Cursor_getModule(), clang_Cursor_getNumArguments(), clang_Cursor_getNumTemplateArguments(), clang_Cursor_getObjCDeclQualifiers(), clang_Cursor_getObjCManglings(), clang_Cursor_getObjCPropertyAttributes(), clang_Cursor_getObjCPropertyGetterName(), clang_Cursor_getObjCPropertySetterName(), clang_Cursor_getRawCommentText(), clang_Cursor_getSpellingNameRange(), clang_Cursor_getVarDeclInitializer(), clang_Cursor_hasAttrs(), clang_Cursor_hasVarDeclExternalStorage(), clang_Cursor_hasVarDeclGlobalStorage(), clang_Cursor_isAnonymous(), clang_Cursor_isAnonymousRecordDecl(), clang_Cursor_isBitField(), clang_Cursor_isExternalSymbol(), clang_Cursor_isFunctionInlined(), clang_Cursor_isInlineNamespace(), clang_Cursor_isObjCOptional(), clang_Cursor_isVariadic(), clang_CXXConstructor_isConvertingConstructor(), clang_CXXConstructor_isCopyConstructor(), clang_CXXConstructor_isDefaultConstructor(), clang_CXXConstructor_isMoveConstructor(), clang_CXXField_isMutable(), clang_CXXMethod_isConst(), clang_CXXMethod_isDefaulted(), clang_CXXMethod_isPureVirtual(), clang_CXXMethod_isStatic(), clang_CXXMethod_isVirtual(), clang_CXXRecord_isAbstract(), clang_EnumDecl_isScoped(), clang_getCanonicalCursor(), clang_getCursorCompletionString(), clang_getCursorDefinition(), clang_getCursorDisplayName(), clang_getCursorLexicalParent(), clang_getCursorLinkage(), clang_getCursorPlatformAvailability(), clang_getCursorPrettyPrinted(), clang_getCursorReferenced(), clang_getCursorResultType(), clang_getCursorSemanticParent(), clang_getCursorTLSKind(), clang_getCursorType(), clang_getCursorUSR(), clang_getCursorVisibility(), clang_getDeclObjCTypeEncoding(), clang_getDefinitionSpellingAndExtent(), clang_getEnumConstantDeclUnsignedValue(), clang_getEnumConstantDeclValue(), clang_getEnumDeclIntegerType(), clang_getFieldDeclBitWidth(), clang_getSpecializedCursorTemplate(), clang_getTypedefDeclUnderlyingType(), clang_isInvalidDeclaration(), clang_Type_visitFields(), getOverriddenCursors(), getSelectorIdentifierCursor(), and getSelectorIdentifierIndexAndLoc().
getCursorExpr()
const Expr * clang::cxcursor::getCursorExpr (CXCursor Cursor)
Definition at line 1105 of file CXCursor.cpp.
                                                   {
  return dyn_cast_or_null<Expr>(getCursorStmt(Cursor));
}
Referenced by clang_Cursor_getArgument(), clang_Cursor_getNumArguments(), clang_Cursor_getReceiverType(), clang_Cursor_getSpellingNameRange(), clang_Cursor_isDynamicCall(), clang_getCursorReferenced(), clang_getCursorReferenceNameRange(), clang_getCursorSpelling(), clang_getCursorType(), getSelectorIdentifierCursor(), getSelectorIdentifierIndexAndLoc(), and getTypeRefCursor().
getCursorInclusionDirective()
const InclusionDirective * clang::cxcursor::getCursorInclusionDirective (CXCursor C)
Unpack a given inclusion directive cursor to retrieve its source range.
Definition at line 1040 of file CXCursor.cpp.
                                                                          {
  assert(C.kind == CXCursor_InclusionDirective);
  return static_cast<const InclusionDirective *>(C.data[0]);
}
Referenced by clang_getIncludedFile().
getCursorLabelRef()
std::pair< const LabelStmt *, SourceLocation > clang::cxcursor::getCursorLabelRef (CXCursor C)
Unpack a label reference into the label statement it refers to and the location of the reference.
Definition at line 1055 of file CXCursor.cpp.
                                      {
  assert(C.kind == CXCursor_LabelRef);
  return std::make_pair(static_cast<const LabelStmt *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), and clang_getCursorSpelling().
getCursorMacroDefinition()
const MacroDefinitionRecord * clang::cxcursor::getCursorMacroDefinition (CXCursor C)
Unpack a given macro definition cursor to retrieve its source range.
Definition at line 998 of file CXCursor.cpp.
                                                                          {
  assert(C.kind == CXCursor_MacroDefinition);
  return static_cast<const MacroDefinitionRecord *>(C.data[0]);
}
Referenced by clang_getCursorCompletionString().
getCursorMemberRef()
std::pair< const FieldDecl *, SourceLocation > clang::cxcursor::getCursorMemberRef (CXCursor C)
Unpack a MemberRef cursor into the field it references and the location where the reference occurred.
Definition at line 958 of file CXCursor.cpp.
                                       {
  assert(C.kind == CXCursor_MemberRef);
  return std::make_pair(static_cast<const FieldDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), and clang_getCursorType().
getCursorNamespaceRef()
std::pair< const NamedDecl *, SourceLocation > clang::cxcursor::getCursorNamespaceRef (CXCursor C)
Unpack a NamespaceRef cursor into the namespace or namespace alias it references and the location where the reference occurred.
Definition at line 925 of file CXCursor.cpp.
                                          {
  assert(C.kind == CXCursor_NamespaceRef);
  return std::make_pair(static_cast<const NamedDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), and clang_getCursorSpelling().
getCursorObjCClassRef()
std::pair< const ObjCInterfaceDecl *, SourceLocation > clang::cxcursor::getCursorObjCClassRef (CXCursor C)
Unpack an ObjCClassRef cursor into the class it references and optionally the location where the reference occurred.
Definition at line 876 of file CXCursor.cpp.
                                          {
  assert(C.kind == CXCursor_ObjCClassRef);
  return std::make_pair(static_cast<const ObjCInterfaceDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), and clang_getCursorType().
getCursorObjCProtocolRef()
std::pair< const ObjCProtocolDecl *, SourceLocation > clang::cxcursor::getCursorObjCProtocolRef (CXCursor C)
Unpack an ObjCProtocolRef cursor into the protocol it references and optionally the location where the reference occurred.
Definition at line 857 of file CXCursor.cpp.
                                             {
  assert(C.kind == CXCursor_ObjCProtocolRef);
  return std::make_pair(static_cast<const ObjCProtocolDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), and clang_getCursorSpelling().
getCursorObjCSuperClassRef()
std::pair< const ObjCInterfaceDecl *, SourceLocation > clang::cxcursor::getCursorObjCSuperClassRef (CXCursor C)
Unpack an ObjCSuperClassRef cursor into the interface it references and optionally the location where the reference occurred.
Definition at line 841 of file CXCursor.cpp.
                                               {
  assert(C.kind == CXCursor_ObjCSuperClassRef);
  return std::make_pair(static_cast<const ObjCInterfaceDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), and clang_getCursorType().
getCursorOverloadedDeclRef()
std::pair< cxcursor::OverloadedDeclRefStorage, SourceLocation > clang::cxcursor::getCursorOverloadedDeclRef (CXCursor C)
Unpack an overloaded declaration reference into an expression, declaration, or template name along with the source location.
Definition at line 1094 of file CXCursor.cpp.
                                               {
  assert(C.kind == CXCursor_OverloadedDeclRef);
  return std::make_pair(OverloadedDeclRefStorage::getFromOpaqueValue(
                            const_cast<void *>(C.data[0])),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), clang_getNumOverloadedDecls(), and clang_getOverloadedDecl().
getCursorPreprocessingDirective()
SourceRange clang::cxcursor::getCursorPreprocessingDirective (CXCursor C)
Unpack a given preprocessing directive to retrieve its source range.
Definition at line 984 of file CXCursor.cpp.
                                                                {
  assert(C.kind == CXCursor_PreprocessingDirective);
  SourceRange Range(SourceLocation::getFromPtrEncoding(C.data[0]),
                    SourceLocation::getFromPtrEncoding(C.data[1]));
  ASTUnit *TU = getCursorASTUnit(C);
  return TU->mapRangeFromPreamble(Range);
}
References getCursorASTUnit().
getCursorStmt()
const Stmt * clang::cxcursor::getCursorStmt (CXCursor Cursor)
Definition at line 1109 of file CXCursor.cpp.
                                                   {
  if (Cursor.kind == CXCursor_ObjCSuperClassRef ||
      Cursor.kind == CXCursor_ObjCProtocolRef ||
      Cursor.kind == CXCursor_ObjCClassRef)
    return nullptr;
  return static_cast<const Stmt *>(Cursor.data[1]);
}
Referenced by clang_Cursor_getSpellingNameRange().
getCursorTemplateRef()
std::pair< const TemplateDecl *, SourceLocation > clang::cxcursor::getCursorTemplateRef (CXCursor C)
Unpack a TemplateRef cursor into the template it references and the location where the reference occurred.
Definition at line 907 of file CXCursor.cpp.
                                         {
  assert(C.kind == CXCursor_TemplateRef);
  return std::make_pair(static_cast<const TemplateDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), and clang_getCursorSpelling().
getCursorTU()
CXTranslationUnit clang::cxcursor::getCursorTU (CXCursor Cursor)
Definition at line 1133 of file CXCursor.cpp.
                                                       {
  return static_cast<CXTranslationUnit>(const_cast<void *>(Cursor.data[2]));
}
Referenced by clang_Cursor_getArgument(), clang_Cursor_getReceiverType(), clang_Cursor_getTranslationUnit(), clang_Cursor_getVarDeclInitializer(), clang_disposeOverriddenCursors(), clang_getCanonicalCursor(), clang_getCursorDefinition(), clang_getCursorReferenced(), clang_getCursorResultType(), clang_getCursorSpelling(), clang_getCursorType(), clang_getCursorUSR(), clang_getEnumDeclIntegerType(), clang_getIBOutletCollectionType(), clang_getOverloadedDecl(), clang_getOverriddenCursors(), clang_getSpecializedCursorTemplate(), clang_getTypedefDeclUnderlyingType(), clang_visitChildren(), getOverriddenCursors(), and getTypeRefCursor().
getCursorTypeRef()
std::pair< const TypeDecl *, SourceLocation > clang::cxcursor::getCursorTypeRef (CXCursor C)
Unpack a TypeRef cursor into the class it references and optionally the location where the reference occurred.
Definition at line 891 of file CXCursor.cpp.
                                     {
  assert(C.kind == CXCursor_TypeRef);
  return std::make_pair(static_cast<const TypeDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), and clang_getCursorType().
getCursorVariableRef()
std::pair< const VarDecl *, SourceLocation > clang::cxcursor::getCursorVariableRef (CXCursor C)
Unpack a VariableRef cursor into the variable it references and the location where the where the reference occurred.
Definition at line 941 of file CXCursor.cpp.
                                         {
  assert(C.kind == CXCursor_VariableRef);
  return std::make_pair(static_cast<const VarDecl *>(C.data[0]),
                        SourceLocation::getFromPtrEncoding(C.data[1]));
}
Referenced by clang_getCursorLocation(), clang_getCursorSpelling(), and clang_getCursorType().
getDeclCursorUSR()
bool clang::cxcursor::getDeclCursorUSR (const Decl * D, SmallVectorImpl< char > & Buf)
Generate a USR for
D and put it in
Buf.
Returns
true if no USR was computed or the result should be ignored, false otherwise.
Definition at line 34 of file CIndexUSRs.cpp.
                                                                         {
  return generateUSRForDecl(D, Buf);
}
Referenced by clang_getCursorUSR().
getOverriddenCursors()
void clang::cxcursor::getOverriddenCursors (CXCursor cursor, SmallVectorImpl< CXCursor > & overridden)
Definition at line 1137 of file CXCursor.cpp.
                                                                           {
  assert(clang_isDeclaration(cursor.kind));
  const NamedDecl *D = dyn_cast_or_null<NamedDecl>(getCursorDecl(cursor));
  if (!D)
    return;
  CXTranslationUnit TU = getCursorTU(cursor);
  SmallVector<const NamedDecl *, 8> OverDecls;
  D->getASTContext().getOverriddenMethods(D, OverDecls);
  for (SmallVectorImpl<const NamedDecl *>::iterator I = OverDecls.begin(),
                                                    E = OverDecls.end();
       I != E; ++I) {
    overridden.push_back(MakeCXCursor(*I, TU));
  }
}
References clang_isDeclaration(), getCursorDecl(), getCursorTU(), and MakeCXCursor().
Referenced by clang_getOverriddenCursors().
getSelectorIdentifierCursor()
CXCursor clang::cxcursor::getSelectorIdentifierCursor (int SelIdx, CXCursor cursor)
Definition at line 1173 of file CXCursor.cpp.
                                                                          {
  CXCursor newCursor = cursor;
  if (cursor.kind == CXCursor_ObjCMessageExpr) {
    if (SelIdx == -1 ||
        unsigned(SelIdx) >=
            cast<ObjCMessageExpr>(getCursorExpr(cursor))->getNumSelectorLocs())
      newCursor.xdata = -1;
    else
      newCursor.xdata = SelIdx;
  } else if (cursor.kind == CXCursor_ObjCClassMethodDecl ||
             cursor.kind == CXCursor_ObjCInstanceMethodDecl) {
    if (SelIdx == -1 ||
        unsigned(SelIdx) >=
            cast<ObjCMethodDecl>(getCursorDecl(cursor))->getNumSelectorLocs())
      newCursor.xdata = -1;
    else
      newCursor.xdata = SelIdx;
  }
  return newCursor;
}
References getCursorDecl(), and getCursorExpr().
getSelectorIdentifierIndexAndLoc()
std::pair< int, SourceLocation > clang::cxcursor::getSelectorIdentifierIndexAndLoc (CXCursor cursor)
Returns a index/location pair for a selector identifier if the cursor points to one.
Definition at line 1156 of file CXCursor.cpp.
                                                          {
  if (cursor.kind == CXCursor_ObjCMessageExpr) {
    if (cursor.xdata != -1)
      return std::make_pair(cursor.xdata,
                            cast<ObjCMessageExpr>(getCursorExpr(cursor))
                                ->getSelectorLoc(cursor.xdata));
  } else if (cursor.kind == CXCursor_ObjCClassMethodDecl ||
             cursor.kind == CXCursor_ObjCInstanceMethodDecl) {
    if (cursor.xdata != -1)
      return std::make_pair(cursor.xdata,
                            cast<ObjCMethodDecl>(getCursorDecl(cursor))
                                ->getSelectorLoc(cursor.xdata));
  }
  return std::make_pair(-1, SourceLocation());
}
References getCursorDecl(), and getCursorExpr().
Referenced by clang_Cursor_getObjCSelectorIndex().
getTypeRefCursor()
CXCursor clang::cxcursor::getTypeRefCursor (CXCursor cursor)
Definition at line 1196 of file CXCursor.cpp.
                                                   {
  if (cursor.kind != CXCursor_CallExpr)
    return cursor;
  if (cursor.xdata == 0)
    return cursor;
  const Expr *E = getCursorExpr(cursor);
  TypeSourceInfo *Type = nullptr;
  if (const CXXUnresolvedConstructExpr *UnCtor =
          dyn_cast<CXXUnresolvedConstructExpr>(E)) {
    Type = UnCtor->getTypeSourceInfo();
  } else if (const CXXTemporaryObjectExpr *Tmp =
                 dyn_cast<CXXTemporaryObjectExpr>(E)) {
    Type = Tmp->getTypeSourceInfo();
  }
  if (!Type)
    return cursor;
  CXTranslationUnit TU = getCursorTU(cursor);
  QualType Ty = Type->getType();
  TypeLoc TL = Type->getTypeLoc();
  SourceLocation Loc = TL.getBeginLoc();
  if (const ElaboratedType *ElabT = Ty->getAs<ElaboratedType>()) {
    Ty = ElabT->getNamedType();
    ElaboratedTypeLoc ElabTL = TL.castAs<ElaboratedTypeLoc>();
    Loc = ElabTL.getNamedTypeLoc().getBeginLoc();
  }
  if (const TypedefType *Typedef = Ty->getAs<TypedefType>())
    return MakeCursorTypeRef(Typedef->getDecl(), Loc, TU);
  if (const TagType *Tag = Ty->getAs<TagType>())
    return MakeCursorTypeRef(Tag->getDecl(), Loc, TU);
  if (const TemplateTypeParmType *TemplP = Ty->getAs<TemplateTypeParmType>())
    return MakeCursorTypeRef(TemplP->getDecl(), Loc, TU);
  return cursor;
}
References getCursorExpr(), getCursorTU(), and MakeCursorTypeRef().
isFirstInDeclGroup()
bool clang::cxcursor::isFirstInDeclGroup (CXCursor C)
Return true if the cursor represents a declaration that is the first in a declaration group.
Definition at line 1244 of file CXCursor.cpp.
                                            {
  assert(clang_isDeclaration(C.kind));
  return ((uintptr_t)(C.data[1])) != 0;
}
References clang_isDeclaration().
MakeCursorCXXBaseSpecifier()
CXCursor clang::cxcursor::MakeCursorCXXBaseSpecifier (const CXXBaseSpecifier * B, CXTranslationUnit TU)
Create a CXX base specifier cursor.
Definition at line 964 of file CXCursor.cpp.
                                                                    {
  CXCursor C = {CXCursor_CXXBaseSpecifier, 0, {B, nullptr, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::VisitCXXRecordDecl().
MakeCursorLabelRef()
CXCursor clang::cxcursor::MakeCursorLabelRef (LabelStmt * Label, SourceLocation Loc, CXTranslationUnit TU)
Create a label reference at the given location.
Definition at line 1045 of file CXCursor.cpp.
                                                            {
  assert(Label && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_LabelRef, 0, {Label, RawLoc, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::RunVisitorWorkList().
MakeCursorMemberRef()
CXCursor clang::cxcursor::MakeCursorMemberRef (const FieldDecl * Field, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a field at the given location.
Definition at line 947 of file CXCursor.cpp.
                                                             {
  assert(Field && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_MemberRef, 0, {Field, RawLoc, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::RunVisitorWorkList(), and clang::cxcursor::CursorVisitor::VisitObjCPropertyImplDecl().
MakeCursorNamespaceRef()
CXCursor clang::cxcursor::MakeCursorNamespaceRef (const NamedDecl * NS, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a namespace or namespace alias at the given location.
Definition at line 913 of file CXCursor.cpp.
                                                                {
  assert(NS && (isa<NamespaceDecl>(NS) || isa<NamespaceAliasDecl>(NS)) && TU &&
         "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_NamespaceRef, 0, {NS, RawLoc, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::VisitNamespaceAliasDecl(), clang::cxcursor::CursorVisitor::VisitNestedNameSpecifier(), clang::cxcursor::CursorVisitor::VisitNestedNameSpecifierLoc(), and clang::cxcursor::CursorVisitor::VisitUsingDirectiveDecl().
MakeCursorObjCClassRef()
CXCursor clang::cxcursor::MakeCursorObjCClassRef (const ObjCInterfaceDecl * Class, SourceLocation Loc, CXTranslationUnit TU)
Create an Objective-C class reference at the given location.
Definition at line 863 of file CXCursor.cpp.
                                                                {
  // 'Class' can be null for invalid code.
  if (!Class)
    return MakeCXCursorInvalid(CXCursor_InvalidCode);
  assert(TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_ObjCClassRef, 0, {Class, RawLoc, TU}};
  return C;
}
References MakeCXCursorInvalid().
Referenced by clang::cxindex::AttrListInfo::AttrListInfo(), clang::cxindex::CXIndexDataConsumer::handleObjCCategory(), clang::cxindex::CXIndexDataConsumer::handleObjCCategoryImpl(), clang::cxindex::CXIndexDataConsumer::handleObjCInterface(), clang::cxcursor::CursorVisitor::VisitObjCCategoryDecl(), clang::cxcursor::CursorVisitor::VisitObjCCategoryImplDecl(), and clang::cxcursor::CursorVisitor::VisitObjCInterfaceDecl().
MakeCursorObjCProtocolRef()
CXCursor clang::cxcursor::MakeCursorObjCProtocolRef (const ObjCProtocolDecl * Proto, SourceLocation Loc, CXTranslationUnit TU)
Create an Objective-C protocol reference at the given location.
Definition at line 847 of file CXCursor.cpp.
                                                                   {
  assert(Proto && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_ObjCProtocolRef, 0, {Proto, RawLoc, TU}};
  return C;
}
Referenced by clang::cxindex::CXIndexDataConsumer::handleObjCProtocol(), clang::cxcursor::CursorVisitor::VisitObjCCategoryDecl(), clang::cxcursor::CursorVisitor::VisitObjCInterfaceDecl(), and clang::cxcursor::CursorVisitor::VisitObjCProtocolDecl().
MakeCursorObjCSuperClassRef()
CXCursor clang::cxcursor::MakeCursorObjCSuperClassRef (ObjCInterfaceDecl * Super, SourceLocation Loc, CXTranslationUnit TU)
Create an Objective-C superclass reference at the given location.
Definition at line 831 of file CXCursor.cpp.
                                                                     {
  assert(Super && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_ObjCSuperClassRef, 0, {Super, RawLoc, TU}};
  return C;
}
Referenced by clang::cxindex::CXIndexDataConsumer::handleObjCInterface(), clang::cxcursor::CursorVisitor::VisitObjCImplementationDecl(), and clang::cxcursor::CursorVisitor::VisitObjCInterfaceDecl().
MakeCursorOverloadedDeclRef() [1/3]
CXCursor clang::cxcursor::MakeCursorOverloadedDeclRef (const Decl * D, SourceLocation Location, CXTranslationUnit TU)
Create a overloaded declaration reference cursor for a declaration.
Definition at line 1071 of file CXCursor.cpp.
                                                                     {
  assert(D && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  OverloadedDeclRefStorage Storage(D);
  CXCursor C = {
      CXCursor_OverloadedDeclRef, 0, {Storage.getOpaqueValue(), RawLoc, TU}};
  return C;
}
MakeCursorOverloadedDeclRef() [2/3]
CXCursor clang::cxcursor::MakeCursorOverloadedDeclRef (const OverloadExpr * E, CXTranslationUnit TU)
Create a overloaded declaration reference cursor for an expression.
Definition at line 1061 of file CXCursor.cpp.
                                                                     {
  assert(E && TU && "Invalid arguments!");
  OverloadedDeclRefStorage Storage(E);
  void *RawLoc = E->getNameLoc().getPtrEncoding();
  CXCursor C = {
      CXCursor_OverloadedDeclRef, 0, {Storage.getOpaqueValue(), RawLoc, TU}};
  return C;
}
Referenced by clang_getCursorDefinition(), clang_getCursorReferenced(), clang::cxcursor::CursorVisitor::VisitTemplateName(), and clang::cxcursor::CursorVisitor::VisitUsingDecl().
MakeCursorOverloadedDeclRef() [3/3]
CXCursor clang::cxcursor::MakeCursorOverloadedDeclRef (TemplateName Template, SourceLocation Location, CXTranslationUnit TU)
Create a overloaded declaration reference cursor for a template name.
Definition at line 1082 of file CXCursor.cpp.
                                                                     {
  assert(Name.getAsOverloadedTemplate() && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  OverloadedDeclRefStorage Storage(Name.getAsOverloadedTemplate());
  CXCursor C = {
      CXCursor_OverloadedDeclRef, 0, {Storage.getOpaqueValue(), RawLoc, TU}};
  return C;
}
MakeCursorTemplateRef()
CXCursor clang::cxcursor::MakeCursorTemplateRef (const TemplateDecl * Template, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a template at the given location.
Definition at line 897 of file CXCursor.cpp.
                                                               {
  assert(Template && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_TemplateRef, 0, {Template, RawLoc, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::VisitTemplateName().
MakeCursorTypeRef()
CXCursor clang::cxcursor::MakeCursorTypeRef (const TypeDecl * Type, SourceLocation Loc, CXTranslationUnit TU)
Create a type reference at the given location.
Definition at line 882 of file CXCursor.cpp.
                                                           {
  assert(Type && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_TypeRef, 0, {Type, RawLoc, TU}};
  return C;
}
Referenced by getTypeRefCursor(), clang::cxcursor::CursorVisitor::VisitNestedNameSpecifier(), and clang::cxcursor::CursorVisitor::VisitTagTypeLoc().
MakeCursorVariableRef()
CXCursor clang::cxcursor::MakeCursorVariableRef (const VarDecl * Var, SourceLocation Loc, CXTranslationUnit TU)
Create a reference to a variable at the given location.
Definition at line 931 of file CXCursor.cpp.
                                                               {
  assert(Var && TU && "Invalid arguments!");
  void *RawLoc = Loc.getPtrEncoding();
  CXCursor C = {CXCursor_VariableRef, 0, {Var, RawLoc, TU}};
  return C;
}
MakeCXCursor() [1/3]
CXCursor clang::cxcursor::MakeCXCursor (const clang::Attr * A, const clang::Decl * Parent, CXTranslationUnit TU)
Referenced by clang::cxindex::AttrListInfo::AttrListInfo(), clang_Cursor_getArgument(), clang_Cursor_getVarDeclInitializer(), clang_getCanonicalCursor(), clang_getCursorDefinition(), clang_getCursorLexicalParent(), clang_getCursorReferenced(), clang_getCursorSemanticParent(), clang_getOverloadedDecl(), clang_getSpecializedCursorTemplate(), clang_Type_visitFields(), clang::cxcursor::CursorVisitor::EnqueueWorkList(), getOverriddenCursors(), clang::cxcursor::CursorVisitor::RunVisitorWorkList(), clang::cxcursor::CursorVisitor::VisitArrayTypeLoc(), clang::cxcursor::CursorVisitor::VisitAttributes(), clang::cxcursor::CursorVisitor::VisitBlockDecl(), clang::cxcursor::CursorVisitor::VisitDecompositionDecl(), clang::cxcursor::CursorVisitor::VisitEnumConstantDecl(), clang::cxcursor::CursorVisitor::VisitFieldDecl(), clang::cxcursor::CursorVisitor::VisitFriendDecl(), clang::cxcursor::CursorVisitor::VisitFunctionTypeLoc(), clang::cxcursor::CursorVisitor::VisitNonTypeTemplateParmDecl(), clang::cxcursor::CursorVisitor::VisitObjCMethodDecl(), clang::cxcursor::CursorVisitor::VisitObjCPropertyDecl(), clang::cxcursor::CursorVisitor::VisitObjCTypeParamList(), clang::cxcursor::CursorVisitor::VisitStaticAssertDecl(), clang::cxcursor::CursorVisitor::VisitTagTypeLoc(), clang::cxcursor::CursorVisitor::VisitTemplateArgumentLoc(), clang::cxcursor::CursorVisitor::VisitTemplateParameters(), clang::cxcursor::CursorVisitor::VisitTemplateTypeParmDecl(), clang::cxcursor::CursorVisitor::VisitTypeAliasTemplateDecl(), and clang::cxcursor::CursorVisitor::VisitVarDecl().
MakeCXCursor() [2/3]
CXCursor clang::cxcursor::MakeCXCursor (const clang::Decl * D, CXTranslationUnit TU, SourceRange RegionOfInterest = SourceRange(), bool FirstInDeclGroup = true)
MakeCXCursor() [3/3]
CXCursor clang::cxcursor::MakeCXCursor (const clang::Stmt * S, const clang::Decl * Parent, CXTranslationUnit TU, SourceRange RegionOfInterest = SourceRange())
MakeCXCursorInvalid()
CXCursor clang::cxcursor::MakeCXCursorInvalid (CXCursorKind K, CXTranslationUnit TU = nullptr)
Definition at line 34 of file CXCursor.cpp.
                                                                           {
  assert(K >= CXCursor_FirstInvalid && K <= CXCursor_LastInvalid);
  CXCursor C = {K, 0, {nullptr, nullptr, TU}};
  return C;
}
Referenced by clang_getNullCursor(), clang_getOverriddenCursors(), clang_getTypeDeclaration(), getCursor(), llvm::DenseMapInfo< CXCursor >::getEmptyKey(), llvm::DenseMapInfo< CXCursor >::getTombstoneKey(), and MakeCursorObjCClassRef().
MakeInclusionDirectiveCursor()
CXCursor clang::cxcursor::MakeInclusionDirectiveCursor (InclusionDirective * ID, CXTranslationUnit TU)
Create an inclusion directive cursor.
Definition at line 1034 of file CXCursor.cpp.
                                                                      {
  CXCursor C = {CXCursor_InclusionDirective, 0, {ID, nullptr, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::visitPreprocessedEntities().
MakeMacroDefinitionCursor()
CXCursor clang::cxcursor::MakeMacroDefinitionCursor (const MacroDefinitionRecord * MI, CXTranslationUnit TU)
Create a macro definition cursor.
Definition at line 992 of file CXCursor.cpp.
                                                                   {
  CXCursor C = {CXCursor_MacroDefinition, 0, {MI, nullptr, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::visitPreprocessedEntities().
MakeMacroExpansionCursor() [1/2]
CXCursor clang::cxcursor::MakeMacroExpansionCursor (MacroDefinitionRecord * MI, SourceLocation Loc, CXTranslationUnit TU)
Create a `pseudo` macro expansion cursor, using a macro definition and a source location.
Definition at line 1009 of file CXCursor.cpp.
                                                                  {
  assert(Loc.isValid());
  CXCursor C = {CXCursor_MacroExpansion, 0, {MI, Loc.getPtrEncoding(), TU}};
  return C;
}
MakeMacroExpansionCursor() [2/2]
CXCursor clang::cxcursor::MakeMacroExpansionCursor (MacroExpansion * MI, CXTranslationUnit TU)
Create a macro expansion cursor.
Definition at line 1003 of file CXCursor.cpp.
                                                                  {
  CXCursor C = {CXCursor_MacroExpansion, 0, {MI, nullptr, TU}};
  return C;
}
Referenced by clang::cxcursor::CursorVisitor::visitPreprocessedEntities().
MakePreprocessingDirectiveCursor()
CXCursor clang::cxcursor::MakePreprocessingDirectiveCursor (SourceRange Range, CXTranslationUnit TU)
Create a preprocessing directive cursor.
Definition at line 975 of file CXCursor.cpp.
                                                                          {
  CXCursor C = {
      CXCursor_PreprocessingDirective,
      0,
      {Range.getBegin().getPtrEncoding(), Range.getEnd().getPtrEncoding(), TU}};
  return C;
}
operator!=()
bool clang::cxcursor::operator!= (CXCursor X, CXCursor Y) [inline]
Definition at line 284 of file CXCursor.h.
{ return !(X == Y); }
operator==()
bool clang::cxcursor::operator== (CXCursor X, CXCursor Y)
Definition at line 1237 of file CXCursor.cpp.
                                                {
  return X.kind == Y.kind && X.data[0] == Y.data[0] && X.data[1] == Y.data[1] &&
         X.data[2] == Y.data[2];
}