clang::cxindex Namespace Reference
Classes
class Logger
class ScratchAlloc
struct EntityInfo
struct ContainerInfo
struct DeclInfo
struct ObjCContainerDeclInfo
struct ObjCInterfaceDeclInfo
struct ObjCProtocolDeclInfo
struct ObjCCategoryDeclInfo
struct ObjCPropertyDeclInfo
struct CXXClassDeclInfo
struct AttrInfo
struct IBOutletCollectionInfo
class AttrListInfo
class CXIndexDataConsumer
Typedefs
typedef IntrusiveRefCntPtr< Logger > LogRef
Functions
void printDiagsToStderr (ASTUnit *Unit)
MacroInfo * getMacroInfo (const IdentifierInfo &II, SourceLocation MacroDefLoc, CXTranslationUnit TU)
const MacroInfo * getMacroInfo (const MacroDefinitionRecord *MacroDef, CXTranslationUnit TU)
Retrieves the corresponding MacroInfo of a MacroDefinitionRecord.
MacroDefinitionRecord * checkForMacroInMacroDefinition (const MacroInfo *MI, SourceLocation Loc, CXTranslationUnit TU)
MacroDefinitionRecord * checkForMacroInMacroDefinition (const MacroInfo *MI, const Token &Tok, CXTranslationUnit TU)
Typedef Documentation
LogRef
typedef IntrusiveRefCntPtr<Logger> clang::cxindex::LogRef
Definition at line 31 of file CLog.h.
Function Documentation
checkForMacroInMacroDefinition() [1/2]
MacroDefinitionRecord * clang::cxindex::checkForMacroInMacroDefinition (const MacroInfo * MI, const Token & Tok, CXTranslationUnit TU)
If Tok resides inside the definition of MI and it points at an identifier that has ever been a macro name, this returns the latest MacroDefinitionRecord for that name, otherwise it returns NULL.
Definition at line 9049 of file CIndex.cpp.
                                                              {
  if (!MI || !TU)
    return nullptr;
  if (Tok.isNot(tok::raw_identifier))
    return nullptr;
  if (MI->getNumTokens() == 0)
    return nullptr;
  SourceRange DefRange(MI->getReplacementToken(0).getLocation(),
                       MI->getDefinitionEndLoc());
  ASTUnit *Unit = cxtu::getASTUnit(TU);
  // Check that the token is inside the definition and not its argument list.
  SourceManager &SM = Unit->getSourceManager();
  if (SM.isBeforeInTranslationUnit(Tok.getLocation(), DefRange.getBegin()))
    return nullptr;
  if (SM.isBeforeInTranslationUnit(DefRange.getEnd(), Tok.getLocation()))
    return nullptr;
  Preprocessor &PP = Unit->getPreprocessor();
  PreprocessingRecord *PPRec = PP.getPreprocessingRecord();
  if (!PPRec)
    return nullptr;
  IdentifierInfo &II = PP.getIdentifierTable().get(Tok.getRawIdentifier());
  if (!II.hadMacroDefinition())
    return nullptr;
  // Check that the identifier is not one of the macro arguments.
  if (std::find(MI->param_begin(), MI->param_end(), &II) != MI->param_end())
    return nullptr;
  MacroDirective *InnerMD = PP.getLocalMacroDirectiveHistory(&II);
  if (!InnerMD)
    return nullptr;
  return PPRec->findMacroDefinition(InnerMD->getMacroInfo());
}
checkForMacroInMacroDefinition() [2/2]
MacroDefinitionRecord * clang::cxindex::checkForMacroInMacroDefinition (const MacroInfo * MI, SourceLocation Loc, CXTranslationUnit TU)
If Loc resides inside the definition of MI and it points at an identifier that has ever been a macro name, this returns the latest MacroDefinitionRecord for that name, otherwise it returns NULL.
Definition at line 9090 of file CIndex.cpp.
                                                              {
  if (Loc.isInvalid() || !MI || !TU)
    return nullptr;
  if (MI->getNumTokens() == 0)
    return nullptr;
  ASTUnit *Unit = cxtu::getASTUnit(TU);
  Preprocessor &PP = Unit->getPreprocessor();
  if (!PP.getPreprocessingRecord())
    return nullptr;
  Loc = Unit->getSourceManager().getSpellingLoc(Loc);
  Token Tok;
  if (PP.getRawToken(Loc, Tok))
    return nullptr;
  return checkForMacroInMacroDefinition(MI, Tok, TU);
}
getMacroInfo() [1/2]
MacroInfo * clang::cxindex::getMacroInfo (const IdentifierInfo & II, SourceLocation MacroDefLoc, CXTranslationUnit TU)
If MacroDefLoc points at a macro definition with II as its name, this retrieves its MacroInfo.
Definition at line 9015 of file CIndex.cpp.
                                                       {
  if (MacroDefLoc.isInvalid() || !TU)
    return nullptr;
  if (!II.hadMacroDefinition())
    return nullptr;
  ASTUnit *Unit = cxtu::getASTUnit(TU);
  Preprocessor &PP = Unit->getPreprocessor();
  MacroDirective *MD = PP.getLocalMacroDirectiveHistory(&II);
  if (MD) {
    for (MacroDirective::DefInfo Def = MD->getDefinition(); Def;
         Def = Def.getPreviousDefinition()) {
      if (MacroDefLoc == Def.getMacroInfo()->getDefinitionLoc())
        return Def.getMacroInfo();
    }
  }
  return nullptr;
}
Referenced by getMacroInfo().
getMacroInfo() [2/2]
const MacroInfo * clang::cxindex::getMacroInfo (const MacroDefinitionRecord * MacroDef, CXTranslationUnit TU)
Retrieves the corresponding MacroInfo of a MacroDefinitionRecord.
Definition at line 9037 of file CIndex.cpp.
                                                             {
  if (!MacroDef || !TU)
    return nullptr;
  const IdentifierInfo *II = MacroDef->getName();
  if (!II)
    return nullptr;
  return getMacroInfo(*II, MacroDef->getLocation(), TU);
}
References getMacroInfo().
printDiagsToStderr()
void clang::cxindex::printDiagsToStderr (ASTUnit * Unit)
Definition at line 8994 of file CIndex.cpp.
                                              {
  if (!Unit)
    return;
  for (ASTUnit::stored_diag_iterator D = Unit->stored_diag_begin(),
                                     DEnd = Unit->stored_diag_end();
       D != DEnd; ++D) {
    CXStoredDiagnostic Diag(*D, Unit->getLangOpts());
    CXString Msg =
        clang_formatDiagnostic(&Diag, clang_defaultDiagnosticDisplayOptions());
    fprintf(stderr, "%s\n", clang_getCString(Msg));
    clang_disposeString(Msg);
  }
#ifdef _WIN32
  // On Windows, force a flush, since there may be multiple copies of
  // stderr and stdout in the file system, all with different buffers
  // but writing to the same device.
  fflush(stderr);
#endif
}
References clang_defaultDiagnosticDisplayOptions(), clang_disposeString(), clang_formatDiagnostic(), and clang_getCString().