clang::cxloc Namespace Reference
Functions
CXSourceRange translateSourceRange (const SourceManager &SM, const LangOptions &LangOpts, const CharSourceRange &R)
CharSourceRange translateCXRangeToCharRange (CXSourceRange R)
Function Documentation
translateCXRangeToCharRange()
CharSourceRange clang::cxloc::translateCXRangeToCharRange (CXSourceRange R)
Translates CXSourceRange to CharSourceRange. The semantics of R are: R.begin_int_data is first character of the range. R.end_int_data is one character past the end of the range.
Definition at line 167 of file CIndex.cpp.
                                                                  {
  return CharSourceRange::getCharRange(
      SourceLocation::getFromRawEncoding(R.begin_int_data),
      SourceLocation::getFromRawEncoding(R.end_int_data));
}
Referenced by clang_CXRewriter_removeText(), and clang_CXRewriter_replaceText().
translateSourceRange()
CXSourceRange clang::cxloc::translateSourceRange (const SourceManager & SM, const LangOptions & LangOpts, const CharSourceRange & R)
Translate a Clang source range into a CIndex source range.
Clang internally represents ranges where the end location points to the start of the token at the end. However, for external clients it is more useful to have a CXSourceRange be a proper half-open interval. This routine does the appropriate translation.
Definition at line 143 of file CIndex.cpp.
                                                                    {
  // We want the last character in this location, so we will adjust the
  // location accordingly.
  SourceLocation EndLoc = R.getEnd();
  bool IsTokenRange = R.isTokenRange();
  if (EndLoc.isValid() && EndLoc.isMacroID() &&
      !SM.isMacroArgExpansion(EndLoc)) {
    CharSourceRange Expansion = SM.getExpansionRange(EndLoc);
    EndLoc = Expansion.getEnd();
    IsTokenRange = Expansion.isTokenRange();
  }
  if (IsTokenRange && EndLoc.isValid()) {
    unsigned Length =
        Lexer::MeasureTokenLength(SM.getSpellingLoc(EndLoc), SM, LangOpts);
    EndLoc = EndLoc.getLocWithOffset(Length);
  }
  CXSourceRange Result = {
      {&SM, &LangOpts}, R.getBegin().getRawEncoding(), EndLoc.getRawEncoding()};
  return Result;
}
Referenced by clang_Cursor_getCommentRange(), clang_Cursor_getSpellingNameRange(), clang_getCompletionFixIt(), clang_getCursorReferenceNameRange(), clang::CXStoredDiagnostic::getFixIt(), and clang::CXStoredDiagnostic::getRange().