tests.unit.test_report Namespace Reference
Classes
class ParseFileTest
class ReportMethodTest
class GetPrefixFromCompilationDatabaseTest
class MergeSarifTest
Functions
def run_bug_parse (content)
def run_crash_parse (content, preproc)
Function Documentation
run_bug_parse()
def tests.unit.test_report.run_bug_parse (content)
Definition at line 14 of file test_report.py.
def run_bug_parse(content):
    with libear.TemporaryDirectory() as tmpdir:
        file_name = os.path.join(tmpdir, 'test.html')
        with open(file_name, 'w') as handle:
            handle.writelines(content)
        for bug in sut.parse_bug_html(file_name):
            return bug
References startfile.open(), and libear.TemporaryDirectory().
Referenced by tests.unit.test_report.ParseFileTest.test_parse_bug(), and tests.unit.test_report.ParseFileTest.test_parse_bug_empty().
run_crash_parse()
def tests.unit.test_report.run_crash_parse (content, preproc)
Definition at line 23 of file test_report.py.
def run_crash_parse(content, preproc):
    with libear.TemporaryDirectory() as tmpdir:
        file_name = os.path.join(tmpdir, preproc + '.info.txt')
        with open(file_name, 'w') as handle:
            handle.writelines(content)
        return sut.parse_crash(file_name)
References startfile.open(), and libear.TemporaryDirectory().
Referenced by tests.unit.test_report.ParseFileTest.test_parse_crash().