clang_fuzzer Namespace Reference
Classes
class InnerLoop
Functions
const std::vector< const char * > & GetCLArgs ()
void HandleCXX (const std::string &S, const char *FileName, const std::vector< const char * > &ExtraArgs)
void HandleLLVM (const std::string &S, const std::vector< const char * > &ExtraArgs)
std::ostream & operator<< (std::ostream &os, const BinaryOp &x)
std::ostream & operator<< (std::ostream &os, const StatementSeq &x)
std::ostream & operator<< (std::ostream &os, const Const &x)
std::ostream & operator<< (std::ostream &os, const VarRef &x)
std::ostream & operator<< (std::ostream &os, const Rvalue &x)
std::ostream & operator<< (std::ostream &os, const AssignmentStatement &x)
std::ostream & operator<< (std::ostream &os, const Statement &x)
void NestedLoopToString (std::ostream &os, const LoopFunction &x)
void SingleLoopToString (std::ostream &os, const LoopFunction &x)
std::ostream & operator<< (std::ostream &os, const LoopFunction &x)
std::string LoopFunctionToString (const LoopFunction &input)
std::string LoopProtoToCxx (const uint8_t *data, size_t size)
std::ostream & operator<< (std::ostream &os, const Lvalue &x)
std::ostream & operator<< (std::ostream &os, const IfElse &x)
std::ostream & operator<< (std::ostream &os, const While &x)
std::ostream & operator<< (std::ostream &os, const Function &x)
std::string FunctionToString (const Function &input)
std::string ProtoToCxx (const uint8_t *data, size_t size)
std::string BinopToString (std::ostream &os, const BinaryOp &x)
std::string StateSeqToString (std::ostream &os, const StatementSeq &x)
std::string ConstToString (const Const &x)
std::string VarRefToString (std::ostream &os, const VarRef &x)
std::string RvalueToString (std::ostream &os, const Rvalue &x)
std::string LoopFunctionToLLVMString (const LoopFunction &input)
std::string LoopProtoToLLVM (const uint8_t *data, size_t size)
Function Documentation
BinopToString()
std::string clang_fuzzer::BinopToString (std::ostream & os, const BinaryOp & x)
Definition at line 87 of file loop_proto_to_llvm.cpp.
                                                           {
  std::string left = RvalueToString(os, x.left());
  std::string right = RvalueToString(os, x.right());
  std::string op;
  switch (x.op()) {
  case BinaryOp::PLUS:
    op = "add";
    break;
  case BinaryOp::MINUS:
    op = "sub";
    break;
  case BinaryOp::MUL:
    op = "mul";
    break;
  case BinaryOp::XOR:
    op = "xor";
    break;
  case BinaryOp::AND:
    op = "and";
    break;
  case BinaryOp::OR:
    op = "or";
    break;
  // Support for Boolean operators will be added later
  case BinaryOp::EQ:
  case BinaryOp::NE:
  case BinaryOp::LE:
  case BinaryOp::GE:
  case BinaryOp::LT:
  case BinaryOp::GT:
    op = "add";
    break;
  }
  std::string val_var = get_var();
  os << val_var << " = " << op << " i32 " << left << ", " << right << "\n";
  return val_var;
}
References RvalueToString().
Referenced by RvalueToString().
ConstToString()
std::string clang_fuzzer::ConstToString (const Const & x)
Definition at line 51 of file loop_proto_to_llvm.cpp.
                                        {
  return std::to_string(x.val());
}
Referenced by RvalueToString().
FunctionToString()
std::string clang_fuzzer::FunctionToString (const Function & input)
Definition at line 88 of file proto_to_cxx.cpp.
                                                  {
  std::ostringstream os;
  os << input;
  return os.str();
}
Referenced by DEFINE_BINARY_PROTO_FUZZER(), and ProtoToCxx().
GetCLArgs()
const std::vector< const char * > & clang_fuzzer::GetCLArgs ()
Definition at line 31 of file fuzzer_initialize.cpp.
                                           {
  return CLArgs;
}
Referenced by DEFINE_BINARY_PROTO_FUZZER().
HandleCXX()
void clang_fuzzer::HandleCXX (const std::string & S, const char * FileName, const std::vector< const char * > & ExtraArgs)
Definition at line 23 of file handle_cxx.cpp.
                                                                       {
  llvm::opt::ArgStringList CC1Args;
  CC1Args.push_back("-cc1");
  for (auto &A : ExtraArgs)
    CC1Args.push_back(A);
  CC1Args.push_back(FileName);
  llvm::IntrusiveRefCntPtr<FileManager> Files(
      new FileManager(FileSystemOptions()));
  IgnoringDiagConsumer Diags;
  IntrusiveRefCntPtr<DiagnosticOptions> DiagOpts = new DiagnosticOptions();
  DiagnosticsEngine Diagnostics(
      IntrusiveRefCntPtr<clang::DiagnosticIDs>(new DiagnosticIDs()), &*DiagOpts,
      &Diags, false);
  std::unique_ptr<clang::CompilerInvocation> Invocation(
      tooling::newInvocation(&Diagnostics, CC1Args, /*BinaryName=*/nullptr));
  std::unique_ptr<llvm::MemoryBuffer> Input =
      llvm::MemoryBuffer::getMemBuffer(S);
  Invocation->getPreprocessorOpts().addRemappedFile(FileName,
                                                    Input.release());
  std::unique_ptr<tooling::ToolAction> action(
      tooling::newFrontendActionFactory<clang::EmitObjAction>());
  std::shared_ptr<PCHContainerOperations> PCHContainerOps =
      std::make_shared<PCHContainerOperations>();
  action->runInvocation(std::move(Invocation), Files.get(), PCHContainerOps,
                        &Diags);
}
Referenced by DEFINE_BINARY_PROTO_FUZZER(), and LLVMFuzzerTestOneInput().
HandleLLVM()
void clang_fuzzer::HandleLLVM (const std::string & S, const std::vector< const char * > & ExtraArgs)
Definition at line 212 of file handle_llvm.cpp.
                                                                        {
  // Populate OptArrays and UnoptArrays with the arrays from InputArrays
  memcpy(OptArrays, InputArrays, kTotalSize);
  memcpy(UnoptArrays, InputArrays, kTotalSize);
  // Parse ExtraArgs to set the optimization level
  CodeGenOpt::Level OLvl;
  getOptLevel(ExtraArgs, OLvl);
  // First we optimize the IR by running a loop vectorizer pass
  std::string OptIR = OptLLVM(IR, OLvl);
  CreateAndRunJITFunc(OptIR, OLvl);
  CreateAndRunJITFunc(IR, CodeGenOpt::None);
  if (memcmp(OptArrays, UnoptArrays, kTotalSize))
    ErrorAndExit("!!!BUG!!!");
  return;
}
Referenced by DEFINE_BINARY_PROTO_FUZZER().
LoopFunctionToLLVMString()
std::string clang_fuzzer::LoopFunctionToLLVMString (const LoopFunction & input)
Definition at line 197 of file loop_proto_to_llvm.cpp.
                                                              {
  std::ostringstream os;
  os << input;
  return os.str();
}
Referenced by DEFINE_BINARY_PROTO_FUZZER(), and LoopProtoToLLVM().
LoopFunctionToString()
std::string clang_fuzzer::LoopFunctionToString (const LoopFunction & input)
Definition at line 147 of file loop_proto_to_cxx.cpp.
                                                          {
  std::ostringstream os;
  os << input;
  return os.str();
}
Referenced by DEFINE_BINARY_PROTO_FUZZER(), and LoopProtoToCxx().
LoopProtoToCxx()
std::string clang_fuzzer::LoopProtoToCxx (const uint8_t * data, size_t size)
Definition at line 152 of file loop_proto_to_cxx.cpp.
                                                           {
  LoopFunction message;
  if (!message.ParsePartialFromArray(data, size))
    return "#error invalid proto\n";
  return LoopFunctionToString(message);
}
References LoopFunctionToString().
Referenced by main().
LoopProtoToLLVM()
std::string clang_fuzzer::LoopProtoToLLVM (const uint8_t * data, size_t size)
Definition at line 202 of file loop_proto_to_llvm.cpp.
                                                            {
  LoopFunction message;
  if (!message.ParsePartialFromArray(data, size))
    return "#error invalid proto\n";
  return LoopFunctionToLLVMString(message);
}
References LoopFunctionToLLVMString().
Referenced by main().
NestedLoopToString()
void clang_fuzzer::NestedLoopToString (std::ostream & os, const LoopFunction & x)
Definition at line 122 of file loop_proto_to_cxx.cpp.
                                                               {
  os << "void foo(int *a, int *b, int *__restrict__ c, size_t s) {\n"
     << "for (int i=0; i<s; i++){\n"
     << "for (int j=0; j<s; j++){\n";
  {
    InnerLoop IL;
    os << x.inner_statements() << "}\n";
  }
  os << x.outer_statements() << "}\n}\n";
}
Referenced by operator<<().
operator<<() [1/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const AssignmentStatement & x)
Definition at line 111 of file loop_proto_to_cxx.cpp.
                                                                     {
  return os << x.varref() << "=" << x.rvalue() << ";\n";
}
operator<<() [2/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const BinaryOp & x)
Definition at line 69 of file loop_proto_to_cxx.cpp.
                                                          {
  os << "(" << x.left();
  switch (x.op()) {
  case BinaryOp::PLUS:
    os << "+";
    break;
  case BinaryOp::MINUS:
    os << "-";
    break;
  case BinaryOp::MUL:
    os << "*";
    break;
  case BinaryOp::XOR:
    os << "^";
    break;
  case BinaryOp::AND:
    os << "&";
    break;
  case BinaryOp::OR:
    os << "|";
    break;
  case BinaryOp::EQ:
    os << "==";
    break;
  case BinaryOp::NE:
    os << "!=";
    break;
  case BinaryOp::LE:
    os << "<=";
    break;
  case BinaryOp::GE:
    os << ">=";
    break;
  case BinaryOp::LT:
    os << "<";
    break;
  case BinaryOp::GT:
    os << ">";
    break;
  }
  return os << x.right() << ")";
}
operator<<() [3/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const Const & x)
Definition at line 46 of file loop_proto_to_cxx.cpp.
                                                       {
  return os << "(" << x.val() << ")";
}
operator<<() [4/12]
std::ostream& clang_fuzzer::operator<< (std::ostream & os, const Function & x)
Definition at line 82 of file proto_to_cxx.cpp.
                                                          {
  return os << "void foo(int *a) {\n" << x.statements() << "}\n";
}
operator<<() [5/12]
std::ostream& clang_fuzzer::operator<< (std::ostream & os, const IfElse & x)
Definition at line 64 of file proto_to_cxx.cpp.
                                                        {
  return os << "if (" << x.cond() << "){\n"
            << x.if_body() << "} else { \n"
            << x.else_body() << "}\n";
}
operator<<() [6/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const LoopFunction & x)
Definition at line 137 of file loop_proto_to_cxx.cpp.
                                                              {
  if (x.has_inner_statements())
    NestedLoopToString(os, x);
  else
    SingleLoopToString(os, x);
  return os;
}
References NestedLoopToString(), and SingleLoopToString().
operator<<() [7/12]
std::ostream& clang_fuzzer::operator<< (std::ostream & os, const Lvalue & x)
Definition at line 32 of file proto_to_cxx.cpp.
                                                        {
  return os << x.varref();
}
operator<<() [8/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const Rvalue & x)
Definition at line 60 of file loop_proto_to_cxx.cpp.
                                                        {
  if (x.has_cons())
    return os << x.cons();
  if (x.has_binop())
    return os << x.binop();
  if (x.has_varref())
    return os << x.varref();
  return os << "1";
}
operator<<() [9/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const Statement & x)
Definition at line 114 of file loop_proto_to_cxx.cpp.
                                                           {
  return os << x.assignment();
}
operator<<() [10/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const StatementSeq & x)
Definition at line 117 of file loop_proto_to_cxx.cpp.
                                                              {
  for (auto &st : x.statements())
    os << st;
  return os;
}
operator<<() [11/12]
std::ostream & clang_fuzzer::operator<< (std::ostream & os, const VarRef & x)
Definition at line 49 of file loop_proto_to_cxx.cpp.
                                                        {
  std::string which_loop = inner_loop ? "j" : "i";
  switch (x.arr()) {
    case VarRef::ARR_A:
      return os << "a[" << which_loop << "]";
    case VarRef::ARR_B:
      return os << "b[" << which_loop << "]";
    case VarRef::ARR_C:
      return os << "c[" << which_loop << "]";
  }
}
operator<<() [12/12]
std::ostream& clang_fuzzer::operator<< (std::ostream & os, const While & x)
Definition at line 69 of file proto_to_cxx.cpp.
                                                       {
  return os << "while (" << x.cond() << "){\n" << x.body() << "}\n";
}
ProtoToCxx()
std::string clang_fuzzer::ProtoToCxx (const uint8_t * data, size_t size)
Definition at line 94 of file proto_to_cxx.cpp.
                                                       {
  Function message;
  if (!message.ParsePartialFromArray(data, size))
    return "#error invalid proto\n";
  return FunctionToString(message);
}
References FunctionToString().
Referenced by main().
RvalueToString()
std::string clang_fuzzer::RvalueToString (std::ostream & os, const Rvalue & x)
Definition at line 73 of file loop_proto_to_llvm.cpp.
                                                          {
  if(x.has_cons())
    return ConstToString(x.cons());
  if(x.has_binop())
    return BinopToString(os, x.binop());
  if(x.has_varref()) {
    std::string var_ref = VarRefToString(os, x.varref());
    std::string val_var = get_var();
    os << val_var << " = load i32, i32* " << var_ref << "\n";
    return val_var;
  }
  return "1";
}
References BinopToString(), ConstToString(), and VarRefToString().
Referenced by BinopToString().
SingleLoopToString()
void clang_fuzzer::SingleLoopToString (std::ostream & os, const LoopFunction & x)
Definition at line 132 of file loop_proto_to_cxx.cpp.
                                                               {
  os << "void foo(int *a, int *b, int *__restrict__ c, size_t s) {\n"
     << "for (int i=0; i<s; i++){\n"
     << x.outer_statements() << "}\n}\n";
}
Referenced by operator<<().
StateSeqToString()
std::string clang_fuzzer::StateSeqToString (std::ostream & os, const StatementSeq & x)
VarRefToString()
std::string clang_fuzzer::VarRefToString (std::ostream & os, const VarRef & x)
Definition at line 54 of file loop_proto_to_llvm.cpp.
                                                          {
  std::string which_loop = inner_loop ? "inner" : "outer";
  std::string arr;
  switch(x.arr()) {
  case VarRef::ARR_A:
    arr = "%a";
    break;
  case VarRef::ARR_B:
    arr = "%b";
    break;
  case VarRef::ARR_C:
    arr = "%c";
    break;
  }
  std::string ptr_var = get_var();
  os << ptr_var << " = getelementptr inbounds i32, i32* " << arr
     << ", i64 %" << which_loop << "_ct\n";
  return ptr_var;
}
Referenced by RvalueToString().