libscanbuild.clang Namespace Reference
Classes
class ClangErrorException
Functions
def get_version (clang)
def get_arguments (command, cwd)
def get_active_checkers (clang, plugins)
def is_active (checkers)
def parse_checkers (stream)
def get_checkers (clang, plugins)
def is_ctu_capable (extdef_map_cmd)
def get_triple_arch (command, cwd)
Variables
ACTIVE_CHECKER_PATTERN = re.compile(r'^-analyzer-checker=(.*)$')
Function Documentation
get_active_checkers()
def libscanbuild.clang.get_active_checkers (clang, plugins)
 Get the active checker list.

:param clang:   the compiler we are using
:param plugins: list of plugins which was requested by the user
:return:        list of checker names which are active

To get the default checkers we execute Clang to print how this
compilation would be called. And take out the enabled checker from the
arguments. For input file we specify stdin and pass only language
information. 
Definition at line 58 of file clang.py.
def get_active_checkers(clang, plugins):
    """ Get the active checker list.
    :param clang: the compiler we are using
    :param plugins: list of plugins which was requested by the user
    :return: list of checker names which are active
    To get the default checkers we execute Clang to print how this
    compilation would be called. And take out the enabled checker from the
    arguments. For input file we specify stdin and pass only language
    information. """
    def get_active_checkers_for(language):
        """ Returns a list of active checkers for the given language. """
        load_args = [arg
                     for plugin in plugins
                     for arg in ['-Xclang', '-load', '-Xclang', plugin]]
        cmd = [clang, '--analyze'] + load_args + ['-x', language, '-']
        return [ACTIVE_CHECKER_PATTERN.match(arg).group(1)
                for arg in get_arguments(cmd, '.')
                if ACTIVE_CHECKER_PATTERN.match(arg)]
    result = set()
    for language in ['c', 'c++', 'objective-c', 'objective-c++']:
        result.update(get_active_checkers_for(language))
    return frozenset(result)
References libscanbuild.clang.get_arguments().
Referenced by libscanbuild.clang.get_checkers().
get_arguments()
def libscanbuild.clang.get_arguments (command, cwd)
 Capture Clang invocation.

:param command: the compilation command
:param cwd:     the current working directory
:return:        the detailed front-end invocation command 
Definition at line 38 of file clang.py.
def get_arguments(command, cwd):
    """ Capture Clang invocation.
    :param command: the compilation command
    :param cwd: the current working directory
    :return: the detailed front-end invocation command """
    cmd = command[:]
    cmd.insert(1, '-###')
    cmd.append('-fno-color-diagnostics')
    output = run_command(cmd, cwd=cwd)
    # The relevant information is in the last line of the output.
    # Don't check if finding last line fails, would throw exception anyway.
    last_line = output[-1]
    if re.search(r'clang(.*): error:', last_line):
        raise ClangErrorException(last_line)
    return decode(last_line)
References libscanbuild.shell.decode(), and libscanbuild.run_command().
Referenced by libscanbuild.clang.get_active_checkers(), libscanbuild.clang.get_triple_arch(), libscanbuild.analyze.report_failure(), and libscanbuild.analyze.run_analyzer().
get_checkers()
def libscanbuild.clang.get_checkers (clang, plugins)
 Get all the available checkers from default and from the plugins.

:param clang:   the compiler we are using
:param plugins: list of plugins which was requested by the user
:return:        a dictionary of all available checkers and its status

{<checker name>: (<checker description>, <is active by default>)} 
Definition at line 138 of file clang.py.
def get_checkers(clang, plugins):
    """ Get all the available checkers from default and from the plugins.
    :param clang: the compiler we are using
    :param plugins: list of plugins which was requested by the user
    :return: a dictionary of all available checkers and its status
    {<checker name>: (<checker description>, <is active by default>)} """
    load = [elem for plugin in plugins for elem in ['-load', plugin]]
    cmd = [clang, '-cc1'] + load + ['-analyzer-checker-help']
    lines = run_command(cmd)
    is_active_checker = is_active(get_active_checkers(clang, plugins))
    checkers = {
        name: (description, is_active_checker(name))
        for name, description in parse_checkers(lines)
    }
    if not checkers:
        raise Exception('Could not query Clang for available checkers.')
    return checkers
References libscanbuild.clang.get_active_checkers(), libscanbuild.clang.is_active(), libscanbuild.clang.parse_checkers(), and libscanbuild.run_command().
Referenced by libscanbuild.arguments.validate_args_for_analyze().
get_triple_arch()
def libscanbuild.clang.get_triple_arch (command, cwd)
Returns the architecture part of the target triple for the given
compilation command. 
Definition at line 175 of file clang.py.
def get_triple_arch(command, cwd):
    """Returns the architecture part of the target triple for the given
    compilation command. """
    cmd = get_arguments(command, cwd)
    try:
        separator = cmd.index("-triple")
        return cmd[separator + 1]
    except (IndexError, ValueError):
        return ""
References libscanbuild.clang.get_arguments().
Referenced by libscanbuild.analyze.ctu_collect_phase(), and libscanbuild.analyze.dispatch_ctu().
get_version()
def libscanbuild.clang.get_version (clang)
 Returns the compiler version as string.

:param clang:   the compiler we are using
:return:        the version string printed to stderr 
Definition at line 27 of file clang.py.
def get_version(clang):
    """ Returns the compiler version as string.
    :param clang: the compiler we are using
    :return: the version string printed to stderr """
    output = run_command([clang, '-v'])
    # the relevant version info is in the first line
    return output[0]
References libscanbuild.run_command().
Referenced by libscanbuild.report.assemble_cover(), and libscanbuild.analyze.report_failure().
is_active()
def libscanbuild.clang.is_active (checkers)
 Returns a method, which classifies the checker active or not,
based on the received checker name list. 
Definition at line 87 of file clang.py.
def is_active(checkers):
    """ Returns a method, which classifies the checker active or not,
    based on the received checker name list. """
    def predicate(checker):
        """ Returns True if the given checker is active. """
        return any(pattern.match(checker) for pattern in predicate.patterns)
    predicate.patterns = [re.compile(r'^' + a + r'(\.|$)') for a in checkers]
    return predicate
Referenced by libscanbuild.clang.get_checkers().
is_ctu_capable()
def libscanbuild.clang.is_ctu_capable (extdef_map_cmd)
 Detects if the current (or given) clang and external definition mapping
executables are CTU compatible. 
Definition at line 164 of file clang.py.
def is_ctu_capable(extdef_map_cmd):
    """ Detects if the current (or given) clang and external definition mapping
    executables are CTU compatible. """
    try:
        run_command([extdef_map_cmd, '-version'])
    except (OSError, subprocess.CalledProcessError):
        return False
    return True
References libscanbuild.run_command().
Referenced by libscanbuild.arguments.validate_args_for_analyze().
parse_checkers()
def libscanbuild.clang.parse_checkers (stream)
 Parse clang -analyzer-checker-help output.

Below the line 'CHECKERS:' are there the name description pairs.
Many of them are in one line, but some long named checker has the
name and the description in separate lines.

The checker name is always prefixed with two space character. The
name contains no whitespaces. Then followed by newline (if it's
too long) or other space characters comes the description of the
checker. The description ends with a newline character.

:param stream:  list of lines to parse
:return:        generator of tuples

(<checker name>, <checker description>) 
Definition at line 100 of file clang.py.
def parse_checkers(stream):
    """ Parse clang -analyzer-checker-help output.
    Below the line 'CHECKERS:' are there the name description pairs.
    Many of them are in one line, but some long named checker has the
    name and the description in separate lines.
    The checker name is always prefixed with two space character. The
    name contains no whitespaces. Then followed by newline (if it's
    too long) or other space characters comes the description of the
    checker. The description ends with a newline character.
    :param stream: list of lines to parse
    :return: generator of tuples
    (<checker name>, <checker description>) """
    lines = iter(stream)
    # find checkers header
    for line in lines:
        if re.match(r'^CHECKERS:', line):
            break
    # find entries
    state = None
    for line in lines:
        if state and not re.match(r'^\s\s\S', line):
            yield (state, line.strip())
            state = None
        elif re.match(r'^\s\s\S+$', line.rstrip()):
            state = line.strip()
        else:
            pattern = re.compile(r'^\s\s(?P<key>\S*)\s*(?P<value>.*)')
            match = pattern.match(line.rstrip())
            if match:
                current = match.groupdict()
                yield (current['key'], current['value'])
Referenced by libscanbuild.clang.get_checkers().
Variable Documentation
ACTIVE_CHECKER_PATTERN
libscanbuild.clang.ACTIVE_CHECKER_PATTERN = re.compile(r'^-analyzer-checker=(.*)$')
Definition at line 19 of file clang.py.