hlibhelp Namespace Reference
Functions
string getUnit (std::chrono::duration< double, std::nano > duration)
string getUsageAsString (double usage)
double convertToSpecifiedUnit (std::chrono::duration< double, std::nano > duration, string prefix)
void printTableRow (string identifier, string stmtClass, double duration, string unit, string scopeUsage, string totalUsage, string calls)
void printTableSeparator (int width, char separator, string escape)
void printTableSeparator (int width, string separator, string position, string escape)
void printStatisticBanner ()
string * getSegmentsOfString (string identifier)
Function Documentation
convertToSpecifiedUnit()
double hlibhelp::convertToSpecifiedUnit (std::chrono::duration< double, std::nano > duration, string prefix)
Definition at line 43 of file Helper.cpp.
                                                                                                {
        if (prefix == "s") {
            return duration.count() / 1000000000;
        }
        if (prefix == "ms") {
            return duration.count() / 1000000;
        }
        return duration.count() / 1000;
    }
Referenced by DataStorage::print().
getSegmentsOfString()
string* hlibhelp::getSegmentsOfString (string identifier)
Definition at line 146 of file Helper.cpp.
                                                     {
        std::stringstream identifierStream(identifier);
        string identifierSegment;
        string *segments = new string[2];
        int segmentCounter = 0;
        while (std::getline(identifierStream, identifierSegment, ' ')) {
            segments[ segmentCounter++ ] = identifierSegment;
        }
        return segments;
    }
Referenced by DataStorage::print().
getUnit()
string hlibhelp::getUnit (std::chrono::duration< double, std::nano > duration)
Definition at line 12 of file Helper.cpp.
                                                                  {
        cout << "\n" << duration.count();
        if (duration.count() > 60000000000) {
            return " s";
        }
        if (duration.count() > 1000000000) {
            return "ms";
        }
        return "µs";
    }
Referenced by DataStorage::print().
getUsageAsString()
string hlibhelp::getUsageAsString (double usage)
Definition at line 26 of file Helper.cpp.
                                            {
        std::ostringstream customPrecision;
        if (usage < 0.01) {
            customPrecision << "< 0.01";
        } else if (usage > 99.99) {
            customPrecision << "> 99.99";
        } else {
            customPrecision << std::fixed;
            customPrecision << std::setprecision(2);
            customPrecision << usage;
        }
        return customPrecision.str();
    }
Referenced by DataStorage::print().
printStatisticBanner()
void hlibhelp::printStatisticBanner ()
Definition at line 138 of file Helper.cpp.
                                 {
        cout << "\n\n";
        printTableSeparator(108, '=', "\n");
        cout << setw(60) << setfill(' ') << "Statistic\n";
        printTableSeparator(109, '=', "\n\n");
    }
References printTableSeparator().
Referenced by DataStorage::print().
printTableRow()
void hlibhelp::printTableRow (string identifier, string stmtClass, double duration, string unit, string scopeUsage, string totalUsage, string calls)
Definition at line 56 of file Helper.cpp.
                                                          {
        string percentChar = " %";
        string separatorChar = " │ ";
        string hagnToolSeparatorChar = " │ ";
        if (identifier == "Runtime" || identifier == "Scope") {
            percentChar = "";
            separatorChar = " ";
            hagnToolSeparatorChar = " ";
        }
        if (identifier == "Hagn-Tool") {
            hagnToolSeparatorChar = " ";
        }
        std::ostringstream durationCustomPrecision;
        if (duration < 0.001) {
            durationCustomPrecision << "< 0.001";
        } else {
            durationCustomPrecision << std::fixed;
            durationCustomPrecision << std::setprecision(3);
            durationCustomPrecision << duration;
        }
        std::cout << setfill(' ') << "│ "
                  << std::setw(15) << std::left << identifier << hagnToolSeparatorChar
                  << std::setw(25) << std::left << stmtClass << separatorChar;
        if (identifier == "ID") {
            std::cout << std::right << std::setw(19) << "Runtime";
        } else {
            std::cout << std::right << std::setw(15) << durationCustomPrecision.str() << " " << unit;
        }
        std::cout
                << std::setw(5) << separatorChar
                << std::right << std::setw(10) << std::setprecision(2) << scopeUsage + percentChar
                << std::setw(5) << separatorChar
                << std::right << std::setw(10) << std::setprecision(2) << totalUsage + percentChar
                << std::setw(5) << separatorChar
                << std::right << std::setw(6) << std::setprecision(0) << calls
                << std::setw(5) << " │" << "\n";
    }
Referenced by DataStorage::print().
printTableSeparator() [1/2]
void hlibhelp::printTableSeparator (int width, char separator, string escape)
Definition at line 110 of file Helper.cpp.
                                                                         {
        cout << setw(width) << setfill(separator) << escape;
    }
References libscanbuild.report::escape().
Referenced by DataStorage::print(), and printStatisticBanner().
printTableSeparator() [2/2]
void hlibhelp::printTableSeparator (int width, string separator, string position, string escape)
Definition at line 115 of file Helper.cpp.
                                                                                            {
        string leftSeparator = "├";
        string rightSeparator = "┤";
        if (position == "top") {
            leftSeparator = "┌";
            rightSeparator = "┐";
        }
        if (position == "bottom") {
            leftSeparator = "└";
            rightSeparator = "┘";
        }
        cout << leftSeparator;
        for (int i = 0; i <= width; i++) {
            cout << separator;
        }
        cout << rightSeparator << escape;
    }
References libscanbuild.report::escape().