clang::cxstring Namespace Reference
Classes
class CXStringPool
A string pool used for fast allocation/deallocation of strings.
struct CXStringBuf
Functions
CXString createEmpty ()
Create a CXString object for an empty `` string.
CXString createNull ()
CXString createRef (const char *String)
CXString createDup (const char *String)
CXString createRef (StringRef String)
CXString createDup (StringRef String)
CXString createCXString (CXStringBuf *buf)
Create a CXString object that is backed by a string buffer.
CXStringSet * createSet (const std::vector< std::string > &Strings)
CXStringBuf * getCXStringBuf (CXTranslationUnit TU)
bool isManagedByPool (CXString str)
Returns true if the CXString data is managed by a pool.
CXString createRef (std::string String)=delete
Function Documentation
createCXString()
CXString clang::cxstring::createCXString (CXStringBuf * buf)
Create a CXString object that is backed by a string buffer.
Definition at line 106 of file CXString.cpp.
                                          {
  CXString Str;
  Str.data = buf;
  Str.private_flags = (unsigned) CXS_StringBuf;
  return Str;
}
References CXS_StringBuf.
createDup() [1/2]
CXString clang::cxstring::createDup (const char * String)
Create a CXString object from a nul-terminated C string. New CXString will contain a copy of String.
String can be changed or freed by the caller.
Definition at line 67 of file CXString.cpp.
                                       {
  if (!String)
    return createNull();
  if (String[0] == '\0')
    return createEmpty();
  CXString Str;
  Str.data = strdup(String);
  Str.private_flags = CXS_Malloc;
  return Str;
}
References createEmpty(), createNull(), and CXS_Malloc.
Referenced by clang_constructUSR_ObjCCategory(), clang_constructUSR_ObjCClass(), clang_constructUSR_ObjCProtocol(), clang_Cursor_getMangling(), clang_Cursor_getObjCPropertyGetterName(), clang_Cursor_getObjCPropertySetterName(), clang_Cursor_isExternalSymbol(), clang_getClangVersion(), clang_getCursorDisplayName(), clang_getCursorPrettyPrinted(), clang_getCursorSpelling(), clang_getDeclObjCTypeEncoding(), clang_getTokenSpelling(), clang_Module_getFullName(), clang_Module_getName(), clang_remap_getFilenames(), createRef(), createSet(), clang::CXLoadedDiagnostic::getCategoryText(), clang::CXStoredDiagnostic::getDiagnosticOption(), clang::CXLoadedDiagnostic::getDiagnosticOption(), and clang::CXStoredDiagnostic::getFixIt().
createDup() [2/2]
CXString clang::cxstring::createDup (StringRef String)
Create a CXString object from a StringRef. New CXString will contain a copy of String.
String can be changed or freed by the caller.
Definition at line 96 of file CXString.cpp.
                                     {
  CXString Result;
  char *Spelling = static_cast<char *>(llvm::safe_malloc(String.size() + 1));
  memmove(Spelling, String.data(), String.size());
  Spelling[String.size()] = 0;
  Result.data = Spelling;
  Result.private_flags = (unsigned) CXS_Malloc;
  return Result;
}
References CXS_Malloc.
createEmpty()
CXString clang::cxstring::createEmpty ()
Create a CXString object for an empty `` string.
Definition at line 43 of file CXString.cpp.
                       {
  CXString Str;
  Str.data = "";
  Str.private_flags = CXS_Unmanaged;
  return Str;
}
References CXS_Unmanaged.
Referenced by clang_Cursor_getMangling(), clang_getCompletionChunkText(), clang_getCursorDisplayName(), clang_getCursorPlatformAvailability(), clang_getCursorPrettyPrinted(), clang_getCursorSpelling(), clang_getCursorUSR(), clang_getDeclObjCTypeEncoding(), clang_getDiagnosticCategoryText(), clang_getDiagnosticFixIt(), clang_getDiagnosticOption(), clang_getDiagnosticSpelling(), clang_Module_getFullName(), clang_Module_getName(), clang_TargetInfo_getTriple(), createDup(), createRef(), clang::CXStoredDiagnostic::getDiagnosticOption(), and clang::CXLoadedDiagnostic::getDiagnosticOption().
createNull()
CXString clang::cxstring::createNull ()
Create a CXString object for an NULL string.
A NULL string should be used as an `invalid` value in case of errors.
Definition at line 50 of file CXString.cpp.
                      {
  CXString Str;
  Str.data = nullptr;
  Str.private_flags = CXS_Unmanaged;
  return Str;
}
References CXS_Unmanaged.
Referenced by clang_BlockCommandComment_getArgText(), clang_BlockCommandComment_getCommandName(), clang_CompileCommand_getArg(), clang_CompileCommand_getDirectory(), clang_CompileCommand_getFilename(), clang_CompileCommand_getMappedSourceContent(), clang_CompileCommand_getMappedSourcePath(), clang_Cursor_getBriefCommentText(), clang_Cursor_getObjCPropertyGetterName(), clang_Cursor_getObjCPropertySetterName(), clang_Cursor_getRawCommentText(), clang_File_tryGetRealPathName(), clang_FullComment_getAsHTML(), clang_FullComment_getAsXML(), clang_getCompletionAnnotation(), clang_getCompletionBriefComment(), clang_getCompletionChunkText(), clang_getCompletionFixIt(), clang_getCompletionParent(), clang_getFileName(), clang_HTMLStartTag_getAttrName(), clang_HTMLStartTag_getAttrValue(), clang_HTMLTagComment_getAsString(), clang_HTMLTagComment_getTagName(), clang_InlineCommandComment_getArgText(), clang_InlineCommandComment_getCommandName(), clang_ParamCommandComment_getParamName(), clang_TextComment_getText(), clang_TParamCommandComment_getParamName(), clang_VerbatimBlockLineComment_getText(), clang_VerbatimLineComment_getText(), and createDup().
createRef() [1/3]
CXString clang::cxstring::createRef (const char * String)
Create a CXString object from a nul-terminated C string. New CXString may contain a pointer to String.
String should not be changed by the caller afterwards.
Definition at line 57 of file CXString.cpp.
                                       {
  if (String && String[0] == '\0')
    return createEmpty();
  CXString Str;
  Str.data = String;
  Str.private_flags = CXS_Unmanaged;
  return Str;
}
References createEmpty(), and CXS_Unmanaged.
Referenced by clang_BlockCommandComment_getArgText(), clang_CompileCommand_getArg(), clang_CompileCommand_getDirectory(), clang_CompileCommand_getFilename(), clang_Cursor_getBriefCommentText(), clang_Cursor_getRawCommentText(), clang_File_tryGetRealPathName(), clang_getCompletionAnnotation(), clang_getCompletionBriefComment(), clang_getCompletionChunkText(), clang_getCompletionFixIt(), clang_getCompletionParent(), clang_getCursorKindSpelling(), clang_getCursorSpelling(), clang_getDeclObjCTypeEncoding(), clang_getDiagnosticCategoryName(), clang_getFileName(), clang_getTokenSpelling(), clang_getTypeKindSpelling(), clang_HTMLStartTag_getAttrName(), clang_HTMLStartTag_getAttrValue(), clang_HTMLTagComment_getTagName(), clang_InlineCommandComment_getArgText(), clang_ParamCommandComment_getParamName(), clang_TextComment_getText(), clang_TParamCommandComment_getParamName(), clang_VerbatimBlockLineComment_getText(), clang_VerbatimLineComment_getText(), clang::CXStoredDiagnostic::getCategoryText(), clang::CXStoredDiagnostic::getDiagnosticOption(), clang::CXLoadedDiagnostic::getFixIt(), clang::CXStoredDiagnostic::getSpelling(), and clang::CXLoadedDiagnostic::getSpelling().
createRef() [2/3]
CXString clang::cxstring::createRef (std::string String) [delete]
createRef() [3/3]
CXString clang::cxstring::createRef (StringRef String)
Create a CXString object from a StringRef. New CXString may contain a pointer to the undrelying data of String.
String should not be changed by the caller afterwards.
Definition at line 80 of file CXString.cpp.
                                     {
  // If the string is not nul-terminated, we have to make a copy.
  // FIXME: This is doing a one past end read, and should be removed! For memory
  // we don't manage, the API string can become unterminated at any time outside
  // our control.
  if (!String.empty() && String.data()[String.size()] != 0)
    return createDup(String);
  CXString Result;
  Result.data = String.data();
  Result.private_flags = (unsigned) CXS_Unmanaged;
  return Result;
}
References createDup(), and CXS_Unmanaged.
createSet()
CXStringSet * clang::cxstring::createSet (const std::vector< std::string > & Strings)
Definition at line 113 of file CXString.cpp.
                                                            {
  CXStringSet *Set = new CXStringSet;
  Set->Count = Strings.size();
  Set->Strings = new CXString[Set->Count];
  for (unsigned SI = 0, SE = Set->Count; SI < SE; ++SI)
    Set->Strings[SI] = createDup(Strings[SI]);
  return Set;
}
References createDup().
Referenced by clang_Cursor_getCXXManglings(), and clang_Cursor_getObjCManglings().
getCXStringBuf()
CXStringBuf * clang::cxstring::getCXStringBuf (CXTranslationUnit TU)
Definition at line 144 of file CXString.cpp.
                                                  {
  return TU->StringPool->getCXStringBuf(TU);
}
Referenced by clang_getCursorUSR().
isManagedByPool()
bool clang::cxstring::isManagedByPool (CXString str)
Returns true if the CXString data is managed by a pool.
Definition at line 152 of file CXString.cpp.
                                   {
  return ((CXStringFlag) str.private_flags) == CXS_StringBuf;
}
References CXS_StringBuf.