diagtool Namespace Reference
Classes
struct DiagnosticRecord
struct GroupRecord
class DiagTool
class DiagTools
class RegisterDiagTool
Functions
llvm::ArrayRef< DiagnosticRecord > getBuiltinDiagnosticsByName ()
Get every diagnostic in the system, sorted by name.
const DiagnosticRecord & getDiagnosticForID (short DiagID)
Get a diagnostic by its ID.
llvm::ArrayRef< GroupRecord > getDiagnosticGroups ()
Get every diagnostic group in the system, sorted by name.
Variables
llvm::ManagedStatic< DiagTools > diagTools
Function Documentation
getBuiltinDiagnosticsByName()
llvm::ArrayRef< DiagnosticRecord > diagtool::getBuiltinDiagnosticsByName ()
Get every diagnostic in the system, sorted by name.
Definition at line 22 of file DiagnosticNames.cpp.
                                                                     {
  return llvm::makeArrayRef(BuiltinDiagnosticsByName);
}
getDiagnosticForID()
const DiagnosticRecord & diagtool::getDiagnosticForID (short DiagID)
Get a diagnostic by its ID.
Definition at line 53 of file DiagnosticNames.cpp.
                                                                 {
  DiagnosticRecord Key = {nullptr, DiagID, 0};
  const DiagnosticRecord *Result =
      llvm::lower_bound(BuiltinDiagnosticsByID, Key, orderByID);
  assert(Result && "diagnostic not found; table may be out of date");
  return *Result;
}
getDiagnosticGroups()
llvm::ArrayRef< GroupRecord > diagtool::getDiagnosticGroups ()
Get every diagnostic group in the system, sorted by name.
Definition at line 104 of file DiagnosticNames.cpp.
                                                        {
  return llvm::makeArrayRef(OptionTable);
}
Referenced by diagtool::GroupRecord::group_iterator< RecordType >::operator*(), TreePrinter::showAll(), and TreePrinter::showGroup().
Variable Documentation
diagTools
llvm::ManagedStatic< DiagTools > diagtool::diagTools
Definition at line 64 of file DiagTool.cpp.
Referenced by main(), and diagtool::RegisterDiagTool< DIAGTOOL >::RegisterDiagTool().