Tests/output_program.cpp File Reference
#include <iostream>
#include `../lib/DataStorage.cpp`
Functions
DataStorage dataStorage (`Runtime,Scope,CustomCompoundStmt InterID2,ForStmt 2086992,CallExpr 2087015,CustomCompoundStmt InterID6`)
void fibonacci ()
int main (void)
Function Documentation
dataStorage()
DataStorage dataStorage (` Runtime, Scope , CustomCompoundStmt InterID2, ForStmt 2086992, CallExpr 2087015, CustomCompoundStmt InterID6`)
Referenced by main().
fibonacci()
void fibonacci ()
Definition at line 3 of file output_program.cpp.
                                                                                                                                                   {
    double n, t1 = 0, t2 = 1, nextTerm = 0;
    n = 100;
    std::cout << "Fibonacci Series: ";
    for (int i = 1; i <= n; ++i) {
        if(i == 1) {
            std::cout << t1 << ", ";
            continue;
        }
        if(i == 2) {
            std::cout << t2 << ", ";
            continue;
        }
        nextTerm = t1 + t2;
        t1 = t2;
        t2 = nextTerm;
        std::cout << nextTerm << ", ";
    }
}
Referenced by main().
main()
int main (void)
Definition at line 26 of file output_program.cpp.
               {
dataStorage.startEvent(0);
    dataStorage.startEvent(2);
int i = 10;
    double e = 54783498;
    double d = 54783498;
    double c = 54783498;
    double x = e+d+c;
    double z = x*2;
    double zy = x*2;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    zy++;
    e = z;
    i++;
    dataStorage.endEvent(2);
dataStorage.startEvent(3);
for (int j = 0; j < 1000000; ++j) {
        i++;
        i++;
        i++;
        i++;
        i++;
    }
dataStorage.endEvent(3);
    dataStorage.startEvent(4);
fibonacci();
dataStorage.endEvent(4);
    dataStorage.startEvent(5);
double cc = 54783498;
    double xx = e+d+c;
    double zz = x*2;
    cc++;
    xx++;
    zz++;
    zy++;
dataStorage.endEvent(5);
    dataStorage.endEvent(0);
dataStorage.print();return 0;
}
References dataStorage(), DataStorage::endEvent(), fibonacci(), DataStorage::print(), and DataStorage::startEvent().