diagtool::DiagnosticRecord Struct Reference
#include <DiagnosticNames.h>
Public Member Functions
llvm::StringRef getName () const
bool operator< (const DiagnosticRecord &Other) const
Public Attributes
const char * NameStr
short DiagID
uint8_t NameLen
Detailed Description
Definition at line 18 of file DiagnosticNames.h.
Member Function Documentation
getName()
llvm::StringRef diagtool::DiagnosticRecord::getName () const [inline]
Definition at line 23 of file DiagnosticNames.h.
                                  {
      return llvm::StringRef(NameStr, NameLen);
    }
References NameLen, and NameStr.
Referenced by Reporter.TextParameter::getHTML(), Reporter.SelectionParameter::getHTML(), Reporter.ReporterParameter::getValue(), and operator<().
operator<()
bool diagtool::DiagnosticRecord::operator< (const DiagnosticRecord & Other) const [inline]
Definition at line 27 of file DiagnosticNames.h.
                                                        {
      return getName() < Other.getName();
    }
References getName().
Member Data Documentation
DiagID
short diagtool::DiagnosticRecord::DiagID
Definition at line 20 of file DiagnosticNames.h.
NameLen
uint8_t diagtool::DiagnosticRecord::NameLen
Definition at line 21 of file DiagnosticNames.h.
Referenced by getName().
NameStr
const char* diagtool::DiagnosticRecord::NameStr
Definition at line 19 of file DiagnosticNames.h.
Referenced by getName().
The documentation for this struct was generated from the following file:
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.h