clang::CXStoredDiagnostic Struct Reference
The storage behind a CXDiagnostic.
#include <CIndexDiagnostic.h>
Public Types
enum Kind { StoredDiagnosticKind
, LoadedDiagnosticKind
, CustomNoteDiagnosticKind
 }
Public Member Functions
CXStoredDiagnostic (const StoredDiagnostic &Diag, const LangOptions &LangOpts)
~CXStoredDiagnostic () override
CXDiagnosticSeverity getSeverity () const override
Return the severity of the diagnostic.
CXSourceLocation getLocation () const override
Return the location of the diagnostic.
CXString getSpelling () const override
Return the spelling of the diagnostic.
CXString getDiagnosticOption (CXString *Disable) const override
Return the text for the diagnostic option.
unsigned getCategory () const override
Return the category of the diagnostic.
CXString getCategoryText () const override
Return the category string of the diagnostic.
unsigned getNumRanges () const override
Return the number of source ranges for the diagnostic.
CXSourceRange getRange (unsigned Range) const override
Return the source ranges for the diagnostic.
unsigned getNumFixIts () const override
Return the number of FixIts.
CXString getFixIt (unsigned FixIt, CXSourceRange *ReplacementRange) const override
Return the FixIt information (source range and inserted text).
Kind getKind () const
CXDiagnosticSetImpl & getChildDiagnostics ()
Static Public Member Functions
static bool classof (const CXDiagnosticImpl *D)
Public Attributes
const StoredDiagnostic & Diag
const LangOptions & LangOpts
Protected Member Functions
void append (std::unique_ptr< CXDiagnosticImpl > D)
Protected Attributes
CXDiagnosticSetImpl ChildDiags
Detailed Description
The storage behind a CXDiagnostic.
Definition at line 111 of file CIndexDiagnostic.h.
Member Enumeration Documentation
Kind
enum clang::CXDiagnosticImpl::Kind [inherited]
Enumerator
StoredDiagnosticKind
LoadedDiagnosticKind
CustomNoteDiagnosticKind
Definition at line 56 of file CIndexDiagnostic.h.
            { StoredDiagnosticKind, LoadedDiagnosticKind,
              CustomNoteDiagnosticKind };
Constructor & Destructor Documentation
CXStoredDiagnostic()
clang::CXStoredDiagnostic::CXStoredDiagnostic (const StoredDiagnostic & Diag, const LangOptions & LangOpts) [inline]
Definition at line 115 of file CIndexDiagnostic.h.
    : CXDiagnosticImpl(StoredDiagnosticKind),
      Diag(Diag), LangOpts(LangOpts) { }
 CXStoredDiagnostic()
clang::CXStoredDiagnostic::~CXStoredDiagnostic () [inline], [override]
Definition at line 120 of file CIndexDiagnostic.h.
{}
Member Function Documentation
append()
void clang::CXDiagnosticImpl::append (std::unique_ptr< CXDiagnosticImpl > D) [inline], [protected], [inherited]
Definition at line 102 of file CIndexDiagnostic.h.
                                                 {
    ChildDiags.appendDiagnostic(std::move(D));
  }
References clang::CXDiagnosticSetImpl::appendDiagnostic(), and clang::CXDiagnosticImpl::ChildDiags.
classof()
static bool clang::CXStoredDiagnostic::classof (const CXDiagnosticImpl * D) [inline], [static]
Definition at line 153 of file CIndexDiagnostic.h.
                                                 {
    return D->getKind() == StoredDiagnosticKind;
  }
References clang::CXDiagnosticImpl::getKind(), and clang::CXDiagnosticImpl::StoredDiagnosticKind.
getCategory()
unsigned CXStoredDiagnostic::getCategory () const [override], [virtual]
Return the category of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 70 of file CXStoredDiagnostic.cpp.
                                               {
  return DiagnosticIDs::getCategoryNumberForDiag(Diag.getID());
}
getCategoryText()
CXString CXStoredDiagnostic::getCategoryText () const [override], [virtual]
Return the category string of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 74 of file CXStoredDiagnostic.cpp.
                                                   {
  unsigned catID = DiagnosticIDs::getCategoryNumberForDiag(Diag.getID());
  return cxstring::createRef(DiagnosticIDs::getCategoryNameFromID(catID));
}
References clang::cxstring::createRef().
getChildDiagnostics()
CXDiagnosticSetImpl& clang::CXDiagnosticImpl::getChildDiagnostics () [inline], [inherited]
Definition at line 94 of file CIndexDiagnostic.h.
                                             {
    return ChildDiags;
  }
References clang::CXDiagnosticImpl::ChildDiags.
getDiagnosticOption()
CXString CXStoredDiagnostic::getDiagnosticOption (CXString * Disable) const [override], [virtual]
Return the text for the diagnostic option.
Implements clang::CXDiagnosticImpl.
Definition at line 52 of file CXStoredDiagnostic.cpp.
                                                                        {
  unsigned ID = Diag.getID();
  StringRef Option = DiagnosticIDs::getWarningOptionForDiag(ID);
  if (!Option.empty()) {
    if (Disable)
      *Disable = cxstring::createDup((Twine("-Wno-") + Option).str());
    return cxstring::createDup((Twine("-W") + Option).str());
  }
  
  if (ID == diag::fatal_too_many_errors) {
    if (Disable)
      *Disable = cxstring::createRef("-ferror-limit=0");
    return cxstring::createRef("-ferror-limit=");
  }
  return cxstring::createEmpty();
}
References clang::cxstring::createDup(), clang::cxstring::createEmpty(), and clang::cxstring::createRef().
getFixIt()
CXString CXStoredDiagnostic::getFixIt (unsigned FixIt, CXSourceRange * ReplacementRange) const [override], [virtual]
Return the FixIt information (source range and inserted text).
Implements clang::CXDiagnosticImpl.
Definition at line 99 of file CXStoredDiagnostic.cpp.
                                                                             {
  const FixItHint &Hint = Diag.fixit_begin()[FixIt];
  if (ReplacementRange) {
    // Create a range that covers the entire replacement (or
    // removal) range, adjusting the end of the range to point to
    // the end of the token.
    *ReplacementRange = translateSourceRange(Diag.getLocation().getManager(),
                                             LangOpts, Hint.RemoveRange);
  }
  return cxstring::createDup(Hint.CodeToInsert);
}
References clang::cxstring::createDup(), and clang::cxloc::translateSourceRange().
getKind()
Kind clang::CXDiagnosticImpl::getKind () const [inline], [inherited]
Definition at line 92 of file CIndexDiagnostic.h.
{ return K; }
Referenced by classof(), and clang::CXLoadedDiagnostic::classof().
getLocation()
CXSourceLocation CXStoredDiagnostic::getLocation () const [override], [virtual]
Return the location of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 40 of file CXStoredDiagnostic.cpp.
                                                       {
  if (Diag.getLocation().isInvalid())
    return clang_getNullLocation();
  
  return translateSourceLocation(Diag.getLocation().getManager(),
                                 LangOpts, Diag.getLocation());
}
References clang_getNullLocation().
getNumFixIts()
unsigned CXStoredDiagnostic::getNumFixIts () const [override], [virtual]
Return the number of FixIts.
Implements clang::CXDiagnosticImpl.
Definition at line 93 of file CXStoredDiagnostic.cpp.
                                                {
  if (Diag.getLocation().isInvalid())
    return 0;
  return Diag.fixit_size();
}
getNumRanges()
unsigned CXStoredDiagnostic::getNumRanges () const [override], [virtual]
Return the number of source ranges for the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 79 of file CXStoredDiagnostic.cpp.
                                                {
  if (Diag.getLocation().isInvalid())
    return 0;
  
  return Diag.range_size();
}
getRange()
CXSourceRange CXStoredDiagnostic::getRange (unsigned Range) const [override], [virtual]
Return the source ranges for the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 86 of file CXStoredDiagnostic.cpp.
                                                                   {
  assert(Diag.getLocation().isValid());
  return translateSourceRange(Diag.getLocation().getManager(),
                              LangOpts,
                              Diag.range_begin()[Range]);
}
References clang::cxloc::translateSourceRange().
getSeverity()
CXDiagnosticSeverity CXStoredDiagnostic::getSeverity () const [override], [virtual]
Return the severity of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 26 of file CXStoredDiagnostic.cpp.
                                                           {
  switch (Diag.getLevel()) {
    case DiagnosticsEngine::Ignored: return CXDiagnostic_Ignored;
    case DiagnosticsEngine::Note: return CXDiagnostic_Note;
    case DiagnosticsEngine::Remark:
    // The 'Remark' level isn't represented in the stable API.
    case DiagnosticsEngine::Warning: return CXDiagnostic_Warning;
    case DiagnosticsEngine::Error: return CXDiagnostic_Error;
    case DiagnosticsEngine::Fatal: return CXDiagnostic_Fatal;
  }
  
  llvm_unreachable("Invalid diagnostic level");
}
getSpelling()
CXString CXStoredDiagnostic::getSpelling () const [override], [virtual]
Return the spelling of the diagnostic.
Implements clang::CXDiagnosticImpl.
Definition at line 48 of file CXStoredDiagnostic.cpp.
                                               {
  return cxstring::createRef(Diag.getMessage());
}
References clang::cxstring::createRef().
Member Data Documentation
ChildDiags
CXDiagnosticSetImpl clang::CXDiagnosticImpl::ChildDiags [protected], [inherited]
Definition at line 100 of file CIndexDiagnostic.h.
Referenced by clang::CXDiagnosticImpl::append(), and clang::CXDiagnosticImpl::getChildDiagnostics().
Diag
const StoredDiagnostic& clang::CXStoredDiagnostic::Diag
Definition at line 112 of file CIndexDiagnostic.h.
LangOpts
const LangOptions& clang::CXStoredDiagnostic::LangOpts
Definition at line 113 of file CIndexDiagnostic.h.
The documentation for this struct was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.h
/Users/maximilian/clang-llvm/clang/tools/libclang/CXStoredDiagnostic.cpp