diagtool::GroupRecord Struct Reference
#include <DiagnosticNames.h>
Classes
class group_iterator
Public Types
typedef group_iterator< GroupRecord > subgroup_iterator
typedef group_iterator< DiagnosticRecord > diagnostics_iterator
Public Member Functions
llvm::StringRef getName () const
subgroup_iterator subgroup_begin () const
subgroup_iterator subgroup_end () const
llvm::iterator_range< subgroup_iterator > subgroups () const
diagnostics_iterator diagnostics_begin () const
diagnostics_iterator diagnostics_end () const
llvm::iterator_range< diagnostics_iterator > diagnostics () const
bool operator< (llvm::StringRef Other) const
Public Attributes
uint16_t NameOffset
uint16_t Members
uint16_t SubGroups
Detailed Description
Definition at line 39 of file DiagnosticNames.h.
Member Typedef Documentation
diagnostics_iterator
typedef group_iterator<DiagnosticRecord> diagtool::GroupRecord::diagnostics_iterator
Definition at line 93 of file DiagnosticNames.h.
subgroup_iterator
typedef group_iterator<GroupRecord> diagtool::GroupRecord::subgroup_iterator
Definition at line 88 of file DiagnosticNames.h.
Member Function Documentation
diagnostics()
llvm::iterator_range< diagtool::GroupRecord::diagnostics_iterator > GroupRecord::diagnostics () const
Definition at line 100 of file DiagnosticNames.cpp.
                               {
  return llvm::make_range(diagnostics_begin(), diagnostics_end());
}
Referenced by TreePrinter::enabledByDefault(), TreePrinter::printGroup(), and TreePrinter::unimplemented().
diagnostics_begin()
GroupRecord::diagnostics_iterator GroupRecord::diagnostics_begin () const
Definition at line 91 of file DiagnosticNames.cpp.
                                                                     {
  return DiagArrays + Members;
}
diagnostics_end()
GroupRecord::diagnostics_iterator GroupRecord::diagnostics_end () const
Definition at line 95 of file DiagnosticNames.cpp.
                                                                   {
  return nullptr;
}
getName()
llvm::StringRef GroupRecord::getName () const
Definition at line 74 of file DiagnosticNames.cpp.
                                         {
  return StringRef(DiagGroupNames + NameOffset + 1, DiagGroupNames[NameOffset]);
}
Referenced by Reporter.TextParameter::getHTML(), Reporter.SelectionParameter::getHTML(), Reporter.ReporterParameter::getValue(), operator<(), TreePrinter::printGroup(), and TreePrinter::showGroup().
operator<()
bool diagtool::GroupRecord::operator< (llvm::StringRef Other) const [inline]
Definition at line 98 of file DiagnosticNames.h.
                                              {
      return getName() < Other;
    }
References getName().
subgroup_begin()
GroupRecord::subgroup_iterator GroupRecord::subgroup_begin () const
Definition at line 78 of file DiagnosticNames.cpp.
                                                               {
  return DiagSubGroups + SubGroups;
}
subgroup_end()
GroupRecord::subgroup_iterator GroupRecord::subgroup_end () const
Definition at line 82 of file DiagnosticNames.cpp.
                                                             {
  return nullptr;
}
subgroups()
llvm::iterator_range< diagtool::GroupRecord::subgroup_iterator > GroupRecord::subgroups () const
Definition at line 87 of file DiagnosticNames.cpp.
                             {
  return llvm::make_range(subgroup_begin(), subgroup_end());
}
Referenced by TreePrinter::enabledByDefault(), TreePrinter::printGroup(), and TreePrinter::unimplemented().
Member Data Documentation
Members
uint16_t diagtool::GroupRecord::Members
Definition at line 41 of file DiagnosticNames.h.
NameOffset
uint16_t diagtool::GroupRecord::NameOffset
Definition at line 40 of file DiagnosticNames.h.
SubGroups
uint16_t diagtool::GroupRecord::SubGroups
Definition at line 42 of file DiagnosticNames.h.
The documentation for this struct was generated from the following files:
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.h
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.cpp