Tests/testPerformance.cpp File Reference
#include <iostream>
#include `../lib/DataStorage.cpp`
Functions
void fibonacci ()
int main (void)
Variables
DataStorage dataStorage
Function Documentation
fibonacci()
void fibonacci ()
Definition at line 5 of file testPerformance.cpp.
                 {
    dataStorage.startEvent("DeclStmt 2082482");
    double n, t1 = 0, t2 = 1, nextTerm = 0;
    dataStorage.startEvent("DeclStmt 2082482");
    dataStorage.startEvent("BinaryOperator 2082496");
    n = 50;
    dataStorage.startEvent("BinaryOperator 2082496");
    dataStorage.startEvent("CXXOperatorCallExpr 2083688");
    std::cout << "Fibonacci Series: ";
    dataStorage.startEvent("CXXOperatorCallExpr 2083688");
    dataStorage.startEvent("ForStmt 2086448");
    for (int i = 1; i <= n; ++i) {
        if(i == 1) {
            std::cout << t1 << ", ";
            continue;
        }
        if(i == 2) {
            std::cout << t2 << ", ";
            continue;
        }
        nextTerm = t1 + t2;
        t1 = t2;
        t2 = nextTerm;
        std::cout << nextTerm << ", ";
    }
    dataStorage.startEvent("ForStmt 2086448");
}
References dataStorage, and DataStorage::startEvent().
Referenced by main().
main()
int main (void)
Definition at line 37 of file testPerformance.cpp.
               {
    dataStorage.startEvent("Runtime");
    int i = 10;
    i++;
    i++;
    i++;
    i++;
    i++;
    fibonacci();
    dataStorage.startEvent("Runtime");
    dataStorage.print();
    return 0;
}
References dataStorage, fibonacci(), DataStorage::print(), and DataStorage::startEvent().
Variable Documentation
dataStorage
DataStorage dataStorage
Definition at line 3 of file testPerformance.cpp.
Referenced by fibonacci(), and main().