.TH "_CXCursorAndRangeVisitorBlock" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CXCursorAndRangeVisitorBlock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Index_Internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBisa\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBreserved\fP"
.br
.ti -1c
.RI "enum CXVisitorResult(* \fBinvoke\fP )(\fB_CXCursorAndRangeVisitorBlock\fP *, CXCursor, CXSourceRange)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file Index_Internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int _CXCursorAndRangeVisitorBlock::flags"

.PP
Definition at line 34 of file Index_Internal\&.h\&.
.SS "enum CXVisitorResult(* _CXCursorAndRangeVisitorBlock::invoke) (\fB_CXCursorAndRangeVisitorBlock\fP *, CXCursor, CXSourceRange)"

.PP
Definition at line 35 of file Index_Internal\&.h\&.
.SS "void* _CXCursorAndRangeVisitorBlock::isa"

.PP
Definition at line 33 of file Index_Internal\&.h\&.
.SS "int _CXCursorAndRangeVisitorBlock::reserved"

.PP
Definition at line 35 of file Index_Internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
