.TH "_CXChildVisitResult" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CXChildVisitResult
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBisa\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBreserved\fP"
.br
.ti -1c
.RI "enum CXChildVisitResult(* \fBinvoke\fP )(struct \fB_CXChildVisitResult\fP *, CXCursor, CXCursor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4577 of file CIndex\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int _CXChildVisitResult::flags"

.PP
Definition at line 4579 of file CIndex\&.cpp\&.
.SS "enum CXChildVisitResult(* _CXChildVisitResult::invoke) (struct \fB_CXChildVisitResult\fP *, CXCursor, CXCursor)"

.PP
Definition at line 4580 of file CIndex\&.cpp\&.
.SS "void* _CXChildVisitResult::isa"

.PP
Definition at line 4578 of file CIndex\&.cpp\&.
.SS "int _CXChildVisitResult::reserved"

.PP
Definition at line 4580 of file CIndex\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
