.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool Directory Reference" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDiagnosticNames\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDiagnosticNames\&.h\fP"
.br
.ti -1c
.RI "file \fBDiagTool\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDiagTool\&.h\fP"
.br
.ti -1c
.RI "file \fBdiagtool_main\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFindDiagnosticID\&.cpp\fP"
.br
.ti -1c
.RI "file \fBListWarnings\&.cpp\fP"
.br
.ti -1c
.RI "file \fBShowEnabledWarnings\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTreeView\&.cpp\fP"
.br
.in -1c
