.TH "/Users/maximilian/clang-llvm/clang/tools/clang-refactor Directory Reference" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-refactor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClangRefactor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTestSupport\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTestSupport\&.h\fP"
.br
.ti -1c
.RI "file \fBToolRefactoringResultConsumer\&.h\fP"
.br
.in -1c
