.TH "/Users/maximilian/clang-llvm/clang/tools/clang-format-vs/ClangFormat Directory Reference" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-format-vs/ClangFormat Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClangFormatPackage\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSuppressions\&.cs\fP"
.br
.ti -1c
.RI "file \fBGuids\&.cs\fP"
.br
.ti -1c
.RI "file \fBPkgCmdID\&.cs\fP"
.br
.ti -1c
.RI "file \fBResources\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBRunningDocTableEventsDispatcher\&.cs\fP"
.br
.ti -1c
.RI "file \fBVsix\&.cs\fP"
.br
.in -1c
