.TH "AllocatedCXCompileCommands" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AllocatedCXCompileCommands
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAllocatedCXCompileCommands\fP (std::vector< CompileCommand > Cmd)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< CompileCommand > \fBCCmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file CXCompilationDatabase\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AllocatedCXCompileCommands::AllocatedCXCompileCommands (std::vector< CompileCommand > Cmd)\fC [inline]\fP"

.PP
Definition at line 41 of file CXCompilationDatabase\&.cpp\&.
.PP
.nf
42       : CCmd(std::move(Cmd)) {}
.fi
.SH "Member Data Documentation"
.PP 
.SS "std::vector<CompileCommand> AllocatedCXCompileCommands::CCmd"

.PP
Definition at line 39 of file CXCompilationDatabase\&.cpp\&.
.PP
Referenced by clang_CompileCommands_getCommand(), and clang_CompileCommands_getSize()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
