.TH "/Users/maximilian/clang-llvm/clang/tools/amdgpu-arch/AMDGPUArch.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/amdgpu-arch/AMDGPUArch.cpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSA_HEADER_FOUND\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HSA_HEADER_FOUND   0"

.PP
Definition at line 25 of file AMDGPUArch\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 29 of file AMDGPUArch\&.cpp\&.
.PP
.nf
29 { return 1; }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
