.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/analyze.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/analyze.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibscanbuild\&.analyze\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.scan_build\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.analyze_build\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.need_analyzer\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.prefix_with\fP (constant, pieces)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.get_ctu_config_from_args\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.get_ctu_config_from_json\fP (ctu_conf_json)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.create_global_ctu_extdef_map\fP (extdef_map_lines)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.merge_ctu_extdef_maps\fP (ctudir)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.run_analyzer_parallel\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.govern_analyzer_runs\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.setup_environment\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.analyze_compiler_wrapper\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.analyze_compiler_wrapper_impl\fP (result, execution)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.report_directory\fP (hint, keep, output_format)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.analyzer_params\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.require\fP (required)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.run\fP (opts)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.report_failure\fP (opts)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.run_analyzer\fP (opts, continuation=report_failure)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.extdef_map_list_src_to_ast\fP (extdef_src_list)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.ctu_collect_phase\fP (opts)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.dispatch_ctu\fP (opts, continuation=run_analyzer)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.filter_debug_flags\fP (opts, continuation=dispatch_ctu)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.language_check\fP (opts, continuation=filter_debug_flags)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.arch_check\fP (opts, continuation=language_check)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.analyze\&.classify_parameters\fP (command)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBlibscanbuild\&.analyze\&.COMPILER_WRAPPER_CC\fP = 'analyze\-cc'"
.br
.ti -1c
.RI "string \fBlibscanbuild\&.analyze\&.COMPILER_WRAPPER_CXX\fP = 'analyze\-c++'"
.br
.ti -1c
.RI "string \fBlibscanbuild\&.analyze\&.CTU_EXTDEF_MAP_FILENAME\fP = 'externalDefMap\&.txt'"
.br
.ti -1c
.RI "string \fBlibscanbuild\&.analyze\&.CTU_TEMP_DEFMAP_FOLDER\fP = 'tmpExternalDefMaps'"
.br
.ti -1c
.RI "dictionary \fBlibscanbuild\&.analyze\&.IGNORED_FLAGS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
