.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/arguments.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/arguments.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibscanbuild\&.arguments\&.AppendCommaSeparated\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibscanbuild\&.arguments\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.parse_args_for_intercept_build\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.parse_args_for_analyze_build\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.parse_args_for_scan_build\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.normalize_args_for_analyze\fP (args, from_build_command)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.validate_args_for_analyze\fP (parser, args, from_build_command)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.create_intercept_parser\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.create_analyze_parser\fP (from_build_command)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.create_default_parser\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.parser_add_cdb\fP (parser)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.parser_add_prefer_wrapper\fP (parser)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.parser_add_compilers\fP (parser)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.print_active_checkers\fP (checkers)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.arguments\&.print_checkers\fP (checkers)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
