.TH "BaseClass(Private)" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseClass(Private)
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(int) \- \fBsomething\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBfield\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file ClassCategory\&.m\&.
.SH "Method Documentation"
.PP 
.SS "\- (int) something "

.SH "Property Documentation"
.PP 
.SS "\- (int) field\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 9 of file ClassCategory\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
