.TH "BaseClass" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseClass
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRootObject\fP, \fBRootObject\fP, and \fBRootObject\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(instancetype) \- \fBinitWithFoo:\fP"
.br
.ti -1c
.RI "(instancetype) \- \fBinit\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(instancetype) + \fBsharedInstance\fP"
.br
.ti -1c
.RI "(instancetype) + \fBalloc\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBfield\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ClassCategory\&.m\&.
.SH "Method Documentation"
.PP 
.SS "+ (instancetype) alloc "

.SS "\- (instancetype) init "

.SS "\- (instancetype) initWithFoo: (int) foo"

.PP
Definition at line 14 of file SharedInstance\&.m\&.
.PP
.nf
26                            :(int)foo {
27   self = [super init];
28   if (self) {
29     counter += foo;
30   }
31   return self;
32 }
.fi
.SS "+ (instancetype) sharedInstance "

.PP
Definition at line 14 of file SharedInstance\&.m\&.
.PP
.nf
17                                {
18   if (sharedInstance) {
19     return sharedInstance;
20   }
21   sharedInstance = [[BaseClass alloc] initWithFoo:3];
22   return sharedInstance;
23 }
.fi
.SH "Property Documentation"
.PP 
.SS "\- (int) field\fC [read]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 5 of file ClassCategory\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
