.TH "BaseClass()" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseClass()
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(int) \- \fBaddFields\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_field1\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBfield2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ClassExtension\&.m\&.
.SH "Method Documentation"
.PP 
.SS "\- (int) addFields "

.PP
References field2\&.
.SH "Member Data Documentation"
.PP 
.SS "\- (int) _field1\fC [protected]\fP"

.PP
Definition at line 8 of file ClassExtension\&.m\&.
.SH "Property Documentation"
.PP 
.SS "\- (int) field2\fC [read]\fP, \fC [atomic]\fP, \fC [assign]\fP"

.PP
Definition at line 10 of file ClassExtension\&.m\&.
.PP
Referenced by addFields\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
