.TH "BasicClass" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicClass
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRootObject\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) \- \fBsomeMethod\fP"
.br
.ti -1c
.RI "(instancetype) \- \fBinit\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(instancetype) + \fBalloc\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_foo\fP"
.br
.ti -1c
.RI "char \fB_boolean\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBbar\fP"
.br
.ti -1c
.RI "id \fBobjectField\fP"
.br
.ti -1c
.RI "id \fBdelegate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file BasicClass\&.m\&.
.SH "Method Documentation"
.PP 
.SS "+ (instancetype) alloc "

.SS "\- (instancetype) init "

.SS "\- (void) someMethod "

.PP
Definition at line 11 of file BasicClass\&.m\&.
.PP
.nf
22                    {
23   int value = self\&.bar;
24   _foo = (_boolean != 0) ? self\&.bar : [self\&.objectField bar];
25   [self setBar:value];
26   id obj = self\&.objectField;
27 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\- (char) _boolean\fC [protected]\fP"

.PP
Definition at line 6 of file BasicClass\&.m\&.
.SS "\- (int) _foo\fC [protected]\fP"

.PP
Definition at line 5 of file BasicClass\&.m\&.
.SH "Property Documentation"
.PP 
.SS "\- (int) bar\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 9 of file BasicClass\&.m\&.
.SS "\- (id) delegate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.PP
Definition at line 11 of file BasicClass\&.m\&.
.SS "\- (id) objectField\fC [read]\fP, \fC [write]\fP, \fC [atomic]\fP, \fC [retain]\fP"

.PP
Definition at line 10 of file BasicClass\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
