.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/corpus_examples/objc/BasicClass.m" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/corpus_examples/objc/BasicClass.m
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRootObject\fP"
.br
.ti -1c
.RI "class \fBBasicClass\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
