.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/broken-one.c" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/broken-one.c
.SH SYNOPSIS
.br
.PP
\fC#include <notexisting\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBvalue\fP (int in)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int value (int in)"

.PP
Definition at line 3 of file broken\-one\&.c\&.
.PP
.nf
4 {
5     return 2 * in;
6 }
.fi
.PP
Referenced by LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter::ConvertFrom(), and LLVM\&.ClangFormat\&.OptionPageGrid\&.FilenameConverter::ConvertFrom()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
