.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexDiagnostic.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::CXDiagnosticSetImpl\fP"
.br
.ti -1c
.RI "class \fBclang::CXDiagnosticImpl\fP"
.br
.ti -1c
.RI "struct \fBclang::CXStoredDiagnostic\fP"
.br
.RI "The storage behind a CXDiagnostic\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxdiag\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCXDiagnosticSetImpl\fP * \fBclang::cxdiag::lazyCreateDiags\fP (CXTranslationUnit TU, bool checkIfChanged=false)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
