.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexer.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CIndexer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br
\fC#include 'clang/Frontend/PCHContainerOperations\&.h'\fP
.br
\fC#include 'llvm/ADT/STLExtras\&.h'\fP
.br
\fC#include <utility>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::CIndexer\fP"
.br
.ti -1c
.RI "class \fBclang::LibclangInvocationReporter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBllvm\fP"
.br
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxindex\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned \fBclang::GetSafetyThreadStackSize\fP ()"
.br
.RI "Return the current size to request for 'safety'\&. "
.ti -1c
.RI "void \fBclang::SetSafetyThreadStackSize\fP (unsigned Value)"
.br
.ti -1c
.RI "bool \fBclang::RunSafely\fP (llvm::CrashRecoveryContext &CRC, llvm::function_ref< void()> Fn, unsigned Size)"
.br
.ti -1c
.RI "void \fBclang::setThreadBackgroundPriority\fP ()"
.br
.ti -1c
.RI "void \fBclang::PrintLibclangResourceUsage\fP (CXTranslationUnit TU)"
.br
.RI "Print libclang's resource usage to standard error\&. "
.ti -1c
.RI "void \fBclang::cxindex::printDiagsToStderr\fP (ASTUnit *Unit)"
.br
.ti -1c
.RI "MacroInfo * \fBclang::cxindex::getMacroInfo\fP (const IdentifierInfo &II, SourceLocation MacroDefLoc, CXTranslationUnit TU)"
.br
.ti -1c
.RI "const MacroInfo * \fBclang::cxindex::getMacroInfo\fP (const MacroDefinitionRecord *MacroDef, CXTranslationUnit TU)"
.br
.RI "Retrieves the corresponding MacroInfo of a MacroDefinitionRecord\&. "
.ti -1c
.RI "MacroDefinitionRecord * \fBclang::cxindex::checkForMacroInMacroDefinition\fP (const MacroInfo *MI, SourceLocation Loc, CXTranslationUnit TU)"
.br
.ti -1c
.RI "MacroDefinitionRecord * \fBclang::cxindex::checkForMacroInMacroDefinition\fP (const MacroInfo *MI, const Token &Tok, CXTranslationUnit TU)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
