.TH "clang::cxcursor::VisitorJob" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxcursor::VisitorJob
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CursorVisitor\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBKind\fP { \fBDeclVisitKind\fP, \fBStmtVisitKind\fP, \fBMemberExprPartsKind\fP, \fBTypeLocVisitKind\fP, \fBOverloadExprPartsKind\fP, \fBDeclRefExprPartsKind\fP, \fBLabelRefVisitKind\fP, \fBExplicitTemplateArgsVisitKind\fP, \fBNestedNameSpecifierLocVisitKind\fP, \fBDeclarationNameInfoVisitKind\fP, \fBMemberRefVisitKind\fP, \fBSizeOfPackExprPartsKind\fP, \fBLambdaExprPartsKind\fP, \fBPostChildrenVisitKind\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKind\fP \fBgetKind\fP () const"
.br
.ti -1c
.RI "const CXCursor & \fBgetParent\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVisitorJob\fP (CXCursor C, \fBKind\fP k, const void *d1, const void *d2=nullptr, const void *d3=nullptr)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const void * \fBdata\fP [3]"
.br
.ti -1c
.RI "CXCursor \fBparent\fP"
.br
.ti -1c
.RI "\fBKind\fP \fBK\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file CursorVisitor\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBclang::cxcursor::VisitorJob::Kind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDeclVisitKind \fP\fP
.TP
\fB\fIStmtVisitKind \fP\fP
.TP
\fB\fIMemberExprPartsKind \fP\fP
.TP
\fB\fITypeLocVisitKind \fP\fP
.TP
\fB\fIOverloadExprPartsKind \fP\fP
.TP
\fB\fIDeclRefExprPartsKind \fP\fP
.TP
\fB\fILabelRefVisitKind \fP\fP
.TP
\fB\fIExplicitTemplateArgsVisitKind \fP\fP
.TP
\fB\fINestedNameSpecifierLocVisitKind \fP\fP
.TP
\fB\fIDeclarationNameInfoVisitKind \fP\fP
.TP
\fB\fIMemberRefVisitKind \fP\fP
.TP
\fB\fISizeOfPackExprPartsKind \fP\fP
.TP
\fB\fILambdaExprPartsKind \fP\fP
.TP
\fB\fIPostChildrenVisitKind \fP\fP
.PP
Definition at line 26 of file CursorVisitor\&.h\&.
.PP
.nf
26             {
27     DeclVisitKind,
28     StmtVisitKind,
29     MemberExprPartsKind,
30     TypeLocVisitKind,
31     OverloadExprPartsKind,
32     DeclRefExprPartsKind,
33     LabelRefVisitKind,
34     ExplicitTemplateArgsVisitKind,
35     NestedNameSpecifierLocVisitKind,
36     DeclarationNameInfoVisitKind,
37     MemberRefVisitKind,
38     SizeOfPackExprPartsKind,
39     LambdaExprPartsKind,
40     PostChildrenVisitKind
41   };
.fi
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::cxcursor::VisitorJob::VisitorJob (CXCursor C, \fBKind\fP k, const void * d1, const void * d2 = \fCnullptr\fP, const void * d3 = \fCnullptr\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 47 of file CursorVisitor\&.h\&.
.PP
.nf
49       : parent(C), K(k) {
50     data[0] = d1;
51     data[1] = d2;
52     data[2] = d3;
53   }
.fi
.PP
References data\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBKind\fP clang::cxcursor::VisitorJob::getKind () const\fC [inline]\fP"

.PP
Definition at line 56 of file CursorVisitor\&.h\&.
.PP
.nf
56 { return K; }
.fi
.PP
References K\&.
.PP
Referenced by clang::cxcursor::CursorVisitor::RunVisitorWorkList()\&.
.SS "const CXCursor& clang::cxcursor::VisitorJob::getParent () const\fC [inline]\fP"

.PP
Definition at line 57 of file CursorVisitor\&.h\&.
.PP
.nf
57 { return parent; }
.fi
.PP
References parent\&.
.PP
Referenced by clang::cxcursor::CursorVisitor::RunVisitorWorkList()\&.
.SH "Member Data Documentation"
.PP 
.SS "const void* clang::cxcursor::VisitorJob::data[3]\fC [protected]\fP"

.PP
Definition at line 44 of file CursorVisitor\&.h\&.
.PP
Referenced by VisitorJob()\&.
.SS "\fBKind\fP clang::cxcursor::VisitorJob::K\fC [protected]\fP"

.PP
Definition at line 46 of file CursorVisitor\&.h\&.
.PP
Referenced by getKind()\&.
.SS "CXCursor clang::cxcursor::VisitorJob::parent\fC [protected]\fP"

.PP
Definition at line 45 of file CursorVisitor\&.h\&.
.PP
Referenced by getParent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
