.TH "clang::cxindex::ContainerInfo" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxindex::ContainerInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXIndexDataConsumer\&.h>\fP
.PP
Inherits CXIdxContainerInfo\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const DeclContext * \fBDC\fP"
.br
.ti -1c
.RI "\fBCXIndexDataConsumer\fP * \fBIndexCtx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file CXIndexDataConsumer\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const DeclContext* clang::cxindex::ContainerInfo::DC"

.PP
Definition at line 61 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang_index_getClientContainer(), and clang_index_setClientContainer()\&.
.SS "\fBCXIndexDataConsumer\fP* clang::cxindex::ContainerInfo::IndexCtx"

.PP
Definition at line 62 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang_index_getClientContainer(), and clang_index_setClientContainer()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
