.TH "clang::refactor::TestSelectionRangesInFile::RangeGroup" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::refactor::TestSelectionRangesInFile::RangeGroup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TestSupport\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "SmallVector< \fBTestSelectionRange\fP, 8 > \fBRanges\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file TestSupport\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string clang::refactor::TestSelectionRangesInFile::RangeGroup::Name"

.PP
Definition at line 56 of file TestSupport\&.h\&.
.SS "SmallVector<\fBTestSelectionRange\fP, 8> clang::refactor::TestSelectionRangesInFile::RangeGroup::Ranges"

.PP
Definition at line 57 of file TestSupport\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
