.TH "clang::cxindex::ObjCCategoryDeclInfo" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxindex::ObjCCategoryDeclInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXIndexDataConsumer\&.h>\fP
.PP
Inherits \fBclang::cxindex::ObjCContainerDeclInfo\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDInfoKind\fP { \fBInfo_Decl\fP, \fBInfo_ObjCContainer\fP, \fBInfo_ObjCInterface\fP, \fBInfo_ObjCProtocol\fP, \fBInfo_ObjCCategory\fP, \fBInfo_ObjCProperty\fP, \fBInfo_CXXClass\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjCCategoryDeclInfo\fP (bool isImplementation)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBDeclInfo\fP *D)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CXIdxObjCCategoryDeclInfo \fBObjCCatDeclInfo\fP"
.br
.ti -1c
.RI "CXIdxObjCProtocolRefListInfo \fBObjCProtoListInfo\fP"
.br
.ti -1c
.RI "CXIdxObjCContainerDeclInfo \fBObjCContDeclInfo\fP"
.br
.ti -1c
.RI "\fBDInfoKind\fP \fBKind\fP"
.br
.ti -1c
.RI "\fBEntityInfo\fP \fBEntInfo\fP"
.br
.ti -1c
.RI "\fBContainerInfo\fP \fBSemanticContainer\fP"
.br
.ti -1c
.RI "\fBContainerInfo\fP \fBLexicalContainer\fP"
.br
.ti -1c
.RI "\fBContainerInfo\fP \fBDeclAsContainer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file CXIndexDataConsumer\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBclang::cxindex::DeclInfo::DInfoKind\fP\fC [inherited]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInfo_Decl \fP\fP
.TP
\fB\fIInfo_ObjCContainer \fP\fP
.TP
\fB\fIInfo_ObjCInterface \fP\fP
.TP
\fB\fIInfo_ObjCProtocol \fP\fP
.TP
\fB\fIInfo_ObjCCategory \fP\fP
.TP
\fB\fIInfo_ObjCProperty \fP\fP
.TP
\fB\fIInfo_CXXClass \fP\fP
.PP
Definition at line 66 of file CXIndexDataConsumer\&.h\&.
.PP
.nf
66                  {
67     Info_Decl,
68 
69     Info_ObjCContainer,
70       Info_ObjCInterface,
71       Info_ObjCProtocol,
72       Info_ObjCCategory,
73 
74     Info_ObjCProperty,
75 
76     Info_CXXClass
77   };
.fi
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::cxindex::ObjCCategoryDeclInfo::ObjCCategoryDeclInfo (bool isImplementation)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 176 of file CXIndexDataConsumer\&.h\&.
.PP
.nf
177     : ObjCContainerDeclInfo(Info_ObjCCategory,
178                             /*isForwardRef=*/false,
179                             /*isRedeclaration=*/isImplementation,
180                             /*isImplementation=*/isImplementation) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "static bool clang::cxindex::ObjCCategoryDeclInfo::classof (const \fBDeclInfo\fP * D)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 182 of file CXIndexDataConsumer\&.h\&.
.PP
.nf
182                                          {
183     return D->Kind == Info_ObjCCategory;
184   }
.fi
.PP
References clang::cxindex::DeclInfo::Info_ObjCCategory, and clang::cxindex::DeclInfo::Kind\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBContainerInfo\fP clang::cxindex::DeclInfo::DeclAsContainer\fC [inherited]\fP"

.PP
Definition at line 84 of file CXIndexDataConsumer\&.h\&.
.SS "\fBEntityInfo\fP clang::cxindex::DeclInfo::EntInfo\fC [inherited]\fP"

.PP
Definition at line 81 of file CXIndexDataConsumer\&.h\&.
.SS "\fBDInfoKind\fP clang::cxindex::DeclInfo::Kind\fC [inherited]\fP"

.PP
Definition at line 79 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang::cxindex::ObjCContainerDeclInfo::classof(), clang::cxindex::ObjCInterfaceDeclInfo::classof(), clang::cxindex::ObjCProtocolDeclInfo::classof(), classof(), clang::cxindex::ObjCPropertyDeclInfo::classof(), and clang::cxindex::CXXClassDeclInfo::classof()\&.
.SS "\fBContainerInfo\fP clang::cxindex::DeclInfo::LexicalContainer\fC [inherited]\fP"

.PP
Definition at line 83 of file CXIndexDataConsumer\&.h\&.
.SS "CXIdxObjCCategoryDeclInfo clang::cxindex::ObjCCategoryDeclInfo::ObjCCatDeclInfo"

.PP
Definition at line 173 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang::cxindex::CXIndexDataConsumer::handleObjCCategory(), and clang::cxindex::CXIndexDataConsumer::handleObjCCategoryImpl()\&.
.SS "CXIdxObjCContainerDeclInfo clang::cxindex::ObjCContainerDeclInfo::ObjCContDeclInfo\fC [inherited]\fP"

.PP
Definition at line 110 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang::cxindex::CXIndexDataConsumer::handleObjCCategory(), clang::cxindex::CXIndexDataConsumer::handleObjCCategoryImpl(), and clang::cxindex::CXIndexDataConsumer::handleObjCInterface()\&.
.SS "CXIdxObjCProtocolRefListInfo clang::cxindex::ObjCCategoryDeclInfo::ObjCProtoListInfo"

.PP
Definition at line 174 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang::cxindex::CXIndexDataConsumer::handleObjCCategory()\&.
.SS "\fBContainerInfo\fP clang::cxindex::DeclInfo::SemanticContainer\fC [inherited]\fP"

.PP
Definition at line 82 of file CXIndexDataConsumer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
