.TH "clang::cxtu::CXTUOwner" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxtu::CXTUOwner
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXTranslationUnit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCXTUOwner\fP (\fBCXTranslationUnitImpl\fP *tu)"
.br
.ti -1c
.RI "\fB~CXTUOwner\fP ()"
.br
.ti -1c
.RI "\fBCXTranslationUnitImpl\fP * \fBgetTU\fP () const"
.br
.ti -1c
.RI "\fBCXTranslationUnitImpl\fP * \fBtakeTU\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file CXTranslationUnit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::cxtu::CXTUOwner::CXTUOwner (\fBCXTranslationUnitImpl\fP * tu)\fC [inline]\fP"

.PP
Definition at line 74 of file CXTranslationUnit\&.h\&.
.PP
.nf
74 : TU(tu) { }
.fi
.SS "cxtu::CXTUOwner::~CXTUOwner ()"

.PP
Definition at line 102 of file CIndex\&.cpp\&.
.PP
.nf
102                           {
103   if (TU)
104     clang_disposeTranslationUnit(TU);
105 }
.fi
.PP
References clang_disposeTranslationUnit()\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCXTranslationUnitImpl\fP* clang::cxtu::CXTUOwner::getTU () const\fC [inline]\fP"

.PP
Definition at line 77 of file CXTranslationUnit\&.h\&.
.PP
.nf
77 { return TU; }
.fi
.SS "\fBCXTranslationUnitImpl\fP* clang::cxtu::CXTUOwner::takeTU ()\fC [inline]\fP"

.PP
Definition at line 79 of file CXTranslationUnit\&.h\&.
.PP
.nf
79                                   {
80     CXTranslationUnitImpl *retTU = TU;
81     TU = nullptr;
82     return retTU;
83   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
