.TH "clang::cxstring::CXStringBuf" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxstring::CXStringBuf
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXString\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCXStringBuf\fP (CXTranslationUnit \fBTU\fP)"
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.RI "Return this buffer to the pool\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SmallString< 128 > \fBData\fP"
.br
.ti -1c
.RI "CXTranslationUnit \fBTU\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file CXString\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::cxstring::CXStringBuf::CXStringBuf (CXTranslationUnit TU)\fC [inline]\fP"

.PP
Definition at line 89 of file CXString\&.h\&.
.PP
.nf
89 : TU(TU) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "void clang::cxstring::CXStringBuf::dispose ()"

.PP
Return this buffer to the pool\&. 
.PP
Definition at line 148 of file CXString\&.cpp\&.
.PP
.nf
148                           {
149   TU->StringPool->Pool\&.push_back(this);
150 }
.fi
.PP
References TU\&.
.PP
Referenced by clang_disposeString(), and clang_getCursorUSR()\&.
.SH "Member Data Documentation"
.PP 
.SS "SmallString<128> clang::cxstring::CXStringBuf::Data"

.PP
Definition at line 86 of file CXString\&.h\&.
.PP
Referenced by clang_getCursorUSR(), and clang::cxstring::CXStringPool::getCXStringBuf()\&.
.SS "CXTranslationUnit clang::cxstring::CXStringBuf::TU"

.PP
Definition at line 87 of file CXString\&.h\&.
.PP
Referenced by dispose()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
