.TH "/Users/maximilian/clang-llvm/clang/tools/clang-rename/clang-rename.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-rename/clang-rename.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\-rename\fP"
.br
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBclang\-rename\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
