.TH "clang-format-sublime" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang-format-sublime
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClangFormatCommand\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBbinary\fP = 'clang\-format'"
.br
.ti -1c
.RI "\fBstyle\fP = None"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string clang\-format\-sublime\&.binary = 'clang\-format'"

.PP
Definition at line 21 of file clang\-format\-sublime\&.py\&.
.SS "clang\-format\-sublime\&.style = None"

.PP
Definition at line 27 of file clang\-format\-sublime\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
