.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/clang.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/clang.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibscanbuild\&.clang\&.ClangErrorException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibscanbuild\&.clang\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.get_version\fP (clang)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.get_arguments\fP (command, cwd)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.get_active_checkers\fP (clang, plugins)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.is_active\fP (checkers)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.parse_checkers\fP (stream)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.get_checkers\fP (clang, plugins)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.is_ctu_capable\fP (extdef_map_cmd)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.clang\&.get_triple_arch\fP (command, cwd)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlibscanbuild\&.clang\&.ACTIVE_CHECKER_PATTERN\fP = re\&.compile(r'^\-analyzer\-checker=(\&.*)$')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
