.TH "/Users/maximilian/clang-llvm/clang/tools/clang-format/clang-format.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-format/clang-format.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\-format\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBclang\-format\&.get_buffer\fP (encoding)"
.br
.ti -1c
.RI "def \fBclang\-format\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBclang\-format\&.binary\fP = 'clang\-format'"
.br
.ti -1c
.RI "\fBclang\-format\&.style\fP = None"
.br
.ti -1c
.RI "\fBclang\-format\&.fallback_style\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
