.TH "clang_fuzzer::InnerLoop" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang_fuzzer::InnerLoop
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInnerLoop\fP ()"
.br
.ti -1c
.RI "\fB~InnerLoop\fP ()"
.br
.ti -1c
.RI "\fBInnerLoop\fP ()"
.br
.ti -1c
.RI "\fB~InnerLoop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file loop_proto_to_cxx\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang_fuzzer::InnerLoop::InnerLoop ()\fC [inline]\fP"

.PP
Definition at line 33 of file loop_proto_to_cxx\&.cpp\&.
.PP
.nf
33               {
34     inner_loop = true;
35   }
.fi
.SS "clang_fuzzer::InnerLoop::~InnerLoop ()\fC [inline]\fP"

.PP
Definition at line 36 of file loop_proto_to_cxx\&.cpp\&.
.PP
.nf
36                {
37     inner_loop = false;
38   }
.fi
.SS "clang_fuzzer::InnerLoop::InnerLoop ()\fC [inline]\fP"

.PP
Definition at line 40 of file loop_proto_to_llvm\&.cpp\&.
.PP
.nf
40               {
41     inner_loop = true;
42   }
.fi
.SS "clang_fuzzer::InnerLoop::~InnerLoop ()\fC [inline]\fP"

.PP
Definition at line 43 of file loop_proto_to_llvm\&.cpp\&.
.PP
.nf
43                {
44     inner_loop = false;
45   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
