.TH "clang::cxindex::AttrInfo" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxindex::AttrInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXIndexDataConsumer\&.h>\fP
.PP
Inherits CXIdxAttrInfo\&.
.PP
Inherited by \fBclang::cxindex::IBOutletCollectionInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttrInfo\fP (CXIdxAttrKind Kind, CXCursor C, CXIdxLoc Loc, const Attr *\fBA\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const Attr * \fBA\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 211 of file CXIndexDataConsumer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::cxindex::AttrInfo::AttrInfo (CXIdxAttrKind Kind, CXCursor C, CXIdxLoc Loc, const Attr * A)\fC [inline]\fP"

.PP
Definition at line 214 of file CXIndexDataConsumer\&.h\&.
.PP
.nf
214                                                                         {
215     kind = Kind;
216     cursor = C;
217     loc = Loc;
218     this->A = A;
219   }
.fi
.PP
References A\&.
.SH "Member Data Documentation"
.PP 
.SS "const Attr* clang::cxindex::AttrInfo::A"

.PP
Definition at line 212 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by AttrInfo(), clang::cxindex::AttrListInfo::AttrListInfo(), and clang::cxindex::IBOutletCollectionInfo::classof()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
