.TH "clang::CXLoadedDiagnostic::Location" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::CXLoadedDiagnostic::Location
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXLoadedDiagnostic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CXFile \fBfile\fP"
.br
.ti -1c
.RI "unsigned \fBline\fP"
.br
.ti -1c
.RI "unsigned \fBcolumn\fP"
.br
.ti -1c
.RI "unsigned \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file CXLoadedDiagnostic\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::CXLoadedDiagnostic::Location::Location ()\fC [inline]\fP"

.PP
Definition at line 78 of file CXLoadedDiagnostic\&.h\&.
.PP
.nf
78 : line(0), column(0), offset(0) {}    
.fi
.SH "Member Data Documentation"
.PP 
.SS "unsigned clang::CXLoadedDiagnostic::Location::column"

.PP
Definition at line 75 of file CXLoadedDiagnostic\&.h\&.
.PP
Referenced by clang::CXLoadedDiagnostic::decodeLocation()\&.
.SS "CXFile clang::CXLoadedDiagnostic::Location::file"

.PP
Definition at line 73 of file CXLoadedDiagnostic\&.h\&.
.PP
Referenced by clang::CXLoadedDiagnostic::decodeLocation()\&.
.SS "unsigned clang::CXLoadedDiagnostic::Location::line"

.PP
Definition at line 74 of file CXLoadedDiagnostic\&.h\&.
.PP
Referenced by clang::CXLoadedDiagnostic::decodeLocation()\&.
.SS "unsigned clang::CXLoadedDiagnostic::Location::offset"

.PP
Definition at line 76 of file CXLoadedDiagnostic\&.h\&.
.PP
Referenced by clang::CXLoadedDiagnostic::decodeLocation()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
