.TH "clang::cxindex::EntityInfo" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::cxindex::EntityInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXIndexDataConsumer\&.h>\fP
.PP
Inherits CXIdxEntityInfo\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const NamedDecl * \fBDcl\fP"
.br
.ti -1c
.RI "\fBCXIndexDataConsumer\fP * \fBIndexCtx\fP"
.br
.ti -1c
.RI "IntrusiveRefCntPtr< \fBAttrListInfo\fP > \fBAttrList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file CXIndexDataConsumer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clang::cxindex::EntityInfo::EntityInfo ()\fC [inline]\fP"

.PP
Definition at line 53 of file CXIndexDataConsumer\&.h\&.
.PP
.nf
53                {
54     name = USR = nullptr;
55     attributes = nullptr;
56     numAttributes = 0;
57   }
.fi
.SH "Member Data Documentation"
.PP 
.SS "IntrusiveRefCntPtr<\fBAttrListInfo\fP> clang::cxindex::EntityInfo::AttrList"

.PP
Definition at line 51 of file CXIndexDataConsumer\&.h\&.
.SS "const NamedDecl* clang::cxindex::EntityInfo::Dcl"

.PP
Definition at line 49 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang_index_getClientEntity(), and clang_index_setClientEntity()\&.
.SS "\fBCXIndexDataConsumer\fP* clang::cxindex::EntityInfo::IndexCtx"

.PP
Definition at line 50 of file CXIndexDataConsumer\&.h\&.
.PP
Referenced by clang_index_getClientEntity(), and clang_index_setClientEntity()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
