.TH "ClangFrontendAction" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClangFrontendAction \- Creates ASTConsumer and returns ASTContext\&. A new \fBClangFrontendAction\fP is created in the main, where the CompilerInstance and the SourceFiles are used to generate a new AST Tree \fBConsumer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits clang::ASTFrontendAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::unique_ptr< clang::ASTConsumer > \fBCreateASTConsumer\fP (clang::CompilerInstance &Compiler, llvm::StringRef InFile) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates ASTConsumer and returns ASTContext\&. A new \fBClangFrontendAction\fP is created in the main, where the CompilerInstance and the SourceFiles are used to generate a new AST Tree \fBConsumer\fP\&. 

! 
.PP
Definition at line 384 of file RegionProfile\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::unique_ptr<clang::ASTConsumer> ClangFrontendAction::CreateASTConsumer (clang::CompilerInstance & Compiler, llvm::StringRef InFile)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 387 of file RegionProfile\&.cpp\&.
.PP
.nf
387                                                                                         {
388         return std::make_unique<Consumer>( &Compiler\&.getASTContext( ));
389     }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
