.TH "clang::refactor::TestSelectionRange" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clang::refactor::TestSelectionRange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TestSupport\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBBegin\fP"
.br
.ti -1c
.RI "unsigned \fBEnd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A source selection range that's specified in a test file using an inline command in the comment\&. These commands can take the following forms:
.PP
.IP "\(bu" 2
/*range=*/ will create an empty selection range in the default group right after the comment\&.
.IP "\(bu" 2
/*range a=*/ will create an empty selection range in the 'a' group right after the comment\&.
.IP "\(bu" 2
/*range = +1*/ will create an empty selection range at a location that's right after the comment with one offset to the column\&.
.IP "\(bu" 2
/*range= -> +2:3*/ will create a selection range that starts at the location right after the comment, and ends at column 3 of the 2nd line after the line of the starting location\&.
.PP
.PP
Clang-refactor will expected all ranges in one test group to produce identical results\&. 
.PP
Definition at line 48 of file TestSupport\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned clang::refactor::TestSelectionRange::Begin"

.PP
Definition at line 49 of file TestSupport\&.h\&.
.PP
Referenced by clang::refactor::TestSelectionRangesInFile::foreachRange()\&.
.SS "unsigned clang::refactor::TestSelectionRange::End"

.PP
Definition at line 49 of file TestSupport\&.h\&.
.PP
Referenced by clang::refactor::TestSelectionRangesInFile::foreachRange()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
