.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/clean-one.c" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/clean-one.c
.SH SYNOPSIS
.br
.PP
\fC#include <clean\-one\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdo_nothing_loop\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int do_nothing_loop ()"

.PP
Definition at line 3 of file clean\-one\&.c\&.
.PP
.nf
4 {
5     int i = 32;
6     int idx = 0;
7 
8     for (idx = i; idx > 0; --idx)
9     {
10         i += idx;
11     }
12     return i;
13 }
.fi
.PP
Referenced by another_method()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
