.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/clean-two.c" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/clean-two.c
.SH SYNOPSIS
.br
.PP
\fC#include <clean\-one\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBanother_method\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int another_method ()"

.PP
Definition at line 5 of file clean\-two\&.c\&.
.PP
.nf
6 {
7     unsigned int const size = do_nothing_loop();
8     unsigned int const square = size * size;
9 
10     return square;
11 }
.fi
.PP
References do_nothing_loop()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
