.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CLog.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CLog.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br
\fC#include 'clang/Basic/LLVM\&.h'\fP
.br
\fC#include 'llvm/ADT/IntrusiveRefCntPtr\&.h'\fP
.br
\fC#include 'llvm/ADT/SmallString\&.h'\fP
.br
\fC#include 'llvm/ADT/StringRef\&.h'\fP
.br
\fC#include 'llvm/Support/Compiler\&.h'\fP
.br
\fC#include 'llvm/Support/raw_ostream\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::cxindex::Logger\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBllvm\fP"
.br
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxindex\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG_SECTION\fP(NAME)       if (\fBclang::cxindex::LogRef\fP Log = \fBclang::cxindex::Logger::make\fP(NAME))"
.br
.ti -1c
.RI "#define \fBLOG_FUNC_SECTION\fP   \fBLOG_SECTION\fP(__func__)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef IntrusiveRefCntPtr< Logger > \fBclang::cxindex::LogRef\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG_FUNC_SECTION   \fBLOG_SECTION\fP(__func__)"

.PP
Definition at line 100 of file CLog\&.h\&.
.SS "#define LOG_SECTION(NAME)       if (\fBclang::cxindex::LogRef\fP Log = \fBclang::cxindex::Logger::make\fP(NAME))"
Macros to automate common uses of Logger\&. Like this: 
.PP
.nf
LOG_FUNC_SECTION {
  *Log << "blah";
}

.fi
.PP
 
.PP
Definition at line 98 of file CLog\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
