.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CursorVisitor.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CursorVisitor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CXCursor\&.h'\fP
.br
\fC#include 'CXTranslationUnit\&.h'\fP
.br
\fC#include 'Index_Internal\&.h'\fP
.br
\fC#include 'clang/AST/DeclVisitor\&.h'\fP
.br
\fC#include 'clang/AST/TypeLocVisitor\&.h'\fP
.br
\fC#include 'clang/AST/TypeLocNodes\&.def'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::cxcursor::VisitorJob\fP"
.br
.ti -1c
.RI "class \fBclang::cxcursor::CursorVisitor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxcursor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBABSTRACT_TYPELOC\fP(CLASS,  PARENT)"
.br
.ti -1c
.RI "#define \fBTYPELOC\fP(CLASS,  PARENT)   bool Visit##CLASS##TypeLoc(CLASS##TypeLoc TyLoc);"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef SmallVector< VisitorJob, 10 > \fBclang::cxcursor::VisitorWorkList\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ABSTRACT_TYPELOC(CLASS, PARENT)"

.PP
Definition at line 257 of file CursorVisitor\&.h\&.
.SS "#define TYPELOC(CLASS, PARENT)   bool Visit##CLASS##TypeLoc(CLASS##TypeLoc TyLoc);"

.PP
Definition at line 258 of file CursorVisitor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
