.TH "CursorSourceLocation" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CursorSourceLocation
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "unsigned \fBline\fP"
.br
.ti -1c
.RI "unsigned \fBcolumn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2805 of file c\-index\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned CursorSourceLocation::column"

.PP
Definition at line 2808 of file c\-index\-test\&.c\&.
.SS "char* CursorSourceLocation::filename"

.PP
Definition at line 2806 of file c\-index\-test\&.c\&.
.SS "unsigned CursorSourceLocation::line"

.PP
Definition at line 2807 of file c\-index\-test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
