.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXCursor.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXCursor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br
\fC#include 'clang/Basic/SourceLocation\&.h'\fP
.br
\fC#include 'llvm/ADT/PointerUnion\&.h'\fP
.br
\fC#include <utility>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::cxcursor::MacroExpansionCursor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxcursor\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef llvm::PointerUnion< const OverloadExpr *, const Decl *, OverloadedTemplateStorage * > \fBclang::cxcursor::OverloadedDeclRefStorage\fP"
.br
.RI "Internal storage for an overloaded declaration reference cursor;\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CXCursor \fBclang::cxcursor::getCursor\fP (CXTranslationUnit, SourceLocation)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCXCursor\fP (const clang::Attr *A, const clang::Decl *Parent, CXTranslationUnit TU)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCXCursor\fP (const clang::Decl *D, CXTranslationUnit TU, SourceRange RegionOfInterest=SourceRange(), bool FirstInDeclGroup=true)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCXCursor\fP (const clang::Stmt *S, const clang::Decl *Parent, CXTranslationUnit TU, SourceRange RegionOfInterest=SourceRange())"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCXCursorInvalid\fP (CXCursorKind K, CXTranslationUnit TU=nullptr)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorObjCSuperClassRef\fP (ObjCInterfaceDecl *Super, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create an Objective-C superclass reference at the given location\&. "
.ti -1c
.RI "std::pair< const ObjCInterfaceDecl *, SourceLocation > \fBclang::cxcursor::getCursorObjCSuperClassRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorObjCProtocolRef\fP (const ObjCProtocolDecl *Proto, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create an Objective-C protocol reference at the given location\&. "
.ti -1c
.RI "std::pair< const ObjCProtocolDecl *, SourceLocation > \fBclang::cxcursor::getCursorObjCProtocolRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorObjCClassRef\fP (const ObjCInterfaceDecl *Class, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create an Objective-C class reference at the given location\&. "
.ti -1c
.RI "std::pair< const ObjCInterfaceDecl *, SourceLocation > \fBclang::cxcursor::getCursorObjCClassRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorTypeRef\fP (const TypeDecl *Type, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create a type reference at the given location\&. "
.ti -1c
.RI "std::pair< const TypeDecl *, SourceLocation > \fBclang::cxcursor::getCursorTypeRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorTemplateRef\fP (const TemplateDecl *Template, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create a reference to a template at the given location\&. "
.ti -1c
.RI "std::pair< const TemplateDecl *, SourceLocation > \fBclang::cxcursor::getCursorTemplateRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorNamespaceRef\fP (const NamedDecl *NS, SourceLocation Loc, CXTranslationUnit TU)"
.br
.ti -1c
.RI "std::pair< const NamedDecl *, SourceLocation > \fBclang::cxcursor::getCursorNamespaceRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorVariableRef\fP (const VarDecl *Var, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create a reference to a variable at the given location\&. "
.ti -1c
.RI "std::pair< const VarDecl *, SourceLocation > \fBclang::cxcursor::getCursorVariableRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorMemberRef\fP (const FieldDecl *Field, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create a reference to a field at the given location\&. "
.ti -1c
.RI "std::pair< const FieldDecl *, SourceLocation > \fBclang::cxcursor::getCursorMemberRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorCXXBaseSpecifier\fP (const CXXBaseSpecifier *B, CXTranslationUnit TU)"
.br
.RI "Create a CXX base specifier cursor\&. "
.ti -1c
.RI "const CXXBaseSpecifier * \fBclang::cxcursor::getCursorCXXBaseSpecifier\fP (CXCursor C)"
.br
.RI "Unpack a CXXBaseSpecifier cursor into a CXXBaseSpecifier\&. "
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakePreprocessingDirectiveCursor\fP (SourceRange Range, CXTranslationUnit TU)"
.br
.RI "Create a preprocessing directive cursor\&. "
.ti -1c
.RI "SourceRange \fBclang::cxcursor::getCursorPreprocessingDirective\fP (CXCursor C)"
.br
.RI "Unpack a given preprocessing directive to retrieve its source range\&. "
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeMacroDefinitionCursor\fP (const MacroDefinitionRecord *, CXTranslationUnit TU)"
.br
.RI "Create a macro definition cursor\&. "
.ti -1c
.RI "const MacroDefinitionRecord * \fBclang::cxcursor::getCursorMacroDefinition\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeMacroExpansionCursor\fP (MacroExpansion *, CXTranslationUnit TU)"
.br
.RI "Create a macro expansion cursor\&. "
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeMacroExpansionCursor\fP (MacroDefinitionRecord *, SourceLocation Loc, CXTranslationUnit TU)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeInclusionDirectiveCursor\fP (InclusionDirective *, CXTranslationUnit TU)"
.br
.RI "Create an inclusion directive cursor\&. "
.ti -1c
.RI "const InclusionDirective * \fBclang::cxcursor::getCursorInclusionDirective\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorLabelRef\fP (LabelStmt *Label, SourceLocation Loc, CXTranslationUnit TU)"
.br
.RI "Create a label reference at the given location\&. "
.ti -1c
.RI "std::pair< const LabelStmt *, SourceLocation > \fBclang::cxcursor::getCursorLabelRef\fP (CXCursor C)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorOverloadedDeclRef\fP (const OverloadExpr *E, CXTranslationUnit TU)"
.br
.RI "Create a overloaded declaration reference cursor for an expression\&. "
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorOverloadedDeclRef\fP (const Decl *D, SourceLocation Location, CXTranslationUnit TU)"
.br
.RI "Create a overloaded declaration reference cursor for a declaration\&. "
.ti -1c
.RI "CXCursor \fBclang::cxcursor::MakeCursorOverloadedDeclRef\fP (TemplateName Template, SourceLocation Location, CXTranslationUnit TU)"
.br
.RI "Create a overloaded declaration reference cursor for a template name\&. "
.ti -1c
.RI "std::pair< \fBOverloadedDeclRefStorage\fP, SourceLocation > \fBclang::cxcursor::getCursorOverloadedDeclRef\fP (CXCursor C)"
.br
.ti -1c
.RI "const Decl * \fBclang::cxcursor::getCursorDecl\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "const Expr * \fBclang::cxcursor::getCursorExpr\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "const Stmt * \fBclang::cxcursor::getCursorStmt\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "const Attr * \fBclang::cxcursor::getCursorAttr\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "ASTContext & \fBclang::cxcursor::getCursorContext\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "ASTUnit * \fBclang::cxcursor::getCursorASTUnit\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "CXTranslationUnit \fBclang::cxcursor::getCursorTU\fP (CXCursor Cursor)"
.br
.ti -1c
.RI "void \fBclang::cxcursor::getOverriddenCursors\fP (CXCursor cursor, SmallVectorImpl< CXCursor > &overridden)"
.br
.ti -1c
.RI "void * \fBclang::cxcursor::createOverridenCXCursorsPool\fP ()"
.br
.ti -1c
.RI "void \fBclang::cxcursor::disposeOverridenCXCursorsPool\fP (void *pool)"
.br
.RI "Dispose of the overridden CXCursors pool\&. "
.ti -1c
.RI "std::pair< int, SourceLocation > \fBclang::cxcursor::getSelectorIdentifierIndexAndLoc\fP (CXCursor)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::getSelectorIdentifierCursor\fP (int SelIdx, CXCursor cursor)"
.br
.ti -1c
.RI "CXCursor \fBclang::cxcursor::getTypeRefCursor\fP (CXCursor cursor)"
.br
.ti -1c
.RI "bool \fBclang::cxcursor::getDeclCursorUSR\fP (const Decl *D, SmallVectorImpl< char > &Buf)"
.br
.ti -1c
.RI "bool \fBclang::cxcursor::operator==\fP (CXCursor X, CXCursor Y)"
.br
.ti -1c
.RI "bool \fBclang::cxcursor::operator!=\fP (CXCursor X, CXCursor Y)"
.br
.ti -1c
.RI "bool \fBclang::cxcursor::isFirstInDeclGroup\fP (CXCursor C)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
