.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CXCursor\&.h'\fP
.br
\fC#include 'Index_Internal\&.h'\fP
.br
\fC#include 'clang/Index/IndexDataConsumer\&.h'\fP
.br
\fC#include 'clang/AST/DeclGroup\&.h'\fP
.br
\fC#include 'clang/AST/DeclObjC\&.h'\fP
.br
\fC#include 'llvm/ADT/DenseSet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::cxindex::ScratchAlloc\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::EntityInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::ContainerInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::DeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::ObjCContainerDeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::ObjCInterfaceDeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::ObjCProtocolDeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::ObjCCategoryDeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::ObjCPropertyDeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::CXXClassDeclInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::AttrInfo\fP"
.br
.ti -1c
.RI "struct \fBclang::cxindex::IBOutletCollectionInfo\fP"
.br
.ti -1c
.RI "class \fBclang::cxindex::AttrListInfo\fP"
.br
.ti -1c
.RI "class \fBclang::cxindex::CXIndexDataConsumer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxindex\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
