.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXIndexDataConsumer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CXIndexDataConsumer\&.h'\fP
.br
\fC#include 'CIndexDiagnostic\&.h'\fP
.br
\fC#include 'CXTranslationUnit\&.h'\fP
.br
\fC#include 'clang/AST/Attr\&.h'\fP
.br
\fC#include 'clang/AST/DeclCXX\&.h'\fP
.br
\fC#include 'clang/AST/DeclTemplate\&.h'\fP
.br
\fC#include 'clang/AST/DeclVisitor\&.h'\fP
.br
\fC#include 'clang/Frontend/ASTUnit\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
