.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXLoadedDiagnostic.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXLoadedDiagnostic.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CXLoadedDiagnostic\&.h'\fP
.br
\fC#include 'CXString\&.h'\fP
.br
\fC#include 'clang/Basic/Diagnostic\&.h'\fP
.br
\fC#include 'clang/Basic/FileManager\&.h'\fP
.br
\fC#include 'clang/Basic/LLVM\&.h'\fP
.br
\fC#include 'clang/Frontend/SerializedDiagnosticReader\&.h'\fP
.br
\fC#include 'clang/Frontend/SerializedDiagnostics\&.h'\fP
.br
\fC#include 'llvm/ADT/STLExtras\&.h'\fP
.br
\fC#include 'llvm/ADT/StringRef\&.h'\fP
.br
\fC#include 'llvm/ADT/Twine\&.h'\fP
.br
\fC#include 'llvm/Bitstream/BitstreamReader\&.h'\fP
.br
\fC#include 'llvm/Support/ErrorHandling\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCASE\fP(X)   case serialized_diags::X: return CXDiagnostic_##X;"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef llvm::DenseMap< unsigned, const char * > \fBStrings\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CXDiagnosticSet \fBclang_loadDiagnostics\fP (const char *file, enum CXLoadDiag_Error *error, CXString *errorString)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CASE(X)   case serialized_diags::X: return CXDiagnostic_##X;"

.SH "Typedef Documentation"
.PP 
.SS "typedef llvm::DenseMap<unsigned, const char *> \fBStrings\fP"

.PP
Definition at line 32 of file CXLoadedDiagnostic\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "CXDiagnosticSet clang_loadDiagnostics (const char * file, enum CXLoadDiag_Error * error, CXString * errorString)"

.PP
Definition at line 389 of file CXLoadedDiagnostic\&.cpp\&.
.PP
.nf
391                                                              {
392   DiagLoader L(error, errorString);
393   return L\&.load(file);
394 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
