.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXLoadedDiagnostic.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXLoadedDiagnostic.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CIndexDiagnostic\&.h'\fP
.br
\fC#include 'llvm/ADT/StringRef\&.h'\fP
.br
\fC#include 'clang/Basic/LLVM\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::CXLoadedDiagnostic\fP"
.br
.ti -1c
.RI "struct \fBclang::CXLoadedDiagnostic::Location\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
