.TH "CXModuleMapDescriptorImpl" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CXModuleMapDescriptorImpl
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBModuleName\fP"
.br
.ti -1c
.RI "std::string \fBUmbrellaHeader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file BuildSystem\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string CXModuleMapDescriptorImpl::ModuleName"

.PP
Definition at line 97 of file BuildSystem\&.cpp\&.
.SS "std::string CXModuleMapDescriptorImpl::UmbrellaHeader"

.PP
Definition at line 98 of file BuildSystem\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
