.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXSourceLocation.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXSourceLocation.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br
\fC#include 'clang/AST/ASTContext\&.h'\fP
.br
\fC#include 'clang/Basic/LangOptions\&.h'\fP
.br
\fC#include 'clang/Basic/SourceLocation\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxloc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CXSourceRange \fBclang::cxloc::translateSourceRange\fP (const SourceManager &SM, const LangOptions &LangOpts, const CharSourceRange &R)"
.br
.ti -1c
.RI "CharSourceRange \fBclang::cxloc::translateCXRangeToCharRange\fP (CXSourceRange R)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
