.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXStoredDiagnostic.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXStoredDiagnostic.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CIndexDiagnostic\&.h'\fP
.br
\fC#include 'CIndexer\&.h'\fP
.br
\fC#include 'CXTranslationUnit\&.h'\fP
.br
\fC#include 'CXSourceLocation\&.h'\fP
.br
\fC#include 'CXString\&.h'\fP
.br
\fC#include 'clang/Basic/DiagnosticIDs\&.h'\fP
.br
\fC#include 'clang/Frontend/ASTUnit\&.h'\fP
.br
\fC#include 'llvm/ADT/Twine\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
