.TH "CXTranslationUnitImpl" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CXTranslationUnitImpl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CXTranslationUnit\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclang::CIndexer\fP * \fBCIdx\fP"
.br
.ti -1c
.RI "clang::ASTUnit * \fBTheASTUnit\fP"
.br
.ti -1c
.RI "\fBclang::cxstring::CXStringPool\fP * \fBStringPool\fP"
.br
.ti -1c
.RI "void * \fBDiagnostics\fP"
.br
.ti -1c
.RI "void * \fBOverridenCursorsPool\fP"
.br
.ti -1c
.RI "clang::index::CommentToXMLConverter * \fBCommentToXML\fP"
.br
.ti -1c
.RI "unsigned \fBParsingOptions\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBArguments\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file CXTranslationUnit\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> CXTranslationUnitImpl::Arguments"

.PP
Definition at line 36 of file CXTranslationUnit\&.h\&.
.SS "\fBclang::CIndexer\fP* CXTranslationUnitImpl::CIdx"

.PP
Definition at line 29 of file CXTranslationUnit\&.h\&.
.SS "clang::index::CommentToXMLConverter* CXTranslationUnitImpl::CommentToXML"

.PP
Definition at line 34 of file CXTranslationUnit\&.h\&.
.SS "void* CXTranslationUnitImpl::Diagnostics"

.PP
Definition at line 32 of file CXTranslationUnit\&.h\&.
.SS "void* CXTranslationUnitImpl::OverridenCursorsPool"

.PP
Definition at line 33 of file CXTranslationUnit\&.h\&.
.SS "unsigned CXTranslationUnitImpl::ParsingOptions"

.PP
Definition at line 35 of file CXTranslationUnit\&.h\&.
.SS "\fBclang::cxstring::CXStringPool\fP* CXTranslationUnitImpl::StringPool"

.PP
Definition at line 31 of file CXTranslationUnit\&.h\&.
.SS "clang::ASTUnit* CXTranslationUnitImpl::TheASTUnit"

.PP
Definition at line 30 of file CXTranslationUnit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
