.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXTranslationUnit.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXTranslationUnit.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CLog\&.h'\fP
.br
\fC#include 'CXString\&.h'\fP
.br
\fC#include 'clang\-c/Index\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCXTranslationUnitImpl\fP"
.br
.ti -1c
.RI "struct \fBCXTargetInfoImpl\fP"
.br
.ti -1c
.RI "class \fBclang::cxtu::CXTUOwner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::index\fP"
.br
.ti -1c
.RI " \fBclang::cxtu\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG_BAD_TU\fP(TU)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCXTranslationUnitImpl\fP * \fBclang::cxtu::MakeCXTranslationUnit\fP (\fBCIndexer\fP *CIdx, std::unique_ptr< ASTUnit > AU)"
.br
.ti -1c
.RI "bool \fBclang::cxtu::isASTReadError\fP (ASTUnit *AU)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG_BAD_TU(TU)"
\fBValue:\fP
.PP
.nf
    do {                                                \
      LOG_FUNC_SECTION {                                \
        *Log << "called with a bad TU: " << TU;         \
      }                                                 \
    } while(false)
.fi
.PP
Definition at line 63 of file CXTranslationUnit\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
