.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/CXType.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/CXType.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br
\fC#include 'clang/AST/Type\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::cxtype\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CXType \fBclang::cxtype::MakeCXType\fP (QualType T, CXTranslationUnit TU)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
