.TH "lib/DataStorage.cpp" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DataStorage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DataStorage\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataStorage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
