.TH "lib/DataStorage.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DataStorage.h
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include 'Helper\&.cpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStatementRuntime\fP"
.br
.ti -1c
.RI "struct \fBMeasurementEvaluation\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr high_resolution_clock::time_point \fBinvalidTime\fP = high_resolution_clock::time_point::min( )"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr high_resolution_clock::time_point invalidTime = high_resolution_clock::time_point::min( )\fC [constexpr]\fP"

.PP
Definition at line 15 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::startEvent()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
