.TH "lib/DataStorage.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DataStorage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DataStorage\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataStorage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
