.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagTool.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagTool.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DiagTool\&.h'\fP
.br
\fC#include 'llvm/ADT/StringMap\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdiagtool\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef llvm::StringMap< \fBDiagTool\fP * > \fBToolMap\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "llvm::ManagedStatic< \fBDiagTools\fP > \fBdiagtool::diagTools\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef llvm::StringMap<\fBDiagTool\fP *> \fBToolMap\fP"

.PP
Definition at line 24 of file DiagTool\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
