.TH "diagtool::GroupRecord::group_iterator< RecordType >" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diagtool::GroupRecord::group_iterator< RecordType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DiagnosticNames\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef RecordType \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef const \fBvalue_type\fP & \fBreference\fP"
.br
.ti -1c
.RI "typedef const \fBvalue_type\fP * \fBpointer\fP"
.br
.ti -1c
.RI "typedef std::forward_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreference\fP \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBpointer\fP \fBoperator\->\fP () const"
.br
.ti -1c
.RI "short \fBgetID\fP () const"
.br
.ti -1c
.RI "\fBgroup_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBgroup_iterator\fP &Other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBgroup_iterator\fP &Other) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBGroupRecord\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RecordType>
.br
class diagtool::GroupRecord::group_iterator< RecordType >"

.PP
Definition at line 47 of file DiagnosticNames\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename RecordType > typedef std::ptrdiff_t \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::\fBdifference_type\fP"

.PP
Definition at line 61 of file DiagnosticNames\&.h\&.
.SS "template<typename RecordType > typedef std::forward_iterator_tag \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::\fBiterator_category\fP"

.PP
Definition at line 60 of file DiagnosticNames\&.h\&.
.SS "template<typename RecordType > typedef const \fBvalue_type\fP* \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::\fBpointer\fP"

.PP
Definition at line 59 of file DiagnosticNames\&.h\&.
.SS "template<typename RecordType > typedef const \fBvalue_type\fP& \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::\fBreference\fP"

.PP
Definition at line 58 of file DiagnosticNames\&.h\&.
.SS "template<typename RecordType > typedef RecordType \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::\fBvalue_type\fP"

.PP
Definition at line 57 of file DiagnosticNames\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename RecordType > short \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::getID () const\fC [inline]\fP"

.PP
Definition at line 68 of file DiagnosticNames\&.h\&.
.PP
.nf
68                                  {
69         return *CurrentID;
70       }
.fi
.SS "template<typename RecordType > bool \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::operator!= (const \fBgroup_iterator\fP< RecordType > & Other) const\fC [inline]\fP"

.PP
Definition at line 83 of file DiagnosticNames\&.h\&.
.PP
.nf
83                                                          {
84         return CurrentID != Other\&.CurrentID;
85       }
.fi
.SS "template<typename RecordType > \fBGroupRecord::diagnostics_iterator::reference\fP diagtool::GroupRecord::diagnostics_iterator::operator* () const\fC [inline]\fP"

.PP
Definition at line 108 of file DiagnosticNames\&.h\&.
.PP
.nf
108                                                 {
109     return getDiagnosticGroups()[*CurrentID];
110   }
.fi
.PP
References diagtool::getDiagnosticGroups()\&.
.PP
Referenced by diagtool::GroupRecord::group_iterator< RecordType >::operator\->()\&.
.SS "template<typename RecordType > \fBgroup_iterator\fP& \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::operator++ ()\fC [inline]\fP"

.PP
Definition at line 72 of file DiagnosticNames\&.h\&.
.PP
.nf
72                                    {
73         ++CurrentID;
74         if (*CurrentID == -1)
75           CurrentID = nullptr;
76         return *this;
77       }
.fi
.SS "template<typename RecordType > \fBpointer\fP \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::operator\-> () const\fC [inline]\fP"

.PP
Definition at line 64 of file DiagnosticNames\&.h\&.
.PP
.nf
64                                         {
65         return &operator*();
66       }
.fi
.PP
References diagtool::GroupRecord::group_iterator< RecordType >::operator*()\&.
.SS "template<typename RecordType > bool \fBdiagtool::GroupRecord::group_iterator\fP< RecordType >::operator== (const \fBgroup_iterator\fP< RecordType > & Other) const\fC [inline]\fP"

.PP
Definition at line 79 of file DiagnosticNames\&.h\&.
.PP
.nf
79                                                          {
80         return CurrentID == Other\&.CurrentID;
81       }
.fi
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename RecordType > friend struct \fBGroupRecord\fP\fC [friend]\fP"

.PP
Definition at line 50 of file DiagnosticNames\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
