.TH "diagtool::RegisterDiagTool< DIAGTOOL >" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diagtool::RegisterDiagTool< DIAGTOOL >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DiagTool\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegisterDiagTool\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename DIAGTOOL>
.br
class diagtool::RegisterDiagTool< DIAGTOOL >"

.PP
Definition at line 51 of file DiagTool\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename DIAGTOOL > \fBdiagtool::RegisterDiagTool\fP< DIAGTOOL >::\fBRegisterDiagTool\fP ()\fC [inline]\fP"

.PP
Definition at line 53 of file DiagTool\&.h\&.
.PP
.nf
53 { diagTools->registerTool(new DIAGTOOL()); }
.fi
.PP
References diagtool::diagTools\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
