.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/diagtool_main.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/diagtool_main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DiagTool\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 17 of file diagtool_main\&.cpp\&.
.PP
.nf
17                                  {
18   if (argc > 1)
19     if (DiagTool *tool = diagTools->getTool(argv[1]))
20       return tool->run(argc - 2, &argv[2], llvm::outs());
21 
22   llvm::errs() << "usage: diagtool <command> [<args>]\n\n";
23   diagTools->printCommands(llvm::errs());
24   return 1;    
25 }
.fi
.PP
References diagtool::diagTools\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
