.TH "diagtool::DiagnosticRecord" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diagtool::DiagnosticRecord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DiagnosticNames\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "llvm::StringRef \fBgetName\fP () const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBDiagnosticRecord\fP &Other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBNameStr\fP"
.br
.ti -1c
.RI "short \fBDiagID\fP"
.br
.ti -1c
.RI "uint8_t \fBNameLen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file DiagnosticNames\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "llvm::StringRef diagtool::DiagnosticRecord::getName () const\fC [inline]\fP"

.PP
Definition at line 23 of file DiagnosticNames\&.h\&.
.PP
.nf
23                                   {
24       return llvm::StringRef(NameStr, NameLen);
25     }
.fi
.PP
References NameLen, and NameStr\&.
.PP
Referenced by Reporter\&.TextParameter::getHTML(), Reporter\&.SelectionParameter::getHTML(), Reporter\&.ReporterParameter::getValue(), and operator<()\&.
.SS "bool diagtool::DiagnosticRecord::operator< (const \fBDiagnosticRecord\fP & Other) const\fC [inline]\fP"

.PP
Definition at line 27 of file DiagnosticNames\&.h\&.
.PP
.nf
27                                                         {
28       return getName() < Other\&.getName();
29     }
.fi
.PP
References getName()\&.
.SH "Member Data Documentation"
.PP 
.SS "short diagtool::DiagnosticRecord::DiagID"

.PP
Definition at line 20 of file DiagnosticNames\&.h\&.
.SS "uint8_t diagtool::DiagnosticRecord::NameLen"

.PP
Definition at line 21 of file DiagnosticNames\&.h\&.
.PP
Referenced by getName()\&.
.SS "const char* diagtool::DiagnosticRecord::NameStr"

.PP
Definition at line 19 of file DiagnosticNames\&.h\&.
.PP
Referenced by getName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
