.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.h
.SH SYNOPSIS
.br
.PP
\fC#include 'llvm/ADT/ArrayRef\&.h'\fP
.br
\fC#include 'llvm/ADT/StringRef\&.h'\fP
.br
\fC#include 'llvm/Support/DataTypes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdiagtool::DiagnosticRecord\fP"
.br
.ti -1c
.RI "struct \fBdiagtool::GroupRecord\fP"
.br
.ti -1c
.RI "class \fBdiagtool::GroupRecord::group_iterator< RecordType >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdiagtool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "llvm::ArrayRef< \fBDiagnosticRecord\fP > \fBdiagtool::getBuiltinDiagnosticsByName\fP ()"
.br
.RI "Get every diagnostic in the system, sorted by name\&. "
.ti -1c
.RI "const \fBDiagnosticRecord\fP & \fBdiagtool::getDiagnosticForID\fP (short DiagID)"
.br
.RI "Get a diagnostic by its ID\&. "
.ti -1c
.RI "llvm::ArrayRef< \fBGroupRecord\fP > \fBdiagtool::getDiagnosticGroups\fP ()"
.br
.RI "Get every diagnostic group in the system, sorted by name\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
