.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagTool.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagTool.h
.SH SYNOPSIS
.br
.PP
\fC#include 'llvm/ADT/StringRef\&.h'\fP
.br
\fC#include 'llvm/Support/ManagedStatic\&.h'\fP
.br
\fC#include 'llvm/Support/raw_ostream\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdiagtool::DiagTool\fP"
.br
.ti -1c
.RI "class \fBdiagtool::DiagTools\fP"
.br
.ti -1c
.RI "class \fBdiagtool::RegisterDiagTool< DIAGTOOL >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdiagtool\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEF_DIAGTOOL\fP(NAME,  DESC,  CLSNAME)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEF_DIAGTOOL(NAME, DESC, CLSNAME)"
\fBValue:\fP
.PP
.nf
namespace {\
class CLSNAME : public diagtool::DiagTool {\
public:\
  CLSNAME() : DiagTool(NAME, DESC) {}\
  virtual ~CLSNAME() {}\
  int run(unsigned argc, char *argv[], llvm::raw_ostream &out) override;\
};\
diagtool::RegisterDiagTool<CLSNAME> Register##CLSNAME;\
}
.fi
.PP
Definition at line 58 of file DiagTool\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
