.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/DiagnosticNames.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DiagnosticNames\&.h'\fP
.br
\fC#include 'clang/Basic/AllDiagnostics\&.h'\fP
.br
\fC#include 'llvm/ADT/STLExtras\&.h'\fP
.br
\fC#include 'clang/Basic/DiagnosticIndexName\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticCommonKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticCrossTUKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticDriverKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticFrontendKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticSerializationKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticLexKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticParseKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticASTKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticCommentKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticSemaKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticAnalysisKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticRefactoringKinds\&.inc'\fP
.br
\fC#include 'clang/Basic/DiagnosticGroups\&.inc'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDIAG_NAME_INDEX\fP(ENUM)   { #ENUM, diag::ENUM, STR_SIZE(#ENUM, uint8_t) },"
.br
.ti -1c
.RI "#define \fBDIAG\fP(ENUM,  CLASS,  DEFAULT_MAPPING,  DESC,  GROUP,  SFINAE,  NOWERROR,  SHOWINSYSHEADER,  DEFER,  CATEGORY)     { #ENUM, diag::ENUM, STR_SIZE(#ENUM, uint8_t) },"
.br
.ti -1c
.RI "#define \fBGET_DIAG_ARRAYS\fP"
.br
.ti -1c
.RI "#define \fBGET_DIAG_TABLE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DIAG(ENUM, CLASS, DEFAULT_MAPPING, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, DEFER, CATEGORY)     { #ENUM, diag::ENUM, STR_SIZE(#ENUM, uint8_t) },"

.SS "#define DIAG_NAME_INDEX(ENUM)   { #ENUM, diag::ENUM, STR_SIZE(#ENUM, uint8_t) },"

.SS "#define GET_DIAG_ARRAYS"

.PP
Definition at line 63 of file DiagnosticNames\&.cpp\&.
.SS "#define GET_DIAG_TABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
