.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/DummyClangFuzzer.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/DummyClangFuzzer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'llvm/FuzzMutate/FuzzerCLI\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBLLVMFuzzerTestOneInput\fP (const uint8_t *Data, size_t Size)"
.br
.ti -1c
.RI "int \fBLLVMFuzzerInitialize\fP (int *argc, char ***argv)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int LLVMFuzzerInitialize (int * argc, char *** argv)"

.PP
Definition at line 19 of file ClangFuzzer\&.cpp\&.
.PP
.nf
19 { return 0; }
.fi
.PP
Referenced by main()\&.
.SS "int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)"

.PP
Referenced by main()\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 17 of file DummyClangFuzzer\&.cpp\&.
.PP
.nf
17                                  {
18   return llvm::runFuzzerOnInputs(argc, argv, LLVMFuzzerTestOneInput,
19                                  LLVMFuzzerInitialize);
20 }
.fi
.PP
References LLVMFuzzerInitialize(), and LLVMFuzzerTestOneInput()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
