.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/emit-one.c" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/emit-one.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdiv\fP (int numerator, int denominator)"
.br
.ti -1c
.RI "void \fBdiv_test\fP ()"
.br
.ti -1c
.RI "int \fBdo_nothing\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int div (int numerator, int denominator)"

.PP
Definition at line 3 of file emit\-one\&.c\&.
.PP
.nf
4 {
5     return numerator / denominator;
6 }
.fi
.PP
Referenced by div_test()\&.
.SS "void div_test ()"

.PP
Definition at line 8 of file emit\-one\&.c\&.
.PP
.nf
9 {
10     int i = 0;
11     for (i = 0; i < 2; ++i)
12         assert(div(2 * i, i) == 2);
13 }
.fi
.PP
References div()\&.
.SS "int do_nothing ()"

.PP
Definition at line 15 of file emit\-one\&.c\&.
.PP
.nf
16 {
17     unsigned int i = 0;
18 
19     int k = 100;
20     int j = k + 1;
21 
22     return j;
23 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
