.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/emit-two.c" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/functional/src/emit-two.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbad_guy\fP (int *i)"
.br
.ti -1c
.RI "void \fBbad_guy_test\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int bad_guy (int * i)"

.PP
Definition at line 2 of file emit\-two\&.c\&.
.PP
.nf
3 {
4     *i = 9;
5     return *i;
6 }
.fi
.PP
Referenced by bad_guy_test()\&.
.SS "void bad_guy_test ()"

.PP
Definition at line 8 of file emit\-two\&.c\&.
.PP
.nf
9 {
10     int * ptr = 0;
11 
12     bad_guy(ptr);
13 }
.fi
.PP
References bad_guy()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
