.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangLLVMProtoFuzzer.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangLLVMProtoFuzzer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'cxx_loop_proto\&.pb\&.h'\fP
.br
\fC#include 'fuzzer\-initialize/fuzzer_initialize\&.h'\fP
.br
\fC#include 'handle\-llvm/handle_llvm\&.h'\fP
.br
\fC#include 'proto\-to\-llvm/loop_proto_to_llvm\&.h'\fP
.br
\fC#include 'src/libfuzzer/libfuzzer_macro\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_BINARY_PROTO_FUZZER\fP (const LoopFunction &input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file implements a function that compiles a single \fBLLVM\fP IR string as input and uses libprotobuf-mutator to find new inputs\&. This function is then linked into the Fuzzer library\&. 
.PP
Definition in file \fBExampleClangLLVMProtoFuzzer\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "DEFINE_BINARY_PROTO_FUZZER (const LoopFunction & input)"

.PP
Definition at line 24 of file ExampleClangLLVMProtoFuzzer\&.cpp\&.
.PP
.nf
24                                                       {
25   auto S = LoopFunctionToLLVMString(input);
26   HandleLLVM(S, GetCLArgs());
27 }
.fi
.PP
References clang_fuzzer::GetCLArgs(), clang_fuzzer::HandleLLVM(), and clang_fuzzer::LoopFunctionToLLVMString()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
