.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangLoopProtoFuzzer.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangLoopProtoFuzzer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'cxx_loop_proto\&.pb\&.h'\fP
.br
\fC#include 'fuzzer\-initialize/fuzzer_initialize\&.h'\fP
.br
\fC#include 'handle\-cxx/handle_cxx\&.h'\fP
.br
\fC#include 'proto\-to\-cxx/proto_to_cxx\&.h'\fP
.br
\fC#include 'src/libfuzzer/libfuzzer_macro\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_BINARY_PROTO_FUZZER\fP (const LoopFunction &input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file implements a function that runs Clang on a single input and uses libprotobuf-mutator to find new inputs\&. This function is then linked into the Fuzzer library\&. This file differs from ExampleClangProtoFuzzer in that it uses a different protobuf that includes C++ code with a single for loop\&. 
.PP
Definition in file \fBExampleClangLoopProtoFuzzer\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "DEFINE_BINARY_PROTO_FUZZER (const LoopFunction & input)"

.PP
Definition at line 26 of file ExampleClangLoopProtoFuzzer\&.cpp\&.
.PP
.nf
26                                                       {
27   auto S = LoopFunctionToString(input);
28   HandleCXX(S, GetCLArgs());
29 }
.fi
.PP
References clang_fuzzer::GetCLArgs(), clang_fuzzer::HandleCXX(), and clang_fuzzer::LoopFunctionToString()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
