.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangProtoFuzzer.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/ExampleClangProtoFuzzer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'cxx_proto\&.pb\&.h'\fP
.br
\fC#include 'handle\-cxx/handle_cxx\&.h'\fP
.br
\fC#include 'proto\-to\-cxx/proto_to_cxx\&.h'\fP
.br
\fC#include 'fuzzer\-initialize/fuzzer_initialize\&.h'\fP
.br
\fC#include 'src/libfuzzer/libfuzzer_macro\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_BINARY_PROTO_FUZZER\fP (const Function &input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file implements a function that runs Clang on a single input and uses libprotobuf-mutator to find new inputs\&. This function is then linked into the Fuzzer library\&. 
.PP
Definition in file \fBExampleClangProtoFuzzer\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "DEFINE_BINARY_PROTO_FUZZER (const Function & input)"

.PP
Definition at line 24 of file ExampleClangProtoFuzzer\&.cpp\&.
.PP
.nf
24                                                   {
25   auto S = FunctionToString(input);
26   HandleCXX(S, "\&./test\&.cc", GetCLArgs());
27 }
.fi
.PP
References clang_fuzzer::FunctionToString(), clang_fuzzer::GetCLArgs(), and clang_fuzzer::HandleCXX()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
