.TH "ExprEvalResult" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExprEvalResult
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~ExprEvalResult\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CXEvalResultKind \fBEvalType\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   unsigned long long \fBunsignedVal\fP"
.br
.ti -1c
.RI "   long long \fBintVal\fP"
.br
.ti -1c
.RI "   double \fBfloatVal\fP"
.br
.ti -1c
.RI "   char * \fBstringVal\fP"
.br
.ti -1c
.RI "} \fBEvalData\fP"
.br
.ti -1c
.RI "bool \fBIsUnsignedInt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3877 of file CIndex\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExprEvalResult::~ExprEvalResult ()\fC [inline]\fP"

.PP
Definition at line 3886 of file CIndex\&.cpp\&.
.PP
.nf
3886                     {
3887     if (EvalType != CXEval_UnExposed && EvalType != CXEval_Float &&
3888         EvalType != CXEval_Int) {
3889       delete[] EvalData\&.stringVal;
3890     }
3891   }
.fi
.SH "Member Data Documentation"
.PP 
.SS "union { \&.\&.\&. }  ExprEvalResult::EvalData"

.PP
Referenced by clang_EvalResult_getAsLongLong(), and clang_EvalResult_getAsUnsigned()\&.
.SS "CXEvalResultKind ExprEvalResult::EvalType"

.PP
Definition at line 3878 of file CIndex\&.cpp\&.
.SS "double ExprEvalResult::floatVal"

.PP
Definition at line 3882 of file CIndex\&.cpp\&.
.SS "long long ExprEvalResult::intVal"

.PP
Definition at line 3881 of file CIndex\&.cpp\&.
.PP
Referenced by clang_EvalResult_getAsLongLong(), and clang_EvalResult_getAsUnsigned()\&.
.SS "bool ExprEvalResult::IsUnsignedInt"

.PP
Definition at line 3885 of file CIndex\&.cpp\&.
.PP
Referenced by clang_EvalResult_getAsLongLong(), and clang_EvalResult_getAsUnsigned()\&.
.SS "char* ExprEvalResult::stringVal"

.PP
Definition at line 3883 of file CIndex\&.cpp\&.
.SS "unsigned long long ExprEvalResult::unsignedVal"

.PP
Definition at line 3880 of file CIndex\&.cpp\&.
.PP
Referenced by clang_EvalResult_getAsLongLong(), and clang_EvalResult_getAsUnsigned()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
