.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/FatalErrorHandler.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/FatalErrorHandler.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/FatalErrorHandler\&.h'\fP
.br
\fC#include 'llvm/Support/ErrorHandling\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclang_install_aborting_llvm_fatal_error_handler\fP (void)"
.br
.ti -1c
.RI "void \fBclang_uninstall_llvm_fatal_error_handler\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void clang_install_aborting_llvm_fatal_error_handler (void)"

.PP
Definition at line 23 of file FatalErrorHandler\&.cpp\&.
.PP
.nf
23                                                            {
24   llvm::remove_fatal_error_handler();
25   llvm::install_fatal_error_handler(aborting_fatal_error_handler, nullptr);
26 }
.fi
.SS "void clang_uninstall_llvm_fatal_error_handler (void)"

.PP
Definition at line 28 of file FatalErrorHandler\&.cpp\&.
.PP
.nf
28                                                     {
29   llvm::remove_fatal_error_handler();
30 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
