.TH "FileHandler::BundleInfo" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileHandler::BundleInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "StringRef \fBBundleID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file ClangOffloadBundler\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "StringRef FileHandler::BundleInfo::BundleID"

.PP
Definition at line 179 of file ClangOffloadBundler\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
