.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/FindDiagnosticID.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/FindDiagnosticID.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DiagTool\&.h'\fP
.br
\fC#include 'DiagnosticNames\&.h'\fP
.br
\fC#include 'clang/Basic/AllDiagnostics\&.h'\fP
.br
\fC#include 'llvm/Support/CommandLine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEF_DIAGTOOL\fP ('find\-diagnostic\-id', 'Print the id of the given diagnostic', FindDiagnosticID) using namespace clang"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DEF_DIAGTOOL ('find\-diagnostic\-id', 'Print the id of the given diagnostic', FindDiagnosticID)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
