.TH "Tests/Examples/ForLoops.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/Examples/ForLoops.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <thread>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 5 of file ForLoops\&.cpp\&.
.PP
.nf
5                {
6 
7     // Compound Statements
8     int i = 1;
9     i = 10 + i;
10     i++;
11 
12     // 10 ms
13     std::this_thread::sleep_for(std::chrono::microseconds (10));
14 
15     // 100 ms
16     for ( int j = 1; j <= 10; j++ ) {
17         std::this_thread::sleep_for(std::chrono::microseconds (5));
18         std::this_thread::sleep_for(std::chrono::microseconds (5));
19     }
20     // 1000 ms
21     for ( int j = 1; j <= 100; j++ ) {
22         std::this_thread::sleep_for(std::chrono::microseconds (5));
23         std::this_thread::sleep_for(std::chrono::microseconds (5));
24     }
25     // 10000 ms
26     for ( int j = 1; j <= 1000; j++ ) {
27         std::this_thread::sleep_for(std::chrono::microseconds (5));
28         std::this_thread::sleep_for(std::chrono::microseconds (5));
29     }
30     return 1;
31 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
