.TH "Tests/Examples/FunctionCallDecls.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/Examples/FunctionCallDecls.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 9 of file FunctionCallDecls\&.cpp\&.
.PP
.nf
9                {
10     test();
11     return 0;
12 }
.fi
.PP
References test()\&.
.SS "void test ()"

.PP
Definition at line 3 of file FunctionCallDecls\&.cpp\&.
.PP
.nf
3             {
4     int i = 0;
5     i = i + 2;
6     std::cout << i;
7 }
.fi
.PP
Referenced by main(), tests\&.unit\&.test_analyze\&.FilteringFlagsTest::test_arch(), tests\&.unit\&.test_shell\&.ShellTest::test_decode_encode_are_same(), tests\&.unit\&.test_compilation\&.SplitTest::test_detect_cxx_from_compiler_name(), tests\&.unit\&.test_shell\&.ShellTest::test_encode_decode_are_same(), tests\&.unit\&.test_compilation\&.SplitTest::test_filter_flags(), tests\&.unit\&.test_intercept\&.InterceptUtilTest::test_format_entry_filters_action(), tests\&.unit\&.test_intercept\&.InterceptUtilTest::test_format_entry_normalize_filename(), tests\&.unit\&.test_clang\&.ClangGetCheckersTest::test_is_active(), tests\&.unit\&.test_analyze\&.FilteringFlagsTest::test_language_captured(), tests\&.unit\&.test_analyze\&.AnalyzerTest::test_nodebug_macros_appended(), and tests\&.unit\&.test_compilation\&.SplitTest::test_source_file()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
