.TH "Tests/Examples/FunctionCallDecl.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/Examples/FunctionCallDecl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 7 of file FunctionCallDecl\&.cpp\&.
.PP
.nf
7                {
8     print();
9     return 0;
10 }
.fi
.PP
References print()\&.
.SS "void print ()"

.PP
Definition at line 3 of file FunctionCallDecl\&.cpp\&.
.PP
.nf
3              {
4     std::cout << "Hello World";
5 }
.fi
.PP
Referenced by ScanView\&.ScanViewServer::halt(), ScanView\&.ScanViewServer::handle_error(), ScanView\&.ScanViewRequestHandler::handle_exception(), clang\-format\-diff::main(), clang\-format::main(), clang\-rename::main(), main(), libscanbuild\&.arguments::print_active_checkers(), libscanbuild\&.arguments::print_checkers(), ScanView\&.ReporterThread::run(), clang\-format\-sublime\&.ClangFormatCommand::run(), ScanView\&.ScanViewRequestHandler::send_open_report(), and ScanView\&.ScanViewServer::serve_forever()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
