.TH "GetCursorData" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetCursorData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetCursorData\fP (SourceManager &SM, SourceLocation tokenBegin, CXCursor &outputCursor)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SourceLocation \fBTokenBeginLoc\fP"
.br
.ti -1c
.RI "bool \fBPointsAtMacroArgExpansion\fP"
.br
.ti -1c
.RI "bool \fBVisitedObjCPropertyImplDecl\fP"
.br
.ti -1c
.RI "SourceLocation \fBVisitedDeclaratorDeclStartLoc\fP"
.br
.ti -1c
.RI "CXCursor & \fBBestCursor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5723 of file CIndex\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GetCursorData::GetCursorData (SourceManager & SM, SourceLocation tokenBegin, CXCursor & outputCursor)\fC [inline]\fP"

.PP
Definition at line 5730 of file CIndex\&.cpp\&.
.PP
.nf
5732       : TokenBeginLoc(tokenBegin), BestCursor(outputCursor) {
5733     PointsAtMacroArgExpansion = SM\&.isMacroArgExpansion(tokenBegin);
5734     VisitedObjCPropertyImplDecl = false;
5735   }
.fi
.SH "Member Data Documentation"
.PP 
.SS "CXCursor& GetCursorData::BestCursor"

.PP
Definition at line 5728 of file CIndex\&.cpp\&.
.SS "bool GetCursorData::PointsAtMacroArgExpansion"

.PP
Definition at line 5725 of file CIndex\&.cpp\&.
.SS "SourceLocation GetCursorData::TokenBeginLoc"

.PP
Definition at line 5724 of file CIndex\&.cpp\&.
.SS "SourceLocation GetCursorData::VisitedDeclaratorDeclStartLoc"

.PP
Definition at line 5727 of file CIndex\&.cpp\&.
.SS "bool GetCursorData::VisitedObjCPropertyImplDecl"

.PP
Definition at line 5726 of file CIndex\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
