.TH "/Users/maximilian/clang-llvm/clang/tools/clang-format-vs/ClangFormat/GlobalSuppressions.cs" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-format-vs/ClangFormat/GlobalSuppressions.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
