.TH "HagnTool.h" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HagnTool.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang/AST/AST\&.h'\fP
.br
\fC#include 'clang/AST/ASTConsumer\&.h'\fP
.br
\fC#include 'clang/AST/ASTContext\&.h'\fP
.br
\fC#include 'clang/AST/RecursiveASTVisitor\&.h'\fP
.br
\fC#include 'clang/Frontend/ASTConsumers\&.h'\fP
.br
\fC#include 'clang/Frontend/CompilerInstance\&.h'\fP
.br
\fC#include 'clang/Frontend/FrontendActions\&.h'\fP
.br
\fC#include 'clang/Rewrite/Core/Rewriter\&.h'\fP
.br
\fC#include 'clang/Tooling/CommonOptionsParser\&.h'\fP
.br
\fC#include 'clang/Tooling/Tooling\&.h'\fP
.br
\fC#include 'llvm/Support/CommandLine\&.h'\fP
.br
\fC#include 'clang/Basic/TokenKinds\&.h'\fP
.br
\fC#include 'clang/Lex/Lexer\&.h'\fP
.br
\fC#include 'clang/AST/Stmt\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "Rewriter \fBrewriter\fP"
.br
.ti -1c
.RI "SourceLocation \fBinitializationLocation\fP"
.br
.ti -1c
.RI "SourceLocation \fBruntimeStartLocation\fP"
.br
.ti -1c
.RI "SourceLocation \fBsummaryLocation\fP"
.br
.ti -1c
.RI "string \fBstatementOption\fP = 'start'"
.br
.ti -1c
.RI "string \fBidentifierString\fP = 'Runtime,Scope,'"
.br
.ti -1c
.RI "int \fBinternalIdentifier\fP = 2"
.br
.ti -1c
.RI "bool \fBtransformationSuccess\fP = false"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string identifierString = 'Runtime,Scope,'"

.PP
Definition at line 42 of file HagnTool\&.h\&.
.PP
Referenced by DataStorage::DataStorage(), and traverseChildren()\&.
.SS "SourceLocation initializationLocation"

.PP
Definition at line 33 of file HagnTool\&.h\&.
.PP
Referenced by Visitor::VisitFunctionDecl()\&.
.SS "int internalIdentifier = 2"

.PP
Definition at line 43 of file HagnTool\&.h\&.
.PP
Referenced by traverseChildren()\&.
.SS "Rewriter rewriter"

.PP
Definition at line 30 of file HagnTool\&.h\&.
.PP
Referenced by traverseChildren(), Visitor::Visitor(), and Visitor::VisitStmt()\&.
.SS "SourceLocation runtimeStartLocation"

.PP
Definition at line 36 of file HagnTool\&.h\&.
.PP
Referenced by Visitor::VisitFunctionDecl()\&.
.SS "string statementOption = 'start'"

.PP
Definition at line 41 of file HagnTool\&.h\&.
.PP
Referenced by Visitor::VisitFunctionDecl(), and Visitor::VisitStmt()\&.
.SS "SourceLocation summaryLocation"

.PP
Definition at line 39 of file HagnTool\&.h\&.
.PP
Referenced by Visitor::VisitFunctionDecl()\&.
.SS "bool transformationSuccess = false"

.PP
Definition at line 44 of file HagnTool\&.h\&.
.PP
Referenced by traverseChildren()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
