.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/handle-cxx/handle_cxx.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/handle-cxx/handle_cxx.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'handle_cxx\&.h'\fP
.br
\fC#include 'clang/CodeGen/CodeGenAction\&.h'\fP
.br
\fC#include 'clang/Frontend/CompilerInstance\&.h'\fP
.br
\fC#include 'clang/Lex/PreprocessorOptions\&.h'\fP
.br
\fC#include 'clang/Tooling/Tooling\&.h'\fP
.br
\fC#include 'llvm/Option/Option\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
