.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/handle-llvm/handle_llvm.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/handle-llvm/handle_llvm.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang_fuzzer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclang_fuzzer::HandleLLVM\fP (const std::string &S, const std::vector< const char * > &ExtraArgs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
