.TH "lib/Helper.cpp" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Helper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhlibhelp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBhlibhelp::getUnit\fP (std::chrono::duration< double, std::nano > duration)"
.br
.ti -1c
.RI "string \fBhlibhelp::getUsageAsString\fP (double usage)"
.br
.ti -1c
.RI "double \fBhlibhelp::convertToSpecifiedUnit\fP (std::chrono::duration< double, std::nano > duration, string prefix)"
.br
.ti -1c
.RI "void \fBhlibhelp::printTableRow\fP (string identifier, string stmtClass, double duration, string unit, string scopeUsage, string totalUsage)"
.br
.ti -1c
.RI "void \fBhlibhelp::printTableSeparator\fP (int width, char separator, string escape)"
.br
.ti -1c
.RI "void \fBhlibhelp::printTableSeparator\fP (int width, string separator, string position, string escape)"
.br
.ti -1c
.RI "void \fBhlibhelp::printStatisticBanner\fP ()"
.br
.ti -1c
.RI "string * \fBhlibhelp::getSegmentsOfString\fP (string identifier)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
