.TH "lib/Helper.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Helper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhlibhelp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBhlibhelp::getUnit\fP (std::chrono::duration< double, std::nano > duration)"
.br
.ti -1c
.RI "string \fBhlibhelp::getUsageAsString\fP (double usage)"
.br
.ti -1c
.RI "double \fBhlibhelp::convertToSpecifiedUnit\fP (std::chrono::duration< double, std::nano > duration, string prefix)"
.br
.ti -1c
.RI "void \fBhlibhelp::printTableRow\fP (string identifier, string stmtClass, double duration, string unit, string scopeUsage, string totalUsage, string calls)"
.br
.ti -1c
.RI "void \fBhlibhelp::printTableSeparator\fP (int width, char separator, string escape)"
.br
.ti -1c
.RI "void \fBhlibhelp::printTableSeparator\fP (int width, string separator, string position, string escape)"
.br
.ti -1c
.RI "void \fBhlibhelp::printStatisticBanner\fP ()"
.br
.ti -1c
.RI "string * \fBhlibhelp::getSegmentsOfString\fP (string identifier)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
