.TH "ImportedASTFilesData" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportedASTFilesData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBfilenames\fP"
.br
.ti -1c
.RI "unsigned \fBnum_files\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3314 of file c\-index\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char** ImportedASTFilesData::filenames"

.PP
Definition at line 3315 of file c\-index\-test\&.c\&.
.SS "unsigned ImportedASTFilesData::num_files"

.PP
Definition at line 3316 of file c\-index\-test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
