.TH "IndexDataStringList_" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexDataStringList_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBIndexDataStringList_\fP * \fBnext\fP"
.br
.ti -1c
.RI "char \fBdata\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3350 of file c\-index\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char IndexDataStringList_::data[1]"

.PP
Definition at line 3352 of file c\-index\-test\&.c\&.
.SS "struct \fBIndexDataStringList_\fP* IndexDataStringList_::next"

.PP
Definition at line 3351 of file c\-index\-test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
