.TH "IndexData" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBcheck_prefix\fP"
.br
.ti -1c
.RI "int \fBfirst_check_printed\fP"
.br
.ti -1c
.RI "int \fBfail_for_error\fP"
.br
.ti -1c
.RI "int \fBabort\fP"
.br
.ti -1c
.RI "CXString \fBmain_filename\fP"
.br
.ti -1c
.RI "\fBImportedASTFilesData\fP * \fBimportedASTs\fP"
.br
.ti -1c
.RI "\fBIndexDataStringList\fP * \fBstrings\fP"
.br
.ti -1c
.RI "CXTranslationUnit \fBTU\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3355 of file c\-index\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "int IndexData::abort"

.PP
Definition at line 3359 of file c\-index\-test\&.c\&.
.SS "const char* IndexData::check_prefix"

.PP
Definition at line 3356 of file c\-index\-test\&.c\&.
.SS "int IndexData::fail_for_error"

.PP
Definition at line 3358 of file c\-index\-test\&.c\&.
.SS "int IndexData::first_check_printed"

.PP
Definition at line 3357 of file c\-index\-test\&.c\&.
.SS "\fBImportedASTFilesData\fP* IndexData::importedASTs"

.PP
Definition at line 3361 of file c\-index\-test\&.c\&.
.SS "CXString IndexData::main_filename"

.PP
Definition at line 3360 of file c\-index\-test\&.c\&.
.SS "\fBIndexDataStringList\fP* IndexData::strings"

.PP
Definition at line 3362 of file c\-index\-test\&.c\&.
.SS "CXTranslationUnit IndexData::TU"

.PP
Definition at line 3363 of file c\-index\-test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
