.TH "/Users/maximilian/clang-llvm/clang/tools/libclang/Index_Internal.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/libclang/Index_Internal.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang\-c/Index\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_CXCursorAndRangeVisitorBlock\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__has_feature\fP(x)   0"
.br
.ti -1c
.RI "#define \fBINVOKE_BLOCK2\fP(block,  arg1,  arg2)   block\->invoke(block, arg1, arg2)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_CXCursorAndRangeVisitorBlock\fP * \fBCXCursorAndRangeVisitorBlock\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRangeComparisonResult\fP { \fBRangeOverlap\fP, \fBRangeBefore\fP, \fBRangeAfter\fP }"
.br
.RI "The result of comparing two source ranges\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __has_feature(x)   0"

.PP
Definition at line 19 of file Index_Internal\&.h\&.
.SS "#define INVOKE_BLOCK2(block, arg1, arg2)   block\->invoke(block, arg1, arg2)"

.PP
Definition at line 30 of file Index_Internal\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_CXCursorAndRangeVisitorBlock\fP * \fBCXCursorAndRangeVisitorBlock\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRangeComparisonResult\fP"

.PP
The result of comparing two source ranges\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRangeOverlap \fP\fP
Either the ranges overlap or one of the ranges is invalid\&. 
.TP
\fB\fIRangeBefore \fP\fP
The first range ends before the second range starts\&. 
.TP
\fB\fIRangeAfter \fP\fP
The first range starts after the second range ends\&. 
.PP
Definition at line 43 of file Index_Internal\&.h\&.
.PP
.nf
43                            {
45   RangeOverlap,
46 
48   RangeBefore,
49 
51   RangeAfter
52 };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
