.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/intercept.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/intercept.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibscanbuild\&.intercept\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.intercept_build\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.capture\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.setup_environment\fP (args, destination)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.intercept_compiler_wrapper\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.intercept_compiler_wrapper_impl\fP (_, execution)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.write_exec_trace\fP (filename, entry)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.parse_exec_trace\fP (filename)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.format_entry\fP (exec_trace)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.is_preload_disabled\fP (platform)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.intercept\&.entry_hash\fP (entry)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlibscanbuild\&.intercept\&.GS\fP = chr(0x1d)"
.br
.ti -1c
.RI "\fBlibscanbuild\&.intercept\&.RS\fP = chr(0x1e)"
.br
.ti -1c
.RI "\fBlibscanbuild\&.intercept\&.US\fP = chr(0x1f)"
.br
.ti -1c
.RI "string \fBlibscanbuild\&.intercept\&.COMPILER_WRAPPER_CC\fP = 'intercept\-cc'"
.br
.ti -1c
.RI "string \fBlibscanbuild\&.intercept\&.COMPILER_WRAPPER_CXX\fP = 'intercept\-c++'"
.br
.ti -1c
.RI "string \fBlibscanbuild\&.intercept\&.TRACE_FILE_EXTENSION\fP = '\&.cmd'"
.br
.ti -1c
.RI "\fBlibscanbuild\&.intercept\&.WRAPPER_ONLY_PLATFORMS\fP = frozenset({'win32', 'cygwin'})"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
