.TH "Tests/Examples/IntroExample.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/Examples/IntroExample.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfoo\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void foo ()"

.PP
Definition at line 3 of file IntroExample\&.cpp\&.
.PP
.nf
3             {
4     int i = 0;
5     while ( i <= 10 ) { i++; }
6     while ( i <= 20 ) { i++; }
7     while ( i <= 30 ) { i++; }
8 
9     std::cout << i;
10 }
.fi
.PP
Referenced by main()\&.
.SS "int main (void)"

.PP
Definition at line 12 of file IntroExample\&.cpp\&.
.PP
.nf
12                {
13     foo();
14     return 0;
15 }
.fi
.PP
References foo()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
