.TH "libscanbuild.arguments.AppendCommaSeparated" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libscanbuild.arguments.AppendCommaSeparated
.SH SYNOPSIS
.br
.PP
.PP
Inherits argparse\&.Action\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__call__\fP (self, __parser, namespace, values, __option_string)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
 argparse Action class to support multiple comma separated lists. 
.fi
.PP
 
.PP
Definition at line 480 of file arguments\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def libscanbuild\&.arguments\&.AppendCommaSeparated\&.__call__ ( self,  __parser,  namespace,  values,  __option_string)"

.PP
Definition at line 483 of file arguments\&.py\&.
.PP
.nf
483     def __call__(self, __parser, namespace, values, __option_string):
484         # getattr(obj, attr, default) does not really returns default but none
485         if getattr(namespace, self\&.dest, None) is None:
486             setattr(namespace, self\&.dest, [])
487         # once it's fixed we can use as expected
488         actual = getattr(namespace, self\&.dest)
489         actual\&.extend(values\&.split(','))
490         setattr(namespace, self\&.dest, actual)
491 
492 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
