.TH "libscanbuild.clang.ClangErrorException" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libscanbuild.clang.ClangErrorException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBerror\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file clang\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def libscanbuild\&.clang\&.ClangErrorException\&.__init__ ( self,  error)"

.PP
Definition at line 23 of file clang\&.py\&.
.PP
.nf
23     def __init__(self, error):
24         self\&.error = error
25 
26 
.fi
.SH "Member Data Documentation"
.PP 
.SS "libscanbuild\&.clang\&.ClangErrorException\&.error"

.PP
Definition at line 24 of file clang\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
