.TH "LineCol" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineCol
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBline\fP"
.br
.ti -1c
.RI "unsigned \fBcol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 729 of file c\-index\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned LineCol::col"

.PP
Definition at line 731 of file c\-index\-test\&.c\&.
.SS "unsigned LineCol::line"

.PP
Definition at line 730 of file c\-index\-test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
