.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/ListWarnings.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/ListWarnings.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DiagTool\&.h'\fP
.br
\fC#include 'DiagnosticNames\&.h'\fP
.br
\fC#include 'clang/Basic/AllDiagnostics\&.h'\fP
.br
\fC#include 'clang/Basic/Diagnostic\&.h'\fP
.br
\fC#include 'llvm/ADT/StringMap\&.h'\fP
.br
\fC#include 'llvm/Support/Format\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEF_DIAGTOOL\fP ('list\-warnings', 'List warnings and their corresponding flags', ListWarnings) using namespace clang"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DEF_DIAGTOOL ('list\-warnings', 'List warnings and their corresponding flags', ListWarnings)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
