.TH "llvm::yaml::MappingTraits< UnsavedFileHash >" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::yaml::MappingTraits< UnsavedFileHash >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmapping\fP (IO &IO, UnsavedFileHash &Info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file cc1gen_reproducer_main\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void llvm::yaml::MappingTraits< UnsavedFileHash >::mapping (IO & IO, UnsavedFileHash & Info)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 54 of file cc1gen_reproducer_main\&.cpp\&.
.PP
.nf
54                                                      {
55     IO\&.mapRequired("name", Info\&.Name);
56     IO\&.mapRequired("md5", Info\&.MD5);
57   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
