.TH "llvm::yaml" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::yaml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMappingTraits< RenameAllInfo >\fP"
.br
.ti -1c
.RI "struct \fBMappingTraits< UnsavedFileHash >\fP"
.br
.ti -1c
.RI "struct \fBMappingTraits< ClangInvocationInfo >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
