.TH "llvm::yaml::MappingTraits< ClangInvocationInfo >" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::yaml::MappingTraits< ClangInvocationInfo >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmapping\fP (IO &IO, ClangInvocationInfo &Info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file cc1gen_reproducer_main\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void llvm::yaml::MappingTraits< ClangInvocationInfo >::mapping (IO & IO, ClangInvocationInfo & Info)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 61 of file cc1gen_reproducer_main\&.cpp\&.
.PP
.nf
61                                                          {
62     IO\&.mapRequired("toolchain", Info\&.Toolchain);
63     IO\&.mapOptional("libclang\&.operation", Info\&.LibclangOperation);
64     IO\&.mapOptional("libclang\&.opts", Info\&.LibclangOptions);
65     IO\&.mapRequired("args", Info\&.Arguments);
66     IO\&.mapOptional("invocation-args", Info\&.InvocationArguments);
67     IO\&.mapOptional("unsaved_file_hashes", Info\&.UnsavedFileHashes);
68   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
