.TH "LLVM.ClangFormat" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVM.ClangFormat
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOptionPageGrid\fP"
.br
.ti -1c
.RI "class \fBClangFormatPackage\fP"
.br
.ti -1c
.RI "class \fBGuidList\fP"
.br
.ti -1c
.RI "class \fBPkgCmdIDList\fP"
.br
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "A strongly-typed resource class, for looking up localized strings, etc\&. "
.ti -1c
.RI "class \fBRunningDocTableEventsDispatcher\fP"
.br
.ti -1c
.RI "class \fBVsix\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
