.TH "llvm::yaml::MappingTraits< RenameAllInfo >" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::yaml::MappingTraits< RenameAllInfo >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmapping\fP (IO &IO, \fBRenameAllInfo\fP &Info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specialized MappingTraits to describe how a \fBRenameAllInfo\fP is (de)serialized\&. 
.PP
Definition at line 55 of file ClangRename\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static void llvm::yaml::MappingTraits< \fBRenameAllInfo\fP >::mapping (IO & IO, \fBRenameAllInfo\fP & Info)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 56 of file ClangRename\&.cpp\&.
.PP
.nf
56                                                    {
57     IO\&.mapOptional("Offset", Info\&.Offset);
58     IO\&.mapOptional("QualifiedName", Info\&.QualifiedName);
59     IO\&.mapRequired("NewName", Info\&.NewName);
60   }
.fi
.PP
References RenameAllInfo::NewName, RenameAllInfo::Offset, and RenameAllInfo::QualifiedName\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
