.TH "LLVM.ClangFormat.OptionPageGrid" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVM.ClangFormat.OptionPageGrid
.SH SYNOPSIS
.br
.PP
.PP
Inherits DialogPage\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFallbackStyleConverter\fP"
.br
.ti -1c
.RI "class \fBFilenameConverter\fP"
.br
.ti -1c
.RI "class \fBStyleConverter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionPageGrid\fP \fBClone\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBStyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAssumeFilename\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFallbackStyle\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBSortIncludes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBFormatOnSave\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBFormatOnSaveFileExtensions\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file ClangFormatPackage\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBOptionPageGrid\fP LLVM\&.ClangFormat\&.OptionPageGrid\&.Clone ()\fC [inline]\fP"

.PP
Definition at line 44 of file ClangFormatPackage\&.cs\&.
.PP
.nf
45         {
46             // Use MemberwiseClone to copy value types\&.
47             var clone = (OptionPageGrid)MemberwiseClone();
48             return clone;
49         }
.fi
.SH "Property Documentation"
.PP 
.SS "string LLVM\&.ClangFormat\&.OptionPageGrid\&.AssumeFilename\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 141 of file ClangFormatPackage\&.cs\&.
.PP
.nf
142         {
143             get { return assumeFilename; }
144             set { assumeFilename = value; }
145         }
.fi
.SS "string LLVM\&.ClangFormat\&.OptionPageGrid\&.FallbackStyle\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 162 of file ClangFormatPackage\&.cs\&.
.PP
.nf
163         {
164             get { return fallbackStyle; }
165             set { fallbackStyle = value; }
166         }
.fi
.SS "bool LLVM\&.ClangFormat\&.OptionPageGrid\&.FormatOnSave\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 183 of file ClangFormatPackage\&.cs\&.
.PP
.nf
184         {
185             get { return formatOnSave; }
186             set { formatOnSave = value; }
187         }
.fi
.SS "string LLVM\&.ClangFormat\&.OptionPageGrid\&.FormatOnSaveFileExtensions\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 193 of file ClangFormatPackage\&.cs\&.
.PP
.nf
194         {
195             get { return formatOnSaveFileExtensions; }
196             set { formatOnSaveFileExtensions = value; }
197         }
.fi
.SS "bool LLVM\&.ClangFormat\&.OptionPageGrid\&.SortIncludes\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 172 of file ClangFormatPackage\&.cs\&.
.PP
.nf
173         {
174             get { return sortIncludes; }
175             set { sortIncludes = value; }
176         }
.fi
.SS "string LLVM\&.ClangFormat\&.OptionPageGrid\&.Style\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 103 of file ClangFormatPackage\&.cs\&.
.PP
.nf
104         {
105             get { return style; }
106             set { style = value; }
107         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
