.TH "LLVM.ClangFormat.ClangFormatPackage" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVM.ClangFormat.ClangFormatPackage
.SH SYNOPSIS
.br
.PP
.PP
Inherits Package\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 206 of file ClangFormatPackage\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void LLVM\&.ClangFormat\&.ClangFormatPackage\&.Initialize ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 212 of file ClangFormatPackage\&.cs\&.
.PP
.nf
213         {
214             base\&.Initialize();
215 
216             _runningDocTableEventsDispatcher = new RunningDocTableEventsDispatcher(this);
217             _runningDocTableEventsDispatcher\&.BeforeSave += OnBeforeSave;
218 
219             var commandService = GetService(typeof(IMenuCommandService)) as OleMenuCommandService;
220             if (commandService != null)
221             {
222                 {
223                     var menuCommandID = new CommandID(GuidList\&.guidClangFormatCmdSet, (int)PkgCmdIDList\&.cmdidClangFormatSelection);
224                     var menuItem = new MenuCommand(MenuItemCallback, menuCommandID);
225                     commandService\&.AddCommand(menuItem);
226                 }
227 
228                 {
229                     var menuCommandID = new CommandID(GuidList\&.guidClangFormatCmdSet, (int)PkgCmdIDList\&.cmdidClangFormatDocument);
230                     var menuItem = new MenuCommand(MenuItemCallback, menuCommandID);
231                     commandService\&.AddCommand(menuItem);
232                 }
233             }
234         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
