.TH "LLVM.ClangFormat.OptionPageGrid.StyleConverter" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LLVM.ClangFormat.OptionPageGrid.StyleConverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits TypeConverter\&.
.PP
Inherited by \fBLLVM\&.ClangFormat\&.OptionPageGrid\&.FallbackStyleConverter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStyleConverter\fP ()"
.br
.ti -1c
.RI "override bool \fBGetStandardValuesSupported\fP (ITypeDescriptorContext context)"
.br
.ti -1c
.RI "override StandardValuesCollection \fBGetStandardValues\fP (ITypeDescriptorContext context)"
.br
.ti -1c
.RI "override bool \fBCanConvertFrom\fP (ITypeDescriptorContext context, Type sourceType)"
.br
.ti -1c
.RI "override object \fBConvertFrom\fP (ITypeDescriptorContext context, System\&.Globalization\&.CultureInfo culture, object \fBvalue\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "ArrayList \fBvalues\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file ClangFormatPackage\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.StyleConverter ()\fC [inline]\fP"

.PP
Definition at line 54 of file ClangFormatPackage\&.cs\&.
.PP
.nf
55             {
56                 // Initializes the standard values list with defaults\&.
57                 values = new ArrayList(new string[] { "file", "Chromium", "Google", "LLVM", "Mozilla", "WebKit" });
58             }
.fi
.PP
References LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.values\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.CanConvertFrom (ITypeDescriptorContext context, Type sourceType)\fC [inline]\fP"

.PP
Definition at line 70 of file ClangFormatPackage\&.cs\&.
.PP
.nf
71             {
72                 if (sourceType == typeof(string))
73                     return true;
74 
75                 return base\&.CanConvertFrom(context, sourceType);
76             }
.fi
.SS "override object LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.ConvertFrom (ITypeDescriptorContext context, System\&.Globalization\&.CultureInfo culture, object value)\fC [inline]\fP"

.PP
Definition at line 78 of file ClangFormatPackage\&.cs\&.
.PP
.nf
79             {
80                 string s = value as string;
81                 if (s == null)
82                     return base\&.ConvertFrom(context, culture, value);
83 
84                 return value;
85             }
.fi
.PP
References value()\&.
.SS "override StandardValuesCollection LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.GetStandardValues (ITypeDescriptorContext context)\fC [inline]\fP"

.PP
Definition at line 65 of file ClangFormatPackage\&.cs\&.
.PP
.nf
66             {
67                 return new StandardValuesCollection(values);
68             }
.fi
.PP
References LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.values\&.
.SS "override bool LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.GetStandardValuesSupported (ITypeDescriptorContext context)\fC [inline]\fP"

.PP
Definition at line 60 of file ClangFormatPackage\&.cs\&.
.PP
.nf
61             {
62                 return true;
63             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "ArrayList LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.values\fC [protected]\fP"

.PP
Definition at line 53 of file ClangFormatPackage\&.cs\&.
.PP
Referenced by LLVM\&.ClangFormat\&.OptionPageGrid\&.FallbackStyleConverter\&.FallbackStyleConverter(), Reporter\&.SelectionParameter\&.getHTML(), LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.GetStandardValues(), and LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.StyleConverter()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
