.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-llvm/loop_proto_to_llvm_main.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-llvm/loop_proto_to_llvm_main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <streambuf>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'loop_proto_to_llvm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 21 of file loop_proto_to_llvm_main\&.cpp\&.
.PP
.nf
21                                 {
22   for (int i = 1; i < argc; i++) {
23     std::fstream in(argv[i]);
24     std::string str((std::istreambuf_iterator<char>(in)),
25                     std::istreambuf_iterator<char>());
26     std::cout << ";; " << argv[i] << std::endl;
27     std::cout << clang_fuzzer::LoopProtoToLLVM(
28         reinterpret_cast<const uint8_t *>(str\&.data()), str\&.size());
29   }
30 }
.fi
.PP
References clang_fuzzer::LoopProtoToLLVM()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
