.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-llvm/loop_proto_to_llvm.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-llvm/loop_proto_to_llvm.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang_fuzzer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBclang_fuzzer::LoopFunctionToLLVMString\fP (const LoopFunction &input)"
.br
.ti -1c
.RI "std::string \fBclang_fuzzer::LoopProtoToLLVM\fP (const uint8_t *data, size_t size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
