.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-cxx/loop_proto_to_cxx.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-cxx/loop_proto_to_cxx.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'cxx_loop_proto\&.pb\&.h'\fP
.br
\fC#include 'proto_to_cxx\&.h'\fP
.br
\fC#include <google/protobuf/text_format\&.h>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang_fuzzer::InnerLoop\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang_fuzzer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const BinaryOp &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const StatementSeq &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Const &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const VarRef &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Rvalue &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const AssignmentStatement &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Statement &x)"
.br
.ti -1c
.RI "void \fBclang_fuzzer::NestedLoopToString\fP (std::ostream &os, const LoopFunction &x)"
.br
.ti -1c
.RI "void \fBclang_fuzzer::SingleLoopToString\fP (std::ostream &os, const LoopFunction &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const LoopFunction &x)"
.br
.ti -1c
.RI "std::string \fBclang_fuzzer::LoopFunctionToString\fP (const LoopFunction &input)"
.br
.ti -1c
.RI "std::string \fBclang_fuzzer::LoopProtoToCxx\fP (const uint8_t *data, size_t size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
