.TH "MapExtDefNamesAction" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapExtDefNamesAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits clang::ASTFrontendAction\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::unique_ptr< ASTConsumer > \fBCreateASTConsumer\fP (CompilerInstance &CI, llvm::StringRef) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file ClangExtDefMapGen\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr<ASTConsumer> MapExtDefNamesAction::CreateASTConsumer (CompilerInstance & CI, llvm::StringRef)\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 106 of file ClangExtDefMapGen\&.cpp\&.
.PP
.nf
107                                                                          {
108     return std::make_unique<MapExtDefNamesConsumer>(CI\&.getASTContext());
109   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
