.TH "MapExtDefNamesConsumer" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapExtDefNamesConsumer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ASTConsumer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapExtDefNamesConsumer\fP (ASTContext &Context)"
.br
.ti -1c
.RI "\fB~MapExtDefNamesConsumer\fP ()"
.br
.ti -1c
.RI "void \fBHandleTranslationUnit\fP (ASTContext &Context) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file ClangExtDefMapGen\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MapExtDefNamesConsumer::MapExtDefNamesConsumer (ASTContext & Context)\fC [inline]\fP"

.PP
Definition at line 36 of file ClangExtDefMapGen\&.cpp\&.
.PP
.nf
37       : Ctx(Context), SM(Context\&.getSourceManager()) {}
.fi
.SS "MapExtDefNamesConsumer::~MapExtDefNamesConsumer ()\fC [inline]\fP"

.PP
Definition at line 39 of file ClangExtDefMapGen\&.cpp\&.
.PP
.nf
39                             {
40     // Flush results to standard output\&.
41     llvm::outs() << createCrossTUIndexString(Index);
42   }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void MapExtDefNamesConsumer::HandleTranslationUnit (ASTContext & Context)\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 44 of file ClangExtDefMapGen\&.cpp\&.
.PP
.nf
44                                                            {
45     handleDecl(Context\&.getTranslationUnitDecl());
46   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
