.TH "MeasurementEvaluation" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeasurementEvaluation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidentifier\fP"
.br
.ti -1c
.RI "std::chrono::duration< double, std::nano > \fBduration\fP"
.br
.ti -1c
.RI "double \fBtotalUsage\fP"
.br
.ti -1c
.RI "double \fBscopeUsage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file DataStorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::chrono::duration<double, std::nano> MeasurementEvaluation::duration"

.PP
Definition at line 22 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print()\&.
.SS "string MeasurementEvaluation::identifier"

.PP
Definition at line 21 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print()\&.
.SS "double MeasurementEvaluation::scopeUsage"

.PP
Definition at line 24 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print()\&.
.SS "double MeasurementEvaluation::totalUsage"

.PP
Definition at line 23 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
