.TH "Tests/output_program.cpp" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/output_program.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./lib/DataStorage\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDataStorage\fP \fBdataStorage\fP ('Runtime,Scope,CustomCompoundStmt InterID2,ForStmt 2086992,CallExpr 2087015,CustomCompoundStmt InterID6')"
.br
.ti -1c
.RI "void \fBfibonacci\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDataStorage\fP dataStorage (' Runtime, Scope, CustomCompoundStmt InterID2, ForStmt 2086992, CallExpr 2087015, CustomCompoundStmt InterID6')"

.PP
Referenced by main()\&.
.SS "void fibonacci ()"

.PP
Definition at line 3 of file output_program\&.cpp\&.
.PP
.nf
3                                                                                                                                                    {
4     double n, t1 = 0, t2 = 1, nextTerm = 0;
5     n = 100;
6 
7     std::cout << "Fibonacci Series: ";
8 
9     for (int i = 1; i <= n; ++i) {
10         if(i == 1) {
11             std::cout << t1 << ", ";
12             continue;
13         }
14         if(i == 2) {
15             std::cout << t2 << ", ";
16             continue;
17         }
18         nextTerm = t1 + t2;
19         t1 = t2;
20         t2 = nextTerm;
21 
22         std::cout << nextTerm << ", ";
23     }
24 }
.fi
.PP
Referenced by main()\&.
.SS "int main (void)"

.PP
Definition at line 26 of file output_program\&.cpp\&.
.PP
.nf
26                {
27 dataStorage\&.startEvent(0);
28 
29     dataStorage\&.startEvent(2);
30 int i = 10;
31     double e = 54783498;
32     double d = 54783498;
33     double c = 54783498;
34     double x = e+d+c;
35     double z = x*2;
36     double zy = x*2;
37     zy++;
38     zy++;
39     zy++;
40     zy++;
41     zy++;
42     zy++;
43     zy++;
44     zy++;
45     zy++;
46     zy++;
47     zy++;
48     zy++;
49     zy++;
50     zy++;
51     zy++;
52     zy++;
53     zy++;
54     zy++;
55     zy++;
56     zy++;
57     zy++;
58     e = z;
59     i++;
60 
61     dataStorage\&.endEvent(2);
62 dataStorage\&.startEvent(3);
63 for ( int j = 0; j < 1000000; ++j ) {
64         i++;
65         i++;
66         i++;
67         i++;
68         i++;
69     }
70 dataStorage\&.endEvent(3);
71 
72     dataStorage\&.startEvent(4);
73 fibonacci();
74 dataStorage\&.endEvent(4);
75 
76     dataStorage\&.startEvent(5);
77 double cc = 54783498;
78     double xx = e+d+c;
79     double zz = x*2;
80     cc++;
81     xx++;
82     zz++;
83     zy++;
84 dataStorage\&.endEvent(5);
85 
86     dataStorage\&.endEvent(0);
87 dataStorage\&.print();return 0;
88 }
.fi
.PP
References dataStorage(), DataStorage::endEvent(), fibonacci(), DataStorage::print(), and DataStorage::startEvent()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
