.TH "Tests/GTime Test Cases/Performance_Fibonacci_Without_Counter.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/GTime Test Cases/Performance_Fibonacci_Without_Counter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 3 of file Performance_Fibonacci_Without_Counter\&.cpp\&.
.PP
.nf
3                {
4     double n, t1 = 0, t2 = 1, nextTerm = 0;
5     n = 1000;
6 
7     std::cout << "Fibonacci Series: ";
8 
9     for (int i = 1; i <= n; ++i) {
10         if(i == 1) {
11             std::cout << t1;
12             std::cout << ", ";
13         }
14         else if(i == 2) {
15             std::cout << t2;
16             std::cout << ", ";
17         }
18         nextTerm = t1 + t2;
19         t1 = t2;
20         t2 = nextTerm;
21 
22         std::cout << nextTerm << ", ";
23     }
24 
25     return 0;
26 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
