.TH "Tests/GTime Test Cases/Performance_Password_With_Counter_2.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/GTime Test Cases/Performance_Password_With_Counter_2.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./lib/DataStorage\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDataStorage\fP \fBdataStorage\fP ('Runtime,Scope,ForStmt 2219597,CXXMemberCallExpr 2219614,CXXMemberCallExpr 2219644,CXXMemberCallExpr 2219662')"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDataStorage\fP dataStorage (' Runtime, Scope, ForStmt 2219597, CXXMemberCallExpr 2219614, CXXMemberCallExpr 2219644, CXXMemberCallExpr 2219662')"

.SS "int main (void)"

.PP
Definition at line 6 of file Performance_Password_With_Counter_2\&.cpp\&.
.PP
.nf
6                {
7 dataStorage\&.startEvent(0);
8     std::vector <std::string> passwordStorage;
9     std::string password;
10     char current;
11 
12     dataStorage\&.startEvent(1);
13 for (int passwordCount = 0; passwordCount < 1000000; passwordCount++) {
14         dataStorage\&.startEvent(2);
15 for (int sectionCount = 0; sectionCount < 3; sectionCount++) {
16             for (int sectionLength = 0; sectionLength < 6; sectionLength++) {
17                 char lowerCase = rand() % 26 + 'a';
18                 char upperCase = rand() % 26 + 'A';
19                 char number = rand() % 10 + '0';
20 
21                 char randomChoice = (rand() % 100 + 1);
22                 if (randomChoice <= 40) {
23                     current = lowerCase;
24                 } else if (randomChoice <= 80) {
25                     current = upperCase;
26                 } else {
27                     current = number;
28                 }
29                 password += current;
30             }
31             password += '-';
32         }
33 dataStorage\&.endEvent(2);
34         dataStorage\&.startEvent(3);
35 password\&.pop_back();
36 dataStorage\&.endEvent(3);
37         dataStorage\&.startEvent(4);
38 passwordStorage\&.push_back(password);
39 dataStorage\&.endEvent(4);
40         dataStorage\&.startEvent(5);
41 password\&.clear();
42 dataStorage\&.endEvent(5);
43     }
44 dataStorage\&.endEvent(1);
45 
46     std::sort(passwordStorage\&.begin(), passwordStorage\&.end());
47     passwordStorage\&.erase(std::unique(passwordStorage\&.begin(),
48                                             passwordStorage\&.end()),
49                           passwordStorage\&.end());
50 
51     for (std::string currentPassword: passwordStorage) {
52         std::cout << currentPassword << '\n';
53     }
54 
55     dataStorage\&.endEvent(0);
56 dataStorage\&.print();return 0;
57 }
.fi
.PP
References dataStorage(), DataStorage::endEvent(), DataStorage::print(), and DataStorage::startEvent()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
