.TH "Tests/CleanTime Test Cases/Performance_ForLoops_With_Counter.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/CleanTime Test Cases/Performance_ForLoops_With_Counter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include '\&.\&./lib/DataStorage\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDataStorage\fP \fBdataStorage\fP ('Runtime,Scope,ForStmt 2192956,ForStmt 2193096,ForStmt 2225085')"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDataStorage\fP dataStorage (' Runtime, Scope, ForStmt 2192956, ForStmt 2193096, ForStmt 2225085')"

.PP
Referenced by main()\&.
.SS "int main (void)"

.PP
Definition at line 5 of file Performance_ForLoops_With_Counter\&.cpp\&.
.PP
.nf
5                {
6 dataStorage\&.startEvent(0);
7     dataStorage\&.startEvent(2);
8 for ( int i = 1; i <= 1000; i++ ) {
9         std::cout << "Hello World";
10     }
11 dataStorage\&.endEvent(2);
12     dataStorage\&.startEvent(3);
13 for ( int i = 1; i <= 1000; i++ ) {
14         int numberA = 892346;
15         int numberB = 384378;
16         int numberC = numberA * numberB;
17     }
18 dataStorage\&.endEvent(3);
19     dataStorage\&.startEvent(4);
20 for ( int i = 1; i <= 1000; i++ ) {
21         std::vector<std::string> shoppingList;
22         shoppingList\&.push_back("Milk");
23         shoppingList\&.push_back("Eggs");
24         shoppingList\&.push_back("Meat");
25         shoppingList\&.push_back("Water");
26         shoppingList\&.push_back("Sugar");
27         shoppingList\&.push_back("Flour");
28         shoppingList\&.push_back("Salt");
29         std::sort( shoppingList\&.begin( ), shoppingList\&.end( ));
30     }
31 dataStorage\&.endEvent(4);
32     dataStorage\&.endEvent(0);
33 dataStorage\&.print();return 0;
34 }
.fi
.PP
References dataStorage(), DataStorage::endEvent(), DataStorage::print(), and DataStorage::startEvent()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
