.TH "Tests/CleanTime Test Cases/Performance_ForLoops_Without_Counter.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/CleanTime Test Cases/Performance_ForLoops_Without_Counter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include '\&.\&./lib/DataStorage\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 5 of file Performance_ForLoops_Without_Counter\&.cpp\&.
.PP
.nf
5                {
6     DataStorage dataStorage("Runtime,Scope");
7     dataStorage\&.startEvent(0);
8     for ( int i = 1; i <= 1000; i++ ) {
9         std::cout << "Hello World";
10     }
11     for ( int i = 1; i <= 1000; i++ ) {
12         int numberA = 892346;
13         int numberB = 384378;
14         int numberC = numberA * numberB;
15     }
16     for ( int i = 1; i <= 1000; i++ ) {
17         std::vector<std::string> shoppingList;
18         shoppingList\&.push_back("Milk");
19         shoppingList\&.push_back("Eggs");
20         shoppingList\&.push_back("Meat");
21         shoppingList\&.push_back("Water");
22         shoppingList\&.push_back("Sugar");
23         shoppingList\&.push_back("Flour");
24         shoppingList\&.push_back("Salt");
25         std::sort( shoppingList\&.begin( ), shoppingList\&.end( ));
26     }
27 
28     dataStorage\&.endEvent(0);
29     dataStorage\&.print();
30     return 0;
31 }
.fi
.PP
References dataStorage(), DataStorage::endEvent(), DataStorage::print(), and DataStorage::startEvent()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
