.TH "Tests/GTime Test Cases/Performance_Loops_Without_Counter.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/GTime Test Cases/Performance_Loops_Without_Counter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 4 of file Performance_Loops_Without_Counter\&.cpp\&.
.PP
.nf
4                {
5     for ( int i = 1; i <= 1000; i++ ) {
6         std::cout << "Hello World";
7     }
8     for ( int i = 1; i <= 1000; i++ ) {
9         int numberA = 892346;
10         int numberB = 384378;
11         int numberC = numberA * numberB;
12     }
13     for ( int i = 1; i <= 1000; i++ ) {
14         std::vector<std::string> shoppingList;
15         shoppingList\&.push_back("Milk");
16         shoppingList\&.push_back("Eggs");
17         shoppingList\&.push_back("Meat");
18         shoppingList\&.push_back("Water");
19         shoppingList\&.push_back("Sugar");
20         shoppingList\&.push_back("Flour");
21         shoppingList\&.push_back("Salt");
22         std::sort( shoppingList\&.begin( ), shoppingList\&.end( ));
23     }
24     return 0;
25 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
