.TH "Tests/GTime Test Cases/Performance_Password_Without_Counter.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/GTime Test Cases/Performance_Password_Without_Counter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 5 of file Performance_Password_Without_Counter\&.cpp\&.
.PP
.nf
5                {
6     std::vector <std::string> passwordStorage;
7     std::string password;
8     char current;
9 
10     for (int passwordCount = 0; passwordCount < 1000000; passwordCount++) {
11         for (int sectionCount = 0; sectionCount < 3; sectionCount++) {
12             for (int sectionLength = 0; sectionLength < 6; sectionLength++) {
13                 char lowerCase = rand() % 26 + 'a';
14                 char upperCase = rand() % 26 + 'A';
15                 char number = rand() % 10 + '0';
16 
17                 char randomChoice = (rand() % 100 + 1);
18                 if (randomChoice <= 40) {
19                     current = lowerCase;
20                 } else if (randomChoice <= 80) {
21                     current = upperCase;
22                 } else {
23                     current = number;
24                 }
25                 password += current;
26             }
27             password += '-';
28         }
29         password\&.pop_back();
30         passwordStorage\&.push_back(password);
31         password\&.clear();
32     }
33 
34     std::sort(passwordStorage\&.begin(), passwordStorage\&.end());
35     passwordStorage\&.erase(std::unique(passwordStorage\&.begin(),
36                                             passwordStorage\&.end()),
37                           passwordStorage\&.end());
38 
39     for (std::string currentPassword: passwordStorage) {
40         std::cout << currentPassword << '\n';
41     }
42 
43     return 0;
44 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
