.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-cxx/proto_to_cxx_main.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-cxx/proto_to_cxx_main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <streambuf>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'proto_to_cxx\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 19 of file proto_to_cxx_main\&.cpp\&.
.PP
.nf
19                                 {
20   for (int i = 1; i < argc; i++) {
21     std::fstream in(argv[i]);
22     std::string str((std::istreambuf_iterator<char>(in)),
23                     std::istreambuf_iterator<char>());
24     std::cout << "// " << argv[i] << std::endl;
25     std::cout << clang_fuzzer::ProtoToCxx(
26         reinterpret_cast<const uint8_t *>(str\&.data()), str\&.size());
27   }
28 }
.fi
.PP
References clang_fuzzer::ProtoToCxx()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
