.TH "/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-cxx/proto_to_cxx.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-fuzzer/proto-to-cxx/proto_to_cxx.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'proto_to_cxx\&.h'\fP
.br
\fC#include 'cxx_proto\&.pb\&.h'\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang_fuzzer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const BinaryOp &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const StatementSeq &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Const &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const VarRef &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Lvalue &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Rvalue &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const AssignmentStatement &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const IfElse &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const While &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Statement &x)"
.br
.ti -1c
.RI "std::ostream & \fBclang_fuzzer::operator<<\fP (std::ostream &os, const Function &x)"
.br
.ti -1c
.RI "std::string \fBclang_fuzzer::FunctionToString\fP (const Function &input)"
.br
.ti -1c
.RI "std::string \fBclang_fuzzer::ProtoToCxx\fP (const uint8_t *data, size_t size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
