.TH "RenameAllInfo" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenameAllInfo \- An oldname -> newname rename\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBOffset\fP = 0"
.br
.ti -1c
.RI "std::string \fBQualifiedName\fP"
.br
.ti -1c
.RI "std::string \fBNewName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An oldname -> newname rename\&. 
.PP
Definition at line 42 of file ClangRename\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string RenameAllInfo::NewName"

.PP
Definition at line 45 of file ClangRename\&.cpp\&.
.PP
Referenced by llvm::yaml::MappingTraits< RenameAllInfo >::mapping()\&.
.SS "unsigned RenameAllInfo::Offset = 0"

.PP
Definition at line 43 of file ClangRename\&.cpp\&.
.PP
Referenced by llvm::yaml::MappingTraits< RenameAllInfo >::mapping()\&.
.SS "std::string RenameAllInfo::QualifiedName"

.PP
Definition at line 44 of file ClangRename\&.cpp\&.
.PP
Referenced by llvm::yaml::MappingTraits< RenameAllInfo >::mapping()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
