.TH "Reporter.BugzillaReporter" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter.BugzillaReporter
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBgetName\fP (self)"
.br
.ti -1c
.RI "def \fBgetParameters\fP (self)"
.br
.ti -1c
.RI "def \fBfileReport\fP (self, report, parameters)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file Reporter\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def Reporter\&.BugzillaReporter\&.fileReport ( self,  report,  parameters)"

.PP
Definition at line 153 of file Reporter\&.py\&.
.PP
.nf
153     def fileReport(self, report, parameters):
154         raise NotImplementedError
155  
156 
.fi
.SS "def Reporter\&.BugzillaReporter\&.getName ( self)"

.PP
Definition at line 147 of file Reporter\&.py\&.
.PP
.nf
147     def getName(self):
148         return 'Bugzilla'
149     
.fi
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), Reporter\&.SelectionParameter\&.getHTML(), and Reporter\&.ReporterParameter\&.getValue()\&.
.SS "def Reporter\&.BugzillaReporter\&.getParameters ( self)"

.PP
Definition at line 150 of file Reporter\&.py\&.
.PP
.nf
150     def getParameters(self):
151         return [TextParameter(x) for x in ['URL','Product']]
152 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
