.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/report.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/report.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibscanbuild\&.report\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.document\fP (args)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.assemble_cover\fP (args, prefix, fragments)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.bug_summary\fP (output_dir, bug_counter)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.bug_report\fP (output_dir, prefix)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.crash_report\fP (output_dir, prefix)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.read_crashes\fP (output_dir)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.read_bugs\fP (output_dir, html)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.merge_sarif_files\fP (output_dir, sort_files=False)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.parse_bug_plist\fP (filename)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.parse_bug_html\fP (filename)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.parse_crash\fP (filename)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.category_type_name\fP (bug)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.create_counters\fP ()"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.prettify_bug\fP (prefix, output_dir)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.prettify_crash\fP (prefix, output_dir)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.copy_resource_files\fP (output_dir)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.encode_value\fP (container, key, encode)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.chop\fP (prefix, filename)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.escape\fP (text)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.reindent\fP (text, indent)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.comment\fP (name, opts=dict())"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.commonprefix_from\fP (filename)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.report\&.commonprefix\fP (files)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
