.TH "Reporter.SelectionParameter" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter.SelectionParameter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBReporter\&.ReporterParameter\fP\&.
.PP
Inherited by \fBReporter\&.RadarClassificationParameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, n, \fBvalues\fP)"
.br
.ti -1c
.RI "def \fBgetHTML\fP (self, r, bugtype, getConfigOption)"
.br
.ti -1c
.RI "def \fBgetName\fP (self)"
.br
.ti -1c
.RI "def \fBgetValue\fP (self, r, bugtype, getConfigOption)"
.br
.ti -1c
.RI "def \fBsaveConfigValue\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalues\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file Reporter\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Reporter\&.SelectionParameter\&.__init__ ( self,  n,  values)"

.PP
Definition at line 59 of file Reporter\&.py\&.
.PP
.nf
59   def __init__(self, n, values):
60     ReporterParameter\&.__init__(self,n)
61     self\&.values = values
62     
.fi
.SH "Member Function Documentation"
.PP 
.SS "def Reporter\&.SelectionParameter\&.getHTML ( self,  r,  bugtype,  getConfigOption)"

.PP
Definition at line 63 of file Reporter\&.py\&.
.PP
.nf
63   def getHTML(self,r,bugtype,getConfigOption):
64     default = self\&.getValue(r,bugtype,getConfigOption)
65     return """\
66 <tr>
67 <td class="form_clabel">%s:</td><td class="form_value"><select name="%s_%s">
68 %s
69 </select></td>"""%(self\&.getName(),r\&.getName(),self\&.getName(),'\n'\&.join(["""\
70 <option value="%s"%s>%s</option>"""%(o[0],
71                                      o[0] == default and ' selected="selected"' or '',
72                                      o[1]) for o in self\&.values]))
73 
74 #===------------------------------------------------------------------------===#
75 # Reporters
76 #===------------------------------------------------------------------------===#
77 
.fi
.PP
References diagtool::DiagnosticRecord\&.getName(), diagtool::GroupRecord\&.getName(), diagtool::DiagTool\&.getName(), clang::cxcursor::MacroExpansionCursor\&.getName(), Reporter\&.ReporterParameter\&.getName(), Reporter\&.EmailReporter\&.getName(), Reporter\&.BugzillaReporter\&.getName(), Reporter\&.ReporterParameter\&.getValue(), Reporter\&.RadarClassificationParameter\&.getValue(), LLVM\&.ClangFormat\&.OptionPageGrid\&.StyleConverter\&.values, and Reporter\&.SelectionParameter\&.values\&.
.SS "def Reporter\&.ReporterParameter\&.getName ( self)\fC [inherited]\fP"

.PP
Definition at line 43 of file Reporter\&.py\&.
.PP
.nf
43   def getName(self):
44     return self\&.name
.fi
.PP
References libear\&.SharedLibrary\&.name, Reporter\&.ReporterParameter\&.name, and startfile\&.BaseController\&.name\&.
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), Reporter\&.SelectionParameter\&.getHTML(), and Reporter\&.ReporterParameter\&.getValue()\&.
.SS "def Reporter\&.ReporterParameter\&.getValue ( self,  r,  bugtype,  getConfigOption)\fC [inherited]\fP"

.PP
Reimplemented in \fBReporter\&.RadarClassificationParameter\fP\&.
.PP
Definition at line 45 of file Reporter\&.py\&.
.PP
.nf
45   def getValue(self,r,bugtype,getConfigOption):
46      return getConfigOption(r\&.getName(),self\&.getName())
.fi
.PP
References diagtool::DiagnosticRecord\&.getName(), diagtool::GroupRecord\&.getName(), diagtool::DiagTool\&.getName(), clang::cxcursor::MacroExpansionCursor\&.getName(), Reporter\&.ReporterParameter\&.getName(), Reporter\&.EmailReporter\&.getName(), and Reporter\&.BugzillaReporter\&.getName()\&.
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), and Reporter\&.SelectionParameter\&.getHTML()\&.
.SS "def Reporter\&.ReporterParameter\&.saveConfigValue ( self)\fC [inherited]\fP"

.PP
Reimplemented in \fBReporter\&.RadarClassificationParameter\fP\&.
.PP
Definition at line 47 of file Reporter\&.py\&.
.PP
.nf
47   def saveConfigValue(self):
48     return True
49 
.fi
.SH "Member Data Documentation"
.PP 
.SS "Reporter\&.ReporterParameter\&.name\fC [inherited]\fP"

.PP
Definition at line 42 of file Reporter\&.py\&.
.PP
Referenced by libear\&.SharedLibrary\&.build_release(), and Reporter\&.ReporterParameter\&.getName()\&.
.SS "Reporter\&.SelectionParameter\&.values"

.PP
Definition at line 61 of file Reporter\&.py\&.
.PP
Referenced by Reporter\&.SelectionParameter\&.getHTML()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
