.TH "Reporter.BugReport" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter.BugReport
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBtitle\fP, \fBdescription\fP, \fBfiles\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBfiles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Reporter\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Reporter\&.BugReport\&.__init__ ( self,  title,  description,  files)"

.PP
Definition at line 20 of file Reporter\&.py\&.
.PP
.nf
20     def __init__(self, title, description, files):
21         self\&.title = title
22         self\&.description = description
23         self\&.files = files
24 
25 # Reporter interfaces\&.
26 
.fi
.SH "Member Data Documentation"
.PP 
.SS "Reporter\&.BugReport\&.description"

.PP
Definition at line 22 of file Reporter\&.py\&.
.SS "Reporter\&.BugReport\&.files"

.PP
Definition at line 23 of file Reporter\&.py\&.
.SS "Reporter\&.BugReport\&.title"

.PP
Definition at line 21 of file Reporter\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
