.TH "Reporter" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReportFailure\fP"
.br
.ti -1c
.RI "class \fBBugReport\fP"
.br
.ti -1c
.RI "class \fBReporterParameter\fP"
.br
.ti -1c
.RI "class \fBTextParameter\fP"
.br
.ti -1c
.RI "class \fBSelectionParameter\fP"
.br
.ti -1c
.RI "class \fBEmailReporter\fP"
.br
.ti -1c
.RI "class \fBBugzillaReporter\fP"
.br
.ti -1c
.RI "class \fBRadarClassificationParameter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetReporters\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Reporter\&.getReporters ()"

.PP
Definition at line 179 of file Reporter\&.py\&.
.PP
.nf
179 def getReporters():
180     reporters = []
181     reporters\&.append(EmailReporter())
182     return reporters
183 
.fi
.PP
Referenced by ScanView\&.create_server()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
