.TH "Reporter.ReporterParameter" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter.ReporterParameter
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBReporter\&.SelectionParameter\fP, and \fBReporter\&.TextParameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, n)"
.br
.ti -1c
.RI "def \fBgetName\fP (self)"
.br
.ti -1c
.RI "def \fBgetValue\fP (self, r, bugtype, getConfigOption)"
.br
.ti -1c
.RI "def \fBsaveConfigValue\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file Reporter\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Reporter\&.ReporterParameter\&.__init__ ( self,  n)"

.PP
Definition at line 41 of file Reporter\&.py\&.
.PP
.nf
41   def __init__(self, n):
42     self\&.name = n
.fi
.SH "Member Function Documentation"
.PP 
.SS "def Reporter\&.ReporterParameter\&.getName ( self)"

.PP
Definition at line 43 of file Reporter\&.py\&.
.PP
.nf
43   def getName(self):
44     return self\&.name
.fi
.PP
References libear\&.SharedLibrary\&.name, Reporter\&.ReporterParameter\&.name, and startfile\&.BaseController\&.name\&.
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), Reporter\&.SelectionParameter\&.getHTML(), and Reporter\&.ReporterParameter\&.getValue()\&.
.SS "def Reporter\&.ReporterParameter\&.getValue ( self,  r,  bugtype,  getConfigOption)"

.PP
Reimplemented in \fBReporter\&.RadarClassificationParameter\fP\&.
.PP
Definition at line 45 of file Reporter\&.py\&.
.PP
.nf
45   def getValue(self,r,bugtype,getConfigOption):
46      return getConfigOption(r\&.getName(),self\&.getName())
.fi
.PP
References diagtool::DiagnosticRecord\&.getName(), diagtool::GroupRecord\&.getName(), diagtool::DiagTool\&.getName(), clang::cxcursor::MacroExpansionCursor\&.getName(), Reporter\&.ReporterParameter\&.getName(), Reporter\&.EmailReporter\&.getName(), and Reporter\&.BugzillaReporter\&.getName()\&.
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), and Reporter\&.SelectionParameter\&.getHTML()\&.
.SS "def Reporter\&.ReporterParameter\&.saveConfigValue ( self)"

.PP
Reimplemented in \fBReporter\&.RadarClassificationParameter\fP\&.
.PP
Definition at line 47 of file Reporter\&.py\&.
.PP
.nf
47   def saveConfigValue(self):
48     return True
49 
.fi
.SH "Member Data Documentation"
.PP 
.SS "Reporter\&.ReporterParameter\&.name"

.PP
Definition at line 42 of file Reporter\&.py\&.
.PP
Referenced by libear\&.SharedLibrary\&.build_release(), and Reporter\&.ReporterParameter\&.getName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
