.TH "Reporter.TextParameter" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter.TextParameter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBReporter\&.ReporterParameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBgetHTML\fP (self, r, bugtype, getConfigOption)"
.br
.ti -1c
.RI "def \fBgetName\fP (self)"
.br
.ti -1c
.RI "def \fBgetValue\fP (self, r, bugtype, getConfigOption)"
.br
.ti -1c
.RI "def \fBsaveConfigValue\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file Reporter\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def Reporter\&.TextParameter\&.getHTML ( self,  r,  bugtype,  getConfigOption)"

.PP
Definition at line 51 of file Reporter\&.py\&.
.PP
.nf
51   def getHTML(self,r,bugtype,getConfigOption):
52     return """\
53 <tr>
54 <td class="form_clabel">%s:</td>
55 <td class="form_value"><input type="text" name="%s_%s" value="%s"></td>
56 </tr>"""%(self\&.getName(),r\&.getName(),self\&.getName(),self\&.getValue(r,bugtype,getConfigOption))
57 
.fi
.PP
References diagtool::DiagnosticRecord\&.getName(), diagtool::GroupRecord\&.getName(), diagtool::DiagTool\&.getName(), clang::cxcursor::MacroExpansionCursor\&.getName(), Reporter\&.ReporterParameter\&.getName(), Reporter\&.EmailReporter\&.getName(), Reporter\&.BugzillaReporter\&.getName(), Reporter\&.ReporterParameter\&.getValue(), and Reporter\&.RadarClassificationParameter\&.getValue()\&.
.SS "def Reporter\&.ReporterParameter\&.getName ( self)\fC [inherited]\fP"

.PP
Definition at line 43 of file Reporter\&.py\&.
.PP
.nf
43   def getName(self):
44     return self\&.name
.fi
.PP
References libear\&.SharedLibrary\&.name, Reporter\&.ReporterParameter\&.name, and startfile\&.BaseController\&.name\&.
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), Reporter\&.SelectionParameter\&.getHTML(), and Reporter\&.ReporterParameter\&.getValue()\&.
.SS "def Reporter\&.ReporterParameter\&.getValue ( self,  r,  bugtype,  getConfigOption)\fC [inherited]\fP"

.PP
Reimplemented in \fBReporter\&.RadarClassificationParameter\fP\&.
.PP
Definition at line 45 of file Reporter\&.py\&.
.PP
.nf
45   def getValue(self,r,bugtype,getConfigOption):
46      return getConfigOption(r\&.getName(),self\&.getName())
.fi
.PP
References diagtool::DiagnosticRecord\&.getName(), diagtool::GroupRecord\&.getName(), diagtool::DiagTool\&.getName(), clang::cxcursor::MacroExpansionCursor\&.getName(), Reporter\&.ReporterParameter\&.getName(), Reporter\&.EmailReporter\&.getName(), and Reporter\&.BugzillaReporter\&.getName()\&.
.PP
Referenced by Reporter\&.TextParameter\&.getHTML(), and Reporter\&.SelectionParameter\&.getHTML()\&.
.SS "def Reporter\&.ReporterParameter\&.saveConfigValue ( self)\fC [inherited]\fP"

.PP
Reimplemented in \fBReporter\&.RadarClassificationParameter\fP\&.
.PP
Definition at line 47 of file Reporter\&.py\&.
.PP
.nf
47   def saveConfigValue(self):
48     return True
49 
.fi
.SH "Member Data Documentation"
.PP 
.SS "Reporter\&.ReporterParameter\&.name\fC [inherited]\fP"

.PP
Definition at line 42 of file Reporter\&.py\&.
.PP
Referenced by libear\&.SharedLibrary\&.build_release(), and Reporter\&.ReporterParameter\&.getName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
