.TH "Reporter.ReportFailure" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reporter.ReportFailure
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBvalue\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Generic exception for failures in bug reporting.
.fi
.PP
 
.PP
Definition at line 12 of file Reporter\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Reporter\&.ReportFailure\&.__init__ ( self,  value)"

.PP
Definition at line 14 of file Reporter\&.py\&.
.PP
.nf
14     def __init__(self, value):        
15         self\&.value = value
16 
17 # Collect information about a bug\&.
18 
.fi
.SH "Member Data Documentation"
.PP 
.SS "Reporter\&.ReportFailure\&.value"

.PP
Definition at line 15 of file Reporter\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
