.TH "RootObject" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RootObject
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBaseClass\fP, \fBBaseClass\fP, \fBBaseClass\fP, and \fBBasicClass\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(instancetype) \- \fBinit\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(instancetype) + \fBalloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file BasicClass\&.m\&.
.SH "Method Documentation"
.PP 
.SS "+ (instancetype) alloc "

.SS "\- (instancetype) init "


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
