.TH "/Users/maximilian/clang-llvm/clang/tools/scan-view/share/ScanView.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-view/share/ScanView.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScanView\&.ReporterThread\fP"
.br
.ti -1c
.RI "class \fBScanView\&.ScanViewServer\fP"
.br
.ti -1c
.RI "class \fBScanView\&.ScanViewRequestHandler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBScanView\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBScanView\&.parse_query\fP (qs, fields=None)"
.br
.ti -1c
.RI "def \fBScanView\&.create_server\fP (address, options, root)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBScanView\&.kReportFileRE\fP = re\&.compile('(\&.*/)?report\-(\&.*)\\\\\&.html')"
.br
.RI "Various patterns matched or replaced by server\&. "
.ti -1c
.RI "\fBScanView\&.kBugKeyValueRE\fP = re\&.compile('<!\-\- BUG([^ ]*) (\&.*) \-\->')"
.br
.ti -1c
.RI "\fBScanView\&.kReportCrashEntryRE\fP = re\&.compile('<!\-\- REPORTPROBLEM (\&.*?)\-\->')"
.br
.ti -1c
.RI "\fBScanView\&.kReportCrashEntryKeyValueRE\fP = re\&.compile(' ?([^=]+)='(\&.*?)'')"
.br
.ti -1c
.RI "list \fBScanView\&.kReportReplacements\fP = []"
.br
.ti -1c
.RI "\fBScanView\&.kShare\fP = posixpath\&.join(\fBposixpath\&.dirname\fP(__file__), '\&.\&./share/scan\-view')"
.br
.RI "Other simple parameters\&. "
.ti -1c
.RI "\fBScanView\&.kConfigPath\fP = os\&.path\&.expanduser('~/\&.scanview\&.cfg')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
