.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/shell.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/lib/libscanbuild/shell.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibscanbuild\&.shell\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibscanbuild\&.shell\&.encode\fP (command)"
.br
.ti -1c
.RI "def \fBlibscanbuild\&.shell\&.decode\fP (string)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
