.TH "/Users/maximilian/clang-llvm/clang/tools/diagtool/ShowEnabledWarnings.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/diagtool/ShowEnabledWarnings.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DiagTool\&.h'\fP
.br
\fC#include 'DiagnosticNames\&.h'\fP
.br
\fC#include 'clang/Basic/LLVM\&.h'\fP
.br
\fC#include 'clang/Frontend/CompilerInstance\&.h'\fP
.br
\fC#include 'clang/Frontend/TextDiagnosticBuffer\&.h'\fP
.br
\fC#include 'clang/Frontend/TextDiagnosticPrinter\&.h'\fP
.br
\fC#include 'clang/Frontend/Utils\&.h'\fP
.br
\fC#include 'llvm/Support/TargetSelect\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEF_DIAGTOOL\fP ('show\-enabled', 'Show which warnings are enabled for a given command line', ShowEnabledWarnings) using namespace clang"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DEF_DIAGTOOL ('show\-enabled', 'Show which warnings are enabled for a given command line', ShowEnabledWarnings)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
