.TH "SingleCommandCompilationDatabase" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingleCommandCompilationDatabase
.SH SYNOPSIS
.br
.PP
.PP
Inherits tooling::CompilationDatabase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleCommandCompilationDatabase\fP (tooling::CompileCommand Cmd)"
.br
.ti -1c
.RI "std::vector< tooling::CompileCommand > \fBgetCompileCommands\fP (StringRef FilePath) const override"
.br
.ti -1c
.RI "std::vector< tooling::CompileCommand > \fBgetAllCompileCommands\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 204 of file ClangScanDeps\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SingleCommandCompilationDatabase::SingleCommandCompilationDatabase (tooling::CompileCommand Cmd)\fC [inline]\fP"

.PP
Definition at line 206 of file ClangScanDeps\&.cpp\&.
.PP
.nf
207       : Command(std::move(Cmd)) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "std::vector<tooling::CompileCommand> SingleCommandCompilationDatabase::getAllCompileCommands () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 214 of file ClangScanDeps\&.cpp\&.
.PP
.nf
214                                                                           {
215     return {Command};
216   }
.fi
.SS "std::vector<tooling::CompileCommand> SingleCommandCompilationDatabase::getCompileCommands (StringRef FilePath) const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 210 of file ClangScanDeps\&.cpp\&.
.PP
.nf
210                                                         {
211     return {Command};
212   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
