.TH "startfile.Start" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
startfile.Start
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstartfile\&.BaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBopen\fP (self, filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Controller for the win32 start program through os.startfile.
.fi
.PP
 
.PP
Definition at line 87 of file startfile\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def startfile\&.Start\&.open ( self,  filename)"

.PP
Reimplemented from \fBstartfile\&.BaseController\fP\&.
.PP
Definition at line 90 of file startfile\&.py\&.
.PP
.nf
90         def open(self, filename):
91             try:
92                 os\&.startfile(filename)
93             except WindowsError:
94                 # [Error 22] No application is associated with the specified
95                 # file for this operation: '<URL>'
96                 return False
97             else:
98                 return True
99 
100     _controllers['windows-default'] = Start('start')
.fi
.SH "Member Data Documentation"
.PP 
.SS "startfile\&.BaseController\&.name\fC [inherited]\fP"

.PP
Definition at line 24 of file startfile\&.py\&.
.PP
Referenced by libear\&.SharedLibrary\&.build_release(), and Reporter\&.ReporterParameter\&.getName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
