.TH "startfile.Controller" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
startfile.Controller
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstartfile\&.BaseController\fP\&.
.PP
Inherited by \fBstartfile\&.KfmClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, *\fBargs\fP)"
.br
.ti -1c
.RI "def \fBopen\fP (self, filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBargs\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Controller for a generic open program.
.fi
.PP
 
.PP
Definition at line 30 of file startfile\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def startfile\&.Controller\&.__init__ ( self, * args)"

.PP
Definition at line 33 of file startfile\&.py\&.
.PP
.nf
33     def __init__(self, *args):
34         super(Controller, self)\&.__init__(os\&.path\&.basename(args[0]))
35         self\&.args = list(args)
36 
.fi
.SH "Member Function Documentation"
.PP 
.SS "def startfile\&.Controller\&.open ( self,  filename)"

.PP
Reimplemented from \fBstartfile\&.BaseController\fP\&.
.PP
Definition at line 72 of file startfile\&.py\&.
.PP
.nf
72     def open(self, filename):
73         if isinstance(filename, basestring):
74             cmdline = self\&.args + [filename]
75         else:
76             # assume it is a sequence
77             cmdline = self\&.args + filename
78         try:
79             return self\&._invoke(cmdline)
80         except OSError:
81             return False
82 
83 
84 # Platform support for Windows
.fi
.PP
References startfile\&.Controller\&._invoke(), and startfile\&.Controller\&.args\&.
.SH "Member Data Documentation"
.PP 
.SS "startfile\&.Controller\&.args"

.PP
Definition at line 35 of file startfile\&.py\&.
.PP
Referenced by startfile\&.Controller\&.open()\&.
.SS "startfile\&.BaseController\&.name\fC [inherited]\fP"

.PP
Definition at line 24 of file startfile\&.py\&.
.PP
Referenced by libear\&.SharedLibrary\&.build_release(), and Reporter\&.ReporterParameter\&.getName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
