.TH "/Users/maximilian/clang-llvm/clang/tools/scan-view/share/startfile.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-view/share/startfile.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstartfile\&.BaseController\fP"
.br
.ti -1c
.RI "class \fBstartfile\&.Controller\fP"
.br
.ti -1c
.RI "class \fBstartfile\&.Start\fP"
.br
.ti -1c
.RI "class \fBstartfile\&.KfmClient\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBstartfile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBstartfile\&.detect_desktop_environment\fP ()"
.br
.ti -1c
.RI "def \fBstartfile\&.register_X_controllers\fP ()"
.br
.ti -1c
.RI "def \fBstartfile\&.get\fP ()"
.br
.ti -1c
.RI "def \fBstartfile\&.open\fP (filename)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
