.TH "startfile.BaseController" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
startfile.BaseController
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBstartfile\&.Controller\fP, and \fBstartfile\&.Start\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBname\fP)"
.br
.ti -1c
.RI "def \fBopen\fP (self, filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for open program controllers.
.fi
.PP
 
.PP
Definition at line 20 of file startfile\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def startfile\&.BaseController\&.__init__ ( self,  name)"

.PP
Reimplemented in \fBstartfile\&.KfmClient\fP\&.
.PP
Definition at line 23 of file startfile\&.py\&.
.PP
.nf
23     def __init__(self, name):
24         self\&.name = name
25 
.fi
.SH "Member Function Documentation"
.PP 
.SS "def startfile\&.BaseController\&.open ( self,  filename)"

.PP
Reimplemented in \fBstartfile\&.Start\fP, and \fBstartfile\&.Controller\fP\&.
.PP
Definition at line 26 of file startfile\&.py\&.
.PP
.nf
26     def open(self, filename):
27         raise NotImplementedError
28 
29 
.fi
.SH "Member Data Documentation"
.PP 
.SS "startfile\&.BaseController\&.name"

.PP
Definition at line 24 of file startfile\&.py\&.
.PP
Referenced by libear\&.SharedLibrary\&.build_release(), and Reporter\&.ReporterParameter\&.getName()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
