.TH "StatementRuntime" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatementRuntime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidentifier\fP"
.br
.ti -1c
.RI "double \fBcalled\fP = 0"
.br
.ti -1c
.RI "high_resolution_clock::time_point \fBstartTime\fP = \fBinvalidTime\fP"
.br
.ti -1c
.RI "high_resolution_clock::time_point \fBendTime\fP = \fBinvalidTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file DataStorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double StatementRuntime::called = 0"

.PP
Definition at line 19 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print(), and DataStorage::startEvent()\&.
.SS "high_resolution_clock::time_point StatementRuntime::endTime = \fBinvalidTime\fP"

.PP
Definition at line 21 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::endEvent(), DataStorage::print(), and DataStorage::startEvent()\&.
.SS "string StatementRuntime::identifier"

.PP
Definition at line 18 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::DataStorage()\&.
.SS "high_resolution_clock::time_point StatementRuntime::startTime = \fBinvalidTime\fP"

.PP
Definition at line 20 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print(), and DataStorage::startEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
