.TH "StatementRuntime" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatementRuntime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStorage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidentifier\fP"
.br
.ti -1c
.RI "high_resolution_clock::time_point \fBstartTime\fP = \fBinvalidTime\fP"
.br
.ti -1c
.RI "high_resolution_clock::time_point \fBendTime\fP = \fBinvalidTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file DataStorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "high_resolution_clock::time_point StatementRuntime::endTime = \fBinvalidTime\fP"

.PP
Definition at line 17 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::endEvent(), DataStorage::print(), and DataStorage::startEvent()\&.
.SS "string StatementRuntime::identifier"

.PP
Definition at line 15 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::DataStorage()\&.
.SS "high_resolution_clock::time_point StatementRuntime::startTime = \fBinvalidTime\fP"

.PP
Definition at line 16 of file DataStorage\&.h\&.
.PP
Referenced by DataStorage::print(), and DataStorage::startEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
