.TH "tests.unit.test_analyze.Spy" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_analyze.Spy
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBcall\fP (self, params)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBarg\fP"
.br
.ti -1c
.RI "\fBsuccess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file test_analyze\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def tests\&.unit\&.test_analyze\&.Spy\&.__init__ ( self)"

.PP
Definition at line 119 of file test_analyze\&.py\&.
.PP
.nf
119     def __init__(self):
120         self\&.arg = None
121         self\&.success = 0
122 
.fi
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_analyze\&.Spy\&.call ( self,  params)"

.PP
Definition at line 123 of file test_analyze\&.py\&.
.PP
.nf
123     def call(self, params):
124         self\&.arg = params
125         return self\&.success
126 
127 
.fi
.PP
References tests\&.unit\&.test_analyze\&.Spy\&.arg, tests\&.unit\&.test_analyze\&.Spy\&.success, and ScanView\&.ReporterThread\&.success\&.
.SH "Member Data Documentation"
.PP 
.SS "tests\&.unit\&.test_analyze\&.Spy\&.arg"

.PP
Definition at line 120 of file test_analyze\&.py\&.
.PP
Referenced by tests\&.unit\&.test_analyze\&.Spy\&.call()\&.
.SS "tests\&.unit\&.test_analyze\&.Spy\&.success"

.PP
Definition at line 121 of file test_analyze\&.py\&.
.PP
Referenced by tests\&.unit\&.test_analyze\&.Spy\&.call(), and ScanView\&.ReporterThread\&.run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
