.TH "tests.unit.test_clang.ClangGetVersion" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_clang.ClangGetVersion
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_get_version_is_not_empty\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_version_throws\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file test_clang\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_clang\&.ClangGetVersion\&.test_get_version_is_not_empty ( self)"

.PP
Definition at line 14 of file test_clang\&.py\&.
.PP
.nf
14     def test_get_version_is_not_empty(self):
15         self\&.assertTrue(sut\&.get_version('clang'))
16 
.fi
.SS "def tests\&.unit\&.test_clang\&.ClangGetVersion\&.test_get_version_throws ( self)"

.PP
Definition at line 17 of file test_clang\&.py\&.
.PP
.nf
17     def test_get_version_throws(self):
18         with self\&.assertRaises(OSError):
19             sut\&.get_version('notexists')
20 
21 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
