.TH "Tests/testPerformance.cpp" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/testPerformance.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./lib/DataStorage\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfibonacci\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDataStorage\fP \fBdataStorage\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fibonacci ()"

.PP
Definition at line 5 of file testPerformance\&.cpp\&.
.PP
.nf
5                  {
6     dataStorage\&.startEvent("DeclStmt 2082482");
7     double n, t1 = 0, t2 = 1, nextTerm = 0;
8     dataStorage\&.startEvent("DeclStmt 2082482");
9 
10     dataStorage\&.startEvent("BinaryOperator 2082496");
11     n = 50;
12     dataStorage\&.startEvent("BinaryOperator 2082496");
13 
14     dataStorage\&.startEvent("CXXOperatorCallExpr 2083688");
15     std::cout << "Fibonacci Series: ";
16     dataStorage\&.startEvent("CXXOperatorCallExpr 2083688");
17 
18     dataStorage\&.startEvent("ForStmt 2086448");
19     for (int i = 1; i <= n; ++i) {
20         if(i == 1) {
21             std::cout << t1 << ", ";
22             continue;
23         }
24         if(i == 2) {
25             std::cout << t2 << ", ";
26             continue;
27         }
28         nextTerm = t1 + t2;
29         t1 = t2;
30         t2 = nextTerm;
31 
32         std::cout << nextTerm << ", ";
33     }
34     dataStorage\&.startEvent("ForStmt 2086448");
35 }
.fi
.PP
References dataStorage, and DataStorage::startEvent()\&.
.PP
Referenced by main()\&.
.SS "int main (void)"

.PP
Definition at line 37 of file testPerformance\&.cpp\&.
.PP
.nf
37                {
38     dataStorage\&.startEvent("Runtime");
39     int i = 10;
40     i++;
41     i++;
42     i++;
43     i++;
44     i++;
45 
46     fibonacci();
47     dataStorage\&.startEvent("Runtime");
48     dataStorage\&.print();
49     return 0;
50 
51 }
.fi
.PP
References dataStorage, fibonacci(), DataStorage::print(), and DataStorage::startEvent()\&.
.SH "Variable Documentation"
.PP 
.SS "\fBDataStorage\fP dataStorage"

.PP
Definition at line 3 of file testPerformance\&.cpp\&.
.PP
Referenced by fibonacci(), and main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
