.TH "tests.unit" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest_analyze\fP"
.br
.ti -1c
.RI " \fBtest_clang\fP"
.br
.ti -1c
.RI " \fBtest_compilation\fP"
.br
.ti -1c
.RI " \fBtest_intercept\fP"
.br
.ti -1c
.RI " \fBtest_libear\fP"
.br
.ti -1c
.RI " \fBtest_report\fP"
.br
.ti -1c
.RI " \fBtest_shell\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBload_tests\fP (loader, \fBsuite\fP, _)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def tests\&.unit\&.load_tests ( loader,  suite,  _)"

.PP
Definition at line 15 of file __init__\&.py\&.
.PP
.nf
15 def load_tests(loader, suite, _):
16     suite\&.addTests(loader\&.loadTestsFromModule(test_libear))
17     suite\&.addTests(loader\&.loadTestsFromModule(test_compilation))
18     suite\&.addTests(loader\&.loadTestsFromModule(test_clang))
19     suite\&.addTests(loader\&.loadTestsFromModule(test_report))
20     suite\&.addTests(loader\&.loadTestsFromModule(test_analyze))
21     suite\&.addTests(loader\&.loadTestsFromModule(test_intercept))
22     suite\&.addTests(loader\&.loadTestsFromModule(test_shell))
23     return suite
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
