.TH "tests.unit.test_report" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_report
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParseFileTest\fP"
.br
.ti -1c
.RI "class \fBReportMethodTest\fP"
.br
.ti -1c
.RI "class \fBGetPrefixFromCompilationDatabaseTest\fP"
.br
.ti -1c
.RI "class \fBMergeSarifTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrun_bug_parse\fP (content)"
.br
.ti -1c
.RI "def \fBrun_crash_parse\fP (content, preproc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_report\&.run_bug_parse ( content)"

.PP
Definition at line 14 of file test_report\&.py\&.
.PP
.nf
14 def run_bug_parse(content):
15     with libear\&.TemporaryDirectory() as tmpdir:
16         file_name = os\&.path\&.join(tmpdir, 'test\&.html')
17         with open(file_name, 'w') as handle:
18             handle\&.writelines(content)
19         for bug in sut\&.parse_bug_html(file_name):
20             return bug
21 
22 
.fi
.PP
References startfile\&.open(), and libear\&.TemporaryDirectory()\&.
.PP
Referenced by tests\&.unit\&.test_report\&.ParseFileTest\&.test_parse_bug(), and tests\&.unit\&.test_report\&.ParseFileTest\&.test_parse_bug_empty()\&.
.SS "def tests\&.unit\&.test_report\&.run_crash_parse ( content,  preproc)"

.PP
Definition at line 23 of file test_report\&.py\&.
.PP
.nf
23 def run_crash_parse(content, preproc):
24     with libear\&.TemporaryDirectory() as tmpdir:
25         file_name = os\&.path\&.join(tmpdir, preproc + '\&.info\&.txt')
26         with open(file_name, 'w') as handle:
27             handle\&.writelines(content)
28         return sut\&.parse_crash(file_name)
29 
30 
.fi
.PP
References startfile\&.open(), and libear\&.TemporaryDirectory()\&.
.PP
Referenced by tests\&.unit\&.test_report\&.ParseFileTest\&.test_parse_crash()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
