.TH "tests.unit.test_clang.ClangIsCtuCapableTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_clang.ClangIsCtuCapableTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_ctu_not_found\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file test_clang\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_clang\&.ClangIsCtuCapableTest\&.test_ctu_not_found ( self)"

.PP
Definition at line 97 of file test_clang\&.py\&.
.PP
.nf
97     def test_ctu_not_found(self):
98         is_ctu = sut\&.is_ctu_capable('not-found-clang-extdef-mapping')
99         self\&.assertFalse(is_ctu)
100 
101 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
