.TH "tests.unit.test_clang.ClangGetTripleArchTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_clang.ClangGetTripleArchTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_arch_is_not_empty\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file test_clang\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_clang\&.ClangGetTripleArchTest\&.test_arch_is_not_empty ( self)"

.PP
Definition at line 103 of file test_clang\&.py\&.
.PP
.nf
103     def test_arch_is_not_empty(self):
104         arch = sut\&.get_triple_arch(['clang', '-E', '-'], '\&.')
105         self\&.assertTrue(len(arch) > 0)
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
