.TH "tests.unit.test_analyze.RequireDecoratorTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_analyze.RequireDecoratorTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_method_without_expecteds\fP (self)"
.br
.ti -1c
.RI "def \fBtest_method_with_expecteds\fP (self)"
.br
.ti -1c
.RI "def \fBtest_method_exception_not_caught\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 333 of file test_analyze\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_analyze\&.RequireDecoratorTest\&.test_method_exception_not_caught ( self)"

.PP
Definition at line 348 of file test_analyze\&.py\&.
.PP
.nf
348     def test_method_exception_not_caught(self):
349         self\&.assertRaises(Exception, method_exception_from_inside, dict())
350 
351 
.fi
.SS "def tests\&.unit\&.test_analyze\&.RequireDecoratorTest\&.test_method_with_expecteds ( self)"

.PP
Definition at line 341 of file test_analyze\&.py\&.
.PP
.nf
341     def test_method_with_expecteds(self):
342         self\&.assertRaises(KeyError, method_with_expecteds, dict())
343         self\&.assertRaises(KeyError, method_with_expecteds, {})
344         self\&.assertRaises(KeyError, method_with_expecteds, {'this': 2})
345         self\&.assertRaises(KeyError, method_with_expecteds, {'that': 3})
346         self\&.assertEqual(method_with_expecteds({'this': 0, 'that': 3}), 0)
347 
.fi
.PP
References tests\&.unit\&.test_analyze\&.method_with_expecteds()\&.
.SS "def tests\&.unit\&.test_analyze\&.RequireDecoratorTest\&.test_method_without_expecteds ( self)"

.PP
Definition at line 335 of file test_analyze\&.py\&.
.PP
.nf
335     def test_method_without_expecteds(self):
336         self\&.assertEqual(method_without_expecteds(dict()), 0)
337         self\&.assertEqual(method_without_expecteds({}), 0)
338         self\&.assertEqual(method_without_expecteds({'this': 2}), 0)
339         self\&.assertEqual(method_without_expecteds({'that': 3}), 0)
340 
.fi
.PP
References tests\&.unit\&.test_analyze\&.method_without_expecteds()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
