.TH "Tests/test_forloop.cpp" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_forloop.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <thread>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 5 of file test_forloop\&.cpp\&.
.PP
.nf
5                {
6     std::this_thread::sleep_for(std::chrono::milliseconds (10));
7     for ( int j = 1; j <= 10; j++ ) {
8         std::this_thread::sleep_for(std::chrono::milliseconds (10));
9         std::this_thread::sleep_for(std::chrono::milliseconds (10));
10     }
11     for ( int j = 1; j <= 100; j++ ) {
12         std::this_thread::sleep_for(std::chrono::milliseconds (10));
13         std::this_thread::sleep_for(std::chrono::milliseconds (10));
14     }
15     for ( int j = 1; j <= 1000; j++ ) {
16         std::this_thread::sleep_for(std::chrono::milliseconds (10));
17         std::this_thread::sleep_for(std::chrono::milliseconds (10));
18     }
19     return 1;
20 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
