.TH "tests.unit.test_compilation.SourceClassifierTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_compilation.SourceClassifierTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_sources\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file test_compilation\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_compilation\&.SourceClassifierTest\&.test_sources ( self)"

.PP
Definition at line 110 of file test_compilation\&.py\&.
.PP
.nf
110     def test_sources(self):
111         self\&.assertIsNone(sut\&.classify_source('file\&.o'))
112         self\&.assertIsNone(sut\&.classify_source('file\&.exe'))
113         self\&.assertIsNone(sut\&.classify_source('/path/file\&.o'))
114         self\&.assertIsNone(sut\&.classify_source('clang'))
115 
116         self\&.assertEqual('c', sut\&.classify_source('file\&.c'))
117         self\&.assertEqual('c', sut\&.classify_source('\&./file\&.c'))
118         self\&.assertEqual('c', sut\&.classify_source('/path/file\&.c'))
119         self\&.assertEqual('c++', sut\&.classify_source('file\&.c', False))
120         self\&.assertEqual('c++', sut\&.classify_source('\&./file\&.c', False))
121         self\&.assertEqual('c++', sut\&.classify_source('/path/file\&.c', False))
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
