.TH "tests.unit.test_report.ReportMethodTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_report.ReportMethodTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_chop\fP (self)"
.br
.ti -1c
.RI "def \fBtest_chop_when_cwd\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file test_report\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_report\&.ReportMethodTest\&.test_chop ( self)"

.PP
Definition at line 116 of file test_report\&.py\&.
.PP
.nf
116     def test_chop(self):
117         self\&.assertEqual('file', sut\&.chop('/prefix', '/prefix/file'))
118         self\&.assertEqual('file', sut\&.chop('/prefix/', '/prefix/file'))
119         self\&.assertEqual('lib/file', sut\&.chop('/prefix/', '/prefix/lib/file'))
120         self\&.assertEqual('/prefix/file', sut\&.chop('', '/prefix/file'))
121 
.fi
.SS "def tests\&.unit\&.test_report\&.ReportMethodTest\&.test_chop_when_cwd ( self)"

.PP
Definition at line 122 of file test_report\&.py\&.
.PP
.nf
122     def test_chop_when_cwd(self):
123         self\&.assertEqual('\&.\&./src/file', sut\&.chop('/cwd', '/src/file'))
124         self\&.assertEqual('\&.\&./src/file', sut\&.chop('/prefix/cwd',
125                                                  '/prefix/src/file'))
126 
127 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
