.TH "tests.unit.test_libear.TemporaryDirectoryTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_libear.TemporaryDirectoryTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_creates_directory\fP (self)"
.br
.ti -1c
.RI "def \fBtest_removes_directory_when_exception\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file test_libear\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_libear\&.TemporaryDirectoryTest\&.test_creates_directory ( self)"

.PP
Definition at line 12 of file test_libear\&.py\&.
.PP
.nf
12     def test_creates_directory(self):
13         dirname = None
14         with sut\&.TemporaryDirectory() as tmpdir:
15             self\&.assertTrue(os\&.path\&.isdir(tmpdir))
16             dirname = tmpdir
17         self\&.assertIsNotNone(dirname)
18         self\&.assertFalse(os\&.path\&.exists(dirname))
19 
.fi
.SS "def tests\&.unit\&.test_libear\&.TemporaryDirectoryTest\&.test_removes_directory_when_exception ( self)"

.PP
Definition at line 20 of file test_libear\&.py\&.
.PP
.nf
20     def test_removes_directory_when_exception(self):
21         dirname = None
22         try:
23             with sut\&.TemporaryDirectory() as tmpdir:
24                 self\&.assertTrue(os\&.path\&.isdir(tmpdir))
25                 dirname = tmpdir
26                 raise RuntimeError('message')
27         except:
28             self\&.assertIsNotNone(dirname)
29             self\&.assertFalse(os\&.path\&.exists(dirname))
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
