.TH "/Users/maximilian/clang-llvm/clang/tools/clang-refactor/TestSupport.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-refactor/TestSupport.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ToolRefactoringResultConsumer\&.h'\fP
.br
\fC#include 'clang/Basic/LLVM\&.h'\fP
.br
\fC#include 'clang/Basic/SourceLocation\&.h'\fP
.br
\fC#include 'llvm/ADT/Optional\&.h'\fP
.br
\fC#include 'llvm/ADT/SmallVector\&.h'\fP
.br
\fC#include 'llvm/Support/Error\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBclang::refactor::TestSelectionRange\fP"
.br
.ti -1c
.RI "struct \fBclang::refactor::TestSelectionRangesInFile\fP"
.br
.RI "A set of test selection ranges specified in one file\&. "
.ti -1c
.RI "struct \fBclang::refactor::TestSelectionRangesInFile::RangeGroup\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::refactor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Optional< TestSelectionRangesInFile > \fBclang::refactor::findTestSelectionRanges\fP (StringRef Filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Declares datatypes and routines that are used by test-specific code in clang-refactor\&. 
.PP
Definition in file \fBTestSupport\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
