.TH "tests.functional.cases.test_from_cdb.ExitCodeTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.functional.cases.test_from_cdb.ExitCodeTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_regular_does_not_set_exit_code\fP (self)"
.br
.ti -1c
.RI "def \fBtest_clear_does_not_set_exit_code\fP (self)"
.br
.ti -1c
.RI "def \fBtest_regular_sets_exit_code_if_asked\fP (self)"
.br
.ti -1c
.RI "def \fBtest_clear_does_not_set_exit_code_if_asked\fP (self)"
.br
.ti -1c
.RI "def \fBtest_regular_sets_exit_code_if_asked_from_plist\fP (self)"
.br
.ti -1c
.RI "def \fBtest_clear_does_not_set_exit_code_if_asked_from_plist\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file test_from_cdb\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.ExitCodeTest\&.test_clear_does_not_set_exit_code ( self)"

.PP
Definition at line 63 of file test_from_cdb\&.py\&.
.PP
.nf
63     def test_clear_does_not_set_exit_code(self):
64         with libear\&.TemporaryDirectory() as tmpdir:
65             cdb = prepare_cdb('clean', tmpdir)
66             exit_code, __ = run_analyzer(tmpdir, cdb, [])
67             self\&.assertFalse(exit_code)
68 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.ExitCodeTest\&.test_clear_does_not_set_exit_code_if_asked ( self)"

.PP
Definition at line 75 of file test_from_cdb\&.py\&.
.PP
.nf
75     def test_clear_does_not_set_exit_code_if_asked(self):
76         with libear\&.TemporaryDirectory() as tmpdir:
77             cdb = prepare_cdb('clean', tmpdir)
78             exit_code, __ = run_analyzer(tmpdir, cdb, ['--status-bugs'])
79             self\&.assertFalse(exit_code)
80 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.ExitCodeTest\&.test_clear_does_not_set_exit_code_if_asked_from_plist ( self)"

.PP
Definition at line 88 of file test_from_cdb\&.py\&.
.PP
.nf
88     def test_clear_does_not_set_exit_code_if_asked_from_plist(self):
89         with libear\&.TemporaryDirectory() as tmpdir:
90             cdb = prepare_cdb('clean', tmpdir)
91             exit_code, __ = run_analyzer(
92                 tmpdir, cdb, ['--status-bugs', '--plist'])
93             self\&.assertFalse(exit_code)
94 
95 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.ExitCodeTest\&.test_regular_does_not_set_exit_code ( self)"

.PP
Definition at line 57 of file test_from_cdb\&.py\&.
.PP
.nf
57     def test_regular_does_not_set_exit_code(self):
58         with libear\&.TemporaryDirectory() as tmpdir:
59             cdb = prepare_cdb('regular', tmpdir)
60             exit_code, __ = run_analyzer(tmpdir, cdb, [])
61             self\&.assertFalse(exit_code)
62 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.ExitCodeTest\&.test_regular_sets_exit_code_if_asked ( self)"

.PP
Definition at line 69 of file test_from_cdb\&.py\&.
.PP
.nf
69     def test_regular_sets_exit_code_if_asked(self):
70         with libear\&.TemporaryDirectory() as tmpdir:
71             cdb = prepare_cdb('regular', tmpdir)
72             exit_code, __ = run_analyzer(tmpdir, cdb, ['--status-bugs'])
73             self\&.assertTrue(exit_code)
74 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.ExitCodeTest\&.test_regular_sets_exit_code_if_asked_from_plist ( self)"

.PP
Definition at line 81 of file test_from_cdb\&.py\&.
.PP
.nf
81     def test_regular_sets_exit_code_if_asked_from_plist(self):
82         with libear\&.TemporaryDirectory() as tmpdir:
83             cdb = prepare_cdb('regular', tmpdir)
84             exit_code, __ = run_analyzer(
85                 tmpdir, cdb, ['--status-bugs', '--plist'])
86             self\&.assertTrue(exit_code)
87 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
