.TH "Tests/test_function_call.cpp" 3 "Sun Nov 14 2021" "Version 1.0" "Hagn Tool Performance Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_function_call.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 9 of file test_function_call\&.cpp\&.
.PP
.nf
9                {
10     test();
11     return 0;
12 }
.fi
.PP
References test()\&.
.SS "void test ()"

.PP
Definition at line 3 of file test_function_call\&.cpp\&.
.PP
.nf
3             {
4     int i = 0;
5     i = i + 2;
6     std::cout << i;
7 }
.fi
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hagn Tool Performance Counter from the source code\&.
