.TH "tests" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfunctional\fP"
.br
.ti -1c
.RI " \fBunit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsuite\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBthis_dir\fP = \fBos\&.path\&.dirname\fP(os\&.path\&.realpath(__file__))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def tests\&.suite ()"

.PP
Definition at line 18 of file __init__\&.py\&.
.PP
.nf
18 def suite():
19     loader = unittest\&.TestLoader()
20     suite = unittest\&.TestSuite()
21     suite\&.addTests(loader\&.loadTestsFromModule(tests\&.unit))
22     suite\&.addTests(loader\&.loadTestsFromModule(tests\&.functional\&.cases))
23     return suite
.fi
.SH "Variable Documentation"
.PP 
.SS "tests\&.this_dir = \fBos\&.path\&.dirname\fP(os\&.path\&.realpath(__file__))"

.PP
Definition at line 9 of file __init__\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
