.TH "tests.unit.test_analyze.PrefixWithTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_analyze.PrefixWithTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_gives_empty_on_empty\fP (self)"
.br
.ti -1c
.RI "def \fBtest_interleaves_prefix\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 352 of file test_analyze\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_analyze\&.PrefixWithTest\&.test_gives_empty_on_empty ( self)"

.PP
Definition at line 354 of file test_analyze\&.py\&.
.PP
.nf
354     def test_gives_empty_on_empty(self):
355         res = sut\&.prefix_with(0, [])
356         self\&.assertFalse(res)
357 
.fi
.SS "def tests\&.unit\&.test_analyze\&.PrefixWithTest\&.test_interleaves_prefix ( self)"

.PP
Definition at line 358 of file test_analyze\&.py\&.
.PP
.nf
358     def test_interleaves_prefix(self):
359         res = sut\&.prefix_with(0, [1, 2, 3])
360         self\&.assertListEqual([0, 1, 0, 2, 0, 3], res)
361 
362 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
