.TH "tests.unit.test_analyze.ReportDirectoryTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_analyze.ReportDirectoryTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_directory_name_comparison\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file test_analyze\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_analyze\&.ReportDirectoryTest\&.test_directory_name_comparison ( self)"

.PP
Definition at line 19 of file test_analyze\&.py\&.
.PP
.nf
19     def test_directory_name_comparison(self):
20         with libear\&.TemporaryDirectory() as tmpdir, \
21              sut\&.report_directory(tmpdir, False, 'html') as report_dir1, \
22              sut\&.report_directory(tmpdir, False, 'html') as report_dir2, \
23              sut\&.report_directory(tmpdir, False, 'html') as report_dir3:
24             self\&.assertLess(report_dir1, report_dir2)
25             self\&.assertLess(report_dir2, report_dir3)
26 
27 
.fi
.PP
References libear\&.TemporaryDirectory()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
