.TH "/Users/maximilian/clang-llvm/clang/tools/clang-refactor/TestSupport.cpp" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-refactor/TestSupport.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TestSupport\&.h'\fP
.br
\fC#include 'clang/Basic/DiagnosticError\&.h'\fP
.br
\fC#include 'clang/Basic/FileManager\&.h'\fP
.br
\fC#include 'clang/Basic/SourceManager\&.h'\fP
.br
\fC#include 'clang/Lex/Lexer\&.h'\fP
.br
\fC#include 'llvm/ADT/STLExtras\&.h'\fP
.br
\fC#include 'llvm/Support/Error\&.h'\fP
.br
\fC#include 'llvm/Support/ErrorOr\&.h'\fP
.br
\fC#include 'llvm/Support/LineIterator\&.h'\fP
.br
\fC#include 'llvm/Support/MemoryBuffer\&.h'\fP
.br
\fC#include 'llvm/Support/Regex\&.h'\fP
.br
\fC#include 'llvm/Support/raw_ostream\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::refactor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Optional< TestSelectionRangesInFile > \fBclang::refactor::findTestSelectionRanges\fP (StringRef Filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file implements routines that provide refactoring testing utilities\&. 
.PP
Definition in file \fBTestSupport\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
