.TH "/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/unit/test_clang.py" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/scan-build-py/tests/unit/test_clang.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtests\&.unit\&.test_clang\&.ClangGetVersion\fP"
.br
.ti -1c
.RI "class \fBtests\&.unit\&.test_clang\&.ClangGetArgumentsTest\fP"
.br
.ti -1c
.RI "class \fBtests\&.unit\&.test_clang\&.ClangGetCheckersTest\fP"
.br
.ti -1c
.RI "class \fBtests\&.unit\&.test_clang\&.ClangIsCtuCapableTest\fP"
.br
.ti -1c
.RI "class \fBtests\&.unit\&.test_clang\&.ClangGetTripleArchTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtests\&.unit\&.test_clang\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
