.TH "tests.functional.cases.test_from_cdb.OutputDirectoryTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.functional.cases.test_from_cdb.OutputDirectoryTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_regular_keeps_report_dir\fP (self)"
.br
.ti -1c
.RI "def \fBtest_clear_deletes_report_dir\fP (self)"
.br
.ti -1c
.RI "def \fBtest_clear_keeps_report_dir_when_asked\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file test_from_cdb\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.OutputDirectoryTest\&.test_clear_deletes_report_dir ( self)"

.PP
Definition at line 43 of file test_from_cdb\&.py\&.
.PP
.nf
43     def test_clear_deletes_report_dir(self):
44         with libear\&.TemporaryDirectory() as tmpdir:
45             cdb = prepare_cdb('clean', tmpdir)
46             exit_code, reportdir = run_analyzer(tmpdir, cdb, [])
47             self\&.assertFalse(os\&.path\&.isdir(reportdir))
48 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.OutputDirectoryTest\&.test_clear_keeps_report_dir_when_asked ( self)"

.PP
Definition at line 49 of file test_from_cdb\&.py\&.
.PP
.nf
49     def test_clear_keeps_report_dir_when_asked(self):
50         with libear\&.TemporaryDirectory() as tmpdir:
51             cdb = prepare_cdb('clean', tmpdir)
52             exit_code, reportdir = run_analyzer(tmpdir, cdb, ['--keep-empty'])
53             self\&.assertTrue(os\&.path\&.isdir(reportdir))
54 
55 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.
.SS "def tests\&.functional\&.cases\&.test_from_cdb\&.OutputDirectoryTest\&.test_regular_keeps_report_dir ( self)"

.PP
Definition at line 37 of file test_from_cdb\&.py\&.
.PP
.nf
37     def test_regular_keeps_report_dir(self):
38         with libear\&.TemporaryDirectory() as tmpdir:
39             cdb = prepare_cdb('regular', tmpdir)
40             exit_code, reportdir = run_analyzer(tmpdir, cdb, [])
41             self\&.assertTrue(os\&.path\&.isdir(reportdir))
42 
.fi
.PP
References tests\&.functional\&.cases\&.test_from_cdb\&.prepare_cdb(), tests\&.functional\&.cases\&.test_from_cdb\&.run_analyzer(), and libear\&.TemporaryDirectory()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
