.TH "tests.unit.test_report.GetPrefixFromCompilationDatabaseTest" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_report.GetPrefixFromCompilationDatabaseTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_with_different_filenames\fP (self)"
.br
.ti -1c
.RI "def \fBtest_with_different_dirnames\fP (self)"
.br
.ti -1c
.RI "def \fBtest_no_common_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBtest_with_single_file\fP (self)"
.br
.ti -1c
.RI "def \fBtest_empty\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file test_report\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_report\&.GetPrefixFromCompilationDatabaseTest\&.test_empty ( self)"

.PP
Definition at line 146 of file test_report\&.py\&.
.PP
.nf
146     def test_empty(self):
147         self\&.assertEqual(
148             sut\&.commonprefix([]), '')
149 
.fi
.SS "def tests\&.unit\&.test_report\&.GetPrefixFromCompilationDatabaseTest\&.test_no_common_prefix ( self)"

.PP
Definition at line 138 of file test_report\&.py\&.
.PP
.nf
138     def test_no_common_prefix(self):
139         self\&.assertEqual(
140             sut\&.commonprefix(['/tmp/abs/a\&.c', '/usr/ack/b\&.c']), '/')
141 
.fi
.SS "def tests\&.unit\&.test_report\&.GetPrefixFromCompilationDatabaseTest\&.test_with_different_dirnames ( self)"

.PP
Definition at line 134 of file test_report\&.py\&.
.PP
.nf
134     def test_with_different_dirnames(self):
135         self\&.assertEqual(
136             sut\&.commonprefix(['/tmp/abs/a\&.c', '/tmp/ack/b\&.c']), '/tmp')
137 
.fi
.SS "def tests\&.unit\&.test_report\&.GetPrefixFromCompilationDatabaseTest\&.test_with_different_filenames ( self)"

.PP
Definition at line 130 of file test_report\&.py\&.
.PP
.nf
130     def test_with_different_filenames(self):
131         self\&.assertEqual(
132             sut\&.commonprefix(['/tmp/a\&.c', '/tmp/b\&.c']), '/tmp')
133 
.fi
.SS "def tests\&.unit\&.test_report\&.GetPrefixFromCompilationDatabaseTest\&.test_with_single_file ( self)"

.PP
Definition at line 142 of file test_report\&.py\&.
.PP
.nf
142     def test_with_single_file(self):
143         self\&.assertEqual(
144             sut\&.commonprefix(['/tmp/a\&.c']), '/tmp')
145 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
