.TH "thread_info" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "const char ** \fBargv\fP"
.br
.ti -1c
.RI "int \fBresult\fP"
.br
.ti -1c
.RI "int(* \fBmain_func\fP )(int \fBargc\fP, const char **\fBargv\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file c\-arcmt\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "int thread_info::argc"

.PP
Definition at line 93 of file c\-arcmt\-test\&.c\&.
.PP
Referenced by thread_runner()\&.
.SS "const char ** thread_info::argv"

.PP
Definition at line 94 of file c\-arcmt\-test\&.c\&.
.PP
Referenced by thread_runner()\&.
.SS "int(* thread_info::main_func) (int \fBargc\fP, const char **\fBargv\fP)"

.PP
Definition at line 4984 of file c\-index\-test\&.c\&.
.PP
Referenced by thread_runner()\&.
.SS "int thread_info::result"

.PP
Definition at line 95 of file c\-arcmt\-test\&.c\&.
.PP
Referenced by thread_runner()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
