.TH "/Users/maximilian/clang-llvm/clang/tools/clang-refactor/ToolRefactoringResultConsumer.h" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maximilian/clang-llvm/clang/tools/clang-refactor/ToolRefactoringResultConsumer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'clang/AST/ASTContext\&.h'\fP
.br
\fC#include 'clang/Tooling/Refactoring/RefactoringResultConsumer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBclang::refactor::ClangRefactorToolConsumerInterface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBclang\fP"
.br
.RI "-rename "
.ti -1c
.RI " \fBclang::refactor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
