.TH "VisitorData" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisitorData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CXTranslationUnit \fBTU\fP"
.br
.ti -1c
.RI "enum CXCursorKind * \fBFilter\fP"
.br
.ti -1c
.RI "const char * \fBCommentSchemaFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1290 of file c\-index\-test\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* VisitorData::CommentSchemaFile"

.PP
Definition at line 1293 of file c\-index\-test\&.c\&.
.SS "enum CXCursorKind* VisitorData::Filter"

.PP
Definition at line 1292 of file c\-index\-test\&.c\&.
.SS "CXTranslationUnit VisitorData::TU"

.PP
Definition at line 1291 of file c\-index\-test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
